nats-io/nats-server

- .goreleaser.yml
Resolves #
release support mips64le
add mips64le arch to release package
-
-
-
Signed-off-by: duchuanLX duchuan@loongson.cn
> [ADDED] release support mips64le

- server/jetstream_cluster_test.go
Same argument as yesterday for `waitOnStreamCurrent`. 
I noticed `TestNoRaceJetStreamClusterStreamCreateAndLostQuorum` fail on travis.
So I ran it locally 300 times.
While doing so I had the timeout of waitOnClusterReady set to 20 seconds (from 10 seconds).
Out of 300 tests, 15 only passed because of the increased timeout. 
```
> grep RUN testout | wc -l
300
> grep "[(].....s[)]" testout -o | wc -l
15
> grep "[(].....s[)]" testout -o
(10.26s)
(12.50s)
(10.80s)
(11.09s)
(11.21s)
(12.63s)
(15.58s)
(11.98s)
(14.06s)
(12.85s)
(14.56s)
(10.38s)
(11.01s)
(11.37s)
(11.12s)
>
```
> Increasing the timeout of waitOnClusterReady

- server/jetstream_cluster_test.go
Bumping to 20 for the same reason as the others.
Ran 100 tests and 16 would have failed without the increased timeout.
I believe that in this unit test we should wait longer as we remove a server from js.
```
> grep RUN testout | wc -l
100
> grep -e "[(][6789]" -e "[(]1[0-9]" testout | wc -l
16
> grep -e "[(][6789]" -e "[(]1[0-9]" testout
--- PASS: TestJetStreamClusterRemovePeer (6.08s)
--- PASS: TestJetStreamClusterRemovePeer (9.90s)
--- PASS: TestJetStreamClusterRemovePeer (7.64s)
--- PASS: TestJetStreamClusterRemovePeer (11.88s)
--- PASS: TestJetStreamClusterRemovePeer (8.57s)
--- PASS: TestJetStreamClusterRemovePeer (10.13s)
--- PASS: TestJetStreamClusterRemovePeer (7.98s)
--- PASS: TestJetStreamClusterRemovePeer (8.15s)
--- PASS: …
```
> Increasing test timeout

- server/jetstream.go
When re-enabling a JS server that got auto shutdown due to reaching an invalid state, sending HUP while still being in the invalid state could 'brick' JS for an account (for example due to a file system issue):
```
[85085] 2021/03/10 01:37:38.220246 [ERR] JetStream out of space, will be DISABLED
[85085] 2021/03/10 01:37:38.475190 [INF] Initiating JetStream Shutdown...
[85085] 2021/03/10 01:37:38.477821 [INF] JetStream Shutdown
[85085] 2021/03/10 01:38:17.746407 [INF] Reloaded: jetstream
[85085] 2021/03/10 01:38:17.746422 [INF] Restarting JetStream
[85085] 2021/03/10 01:38:17.746471 [WRN] Can't start JetStream: storage directory is not writable
[85085] 2021/03/10 01:38:17.746720 [INF] Reloaded server configuration
```
Then from the natscli would always get the following 503:
```
nats: …
```
> Disable JS on restart if on invalid state

- server/const.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/norace_test.go
- server/stream.go
This PR changes our behaviors for streams and peer removals in several ways.
First we no longer try to auto-remap stream assignments on peer removals from the system.
We also now can always respond to stream info requests if at least a member is running.
So when a stream loses quorum, either for simple server down or automated peer removals like out of disk storage, the streams are still visible and operators can remove the peer assignments for the stream manually.
> Lost quorum changes for streams

- server/jetstream_cluster_test.go
- server/norace_test.go
- server/raft.go
When a new leader is elected it has to give everyone a chance to reply,
so that we can observe rejections with higher term.
The maximum election timeout is 7.5 seconds.
The new behavior of waiting for the election timeout caused unit tests
to fail. Hence upping the timeout there as well.
Unit test wise this might cause more failures due to the altered timing. (only ran locally so far)
I am also missing the knowledge to implement the TODO that I added. 
But if we could, this would speed things back up for cases where the leader does not change.
> Fixed a quorum formation issue that caused truncation

- server/jetstream.go
- server/reload.go
Allow disable/re-enable JS at runtime with HUP.
```
[1717] 2021/03/12 09:44:12.370469 [INF] Using configuration file: my.conf
[1717] 2021/03/12 09:44:12.371519 [INF] Starting JetStream
[1717] 2021/03/12 09:44:12.371882 [WRN]     _ ___ _____ ___ _____ ___ ___   _   __  __
[1717] 2021/03/12 09:44:12.371889 [WRN]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[1717] 2021/03/12 09:44:12.371894 [WRN] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[1717] 2021/03/12 09:44:12.371897 [WRN]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[1717] 2021/03/12 09:44:12.371900 [WRN] 
[1717] 2021/03/12 09:44:12.371905 [WRN]       https://github.com/nats-io/jetstream
[1717] 2021/03/12 09:44:12.371908 [INF] 
[1717] 2021/03/12 09:44:12.371910 [INF] ---------------- JETSTREAM ----------------
[1717] …
```
> reload: Allow re-enabling JS after it was disabled

- server/consumer.go
- server/jetstream_cluster_test.go
Watch for interest loss across GWs so ephemeral consumers are removed
when there is no longer local and GW interest.
> Ephemeral cleanup across GWs

- server/events_test.go
- server/gateway.go
- server/gateway_test.go
Also fixed a test that would sometimes fail depending on timing.
> [CHANGED] Move Gateway interest-only mode switch from INF to DBG

- server/events.go
- server/jetstream.go
- server/reload.go
Fixes the following issue that occurs during reload after JS got disabled:
```
[88019] 2021/03/14 14:37:36.994423 [DBG] Starting metadata monitor
[88019] 2021/03/14 14:37:36.994490 [ERR] Error setting up jetstream service imports for account: service import not authorized
[88019] 2021/03/14 14:37:36.994497 [INF] Reloaded server configuration
```
> Fix for JS reload and exports

- server/stream.go
> Don't set to nil on stop to avoid any panics accessing that map.

- server/monitor.go
What it used to look like:
```
"jetstream": {
"config": {
"max_memory": 0,
"max_storage": 0
},
"stats": null
},
```
What this will be now 
```
"jetstream": {},
```
Test
```
> nats-server -m 5222 &
[1] 84077
[84077] 2021/03/15 16:02:38.676376 [INF] Starting nats-server
[84077] 2021/03/15 16:02:38.676616 [INF]   Version:  2.2.0
[84077] 2021/03/15 16:02:38.676627 [INF]   Git:      [not set]
[84077] 2021/03/15 16:02:38.676737 [INF]   Name:     NDQKXZJBFFVO3XUIWIEXVBI3CWTDIIT3PP7DORBGNCG5Y5UZQB4FHQQN
[84077] 2021/03/15 16:02:38.676747 [INF]   ID:       NDQKXZJBFFVO3XUIWIEXVBI3CWTDIIT3PP7DORBGNCG5Y5UZQB4FHQQN
[84077] 2021/03/15 16:02:38.678096 [INF] Starting http monitor on 0.0.0.0:5222
[84077] 2021/03/15 16:02:38.678295 [INF] Listening for client …
```
> Suppress varz jetstream output if not enabled

- server/filestore.go
- server/jetstream.go
> Fix for #2011 and atomics on 32bit systems.

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
> When a stream is a mirror or has sources we need to check the upstream streams.

- server/filestore.go
- server/stream.go
Updates to memory pressure.
1. Release cache during heavy writes when we move to a new block if no read activity.
2. If we detect a linear scan reading dump the cache on the last seq read for the mb.
> Updates to memory retention in filestore.

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_test.go
1. Reduce maximum sliding window for large N->1.
2. Do not create any store for directs.
3. Relax hard requirement for interest at creation for directs.
> Direct consumer updates.

- server/gateway.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/monitor.go
This prevents possible double adds under reload or restart scenarios.
> Make sure the jetstream accounts use the name as the key to the map.

- server/const.go
- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
Remove another possible wire blocking operation in raft.
> Reduce sliding window for direct consumers and catchup stream windows.

- server/jwt.go
This broke due to the RC portion 2.2.1.RC1 without -
old code assumed - as separator between version and RC
> [fixed] version parsing issue that got tripped by extra .

- .github/workflows/nightly.yaml
goreleaser now only function with GO111MODULES on, as will
much of the go eco system soon and we will need to move also.
For now use a version that still supports it
> fix nightly builds

- server/const.go
- server/jetstream_cluster.go
- server/jwt_test.go
- server/memstore.go
We had lock inversion with consumers. Not best solution but good for now.
> Calling out to the storage update should not hold lock.

- server/client.go
- server/leafnode.go
- server/leafnode_test.go
- server/websocket.go
- server/websocket_test.go
- It was possible that when the server was sending frames to a
webbrowser, it would send empty frames. While technically not wrong,
prevent that from happening.
- Not copying enqueued buffers could cause corruption with LN+WS.
> [FIXED] Websocket: do not generate empty frames + LN corruption

- server/auth.go
- server/leafnode_test.go
- server/opts.go
This broke the setup in such a way that any connect relying on this would have failed.
This also fixes an issue where specifying no account did not result in using $G.
> [fixed] issue where verify_and_map: true in leaf node config was not used

- server/jetstream_api.go
- server/jetstream_cluster_test.go
This change collects prefixes from mirror or sources, then checks them against collected subjects.
This does not work if the streams are in different accounts.
I can look into adding that as well. 
Just haven't yet as I was unsure why it was not done already.
Should I add it?
I am also wondering if this (already  present) check should be done for Sources as well? (since I added code to obtain the stream config there as well)
```
if exists && cfg.MaxMsgSize > 0 && maxMsgSize > 0 && cfg.MaxMsgSize < maxMsgSize {
resp.Error = &ApiError{Code: 400, Description: "stream mirror must have max message size >= source"}
s.sendAPIErrResponse(ci, acc, subject, reply, string(msg), s.jsonResponse(&resp))
return
}
```
> [Added] error when mirror/source stream prefix overlaps with stream subs

- server/server.go
Fixes race with account client map.
```
=== RUN   TestJetStreamOperatorAccounts
Write at 0x00c002a482b8 by goroutine 146:
github.com/nats-io/nats-server/server.(*Server).registerAccountNoLock()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1240 +0x71e
github.com/nats-io/nats-server/server.(*Server).registerAccount()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1207 +0x5c
github.com/nats-io/nats-server/server.(*Server).fetchAccount()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1410 +0x10c
github.com/nats-io/nats-server/server.(*Server).lookupAccount()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1291 +0x30d …
```
> Guard account client map

- server/websocket.go
When a random port is selected (likely in tests), the banner would
print the port as `0` instead of its real value.
> [FIXED] Websocket: print correct random port instead of `0`

- server/jetstream_cluster.go
```
[4295] 2021/03/31 19:08:52.377093 [WRN] Account [AAODZMQUUPCOJW7RG7FJWR5FGZJE45GXHPUH45ZYFJGHMOQXMLBHPOQY] lookup for consumer create failed: fetching jwt timed out
```
> [Fixed] missing unlock and added a warning trace

- server/jetstream_api.go
> Fix for #1976

- server/const.go
- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
When publishing and receiving from a stream concurrently performance was hindered due to aggressive cache expiration.
> Aggressive cache expiration was hindering performance

- server/accounts.go
- server/const.go
- server/jwt_test.go
- server/opts.go
Just in case as per our conversation
The change in signature to NewCacheDirAccResolver and NewDirAccResolver are backwards compatible.
I left URLAccResolver unchanged for now.
The resolver being public, made this a little more involved
> [Adding] (fetch) timeout to nats resolver

- server/client.go
- server/client_test.go
Resolves #
- substitute switch-case with map in the `typeString` function.
> put typestring to map and add tests

- server/leafnode.go
- server/leafnode_test.go
- server/route.go
If leafnodes from a cluster were to reconnect to a server in
a different cluster, it was possible for that server to send
to the leafnodes some their own subscriptions that could cause
an inproper loop detection error.
There was also a defect that would cause subscriptions over route
for leafnode subscriptions to be registered under the wrong key,
which would lead to those subscriptions not being properly removed
on route disconnect.
Finally, during route disconnect, the leafnodes map was not updated.
This PR fixes that too.
> [FIXED] Leafnode: incorrect loop detection in multi-cluster setup

- server/errors.go
- server/reload.go
- server/server.go
This happened when a dummy (expired/incomplete) account was created during
a route operation. The dummy was to avoid fetching the account, which would
cause a lock inversion.
When a non route request required the account, we'd download it as it is
set to expired.
A concurrent request would result in ErrAccountResolverSameClaims which
the caller did not handle.
Fix is to remove ErrAccountResolverSameClaims.
> [fixed] issue with concurrent account fetch when account was incomplete

- logger/log_test.go
- server/configs/cluster.conf
- server/configs/js-op.conf
- server/configs/test.conf
- server/dirstore_test.go
- server/filestore_test.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/jwt_test.go
- server/leafnode_test.go
- server/log_test.go
- server/opts_test.go
- server/reload_test.go
- server/routes_test.go
- server/server_test.go
- test/pid_test.go
- test/ports_test.go
- test/routes_test.go
- test/test.go
- test/tls_test.go
Currently, temporary test files and directories are written to lots of different paths within the OS's temp dir. This makes it hard to know which files are from nats-server and which are unrelated. This in turn makes it hard to clean up nats-server test files.
Instead, this change puts temporary test files into two directories:
* TMPDIR/nats - used to test defaults
* TMPDIR/nats-server - used repo name to hold everything else
**Before change** - After 1 `go test ./...` (every subsequent test run grows the number of files in this directory):
```
$ ls /tmp
173187694  758384159           jetstream222581463  jetstream731178586      nats
275273063  770437285           jetstream297313931  jetstream921343952      v1cWZsv
282940336  804279746           jetstream360981205  jetstream941867353 …
```
> Consolidate temporary test files and directories

- server/websocket.go
- server/websocket_test.go
Although we do not support websocket configuration changes, we usually
try to support changes to TLS certificates, etc..
The way websocket is handled (using an http server), the TLS config
was given on startup and updates following a configuration reload
would not be reflected.
Using a tls.Config function that allows passing the tls config
prior to handshake seem to workaround this issue.
I have added a test that demonstrate that the TLS configuration
is really updated after the reload.
> [FIXED] Websocket: TLS configuration not updated on reload

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/memstore.go
- server/store.go
- server/stream.go
> Optimize startup for filtered consumers when creating pending count.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
We expected an account load to not fail but this is possible with resolvers.
If we can not load the account report back to the metaleader the error.
Consumers overlay the same peer group and need to exist prior, so I believe we only need to check on creating a stream, not on update or creating a consumer.
> Report an error if we fail to load an account on a stream assignment.

- server/filestore.go
- server/filestore_test.go
> Fix bug that could cause panic and corruption on filestore compact.

- server/client.go
- server/server.go
Resolves #
- Extract server updates functionality into function
> extract_server_update

- server/auth.go
- server/client.go
> expose the connection kind to CustomClientAuthentication

- server/consumer.go
- server/jetstream_cluster_test.go
> Fix for #2083

- server/opts_test.go
- server/routes_test.go
This was introduced by PR #2071.
On some tests, options are loaded based on a config file that has
the pid set to "/tm/nats-server/nats-server.pid", however, the
expected option's pid path was set based on tmpRoot. The problem
is that on macOS, that value would be "/var/folders/xxx" which
would not match.
So this PR simply reverts the changes to the expected pid file
name: it simply needs to match was in the test.conf file.
> Fixed expected pid path in options

- server/leafnode.go
- server/leafnode_test.go
We were setting the ping timer in the accepting server as soon
as the leafnode connection is created, just after sending
the INFO and setting the auth timer.
Sending a PING too soon may cause the solicit side to process
this PING and send a PONG in response, possibly before sending
the CONNECT, which the accepting side would fail as an authentication
error, since first protocol is expected to be a CONNECT.
Since LeafNode always expect a CONNECT, we always set the auth
timer. So now on accept, instead of starting the ping timer just
after sending the INFO, we will delay setting this timer only
after receiving the CONNECT.
The auth timer will take care of a stale connection in the time
it takes to receives the CONNECT.
> [FIXED] LeafNode: set first ping timer after receiving CONNECT

- server/client.go
- server/leafnode.go
- server/server.go
- test/gateway_test.go
- test/leafnode_test.go
- test/test.go
On connect all subscription where sent by the soliciting leaf node.
If creds contains sub deny permissions, the leaf node would be
disconnected.
This waits for the permissions to be exchanged and checks permissions
before sending subscriptions.
split up leafNodeFinishConnectProcess into two functions.
When expecting multiple messages in a row, use a buffer to store everything after the left most match.
This can be used a lot more. But there are unrelated tests that rely on the old behavior. (will address separately)
> [Fixed] leaf node subscription permission negotiation.

- server/auth_test.go
- server/filestore_test.go
- server/gateway_test.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/leafnode_test.go
- server/monitor_test.go
- server/mqtt_test.go
- server/raft.go
- server/server_test.go
- server/test_test.go
- server/websocket_test.go
- test/leafnode_test.go
- test/system_services_test.go
This runs `gofmt -s -w .` at the root of this repo. `gofmt` is part of the default Go distribution and it's what `go fmt` runs under the hood.
> Run gofmt -s to simplify code

- server/events.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/route.go
- server/server.go
1. When in mixed mode and only running the global account we now will check the account for JS.
2. Added code to decrease the cluster set size if we guessed wrong in mixed mode setup.
> Mixed mode improvements.

- server/filestore.go
- server/filestore_test.go
Signed-off-by: Derek Collison derek@nats.io
> Partial fix for #2068

- server/signal.go
Before 2.2 series, the TERM signal used to not be handled by the server, so it would not have been a clean exit. In 2.2, it was changed to process TERM signal as a clean exit but this affects the behavior of some tools that were expecting TERM to be exit 1.
> Make TERM exit 1 as pre v2.2 series

- server/client.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
This PR improves the setup that has a remote leafnode cluster extending a cluster or supercluster and the JetStream domain. We want to ensure the remote cluster places correctly and does not try to elect its own leader.
> Improve JS when a leafnode cluster extends and shares a system account.

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
This fixes that scenario by detecting the situation and inserting skip msgs to catch up.
> Mirrors failed when upstream messages had expired.

- server/norace_test.go
- server/stream.go
> Allow control messages like heartbeats to pass the old sub test.

- server/jetstream_cluster_test.go
Currently, TestJetStreamClusterMirrorExpirationAndMissingSequences calls
FailNow from the parent test when a subtest fails. This causes an error.
This change calls FailNow to fail the subtest from the subtest itself.
Fixes this error in CI:
```
Error:     testing.go:1103: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestJetStreamClusterMirrorExpirationAndMissingSequences (7.49s)
```
> Fix calling FailNow in parent test

- server/jetstream_cluster_test.go
- server/raft.go
Under scenarios where peers would not be known prior to the metagroup leader being elected, they would artificially not be allowed to properly be added.
> Do not limit expansion of new peers

- server/filestore.go
- server/test_test.go
This fixes the issue of sometimes file descriptors remaining open after shutdown in tests. Also swaps order of cleaning up resource directory in cluster tests to prevent artifacts from previous tests remain in temp storage dir.
> js: msgblock close fix

- server/accounts.go
- server/client.go
- server/events_test.go
- server/gateway.go
- server/jetstream_api.go
- server/jwt_test.go
- server/route.go
> Do not propagate service import interest across GW and ROUTES

- server/accounts_test.go
- server/client.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/jwt_test.go
- server/leafnode_test.go
- server/opts_test.go
- test/tls_test.go
> Cleanup some tests + GetTLSConnectionState() race fix

- server/client.go
- server/leafnode.go
This was caused by not sending subs across leaf node connections in some
cases but sending unsub in all cases. This imbalance caused
subscriptions to go away too soon. (ref count was off)
The test TestJetStreamClusterInterestRetention failed locally for me, but that happened even without changes in this PR
```
client.go  (5 usages found)
closeConnection  (2 usages found) ---- added as part of PR
4585 srv.updateRouteSubscriptionMap(acc, sub, -1) . 
4606 srv.updateRouteSubscriptionMap(acc, esub.sub, -(esub.n))
processSubEx  (1 usage found) ---- does not call with client.kind LEAF
2437 srv.updateRouteSubscriptionMap(acc, sub, 1)
processUnsub  (1 usage found) ---- does not call with client.kind LEAF
2776 srv.updateRouteSubscriptionMap(acc, sub, …
```
> [fixed] sub issue across leaf node connections -  bad sub  ref count

- server/jetstream_cluster.go
- server/raft.go
If a subject in the system accounts leafnode deny_imports matches $NRG.>
then jetstream is explicitly disconnected and the server can become
leader.
> [fixed] only become observer if the leaf config has raft not restricted

- server/configs/js-op.conf
Currently, tests that use js-op.conf use dynamic JetStream limits,
calculated from the machine where the test is run. However, this file
also has an account JWT that requires an explicit amount of resources.
This causes some tests to pass on some machine, but not others.
This change explicitly declares the max storage and memory limits
JetStream requires to match the limits specified in the account JWT, so
that the host environment doesn't influence the tests.
tl;dr; Dynamic limits correctly determines MaxStore should be 2.75GB for my Linux laptop, but the account requires 10GB. This causes the test to fail. For `/tmp/nats/jetstream`, my laptop only has 3.8GB available because tmpfs is in memory, not disk.
> Declare required JetStream resources in test

- server/accounts_test.go
- server/gateway.go
- server/leafnode.go
- server/mqtt.go
- server/mqtt_test.go
- server/route.go
- server/routes_test.go
- server/server.go
- server/server_test.go
- server/service_test.go
- server/websocket.go
Currently, we use ReadyForConnections in server tests to wait for the
server to be ready. However, when this fails we don't get a clue about
why it failed.
This change adds a new unexported method called readyForConnections that
returns an error describing which checks failed. The exported
ReadyForConnections version works exactly as before. The unexported
version gets used in internal tests only.
Ulimit 256 too low error - before
```
panic: Unable to start NATS Server in Go Routine
```
Ulimit 256 too low error - with this change
```
panic: failed to be ready for connections after 10s: server(listen tcp 127.0.0.1:0: socket: too many open files)
```
At higher ulimit values, we still get the not ready panic, but for different
reasons.
Ulimit 65535 - before
```
panic: Unable to start NATS …
```
> Return not ready for connection reason

- server/server.go
This is benign as the inversion was between start and stop.
with this in place the race detector is happy on shutdown
> Fix account resolver lock ordering on shutdown

- server/const.go
- server/jetstream_cluster.go
New code dealing with concurrent consumer requests inadvertently broke tests that were restoring consumers with same config.
> Fix for consumer on restore being deleted

- server/jetstream.go
- server/raft.go
```
Write at 0x00c00050ae00 by goroutine 344:
github.com/nats-io/nats-server/v2/server.(*Server).setJetStreamDisabled()
/Users/secret/nats-dev/src/github.com/nats-io/nats-server/server/jetstream.go:289 +0xbb
github.com/nats-io/nats-server/v2/server.(*Server).DisableJetStream()
/Users/secret/nats-dev/src/github.com/nats-io/nats-server/server/jetstream.go:321 +0x76
Previous read at 0x00c00050ae00 by goroutine 61:
github.com/nats-io/nats-server/v2/server.(*raft).outOfResources()
/Users/secret/nats-dev/src/github.com/nats-io/nats-server/server/raft.go:467 +0xab
github.com/nats-io/nats-server/v2/server.(*raft).handleAppendEntry()
/Users/secret/nats-dev/src/github.com/nats-io/nats-server/server/raft.go:2300 +0x3c …
```
> Fix for data race when disabling JS running out of resources

- server/jetstream_cluster.go
In the case when raft layer can run for a bit as we exit the monitorStream that pulls from the apply channel make sure we drain that to prevent a lockup at the raft layer.
> Make sure to not have the raft layer block on apply channel on exit.

- server/mqtt.go
- server/mqtt_test.go
Websocket is currently not supported for MQTT clients. When a
client tries to connect with websocket protocol to the MQTT port,
the error message: `mid:9 - not connected` would be logged, which
is not really telling.
The server will now guess if the connection was websocket and report
a more appropriate error message, such as:
```
invalid connection, websocket currently not supported
```
Resolves #2126
> [IMPROVED] MQTT error message when client connects with websocket

- server/filestore.go
- server/jetstream.go
- server/raft.go
close temp files
signed by @scottf
> close temp files, fix path print

- server/client.go
Resolves #2082
- flushing outbound is not to block the client read loop
-
-
> [CHANGED] Flush in place only if producer and consumer are client connections

- server/jetstream_cluster_test.go
Locally had a crash in leader.JetStreamClusterPeers() where the first access to `s.mu` would crash.
Probably caused by leadership change between awaiting a leader and retrieving it.
Not worried about waiting forever as waitOnLeader will fail if there's none in time.
> fix unit test crashing when leader was nil caused by quorum reformation

- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
- server/opts_test.go
Currently, leafnode remote URLs are kept in order when parsed. This change randomizes the order of URLs by default and adds an option to disable this behavior, returning you to the way it was before.
```
leafnodes {
remotes = [
{
dont_randomize: true
url: [
"nats-leaf://host1:7422"
"nats-leaf://host2:7422"
"nats-leaf://host3:7422"
"nats-leaf://host4:7422"
]
account: fizzbuzz
credentials: "./fizzbuzz.creds"
}
]
}
```
Resolves #2153
> [CHANGED] Randomize Leafnode remote URLs and add option to disable

- server/jwt.go
- server/jwt_test.go
- server/leafnode_test.go
- server/server.go
Fixes #2160 
Will raise an error instead
Also noticed that s.Shutdown relied on s being not nil.
> [fixed] crash when using nats-resolver without system account

- server/dirstore_test.go
- server/jetstream_cluster_test.go
- server/jwt_test.go
- server/mqtt.go
- server/mqtt_test.go
In a setup with shared system account and a cluster of leaf nodes,
the JS requests did not contain the origin cluster, which caused
assets to possibly be created in the HUB. With this change, the
assets will be created in the origin cluster.
Also, removed use of acc.JetStreamEnabled() but instead fail
start of the server if mqtt is enabled in standalone mode and JS
is not enabled. If JS is enabled, we will get proper error if
account has no JS enabled.
> [FIXED] MQTT: asset placement in origin cluster

- server/client.go
GW Routed replies by default pin the map to the destination client connection. For internal callbacks, especially ones that use different internal clients for receiving versus sending the response we would not properly track these routed replies. If proper interest arrived after the request it could be lost.
> [FIXED] JetStream pull based message delivery could drop responses.

- server/client.go
- server/leafnode.go
- server/leafnode_test.go
- server/route.go
In a setup with a cluster of servers to which 2 different leaf nodes
attach to, and queue subs are attached to one of the leaf, if the
leaf server is restarted and reconnects to another server in the
cluster, there was a risk for an infinite message loop between
some servers in the "hub" cluster.
> [FIXED] Message loop with cluster, leaf nodes and queue subs

- server/opts.go
- server/opts_test.go
If running the server with command lines:
```
nats-server --tlsverify --tlscert "cert.pem" --tlskey "key.pem"
```
the default ciphers would not be set, however, they would using this
equivalent config:
```
tls: {
verify: true
cert_file: "cert.pem"
key_file: "key.pem"
}
```
Reported by @DavidSimner
> [FIXED] TLS: default ciphers not set when tls enabled from command line

- server/client.go
A custom authenticator can call `RegisterUser`, but the Username it sets on the 
User struct is never used, setting it here will allow a custom authenticator to declare
a username that will be seen in advisories, logs etc.
I am not sure if I should also do same for password - could not see any use case
for that but I am not super familiar with this code.
> allow custom authenticators to set a username

- server/auth.go
- server/client.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/leafnode.go
- server/server.go
We want to auto-suppress JetStream traffic on normal accounts when noticing the JetStream domain is extended.
We also now track remote accounts so that client info headers can be remapped if the accounts are different.
This PR does not have single leafnode as JetStream cluster extension yet.
> JetStream extended over a leafnode fixes.

- server/monitor.go
- server/monitor_test.go
> [FIXED] Getting varz from the http endpoint saw subscriptions always double for each fetch.

- server/mqtt.go
- server/mqtt_test.go
In cluster mode, a sub connects to server 1, another on server 2.
A publisher connects to server 2 and publishes a retained message.
If both subs restart they would properly receive the retained message.
However, if the publisher sens an empty message that "removes" the
retained message for this topic, and then consumer that connects to
server 1 restarts, it would not receive the retained message as it
should.
> [FIXED] MQTT retained message in cluster mode may not be delivered

- server/filestore.go
- server/filestore_test.go
We had issues of instability and incorrect behavior during concurrent operations.
This CL optimizes expiring msgs to be more efficient and hold the lock until completion.
Compact will also now hold the top level lock through completion.
> [IMPROVED] Stability when expireMsgs and writeMsg and Compact/Purge concurrent.

- go.mod
- go.sum
- server/jwt.go
- vendor/github.com/nats-io/jwt/v2/creds_utils.go
- vendor/github.com/nats-io/jwt/v2/header.go
- vendor/modules.txt
fixes #2069
The regex used by `nats-server` was missing `\r`. 
Instead of fixing it I started to use the same functionality from the jwt library.
That library had to change as it did not cope with eof...
So this updates the jwt library and uses it.
> [fixed] decorated jwt parsing issue by using same functionality of jwt

- server/accounts.go
- server/client.go
- server/gateway.go
- server/gateway_test.go
- server/mqtt.go
- server/mqtt_test.go
- server/server_test.go
Some issues that have been fixed would manifest by timeouts on
connect, unexpected memory usage on high publish message rate.
Some details:
- Replies were not always GW routed properly because we were looking
at the wrong connection's rsubs
- GW routed replies would not be found because they were tracked
in the subscription's client object, which may not be the same used
to send the reply
- Increased the mqtt timeout to wait for JS replies since in some
tests it was sometimes taking more than the original 2 seconds
- Incoming gateway messages destined for an MQTT internal subscription
may have been rejected as a no interest if the account had service imports
- Don't use time.After(), instead create explicit timer so it can
be stopped when not timing out.
- Unnecessary copy of a slice …
> [FIXED] MQTT fixes and improvements

- server/mqtt.go
At the time where we need the domain to construct the session hash,
we have access to server options. So use that instead of storing
the domain in the internal mqtt structure.
> Don't need to store domain in mqttJSA structure

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
In certain scenarios a follower could get stuck in an endless loop trying to catchup because the leader would not send a snapshot when the log was empty and the requested sequence was exactly the first sequence of the log, which would be lastIndex+1 for a used but empty store.
> [FIXED] Raft groups could continually spin trying to catch up.

- server/events.go
```
> nats -s nats://admin:admin@localhost:4222 req '$SYS.REQ.SERVER.PING.JSZ' '{"domain":"leaf"}'
18:15:51 Sending request on "$SYS.REQ.SERVER.PING.JSZ"
18:15:51 Received on "_INBOX.VT8qToDYRhQEugeQoLnKqq.tN0mZqav" rtt 1.109964ms
{"data":{"server_id":"NAJPDFSKAT4QLMJHYPWYQZ3ENUNCNFEM2VUZQ2BHH4XG2XM3MVKQXVRD","now":"2021-05-07T22:15:51.795782Z","config":{"max_memory":51539607552,"max_storage":544531544064,"store_dir":"store_leaf_1/jetstream","domain":"leaf"},"memory":0,"storage":0,"api":{"total":0,"errors":0},"current_api_calls":0},"server":{"name":"leaf-server-1","host":"0.0.0.0","id":"NAJPDFSKAT4QLMJHYPWYQZ3ENUNCNFEM2VUZQ2BHH4XG2XM3MVKQXVRD","cluster":"leaf","ver":"2.2.3-beta.8","seq":17,"jetstream":true,"time":"2021-05-07T22:15:51.795797Z"} …
```
> [added] filter system requests by JS domain 

- server/jetstream.go
> Extend stream/consumer name validation to include more characters

- server/client.go
- server/jetstream_cluster_test.go
- server/test_test.go
When a response was needed from a leafnode cluster back to a hub, we had rules to disallow.
That rule was a bit dated and since we have cluster origin for leafnode clusters and that
is checked before the message is actually sent we could remove the old rule.
Resolves: #2205 
> [FIXED] Issue #2205

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_test.go
- server/monitor.go
- server/stream.go
We do not want to report direct consumers that were created for the purpose of sources or mirrors.
Resolves: #2213 
> [FIXED] #2213

- server/jetstream_cluster_test.go
- server/stream.go
> Fix stream source lookup and add in optional External to StreamSource

- server/jetstream.go
Jetstream movement can fail, so return that error and abort start-up if there's
a failure in moving precious data, rather than serve without it.
Create the jetstream directory if needed.
~~Create directories for private data mode 0750 not 0755.~~
This does not handle a directory layout made with 2.2.3, but does support a
2.2.2 to 2.2.4 migration.  The empty directories made under 2.2.3 will still
hinder the renames we do here.
- Create the jetstream dir if needed instead of assuming it exists
- Check for errors and return them
- ~~Use better permissions for jetstream storage~~
> Error-checking & resilience for JetStream move

- doc/adr/0004-nats-headers.md
Resubmission of the ADR edits with the specified clarifications as discussed with Colin and Ivan.
- Changed to be case-sensitive by default
- Removed all references to the Go implementation
- Clarified how append in a case-insensitive context should behave
[ci skip]
> clarified client operations to promote cross-client compatibility

- server/filestore.go
- server/filestore_test.go
> Bad redelivered values on consumer state should not panic.

- server/dirstore.go
- server/disk_avail.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_api.go
- server/stream.go
This did not work when using our default docker image which does not have /tmp by default.
> Fixed issue that we would stage snapshot restores in temporary storage.

- server/auth.go
- server/gateway.go
- server/leafnode.go
- server/mqtt.go
- server/opts.go
- server/opts_test.go
- server/reload.go
- server/server.go
- server/websocket.go
- test/tls_test.go
To create the hex(sha256(spki)) identifier:
openssl x509 -noout -pubkey -in certfile.pem | openssl pkey -pubin -outform DER | openssl dgst -sha256
> [added] pinned_cert option to tls block hex(sha256(spki))

- server/jetstream_api.go
addressed by failing
```
ats --context=hub s add --creds keys/creds/OP/IMPORTER/iuser.creds --mirror aggregate crosspassxxx
? Storage backend file
? Retention Policy Limits
? Discard Policy Old
? Stream Messages Limit -1
? Message size limit -1
? Maximum message age limit -1
? Maximum individual message size -1
? Replicas 1
? Adjust mirror start No
? Import mirror from a different JetStream domain No
? Import mirror from a different account Yes
? Foreign account API prefix  $JS.spoke-1.API
X Sorry, your reply was invalid: Value is required
? Foreign account delivery prefix ff
nats: error: could not create Stream: stream external api prefix " $JS.spoke-1.API" must be a valid subject without wildcards
```
> [fixed] issue with invalid api prefix for source/mirror

- server/client.go
- server/jetstream_cluster_test.go
We had a report of corrupt message payloads when going across leafnodes between streams that were sourced from one another.
We were incorrectly using the underlying buffer when a header already existed.
> Fix for corrupting a message when extending an existing header.

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
When we had a duplicate detected in R>1 mode we set the skip sequence indicator but were not using that when dealing with underlying store.
Resolves: #2242
> [FIXED] #2242.

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
> Fix for #2243. We were not allowing replicated acks processing for work queues.

- server/accounts.go
- server/jetstream.go
- server/server.go
fixed by moving setting of the mappings into a common function that is
also called when the jwt is updated
Below code would not receive a message without the change.
```
> [124] 2021/05/24 15:27:04.263472 [INF] Starting nats-server
[124] 2021/05/24 15:27:04.263663 [INF]   Version:  2.2.5
[124] 2021/05/24 15:27:04.263672 [INF]   Git:      [not set]
[124] 2021/05/24 15:27:04.263682 [INF]   Name:     s1
...
[124] 2021/05/24 15:27:04.267934 [INF] ---------------- JETSTREAM ----------------
[124] 2021/05/24 15:27:04.267954 [INF]   Max Memory:      48.00 GB
[124] 2021/05/24 15:27:04.267989 [INF]   Max Storage:     498.61 GB
[124] 2021/05/24 15:27:04.268022 [INF]   Store Directory: "store_server_1/jetstream"
[124] 2021/05/24 15:27:04.268033 [INF] …
```
> [fixed] deletion of js mappings on account jwt update

- server/auth.go
- server/client.go
- server/errors.go
- server/gateway.go
- server/leafnode.go
- server/mqtt.go
- server/reload.go
- server/route.go
- server/server.go
- test/tls_test.go
on reload clients with removed pinned certs will be disconnected.
The check happens only on tls handshake now.
> [changed] pinned certs to check the server connected to as well

- doc/adr/0007-error-codes.md
- server/errors.json
- server/errors_gen.go
- server/jetstream_errors.go
- server/jetstream_errors_generated.go
> Minor updates to error data

- server/pse/pse_darwin.go
This removes the dependency on `ps` and just uses rusage and sampling for percentage of cpu. We do not use virtual memory size in any of the upper layers.
> Remove external dependency on 'ps' for memory and cpu usage.

- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/leafnode.go
These changes are to properly allow a setup where a hub cluster has JetStream as a capability but an account does not.
We were incorrectly shutting things down via deny clauses when detecting the remote side/hub had JetStream capabilities.
This change moves that logic to the remote side and is signalled off the connect message which let's the remote side know
if the local leafnode account has JetStream enabled.
> Changes to leafnodes and JetStream

- server/jetstream_api.go
The addStream() can return an ApiErr but we did not handle
that leading to errors like 'stream name already in use (10058)' instead
of just 'stream name already in use' with the correct error code 10058 set
> ensure correct error handling in non clustered stream add

- server/client.go
- server/mqtt.go
- server/mqtt_test.go
The issue was that the subscription created for the MQTT client
was resulting in creation of a shadow subscription which did not
have the mqtt specific object attached, which would cause the
panic when accessing it in the sub's icb.
After that, it was discovered that the wrong subject was passed
to deliverMsg(), so fixed that too so that the icb callback gets
the proper transformed subject.
Resolves #2265
> [FIXED] MQTT: panic when using import/export

- server/leafnode.go
- server/leafnode_test.go
- server/opts_test.go
- server/reload.go
- server/reload_test.go
Issuing a configuration reload for a leafnode that has remotes
defined with remotes having more than 1 url could lead to a failure.
This is because we have introduced shuffling of remote urls but
that was done in the server's options object, which then would
cause the DeepEqual when diff'ing options to fail.
We move the suffling to the private list of urls.
The other issue was that the "old" remote option may not have
had a local account and it was not set to "$G", which could make
the DeepEqual fail.
Resolves #2273
> [FIXED] LeafNode config reload failed without any change made

- server/client.go
- server/consumer.go
- server/jetstream_cluster_test.go
- server/stream.go
We were seeing results where subject rewrite for JetStream was not working properly when the reply subject to a leafnode was a globally routed subject.
> [FIXED] Handling of subject rewrites for subjects to a globally routed subject.

- server/events.go
- server/jetstream.go
- server/jetstream_api.go
- server/monitor.go
This also removes iterating over all accounts for usage.
I Inlined `JetStreamStats` in order to have a similar layout to jsm, but can change that.
@ripienaar we had to leave out a few values as they required iterating over all accounts.
sample output single server no data 
```
{
"server": {
"cluster": "cluster-spoke-2",
"host": "localhost",
"id": "NCOWTDXMZW4XMV335NLVDXO3LHWGHB3G6UACJJ5PHH5I32QDHG5WBJLX",
"jetstream": true,
"name": "srv-4262",
"seq": 29,
"time": "2021-06-08T21:35:08.273028Z",
"ver": "2.2.6"
},
"statsz": {
"active_accounts": 3,
"connections": 1,
"cores": 16,
"cpu": 0.2,
"jetstream": {
"accounts": 3,
"api": {
"errors": 0,
"total": 0
},
"config": {
"domain": "spoke-2",
"max_memory": 51539607552,
"max_storage": 540083272704, …
```
> [adding] jetstream info to statsz

- server/accounts.go
- server/client.go
- server/leafnode.go
as a result of the issue, the leaf node connection never got created,
even after the account can be found.
Also tracing account id and name (when available)
```
[48700] 2021/06/08 15:02:46.327026 [INF] 127.0.0.1:4224 - lid:12 - Leafnode connection created for account: ACIB3OAWRMNK34DVSNYVQOEHH5RK7GNPHI7RPYZKVBX4UPD4262H2M2G/EXCACC
[48699] 2021/06/08 15:03:59.174597 [INF] 127.0.0.1:4224 - lid:10 - Leafnode connection closed: Server Shutdown account: ADXKBBHIU3HAY3VXAEETH3XSKQSFJ3YUH7NOBHGS5BN3K4SKNUNE7TUV/TEST
[48699] 2021/06/08 15:03:59.174824 [INF] 127.0.0.1:4224 - lid:11 - Leafnode connection closed: Server Shutdown account: ACIB3OAWRMNK34DVSNYVQOEHH5RK7GNPHI7RPYZKVBX4UPD4262H2M2G/EXCACC
[48699] 2021/06/08 15:03:59.175225 [INF] …
```
> [fixed] hanging leaf node connection when account can't be found

- server/events.go
- server/jetstream_cluster_test.go
- test/norace_test.go
This is generally useful but will also help with cli actions since we know from first response how many total responses are expected.
> Added active servers to statsz.

- server/opts.go
- server/reload.go
- test/ocsp_test.go
Allows configuration of OCSP mode and responder url via the config file if not present in the TLS cert:
```hcl
ocsp {
mode: must # always, never, auto
url: "http://ocsp.example.net"
}
```
By default, when ocsp is enabled it runs in `auto` mode but there are a few other different OCSP modes that control the behavior on whether OCSP should be enforced and server should shutdown if the cert runs with a revoked staple.
| Mode   | Description                                                           | Server shutdowns when revoked |
| --------- | ---- | ----- |
| auto   | Enables OCSP Stapling when it has the must staple/status_request flag | No                            |
| must   | Enables OCSP Staping when it has the must staple/status_request flag  | Yes                           |
| …
> ocsp: add more config options to customize OCSP

- server/gateway.go
- server/jetstream_cluster_test.go
When receiving a response across a gateway that has headers and a globally routed subject (_GR_) we were dropping header information.
> [FIXED] Headers were lost from a response across a GW and through a route.

- server/jetstream_cluster_test.go
- server/stream.go
When leader changes happened to streams that mirrored or sourced other streams we could continue to try to create consumers.
This could get excessive on a stream that has sourced many upstream origin streams and had several leader changes.
> [FIXED] Orphaned consumers on sourced or mirrored streams keep trying to create new ones.

- server/jetstream.go
- server/jetstream_cluster_test.go
- server/monitor.go
When checking limits we would check total ask against the server limits if limits were not set.
We were also dynamically setting account limits based on a single server limit.
> [FIXED] Dynamic account limits would limit based on single server limits.

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/norace_test.go
- server/store.go
- server/stream.go
Streams have always allowed multiple subjects however setting initial pending and selecting starting sequence number needed to be furthered optimized.
We also introduce per subject message limits.
> Adds in per subject tracking and limits for streams.

- server/accounts.go
- server/leafnode.go
- server/leafnode_test.go
A missing account on initial connect attempt caused the leaf node
connection to never be established.
An account service import subscription was not propagated along leaf
node connections.
I manually tested that this new behavior works.
I created issue #2289 to modify the unit test later. (discussed with Derek)
> [fixing] leafnode missing retry and service export interest propagation

- server/jetstream.go
obviously in the else condition config alway not nil ,so no need check
> remove config !nil check,beacuse the if branch is always not nil

- server/accounts.go
- server/client.go
- server/client_test.go
We could make it for all limits by having a map of error types
instead of applying just to max subs.
> [CHANGED] Reduce print for an account subs limit to every 2 sec

- server/route.go
- server/routes_test.go
This is a regression introduced in v2.2.6.
> [FIXED] Failed route TLS handshake would leave failed conn's lock, locked

- server/filestore.go
- server/norace_test.go
We optimized the filtered purge to skip msgBlks that are not in play.
Also optimized msgBlock buffer usage by using two sync.Pools to enhance reuse.
> Improvements to filtered purge and general memory usage for filestore.

- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
We did account for high level failure properly but were not properly accounting for low level store failures. When in clustered mode we need to account for the failure properly, and we use clfs for that, just needed updating on low level store failure.
> FIXED Clustered streams with seq mismatch state on store failures.

- server/filestore.go
> If dirty flag set always write consumer state.

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_test.go
When we created a filestore we would figure out if we should track by subject based on stream config.
This would cause bad results when a stream was updated to multiple subjects or wildcards.
This change tightens when and what we track per subject but turns it on all the time now, meaning we can update streams and track by subject behaviors will now work.
Resolves #2329 
> Fix for #2329.

- server/stream.go
> Check not really needed here, so removed

- server/const.go
- server/jetstream_test.go
- server/sendq.go
- server/stream.go
> Should not flush in place for stream loop.

- server/consumer.go
- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_errors.go
- server/jetstream_errors_generated.go
I wanted to supress some logging of consumer create
errors that just isn't needed and would be really
annoying on large networks, so I added many constants
and updated all errors.
I think only JSConsumerStoreFailedErrF is worth logging
on large networks else there would be quite a lot of
logs generated that one just cannot act on
> Add error codes for all consumer creation errors

- server/jetstream_cluster.go
- server/norace_test.go
- server/raft.go
Also put in safety for lag going upside down as well.
Resolves #2332 
> [FIXED] #2332 Peer info reports that had large last active values.

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
Will start the cleanup timer if no interest but allow creation.
> Make requirement for interest on creation of ephemerals soft vs hard.

- server/events.go
Was missing this one in the last PR.
In addition to that it also couldn't cope with an empty message
> [fixed] CONNS system endpoint which had issues with header and empty msg

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
Bug that did not limit ephemeral consumers when in clustered mode and with multiple concurrent requests.
> Fix for multiple concurrent ephemeral consumer requests with max consumers set.

- server/consumer.go
- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
Fix for a consumer's num pending being stuck at 1.
We were trying to protect the sgap uint64 from wrapping, but in some cases the consumers is eager and can get a message before we sgap++.
Instead of slowing things down and synchronizing ++ then --, we allow it to wrap temporarily and have and adjustedPending() func that will set to zero for reporting.
> [FIXED] Consumer NumPending bug

- server/jetstream_api.go
It was introduced by mistake in PR #2324 which I had reported
but failed to be actually removed before PR was merged:
https://github.com/nats-io/nats-server/pull/2324#pullrequestreview-695163635
> Removed debug.PrintStack() from apiDispatch [ci skip]

- server/configs/tls.conf
- server/opts.go
ran into trying to set with units this the other day.
didn't work and didn't cause an error, so made it work
> [fixed] tls timeout now accepts units

- server/const.go
changes this (account for creds has not been pushed):
```bash
nats --server localhost:4222 --creds ~/test/jetstream-leaf-nodes-demo/keys/creds/OP/NOPUSH/nopush.creds sub foo
nats: error: read tcp 127.0.0.1:49279->127.0.0.1:4222: i/o timeout, try --help
```
to that:
```bash
nats --server localhost:4222 --creds ~/test/jetstream-leaf-nodes-demo/keys/creds/OP/NOPUSH/nopush.creds sub foo
nats: error: nats: Authorization Violation, try --help
```
> [changed] default account fetch timeout to be smaller as client timeout

- server/accounts_test.go
- server/client.go
- server/sublist.go
fixes #2361
The subject used was not a subset of the import. Nor the other way
around. Instead it is an overlap that needs to be dynamically computed.
I added more unit tests for transforms and discovered another test involving ">".
Took care to not iterate over subj more often than necessary. 
Part of this was to support better re-use of tokenized subjects.
> [fixed] subscription on wildcard import that is not a subset

- server/fuzz.go
The OSS-fuzz coverage build is broken, but when applying the fixes on the OSS-fuzz side, a few conflicts come up. This PR fixes these conflicts.
> Change naming in server fuzzer

- server/accounts.go
- server/client.go
- server/consumer.go
- server/events.go
- server/events_test.go
- server/gateway.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/mqtt.go
- server/norace_test.go
- server/raft.go
- server/stream.go
When processing service imports we would swap out the accounts during processing.
With the addition of internal subscriptions and internal clients publishing in JetStream we had an issue with the wrong account being used.
This was specific to delayed pull subscribers trying to unsubscribe due to max of 1 while other JetStream API calls were running concurrently.
> Remove the swapping of accounts during processing of service imports.

- server/events.go
- server/leafnode.go
- server/leafnode_test.go
- server/route.go
- server/server.go
including domain in server info
adding check for cluster name in duplicate leaf node connection check
This does not address non unique domains in the same domain, say within super cluster.
---
By using the hash of the server name to compute a shortened identifier, jetstream introduced the need for unique server names (say across an entire super cluster)
```
node := string(getHash(si.Name))
s.nodeToInfo.Store(node, nodeInfo{si.Name, si.Cluster, si.ID, false, si.JetStream})
```
Short of changing how this key is computed, say by using a truncated server Id or the hash of domain+cluster+server. server names have to be unique. This change only addresses the need for unique server names across domains.
When this change is accepted, I'll add domain …
> [fixed] jetstream unique server name requirement across domains

- server/filestore_test.go
returning nil, nil
crash report indicates that state was nil.
looking at the memory store implementation, returning nil, nil seems legit, so the test needed to be fixed.
```
--- FAIL: TestFileStoreConsumerRedeliveredLost (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1169413]
goroutine 6977 [running]:
testing.tRunner.func1.2(0x137dbe0, 0x1b1c700)
/home/travis/.gimme/versions/go1.16.6.linux.amd64/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc000503200)
/home/travis/.gimme/versions/go1.16.6.linux.amd64/src/testing/testing.go:1146 +0x695
panic(0x137dbe0, …
```
> [fixed] crash in unit test caused by *ConsumerStore.State()

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
> Add descriptions to JetStream streams and consumers.

- server/consumer.go
- server/jetstream_test.go
A clustered consumer on an interest retention policy it could cause the server to panic when the consumer was being deleted.
> [FIXED] A stream with interest retention had a clustered consumer could cause server panic.

- .goreleaser-nightly.yml
- .goreleaser.yml
- docker/Dockerfile.nightly
This retains the symbols (but still removes the dwarf info).
This increases the executable size by ~8% (test on my laptop):
$ go build -ldflags '-w' -o nats-server
-rwxrwxr-x 1 yzhao yzhao 11911273 Jul 28 15:52 nats-server
$ go build -ldflags '-s -w' -o nats-server
-rwxrwxr-x 1 yzhao yzhao 11128832 Jul 28 15:52 nats-server
Symbols are very useful during debugging. It would be great that if the
NATS team consider including symbols.
Resolves #2366
> Remove '-s' flag from ldflags from the build

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
When a server was restarting, if a stream had a MaxAge configured and there were a very large amount of messages to expire, this process would take too long and delay the server reaching a running state.
This PR introduces an optimized expiration tailored for startup.
> [IMPROVED] Server restart time with many expired JetStream messages.

- server/events.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/leafnode.go
- server/reload.go
- server/route.go
- server/server.go
Allow non-JS leafnode(s) to access a HUB transparently. Also tests for mixed mode.
Mixed mode should always configure a JS block for the server and specify domain and disable the servers they do not want to do JS.
e.g. jetstream: {domain: "SPOKE", enabled: false}
Resolves #2388
-
-
-
> [FIX] #2388

- server/ocsp.go
- test/ocsp_test.go
When trying to update NATS Streaming server dependencies with
latest NATS Server, I noticed that a TLS test was failing and
this was because the TLS configuration was manually set like this:
```
o := DefaultTestOptions
o.HTTPHost = "127.0.0.1"
o.HTTPSPort = -1
o.TLSConfig = &tls.Config{ServerName: "localhost"}
cert, err := tls.LoadX509KeyPair("configs/certs/server-cert.pem", "configs/certs/server-key.pem")
if err != nil {
t.Fatalf("Got error reading certificates: %s", err)
}
o.TLSConfig.Certificates = []tls.Certificate{cert}
```
Notice how the `cert.Leaf` is not parsed. This cause the NATS Server
OCSP code to fail when hasOCSPStatusRequest() is invoked with
a `nil` pointer.
My first approach was to add a `nil` check in hasOCSPStatusRequest()
and return `false` in that case.
But then I …
> [FIXED] OCSP: parse cert.Leaf if not set

- server/jetstream_test.go
- server/server.go
- server/stream.go
When we would expire msgs we held the stream readlock and called down into consumers. If the stream was interest policy and we had unacked messages we would try to reacquire the stream readlock to check for any remaining interest. If someone tried to acquire the write lock in between, it would not be able acquire it, but that would cause the second read lock to also block leading to a deadlock.
Resolves #2403 
> [FIXED] Fix for #2403

- server/jetstream_cluster_test.go
- server/leafnode.go
Leafnodes with same domain and shared system account should behave like flat jetstream network.
Resolves #2401 
> [FIXED] #2401

- server/const.go
- server/opts.go
- server/opts_test.go
- server/routes_test.go
- server/server.go
This is related to PR #2407. Since the 64MB pending size is actually
configurable, we should fail only if max_payload is greater than
the configured max_pending. This is done in validateOptions() which
covers both config file and direct options in embedded cases.
The check in opts.go is reverted to max int32 since at this point
we don't know if/what max_pending will be, so we simply check
that it is not more than a int32.
For the next minor release, we could have another change that
imposes a lower limit to max_payload (regardless if max_pending
is higher).
> [CHANGED] Check that max_payload is not greater than max_pending

- server/filestore.go
- server/filestore_test.go
> [FIXED] #2417

- server/consumer.go
- server/errors_gen.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_errors.go
- server/jetstream_errors_generated.go
- server/jetstream_errors_test.go
- server/mqtt.go
- server/stream.go
Previously we had a few confusing functions like NewT
and similar that were quite fragile to use due to minimal
validation and a panic in go stdlib string Replacer.
Now we generate helper methods for every string, these
are used to access errors, fill in templates and conditional
returns of error type using the new Unless() option
We now get compile time errors for some common mistakes
and have better IDE helpers for arguments etc
> attempt to improve UX of the error system

- server/consumer.go
Explicitly sets MaxAckPending when not supplied to AckExplicit or AckAll, not just AckExplicit
> assign default to MaxAckPending when AckExplicit -or- AckAll

- server/jetstream_cluster_test.go
Realized that FC needed to be exported as well...
> fixed unit test to require fc export as well

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
This adds two items.
1. Domain information for PubAcks.
2. Active state for push consumers that details active subject and optionally queue group.
> JetStream additions

- server/norace_test.go
saw this in travis
```
=== RUN   TestNoRaceJetStreamClusterMirrorExpirationAndMissingSequences
norace_test.go:1980: Unexpected publish error: nats: timeout
--- FAIL: TestNoRaceJetStreamClusterMirrorExpirationAndMissingSequences (11.75s)
```
> Made test more predictable by waiting for leader after leader shutdown

- server/jwt_test.go
- server/leafnode.go
- server/leafnode_test.go
Fixes #2415. We did a set instead of merge.
changes in `jwt_test.go` are to make the `createUserWithLimit` usable by my new test.
> [fixed] issue where js overwrote leafnode remotes permissions from creds

- server/client.go
- server/jetstream_test.go
- server/norace_test.go
We were not properly unregistering from the account on cleanup.
> Fixed a leak of internal clients for JetStream consumers.

- server/leafnode.go
- server/leafnode_test.go
- server/websocket.go
If the remote did not have any TLS configuration, the URL scheme
"wss://" was not used as the indicating that the connection should
be attempted as a TLS connection, causing "invalid websocket connection"
in the server attempting to create the remote leafnode connection.
> [FIXED] LeafNode with "wss://.." url was not always initiating TLS

- server/accounts.go
- server/dirstore.go
- server/events.go
- server/jwt_test.go
- server/server.go
> Make sure jwt claim update does not wipe system imports

- server/accounts.go
- server/jwt_test.go
Updating the system account could wipe the account connz export.
> Added test for system account update as well

- server/leafnode.go
- server/leafnode_test.go
There are many examples in the documentation for one half of this configuration or the other,
but none which configure a leafnode remote on an operator-authenticated cluster.
The error "operator mode requires account nkeys in remotes." is not very clear or actionable.
It was only chance googling that led us to https://github.com/nats-io/k8s/pull/286 and gave us a hint about what we needed to do.
> [IMPROVED] Make error actionable when adding operator+leafnodes

- server/client.go
- test/leafnode_test.go
The PR #1480 was added in v2.2.0, so that matches user report that suggest that things changed compared to pre-2.2.0 releases.
The check for "pubAllowed" when client is a LEAF was added in that PR. Only the PUB permissions were checked regardless of the type of leaf connection (hub or spoke). In PR 1480, the check was done only for spoke but then was changed to perform pub check as long as client is LEAF: https://github.com/nats-io/nats-server/pull/1480/commits/3729552a37ba6141b8b5fba7d9fc3c1b1d654f2a
I think that we need to distinguish if the connection is hub, check subscribe permissions, if spoke, pub permissions. I have added a test that reproduces the user report `TestLeafNodeOperatorAndPermissions` that seem to be fixed with the proposed change.
Resolves #2454
Signed-off-by: Ivan …
> [FIXED] LeafNode: wrong permission check prevented message flow

- go.mod
- go.sum
- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/norace_test.go
- server/store.go
- server/stream.go
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/jsm.go
- vendor/modules.txt
> Improve file utilization when using a JetStream stream as a KV.

- server/consumer.go
- server/filestore_test.go
- server/store.go
This change was made in a previous PR wit this commit:
https://github.com/nats-io/nats-server/pull/2438/commits/9405b77e464dccf3be051b8c750a2354a088c5df
After some discussions, we agreed that the original approach
is best, so using a dedicated object SequenceInfo for ConsumerInfo.
> [CHANGED] ConsumerInfo's SequencePair replaced with SequenceInfo

- server/auth.go
- server/jwt.go
- server/jwt_test.go
- server/monitor.go
- server/opts.go
- server/opts_test.go
- server/server.go
option name: resolver_pinned_accounts
Contains a list of public account nkeys.
Connecting user of leaf nodes need to be signed by this.
The system account will always be able to connect.
> [added] operator option to ensure user are signed by certain accounts

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/monitor.go
The locking is jetStream->Server, not the otherway around. There
was few places where lock inversion could have caused deadlock.
Also, a change made recently to solve a deadlock was causing
a race that is demonstrated with TestJetStreamRaceOnRAFTCreate.
> [FIXED] JetStream: possible deadlock due to lock inversion

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
When we had partial state due to server failure or being shutdown ungracefully we could enter into a stream reset state.
The stream reset state is harsh but worked, however there was a bug that would not restart consumers that were attached.
Also if no state exists, or state was truncated, we can detect that and not go through a full reset.
> [FIXED] Issue #2397

- server/signal_windows.go
Since Go 1.14, close window event on windows becomes [SIGTERM](https://github.com/golang/go/commit/5d1a95175e693f5be0bc31ae9e6a7873318925eb) which we are currently not handling so becomes a non graceful exit that could be more difficult to recover from sometimes. With this change, it now catches the `terminated` signal so exits gracefully:
```
[12616] 2021/09/01 16:31:50.537622 [INF] Server is ready
[12616] 2021/09/01 16:32:03.179669 [DBG] Trapped "terminated" signal
[12616] 2021/09/01 16:32:03.180442 [INF] Initiating Shutdown...
[12616] 2021/09/01 16:32:03.181038 [INF] Initiating JetStream Shutdown...
[12616] 2021/09/01 16:32:03.181038 [INF] JetStream Shutdown
[12616] 2021/09/01 16:32:03.182625 [DBG] Client accept loop exiting..
[12616] 2021/09/01 16:32:03.182969 [DBG] SYSTEM - System …
```
> Handle SIGTERM on windows (close window event)

- server/const.go
- server/consumer.go
- server/jetstream_test.go
When expiring requests, the server would send 408 if interest was
still present, which can happen for pull subscribe implementations
that maintain interest for the duration of the pull subscription.
Let's keep the 408 for when a request is "force expired", that
is, a request was removed from the queue because it queue was
full but interest is still found.
> [FIXED] Pull requests: don't send 408 when request expires

- server/jwt_test.go
- server/opts.go
- server/reload_test.go
The RootCAs was not properly set, which could prevent the server
to create a TLS connection to the account resolver with an error
such as:
```
x509: certificate signed by unknown authority
```
Resolves #1207
> [FIXED] Account resolver TLS configuration

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
Also if we do not have room trap add peer and process there.
Also fixed a bug that would treat ephemerals the same as durables during remapping after peer removal.
> During peer removal, try to remap any stream or consumer assets.

- .travis.yml
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
Under load and pressure from concurrent publishing and consuming with multiple consumers the filestore would return a partial or no cache error to the upper layers. For consumers this could result in us skipping a stream sequence when we should not.
This change stabilizes the filestore and removes the flush state for msg blocks. I also found some bugs that did not track last sequence properly after snapshots / restore.
Also increased timeout under Travis for the Go tests. We were bumping up against the 10m default.
> Fixed a bug that could lead to perceived message loss under JetStream.

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
Fixed a bug when an interest retention stream with noack consumers is in clustered mode.
We were not properly propagating the ack state and proper cleanup of the stream messages.
Resolves #2488 (Related)
> [FIXED] - Message cleanup for interest stream and no-ack consumers in clustered mode.

- server/mqtt.go
- server/mqtt_test.go
- server/test_test.go
With the availability of a "max message per subject" for a given
stream, it is possible to replace individual streams that were
created per session with a single stream that gets all sessions
as a single message per subject, which subject is composed of
the session client ID hash.
The first time the new stream is created for a given account,
all existing MQTT session streams will be transferred to the
new mux'ed MQTT session stream.
> [IMPROVED] MQTT stream per session replaced with single stream

- server/filestore.go
- server/filestore_test.go
When we triggered a filestore msg block compact we were not properly dealing with interior deletes.
Subsequent lookups past the skipped messages would cause an error and stop delivering messages.
Resolves #2488 
> [FIXED] #2488

- server/jetstream_test.go
- server/mqtt.go
- server/stream.go
Feature request.
Resolves #2494
> Added ability to check if no message exists as a test to store the message.

- server/client.go
- server/events.go
- server/monitor.go
- server/mqtt.go
- server/mqtt_test.go
ClientID has been added to various monitoring objects. Also, added
the ability to filter connections on `client_id`.
On auth violation, the proper code was not invoked, which meant
that no disconnect event (with auth reason) would be published.
Resolves #2270
> [ADDED] Monitoring: ClientID (for MQTT clients) on connection events

- server/config_check_test.go
- server/opts.go
Authentication token has never been supported for cluster and
gateway (and leafnode). There is not even a Token option in
ClusterOpts or GatewayOpts.
However, the parsing of the configuration was not rejecting this
misconfiguration, making users believe that token was used for
authentication.
Documentation will also be fixed since it is reported there that
token is supported, which again, has never been the case.
> [FIXED] Report config error if "token" defined for cluster{} and gateway{}

- server/websocket.go
- server/websocket_test.go
> [FIXED] Websocket: possible panic when decoding CLOSE frame

- server/filestore.go
- server/norace_test.go
This could lead to the filtered subject state being incorrect.
> During compaction the cache may not be loaded completely

- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/stream.go
We use u16 to encode header len when replicating JetStream messages.
Make sure to error if we exceed that limit.
Resolves #2525 
> [FIXED] #2525

- util/nats-server-hardened.service
Resolves #
I'm working on adding a [NATS service to NixOS](https://github.com/NixOS/nixpkgs/pull/128189). During this process I found that the recommended systemd service definition does not contain any systemd hardening options. In NixOS more and more services have hardening options applied (where possible). Giving services the least amount of privileges makes sense to me.
This PR adds a second systemd service file that has hardening options applied. Tested this on my machine with basic pub/sub and with (JetStream) streams (to verify files can be accessed by NATS). Reason for adding a second file is to give users a choice between a bare-bones service definition or a hardened definition. Having the hardening options in this repo could also serve as documentation about the …
> Add hardened systemd service

- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/leafnode.go
- server/stream.go
Also added in optional Domain to StreamInfo.
> Fixed a condition where JetStream assets could be created in multiple leafnode domains.

- server/errors.json
- server/errors_gen.go
- server/jetstream_errors_generated.go
Fixes an error code that was added that left a big gap in numbers, this has
not been released so should be safe.
`nats errors add server/errors.json` will assist in picking the next number 
when adding errors
`go generate` will now fail on gaps
> fix error code for JSStreamHeaderExceedsMaximumErr

- server/jetstream_api.go
- server/mqtt.go
When a session record exists and is currently not connected, if
the user reconnects with the same client ID but with now the
clean flag set, we are required to clear the state. In earlier
implementation (where we were using a stream per session), we
were not deleting the stream to be created right away. Since now
we just have a message per session, it is ok to delete that
message when clearing the existing session that is going to be
replaced.
Also made apiDispatch execute in place for any connection that
is not ROUTER or GATEWAY.
> MQTT: delete the session record even on restart with clean flag

- server/client.go
- server/const.go
- server/events.go
- server/events_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/mqtt.go
This makes the behavior consistent with single server mode.
Resolves #2528
> Allow clustered JetStream to allow duplicate stream creation calls.

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
The server will now reject the creation of a push consumer with
flow control if no heartbeat is set.
Resolves #2520
> [CHANGED] JetStream: flow control requires heartbeats

- server/events.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
This change returns an info in those states now to better support client logic when binding consumers.
> [FIXED] ConsumerInfo in clustered mode during setup returned NotFound.

- server/const.go
- server/consumer.go
- server/jetstream_test.go
Thanks to @wallyqs for tracking down.
> Make large batch requests expire more efficiently.

- server/const.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/raft.go
- server/stream.go
See individual CLs.
Note coveralls still broke so that test on Travis always failing atm.
Resolves: #2544 
> Stabilize filestore, bug fixes, test tweaks.

- server/jetstream_test.go
- server/stream.go
> protect against negative dupe window via negative max age

- server/filestore.go
- server/jetstream_cluster.go
- server/memstore.go
- server/norace_test.go
- server/store.go
Replicated durable consumers that were backed by a memory store were bypassing snapshotting which also did compaction of the raft WAL.
This change adapts for memory store backed consumers by compacting the raft WAL directly on snapshot logic.
Resolves #2548 
> [FIXED] #2548

- server/const.go
- server/norace_test.go
- server/raft.go
When we stored a message in the raft layer in a wrong position (state corrupt), we would panic, leaving the message there.
On restart we would truncate the WAL and try to repair, but we truncated to the wrong index of the bad entry.
This change also includes additional changes to truncateWAL and also reduces the conditional for panic on storeMsg.
> Fix RAFT WAL repair.

- server/jetstream.go
- server/monitor_test.go
- server/reload.go
[fixed] reservations accounting issue on reload introduced by:
commit: bfb726e8e979e0b44497b34e54a6209174d1c14b
clearResources appeared to have been a workaround and broke
reload for non global accounts
As @ripienaar pointed out [here](https://github.com/nats-io/nats-server/pull/2539/files#r712878686), memory/storage in combination with dynamic accounts where cumbersome. 
So I added more values so to show how much of total usage accounted to accounts with reservations. 
If you want I can add another pair of values that are `totalused-reservedused`, but had a hard time finding a name for that.
When writing the unit test I noticed bad reservation values after a reload.
This was introduced by this …
> [added] value to JS stats showing memory used from accounts with reservations

- server/const.go
- server/consumer.go
- server/norace_test.go
- server/stream.go
Fix for deadlock with stream mirrors or sources where origin is interest or workqueue policy.
This would cause an interaction with channels and locks that could cause a deadlock.
> [FIXED] Deadlock with stream mirrors

- server/jetstream_api.go
We resused msg variable for both the request
and later the data loaded from the stream.
The data thus replaces the request and the audit
had the data as both request and response
> fixes the msg get audit event

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/stream.go
Sealed streams can not accept new messages, allow you to delete or purge messages, or have messages expire due to age.
Sealed stream can not be unsealed through an update.
> Allow streams to be sealed through a stream update.

- server/consumer.go
- server/jetstream.go
- server/jetstream_test.go
Replaced use of eventsEnabled() with EventsEnabled() that will
check under server lock. Also found another reference when
creating templates.
Resolves #2588
> [FIXED] JetStream: data race on shutdown

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
> Allow consumers to request only headers to be delivered

- server/mqtt.go
- server/mqtt_test.go
This way, any log statement for a client will include the client id,
similar to how the server now logs information about NATS clients
(such as language, version, connection name).
Also adding a debug statement once the client has successfully connected.
Here is how this will look like for a client with client id "client_0".
```
[69591] 2021/10/06 10:06:50.837977 [DBG] [::1]:57415 - mid:18 - Client connection created
[69591] 2021/10/06 10:06:50.839871 [DBG] [::1]:57415 - mid:18 - "client_0" - Client connected
[69591] 2021/10/06 10:07:00.627307 [DBG] [::1]:57415 - mid:18 - "client_0" - Client connection closed: Client Closed
```
All log statements will be affected, for instance here is an auth error:
```
[69591] 2021/10/06 10:09:48.618964 [DBG] [::1]:57424 - mid:23 - Client connection …
```
> [IMPROVED] MQTT: add client id to client connection string

- server/websocket.go
- server/websocket_test.go
The error message would now look like this:
```
[8672] 2021/11/01 10:56:50.251985 [ERR] [::1]:59279 - websocket handshake error: invalid value for header 'Upgrade'
```
(without this change the part `[::1]:59279 - ` would not be present)
> [IMPROVED] Websocket: Add client IP in websocket upgrade failures

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
When encountering errors for sequence mismatches that were benign we were returning an error and not processing the rest of the entries. This would lead to more severe sequence mismatches later on that would cause stream resets.
Also added code to deal with server restarts and the internal clfs fixup states which should have been reset properly.
Resolves #2666 
> [FIXED] Conditional failures for stream messages could cause stream resets #2666

- server/jetstream_api.go
- server/jetstream_cluster_test.go
Makes interactions with nats cli a bit better.
> Allow system account to respond with jetstream not enabled.

- server/jetstream_cluster_test.go
Ran this test 80 times locally. passed every single time
> fixed unit test where after a server shutdown no quorum existed

- server/accounts.go
- server/client.go
- server/const.go
- server/opts.go
- test/service_latency_test.go
The bug occurs when latency tracking is on, a requestor and responder are not connected to the same server, and the responder sends two responses for a single request.
> Fix for latency tracking bug.

- .travis.yml
- conf/fuzz.go
- logger/syslog.go
- logger/syslog_test.go
- logger/syslog_windows_test.go
- server/disk_avail.go
- server/disk_avail_openbsd.go
- server/disk_avail_windows.go
- server/fuzz.go
- server/norace_test.go
- server/pse/pse_freebsd.go
- server/pse/pse_rumprun.go
- server/pse/pse_windows.go
- server/pse/pse_windows_test.go
- server/service.go
- server/service_test.go
- server/signal.go
- server/signal_test.go
- server/sysmem/mem_bsd.go
- server/sysmem/mem_darwin.go
- server/sysmem/mem_linux.go
- server/sysmem/mem_windows.go
- server/sysmem/sysctl.go
- test/fanout_test.go
- test/norace_test.go
- Add Go 1.17
- Fix go fmt from Go 1.17 (build directives)
- Download version of misspell and staticcheck instead of doing
"go get" since current staticcheck would be broken without go.mod
> Travis updates

- server/nkey.go
- server/nkey_test.go
- server/opts.go
The nonce feature is useful to custom authentication plugins
but at present there is no way to enable a nonce to be presented
other than by setting nkey accounts etc.
This enables the nonce to always be presented in those situations.
Since its primarily useful to embedded scenarios there is no corresponding
configuration file behavior for this flag.
> support always presenting a nonce to clients

- scripts/cov.sh
Default of 10 minute (per package) seem to no longer be enough,
so bumping to 20 minutes, as it is on non code coverage runs.
> Bump tests code coverage timeout

- scripts/cov.sh
The "TestNoRace" can be very expensive memory/cpu wise.
When running test coverage, we do it with `-covermode=atomic` which is a bit similar to `-race` in that the runtime adds tracking that causes memory overhead. So we will remove those from code coverage.
It saves about 2min of running the code coverage tests by excluding those, but server package code coverage falls by a bit more than 1%.
> Remove TestNoRace tests from code coverage

- server/auth.go
- server/client.go
- server/server_test.go
> expose the nonce to custom authentication

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
> allow streams api to be filtered like list api

- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/norace_test.go
- server/stream.go
1. When a snapshot did not yield actionable data, we were not setting new last sequence if we have to readjust based on snapshot. This could lead to spinning on stream reset for followers.
2. When a stream has lots of failures by design, like KV abstraction, if we cleared the clfs state we would endlessly spin trying to reset the stream.
3. Also have better logging when we fail to decode a low level packet from the raft layer.
> Better handling for stream mismatch scenarios.

- go.mod
- go.sum
- server/auth.go
- server/client.go
- server/leafnode_test.go
- vendor/github.com/nats-io/jwt/v2/header.go
- vendor/github.com/nats-io/jwt/v2/signingkeys.go
- vendor/github.com/nats-io/jwt/v2/user_claims.go
- vendor/modules.txt
This was missing since WEBSOCKET allowed connection type is really
used for client connections.
If one wants to limit a configured user to leafnode connections,
including if the connection is over websocket, but does not
want an application to connect over websocket using this user,
this would have been impossible to configure.
The JWT library has been updated to add LEAFNODE_WS and MQTT_WS for
future work.
> [FIXED/CHANGED] Add leafnode websocket connection type

- server/stream.go
Tried to write several tests to re-create but believe this is very timing dependent. Based on excellent report I can track it down to the fix that is here, that one liner, but could not create a test to show behavior, but obvious that ssi was gone at that point and we did not check for nil.
Resolves #2708
> [FIXED #2708] Removing a source depending on timing could cause a server panic.

- server/events_test.go
- server/jetstream_cluster_test.go
- server/leafnode_test.go
- server/monitor_test.go
- server/server.go
- server/websocket.go
- server/websocket_test.go
When creating the http server, we need to provide a TLS configuration.
After a config reload, the new TLS config would not be reflected.
We had the same issue with Websocket and was fixed with the use
of tls.Config.GetConfigForClient API, which makes the TLS handshake
to ask for a TLS config. That fix for websocket was simply not applied
to the HTTPs monitoring case.
I have also fixed some flappers due to the use of localhost instead
of 127.0.0.1 (connections possibly would resolve to some IPv6 address
that the server would not accept, etc..)
> [FIXED] Monitoring: tls configuration not updated on reload

- server/leafnode.go
since no error was traced or the connection closed, subscriptions where
not forwarded
What caused the error on my end was the local accounts leaf node count.
Apparently, the count applies to leaf node connections accepted as well as initiated/connected. (See in the traces below.)
My expectation was that it only applies to accepted connections.
```
[30765] 2021/11/30 15:55:56.958332 [WRN] ACHE74YJWQW3MGM6KGYU4I7R37FWPI2VHR2ZVZTDURHRCXZFDIZOS3CN MaxTotalLeafNodesReached true
goroutine 1431 [running]:
runtime/debug.Stack()
/Users/matthiashanel/.gimme/versions/go1.17.darwin.amd64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/Users/matthiashanel/.gimme/versions/go1.17.darwin.amd64/src/runtime/debug/stack.go:16 +0x19 …
```
> hitting an account limit left an outgoing leaf node conn in bad state

- go.mod
- go.sum
- server/consumer.go
- server/filestore.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_test.go
- server/memstore.go
- server/mqtt.go
- server/raft.go
- server/raft_test.go
- server/sendq.go
- server/stream.go
- server/util.go
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/kv.go
- vendor/github.com/nats-io/nats.go/nats.go
- vendor/modules.txt
When a consumer is configured with "meta-only" option, and the
stream was backed by a memory store, a memory corruption could
happen causing the application to receive corrupted headers.
Also replaced most of usage of `append(a[:0:0], a...)` to make
copies. This was based on this wiki:
https://github.com/go101/go101/wiki/How-to-efficiently-clone-a-slice%3F
But since Go 1.15, it is actually faster to call make+copy instead.
> [FIXED] Corrupted headers receiving from consumer with meta-only

- server/jetstream.go
- server/jetstream_test.go
- server/stream.go
This will patch them on the fly during recovery. Specifically subjects with leading or trailing spaces and mirror streams with any subjects at all.
> There were situations where invalid subjects could be assigned to streams.

- server/server.go
Enables use of pprof to investigate server startup.
Co-authored-by: Ivan Kozlovic <ivan@synadia.com>
Signed-off-by: Ben Werthmann <ben@synadia.com>
> [CHANGED] Profiler: Start profile_port earlier

- server/jetstream_cluster.go
This is what is done in `jsClusteredStreamListRequest` as well
> Set incomplete error when cluster list fails

- server/client.go
- server/websocket.go
- server/websocket_test.go
This is for cases when there is a proxy (Nginx, HAProxy, etc..)
between the client and the NATS Server. If this header is present,
the first IP is the one of the originating client and will be
used as the host/IP in server's representation of the client host.
Resolves #2514
> [IMPROVED] Websocket: added client IP from X-Forwarded-For header

- server/auth.go
- server/client.go
- server/mqtt.go
- server/mqtt_test.go
- server/server_test.go
- server/websocket.go
- server/websocket_test.go
Clients will need to connect to the Websocket port and have `/mqtt`
as the URL path.
Resolves #2433
> [ADDED] MQTT: Support for Websocket

- server/filestore.go
- server/filestore_test.go
> [FIXED] JetStream: panic "could not decode consumer snapshot"

- server/jetstream_api.go
- server/jetstream_cluster.go
As per request from RI, removing the error we used to get.
Instead return no error but a list of missing items by name.
In below example, you see the missing entry at the end of the json file.
`"missing_consumer_names":["fail"]}`
`"missing_stream_names":["fail-me"]}`
`"missing_stream_names":["fail-me"]}`
```bash
~/test/list-issue  nats -s localhost:4222 c report drei --trace
18:34:32 >>> $JS.API.STREAM.INFO.drei
18:34:32 <<< $JS.API.STREAM.INFO.drei
{"type":"io.nats.jetstream.api.v1.stream_info_response","config":{"name":"drei","subjects":["drei"],"retention":"limits","max_consumers":-1,"max_msgs":-1,"max_bytes":-1,"max_age":0,"max_msgs_per_subject":-1,"max_msg_size":-1,"discard":"old","storage":"file","num_replicas":1,"duplicate_window":1200 …
```
> Adding missing entry to stream/consumer list

- server/monitor.go
Appears what happens is that the getPublicConsumers()
is called which produces a list of consumers and that
between the time the list is made and the Info() is
called the ephemeral was removed.
> fixes a nil panic on jsz

- server/auth.go
- server/auth_test.go
- server/events_test.go
Check for a no_auth_user should be done only when no authentication
at all is provided by the user. This was not the case. For instance,
if the user provided a token, the server would still check for
no_auth_user if users are defined. It was not really an issue since
the admin cannot configure users AND token, but it is better for
the application to fail if providing a token that is actually not
being used. If the admin configures a no_auth_user, this should
be used only when no authentication is provided.
> [FIXED] Check for no_auth_user

- server/auth.go
- test/tls_test.go
For TLS configuration with `verify_and_map` set to true, if a
connection connects and has a certificate with ID that matches
a user, but that user's `allowed_connection_types` is specified
and does not have the connection type in its list, then the
server will panic.
> [FIXED] TLS map: panic for existing user but conn type not allowed

- server/consumer.go
- server/jetstream_cluster_test.go
If the interest existed prior to the initial creation of the
consumer, the gateway "watcher" would not be started, which means
that interest moving across the super-cluster after that would
not be detected.
The watcher runs every second and not sure if this is costly or
not, so we may want to go a different approach of having a separate
interest change channel that would be specific to gateways. But this
means adding a new sublist where the interest would be registered
and that sublist would need to be updated when processing GW RSub
and RUnsub?
Resolves #2745 
> [FIXED] JetStream: interest across gateways

- server/jetstream_cluster.go
- server/memstore.go
- server/norace_test.go
- server/stream.go
Memory store tracked interior deletes for stream state, but under KV semantics this could be a very large state to maintain.
In looking into memory usage we discovered it was actually faster to not track at all and generate on the fly. 
And this also saves quite a bit of memory in edge cases.
Signed-off-by: Derek Collison <derek@nats.io> 
> Memstore tracking of interior deletes improved.

- server/filestore.go
- server/filestore_test.go
A low-level Filestore issue would cause a new block to be created
when the last block was empty, but the index for the new block
would not be forced to be written on disk.
The observed issue could be that with a stream with a WorkQueue
retention policy, its first/last sequence values could be reset
after a pull subscriber would have consumed all messages and
the server was restarted without a clean shutdown.
This would cause the pull subscriber to "stall" until enough
new messages are sent to reach a stream sequence that catches
up with the consumer's view of the stream first sequence prior
to the restart.
> [FIXED] JetStream: stream first/last sequence possibly reset

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
Stabilize filestore to eliminate sporadic errPartialCache errors under certain situations.
The filestore would release a msgBlock lock while trying to load a cache block if it thought it needed to flush pending data. With async false, this should be very rare but was possible after careful inspection and could lead under the right conditions to a consumer getting an errPartialCache returned trying to load a message.
Resolves #2732 (Hopefully)
> Fix for when consumer would stop working due to errPartialCache returned from fileStore.

- server/consumer.go
- server/filestore.go
- server/norace_test.go
Under certain situations large number of consumers that are racing to update state or delete their stores during a delete
would start taking up OS threads due to blocking disk IO. When this happened and their were a bunch of Go routines becoming runnable the Go runtime would create extra OS threads to fill in the runnable pool and would exhaust the max thread setting. Even if it did not exhaust it you could see a quick run up in memory and unstable systems.
This code places a channel as a simple semaphore to limit the number of disk IO blocking OS threads.
Resolves #2742 
> Large number of ephemeral consumers could exhaust Go runtime's max OS threads.

- server/client.go
- server/websocket_test.go
Instead of replacing connection's host with value specified by
this header, we will simply add the address to the logging only.
So instead of having something like:
```
192.168.1.1:5678 - wid:10 - Client connection created
```
we could have:
```
1.2.3.4/192.168.1.1:5678 - wid:10 - Client connection created
```
As seen above, this PR simply prefixes the connection's remote address
with the header's value (if a valid IP).
Related to #2734
Resolves #2767
> Add X-Forwarded-For IP to the client's remote address

- server/client.go
- server/consumer.go
- server/errors.json
- server/events.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/monitor.go
- server/monitor_test.go
- server/mqtt_test.go
- server/opts.go
- server/route.go
- server/server.go
- server/stream.go
This allows stream placement to overflow to adjacent clusters.
We also do more balanced placement based on resources (store or mem). We can continue to expand this as well.
We also introduce an account requirement that stream configs contain a MaxBytes value.
We now track account limits and server limits more distinctly, and do not reserver server resources based on account limits themselves.
> Implement overflow placement for JetStream streams.

- server/opts.go
- server/opts_test.go
Resolves #2754
- Adds a function to check if max_file_store is a string or int64. Possibly could be reused again.
> [ADDED] Ability to express the max_file_store and max_memory_store as a string (100M, etc..)

- server/raft.go
Some operations could cause the route to block due to lock being
held during store operations. On macOS, having lots of streams/consumers
and restarting the cluster would cause lots of concurrent IO that
would cause lock to be held for too long, causing head-of-line
blocking in processing of messages from a route.
> [IMPROVED] JetStream clustering with lots of streams/consumers

- server/filestore.go
> When rebuilding the complete filestore state we need to do this in a go routine.

- .goreleaser.yml
- server/const.go
Since we moved to go modules, the path must include the `/v2`.
> Fixed goreleaser ldflags

- server/accounts.go
- server/auth.go
This is due to a re-entrant RLock(). It works sometimes, but if there
is a go routine requesting the write lock, then the second RLock()
will not be granted which will lead to a deadlock.
In summary: one should never make re-entrant RLock calls.
> [FIXED] Possible deadlock

- server/server.go
I'm somewhat frequently seeing this data race in the [nats-io/prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter/runs/4888499652?check_suite_focus=true) CI.
```
=== RUN   TestStreamingServerInfoMetricLabels
Write at 0x00c0001f6010 by goroutine 57:
github.com/nats-io/nats-server/v2/server.(*Server).startMonitoring.func1()
C:/Users/runneradmin/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.7.0/server/server.go:2365 +0x98
Previous read at 0x00c0001f6010 by goroutine 118:
net/http.serverHandler.ServeHTTP()
C:/hostedtoolcache/windows/go/1.16.13/x64/src/net/http/server.go:2861 +0x49
net/http.(*conn).serve()
C:/hostedtoolcache/windows/go/1.16.13/x64/src/net/http/server.go:1933 +0x89d
Goroutine 57 (running) created at: …
```
> Fix race condition in HTTP monitoring shutdown

- server/auth.go
- server/auth_test.go
- server/opts.go
- server/parser.go
Resolves #2810 and also allows telnet demo for protocol to demo.nats.io to work again.
> Do not require CONNECT when no_auth_user defined, don't complain about password for internal clients.

- server/monitor.go
- server/monitor_test.go
[Resolves #2778 ](https://github.com/nats-io/nats-server/issues/2778)
- Adds ReplicationLagInfo list to StreamDetail
- Adds option to populate ReplicationLagInfo
> [ADDED] Replication lag to stream monitoring

- server/filestore.go
This is a bandaid for now. This could possibly happen but unclear why.
> If we detect negative deleted, adjust to 0.

- go.mod
- go.sum
- server/consumer.go
- server/events.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/route.go
- server/server.go
This change fixes a break in behavior for one-shot pull batch requests and formalizes pull requests and their associated behaviors. We also now can expire out of order and we will expire on a leader change for the consumer as that state is shared for pending requests between leaders and followers, only if >= 2.7.1
> Updates to Pull Consumers

- server/jetstream_cluster_test.go
- server/monitor.go
- server/norace_test.go
- server/server.go
Used for health and liveness probes for environments like k8s.
Currently this code returns a 200 and `{ "status": "ok" }` iff all configured ports are open
and if JetStream is configured and we have contact with the meta leader and its current and all streams are up to date.
If we are not current we return a 503 at first error and a `{ "status": "unavailable", "error": "DESCRIPTION" }` body.
We can do much more but this feels like a decent start to test with upgrading servers in a k8s environment that is running JetStream.
> Added in /healthz endpoint.

- go.sum
- server/accounts.go
- server/jwt_test.go
- server/monitor.go
user and activation token did not honor the jwt value for all * on
connect.
activation token where not re evaluated when the export revoked a key.
In part this is a consistency measure so servers that already have an
account and servers that don't behave the same way.
in jwt activation token revocations are stored per export.
The server stored them per account, thus effectively merging
revocations. Now they are stored per export inside the server too.
fixes nats-io/nsc/issues/442
> Fix jwt based user/activation token revocation and granularity

- .github/workflows/nightly.yaml
> Nightly: set Go version to 1.17 and use latest goreleaser

- server/consumer.go
- server/jetstream_cluster_test.go
This CL will disallow that upgrade. We had a check in place for pull to push, but not the reverse.
> Updating a push consumer to be pull should fail.

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
The original design of the consumer and the subsequent storage layer did not allow for config updates.
Now that we do, we need to store the new config into our storage layer.
> FIXES #2828. 

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
- server/norace_test.go
> A true no wait pull request was not considering redeliveries.

- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
Per the discussion, unless a stream is reaching a limit, DiscardNew should not be in affect if we are at a per subject limit with max msgs.
> Fixed behavior for when MaxMsgsPerSubject is set and DiscardNew is also set.

- server/events.go
- server/jetstream_cluster_test.go
Currently, we don't update the JetStream configuration in `Server.nodeToInfo`. This can cause a problem if the user doesn't explicitly configure JetStream `MaxStore` or `MaxMem`. It's a problem because some code expects `MaxStore=-1` to be resolved to a real non-negative amount of bytes. Specifically, this check fails: https://github.com/nats-io/nats-server/blob/main/server/jetstream_cluster.go#L3683
This is what the call stack looks like.
* `jetStreamCluster.selectPeerGroup` - returns nil because `ni.cfg.MaxStore > int64(used)` is false because `MaxStore=-1`
* `jetStream.createGroupForStream` - returns nil because `selectPeerGroup` returned nil
* `Server.jsClusteredStreamRequest` - returns "insufficient resources"
The included test fails to `js.AddStream` with the error "insufficient …
> Store JetStream Config in node info map

- server/consumer.go
- server/jetstream_cluster_test.go
If the consumer's sequence was not the same than the stream's sequence,
then the redelivery would always use the first duration from the
BackOff list.
> [FIXED] JetStream: BackOff redeliveries would always use first in list

- server/filestore.go
- server/filestore_test.go
Under certain scenarios the pending for a consumer could appear to get stuck.
Under the covers we were calculating pending per msg block incorrectly when a single message existed beyond the requested sequence.
> Consumer pending gets stuck.

- server/norace_test.go
This test was using fetch and failing if the complete batch was not filled.
This has nothing to do with the test, we just want to make sure the leader steps down and there were no low level errors on the fetch.
> Fix flapping test - TestNoRaceJetStreamClusterCorruptWAL

- server/jetstream_test.go
- server/stream.go
When a consumer had no filtered subject and was attached to an interest policy retention stream we could incorrectly drop messages.
> FIXED #2836

- server/errors.json
- server/filestore.go
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/memstore.go
- server/norace_test.go
- server/store.go
Note that we went with a simpler approach vs message per result or a paged api. We will place the subject details (just msg count) into the stream info state. Since NATS as a system can limit payloads of any msg entering the system, but the system itself can send any size message to any client, we allow this to proceed. We artificially limit it to 100k, and for items like KV we can fall back to the watcher/ordered consumer pattern as needed.
> Added in ability to get per subject details via StreamInfo.

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
- server/norace_test.go
- server/store.go
When a stream has multiple subjects and a consumer filters the stream to a small and spread out list of messages the logic would do a linear scan looking for the next message for the filtered consumer.
This CL allows the store layer to utilize the per subject info to improve the times.
> Improved sparse consumers replay time.

- server/filestore.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
> A stream name is tied to its identity and can not be changed on a restore.

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
In certain circumstances, mostly with direct push based consumers, the consumer info returned by the js.Subscribe() calls could have a consumer info that already reflects delivering some, possibly all the original pending messages.
This change makes the initial pending state correct in those situations.
> Make sure we snapshot initial consumer info during consumer creation.

- server/filestore.go
- server/norace_test.go
During a filestore snapshot we generate the fss files for the snapshot but were not cleaning them up if the block was deleted before a server restart.
https://gist.github.com/nekufa/010185dfb59261f222a0042d3a7d2a1c
> Remove fss files from a snapshot when a block is removed.

- server/consumer.go
- server/jetstream_test.go
Introduced by #2848, so should not have impacted existing releases.
> Fixed consumer dlv count and num pending wrong due to redeliveries

- server/jetstream_cluster.go
After 0cc7302be9bc37f0ee45f480e4e4a458b3bb62bf doing a restore that fails due
to the new error in a clustered environment will trigger this seg fault, panic and leaving
the failed stream on disk.
Not sure why this responce here is nil, but its guarded against now and the restore failure
is handled correctly with no panic and no orphaned stream.
> avoid seg fault when stream restore fails

- server/ipqueue.go
- server/raft.go
- Limit IPQueue logging
- Add a rand per raft node. This is because in some situations when
running 3 servers at the same time, we would end-up with identical
inboxes for different subjects on the different nodes which would
cause panics
- Move the creation of internal subscriptions after the tracking
of the node and its peers.
> Various changes

- server/gateway.go
- test/gateway_test.go
When a gateway connection was created (either accepted or initiated)
the timer to fire the first PING was started at that time, which
means that for an outbound connection, if the INFO coming from
the other side was delayed, it was possible for the outbound to
send the PING protocol before the CONNECT, which would cause
the accepting side to close the connection due to a "parse" error
(since the CONNECT for an inbound is supposed to be the very
first protocol).
Also noticed that we were not setting the auth timer like we do
for the other type of connections. If authorization{timeout:<n>}
is not set, the default is 2 seconds.
> [FIXED] Gateway: connect could fail due to PING sent before CONNECT

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
In clustering mode, the number of consumers in stream info may be
wrong in presence of non durable consumers. Ephemeral are handled
by specific nodes. The StreamInfo response would contain only the
consumer count that the stream leader is handling.
This fix overrides the stream's state consumers count with the
number of consumers from the stream assignment record.
Resolves #2895
> [FIXED] JetStream stream info consumers count in clustered mode

- server/jetstream.go
- server/jetstream_cluster.go
- server/stream.go
In the process of working on #2885 with a user, I was struggling to map $SYS directories to consumer names.
This change allows a bit better logging on startup to more easily map a RAFT log directory etc to the stream/consumer.
> Better startup logging to help debug RAFT to streams/consumers.

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
When a filtered consumer who has no state, meaning no messages are being processed, it still will receive updates to properly track the delivered sequence as it relates to the entire stream.
Since we did not have state we were inadvertently skipping the compaction logic for the raft store.
Resolves #2885
> [FIXED] Never used clustered and filtered consumers consume too much disk storage under $SYS

- server/filestore.go
- server/jetstream_test.go
Fixed a bug that would not recover a stream properly after a non-clean shutdown with deleted messages.
> Can't recover stream on restart with deleted msg error.

- server/leafnode.go
- server/leafnode_test.go
In complex situations, queue members count across various servers
may not be properly accounted for when sent to a new leafnode
connection.
The new test TestLeafNodeQueueGroupWithLateLNJoin has a drawing
of such setup, when after LN1 joined, and then queue members
were removed with 1 left, LN1 was told that there was no
more interest, so message published to LN1 would not reach
the remaining queue sub connected to LN2.
> [FIXED] LeafNode: queue sub interest not properly sent to new LN

- server/client.go
- server/gateway.go
- server/leafnode.go
- server/route.go
- server/server.go
This was introduced when fixing #2881. The call to setFirstPingTimer
needed to be done under the client's lock.
Moved setFirstPingTimer from a server receiver to a client receiver.
The only reason it was a server receiver is because we need the
server options, but c.srv is always set when invoking this function,
so we will get the server from c.srv in that function now.
Related to #2881
> Gateways: data race when setting first ping timer

- server/jetstream_cluster_test.go
- server/stream.go
If we had not heard from a source or mirror we would still calculated active.
This would wrap and create a large number which overflowed JSON's 2^53 limit.
This would cause schema violations in the NATS cli.
> Set active for Sources and Mirrors to -1 on no contact

- server/jetstream_cluster_test.go
- server/stream.go
The "deleted" advisory was missing because the stream's send loop
was closed before the advisory was pushed to the queue to be sent.
Added tests, both for single and clustered mode to test all stream
advisories.
Resolves #2886
> [FIXED] JetStream: Some stream advisories missing

- go.mod
- go.sum
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/server.go
please read the introduced comment carefully
> Adding denies $KV.>/$OBJ.> along leaf connections on differing domain

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
When a consumer has no state we are now compacting the log, but were not snapshotting.
This caused issues on leader change and losing quorum.
Resolves #2913 
> [FIXED] Consumer with no activity can lose quorum

- README.md
- server/const.go
> Release v2.7.4

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
When a stream or consumer was offline we would not properly respond to a delete call.
We also would hang if no stream info requests were sent during a stream list due to the asset being offline.
> Offline streams behavior during list and delete improved.

- server/jetstream_test.go
- server/stream.go
Currently, there is a bug where `js.storeReserved` and `js.memReserved` can underflow, causing `/varz` metrics to be incorrect. Below is a history of the state changes.
1. Create stream with no MaxBytes: `js.storeReserved` → 0
2. Update stream with MaxBytes=1234: `js.storeReserved` → 0 (should have reserved 1234)
3. Delete stream: `js.storeReserved` → -1234
**Bug:**`js.storeReserved=-1234` is an `int` that later gets converted to a `uint64`, which causes an underflow.
This change releases the old MaxBytes and reserves the new MaxBytes during the stream update step. This way, when a stream is deleted, these values don't become negative.
Resolves https://github.com/nats-io/nats-server/issues/2882 (see for additional info)
> Prevent reserved bytes underflow

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/monitor.go
> Improve consumer state handling.

- server/client.go
- server/errors.go
- server/gateway.go
- server/gateway_test.go
- server/monitor.go
- server/route.go
- server/server.go
Gateway connection will be closed and error reported if a remote
has a name that is a duplicate of the local cluster.
> [CHANGED] Gateway: Detect duplicate names between clusters

- server/consumer.go
- server/jetstream_test.go
We have seen situations where when a lot of pending messages accumulate,
there is a contention between the processing of the ACKs and the
checking of the pending map.
Decision is made to abort checking of pending list if processing of
ack(s) would be delayed because of that. The result is that a
redelivery may be post-poned.
Internally, the ACKs are also now using a queue to prevent processing
of them from the network handler, which could cause head-of-line
blocking, especially bad for routes.
> [CHANGED] JetStream: Redeliveries may be delayed if necessary

- server/monitor.go
- server/server.go
On main page for monitoring I put a version with a link that is gitCommit aware directly to the source.
> Show version on main monitoring page with link to source

- server/jetstream_test.go
This adds a test to see if we can update a stream when the stream limit is 1. Currently, this test fails, so we're skipping it. This test will be enabled in a future PR.
> Add stream limit update test

- server/jetstream_cluster_test.go
- server/opts.go
If misconfigured could prevent the JetStream system from electing a leader. We will skip the entry and warn to the log.
> Detect exact duplicates for URLs for routes, gateways or leafnodes.

- server/consumer.go
- server/events.go
- server/ipqueue.go
- server/ipqueue_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/monitor.go
- server/mqtt.go
- server/raft.go
- server/sendq.go
- server/server.go
- server/server_test.go
- server/stream.go
Removed the warnings, instead have a sync.Map where they are
registered/unregistered and can be inspected with an undocumented
monitor page.
Added the notion of "in progress" which is the number of messages
that have been pop()'ed. When recycle() is invoked this count
goes down.
> Changes to IPQueues

- server/jetstream_test.go
- server/stream.go
Removal of a stream source that was external was not working properly,
allowing messages to still flow after the removal and until the
server hosting the stream to which the source was removed was
restarted.
Resolves #2920
> [FIXED] Removal of an external source stream

- server/jetstream_cluster.go
I got this panic in a test:
```
=== RUN   TestJetStreamClusterAccountLoadFailure
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xb1501b]
goroutine 47853 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).processLeaderChange(0xc000b60580, 0x0)
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3638 +0x9b
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster(0xc000b60580)
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:853 +0x60f
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:3017 +0x87
FAIL …
```
> [FIXED] JetStream: possible panic on leadership change notices

- server/config_check_test.go
- server/opts.go
- server/opts_test.go
If accounts{} block is specified, authorization{} should not have
any user/password/token or users array defined.
The reason is that users parsed in accounts{} are associated with
their respective account but users parsed in authorization{} are
associated with the global account. If the same user name is
in both, and since internally the parsing of those 2 blocks is
completely random (even if layed out in the config in a specific
order), the outcome may be that a user is either associated with
an account or the default global account.
To minimize breaking changes, but still avoid this unexpected
outcome, the server will now detect if there are duplicate users
(or nkeys) inside authorization{} block itself, but also between
this block and accounts{}.
The check will also detect if …
> [CHANGED] Duplicates in authorization{} and accounts{} now detected

- server/jetstream_test.go
- server/stream.go
This was introduced by the change for ipQueues in #2931.
The (*ipQueue).unregister() was written with a protection for
the ipQueue to be nil, however, mset.outq is actually not a bare
ipQueue but a jsOutQ that embeds a pointer to an ipQueue. So we
need to implement register() for jsOutQ.
Added a test that reproduced the issue, but found it with a flapping
test (TestJetStreamLongStreamNamesAndPubAck) that failed due to
a file name too long.
> Fixed panic on stream create failure (with filestore)

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
Since the "next" timer value is set to the AckWait value, which
is the first element in the BackOff list if present, the check
would possibly happen at this interval, even when we were past
the first redelivery and the backoff interval had increased.
The end-user would still see the redelivery be done at the durations
indicated by the BackOff list, but internally, we would be checking
at the initial BackOff's ack wait.
I added a test that uses the store's interface to detect how many
times the checkPending() function is invoked. For this test it
should have been invoked twice, but without the fix it was invoked
15 times.
Also fixed an unrelated test that could possibly deadlock causing
tests to be aborted due to inactivity on Travis.
> JS: BackOff list caused too frequent checkPending() calls

- go.mod
- go.sum
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/norace_test.go
- server/raft.go
- server/store.go
- server/stream.go
Under certain circumstances a stream that was still trying to catch up at the upper layers above NRG could be elected leader staling consumers.
Improved memory usage through JetStream storage layer.
Previously we would rely more heavily on Go's garbage collector since when we loaded a block for an underlying stream we would pass references upward to avoid copies.
Now we always copy when passing back to the upper layers which allows us to not only expire our cache blocks but pool and reuse them.
The upper layers also had changes made to allow the pooling layer at that level to interoperate with the storage layer.
> [IMPROVED] Stream recovery and Memory Utilization

- server/accounts.go
- server/accounts_test.go
- server/errors.go
- server/opts.go
- test/accounts_cycles_test.go
introduces 'Moustache' style subject mapping format (e.g. foo.*.* -> foo.{{wildcard(1)}}.{{wildcard(2)}}.{{partition(10,1,2)}})
> [ADDED] deterministic subject tokens to partition mapping

- server/jetstream_cluster.go
- server/jetstream_test.go
missing reply caused timeout
Resolves #
-
-
-
> [FIXED] update of R1 Consumer in clustered setup.

- locksordering.txt
- server/consumer.go
- server/jetstream.go
- server/jetstream_cluster_test.go
- server/stream.go
Would possibly show up when a consumer leader changes for a consumer
that had redelivered messages and for instance messages were inbound
on the stream.
Resolves #2912
> [FIXED] JetStream: possible deadlock during consumer leadership change

- server/filestore.go
Under heavy contention skipMsg combined with removeMsg and writeIndexInfo could result in index being stamped with underflow for number of messages. This would lead to possible panic when using mb.msgs to allocate a block buffer.
We had a report of a panic on server restart with 2.8.0-beta.1 (Thanks to Derek Wang!). The panic was trying to malloc/make the size of a load block based off of the number of messages we thought the block had from the index file. Before, SkipMsg would decrement and when we added the record via writeMsgRecord we would add it back in. However we did release the lock, meaning other things could run in between under load. If in between the decrement, say to 0 (we did protect against underflow there), then a remove and subsequent writeIndexInfo would stamp an …
> Heavy contention in filestore could result in underflow and panic.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
Also fixed a bug where we were incorrectly not spinning up the monitoring loop for a stream when going from 3->1->3.
Resolves #2955 
> [FIXED] Scaling up an R1 stream would not replicate existing messages.

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
During contention to the head write block, the system could perform worse memory wise compared to simple go runtime and GC. Also had some references for the subject of messages being read back in to the underlying block which was bloating memory.
Additionally a fix for firstMatching() that did unnecessary work when matching all. This would cause excessive CPU and excessive load on the garbage collector.
> Additional improvements to memory pooling and management. 

- go.mod
- go.sum
- server/accounts.go
- server/consumer.go
- server/errors.json
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/jwt_test.go
- server/monitor.go
- server/mqtt_test.go
- server/opts.go
- server/raft.go
- server/server.go
- server/store.go
- server/stream.go
This keeps proper track of reservations (computes them on the fly)
stream updates now pass when at the stream limit. (Similar for changes in replication factor)
Adding tiers also influenced the layout of the info message.
> [ADDED] Tiered limits and fix limit issues on updates

- server/consumer.go
The default value is lowered from 20,000 to 1,000. This does not
seem to have a performance degradation impact, but may help
with scalability at scale.
> [CHANGED] JetStream: lower default consumer's maximum ack pending

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/norace_test.go
Also fixed a bug that could cause memory based replicated consumers to potentially no longer work after snapshots and server restarts.
The snapshot logic would allow non-state changing updates to continuously grow the raft logs. We also were too conservative on when we snapshotted and why.
Also added in ability to have FileStore.Compact() reclaim space from the block file from the head of last changed block.
Resolves #2936 
> [IMPROVED] Consumer snapshot logic in clustered mode and disk usage.

- .travis.yml
- server/events.go
- server/gateway.go
- server/gateway_test.go
- server/jetstream_test.go
Got a data race:
```
Write at 0x00c001c736b0 by goroutine 605:
runtime.mapassign_faststr()
/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/runtime/map_faststr.go:202 +0x0
github.com/nats-io/nats-server/v2/server.(*Account).addServiceImport()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/accounts.go:1868 +0xb7b
github.com/nats-io/nats-server/v2/server.(*Account).AddServiceImportWithClaim()
...
Previous read at 0x00c001c736b0 by goroutine 301:
runtime.mapaccess2_faststr()
/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/runtime/map_faststr.go:107 +0x0
github.com/nats-io/nats-server/v2/server.(*Server).registerSystemImports()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/events.go:1577 +0x284 …
```
> Fix races and some tests

- server/monitor.go
Kubernetes probes don't use nor log the reponse body of health
endpoints. This means that for some reason a nats node running in
Kubernetes becomes on a Not Ready state we won't have a way to know why
other than to manually access the cluster and call the /healthz endpoint
manually and see the error.
This change adds an error log so we can observe what is going wrong with
a nats node that is not ready.
Signed-off-by: Samuel Torres <samuel.torres@form3.tech>
Resolves #
- Add error logging to healthcheck endpoint 
> [ADDED] Logs to healthcheck handler

- server/accounts.go
- server/consumer.go
- server/jetstream_test.go
A panic was reported that looked like this:
```
fatal error: concurrent map read and map write
goroutine 200 [running]:
runtime.throw({0xa366ce, 0xe620e0})
/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/runtime/panic.go:1198 +0x71 fp=0xc00105f098 sp=0xc00105f068 pc=0x434ff1
runtime.mapaccess1_faststr(0x0, 0x0, {0xc0054b6f18, 0x11})
/home/travis/.gimme/versions/go1.17.8.linux.amd64/src/runtime/map_faststr.go:21 +0x3a5 fp=0xc00105f100 sp=0xc00105f098 pc=0x412285"
github.com/nats-io/nats-server/v2/server.(*consumer).processNextMsgReq(0xc000681000, 0xc00105f2a8, 0x4503e9, 0x11, {0x0, 0xc000246900}, {0xc0054b6f18, 0x11}, {0xc0002469c4, 0x90, ...})
/home/travis/gopath/src/github.com/nats-io/nats-server/server/consumer.go:2454 +0x8ce fp=0xc00105f250 sp=0xc00105f100 pc=0x77dc2e …
```
> [FIXED] Possible panic due to data races

- server/jetstream_test.go
- server/reload.go
This still does not work, out of ideas.
> Fixes #2969, on reload stream import was not removed for js streams

- .travis.yml
- server/client.go
- server/filestore_test.go
- server/jetstream_cluster_test.go
- server/monitor.go
Data race that has been seen:
```
Read at 0x00c00134bec0 by goroutine 159:
github.com/nats-io/nats-server/v2/server.(*client).msgHeaderForRouteOrLeaf()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:2935 +0x254
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:4364 +0x2147
(...)
Previous write at 0x00c00134bec0 by goroutine 201:
github.com/nats-io/nats-server/v2/server.(*Server).addRoute()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/route.go:1475 +0xdb4
github.com/nats-io/nats-server/v2/server.(*client).processRouteInfo()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/route.go:641 +0x1704
```
Also fixed some flappers and removed use of …
> Fixed data race and some flappers

- server/jetstream_cluster.go
Noticed the failure when I removed the `t.Skip()` in my test :-(
> Fixed wrong error check

- server/const.go
- server/jetstream_api.go
Down from 256KB to 128KB for chunk and 32MB to 8MB.
> Updated snapshot default chunk size and window size

- server/jetstream_test.go
- server/server_test.go
The system limit placement tests can fail if we can't get a specific server to be the leader. There is currently no way to force a specific server to be the leader, so we have to rely on chance for this to happen.
The main change here is that if we can't pick the right leader, then we'll skip the test instead of fail the test. I also added some more checks to `TestJetStreamSystemLimitsPlacement`.
I can't use the current JetStream cluster helpers because those assume that every server in the cluster is identical. However, the point of these tests is to verify the behavior when servers are configured differently. There may be a way to start the cluster and update individual servers after the fact, based on [this test](https://github.com/nats-io/nats-server/blob/ee98a814694820d9eeb9a2646a9aa5 …
> Skip SystemLimitsPlacement if we can't get the desired leader

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
Not allowing sealed streams to be created meant we could not recover on server restart.
> [FIXED] Sealed streams would not recover on server restart.

- server/jwt_test.go
If both servers sent a remote update of their local use,
the limit was hit. But that limit wass to small by 200
> start using unit test TestJWTClusteredJetStreamTiers, size was off

- server/client.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/log.go
- server/server.go
- server/server_test.go
- server/stream.go
Some warnings, especially when dealing with JS limits that were
printed on a per-message basis, are now limited to ~1 per second
if the content of the warning is already found in a map.
This is also for "client" warnings, but the client porting of the
warning is not taken into account so that helps with reducing logging
for similar content, but coming from different clients.
> [CHANGED] Rate limit (some) similar warnings

- server/jetstream_cluster_test.go
- server/jwt_test.go
named createJetStreamClusterAndModHook allowing the generated config to
be altered prior to server start
Resolves #
-
-
-
> Add a config modification callback to createJetStreamCluster

- server/jetstream.go
fixes 
```
--- FAIL: TestJetStreamSystemLimitsPlacement (2.99s)
--- PASS: TestJetStreamSystemLimitsPlacement/file_create_large_stream_on_small_server (0.00s)
--- PASS: TestJetStreamSystemLimitsPlacement/memory_create_large_stream_on_small_server (0.00s)
--- PASS: TestJetStreamSystemLimitsPlacement/file_create_large_stream_on_medium_server (0.00s)
--- PASS: TestJetStreamSystemLimitsPlacement/memory_create_large_stream_on_medium_server (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x8fed6e]
goroutine 193037 [running]:
testing.tRunner.func1.2(0x10003a0, 0x17d2360) …
```
> fix crash on shutdown with meta being nil

- server/raft_test.go
I sampled on which index errors happened. All where below 42
for reference: 
```go
// This can not be used post the wire level callback since we do not copy.
func (n *raft) decodeAppendEntry(msg []byte, sub *subscription, reply string) (*appendEntry, error) {
if len(msg) < appendEntryBaseLen {
return nil, errBadAppendEntry
}
var le = binary.LittleEndian
ae := &appendEntry{
leader: string(msg[:idLen]),
term:   le.Uint64(msg[8:]),
commit: le.Uint64(msg[16:]),
pterm:  le.Uint64(msg[24:]),
pindex: le.Uint64(msg[32:]),
}
// Decode Entries.
ne, ri := int(le.Uint16(msg[40:])), 42
for i, max := 0, len(msg); i < ne; i++ {
if ri >= max-1 {
return nil, errBadAppendEntry
}
le := int(le.Uint32(msg[ri:]))
ri += 4
if le <= 0 || ri+le > max {
return nil, …
```
> fix unit test that did not fail when header was modified

- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
This broke cross-account functionality. Ported the test from the
Go client that showed the failure after PR#2997 was merged.
> Undo sending bad request on no-interest in apiDispatch

- server/jetstream_cluster_test.go
- server/jwt_test.go
This needs testing because stream move adjusts the replication factor
Because adjusting replication factor and moving is illegal, this case
does not need to be tested
In order to support one off configurations, added same modification
callout to super cluster as is used with cluster
> unit test to make sure tiered limits and stream moves work together

- server/filestore.go
This is more of a regression introduced in v2.7.3 (with PR #2848).
When the store has a list of subjects, finding the next message
to deliver would go through the subjects map and have to match
to find out if it is a subset (if the filter had a wildcard).
In situations where there were lots of subjects (for instance 1
message per subject), but the consumer did not filter on anything
specific, then this processing was becoming slow.
We now check that if the stream has a single subject (even with
wildcard) and the consumer filters on that exact subject, then
we can do a linear scan. We also do a linear scan if the number
of messages in the block is 1/2 the number of subjects in the
subjects map.
> [IMPROVED] Stream with multiple subjects and consumer with filter

- server/jwt_test.go
ran without and this and -race, spotted the issues
ran with this and -race, no issue in 40 min
> fix sleep in unit test to ensure updates have propagated

- server/client.go
- server/config_check_test.go
- server/errors.go
- server/leafnode.go
- server/leafnode_test.go
- server/monitor.go
- server/opts.go
- server/util.go
- test/leafnode_test.go
If set, a server configured to accept leafnode connections will
reject a remote server whose version is below that value. Note
that servers prior to v2.8.0 are not sending their version
in the CONNECT protocol, which means that anything below 2.8.0
would be rejected.
Configuration example:
```
leafnodes {
port: 7422
min_version: 2.8.0
}
```
The option is a string and can have the "v" prefix:
```
min_version: "v2.9.1"
```
Note that although suffix such as `-beta` would be accepted,
only the major, minor and update are used for the version comparison.
> [ADDED] LeafNode `min_version` new option

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/opts.go
Allows to not place a stream in the same availability zone twice
> Adding unique_placement_prefix to ensure matching tags are not used twice

- server/client.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
> [FIXED] Consumer deliver subject incorrect when imported and crossing a route.

- server/consumer.go
- server/jetstream_cluster_test.go
- server/server.go
basically a gw subject propagation issue could be hidden behind a leaf
node.
also change error text when this was the case
> fix js nex interest check where leaf node masked gw subj propagation

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
This introduces stream alternates as an optional part of StreamInfo.
Alternates provide a priority list of mirrors and the source in relation to where the request originated.
So if a stream S has 2 mirrors, and we receive a user request for the stream info for S, it will include a sorted list of itself, since it could be the closest, and all mirrors, allowing clients to select read replicas if so desired.
> Stream Alternates

- server/raft.go
Got this race:
```
Read at 0x00c001c880e8 by goroutine 342:
github.com/nats-io/nats-server/v2/server.(*raft).resetElect()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/raft.go:1525 +0x44
github.com/nats-io/nats-server/v2/server.(*raft).resetElectionTimeout()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/raft.go:1520 +0xa4
github.com/nats-io/nats-server/v2/server.(*raft).handleAppendEntry()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/raft.go:2537 +0x12e
github.com/nats-io/nats-server/v2/server.(*raft).handleAppendEntry-fm()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/raft.go:2525 +0xcc
...
Previous write at 0x00c001c880e8 by goroutine 587: …
```
> Fixed data race with RAFT node election timer

- server/jetstream_test.go
- server/sublist.go
- test/leafnode_test.go
When using subscriptions through import/exports, the server with
a leafnode connection would properly send the interest over, but
if the connection is recreated, this would not happen.
In case of JetStream where that happens under the cover, message
flow would stop after the leafnode restart because the subscriptions
would be created on recovery of the JetStream assets but *before*
the LeafNode connection could be established.
Resolves https://github.com/nats-io/nats-server/issues/3024
Resolves https://github.com/nats-io/nats-server/issues/3027
Resolves https://github.com/nats-io/nats-server/issues/3009
> [FIXED] LeafNode interest propagation with imports/exports

- server/jetstream_cluster.go
> Bump catchup flow control max outstanding bytes

- server/jetstream_test.go
This re-enables previously flaky placement tests. https://github.com/nats-io/nats-server/pull/2998 has helped eliminate the flakiness.
```
$ go test -count=100 -run=SystemLimitsPlacement
PASS
ok  	github.com/nats-io/nats-server/v2/server	296.784s
$ go test -count=100 -run=SystemLimitsPlacement
PASS
ok  	github.com/nats-io/nats-server/v2/server	274.613s
$ go test -count=100 -run=SystemLimitsPlacement
PASS
ok  	github.com/nats-io/nats-server/v2/server	282.251s
$ go test -count=100 -run=SystemLimitsPlacement
PASS
ok  	github.com/nats-io/nats-server/v2/server	274.307s
$ go test -count=100 -run=SystemLimitsPlacement
PASS
ok  	github.com/nats-io/nats-server/v2/server	277.616s
```
> Re-enable placement tests

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/opts.go
server running more than max_ha_assets #raft nodes will not be used to
place new streams and fail if not enough free server can be found.
Durable Consumer creation on such server will fail as their peer size is
bound to the same set as their stream.
This also avoids updating placement where no new placement is needed.
> [Adding] max_ha_assets to limit placement on server with more ha assets

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
During elected stepdown and transfer allow the new leader to take over before we stepdown.
We could receive a leader change, so make sure to also check migration state.
> Improvements to stream and consumer move.

- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/raft.go
- Wait of some sort of routing to be in place before starting
the raft run loop
- Remove use of lock in apiDispatch that was not necessary but
could have cause a route to block, causing memory growth, etc..
Unrelated rename of some tests so that they start with TestJetStream
and TestJetStreamCluster for cluster tests, fixed some flappers
and ensure that tests that change RAFT timeouts put them back
to default values on exit.
> [IMPROVED] JetStream: reduce unnecessary leader election

- server/accounts.go
- server/events.go
- server/jetstream_cluster_test.go
- server/jwt_test.go
The removed code is subsequently handled by addSystemAccountExports.
Right now I am using !standalone as signal to add in the exports. But could add an option, or check for options as well.
> Fixed mixed mode server without JS dropping js export on jwt update

- server/consumer.go
- server/errors.json
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/opts.go
- server/stream.go
stream create had checks that stream restore did not have.
Moved code into commonly used function checkStreamCfg.
Also introduced (cluster/non clustered) StreamLimitsCheck functions to
perform checks specific to clustered /non clustered data structures.
Checking for valid stream config and limits/reservations before
receiving all the data. Now fails the request right away.
Added a jetstream limit "max_request_batch" to limit fetch batch size
Shortened max name length from 256 to 255, more common file name limit
Added check for loop in cyclic source stream configurations
features related to limits
> [Fixed] limits enforcement issues

- server/consumer.go
Have seen some small dips in some global systems that @ripienaar has been running and I have been testing. Originally bumped it down due to some instability but that was not associated with this in the end.
> Bump ordered consumer flow control window back up.

- server/norace_test.go
- server/stream.go
- Possibly missing some early messages from the sourced stream
- In some cancel situations, the processing of sourced messages
would not longer work
> [FIXED] JetStream: some stream SOURCE issues

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
The old raft node assignment would prevent proper catchup.
> If we moved a stream back to a cluster we were once at, the stream would be empty.

- server/opts.go
- [] Documentation added (if applicable)
- [] Tests added
- merge the `JetStream` in function `MergeOptions`.
> Keep jetstream on while using empty config file and reloading

- server/jetstream.go
- server/raft.go
On restart, we report when we find error in checksums, but we
did not report the name of the file.
> [IMPROVED] JetStream: add file names for invalid checksums

- server/service_windows.go
Trying to run nats-server as nt_authority/system, the process would immediately exit with error: "The service process could not connect to the service controller."
This is now fixed
- Stopped using Deprecated method IsAnInteractiveSession (https://pkg.go.dev/golang.org/x/sys/windows/svc#IsAnInteractiveSession)
- Replaced Deprecated method with suggested one (IsWindowsService)
(https://pkg.go.dev/golang.org/x/sys/windows/svc#IsWindowsService)
In order to start a command prompt as nt_authority you can use the following command:
```cmd
PS> psexec -s -i cmd.exe
```
PSExec tool can be found here ([https://docs.microsoft.com/en-us/sysinternals/downloads/psexec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec))
**cmd output before changes:**
```cmd …
```
> Allow nats-server to run as system user on Windows

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
When we polled too quickly on migration we could check before catchup logic had even kicked in.
> Polling too quickly could make migration fail.

- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
Added minimum values of 100ms (used elsewhere as well)
> introducing max_age/dupe_window minimum value of 100ms.

- server/client.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
change in `server/client.go` essentially copies the added code from the non queue part.
Both section of code add a check for leaf connections. (original unit test was wrong).
> Fix subject renaming for leaf connections and queued subs

- server/ipqueue.go
- server/jetstream_test.go
- server/leafnode_test.go
- server/norace_test.go
- server/stream.go
The main issue was that in mixed-mode, the interest through gateway
may still be in optimistic mode, which when creating the source
consumer would start delivery before we had a chance to setup
the subscription to receive those messages.
The approach is to create the subscription prior to sending
the consumer create request. Also refactored a bit the code in
the hope to make the retries a bit more bullet proof.
We may also look at making sure that gateways are switched to
interest-mode when detecting a mixed-mode setup.
Also fixed a defect that could cause a source to be canceled
when updating a stream.
Resolves https://github.com/nats-io/nats-server/issues/2801
> [FIXED] JetStream: stream sources issue in mixed mode clusters

- go.mod
- go.sum
* our CVE scanner has detected crypto go module vulnerability in nats exporter this PR fixes that issue by updating the module version
Resolves #
https://github.com/nats-io/nats-server/issues/3064
- fix crypto vulnerability in go module
> fix for CVE-2022-27191

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_events.go
Resolves #3072
- add the advisory `JSAdvisoryConsumerMsgNakPre` will be triggered when a message is naked.
> Implement JSConsumerDeliveryNakAdvisory

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_super_cluster_test.go
- server/monitor.go
- server/stream.go
We had an issue where a recovered consumer might not recover if a source based stream which housed the consumer filter subject was removed.
We now signal that we are recovering a consumer and if so skip the filtered subject check.
Also per ops re-worked healthz to test all assigned assets, just not those that we could recover.
Also various fixes found during @matthiashanel original diagnosis.
> Fix for a consumer recovery issue and update to healthz.

- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/server.go
- server/stream.go
Step down timing for consumers or streams.
Signals loss of leadership and sleeps before stepping down.
This makes it less likely that messages are being processed during step
down.
When becoming leader, consumer stream seqno got reset,
even though the consumer existed already.
Proper cleanup of redelivery data structures and timer
> [fixed] step down timing, consumer stream seqno, clear redelivery

- server/jetstream_test.go
- server/memstore.go
For memory store KV with history of 1 we were scanning for our next first when we did not have to on rewrites.
> [IMPROVED] KV memory store performance

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/norace_test.go
When deciding to compact a file, we need to remove from the raw
bytes the empty records, otherwise, for small messages, we would
end-up calling compact() too many times.
When removing a message from the stream, in FIFO cases we would
write the index every 2 seconds at most when doing it in place,
when when dealing with out of order deletes, we would do it for
every single delete, which can be costly. We are now writing
only every 500ms for non FIFO cases.
Also fixed some unrelated code:
- Decision to install a snapshot was based on incorrect logical
expression
- In checkPending(), protect against the timer being nil which
could happen when consumer is stopped or leadership change.
> [FIXED] JetStream: file store compact and when to write index

- locksordering.txt
- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/monitor.go
- server/stream.go
When updating usage, there is a lock inversion in that the jetStream
lock was acquired while under the stream's (mset) lock, which is
not correct. Also, updateUsage was locking the jsAccount lock, which
again, is not really correct since jsAccount contains streams, so
it should be jsAccount->stream, not the other way around.
Removed the locking of jetStream to check for clustered state since
js.clustered is immutable.
Replaced using jsAccount lock to update usage with a dedicated lock.
Originally moved all the update/limit fields in jsAccount to new
structure to make sure that I would see all code that is updating
or reading those fields, and also all functions so that I could
make sure that I use the new lock when calling these. Once that
works was done, and to reduce code changes, I put …
> [FIXED] JetStream: possible lock inversion

- server/jetstream_cluster.go
Got this stack:
```
goroutine 247945 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).isGroupLeaderless(0xc004794e70, 0xc0031b0300)
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:661 +0xc2
github.com/nats-io/nats-server/v2/server.(*Server).jsMsgDeleteRequest(0xc001dc9388, 0xc003e6de30, 0xc00222b980, 0xc001454f70, {0xc000668930, 0x24}, {0xc0011dbdb8, 0x11}, {0xc000da93f0, 0xa6, ...})
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_api.go:2335 +0x67d
github.com/nats-io/nats-server/v2/server.(*jetStream).apiDispatch.func1()
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_api.go:716 +0x85
created by github.com/nats-io/nats-server/v2/server.(*jetStream).apiDispatch …
```
> [FIXED] JetStream: possible panic checking for group leader less

- .github/workflows/cov.yaml
- scripts/cov.sh
We are ok with a flapper or two, because they should not affect
code coverage that much, so it is better to have those and publish
code coverage than to have to recycle the whole test suite until
we get no test failure.
However, if there is a test panic, then all other tests within this
package will NOT run, which then would have possibly a massive
impact in the code coverage percentage.
These changes will ensure that the run fails if one of the code
coverage output is "empty" (it is actually not empty, but the
initial content is "mode: atomic" and then whe code coverage is
complete, it gets filled with actual code coverage data).
On failure, the push to coverall will not happen.
> Fixed GithubAction code coverage to handle test panics

- server/consumer.go
- server/jetstream_test.go
- server/norace_test.go
There was an issue with MaxWaiting==1 that was causing a request
with expiration to actually not expire. This was because processWaiting
would not pick it up because wq.rp was actually equal to wq.wp
(that is, the read pointer was equal to write pointer for a slice
of capacity of 1).
The other issue was that when reaching the maximum of waiting pull
requests, a new request would evict an old one with a "408 Request Canceled".
There is no reason for that, instead the server will first try to
find some existing expired requests (since some of the expiration
is lazily done), but if none is expired, and the queue is full,
the server will return a "409 Exceeded MaxWaiting" to the new
request, and not a "408 Request Canceled" to an old one...
> [FIXED] JetStream: PullConsumer MaxWaiting==1 and Canceled requests

- server/filestore.go
> Bump up default block sizes

- go.mod
- go.sum
- server/accounts.go
- server/auth.go
- server/events_test.go
- server/jwt_test.go
- server/server.go
I modified an existing data structure that held a similar attribute already.
Instead this data structure references the claim.
change 3 out of 3. Fixes #3084
corresponds to:
https://github.com/nats-io/jwt/pull/177
https://github.com/nats-io/nsc/pull/495
> [added] support for jwt operator option DisallowBearerToken

- server/raft.go
This would happen in situation where a node receives an append
entry with a term higher than the node's (current leader).
This was introduced by moving a return [here](https://github.com/nats-io/nats-server/pull/3100/files#diff-0a3d4e9b87bb3880bdb735fa489ef618b571de3370dae31d8f509b26e2fb852eR2709) in PR #3100.
> [FIXED] JetStream: possible lockup due to a return prior to unlock

- server/consumer.go
Before PR #3099, `waitQueue.isEmpty()` returned `wq.len() == 0`
and `waitQueue.len()` was protecting against the pointer being
nil (and then return 0).
The change in #3099 caused `waitQueue.isEmpty()` to return `wq.n == 0`,
which means that if `wq` was nil, then it would crash.
This PR restores `waitQueue.isEmpty()` to return `wq.len() == 0` and
add the protection for waitQueue being nil in `len()` similar to
how it was prior to PR #3099.
Resolves #3117
> [FIXED] JetStream: panic processing cluster consumer create

- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
We were getting a data race checking the js.clustered field in
updateUsage() following fix for lock inversion in PR #3092.
```
=== RUN   TestJetStreamClusterKVMultipleConcurrentCreate
Read at 0x00c0009db5d8 by goroutine 195:
github.com/nats-io/nats-server/v2/server.(*jsAccount).updateUsage()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:1681 +0x8f
github.com/nats-io/nats-server/v2/server.(*stream).storeUpdates()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:2927 +0x1d9
github.com/nats-io/nats-server/v2/server.(*stream).storeUpdates-fm()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:2905 +0x7d
github.com/nats-io/nats-server/v2/server.(*fileStore).removeMsg() …
```
> [FIXED] JetStream: Some data races

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
Allowing more control over consumers for large number of consumer setups as we have been seeing lately.
> Allow explicit consumer configuration of replica count and memory storage

- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
- server/util.go
This enables lightweight distribution of messages to very large number of NATS subscribers.
We add in metadata as headers that allows for gap detection which enables initial value (via JetStream, maybe KV) and real-time NATS core sub updates but all being globally ordered and gap detection allowed, even for a subset of messages.
> Enable republishing of messages once stored in a stream.

- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/raft.go
With inlining election timeout updates we double the lock contention and most likely introduced head of line issues for routes under heavy load.
Also slowing down heartbeats with so many assets being deployed in our user ecosystem, also moved the normal follower to candidate timing further out, similar to the lost quorum.
Note that the happy path transfer will still be very quick.
> With use cases bringing us more data I wanted to suggest these changes.

- server/monitor.go
- server/monitor_test.go
- server/route.go
Added Start, LastActivity, Uptime and Idle that we normally have
in a Connz for non route connections. This info can be useful
to determine if a route is recent, etc..
> [ADDED] Monitoring: Routez's individual route has now more info

- server/mqtt.go
- server/mqtt_test.go
- server/opts.go
- server/reload.go
Ability to override the stream and consumers replica count, which is by default
determined based on the cluster size.
```
mqtt {
port: 1883
stream_replicas: 5
consumer_replicas: 1
}
```
The above would allow *new* MQTT streams to be created with a replicas
factor of 5 (it will be an error if the cluster does not have that
many nodes, and error will occur at runtime when the first client
on a given account connects), and new consumers would be R=1.
The MQTT existing streams/consumers for an account are not modified.
The stream_replicas can also obviously be reduced to 1 for a cluster
of 3 nodes if one desire to have those streams as R=1.
A value of 0 or negative is considered letting the server pick
the value (from 1 to 3 depending on standalone/cluster size).
There is another property …
> [ADDED] MQTT: Stream/Consumer replica count override

- server/jetstream.go
- server/mqtt_test.go
Saw this data race report:
```
=== RUN   TestJetStreamJWTClusteredDeleteTierWithStreamAndMove
Write at 0x00c000d88a60 by goroutine 86:
github.com/nats-io/nats-server/v2/server.(*Server).updateAccountClaimsWithRefresh()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/accounts.go:3299 +0x4532
github.com/nats-io/nats-server/v2/server.(*Server).UpdateAccountClaims()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/accounts.go:2932 +0x45
github.com/nats-io/nats-server/v2/server.(*Server).updateAccountWithClaimJWT()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1490 +0x3b4
github.com/nats-io/nats-server/v2/server.(*Server).updateAccount()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server …
```
> [FIXED] JetStream: data race with account's jsLimits

- server/consumer.go
- server/norace_test.go
- server/stream.go
We used to maintain a separate state during runtime which could be wrong under certain conditions.
> Consumer's num pending can now rely on the stream's store

- server/mqtt.go
- server/mqtt_test.go
When there was a failure to delete a QoS1 consumer, the session
would still be deleted, which would cause orphaned consumers.
In case of error, the session record will not be deleted, which means
that it is still possible to restart the session and then close
it (with the clean flag).
Relates to #3116
> [FIXED] MQTT: Errors deleting consumers will now prevent deletion of session

- server/jetstream_api.go
- server/jetstream_helpers_test.go
- server/norace_test.go
- server/server.go
If a JS API request is received from a non client connection, it
was processed in its own go routine. To reduce the number of
such go routine, we were limiting the number of outstanding routines
to 4096. However, in some situations, it was possible to issue
many requests at the same time that would then cause those requests
to be dropped.
(an example was an MQTT benchmark tool that would create 5000
sessions, each with one QoS1 R1 consumer (with the use of consumer_replicas=1).
On abrupt exit of the tool, the consumers and their sessions needed
to be deleted. Since would cause fast incoming delete consumer requests
which would cause the original code to drop some of them)
> [FIXED] Fast routed JetStream API requests were dropped

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/jetstream_jwt_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
- server/stream.go
This could happen when a consumer had not sent anything to the
attached NATS subscription and there was a consumer leader
step down or server restart.
Stabilized code to set starting sequence numbers on true start versus recovered state.
> [FIXED] JetStream: consumer with deliver new may miss messages

- server/accounts.go
- server/client.go
- server/stream.go
This exports the one key function of the subject transformer
allowing external tools to be written to test mappings are
valid and see how they would interact without the hassle of
configuring a serrver
The APIs are specifically marked as being unsupported and
having kept the transform struct itself unexported one can
not cast from the interface to the real implementation
> Export the subject transformer

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
Suppress consumer and stream advisories on server restart and any direct stream get message advisory.
Resolves #3155 
> [FIXED] Suppress some JetStream advisories

- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/stream.go
This could be useful for large messages and having republish just be a signalling mechanism.
> Allow for republish to have headers only option

- server/jetstream.go
- server/jetstream_cluster.go
> Mark meta recovering state and use to suppress api responses and api audits during restarts.

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/stream.go
While the TransformSubject function was doing the right
thing it did not match first and so would panic for subjects
that do not match the mapping.
The map function does the right thing so this is a more
appropriate function to export.
This undoes the exporting of unsafe TransformSubject and
exports the safer Match instead.
> export the correct subject transformer subject

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
Stream get for KV was going through the API layer, but with the popularity, needed a more performant, lighter weight and direct approach. This skips the API layer, which currently still floods and does a bunch of API layer stats and client info tracking.
We could look into using a DQ for R>1 as well, or suggest that for KV just use mirrors for horizontal scalability for reads.
> [IMPROVED] Fast and Direct access to stream messages.

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_errors.go
- server/raft.go
- server/stream.go
This is to help improve when a server/system is under heavy load with low resources, CPU/MEM or FDs.
If the user wants to try to stabilize by deleting a stream possibly with lots of consumers.
Resolves #3167 
> [IMPROVED] Loaded server and low on resources like FDs.

- server/client.go
- server/events_test.go
When internal system messages were destined for a queue subscriber across a route the reply subject would be empty but not nil. This caused mangling of the RMSG proto and would not allow delivery across routes.
Resolves #3177 
> [FIXED] Delivery of internal system msgs to queue subscribers across routes.

- server/filestore.go
- server/memstore.go
In the presence of many subjects in a stream and a wildcard filter subject, fall back to linear scan if too many.
> [IMPROVED] Performance of wildcard filtered consumer with stream with many subjects.

- server/mqtt.go
- server/mqtt_test.go
- server/opts.go
- server/reload.go
A server can configure the mqtt section to designate orphaned inactive consumers for auto cleanup.
Several users have reported a buildup of orphaned consumers from MQTT software they can not change or update.
> Allow for MQTT QoS-1 consumers to be auto cleaned up

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
When stream or consumer names contained path separators it prevented backup and restore.
Resolves #3199 
> [FIXED] Path separators in consumer or stream names prevented restoring a stream

- server/accounts.go
- server/client.go
- server/consumer.go
- server/events.go
- server/jetstream_cluster.go
- server/server.go
We did default to full sharing for an export from the system account, the main one being JetStream. 
As part of this process moved server to RW lock.
Was also going to replace json encoder/decoder but I ran several experiments with my top choices and results are not what I wanted them to be. We should do custom marshallers in a follow up PR.
> Default to essential ClientInfo for JetStream

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/reload.go
Also added:
ability to reload tags
special tag (!jetstream) to remove peer from peer placement
$JS.API.SERVER.STREAM.MOVE subject to initiate move away from a server
This changes a detail about regular stream move as well.
Before differing cluster names where used to start/stop a transfer.
Now only the peer list and it's size relative to configured replica
matter.
Once a transfer is considered completed, excess peers will be dropped
from the beginning of the list.
This allows transfers within the cluster as well.
> [Add] ability for operator to move streams (WIP)

- server/jetstream_cluster_test.go
- server/reload.go
- server/stream.go
account.rm had races caused by reload copying rm from one account to
another
mset.store was used outsisde the lock
in rare cases the stasz message was not received in time.
Trigger automatically now
sometimes a statsz message received before reload cause issues.
try receiving a second time
> [fixed] reload related races

- server/accounts.go
- server/client.go
- server/events.go
- server/events_test.go
- server/reload.go
This subject $SYS.ACCOUNT.%s.SERVER.CONNS will now respond with account
specific datastats for Received and sent messages as well as number of slow
consumers for the account.
Benchmarks ran are `PubSub` and `Pub0b_Payload` 3 times each.
Without then with this change.
The impact seems small enough to prefer the straight forward solution. 
If deemed not so, I can try to also delete the server counter and aggregate its value from account based ones.
First set of 3 is without this change.
```
> go test -v -vet=off -bench='PubSub$' -run=X
goos: darwin
goarch: amd64
pkg: github.com/nats-io/nats-server/v2/test
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Benchmark_____________PubSub
Benchmark_____________PubSub-16    	 5629795	       203.8 ns/op …
```
> [ADD] account specific in/out msgs/bytes stats to CONNS

- server/client.go
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/stream.go
Also for direct get and for pull requests, if we are not on a client connection check how long we have been away from the read loop. If need be execute in a separate go routine.
Note this will move the direct get under the correct subject imo, so account imports/exports should be more easily handled.
Also noting that our bet going forward is that the majority of pulling messages from a system will be the pull request for a consumer and this direct get as will be used in KV, I wanted to make sure to not block any routes or gateways.
> Made direct get from a stream part of the $JS.API hierarchy vs separate.

- server/opts.go
- server/server.go
This PR adds three things:
1.  `InProcessConn()` function to `Server` which builds a `net.Pipe` to get a connection to the NATS server without using TCP sockets
2. `DontListen` option which tells the NATS server not to listen on the usual TCP listener
3. `startupComplete` channel, which is closed right before we start `AcceptLoop`, and `readyForConnections` will wait for it
The main motivation for this is that we have an application that can run either in a monolith (single-process) mode or a polylith (multi-process) mode. We'd like to be able to use NATS for both modes for simplicity, but the monolith mode has to be able to cater for a variety of platforms where opening socket connections either doesn't make sense (mobile) or just isn't possible (WASM). These changes will allow us to use …
> [ADDED] In-process connections

- server/jetstream_cluster.go
write originated in updateWithAdvisory while holding the lock
```
Write at 0x00c0029c23f8 by goroutine 170:
github.com/nats-io/nats-server/v2/server.(*stream).updateWithAdvisory()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:1413 +0x63d
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2775 +0x4a4
github.com/nats-io/nats-server/v2/server.(*jetStream).processStreamAssignment()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2523 +0xaf9
github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaEntries() …
```
> [Fixed] race on unlocked cfg access

- main.go
> AutoMaxProcs would default log output, this suppresses the logging.

- server/jetstream_cluster_test.go
- server/mqtt_test.go
- server/server.go
The "InProcess" change make readyForConnections() possibly return
much faster than it used to, which could cause tests to fail.
Restore the original behavior, but in case of DontListen option
wait on the startupComplete gate.
Also fixed some missing checks for leafnode connections.
> Rework startupComplete gate from PR #2360

- server/jetstream_cluster_test.go
- server/stream.go
This was allowed before but did not actually assign the filter subject so did not really work. This re-allows it and makes sure it works properly.
Tests are a tad flaky atm but not due to this.
Resolves #3226 
> Allow filtered stream mirrors

- server/consumer.go
- server/jetstream_test.go
When creating a pull consumer with InactiveThreshold set, if the
application is doing pull requests with "no_wait" at regular interval
(lower than InactiveThreshold), the JS consumer should be considered
active and not deleted.
> [FIXED] Pull consumer may be incorrectly removed after InactiveThreshold

- server/client.go
- server/client_test.go
- server/errors.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/monitor.go
- server/server_test.go
> Close leafnode connection when same cluster name detected

- server/consumer.go
- server/jetstream_test.go
This effectively means that requests with batch > 1 will process a message and go to the end of the line.
Ivan, this was considered incorrect behavior hence no option etc.
> Make pull consumers FIFO per message, not per request.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_helpers_test.go
- server/jetstream_super_cluster_test.go
- server/monitor_test.go
- server/mqtt_test.go
- server/norace_test.go
- server/stream.go
As direct access becomes more important through materialized views like KeyValue, and having alternatives to a full blown JetStream consumers is important in future hybrid architectures, this PR introduces two enhancements.
Both of these are opt in and will be easily identified by clients.
1. DirectAccess now uses a queue group and the system allows non-leader replicas to participate.
2. Mirrors can now optionally be a part of the origin's group.
So for the second, this could allow a KV store with multiple mirrors to have a single subject to retrieve a message that operates in a single queue group. Since these are cluster aware, meaning we prefer the ones closer first and only move to a nearby cluster when no interest exists, adding a stream mirror when a large amount of traffic is direct …
> Direct stream access enhancements

- server/errors.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/leafnode.go
- server/opts.go
This allows a soliciting leafnode config to ask that any JetStream cluster assets that are a current leader have the leader stepdown. This will allow a new leader to take over and service direct access.
Resolves #3178 
> Direct access to JetStream resources when a leafnode connection is down.

- .goreleaser.yml
Since v2.7.4 and due to an update of the goreleaser tool, the
server is now installed under "/usr/bin" instead of "/usr/local/bin".
We keep the install in "/usr/bin" but this PR adds symlink so that
"/usr/local/bin" still points to the nats-server.
Resolves #3239
> [ADDED] Symlink for deb/rpm packages

- server/jetstream_api.go
- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
This continues to allow more diversity in hybrid setups combining JetStream and Core.
Also is Request() mux friendly.
> Allows direct get to also do get next for subject with starting sequence

- server/const.go
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
fixes peer removal, simplifies move, more tests
Make sure when processing a peer removal that the stream assignment agrees.
When a new leader takes over it can resend a peer removal, and if the stream/consumer really was rescheduled we could remove by accident.
Also need to make sure that when we remove a stream we remove the node as part of the stream assignment.
If we didn't, if the same asset returned to this server we would not start up the monitoring loop.
Simplify migration logic in monitorStream, to be driven by leader only
Improved unit tests
Added failure when server not in peer list
Move command does not require server anymore
----
fixes FilterSubject crash
----
bumps server version
> fixes peer removal, simplifies move, more tests

- server/jetstream_test.go
- server/stream.go
We use to ignore if the seq was 0, but now would treat it as
a requirement that the stream be empty if header is present but
set to 0.
This relates to client PR: https://github.com/nats-io/nats.go/pull/958
> [CHANGED] JetStream: accept "Nats-Expected-Last-Sequence" with "0"

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
A customer experienced and endless failure to have a stream catchup. The current leader was being asked for a message from a snapshot that was larger than what we had, resulting in EOF which silently failed.
We now detect this and signal end of catchup and redo the bad snapshot if possible.
> Fix for stalled catchup in endless cycle on EOF 

- server/events_test.go
The test was lowering the eventsHBInterval to low value but not
restoring its original value. This would cause some servers to
be considered "orphan" and the shutdown event sent causing their
raft node to be considered "offline", which then would result
in some tests failing with "insufficient resources".
> Fixed a test that was causing others to flap

- server/events.go
- server/jetstream.go
- server/jetstream_cluster_test.go
In some situations, a server may report that a remote server is
detected as orphaned (and the node is marked as offline). This is
because the orphaned detection relies on conns update to be received,
however, servers would suppress the update if an account does not
have any connections attached.
This PR ensures that the update is sent regardless if the account
is JS configured (not necessarily enabled at the moment).
> [FIXED] JetStream: servers may be reported as orphaned

- server/events.go
- server/events_test.go
- server/jetstream_cluster_test.go
- server/jetstream_super_cluster_test.go
- server/leafnode_test.go
- server/monitor.go
- server/monitor_test.go
- server/routes_test.go
- server/server.go
- test/leafnode_test.go
Added http monitoring endpoint /accstatz
It responds with a list of statz for all accounts with local connections
the argument "unused=1" can be provided to get statz for all accounts
This endpoint is also exposed as nats request under:
This monitoring endpoint is exposed via the system account.
`$SYS.REQ.ACCOUNT.*.STATZ`
Each server will respond with connection statistics for the requested
account. The format of the data section is a list (size 1) identical to the event
`$SYS.ACCOUNT.%s.SERVER.CONNS` which is sent periodically as well as on
connect/disconnect. Unless requested by options, server without the account, 
or server where the account has no local connections, will not respond. 
A PING endpoint exists as well. The response format is identical to
$SYS.REQ.ACCOUNT.*.STATZ …
> [Added] account specific monitoring endpoint(s)

- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
Updates to stream mirror config are rejected in cluster mode, but
were not in standalone. This PR adds the check in standalone mode.
> [FIXED] JetStream: stream mirror updates not rejected in standalone

- server/const.go
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
The Move/Cancel/Downscale mechanism did not take into account that since recently, 
the consumer's replica count can be set independently. 
This alters peer selection to have the ability to skip unique tag prefix check for server that will be replaced.
Say you have 3 az, and want to add another server to az:1, in order to replace a server that is the same zone.
Without this change, uniqueTagPrefix check would filter the server to replace with and cause a failure.
The cancel move response could not be received due to the wrong account name.
> Move and cancel fixes

- server/accounts.go
- server/jetstream_test.go
- server/stream.go
For a stream that is RePublish-enabled, the RePublish source configuration (RePublish message filter) was not being evaluated for each ingested message.  Every message ingested by stream would be (re)published.
This PR fixes and adds unit tests.
> Fix and test for RePub src ignored at runtime.

- server/jwt_test.go
fixed by moving activation token generation ahead of:
`aExpClaim.Exports[0].RevokeAt(revPubKey, time.Now())`
Resolves #
-
-
-
> fix jwt unit test by ensuring activation issue time is > expiration

- server/disk_avail_wasm.go
- server/pse/pse_wasm.go
- server/signal.go
- server/signal_wasm.go
- server/sysmem/mem_wasm.go
This should allow NATS Server to build under the `js/wasm` target.
> Stubs for WebAssembly

- server/jetstream_cluster_test.go
- server/raft.go
introduced by 57395bba027cfc67fd4647c750ca121b5e9cb67a
Resolves #
-
-
-
> Fix raft issue where pindex of follower was off by 1

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
Resolves https://github.com/nats-io/nats-server/issues/3264
- On update check if BackOff is defined, MaxDeliver is within range
- Set `o.maxdc` to the new value
- Add tests
> [FIXED] Maximum Deliveries update has no effect

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_test.go
When msgs were expired on restart recovery we could lose track on subsequent restarts of our starting sequence with no additional activity. If a leadership change happened or we were in R1 mode we would lose our starting sequence.
This could happen on low traffic streams with TTLs that frequently would empty the stream and when a server was down possibly before that event happened.
Thanks to @tbeets for the details on how to reproduce!
> [FIXED] Losing stream sequence on multiple restarts and leader changes.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/norace_test.go
If there are more stream names that the current limit of 1024, getting
the list of names would return them all instead of using pagination.
For "stream infos", the Total amount returned would be the API limit
instead of the actual number of streams.
Resolves https://github.com/nats-io/natscli/issues/541
> [FIXED] JetStream/Cluster: Stream names/infos would return bad response

- server/jetstream_cluster.go
- server/norace_test.go
- server/raft.go
- server/stream.go
- Send snapshot only if leader
- When processing snapshot, start with a smaller inactivity interval
that will double up to 10sec or use 10sec directly once we get a
message. Reason for that is that it is possible that the request
for snapshot is sent while the leader has not yet setup the subscription
that receives the requests (or subscription has not fully reached the
cluster).
- Don't remember snapfile on err.
- Do not consider current if we have not had any activity.
- Stabilize stream scale up under active heavy publishing.
- Due to the publish pressure move the check for followers direct subs spinning up til after we stop publishing.
> [FIXED] JetStream: Some scaling up issues

- server/jetstream_cluster.go
- server/jetstream_jwt_test.go
- server/raft.go
in doRemovePeerAsLeader the leader also records the removed peer in the removed set
Resolves #
-
-
-
> fix peer tracking by removing peers before scaledown

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
fixes #3262
also check peer list on every update
Resolves #
-
-
-
> add implementation for consumer replica change

- server/filestore.go
A message block is checking the filestore's cfg.Subjects to see
if it can "intern" the subject or not. The problem is that this
is done under the message block's lock, but not the filestore.
However, during a stream configuration update, the filestore's
cfg field is switched to a new one, causing the datarace.
By making sure we do the switch under all message blocks lock,
we remove the data race (that could be reproduce by running th
test TestJetStreamClusterMoveCancel with -count=10).
We investigating the use of a string interning library but it
showed a little performance degradation that this approach does
not suffer from.
> Fixed data race between UpdateConfif() and subjString

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
Fixed and improved several system instability issues with encrypted state that were a result of block counters being incorrect for message blocks either due to compaction or when messages expired and we would keep markers for sequence state.
> [FIXED] Instability with encrypted systems

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
This avoids marshaling or un-marshaling but also allows subject based permissioning.
> Allow direct get by subject to be all subject based.

- server/jetstream_cluster_test.go
- server/stream.go
The update was not rejected, yet the republish update was not
taking place.
> [FIXED] JetStream: reject stream update with changes to RePublish

- go.mod
- go.sum
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_super_cluster_test.go
- server/leafnode.go
DirectGet needed to be added to the import map to allow cross domain traffic.
However, DirectGets were part of a queue group, and that exposed a bug that would prevent the origin ingest server from a leafnode from processing it for local queue subs since the interest was for the mapping which had no queue context.
> [FIXED] DirectGet working across leafnodes with JetStream Domains.

- server/jetstream_cluster_test.go
Related to PR #3329 that added the test but with incorrect name prefix in order to run on Travis.
> Fixed JS cluster prefix name for Travis run

- server/jetstream_helpers_test.go
- server/leafnode.go
- server/server.go
A test TestJetStreamClusterLeafNodeSPOFMigrateLeaders was added at
some point that needed the remotes to stop (re)connecting. It made
use of existing leafNodeEnabled that was used for GW/Leaf interest
propagation races to disable the reconnect, but that may not be
the best approach since it could affect users embedding servers
and adding leafnodes "dynamically".
So this PR introduced a specific boolean specific for that test.
> Use specific boolean for a leaf test instead of using leafNodeEnabled

- server/stream.go
Resolves #3336:
On stream create, MaxMsgsPer is checked for values != 0 and sets AllowDirect to true if test is true. Unset or explicit 0 in stream request initializes MaxMsgsPer to -1 so test will always be true. Test instead for > 0 (an explicit configuration of messages per subject limit).
Changes made:
Change test from !=0 to >0.
> On stream create, change AllowDirect set test on MaxMsgsPer to > 0

- server/route.go
- server/routes_test.go
A server maintains a map for the subject+queue to know the number
of members on the same group. However, on unsubscribe when we get
to the last one being unsubscribed, we were removing from the map
but then unfortunately adding back with a value of 0, which caused
a leak. If the same subscription was coming back, then this map
entry would be reused, but if it is a never coming back queue sub,
then memory could increase continously.
> [FIXED] Memory leak when unsubscribing the last queue subscription

- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
This would allow in embedded use-cases where the user does not
have the ability to use a credentials file. Instead, a signature
callback is specified and invoked by the server sends the CONNECT
protocol. The user is responsible to provide the JWT and sign the
nonce.
Resolves #3331
> [ADDED] LeafNode: Support for a SignatureHandler in remote config

- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
The new request is available for the system account.
The subject to send the request to is `$JS.API.ACCOUNT.PURGE.*`
With the name of the account to purge instead of the wildcard.
Also added directory cleanup code such that server do not
end up with empty streams directories and account dirs that
only contain streams
Also adding ACCOUNT to leaf node domain rewrite table
Addresses #3186 and #3306 by providing a way to
get rid of the streams for existing and non existing accounts
> Adding account purge operation

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_leafnode_test.go
- server/jetstream_super_cluster_test.go
- server/mqtt_test.go
It is pretty hard to diagnose what went wrong when not enough peers for
an operation where found. This change now returns counts of reasons why
peers where discarded.
**This is a first shot at this and we don't want to reveal too much information.
So please let me know if you think I'm showing too much and/or should
change the format. The intent is that whoever sees this error, has enough 
information to why it failed, without having to rely on logging.**
Changed the error to `JSClusterNoPeers` as it seems more appropriate
of an error for that operation. Not having enough resources is one of
the conditions for a peer not being considered. But so is having a non
matching tag. Which is why `JSClusterNoPeers` seems more appropriate
In addition, `JSClusterNoPeers` was already used as error …
> better error when peer selection fails

- scripts/runTestsOnTravis.sh
- server/jetstream_chaos_cluster_test.go
- server/jetstream_chaos_helpers_test.go
- server/jetstream_helpers_test.go
Resolves #
[[FIXED] Wrong flag in Travis to exclude chaos tests](https://github.com/nats-io/nats-server/commit/60b0180102c78a83afb3f5d10f466fccdfb730d5)  …
The `js_tests` build target was using the wrong tag to exclude chaos 
tests.
As a result, chaos tests would run as part of the default testing.
[Exclude chaos tests helpers from default build](https://github.com/nats-io/nats-server/commit/60ef3e228283673e85610bda5a223a2c70e91437)
> Fix chaos tests build tags for Travis

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
If a cluster is brought down and then partially restarted, the
replica information about the non restarted node would be completely
missing. The CLI could report replicas 3 but then only the leader
and the running replicas, but nothing about the other node.
Since this node's server name is not know, this PR adds an entry
with something similar to this:
```
<unknown (peerID: jZ6RvVRH)>, outdated, OFFLINE, not seen
```
Also, replicas array is now ordered, which will help when using
a watcher or repeating stream info commands in that the replicas
output will be stable in regards to the list of replicas.
> [IMPROVED] Replicas ordering and info regarding unknown in stream info

- server/events.go
- server/events_test.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/monitor.go
Related to # https://github.com/nats-io/k8s/issues/541
Resolves # The JetStream portion of https://github.com/nats-io/nats-server/issues/2687
- Added `/healthz?js-enabled=true` to return error if JetStream is disabled.
- Added `/healthz?js-server-only=true` to skip checking of JetStream accounts, streams and consumers.
> Added param options to /healthz endpoint

- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_test.go
- server/norace_test.go
This PR is to improve the worst case lookup times for direct get by subject, e.g. KV.
When the number of blocks became very large, the linear scan walking backwards for the correct block, and the linear scan walking forward to find the previous entry to delete was becoming slow. This would become evident in > 100M messages or small block sizes, e.g. 4k.
We now use better indexing for lookups by soft tracking the first and last block per subject.
We also improve memory usage by some degree on very large stores by swapping out the per block subject info and swap out the indexing data structures more aggressively.
This approximately doubles the number of messages we can store and manage with direct gets.
More work to be done but this is a start. …
> [IMPROVED] DirectGet performance and memory usage for large streams.

- server/jetstream_cluster_test.go
- server/stream.go
When the origin stream exists, the sourec/mirror filter subject
will be checked against the stream subjects.
If there is no overlap, an error will be returned
> Added check for source/mirror filter subjects

- server/jetstream_cluster_test.go
- server/stream.go
When a stream source filter subject was updated, the internal consumer
was not re created
If the upstream stream contains a tail of previously filtered messages,
these will now be delivered
PLEASE check my method to restart and if my use of mset.setSourceConsumer(s.iname, si.sseq+1) is the right thing to do here. Test etc... look al right. just want to point this one out.
> fixed consumer restart on source filter update

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
- server/stream.go
monitorCluster stops the stream, when doing so, monitorStream
needs to be stopped to avoid miscounting of store size.
In a test stop and reset of store size happened first and then
was followed by storing more messages via monitorStream
Resolves #
-
-
-
> Fix race between stream stop and monitorStream

- go.mod
- go.sum
- server/stream.go
In normal message get, the returned format is RFC3339Nano, which
is what is being used when using JSON marshaling. However, for
the direct get we had to pass a string to construct the header
and we were using time.Time.String() which was using a different
layout. So use ts.Format(time.RFC3339Nano) to be consistent with
the non-direct get message.
Libraries that already parsed the non RFC3339Nano time format
can be updated since none should have been released yet (since
the feature in the server is not released yet)
> Fixed message timestamp formatting for direct message get feature

- server/jetstream_test.go
- server/stream.go
In standalone mode, when attempting to create a stream which has
subjects that overlap with an existing stream, the generic
stream create error "10049" was returned instead of the more
accurate "10065" error code corresponding to subject overlap,
as it was the case in clustered mode.
Resolves #3362
> [FIXED] JetStream: subject overlap error should be returned

- server/auth.go
- server/jwt_test.go
For security reasons we have introduced scoped signing keys to jwt.
They carry user permissions.
Wich is why jwt issued by those keys are not allowed to carry their own permission.
Instead they are copied from the signing key.
If the scoped signing key gets compromised, an attacker can only issue jwt with the permissions of the key.
With a plain signing key, an attacker can create arbitrary user with permissions.
Because user jwt creation is greatly simplified we added a single utility function to go/java/.net which issues user for such keys.
This is function is documented in ADR-14:
```
/**
* signingKey, is a mandatory account nkey pair to sign the generated jwt.
* accountId, is a mandatory public account nkey. Will return error when not set or not account nkey.
* publicUserKey, is a …
```
> Adding templates to scoped signing key user permis

- server/jetstream_chaos_consumer_test.go
- server/jetstream_chaos_helpers_test.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
Add 4 "chaos" tests for
- Durable consumer
- Ordered consumer
- Pull consumer
- Default (async) consumer
These tests are trivial to pass under normal circumstances. In this case, a chaos monkey keeps restarting the cluster.
This is surfacing some issues that would otherwise go unnoticed (discussed separately)
> Chaos tests for Consumers

- dependencies.md
According to go-licenses, github.com/klauspost/compress/s2 is BSD, not Apache License 2.0
> Update dependencies.md [ci skip]

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/raft.go
- server/server.go
This is a regression introduced in v2.8.3. If a message reaches
the max redeliver count, it stops being delivered to the consumer.
However, after a server or cluster restart, those messages would
be redelivered again.
Resolves #3361
> [FIXED] JetStream: issue with max deliver and server/cluster restart

- server/auth.go
- server/jwt_test.go
ordering of templates got messed up by a map (now removed)
Also improved error message when template generation fails
> fix jwt template ordering issue and error message

- server/gateway.go
- server/gateway_test.go
- server/monitor.go
The monitoring http server is started early and the gateway setup
(when configured) may not be fully ready when the `/gatewayz`
endpoint is inspected and could cause a panic.
> [FIXED] Gateway: possible panic if monitor endpoint inspected too soon

- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_errors_generated.go
- server/jetstream_super_cluster_test.go
by adding progress indicators to the error message
> Improve StreamMoveInProgressError

- server/jetstream_chaos_kv_test.go
Add tests for KV while a chaos monkey keeps bouncing the cluster
> Chaos tests for KeyValue

- server/accounts.go
- server/accounts_test.go
- server/sublist.go
- server/sublist_test.go
- Adds new subject mapping functions:
```go
{{SplitFromLeft(wildcard index, position)}}
{{SplitFromRight(wildcard index, position)}}
{{SliceFromLeft(wildcard index, slice size)}}
{{SliceFromRight(wildcard index, slice size)}}
{{Split(wildcard index, deliminator)}}
```
Examples:
```go
shouldMatch("*", "{{splitfromleft(1,3)}}", "12345", "123.45")
shouldMatch("*", "{{SplitFromRight(1,3)}}", "12345", "12.345")
shouldMatch("*", "{{SliceFromLeft(1,3)}}", "1234567890", "123.456.789.0")
shouldMatch("*", "{{SliceFromRight(1,3)}}", "1234567890", "1.234.567.890")
shouldMatch("*", "{{split(1,-)}}", "-abc-def--ghi-", "abc.def.ghi")
shouldMatch("*.*", "{{split(2,-)}}.{{splitfromleft(1,2)}}", "foo.-abc-def--ghij-", "abc.def.ghij.fo.o")
```
- Subject mapping functions can now be all lower case or Pascal …
> - Changes to make adding new mapping functions easier

- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
This is to avoid a narrow race between adding server and them catching
up where they also register as current.
Also wait for all peers to be caught up. 
This also avoids clearing catchup marker once catchup stalled.
A stalled catchup would remove the marker causing the peer to
register as current.
> induce delay prior to scale down

- server/accounts.go
- server/events.go
- server/jwt_test.go
When a request for a system service like $SYS.REQ.ACCOUNT.*.CONNZ
is imported/exported we ensured that the requesting account is identical
to the account referenced in the subject.
In #3250 this check was extended from CONNZ to all $SYS.REQ.ACCOUNT.*.*
requests.
In general this check interferes with monitoring accounts that need
to query all other accounts, not just itself.
There the use case is that account A sends a request with account B
in the subject. The check for equal accounts prevents this.
This change removes the check to support these use cases.
Instead of the check, the default export now uses exportAuth
tokenPos to ensure that the 4th token is the importer account id.
This guarantees that an explicit export (done by user) can only import
for the own account.
This change also …
> Fix bad sys request for different account

- server/jetstream_cluster.go
Saw this panic in code coverage run:
```
=== RUN   TestJetStreamClusterPeerExclusionTag
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x8acd55]
goroutine 97850 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream(0xc002b94780, 0xc001ecb500, 0xc003229b00, 0x0)
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:1653 +0x495
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2953 +0x3b
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine …
```
> Fixed possible panic in monitorStream

- server/jetstream_cluster.go
Missed those when re-running the previous test for longer period
of time.
> Some more checks for cc.meta == nil

- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
Since PR #3381, the 2 tests modified here would take twice as
long (around 245 seconds) to complete.
Talking with Matthias, he suggested using a variable instead of
a const and set it to 0 for those 2 tests since they don't really
need that to be set.
> Reduce length of some clustering tests

- server/consumer.go
- server/jetstream_cluster_test.go
- server/stream.go
This fixes an issue introduced in #3080
The consumer filter subject check was skipped on recovery.
The intent was to bypass the upstream stream subjects.
But it also filtered the downstream stream subject.
This became a problem when the downstream was itself an upstream.
Then during recover, the stream subject was not checked, which
lead to delivery of filtered messages that should never have been
delivered.
-- Detail explanation --
he issue was was introduced by
```
commit f702e279ab4de56f907db10a563a64407fd64831
Author: Derek Collison <derek@nats.io>
Date:   Tue Apr 26 17:06:43 2022 -0700
Fix for a consumer recovery issue.
Also update healthz to check all assets that are assigned, not just running.
Signed-off-by: Derek Collison …
```
> fix consumer subject validation on recovery

- server/auth.go
- server/jwt_test.go
Scoped signing keys allow for optional values in allow rules
If an allow rule therefore gets removed because a tag is not present,
the removal needs to be compensated by adding in a deny >
> fix signing key template processing dropping allow

- server/gateway.go
- server/gateway_test.go
- server/jetstream_super_cluster_test.go
- server/monitor_test.go
- server/server.go
- test/gateway_test.go
- test/leafnode_test.go
We are phasing out the optimistic-only mode. Servers accepting
inbound gateway connections will switch the accounts to interest-only
mode.
The servers with outbound gateway connection will check interest
and ignore the "optimistic" mode if it is known that the corresponding
inbound is going to switch the account to interest-only. This is
done using a boolean in the gateway INFO protocol.
> [CHANGED] Gateway: Switch all accounts to interest-only mode

- server/accounts.go
- server/accounts_test.go
- server/jetstream_cluster_test.go
past processing the import response, c.pa was not reset to the
appropriate state, which lead to an unintended recursion.
(see traces with comments for detail)
The initial change had no check for client/leaf but one unit test failed `TestJetStreamClusterDomainsAndAPIResponses`
So now I only reset the state for client/leaf node. 
But I'm not 100% sure why not doing it for routes/gateway would matter.
We are done with the response, so we shouldn't keep the re-written subject around.
To be on the safe side we also added a reset when we did make the switch.
Don't think it's strictly necessary, but we didn't want to risk it.
added traces with explanations
```
start
processMsgResults dsubj: 'q1.a' reply: 'q2.inbox'
deliverMsg 'q1.a' reply: 'q2.inbox'
import sub subject: 'q1.a' reply 'q2.inbox' …
```
> [FIXED] Service import response invoking svc import

- server/const.go
- server/jetstream_cluster.go
scale down happened too soon
when currentCount != replicas
> Scale down

- server/monitor.go
- server/monitor_test.go
- server/server.go
Add basic peer certificates information in /connz endpoint when
the "auth" option is provided.
```
{
"server_id": "NDA6JPO2S27UL7QCA5OO7LP5JT324OMEYXTNEWDCSH2JRJYORSMW4HWD",
"now": "2022-08-24T20:15:58.287276Z",
"num_connections": 1,
"total": 1,
"offset": 0,
"limit": 1024,
"connections": [
{
"cid": 4,
"kind": "Client",
"type": "nats",
"ip": "127.0.0.1",
"port": 55361,
"start": "2022-08-24T20:15:58.275853Z",
"last_activity": "2022-08-24T20:15:58.284893Z",
"rtt": "9.041ms",
"uptime": "0s",
"idle": "0s",
"pending_bytes": 0,
"in_msgs": 0,
"out_msgs": 0,
"in_bytes": 0,
"out_bytes": 0,
"subscriptions": 0,
"lang": "go",
"version": "1.16.0",
"tls_version": "1.3",
"tls_cipher_suite": "TLS_AES_128_GCM_SHA256",
"tls_peer_certs": [
{
"subject": "CN=localhost,OU=nats.io,O=Synadia,ST=California,C=US", …
```
> [ADDED] Monitoring: TLS Peer Certificates in Connz when auth is on

- server/consumer.go
- server/norace_test.go
- server/stream.go
We now hold stream locks through storage and use a separate lock for the consumer list and any storage updates from the store level.
> CAS operations improved,

- main.go
Can fail in some embedded systems.
> Don't fail if auto setting of maxprocs fails.

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/jetstream_leafnode_test.go
- server/parser.go
There was a way to detect a cycle but I believe it needs to be
a stack of "si" not just the one before invoking processServiceImport.
Changes in #3393 would solve issue reported with test TestAccountImportCycle,
but would not address the new reported issue represented by new test
TestLeafNodeSvcImportExportCycle. This current approach seems to solve
all known cases.
Resolves #3397
Replaces #3393
> [FIXED] Service import/export cycles causing stack overflow

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
This was due to the fact that we updated the accounting and then checked if we needed to load state which would then fallback to generating the state on the fly.
> When writing a msg after the fss state was expired we would count the msg twice.

- server/consumer.go
- server/errors.json
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
New consumer create that allows elevation of the stream and consumer names, and optional filter subject to the request subject.
Similar to changes in direct get allows proper security if needed for filter subject selection.
> [IMPROVED] Secure consumer create

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/opts.go
- server/server.go
The original value was hardcoded to 128MB and 32MB per stream. The
per-server limit is lowered to 32MB but is configurable with
a new configuration parameter:
```
jetstream {
max_catchup: 8MB
}
```
The per-stream limit was also lowered from 32MB/128,000msgs to
8MB/32,000 messages.
Tests have shown no difference in performance for fast links.
> [ADDED] JetStream: Ability to configure the per server max catchup bytes

- server/gateway.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_helpers_test.go
- server/jetstream_super_cluster_test.go
- server/norace_test.go
- server/raft.go
- server/server.go
- server/stream.go
We will not optionally compress raft traffic and stream catchup messages iff all peers support it. Current threshold (fixed atm) is 4k for review.
Improved stream and consumer moves.
> Allow optional compression in raft and stream catchup, move improvements for streams and consumers

- server/jetstream_cluster.go
> Bump back the defaultMaxTotalCatchupOutBytes to 128MB

- server/events_test.go
- server/jetstream_benchmark_consume_test.go
- server/jetstream_benchmark_publish_test.go
- server/jetstream_chaos_helpers_test.go
- server/jetstream_helpers_test.go
- server/jwt_test.go
- server/reload_test.go
- server/routes_test.go
- server/server_test.go
- server/test_test.go
- test/cluster_test.go
- test/routes_test.go
- test/test.go
- test/test_test.go
- Minor refactoring of test utilities
- Jetstream publish benchmark (sync/async, small/medium messages, single-server/cluster, ...)
- Jetstream consume benchmark (push/pull, ordered/unordered, durable/ephemeral, small/medium messages, single-server/cluster, ...)
Example (localhost) output:
```
❯❯❯ go test --run BenchmarkJetStream --bench BenchmarkJetStream -timeout 30m
goos: darwin
goarch: arm64
pkg: github.com/nats-io/nats-server/v2/server
BenchmarkJetStreamConsume/N=1,R=1,MsgSz=10b/PUSH[Sync,Ephemeral]-8               1000000              1459 ns/op           6.85 MB/s             0 %dupe                 0 %error
BenchmarkJetStreamConsume/N=1,R=1,MsgSz=10b/PUSH[Async,Ephemeral]-8              1000000              1123 ns/op           8.90 MB/s             0 %dupe                 0 …
```
> Publish and consume JS benchmarks

- server/jetstream_test.go
- server/stream.go
We detected overlap between different streams for subjects but not same stream with multiple subjects configured.
> [FIXED] Do not allow overlap between multiple subjects for a stream.

- server/events.go
- server/jetstream.go
- server/jetstream_cluster_test.go
- server/jetstream_super_cluster_test.go
In some rare situations, it is possible that nodes are added
to the cluster but are not properly tracked and not shown as
offline when they exit the cluster.
Relates to #3258
> [FIXED] JetStream: Some nodes may never be reported as offline

- conf/lex.go
- conf/lex_test.go
- conf/parse_test.go
If a configuration variable starts with numbers and has a character
that such as K/k/G/g/etc.. it would assume that it was a number
(expressed in Kb, Gb, etc..).
This PR checks that if the special characters are not the suffix,
that is, the variable does not end after those characters, then
the parsing will treat the whole thing as a string.
Resolves #3431
> [FIXED] Parsing of strings starting with numbers and K/G/etc.. suffix

- server/sublist.go
- server/sublist_test.go
The server was not properly handling queue subscriptions internal
notifications which could lead to messages not being delivered
to applications using a queue group to consume from a JetStream
consumer after they were restarted.
Resolves #1066
> [FIXED] JetStream: Restarted queue subscriptions may not receive msgs

- server/benchmark_publish_test.go
Resolves #
- Add a NATS core Publish benchmark in `server` (varying message size, number and type of subscribers)
> NATS Publish benchmark

- server/consumer.go
- server/jetstream_test.go
Still required for WorkQueue retention policy streams.
> NoAck allowed now on pull consumers

- server/monitor.go
- server/monitor_test.go
This makes the `reserved_memory` and `reserved_storage` quotas for an account to be filled. For example given the following configuration:
```hcl
accounts {
sys {
users = [{ user: 'sys', pass: 'sys' }]
}
a {
users = [{ user: 'foo', pass: 'foo' }]
jetstream {
max_mem: 500mi
max_store: 1gi
}
}
```
Now making a request to `http://127.0.0.1:8222/jsz?accounts=true` it would make the reserved_memory and reserved_storage show up instead of 0s:
```js
"account_details": [
{
"name": "a",
"id": "a",
"memory": 0,
"storage": 28956,
"reserved_memory": 524288000,
"reserved_storage": 1073741824,
"accounts": 0,
"ha_assets": 0,
"api": {
"total": 0,
"errors": 0
}
}
]
```
Also fixes `$SYS.REQ.ACCOUNT.*.JSZ`:
```
nats req -s 'nats://sys:sys@127.0.0.1:4222' '$SYS.REQ.ACCOUNT.a.JSZ' '{"streams": true, …
```
> js: add per account reserved mem/store bytes

- server/jetstream.go
- server/jetstream_cluster.go
Only complain about leaderless group with previous leader if we know JetStream has been running for some threshold.
> Suppress leaderless claims if JetStream just started.

- server/server.go
When using `Trusted Operators` the output is showing 1970 as expire date:
```
[87502] 2022/09/07 20:27:20.600022 [INF] Trusted Operators
[87502] 2022/09/07 20:27:20.600024 [INF]   System  : ""
[87502] 2022/09/07 20:27:20.600026 [INF]   Operator: "my_org"
[87502] 2022/09/07 20:27:20.600056 [INF]   Issued  : 2022-09-06 20:24:43 +0200 CEST
[87502] 2022/09/07 20:27:20.600060 [INF]   Expires : 1970-01-01 01:00:00 +0100 CET
```
this patch replaces the Expires null date with "Never"
> server: expire display Never instead of 1970

- server/jetstream_api.go
- server/norace_test.go
Resolves #
- Adds pagination to the JS Stream Info API (backwards compatible) that was previously hard-coded to a max number of 100K subject states
> Adds pagination to stream info

- server/consumer.go
- server/jetstream_test.go
- server/norace_test.go
Prepping for pull consumer increased usage in clients.
1. Do better accounting on per message basis of bytes used for MaxBytes in pull requests.
2. Always used the MaxBytes allowed unless first delivery.
3. Fixed bug that would cause us to expire one shots on hitting max ack pending.
Resolves #3455 
> [IMPROVED] Pull request logic

- server/errors.json
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_super_cluster_test.go
This error was introduced in #3342 and reveals too much information 
This change gets rid of cluster names and peer counts.
All other counts where changed to booleans,
which are only included in the output when the filter was hit.
In addition, the set of not matching tags is included.
> changed format of JSClusterNoPeers error

- server/accounts.go
- server/accounts_test.go
Resolves a small bug in the {{Split()}} subject  mapping function - and of course I just noticed that bug right after 2.9.0 is released :(
> [FIXED] Edge condition handling in {{Split()}} subject mapping function

- server/jetstream_cluster.go
Signed-off-by: Deepak <sah.sslpu@gmail.com>
- [n/a] Documentation added (if applicable)
- [n/a] Tests added
Resolves #3469
-
-
-
> Fix peer randomisation when creating consumers groups for replica=1

- server/consumer.go
- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
Resolves #
When creating a Consumer with specified both Durable and Name, eats-server was overriding Name with Durable value.
- Error if both Name and Durable are specified, but not equal
> Add error if Consumer Name and Durable are not equal

- server/jetstream_cluster.go
This was discovered by new test TestJetStreamClusterRemovePeerByID. I saw this on Travis and repeating the test locally with -count=10 I was able to reproduce. The issue is cc.meta being nil but accessing cc.meta.ID() directly.
> [FIXED] JetStream: possible panic on peer remove on server shutdown

- server/consumer.go
- server/jetstream_test.go
If the client pull requests has a max_bytes value and the server cannot deliver a single message (because size is too big), it is sending a 409 to signal that to the client library. However, if it sends at least a message then it would close the request without notifying the client with a 409, which would cause the client library to have to wait for its expiration/timeout.
> [FIXED] JetStream: Pull requests closed due to max_bytes were silent

- server/consumer.go
- server/events.go
- server/events_test.go
- server/gateway.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
- server/monitor.go
- server/monitor_test.go
- server/mqtt.go
- server/mqtt_test.go
- server/norace_test.go
- server/route.go
- server/server.go
- server/stream.go
A request to `$SYS.REQ.SERVER.PING.JSZ` would now return something
like this:
```
...
"meta_cluster": {
"name": "local",
"leader": "A",
"peer": "NUmM6cRx",
"replicas": [
{
"name": "B",
"current": true,
"active": 690369000,
"peer": "b2oh2L6w"
},
{
"name": "Server name unknown at this time (peerID: jZ6RvVRH)",
"current": false,
"offline": true,
"active": 0,
"peer": "jZ6RvVRH"
}
],
"cluster_size": 3
}
```
Note the "peer" field following the "leader" field that contains
the server name. The new field is the node ID, which is a hash of
the server name.
Related to #3473
> [ADDED] JetStream: peer (the hash of server name) in statsz/jsz

- server/filestore.go
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
- server/memstore.go
- server/stream.go
Require general DiscardNewPolicy to bet set as well.
> Allow discard new per subject for certain KV type scenarios.

- server/auth.go
- server/leafnode_test.go
If the `no_auth_user` is set in the `websocket{}` block and a server creates a leafnode connection using the websocket port, and does not provide credentials, that no_auth_user should be used, but was not.
> [FIXED] LeafNode: connecting using websocket and no_auth_user

- server/client.go
Resolves #3496 
Protocol errors print arguments that contain arbitrary []byte and are possibly not formattable strings; use %q to escape
> [FIXED] Format protocol error []byte with %q

- server/consumer.go
It could be that while the routine processing the consumer assignment runs the stream is being stopped, which would lead to a panic.
> [FIXED] JetStream: prevent panic on consumer assignment

- server/filestore.go
The write cache may be pinned for longer than needed when creating
a new write block. This could be seen in some benchmark tests.
The old block cache would be kept for 5 more seconds, which, with
a fast rate of inserts could start to show in some memory profiling.
This was a change introduced in https://github.com/nats-io/nats-server/pull/3351
which was different than code in v2.8.4
> [FIXED] JetStream: File store memory usage

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
Updating a consumer configuration from say R3 to R1 would work but no response was received by the client sending the request.
Resolves #3493
> [FIXED] JetStream: Scale down of consumer to R1 would not get a response

- server/jetstream_cluster.go
Originally, createRaftGroup() would not hold the jetstream's lock for the whole duration. But some race reports made us change this function to keep the lock for the whole duration. A test called TestJetStreamClusterRaceOnRAFTCreate() was demonstrating the race between "consumer info" request handling and createRaftGroup code. Since then, the race has been fixed, so this PR restores the more fine-grained locking inside createRaftGroup.
Resolves #3516
> [FIXED] JetStream: unresponsiveness while creating raft group

- main.go
The usage message for nats core does not contain all the exisitng options for setting up the host
https://github.com/nats-io/nats-server/issues/3522
Updates the usage guide for nats server
> fix to  bug  #3522 - update usage guide message in main.go

- server/consumer.go
- server/errors.json
- server/jetstream_cluster_3_test.go
- server/jetstream_errors_generated.go
- server/stream.go
If a stream is created or updated with a negative replicas count, and error is now returned. Same for consumers.
> [FIXED] JetStream: return error on negative replicas count

- server/consumer.go
We don't seem to release the read lock if `LoadMsg` fails, which could result in unexpected lock contention.
Spotted by [ashumkin](https://github.com/ashumkin).
> Add missing `RUnlock` in `needAck`

- server/jetstream.go
- server/jetstream_cluster_3_test.go
- server/server.go
If an ephemeral was given a name by the user, if the consumer leader was then shutdown, the ephemeral would be migrated using a server generated new name instead of keeping the user given name.
Also, in some cases the migration would not even occur. This was likely due to the fact that RAFT node(s) were shutdown prior to the ephemeral migration code was invoked.
Resolves #3550
> [FIXED] JetStream: User given named ephemeral lost after migration

- server/filestore.go
If the server is unable to write to disk, there is a failure mode that results in the fss map being nil when writing message block data to it, resulting in a panic. This fix checks whether an error is returned by the function that loads the fss map, and if so, returns an error to prevent future assignment.
This issue was brought up in matrix-org/dendrite#2796. I'm not sure if it's appropriate to return early if an error is encountered, or to simply allocate the map and continue with the function. Or perhaps I could add an explicit check for whether the error returned is an "out of space" error and only return in that instance. Please let me know if there's a better alternative, thanks!
- Fix panic that occurs when disk is full
> fix: Prevent nil map assignment panic if disk is full

- server/client.go
- server/routes_test.go
Originally, only solicited routes were retried in case of a disconnect, but that was before gossip protocol was introduced. Since then, two servers that connect to each other due to gossip should retry to reconnect if the connection breaks, even if the route is not explicit. However, server will retry only once or more accurately, ConnectRetries+1.
This PR solves the issue that the reconnect attempt was not initiated for a "solicited route" that was not explicit.
Maybe related to #3571
> [FIXED] Solicited route may not retry to reconnect

- server/jetstream_cluster.go
> Make sure to stop raft nodes on all monitor exits.

- server/consumer.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/server.go
We still will signal R1 pull consumers with pending requests.
Also fixed a bug that would not honor replicas for new style named consumers.
> Removed ephemeral consumer migration.

- go.mod
- go.sum
> Update Go client to release 1.19.0

- server/leafnode.go
- server/leafnode_test.go
The LS+ would be sent for existing subscriptions upon leafnode connect but then would be silently denied due to permissions violations. This would make it tough for anyone with only access to the leafnode to understand why a request might be getting NoResponders.
We now do not allow existing subs to pass, so a trace log on the leafnode would not show an LS+ for the service subject.
If the LS+ does get through we debug log that it was denied.
> [FIXED] Existing subs would be sent to leafnodes even though they violated permissions.

- server/auth.go
- server/auth_test.go
- server/client.go
- server/server_test.go
This will be used mainly by CustomClientAuthentication implementations to indicate that the user connection should be disconnected at some point in future - like when a certificate or token expires
> adds the notion of a connection deadline to User

- server/jetstream_cluster.go
Very difficult to reproduce. Had to run TestJetStreamSuperClusterMoveCancel in covermode=atomic on a slow machine to hit the condition where the monitorConsumer go routine is started by RAFT node is nil, which caused the warning message to produce the panic (since n is nil)
> [FIXED] JetStream: possible panic on some rare cases

- server/leafnode.go
- server/leafnode_test.go
This is specific to setup described [here](https://github.com/nats-io/nats-server/issues/3191#issuecomment-1296974382) and does not require JetStream to be reproduced. The added test reproduces the above setup but without JetStream enabled in the accounts.
Each cluster has a leafnode for a given account to the other cluster. The accounts import/export a subject. When a consumer is connected to cluster "B" and the producer is on cluster "A" there was a duplicate message. Due to shadow subscription caused by the import/export rules, an additional subscription was sent across the leafnode.
Resolves #3191
> [FIXED] LeafNode: possible duplicate messages in complex setup

- server/consumer.go
- server/jetstream_cluster_3_test.go
> [FIXED] Notifying waiting pull consumers on consumer or parent stream deletion.

- server/jetstream_cluster_3_test.go
- server/stream.go
If start by time is before what we remember during recovery use that instead
Resolves #3559
> [FIXED] JetStream: Sources with OptStartTime gets redelivered

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
If a stream R2 had one of its server network-partitioned and at that time the stream was edited to be scaled down to an R1 it would cause the stream to no longer have quorum even when the network partition is resolved.
> [FIXED] JetStream: Stream scale down while it has no quorum

- server/reload.go
- server/route.go
- server/routes_test.go
- server/server.go
The server was not setting "server name" in the TLS configuration for route connections, which may lead to failed (re)connect if the certificate does not allow for the IP and the URL did not have the hostname, which would happen with gossip protocol.
> [FIXED] Routing: TLS connections to discovered server may fail

- server/accounts.go
- server/route.go
- server/routes_test.go
- server/server.go
- Save the TLS name only if not already set
- Use the passed URLs slice instead of using s.getOpts().Routes
- Enhanced the test
- Fixed an unrelated DATA RACE report
> Updates to PR #3611

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/test_test.go
> [FIXED] Enforce HA asset limits during peer processing as well as assignments.

- server/accounts.go
- server/jwt_test.go
Suppose an account is updated to have the following weighted mapping:
```
foo -> bar 40%
```
The server automatically adds foo -> foo at 60%. Sending messages to "foo" will result in the expected distribution of 60% messages going to "foo" and 40% going to bar.
However, if a successive update is pushed to the server(s):
```
foo -> bar 40%
foo -> baz 60%
```
The subject mapping should now be as described, that is, no more mapping from "foo" to "foo" and 40% to bar and 60% to baz, however, what was happening is that the server would always use the original mapping.
> [FIXED] Weighted subject mappings updates not applied

- server/jetstream.go
- server/monitor_test.go
- server/server.go
Surface unique_tag (if set as a JetStream option on a server) in varz and jsz.  This provides an operational debugging and configuration validation data point (e.g. unique_tag MUST be uniform across all servers in a SuperCluster).
> add unique_tag to JetStreamConfig for varz/jsz visibility

- server/fuzz.go
This was causing the test to overrun mem limits.
> Set max payload in gofuzz test

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/memstore.go
- server/store.go
When determining whether we need an ack, no need to copy since under consumer lock.
> [IMPROVED] Don't copy pending on needAck check.

- server/jetstream_api.go
- server/jetstream_cluster_3_test.go
It is possible that a stream info request would be handled at a time where the raft group would not yet be set/created, causing a panic.
Resolves #3626 (at least the panic reports there)
> [FIXED] JetStream: possible panic on stream info when leader not elected

- server/consumer.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
Also modified some of the auto-cleanup logic for pull consumers.
Resolves #3630 
> [FIXED] Allow any type of ack to suppress auto-cleanup of consumer.

- server/stream.go
Creating source consumers used this but mirrors were overlooked, this fixes that.
> [FIXED] Make mirror consumers use filtered version of consumer create

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
A stream with a WorkQueue retention policy is supposed to allow more than one consumer if they user filtered subjects, but those subjects should not overlap.
There was an issue that if a new consumer had a filter subject "wider" than an existing one, the error was not detected and the new consumer was incorrectly accepted.
Resolves #3639
> [FIXED] JetStream: WorkQueue not preventing overlapping consumers

- server/consumer.go
- server/jetstream_test.go
If a pull consumer with an inactivity threshold ack'd a msg then immediately deleted the consumer, the server could crash.
Resolves #3657 
> [FIXED] Server might crash on pull consumer delete.

- server/auth.go
- server/client_test.go
- server/server.go
> If no_auth_user is set, clear auth required from server info to client.

- server/events.go
- server/events_test.go
- server/monitor_test.go
This will avoid write locks and any non-static data.
> Add a system account responder for IDZ along with STATSZ etc.

- server/consumer.go
Resolves #
- Adds account, stream and consumer names to the consumer assignment not cleaned up warning
> Add account, stream and consumer name to consumer alignment cleanup warning

- server/jetstream_benchmark_consume_test.go
- server/jetstream_benchmark_kv_test.go
- server/jetstream_benchmark_publish_test.go
Lower minimum amount of data / number of operations so that benchmarks  can run in reasonable time.
Minimum amount of work should be controlled via `-benchtime` flag. But  due to these hardcoded limits, some tests were taking too long.
e.g. Running for 2 minutes even with `-benchtime` set to 1 second.
- Lower the minimum hardcoded amount of work in JS benchmarks
In some cases, the hardcoded minimum was too high, leading to a benchmark taking **minutes**, even if `-benchtime=1s` (or similar). 
> Adjust minimum workload of JetStream benchmarks

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/stream.go
This requires stream requests for the same stream be received before any assignments have been quorum'd.
First issue was applications not getting any response. However, there was also a more serious issue that would create multiple raft groups for each concurrent request. The servers would only run one stream monitor loop, however they would update the state to the new raft group's name, so on server restart the stream would be using a different raft group then existing servers.
Also added in protection for when the meta-leader knows about the stream assignment and wants to convert it to a stream info call but the leader has not been elected yet.
Resolves #3677 
> [FIXED] Multiple issues with concurrent stream create requests.

- server/filestore.go
This avoids full state outputs for streams with many deleted items
> Do not gather full state for snapshots

- server/filestore.go
- server/norace_test.go
- server/raft.go
- server/store.go
The bug was when a timestamp for the pending state was exactly -1 which could happen based on timing of the redlivered pending items which would set pending.Timestamp into the future potentially and the timing on the encodeConsumerState call.
Minor fixes to raft.
Resolves #3535 
> [FIXED] Fix for server panic when consumer state was not decoded correctly.

- server/accounts.go
- server/jetstream_jwt_test.go
Whenever an account was disabled and then reenabled, JS would not have been active until server restart because the state was not reset in memory in the server. 
Resolves #3655
> Fix to reenable JetStream for account when reactivated

- server/client.go
This change is required to ensure failover of leaf node connections
This contribution is my original work and I license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)
> Fix for #3682 (Take 2): do not delay PINGs for GATEWAY or spoke LEAF connections

- server/jetstream_jwt_test.go
This was causing longer than necessary startup times since by default they would have been using the same temporary directory and the extra account lookup failures due to a previous JS run using different accounts and leaving those artifacts in the shared folder. Also renamed some of these tests to be possible to run them via `-run TestJetStreamJWT`.
> Fix JWT tests JS store dir

- server/log.go
- server/stream.go
With the increase use of subject based limits not being able to store due to limits exceeded happens frequently and makes running the server in debug quite noisy, so we rate limit this log line even in debug
> Rate limit frequent debug log lines

- server/events_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
- server/monitor.go
When js-enabled is set to true, the condition was only checked if
the `getJetStream()` call returned `nil`. However, if it non-nil,
all remaining checks were executed, including assessing the health
of the assets (streams and consumers).
This change addresses two issues:
- Switch to use `js.isEnabled()` which will check whether the value
is nil OR `js.disabled = true` which can occur if the subsystem
is temporarily disabled (insufficient resources).
- Correctly exit the check after the assertion and before meta and
asset checks are performed.
In addition, the option has been renamed to `js-enabled-only` to align
with the `js-server-only` naming. The previous `js-enabled` name still
works, but is mapped to this new option. A warning is emitted noting
the previous option is deprecated.
Fix …
> Fix /healthz?js-enabled=true behavior

- server/consumer.go
- server/norace_test.go
- server/stream.go
When a stream had a large number of consumers on a server that were sparse, the signaling mechanism would do a linear scan to signal matching consumers. As usage patterns have continued to have more consumers that are filteres and sparse, meaning a message is destined for a single or small number of consumers.
This change moves selection to a sublist that tracks only active consumer leaders for selection, which optimizes selection of consumers to signal when the number of consumers is large.
> Improve performance and latency with large number of sparse consumers.

- server/jetstream_cluster_3_test.go
- server/raft.go
Resolves [Issue #3712](https://github.com/nats-io/nats-server/issues/3712)
If the leader peer of a clustered memory-store stream was restarted, stream would become no quorum after the peer returned.
> fix and test for clustered mem store asset no-quorum if leader restarted

- server/filestore.go
- server/filestore_test.go
Under the right circumstances Compact could leave a dangling last msg block leading to `error opening msg block file [""]: open : no such file or directory`
When the compaction would not uplevel to a normal purge, but after completion all msg blocks were empty the mb.lmb was not cleared or reset properly.
Resolves #3652 
> [FIXED] Failure to store msg with `error opening msg block file [""]: open : no such file or directory`

- docker/Dockerfile.nightly
Use v2 form to fetch the nsc tool which is now supported in that repo.
> Update nsc go install to use go modules

- server/monitor.go
This fixes a backwards incompat change introduced in #3704 for library usage as well as using the healthz NATS API which depends on the JSON payload.
Signed-off-by: Byron Ruth <byron@nats.io>
> Add back existing HealthzOptions.JSEnabled field

- server/accounts.go
- server/accounts_test.go
- server/jetstream_test.go
When a leafnode connection is bound to an account where there was already a wildcard response import subscription to handle the requests (e.g. `_R_.foo.>`), this would have created message duplicates due to an extra subscription being created that also matched the wildcard (e.g. `_R_.foo.bar`). To avoid this condition, we now skip creating the latter extra subscription for leafnode connections.
Fixes #3191 #2694 
> Fix dup msgs when leafnode binds to account with service imports

- server/filestore.go
- server/jetstream_test.go
- server/monitor.go
If a stream's meta was not properly written but the file existed, we could re-add the stream but a subsequent restart would lose the stream again.
Also added in healthz for single server systems to make sure all stream directories resulted in recovered streams.
> Healthz works on single server systems and allow recovery if stream meta not flushed.

- .golangci.yml
- conf/lex.go
- conf/parse.go
- scripts/runTestsOnTravis.sh
- server/accounts.go
- server/auth.go
- server/dirstore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
- server/jetstream_leafnode_test.go
- server/jetstream_test.go
- server/mqtt.go
- server/mqtt_test.go
- server/norace_test.go
- server/opts_test.go
- server/route.go
- server/server.go
- server/websocket_test.go
- test/test.go
This replaces the separate linters in `runTestsOnTravis.sh` with the more modern `golangci-lint`. This is the recommended approach now and also means that the `gopls` language server stands a much better chance of picking up the same issues that CI will.
It also adds a `.golangci-lint.yml` file to control the linter behaviours, as well as fixing a few things in the code that it yelled about.
There are more linters we can enable in the future if we want to — I commented out a few but they can be addressed in separate PRs.
> Switch to `golangci-lint`

- server/service_windows.go
- server/service_windows_test.go
The startup delay when starting as a service under windows was set to 10 seconds.
This value was fixed and hardcoded since before JetStream. On (some) Windows systems, this leads to service startup failures, as the store dir sorting may be hindered by an important load, or slowed down by increased accesses times, typically from security software influence.
This commit allows overriding the startup delay using an environment variable NATS_STARTUP_DELAY. This variable is checked outside init() to allow reporting into the service log.
Any value can be used (even lower than the initial 10s). Bare NATS start can be far faster than 10s. Ops may want to setup this env var to lower values in order to trigger an error on stricter constraints.
Resolves #3742 
- make max startup delay of server a …
> Set startup time with env NATS_STARTUP_DELAY

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
This could lead to missing consumers for R1s that were assigned to a server while it was down and on restart the metaleader had snapshotted it's meta state.
> Ensure we add in new consumers from a meta snapshot from the leader.

- go.mod
- go.sum
This PR bumps the dependency `golang.org/x/crypto` to `v0.5.0` to increase security and performance.
> Upgrade the dependency golang.org/x/crypto to `v0.5.0`.

- server/jetstream_cluster_2_test.go
- server/jetstream_helpers_test.go
- server/leafnode.go
- server/raft.go
When migrating leaders off a server when the leafnode is not connected, also ensure leaders can not return until reconnected.
> Set and clear observer state for servers with disconnected leafnodes.

- server/accounts_test.go
- server/client.go
- server/client_test.go
- server/websocket.go
- test/cluster_test.go
Previously, dynamically-sized buffers were used and discarded often in the client outbound queues. This PR removes the dynamic sizing and instead replaces them with fixed-size coalesced buffers, as well as a `sync.Pool` to enable efficient buffer reuse. The result is that the server now allocates dramatically less memory when sending data to clients.
The following results are generated by running `-bench=BenchmarkJetStreamConsume -benchtime=100000x -memprofile=`.
Memory allocations on `main` (2.9.10) as of this morning:
Memory allocations on this PR:
I don't know if this will make a huge difference to throughput in the usual case, but for servers that are pushing a lot of traffic or handling a large number of concurrent clients, this should reduce the GC burden noticeably and, with any …
> Refactor client outbound queues

- server/jetstream_api.go
- server/jetstream_test.go
Single token subject filters were ignored.
> Fix not validating single token filtered consumer

- server/events.go
- server/events_test.go
- server/monitor.go
- server/monitor_test.go
This PR adds a `profilez` endpoint to the system account, which accepts two parameters: `profile` for the name of the profile (i.e. `allocs`, `block`, `goroutine`, `heap`, `mutex`, `threadcreate`) and `debug` for the return format (defaults to `0`, which is usually gzipped for `go tool pprof`).
It will only be possible to query this endpoint if `PROF_PORT` is already enabled, otherwise it will return a `Profiling is not enabled` error.
> Add `profilez` server endpoint

- server/auth.go
- server/client.go
- server/events.go
- server/gateway.go
> Fix some typos in code comment

- server/leafnode.go
Currently the logic here doesn't feel too tight — currently we are only checking movement upward if `n` is exactly 0, and movement downward can be triggered again even if we're already below 0.
This new line should be clearer and more explicit that we're trying to capture *transitions* to/from +ve and -ve only.
> Tweak logic for sending leaf node subscription updates

- server/auth_callout.go
- server/leafnode.go
The auth request, the `sub` for the JWT is `nats-authorization-request`, and the `aud` is the nkey, typically our JWTs have `sub` be an identity and the `aud` is just a string describing where this jwt is applicable.
> [CHANGE] [AC] flip aud and sub for consistency

- server/accounts.go
- server/auth_callout_test.go
- server/events.go
- server/events_test.go
Make sure connection events during auth callouts are correct.
Fixed one extraneous account update for $G. We sent for the addition before switching but suppressed the change back to 0. We now suppress all for $G as was designed.
> Auth-Callout connect events

- server/consumer.go
`consumer.sigSub` was never actually assigned, so subjects were evaluated and created every time `signalSub` was called, as 
```
if o.sigSub != nil {
return o.sigSub
}
```
was never true.
> Assign signal subscription to consumer when created

- server/jetstream_cluster_2_test.go
- server/stream.go
This fixes #3803 by allowing `RePublish` to be edited on an existing stream.
The `TestJetStreamClusterRePublishUpdateNotSupported` test that was previously checking that it couldn't be updated has been renamed and rewritten to prove that modifying `RePublish` on an existing stream works as intended.
> Allow editing `RePublish` on an existing stream

- server/jetstream_cluster.go
During restart if the stream existed in the server's state but was also in a meta-snapshot delivered by the leader we would not process the update properly.
Resolves #3636 
> [FIXED] Properly process updates on a stream on restart.

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/monitor.go
- server/raft.go
If messages are being async published faster than the cluster can apply Raft updates, then the `HEALTHZ` check will report unhealthy, even if we are still making forward progress. This might cause problems in instances where hosting infrastructure will restart the NATS Server if it reports an unhealthy state for a certain period of time, for example.
Adding a slight tolerance to the health check should improve this situation and report only if we are provably not making forward progress. There's also a unit test that demonstrates the problem.
> Add small tolerance in stream health check

- server/consumer.go
- server/errors.json
- server/jetstream.go
- server/jetstream_cluster_3_test.go
- server/jetstream_errors_generated.go
- server/mqtt.go
- server/mqtt_test.go
- server/opts.go
- server/stream.go
Consumers must match replica of parent stream if interest based policy retention.
For MQTT, this was ill-advised by me, not understanding that the messages stream for MQTT was interest policy based. Interest policy based streams require consumers to match the replica count.
> [FIXED] Force consumer replicas to match for interest policy streams

- .golangci.yml
This will create linter warnings on `fmt.Print`, `fmt.Printf` and `fmt.Println`, except for in unit tests and a couple sanctioned places.
> Lint warnings on `fmt.Print`, `fmt.Printf`, `fmt.Println`

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/jetstream_test.go
- server/stream.go
- server/subject_transform.go
- server/subject_transform_test.go
Adds support for subject mapping transforms in streams
Introduces the following changes:
- Extracts subject transform code and tests from accounts.go to it's own separate set of files.
- Ability to add a subject mapping transform destination to sourced streams, allowing to map message subjects as they are received from the stream being sourced
- Ability to source more than once from the same stream, each time using a specific subject filter and destination transform
- Ability to add a stream input subject mapping transform to a stream which will not act as a filter but will transform the subject of messages matching the transform's source according to the transform's destination. This mapping happens regardless of how the messages are received into the stream (mirror, or subject(s) and/or …
> [ADDED] Stream subject mapping transforms

- server/consumer.go
- server/jetstream_test.go
This adds new status requested by #3816 
It is consistent with other statuses with pending data headers.
It can break simplification clients, or thos exposing full `Request` config (max_bytes and batch).
That is reflected in the need of test adoption.
> Add batch completed status to Pull Consumers

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
Adds `Metadata` field to `ConsumerConfig` and `StreamConfig`, allowing for a convenient way of adding additional information to those, better than using `Description`.
When merged, will follow up with ADR for clients.
> Add metadata to StreamConfig and ConsumerConfig

- server/accounts.go
- server/stream.go
- server/subject_transform.go
- server/subject_transform_test.go
This undoes some breaking changes made in https://github.com/nats-io/nats-server/pull/3814
> Mappings breaking changes

- server/client.go
> Check if connection name was already set when storing it

- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_3_test.go
- server/stream.go
Allow cycles between source streams if subjects do not overlap.
This is a common pattern we can use for 2 node setups.
> [FIXED] Sourced streams that do not overlap subjects reported as a cycle.

- server/accounts.go
- server/stream.go
Improve checking that subject filters and destination transforms are valid subjects.
Improve error messages when bad filters/transforms are encountered.
Cover all cases of updating an existing stream's subject transform or sources
> Stream subject transform improvements

- server/filestore.go
- server/jetstream_cluster.go
- server/memstore.go
- server/raft.go
1. Only snapshot with minSnap time window like consumers and meta. Make it consistent for all to 5s.
2. Only snapshot at the end of processing all entries pending vs inside the loop.
3. Use fast state when calculating sync request, do not need deleted details there.
4. Only hold on to so many raft pending in memory, will fetch from WAL
> A few small optimizations

- server/jetstream_cluster.go
Fix for the following panic that can happen when using the API while shutting down a node:
```
[7] 2023/01/30 19:40:10.189635 [INF] Initiating JetStream Shutdown...
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4c pc=0x844fa6]
goroutine 1011 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).isGroupLeaderless(0x0, 0xc0000688a0)
/go/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:745 +0x46
github.com/nats-io/nats-server/v2/server.(*stream).handleClusterStreamInfoRequest(0xc0000cdc00, 0xc0001ff1f0?, 0x452ba9?, 0x1d?, {0x0?, 0x0?}, {0xc00e5f99c0, 0x1d}, {0xc010d30040, 0x0, ...})
/go/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:7549 +0x1ba …
```
> Fix for isGroupLeaderless when JS not available (due to shutdown)

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/raft.go
- server/stream.go
We were snapshotting more then needed, so double check that we should be doing this at the stream and consumer level. At the raft level, we should have always been compacting the WAL to last+1, so made that consistent. Also fixed bug that would not skip last if more items behind the snapshot.
> Minor fixes and optimizations for snapshots.

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
Found during work on multiple filters
After consumer filter update:
1. Wildcard bool was not updated
2. Sublist for consumers was not updated
> Fix Consumer not getting messages after filter update

- server/jetstream_cluster.go
- server/norace_test.go
- server/raft.go
Had a logic bug that would incorrectly suppress snapshots and compaction of the raft logs.
> [FIXED] Do not let !NeedSnapshot() avoid snapshots and compaction.

- server/jetstream_test.go
- server/stream.go
- server/sublist_test.go
Until now, purge updated all consumers sequences
even if purge subject was only a subset of given consumer filter. Because of that, even messages from not purged subjects were not fetched or properly accounted for existing consumers.
> Fix current consumers not getting messages after purge

- server/accounts.go
- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/raft.go
- server/stream.go
- server/websocket_test.go
Due to a bug, in rare circumstances we could write an empty snapshot for applied == 0. This would cause a spinning behavior at the raft layer.
To fix this issue, given that these could be out in deployments potentially.
1. Allow Truncate() to also properly do a reset of the store when terms were the only mismatch.
2. During testing fixed memstore truncate and also made sure per subject info was also cleaned up.
3. Added fix to detect a bad snapshot on initialization and remove.
4. Do not allow snapshots for applied == 0.
Also small fixes for new staticcheck.
> [FIXED] Snapshots Issue

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
For updating a consumer filter subject make sure locking order is correct and that our sublist is present.
> [FIXED] Updating consumer filter subject possible panic and deadlock.

- .github/workflows/go-test.yaml
- .github/workflows/nightly.yaml
- .travis.yml
We're currently using Go 1.19; we'll switch to 1.20 when the NATS Maintainers
make the call to switch.  Prepare by making sure that 1.20 won't turn into 1.2
instead, by quoting the string to be updated and adding a warning.
> YAML engineering: quote go version string

- server/filestore_test.go
This PR changes all of the file store tests to use subtests, so that we can easily run the full suite of tests with and without encryption, and in the future, with and without compression. Permutations are set at the top of `filestore_test.go`. This should hopefully improve test coverage of the file store quite a bit for alternate configs. No other behaviours in the tests have been changed.
> File store subtests

- util/nats-server-hardened.service
Importing as is would have reported:
```
/etc/systemd/system/nats.service:15: Failed to parse resource value, ignoring: 800000 # JetStream requires 2 FDs open per stream.
```
> Small fix to nats-server-hardened.service

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
> Make sure we adjust per subject info when doing a Compact().

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
Assumptions:
*  Separate single filter and multiple filters logic to not break anything in current codebase (not all done)
*  Make it reasonable performant, but not at the cost of increasing complexity (a first pass)
What's missing:
> Multiple consumer subject filters

- logger/log.go
- logger/log_test.go
- server/configs/reload/reload.conf
- server/log.go
- server/log_test.go
- server/opts.go
- server/reload.go
- server/reload_test.go
- server/signal_test.go
Fixes #3826 by adding the `logtime_utc` configuration option for both the stdout and the file logger.
> Add `logtime_utc` option

- server/accounts.go
In the case that the reverse entries also contain wildcards then this leads to infinite recursion. By breaking out the function to accept a parameter to tell us whether or not we have recursed, we can detect this condition and give up.
> Fix stack overflow panic in reverse entry check when inbox ends with wildcard

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
Applies @wallyqs review comments from multiple filters.
> Make JetStream errors naming consistent

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/norace_test.go
Only update on disk per subject information if we know we have an update.
Increase limit for internal blocking IO vs num cores. Will help in slow IO situations and lots of expire cache calls.
Improve expireMsgs minAge calculation for when lots of messages to expire in each callback.
> Improvements to Filestore

- server/jetstream_cluster_3_test.go
```
Write at 0x00c0000a94d0 by goroutine 189:
github.com/nats-io/nats-server/v2/server.TestJetStreamParallelConsumerCreation.func1()
./nats-dev/src/github.com/nats-io/nats-server/server/jetstream_cluster_3_test.go:1507 +0x1ec
Previous write at 0x00c0000a94d0 by goroutine 180:
github.com/nats-io/nats-server/v2/server.TestJetStreamParallelConsumerCreation.func1()
./nats-dev/src/github.com/nats-io/nats-server/server/jetstream_cluster_3_test.go:1507 +0x1ec
Goroutine 189 (running) created at:
github.com/nats-io/nats-server/v2/server.TestJetStreamParallelConsumerCreation()
./nats-dev/src/github.com/nats-io/nats-server/server/jetstream_cluster_3_test.go:1497 +0x360
testing.tRunner()
/usr/local/go/src/testing/testing.go:1576 +0x180
testing.(*T).Run.func1() …
```
> Fix TestJetStreamParallelConsumerCreation race

- server/norace_test.go
> [FIXED] Adjusted test to correspond to new limit of 1024.

- server/filestore.go
- server/jetstream_test.go
Make sure we update storage accounting on extended version purge for filestore.
> [FIXED] Extended Purge accounting was not updating account usage.

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
Do not re-calculate NumPending on all consumer info calls.
We noticed that consumer info calls were being called alot in some environments. When the consumer had a filtered subject with a wildcard and the stream had a high cardinality of subjects and was falling behind this could take a substantial amount of time.
> [IMPROVED] ConsumerInfo request processing.

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/stream.go
Parallel consumer creation could drop responses (create and info) and could also possibly run monitorConsumer twice.
> [IMPROVED] Parallel consumer 

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
In certain scenarios during restarts we could propagate errors to the meta-layer and delete consumers.
> [FIXED] Do not delete consumers on restarts with non-fatal update errors.

- server/stream.go
If a consumer had an older configuration with replicas of 0, we do not need to warn for an interest policy stream since the replicas will be inherited from the parent stream.
> [FIXED] Do not warn if consumer replicas configured to 0

- server/accounts.go
- server/accounts_test.go
Resolves https://github.com/nats-io/nats-server/issues/3868 (and https://github.com/nats-io/natscli/issues/703)
When using a `{{partition(10,1,2)}}` with multiple wildcard token positions, because of the `nphs++` it would only count as one wildcard being used.
> [FIXED] Using partition with multiple wildcard token positions

- server/raft.go
Needed to compact wal on snapshot to pindex+1, not pindex to make sure next append entry would not fail.
Also we could spin on a certain condition due to not processing if equal as well as less than.
> [FIXED] Spurious "Error storing entry to WAL" log messages

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_test.go
Make sure to also cleanup pending if below our stream ack floor.
Make sure to clean up redelivered state on purge.
Make sure to update ack floors on messages being expired out from underneath of us.
Fixed bug that would lose ack pending state during partial stream purge.
Make sure we warn properly of consumer state update failures.
> [FIXED] Consumer fixes and improvements on state management.

- server/consumer.go
- server/events.go
- server/ipqueue.go
- server/ipqueue_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/monitor.go
- server/mqtt.go
- server/raft.go
- server/sendq.go
- server/server.go
- server/stream.go
This refactors `ipQueue` to use Go generics. Since there are now considerably less interface boundaries, there should be far less small runtime allocations and less potential for `nil`s to creep out by accident and cause panics during type assertions.
> Refactor `ipQueue` to use generics

- server/filestore.go
- server/norace_test.go
When having a max msgs per subject (e.g. KV) under heavy concurrent usage we could skew the accounting for the underlying filestore.
This fixes the incorrect accounting.
> [FIXED] KV accounting errors under heavy concurrent usage

- server/filestore.go
- server/norace_test.go
In cases where we had a large subject space, a filestore with many msg blocks, and a filtered consumer with a wildcard filtered subject, creating a consumer could take more memory and time then we wanted. This improvement works when the consumer is DeliverAll and we used the upper layer in memory psim structure to scan but only in memory and avoid a file read for each msg block.
> [IMPROVED] Consumer create performance in some circumstances.

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
This will remove the "cc" from the PR template (which typically doesn't work for outside contributors) and instead replaces it with a code owners file, which will mean that PRs against this repository will automatically request review from the new @nats-io/server team.
> Set code owners, tweak PR template

- server/jetstream_cluster.go
- server/norace_test.go
This can help sync on restarts and improve ghost ephemerals. Also added more code to suppress respnses and API audits when we know we are recovering.
Signed-off-by: Derek Collison <derek@nats.io
> [IMPROVED] When becoming meta-leader optionally send current snapshot to followers.
