nats-io/nats-server

jetstream/README.md
=> Removed JetStream directory

server/jetstream.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go, server/raft.go
=> Allow replica updates during stream update.

server/filestore.go, server/jetstream_test.go
Cleaned up some locking and if fifo make index updates lazy like writeMsgRecord.
=> Small improvements to send performance to a full stream.

server/consumer.go, server/jetstream_cluster_test.go
On filtered subjects when consumers were staggered we need to disqualify a filtered consumer as not applicable before doing any sequence and ack floor determinations are made to see if we can delete a message from a stream.
Resolves #2873
=> [FIXED] Interest policy and staggered filtered consumers could fail to remove messages.

server/filestore.go, server/norace_test.go
=> Cleanup key files when removing message blocks.

README.md, server/const.go
=> Release v2.7.3

server/consumer.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go
When removing a stream peer with an attached durable consumer, the consumer could become inconsistent.
=> [FIXED] Inconsistent durable consumer state after stream peer removal

server/consumer.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go, server/stream.go
=> Made improvements to scale up and down for streams and consumers.

server/jetstream_test.go
Had a question about them and noticed we did not really have a test.
=> Test ack metrics

server/jetstream_test.go
This disables some flaky placement tests. I need to keep debugging, but in the meantime I don't want to impact anyone else.
=> Disable some supercluster limit placement tests

server/jetstream_test.go
This updates TestJetStreamSuperClusterSystemLimitsPlacement to use random high ports.
=> Use random high port in placement test

server/server.go, server/util.go, server/util_test.go
=> [FIXED] Server version check

server/jetstream_test.go
=> Add failing test for updating JS Consumer with sampling option

server/consumer.go, server/jetstream_test.go
=> [FIXED] JetStream: sampling not updated during consumer update

server/jetstream.go
=> update message size was too short when nothing needed to be sent

go.mod, go.sum, server/accounts.go, server/errors.json, server/jetstream.go, server/jetstream_api.go, server/jetstream_errors_generated.go, server/jetstream_test.go, server/jwt_test.go, server/opts.go
Also start checking on  stream update
Resolves #
-
-
-
=> Adding max stream bytes check

go.mod, go.sum, server/accounts.go, server/consumer.go, server/jetstream.go, server/jetstream_api.go, server/jetstream_cluster.go, server/jetstream_test.go, server/jwt_test.go, server/opts.go
because of the addition, defaults now have to be set later (depend on
these new limits now)
also re-organized the code to closer track how stream create looks
Resolves #
-
-
-
=> added max_ack_pending setting to js account limits

server/dirstore.go, server/dirstore_test.go
=> In Merge validate nkey and subsequent saveIfNewer error on invalid jwt

server/jetstream.go, server/jetstream_cluster.go, server/jwt_test.go, server/stream.go
adds unit test to test this scenario
improves reporting of correct error
only show info for non existing tiers where streams exist
=> error handling and info when moving a stream from non existing tier

server/monitor.go, server/monitor_test.go
=> [ADDED] Monitoring: MQTT and Websocket blocks in `/varz` endpoint

server/accounts.go, server/jetstream.go, server/jwt_test.go, server/opts.go
=> returns -1 for new unlimited/unset limits and tests/fixes info counts

server/norace_test.go
This is a follow up to PR #3008.
This test fails on v2.7.4 but passes on main.
=> Add test that demonstrated the consumer filter perf degradation

server/jetstream_test.go
This change refactors `TestJetStreamSystemLimitsPlacement` and `TestJetStreamSuperClusterSystemLimitsPlacement` to use the new `ModHook` helper functions from https://github.com/nats-io/nats-server/pull/2998.
I still need to debug the commented out tests. Those continue to be flaky even with these helpers.
=> Refactor SystemLimitsPlacement tests

go.mod, go.sum, server/consumer.go, server/errors.json, server/filestore.go, server/jetstream.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go, server/jetstream_errors_generated.go, server/memstore.go, server/norace_test.go, server/raft.go, server/store.go
=> [IMPROVED] Raft layer for general stability and leader election.

server/client.go, server/jetstream_api.go, server/routes_test.go
Please read comment in client.go. probably should make this illegal, @ or not.
=> [FIXED] subject renaming with hand crafted reply subject

server/jetstream_cluster.go, server/jetstream_cluster_test.go
This window is small, less than 2 secs in most cases, but can happen.
=> Make sure if we recreate something after deleting that we do not wipe valid state

server/jetstream_cluster.go
Need to also limit the number of outstanding messages during a
catchup. It was removed in PR #3029
=> Add catchup messages limit that was removed

server/jetstream_api.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go, server/jetstream_test.go, server/raft.go, server/stream.go
We would declare lost quorum too quickly on scale up.
=> Raft improvements

server/consumer.go, server/errors.json, server/jetstream_errors_generated.go, server/jetstream_test.go, server/jwt_test.go
- Updated tests that were checking for the error to include the limit
- Moved some tests above the benchmark ones
=> Return limit in consumer max_ack_pending limit exceeded

server/jetstream_cluster.go, server/raft.go
=> Improvements to move semantics.

server/consumer.go, server/jetstream_api.go
=> Cleanup timers on consumer leader change

README.md, server/const.go
=> Release v2.8.0

server/consumer.go, server/jetstream_cluster_test.go, server/norace_test.go, server/stream.go
=> [FIXED] JetStream: stream mirror issues in mixed mode clusters

README.md, server/const.go
=> Release v2.8.1

server/filestore.go
=> Small improvement with fss processing

server/client.go, server/jetstream_test.go
=> Fix for subject transforms and JetStream delivery subjects.

server/jetstream_cluster.go, server/raft.go
Some small improvements to the raft layer and clustering layer trying to diagnose bad raft state during upgrades from 2.7.x to 2.8.x.
I believe some could be caused by ill-advised snapshot sends for consumers when not a leader but not only when scaling up from R1. Also fixed small bug that would not reset catchingUp state and could lead to processing logic errors in the raft layer.
During move or scale up will snapshot so followers can kick up to upper layers to sync vs raft only.
Resolves #
-
-
-
=> Raft and cluster improvements.

server/filestore.go
There was a case where we may have done a check for max-per-subject
limit twice per message. That would apply to streams that have
max-per-subject and also discard_new, which is what KV configures.
=> [IMPROVED] JetStream: check max-per-subject once

go.mod, go.sum, server/accounts.go, server/auth.go, server/events_test.go, server/jwt_test.go, server/server.go
Reverts nats-io/nats-server#3091
=> Revert "[added] support for jwt operator option DisallowBearerToken"

README.md, server/const.go
=> Release v2.8.2

server/filestore.go, server/stream.go
=> Fix for panic due to not loaded cache during compact

server/jetstream_jwt_test.go
expand unit test to cover stream move tiered/non tiered.
I also tried out deleting stream + sleep Minute + check account info. (always worked)
=> altered move unit test to test tiered/non tiered setup

server/jetstream_test.go, server/stream.go
=> Fix for #3119

server/filestore.go, server/filestore_test.go, server/memstore.go, server/memstore_test.go, server/store.go
This in response to tracking issue #3114.
Resolves #3114
Hopefully ;)
=> General improvements to accounting for the filestore.

server/consumer.go, server/jetstream_api.go, server/jetstream_test.go
Getting us prepped for move to all pull consumers for clients and for the internal consumers for mirrors/sources.
=> Support for MaxBytes for pull requests.

server/consumer.go, server/filestore.go, server/jetstream_cluster_test.go, server/memstore.go, server/store.go
=> Make sure consumer store is memory based when selected.

server/jetstream_cluster_test.go, server/jetstream_helpers_test.go, server/norace_test.go, server/raft.go
=> Speed up raft for tests

server/jetstream_api.go
was not removed when moving the code into checkStreamCfg
Resolves #
-
-
-
=> removed redundant republish code

README.md, go.mod, go.sum, server/const.go
=> Release v2.8.3

server/consumer.go, server/jetstream_test.go, server/stream.go
When a consumer was created that filtered out partial sets of messages with deliver last by subject, and this was on a stream that had max message per subject set and > 1 and the matching filtered messages did have some subjects > 1 the num pending was incorrect.
This could happen with KV streams and history > 1 with duplicates and could result in not getting the initial data set done signal for a watcher.
=> [FIXED] Consumer NumPending incorrect on certain stream setups.

server/mqtt.go, server/mqtt_test.go
There is a mechanism to detect if a connection somewhere in the
cluster is using the session ID of an existing one, and if so,
close one as a duplicate.
However, when different domains are used, they should not be considered
duplicates.
=> [FIXED] MQTT: Sessions with same ID in different domains were considered duplicates

README.md, server/const.go
=> Release v2.8.4

server/jetstream_cluster.go, server/jetstream_cluster_test.go
Make sure we do not resend responses on restart for certain clustered consumers after a meta snapshot.
=> [FIXED] Do not send consumer API advisories on restart.

server/stream.go
=> Republish on the republish subject, place original subject in a header like direct stream gets.

server/consumer.go, server/jetstream_test.go
Resolves https://github.com/nats-io/nats-architecture-and-design/issues/116
=> Make error on make bytes exceeded on a pull request a 409

server/jetstream.go
=> [FIXED] Account.exports.services Data Race

server/consumer.go, server/jetstream_helpers_test.go, server/jetstream_test.go
Prepping more support for JS simplification. Also will be useful in override configs to cleanup MQTT QoS-1 consumers that are orphaned.
=> Add in support for inactivity thresholds for durable consumers.

server/jetstream_cluster.go, server/jetstream_cluster_test.go
If no max bytes set do better randomization of placement.
If the stream is replicated take into consideration number of ha assets on the server already.
=> [IMPROVED] Distributed placement of streams in a cluster

server/consumer.go, server/jetstream_cluster_test.go, server/jetstream_test.go
=> Allow consumer filter subjects to be updated

server/jetstream_api.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go
=> removed commented out code

server/jetstream_api.go
=> fix json tag for meta stream move

main.go
=> Allow maxprocs to debug log after start banner

server/jetstream_cluster.go, server/jetstream_super_cluster_test.go
When increasing the replica count unique tags for already existing peers
where ignored, which could lead to bad placement
Resolves #
-
-
-
=> Fix unique_tag issue with stream replica increase

server/jetstream_api.go, server/jetstream_cluster_test.go, server/stream.go
Also add NextFor to json stream get.
=> Allow stream and mirror direct get to be updated

server/const.go
=> bump version to 2.9.0-beta.7

go.mod, go.sum
=> [UPDATED] Compression library

server/const.go
=> Bump version to 2.9.0-beta.8

server/jetstream_cluster.go
=> [FIXED] Issue #3278 - Make sure to protect against mset == nil

server/jetstream_cluster_test.go
reduce number of messages sent
try move+cancel for every server
Resolves #
-
-
-
=> fix and improve unit test

server/filestore.go, server/filestore_test.go
When we write a msgBlock idx file that is shorter than the previous write we could fail to recover the idx properly. We do truncate when we do syncs but if the filestore is encrypted and the server is restarted before this operation the decrypt would fail since there are extra bytes. For a stream that is empty but has a non-zero start sequence, we could lose that state on a restart.
=> [FIXED] Short index write could lead to loss of stream sequence for an empty stream

server/jetstream_cluster.go
Now monitorStream waits with scaling down the stream until all
monitorConsumer have scaled down their respective consumer
Also update consumer assignment for later use in monitorConsumer
Same for stream assignment in monitorStream
Resolves #
-
-
-
=> down scale consumer before downscale of stream

server/consumer.go, server/jetstream_cluster.go
=> fix race by locking arround o.isLeader

server/filestore_test.go, server/jetstream_cluster_test.go
=> Update tests to check last sequence state

server/accounts.go, server/accounts_test.go, server/sublist.go, server/sublist_test.go
This reverts commit cf784c19f095fd1c0c8c58609de259c2daed0bd8.
This reverts commit c269a1ca095b099b66aed8582d4a9ff4fb234ce5.
(done using `git revert`)
=> Revert direct changes to main

server/leafnode_test.go
=> Fixed TLS test so it passes on macOS

server/jetstream_cluster_test.go, server/raft.go
When we were catching up a raft follower that involved snapshots, we would send the snapshot entry followed by an entry that was one less.
Also added in more logging around exceptional conditions to help with triage and debugging production systems.
=> Improvements to raft layer with snapshots on catchup.

server/jetstream_cluster.go
=> Encrypt meta and raft states.

server/filestore_test.go, server/jetstream_cluster.go, server/raft.go
=> General stability improvements

.github/workflows/nightly.yaml, docker/Dockerfile.nightly
=> Update nightly to Go 1.18

docker/Dockerfile.nightly
=> Replace "go get" with "go install"

server/mqtt.go, server/mqtt_test.go
If a client with a given client ID is connected and while connected
another client tries to reuse the same client ID, the spec says that
the old client be closed and the new one accepted.
However, the server protects from this flapping happening all the time
by rejecting new clients that try to connect at a very fast pace.
However, the server was closing a misbehaving client after a second
delay (to prevent immediate reconnect if the client library does that)
but was not blocking the read loop and the compounding issue was that
if that misbehaving client is sending more protocols (for instance SUB) 
the server would panic because the client was not fully configured.
To prevent that, the server will now "block" this misbehaving client
in its readLoop before closing the connection, …
=> [FIXED] MQTT: Possible panic when clients misbehave

server/filestore.go
=> [IMPROVED] Speed of storing new keys with a large number of pre-existing keys.

server/nkey.go, server/server.go
=> Move to crypto/rand for nonce generation

server/raft.go
=> Downgrade a RAFT warning to debug

.gitignore, scripts/runTestsOnTravis.sh, server/jetstream_chaos_cluster_test.go, server/jetstream_chaos_helpers_test.go, server/jetstream_helpers_test.go
- Add chaos controller
- Add "cluster bouncer" chaos monkey
- Add 2 tests that use it
- Add some utility methods
=> Chaos tests for JS cluster

server/jetstream.go, server/jetstream_cluster_test.go
=> Remove io/ioutil

server/jetstream_cluster_test.go
=> Fixed flapping test

server/jetstream_cluster.go, server/jetstream_cluster_test.go
If the leader sends messages but the follower for any reason aborts
or retry the snapshot process, it will now send the error that
caused this and the leader can then abort the catchup instead of
waiting for its inactivity threshold of 5 seconds.
Also make the send of a batch be delayed for a bit until the number
of "acks" is 1/2 of the batch size or after reaching 100ms. This
helps avoid trickling of messages. Tested with the new test
TestJetStreamSuperClusterStreamCathupLongRTT() and see better
results both in size of batches and overall time is smaller or
similar but not longer.
=> [IMPROVED] JetStream catchup can be aborted and better flow control

server/filestore.go
=> [FIXED] Data race

server/jetstream_api.go, server/jetstream_super_cluster_test.go
This can happen if the move was initiated by the user.
A subsequent cancel resets the initial peer list.
The original peer list was picked on the old set of tags.
A cancel would then keep the new list of tags but reset
to the old peers. Thus tags and peers diverge.
The problem is that at the time of cancel, the old
placement tags can't be found anymore.
This fix causes cancel to remove the placement tags, if
the old peers do not satisfy the new placement tags.
=> fix move cancel issue where tags and peers diverge

server/jetstream_cluster_test.go
=> adding source/mirror unit tests

server/const.go
=> bump version to 2.9.0-RC.2

server/jetstream_super_cluster_test.go
=> fix unit test

server/filestore.go, server/filestore_test.go
=> [FIXED] Make sure when SubjectState is called we have loaded fss state.

server/filestore.go, server/filestore_test.go, server/jetstream.go, server/jetstream_test.go, server/opts.go, server/reload.go, server/stream.go
Also supports upgrade to different cipher for existing store assets.
=> [ADDED] Support for AES-GCM as a cipher along with ChaChaPoly. 

server/jetstream_cluster.go
=> We can't purge directories here since not 100% sure all state is in snapshot.

server/filestore.go, server/filestore_test.go
=> When filestore is used for raft layer do not attempt to track subjects

server/jetstream_cluster_test.go, server/stream.go
if an origin stream contains:
1M msgs with subject foo and 1M msgs with subject bar
IF the source consumer changes their filter from foo to bar
Then it would have received messages for subject bar.
This happens because this tail was filtered and their
respective seqno was not communicated to the consumer.
This is somewhat unexpected. It is also coincidental.
Had the last message in the stream had subject foo then
this wouldn't happen.
Therefore, when completely changing the subject say,
from foo to bar, we only receive messages received
after the time the change was made.
However, if the old and new subject overlap in any way,
we go by sequence number. Meaning in these cases the
outlined behavior remains in order to not induce artificial
message loss for the part of the subject space that …
=> fixed consumer source update receiving upstream msgs

server/jetstream_cluster_test.go, server/stream.go
=> Don't immediately listen on the direct get subjects.

server/consumer.go, server/filestore.go, server/jetstream_chaos_kv_test.go, server/jetstream_cluster.go, server/jetstream_cluster_test.go, server/jetstream_test.go, server/raft.go, server/stream.go
=> General improvements to clustered streams during server restart and KV/CAS.

server/filestore.go, server/filestore_test.go, server/jetstream_test.go
This was seen in internal testing by @ripienaar manifested as a consumer that would get stuck for a bit and skip records due to incorrect EOF signaling.
=> Fixed a bug that would not track per subject info for streams that were mirrors/sources.

scripts/cov.sh
=> Increase test timeout for nightly code coverage

server/jetstream_cluster.go
It seems to cause problems when upgrading from a v2.7.4 to main
branch.
=> Revert a change made in PR #3392

server/gateway.go
When a subscription is recently made, gateway code ensures that if
there is a reply subject, the reply is "mapped" or rewritten to allow
the reply to come back to the origin cluster, regardless of subscription
interest propagation.
The issue was that this uses a map with a `*client` as the key
but the pointer for SYSTEM clients would not always be the same,
which meant that the rewrite would not happen, causing possible
"loss" of replies.
=> [FIXED] Gateway: system request/replies may not work properly

server/filestore.go, server/filestore_test.go
Also added in sanity check on server start.
=> FSS state could skew on expire on recover with no msgs left.

server/jetstream_cluster.go, server/jetstream_cluster_test.go
This would happen after multiple replicas changes.
=> [FIXED] Stream info numbers may be 0 after cluster restart

server/gateway.go, server/jetstream_super_cluster_test.go
Internally jetstream may subscribe to some subject and then send
a request with a reply subject matching that subscription.
Due to interest propagation through a super cluster, it is possible
that the reply comes back to a node that is not yet aware of
the subscription interest which would cause the reply to be dropped.
Some code detects that the subscription is recent and "map" the
reply subject so that it can be routed back to the origin server.
However, this was done with the use of the connection object that
created the subscription, but at the time of the send, a different
internal "*client" object may be used which would then cause
the code to not be aware of the recent subscription and not do
the mapping.
This code was changed to scope at the account level instead of
connection.
A …
=> [FIXED] JetStream: possible routing issues through gateways

server/jetstream_benchmark_kv_test.go
Resolves N/A
- Add KV benchmark (put/get/update, single-server/cluster, ...)
=> KeyValue Put/Get/Update benchmark

conf/lex.go, conf/lex_test.go
=> Fixed lexer changes made in #3434

server/jetstream_cluster.go
=> Tweak lost quorum reporting

.goreleaser.yml
=> [ADDED] Architecture s390x in goreleaser.yml file

server/consumer.go, server/norace_test.go, server/stream.go
Based off excellent insight and PR #3468 by @neilalexander.
This reuses pools we already had and also only loads the msg once for all consumers.
=> Optimize needAck.

server/stream.go
=> When filtering a source stream use new consumer create API subject.

server/filestore.go, server/filestore_test.go
When a block's subject meta state was swapped out and subsequently loaded back in with only one subject present, but other messages with different subjects were added later, a filtered get could return the wrong result.
Resolves #3848
=> [FIXED] Filtered Consumers return wrong messages.

README.md, server/const.go
=> Release v2.9.1

server/client.go, server/gateway.go
There was an observed degradation (around 5%) for large fan out in v2.9.0 compared to earlier release. This is because we added accounting of the in/out messages for the account, which result in 4 atomic operations, 2 for in and 2 for out, however, it means that for a fan-out of say 100 matching subscriptions, it is now 2 + 2 * 100 = 202.
This PR rework how the stats accounting is done which removes the regression and even boost a bit the numbers since we are doing the server stats update as an aggregate too.
There are still degradation for queues and no-sub at all that need to be looked at.
=> [IMPROVED] Fan-out performance

server/jetstream_api.go, server/jetstream_cluster_3_test.go
=> [FIXED] bug in consumer names paging, did not honor limits and returned duplicate results.

server/consumer.go, server/jetstream_test.go
=> [FIXED] JetStream: redeliveries for LastPerSubject delivery policy

README.md, server/const.go
=> Release v2.9.2

server/filestore.go, server/filestore_test.go
While going over message blocks, when some blocks were removed there was a risk that a block is ignored, leaving some messages around.
Resolves #3528
=> [FIXED] JetStream: Purge with additional options may leave some messages

server/jetstream_cluster_3_test.go
=> Test to make sure a consumer that is deleted while a server is down recovers correctly.

main.go
=> Adjust "nats-server -h" output

server/accounts_test.go, server/client.go
=> [FIXED] Stack overflow when account imports its own export

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go
If the user sends a CONSUMER.CREATE request with a configuration that specifies the name that the user wants for the ephemeral consumer, this would not work on cluster mode, that is, the server would still pick a name instead of using the provided one.
=> [FIXED] JetStream: User-defined ephemeral Name not used in cluster mode

server/client.go, server/jetstream_api.go
=> Added warning if internal sub callback takes too long

README.md, server/const.go
=> Release v2.9.3

.github/workflows/cov.yaml, server/gateway_test.go
=> Fix some flappers and update Go version for nightly code coverage

server/client.go, server/mqtt.go, server/mqtt_test.go
A simple configuration like this:
```
...
mappings = {
foo: bar
}
mqtt {
port: 1883
}
```
would cause an MQTT subscription on "bar" to not receive messages published on "foo".
In otherwords, the subject transformation was not done when parsing a PUBLISH packet.
This PR also handles the case of service imports where transformation occurs after the initial publish parsing.
Resolves #3547
=> [FIXED] MQTT: Subjects mapping were not handled

server/jetstream_cluster_3_test.go, server/jetstream_helpers_test.go
Signed-off-by: Derek Collison derek@nats.io
=> Added specific tests for using non system extended setup similar to NGS

server/jetstream_cluster_2_test.go
=> Fix a test that would sometimes fail

server/filestore.go, server/filestore_test.go
We could potentially fail a write and not rebuild the state since we tried to ensurePerSubjectInfo was loaded after we set the flush pending state. So if it had to be rebuilt it would try to flushPending first.
This was referenced in #3560 
So we moved this above setting the pending state, and also made sure the rebuildState also took into account the per subject info as well.
=> Make sure to rebuild per subject info on write error

server/jetstream_cluster.go
=> Added warning for high message lag into a clustered stream.

server/filestore.go, server/filestore_test.go
On abnormal server exit, for streams or KV with max msgs per subject set we could recover more than N msgs per subject.
This fix allows for recovery of correct state on restart when index files are missing or not current.
=> [FIXED] MaxMsgPerSubject recovered on corrupt or missing index file.

server/filestore.go
=> Make sure to check for ss == nil

go.mod, go.sum
=> Updated Go client

server/consumer.go, server/jetstream.go, server/jetstream_test.go
This is related to PR #3572 and PR #3576
=> Add the pending msgs/bytes on 409 Shutdown

README.md, server/const.go
=> Release v2.9.4

server/jetstream_cluster.go
=> [FIXED] Move code that references sreq past the check for nil

server/sublist.go, server/sublist_test.go
=> [FIXED] Sublist's cache hit rate would be wrong in presence of multiple accounts

server/disk_avail_netbsd.go, server/pse/pse_netbsd.go
Signed-off-by: Matthias Petermann <mp@petermann-it.de>
- [-] Tests added
- [-] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [?] Build is green in Travis CI
Resolves #3525
- Add pse support on NetBSD (based on OpenBSD work)
- Add (dummy) support for disk availability on NetBSD (similiar to Windows work) - I will work on real support on NetBSD later
=> [ADDED] Ability to build on NetBSD

server/jetstream_cluster_3_test.go
=> Fixing a flapper

server/filestore.go, server/filestore_test.go, server/memstore.go, server/memstore_test.go
=> [FIXED] Honor MaxMsgsPerSubject during a stream config update.

server/jetstream_cluster.go
The issue that a "first sequence mismatch" during processing of a snapshot was causing the state to be reset and caused a lot of catchup from the follower. An attempt to fix that in PR #3567 caused an issue that was addressed in PR #3589. However, this was then causing the follower to sometime never able to catchup or took a very long time.
This PR - we believe - addresses the original and subsequent issues.
=> [FIXED] JetStream: processing of snapshot with expired messages

README.md, server/const.go
=> Release v2.9.5

.github/workflows/cov.yaml, .github/workflows/nightly.yaml
Also updated some of the actions to avoid some deprecation warnings
=> Change code coverage and nightly to build from dev instead of main [ci skip]

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go
We were not taking the failures (mset.clfs) into account.
=> [FIXED] On stream proposal failures we could accidentally warn about high stream lag.

README.md, server/const.go
=> Release v2.9.6

server/consumer.go, server/norace_test.go
When we deleted a consumer from an interest policy stream we would make sure to clean up any unacked messages. However we only based start from the ack floor for the consumer and did not take into account the first sequence of the stream.
Resolves #3499 
=> [FIXED] #3499

server/jetstream_cluster.go, server/jetstream_cluster_2_test.go
This could happen during concurrent requests where the assignments are not yet fully processed.
=> [FIXED] JetStream: Account max streams/consumers not always honoured

server/raft.go
=> Updated pae threshold and reporting modulo to not spam logs as much.

server/consumer.go, server/jetstream_cluster_3_test.go
=> [FIXED] Fix logic bug that would prevent some stream messages from being deleted.

server/jetstream.go, server/jetstream_test.go, server/stream.go
=> Auto cleanup dangling messages from interest policy streams on server start.

server/accounts.go, server/jetstream_jwt_test.go
=> [FIXED] JetStream: Account removal leaks subscriptions

server/norace_test.go, server/stream.go
This will offload consumer processing and signaling from the stream ingest routine when the number of consumers passes a threshold.
=> Offload signaling to consumers when number is large.

server/filestore.go
This PR fixes a concurrent write to the consumer pending map on startup reported by a user.
```
fatal error: concurrent map iteration and map write
goroutine 1 [running]:
github.com/nats-io/nats-server/v2/server.(*consumerFileStore).Update(0xc000324cc0, 0xc00107c1e0)
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/filestore.go:6249 +0x352
github.com/nats-io/nats-server/v2/server.(*consumer).writeStoreStateUnlocked(0xc001078900)
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/consumer.go:2133 +0xfb
github.com/nats-io/nats-server/v2/server.(*consumer).checkRedelivered(0xc001078900, 0x0)
/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/consumer.go:2047 +0x173
github.com/nats-io/nats-server/v2/server.(*consumer).readStoredS …
```
=> Fix concurrent write in consumer pending map at startup

server/monitor.go
Resolves #
- Added stream created timestamp for stream monitoring 
=> Added stream created timestamp to stream detail

server/client.go, server/jetstream_test.go
=> [FIXED] Make sure header keys do not have additional prefixes.

README.md, server/const.go
=> Release v2.9.7

README.md, server/const.go
=> Release v2.9.8

server/jwt_test.go, server/server.go
In operator mode the system could incorrectly return no_auth_required when a client tries to connect.
This is due to the mechanism used to allow system users but not official users on the $G (global account) and a change in 2.9.8 that if no_auth_user was set that we would not return auth_required set to true.
Any client (java) that suppressed sending credentials because of the flag could be affected.
This fix only executes that code when in non-operator mode now and when we are looking to suppress that flag for clients we make sure it is not the anonymous user if it was created.
A simple fix for those affected is to have the server reload its config which will clear this behavior.
This only is present in 2.9.8 server version and when the server is in operator mode with an account …
=> [FIXED] Operator Mode could return no_auth_required set to false on client connect.

server/client.go
This ensures the logic that triggers user disconnections share the same code paths and sets the same variables
=> allow expiration timer logic to be called unlocked

server/accounts.go, server/jetstream_jwt_test.go
PR to upstream change from #3687 to main
=> Fix to reenable JetStream for account when reenabled (dev → main)

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go
=> Make stream removal from a server consistent.

server/jetstream_cluster_3_test.go
=> Extensive test in support of issue #3191.

server/const.go
Signed-off-by: Byron Ruth <b@devel.io>
=> Bump version to 2.9.10-dev

server/jetstream_cluster.go, server/todd_test.go
=> [FIXED] Make sure we remove node from stream assignment.

server/filestore.go, server/filestore_test.go
Fix for the condition after restart where first sequence was wrong and reported zero timestamp and expiration stopped working.
Resolves #3653 
=> [FIXED] Bad first sequence and expiration stopped working after server restart.

server/consumer.go, server/norace_test.go, server/stream.go
When a stream had a large number of consumers on a server that were sparse, the signaling mechanism would do a linear scan to signal matching consumers. As usage patterns have continued to have more consumers that are filtered and sparse, meaning a message is destined for a single or small number of consumers.
This change moves selection to a sublist that tracks only active consumer leaders for selection, which optimizes selection of consumers to signal when the number of consumers is large.
=> Improve performance and latency with large number of sparse consumers.

server/consumer.go
=> Simplify locking for consumer info requests.

server/jetstream_cluster.go, server/jetstream_test.go, server/stream.go
In a non-clustered JetStream system, subject overlap with other streams in the account was not checked on stream update.
=> fix and test for overlapping stream subscription on update

README.md, server/const.go
Signed-off-by: Byron Ruth <b@devel.io>
=> Prepare for v2.9.10 release

server/const.go
Signed-off-by: Byron Ruth <b@devel.io>
=> Bump version to 2.9.11-beta

server/jetstream.go
=> Default to replicas == 1 in tiered jetStream setup

server/filestore.go, server/filestore_test.go, server/jetstream_test.go
When a msg blk was not written correctly, but the idx file was, max bytes for a stream would no longer be honored since the deletion of any messages in that empty block were not being handled properly.
Resolves #3734 
=> Fix for #3734

server/sublist.go
Currently we are storing the same `*subscription` pointer both in the map keys and values, which seems like an unnecessary duplication. This replaces the map value with `struct{}` as it has an effective width of zero in memory.
cc #3730
=> Deduplicate `*subscription` in `Sublist`

README.md, server/const.go
Signed-off-by: Byron Ruth <byron@nats.io>
=> Release v2.9.11

server/const.go
Signed-off-by: Byron Ruth <byron@nats.io>
=> Bump to 2.9.12-beta

server/jetstream_cluster.go
These snapshots can grow quite large, especially in the case of lots of interior deletes on streams, lots of pending ACKs on consumers etc. By using hashes instead, we can determine whether or not the snapshot has changed without having to hold the entire snapshot on the heap.
=> Use highwayhash for last stream, consumer and cluster snapshots

main.go, server/monitor.go
=> Update snapshots to numCores and maxProcs after maxrocs.Set()

server/filestore.go, server/filestore_test.go
Discovered doing the optimizations work for interior deletes branch for dev.
Also brought over a simple optimization for large interior deletes if we decide to do a 2.9.12 release.
=> [FIXED] Filtered state for all subjects when the first seqs are deleted.

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go
When we create a consumer with less replicas then the stream, make sure to select from online peers.
Resolves #3791 
=> [FIXED] Select consumer peer(s) from active peers only.

server/pse/pse_dragonfly.go
Simply copy the pse implementation for openbsd.
Resolves #
-
-
-
=> Add support for dragonfly bsd.

server/filestore.go
https://gist.github.com/wallyqs/a9e764bd513af8d8ef2efaaecad519d4
=> [FIXED] Deadlock on dataloss when holding mb lock.

.travis.yml
=> Bump to Go 1.19.5

README.md, server/const.go
=> Release v2.9.12

server/const.go
=> Bump 2.9.13-beta

server/jetstream_cluster.go
=> Revert consumer snapshot logic

README.md, server/const.go
=> Release v2.9.14

server/const.go
=> Bump v2.9.15-beta

server/jetstream_super_cluster_test.go
=> Fix to flapping test to make sure we do not quickly blow away all consumer state.

server/consumer.go, server/jetstream_cluster_3_test.go
Fixed a bug where a named consumer under an interest policy stream was incorrectly spinning up inactive threshold timers in all replicas not just the leader.
=> [FIXED] Named push consumers with inactive thresholds deleted when still active.

server/jetstream_cluster_3_test.go
This test adds check if consumer with inactivity threshold is properly removed on intertest based stream when reaching the threshhold.
=> Improve test for consumer with inactivity threshold

server/raft.go
=> Off-by-one on RAFT pindex

server/jetstream_cluster.go, server/raft.go
This means a subsequent request for exactly applied index would return that entry only and not the full state snapshot.
Also fixed bug where we would not snapshot when we should.
=> [FIXED] Snapshots would not compact through applied. 

server/monitor.go, server/monitor_test.go
backport of https://github.com/nats-io/nats-server/pull/3914
=> [main] Add raft query parameter to /jsz to include raft group info

server/mqtt.go, server/mqtt_test.go
Per the spec, the Server MUST NOT match Topic Filters starting with a wildcard character (# or +) with Topic Names beginning with a $ character, Spec [MQTT-4.7.2-1].
Resolves #3924
=> [FIXED] Fix for MQTT Spec 4.7.2-1 violation

server/norace_test.go
=> Attempt to fix flapper again

server/monitor_test.go
=> Fixed flapping test since we have two streams and order in slice not guaranteed.

go.mod, go.sum, server/accounts.go
[waiting on PR to be merged on JWT side, and release before merging this]
=> [FIX] referenced JWT constant for AnyAccount

server/jetstream_cluster_3_test.go, server/jetstream_test.go, server/norace_test.go, server/opts_test.go
=> Fixed some tests

server/events_test.go, server/jetstream_api.go
=> Fix for API data race.

server/client.go, server/consumer.go, server/events.go, server/filestore.go, server/jetstream_cluster.go, server/jetstream_cluster_2_test.go, server/norace_test.go, server/raft.go, server/sendq.go, server/stream.go
Improved some hot spots on the memory subsystem with sync.Pools.
=> [IMPROVED] Memory allocations and pressure in the raft layer.

docker/Dockerfile.nightly
Pin to the v2 version from nsc instead.
=> Fix nsc in nightly

server/accounts.go, server/server.go
=> [FIX] Data race when setting up service import subscriptions.

go.mod, go.sum
=> Update to the compress lib

server/jetstream_cluster_3_test.go
This is specifically when a cluster is reconfigured and the servers are restarted with a new cluster name.
=> Test that makes sure that assets can change be scaled after a cluster change.

server/client.go, server/monitor.go, server/monitor_test.go, server/server.go
=> [FIXED] Allow user filtering on connz for other user types like nkeys etc.

server/raft.go
When we receive a catchup request for an item beyond our current state, we should stepdown.
=> [IMPROVED] Stepdown on catchup request for something newer than our state

.goreleaser-nightly.yml, README.md, server/const.go
Include fix with GoReleaser for nightly.
=> Prepare v2.9.17 release

server/filestore.go
Some async tests were showing artifacts being left after a message block was being closed.
=> When in async mode make sure to not flush or create new files after close.

server/jetstream_benchmark_test.go
- Refactors BenchmarkJetStream(Consume|Publish) and BenchmarkJetStreamKV benchmarks to connect to stream leader for benchmark cases where cluster size is greater than 1. 
- BenchmarkJetStreamKV now only targets a single bucket (B=1).
CC: @mprimi
=> Connect JS benchmarks to stream leader

go.mod, go.sum
=> [UPDATED] Dependencies

go.mod
=> Bump client version to v1.27.0

go.sum
=> [UPDATED] go mod tidy to update go.sum

server/certstore/certstore_windows.go
Cert Store (aka wincert) feature wasn't properly handling TLS 1.2 handshake with TLS 1.2 clients that do not support RSA signature with PSS padding.
With this update, Cert Store will perform either PKCS#1 v1.5 or PSS padding for RSA signature depending on what type is negotiated by the TLS 1.2 client.
Issue surfaces with the NATS .NET v1 client which supports TLS 1.2 only (.NET 4.6.2 dependency) only when the client application was hosted on Windows 10 Enterprise LTSC 2019 (equivalent also to Windows 10 1809 and Windows Server 2019).  If the same client was executed on a more modern Windows 10 release, RSA signature with PSS padding was negotiated and succeeded normally.
The Go NATS client as well as any client operating at TLS 1.3 level would not exhibit the issue as TLS 1.3 requires …
=> Support TLS 1.2 RSA signature with PKCS#1 v1.5 padding

server/leafnode_test.go
This test has multiple leafnode connections to different accounts and to a shared account to make sure behavior is correct.
=> Added in another DQ test across leafnodes.

server/jetstream_benchmark_test.go
- New benchmark for NATS JetStream Object Store
=> Add object store benchmark

server/leafnode_test.go
=> Updated Leafnode Test

server/jetstream_cluster_2_test.go, server/jetstream_cluster_3_test.go, server/jetstream_test.go, server/norace_test.go
This should hopefully make a small handful of tests less flakey.
=> De-flake a few tests

server/consumer.go
=> [IMPROVED] Don't error to server logs if message was deleted for consumer

server/auth_callout.go, server/leafnode_test.go, server/routes_test.go, server/server.go
=> Cleanup for some staticcheck warnings

server/jetstream.go, server/jetstream_api.go, server/jetstream_cluster.go, server/stream.go
=> Fix typo from internal function

server/stream.go
=> [IMPROVED] Also reset clseq to avoid possible immediate sequence mismatch

server/reload_test.go, server/server.go
The fix from #4360 will not work for v2.10 branch features so removing from dev and working on a different PR.
=> Remove reload fix from main

test/accounts_cycles_test.go
Added timeout to test to prevent running into go test timeout in case messages did not arrive on time.
```
=== RUN   TestAccountImportSubjectMapping
panic: test timed out after 30m0s
goroutine 85 [chan receive, 29 minutes]:
github.com/nats-io/nats-server/v2/test.TestAccountImportSubjectMapping(0xc000007d40)
/workspace/build/buildkite/synadia/nats-server-go-v1-21/test/accounts_cycles_test.go:466 +0x5d2
testing.tRunner(0xc000007d40, 0x11e1818)
/usr/local/go/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
/usr/local/go/src/testing/testing.go:1648 +0x82b
```
=> test: fix TestAccountImportSubjectMapping hanging build

server/leafnode_test.go
It would fail sometimes locally otherwise...
```
=== RUN   TestLeafNodeSlowConsumer
leafnode_test.go:7069: got: 0, expected: 1
--- FAIL: TestLeafNodeSlowConsumer (0.29s)
=== RUN   TestLeafNodeSlowConsumer
leafnode_test.go:7069: got: 0, expected: 1
--- FAIL: TestLeafNodeSlowConsumer (0.28s)
=== RUN   TestLeafNodeSlowConsumer
--- PASS: TestLeafNodeSlowConsumer (0.28s)
=== RUN   TestLeafNodeSlowConsumer
leafnode_test.go:7069: got: 0, expected: 1
--- FAIL: TestLeafNodeSlowConsumer (0.28s)
=== RUN   TestLeafNodeSlowConsumer
--- PASS: TestLeafNodeSlowConsumer (0.28s)
```
=> test: fixes for TestLeafNodeSlowConsumer

server/events.go
Minor update to server info structures
=> Missing json tag

server/jetstream_cluster_3_test.go
This flaky test seems not to be a real issue, but it's time-sensitive.
After adding retries, it succeeded ~1k times on local runs.
Target against `main`, as it happens also on main.
=> Fix flaky TestJetStreamClusterConsumerFollowerStoreStateAckFloorBug

server/routes_test.go
=> Fixed a route pooling flapper

server/filestore.go
=> [FIXED] Fix on rebuild first when rebuild results in empty block

server/filestore.go
=> [FIXED] Make sure order correct

go.mod, go.sum
=> Update to dependencies

server/filestore.go, server/jetstream_cluster_3_test.go
=> [FIXED] Fix for a bug that would make normal streams use the wrong block size.

server/README-MQTT.md
- Adds MQTT implementation notes
=> [ADDED] README-MQTT.md: MQTT implementation notes

server/filestore.go, server/filestore_test.go, server/jetstream.go, server/jetstream_test.go, server/monitor_test.go, server/opts.go, server/opts_test.go, server/server.go, server/stream.go
=> Added ability to control sync intervals and sync always

server/mqtt.go
Fixes a panic in error handling/logging
=> [FIXED] MQTT: panic in an error log

test/accounts_cycles_test.go
When it fails it hangs the build.
```
=== FAIL: test  (0.00s)
--
  | panic: test timed out after 10m0s
  | running tests:
  | TestAccountSubjectMapping (9m57s)
goroutine 115 [chan receive, 9 minutes]:
--
  | github.com/nats-io/nats-server/v2/test.TestAccountSubjectMapping(0xc000274ea0)
  | /go/test/accounts_cycles_test.go:388 +0x445
  | testing.tRunner(0xc000274ea0, 0x11f5df8)
  | /usr/local/go/src/testing/testing.go:1595 +0x239
  | created by testing.(*T).Run in goroutine 1
  | /usr/local/go/src/testing/testing.go:1648 +0x82b
```
=> flakes: Fix TestAccountSubjectMapping

server/events_test.go, server/jetstream.go, server/jetstream_test.go
Also fixes some tests using default JS dir instead of TempDir
=> flake: Fixes TestAccountReqMonitoring

server/jetstream_cluster.go, server/jetstream_cluster_2_test.go
=> Better fix for flapping test - TestJetStreamClusterStaleReadsOnRestart

server/norace_test.go
=> [FIXED] Test fix for TestNoRaceJetStreamClusterStreamReset

server/const.go
=> Bump to 2.10.0-RC.1

server/jetstream_api.go
=> [FIXED] Fix for data race accessing consumer assignment

server/events.go
=> [FIXED] Data race, protect access to c.acc

server/filestore.go
=> [FIXED] We will panic since we unlock the mb in removeMsgBlock

server/filestore.go
=> [FIXED] Protect against going upside down on mb.msgs.

server/consumer.go, server/jetstream_api.go
Co-authored-by: Derek Collison <derek@nats.io>
=> Fix consumer info if consumer was closed

.github/workflows/cov.yaml, scripts/cov.sh
=> Fixed code coverage GithHub Action

README.md, server/const.go
Signed-off-by: Your Name <wally@nats.io>
=> Release v2.10.3

server/jetstream_cluster.go, server/jetstream_cluster_1_test.go, server/stream.go
Report the raft group name in stream and consumer info
=> Report the raft group name in stream and consumer info

server/mqtt.go, server/mqtt_test.go
=> [FIXED]  #4664 mqtt retained messages memory leak

server/consumer.go, server/jetstream_api.go
=> Fix panic if a store error occurs when requesting consumer info

server/core_benchmarks_test.go
Some refactoring and cleanup for the recent PR I submitted (#4660), which added core fan-in and fan-out benchmarks. 
Changes have already been discussed and approved by @mprimi.
Signed-off-by: Reuben Ninan <reuben@nats.io>
=> [FIX] Refactor fan-in/fan-out core benchmarks

server/filestore.go, server/memstore.go
=> Don't purge entire stream for sequence 1

server/stream.go
NPE seen in Antithesis report, but struggling to see how it could be possible.
=> [FIXED] Check that we have a valid msgs ipq prior to proceeding.

server/filestore.go
=> [IMPROVED] Recycle buffers on rebuild and write out our full state prior to snapshotting

server/consumer.go
Be more stringent on setting the leader. Use atomic swap to make sure only one is running as leader.
Had a situation where the consumer processed multiple setLeader calls and had multiple loopAndGather routines running.
=> [FIXED] Avoid concurrent consumer setLeader calls to run multiple leaders.

server/consumer.go
This is optimization for last change, the get last works but not if number of subjects is very large, for that fall back to subjects state.
=> Make sure if we have lots of subjects to fallback to subjects state

server/jetstream_cluster.go, server/jetstream_consumer_test.go
=> Fix last per subject with multiple filters validation check

server/filestore.go
Limit to at most once every 10s.
We will schedule timer so that the signal is not lost.
Also after first run through of writeFullState track the avg dmap encoded len for subsequent runs.
=> [IMPROVED] Throttle writeFullState from separate go routine. 

server/filestore.go, server/filestore_test.go
=> [FIXED] Make sure to properly remove meta files for filestore after conversion.

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go
=> [FIXED] Make sure we check limits when scaling up a stream.

server/raft.go, server/raft_test.go
This PR backports the following into the v2.9.24 branch:
* #4684 
* #4725
* #4727
=> Backports into v2.9.24

server/mqtt.go
Show `clean` in CONNECT traces as applicable.
=> [ADDED] MQTT: show clean flag in Trace

server/filestore.go
When deleted entries went from none to some on small full states we would see reallocations.
Also optionally use 4k stack and avoid any allocation, and always check if deleted > 0 and adml is still 0.
=> [IMPROVED] Estimation on full state allocations to avoid reallocations.

server/filestore.go
Prior to 2.10 we depended on per block subject metadata, the fss files. We used subject interning to cut down on the number of duplicate strings.
With 2.10, we have a builtin version of this with fs.psim that tracks all in use subjects for the filestore. We can just use that, which should be friendlier on memory buildup vs the global subject interning.
=> [IMPROVED] Memory usage with lots of subjects in filestores.

server/client.go, server/consumer.go, server/jetstream_cluster.go, server/mqtt.go
=> [IMPROVED] Remove places where we were using time.After could cause gc pressure.

server/events.go
When determining if we should check for interest for sending statsz, take into consideration leafnodes that may extend the system account.
=> [IMPROVED] Better check for standalone mode when determining to send statsz.

server/filestore.go, server/jetstream.go
Will will remove by doing meta inline in case there are perm errors.
=> [IMPROVED] Move removal of fs.Delete files to a go routine

go.mod, go.sum
=> [UPDATED] Dependency update for x/crypto

server/filestore.go, server/filestore_test.go
This led to some bug fixes around compaction where the states diverged. 
Also made all filestore tests that used permutations helper actually do encryption and be more standard.
=> [IMPROVED] Added in internal filestore state checks on write and recover.

server/raft.go
When the raft layer receives an index less than ours, if all else ok simply ack.
=> [IMPROVED] Avoid resetting WAL in RAFT layer if we already processed msg.

server/mqtt.go
Revert https://github.com/nats-io/nats-server/pull/4825. It had at least one significant issue that needs to be fixed.
`git revert e0d45bd5fcd83d70785ef767493c533684a1cee7` was clean
=> Revert #4862

README.md
Changes to always point to latest release in the badge.
=> Make readme release badge dynamic

go.mod, go.sum
=> [IMPROVED] Dependency updates

server/consumer.go, server/jetstream_consumer_test.go, server/stream.go
Closes https://github.com/nats-io/nats-server/issues/4826
=> Check all filterSubjects of consumers when purging a stream

server/filestore.go
We do not always need the tokenized subject here.
Signed-off-by: Sven Neumann <sven.neumann@holoplot.com>
=> Move tokenizing of subject after early returns

server/filestore_test.go, server/jetstream_cluster.go, server/jetstream_cluster_3_test.go, server/norace_test.go
=> [FIXED] Fix for some flapping tests.

server/jetstream_cluster.go
=> [IMPROVED] Only call into stream update() iff the config has changed.

server/accounts.go
The `*rand.Rand` in the account is not thread-safe. This should fix #4893.
=> Guard account random number generator with mutex

go.mod, go.sum, server/accounts.go, server/filestore_test.go, server/jetstream_cluster.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/jetstream_cluster_3_test.go, server/jetstream_helpers_test.go, server/mqtt_test.go, server/norace_test.go, server/raft.go
Cherry-picks the following PRs into the v2.10.8 release branch:
* #4894
* #4898
* #4895
* #4897
* #4896
=> Cherry-pick PRs into v2.10.8 release branch

server/filestore.go, server/filestore_test.go
=> [IMPROVED] Make sure to flush cache during PurgeEx to avoid memory bloat.

server/jetstream.go, server/jetstream_cluster.go, server/jetstream_cluster_2_test.go, server/jetstream_jwt_test.go, server/stream.go
Also added in reporting for account info for reserved storage.
=> [FIXED] Fixes for JetStream accounting for replicas. 

server/jetstream_api.go, server/jetstream_cluster_3_test.go
=> [IMPROVED] Return account not enabled for JetStream when accessing via system account

server/accounts.go, server/leafnode.go, server/leafnode_test.go, server/server.go
We should update the leafnode connection's smaps correctly.
Resolves: #4934 
=> [FIXED] Reloads that contain mapping updates for global account with leafnodes.

server/auth.go, server/leafnode.go, server/leafnode_test.go, server/opts.go
=> [FIXED] Allow leafnode authorization to support nkeys.

server/accounts.go
The previous response was attempting to look like a typical Api response but in the process invented its own way of representing error and more making it really hard for users to figure out how this is supposed to look.
Added a struct that retains the non standard behavior while working on CLI tooling
=> Formalize claims update response

server/stream.go
Fixed setStartingSequenceForSources line using the wrong variable name
=> [FIXED] setStartingSequenceForSources could panic in some specific scenarios

README.md
=> Release v2.10.9

server/jetstream_cluster.go
=> [FIXED] Fix for a datarace with stream stop and removal from jsa.streams.

server/filestore.go, server/raft.go
In extended stress testing we ran into more issues with concurrent blocking IO and the Go runtime. We had the gated semaphore already in use but not everywhere.
=> [IMPROVED] Utilize our IO gated semaphore more comprehensively.

server/accounts.go, server/auth_callout.go, server/auth_callout_test.go, server/filestore.go, server/jetstream.go, server/jetstream_events.go, server/jetstream_test.go, server/mqtt.go, server/mqtt_test.go, server/raft.go
Includes:
- #5013 
- #5017 
- #5019 
- #5022
=> Cherry-pick PRs into v2.10.10 release branch 

server/routes_test.go
=> Fix flapping test TestRouteCompressionAuto

server/msgtrace.go
=> Fix message tracing staticcheck reports

server/mqtt_test.go
The order of messages was always the same on my machine, but doesn't have to be.
=> [FIXED] flapping TestMQTTDecodeRetainedMessage

server/filestore.go, server/jetstream_cluster.go, server/jetstream_cluster_3_test.go, server/stree/node.go, server/stree/parts.go, server/stree/stree.go, server/stree/stree_test.go
=> Cherry picks for Release v2.10.11 

server/filestore.go
When doing firstMatching we were picking wrong on linearScans. We also did not optimize the subjectIsSubsetMatch functionality.
=> [IMPROVED] Filtered consumers retrieval speed.

server/sublist.go
=> [IMPROVED] This version exits sooner for longer subjects

server/leafnode_test.go
=> Additional test to check that changing subject map values takes effect on reloads.

server/mqtt.go, server/mqtt_test.go
=> [FIXED] MQTT: (in v2.11) header length calculation for stored retained messages

server/leafnode_test.go, server/server.go
=> [FIXED] Make sure to not remove mappings that just had their value changed.

.travis.yml, scripts/runTestsOnTravis.sh
Also fixes golang-ci version to work with Go v1.22
=> Build with Go v1.22

.github/workflows/tests.yaml
WIP.. trying out a parallel unit test CI process in GHA alongside Travis
=> GitHub Actions

server/consumer.go
When we were checking if the consumer was assigned we were doing it with the consumer lock being held which is a lock inversion.
We also needed to lock the account when accessing the jsa to avoid a data race.
=> [FIXED] Data race and lock inversion on consumer delete.

server/jetstream_api.go, server/norace_test.go
=> [FIXED] Slow ack for snapshots could cause slow consumer and client disconnect.

server/consumer.go, server/jetstream_cluster_2_test.go
=> [FIXED] Fix for a test flapper with expire frequency change

server/jetstream_api.go
=> [IMPROVED] Make sure we have decent room in acks since we do not block on insert.

server/stree/parts.go, server/stree/stree_test.go
=> [FIXED] Stree not matching when partial parts were compared to long fragments

server/jetstream_cluster.go, server/stream.go
Locking order is clMu then mset lock.
=> Lock when bumping clfs. Make sure to unlock mset lock before bumpCLFS.

go.mod, go.sum, server/filestore.go, server/filestore_test.go, server/jetstream_api.go, server/jetstream_cluster_3_test.go, server/jetstream_test.go, server/memstore.go
- https://github.com/nats-io/nats-server/pull/5145
- https://github.com/nats-io/nats-server/pull/5153
- https://github.com/nats-io/nats-server/pull/5104
=> Cherry picks for release/v2.10.12

server/filestore.go, server/gateway.go, server/gateway_test.go
=> Cherry picks for release v2.10.12

server/raft.go
This reverts #4990 for now.
From a Raft correctness perspective I think removing the step-down channel is the right thing to do, but it has a negative impact on the amount of time taken to complete stream moves currently (seemingly they wait for an election timeout) so I want to better understand what's going on there and to make sure that the cooperative leader handover is doing the right thing before we reintroduce those changes.
`TestJetStreamSuperClusterMovingStreamAndMoveBack/R3` shows the issue for future reference.
=> Revert #4990

server/consumer.go, server/norace_test.go
1. Big fix on check ack floor was off by one when setting via pending.
2. Remove from redilver queue <= stream floor not just <.
3. Update skipped only when increasing o.sseq, saves lots on network.
=> [FIXED] Improved edge situations that could leave orphan msgs in workqueues.

server/mqtt.go, server/mqtt_ex_test.go, server/mqtt_test.go, server/proto.go
=> Added [ND]DEATH timestamp rewrite

go.mod, go.sum
=> Update go client to 1.34.1

scripts/runTestsOnTravis.sh
I missed this change in #5275.
=> Update CI to run new store tests

go.mod, go.sum, server/consumer.go, server/filestore.go, server/filestore_test.go, server/jetstream_api.go, server/jetstream_cluster.go, server/jetstream_cluster_3_test.go, server/memstore.go, server/stream.go
Includes
- https://github.com/nats-io/nats-server/pull/5283
- https://github.com/nats-io/nats-server/pull/5287
=> Cherry picks for release/v2.10.14

server/jetstream_cluster_3_test.go, server/raft.go
=> [FIXED] Fix for dangling NRG directories (mostly consumers) when deleted.

internal/fastrand/fastrand.go, logger/syslog_windows_test.go, server/events.go, server/jetstream_cluster.go
=> chore: fix function names in comment

server/stream.go
Saw a flapping test that was not properly clearing out messages and this was why.
=> [FIXED] Do normal purge if ack floor is higher then our last. Do not skip.

server/filestore.go
Includes:
- https://github.com/nats-io/nats-server/pull/5298
Also the following PR was already included in the release/v2.10.14 branch this [commit](https://github.com/nats-io/nats-server/commit/6c59372136b2bb8a233a2c5d9620b32ed682a93f):
- https://github.com/nats-io/nats-server/pull/5295
=> Cherry picks for release v2.10.14

server/filestore.go
We detected issues with sync on certain storage subsystems. So will hold lock for msg block while calling sync.
=> [IMPROVED] Hold the lock for a msg block while calling sync.

.travis.yml, server/filestore.go
Cherry-picks the following into the v2.10.14 release branch:
* #5300
* #5301
=> Cherry-pick PRs for v2.10.14-RC.6

server/filestore.go
=> [IMPROVED[ Also hold the fs lock while sync call to index.db

server/tpm/js_ek_tpm_windows.go
The `base64.StdEncoding.AppendEncode(...)` and `base64.StdEncoding.AppendDecode(...)` functions were only added in Go 1.22 and the Rust client Windows tests picked up on this as they are running Go 1.21.
=> TPM: Replace `AppendEncode`/`AppendDecode` as not available in Go 1.21

server/certstore/certstore_windows.go, server/jetstream_cluster_2_test.go, server/jetstream_test.go, server/mqtt.go, server/mqtt_ex_test.go, server/raft.go, server/route.go, server/routes_test.go, server/stream.go, server/websocket.go, test/ocsp_peer_test.go
Signed-off-by: Your Name <your.email@example.com>
=> Fix some comments

server/jetstream_cluster.go
As `calculateSyncRequest` requires the lock to be held, but the callers in `processSnapshot` also have a `defer` which tries to take the lock, any scenario in which `calculateSyncRequest` panics will result in a deadlock scenario on the stream lock.
As seen in cases like:
```
goroutine 161529372 [sync.RWMutex.Lock, 299 minutes]:
sync.runtime_SemacquireRWMutex(0x484a7a?, 0x28?, 0xc00419c2f0?)
runtime/sema.go:87 +0x25
*** CALLER TRIES TO LOCK AGAIN: ***
sync.(*RWMutex).Lock(0x0?)
sync/rwmutex.go:152 +0x6a
github.com/nats-io/nats-server/v2/server.(*stream).processSnapshot.func2()
github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:8048 +0x45
*** PANIC CAUSES DEFER IN CALLER: ***
panic({0xabf280?, 0x106a1b0?})
runtime/panic.go:920 +0x270
*** LOCK TAKEN BEFORE HERE: *** …
```
=> Fix potential deadlock if `calculateSyncRequest` panics

server/consumer.go, server/jetstream_consumer_test.go
When we failed to deliver a message, meaning the server knows it was not delivered, we did not properly send the message with deliver count of 1 when we redelivered.
Also fixed a bug where if a message was pulled from rdq but did not have a valid waiting request we would not redeliver until ackWait expired even though was never delivered to the client.
Updated test to make sure NumDelivered was always 1.
Big thanks to @piotrpio for finding the issue and writing first test to show the issue.
=> [FIXED] Delivery counts on failed deliveries.

server/filestore.go, server/norace_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5363
=> Cherry picks for release/v2.10.15

server/filestore.go
=> [IMPROVED] Simplify writing the full state to index.db and protect with dios.

server/events.go, server/events_test.go, server/monitor.go, server/monitor_test.go
=> Add a exprvar monitoring endpoint

server/events.go, server/events_test.go, server/filestore.go, server/filestore_test.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/monitor.go, server/monitor_test.go, server/norace_test.go, server/stream.go
Includes:
- https://github.com/nats-io/nats-server/pull/5378
- https://github.com/nats-io/nats-server/pull/5379
- https://github.com/nats-io/nats-server/pull/5380
- https://github.com/nats-io/nats-server/pull/5374
=> Cherry picks for v2.10.15 RC.6

server/consumer.go, server/jetstream_test.go, server/stream.go
Resolves https://github.com/nats-io/nats-server/issues/5383
=> Fix Interest stream should drop message when no interest based on FilterSubjects

go.mod, go.sum, server/consumer.go, server/filestore.go, server/filestore_test.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/jetstream_cluster_3_test.go, server/jetstream_cluster_4_test.go, server/jetstream_helpers_test.go, server/jetstream_sourcing_scaling_test.go, server/jetstream_super_cluster_test.go, server/jetstream_test.go, server/raft.go, server/stream.go
Includes:
- https://github.com/nats-io/nats-server/pull/5384
- https://github.com/nats-io/nats-server/pull/5385
- https://github.com/nats-io/nats-server/pull/5386
- https://github.com/nats-io/nats-server/pull/5388
- https://github.com/nats-io/nats-server/pull/5389
=> Cherry picks for v2.10.15 RC.7

server/stream.go
=> [FIXED] Make sure to set deliver by time policy

server/accounts.go, server/client.go, server/events_test.go, server/jwt_test.go, server/monitor.go, server/route.go, server/server.go
Includes:
- https://github.com/nats-io/nats-server/pull/5398
- https://github.com/nats-io/nats-server/pull/5399
=> Cherry picks for v2.10.15 RC.9

server/filestore.go, server/filestore_test.go
1. If we think out filter matches our stream do linear since first should match.
2. If literal, make sure to look up directly from fss and uses ss.First as fseq, bypass other logic.
3. Only do fss scan if len(fss) is 25% of scan range.
=> [IMPROVED] LoadNextMsg performance.

server/filestore.go, server/filestore_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5401
=> Cherry picks for v2.10.15 RC.10

conf/lex.go, conf/parse_test.go, server/jetstream_cluster.go, server/server_test.go
Includes: 
- https://github.com/nats-io/nats-server/pull/5432
- https://github.com/nats-io/nats-server/pull/5431
- https://github.com/nats-io/nats-server/pull/5406
=> Cherry picks for v2.10.15 release

conf/lex.go
=> [FIXED] Fix for lex block start on comments to return to lex block start.

go.mod, go.sum
=> Update NATS client

conf/lex.go, conf/parse_test.go
=> Test for block with top level comment after value parse bug

server/jetstream_cluster_4_test.go
More tests to cover rollout restarts under certain conditions.
=> Add more cases to TestJetStreamClusterBusyStreams

server/events.go, server/stream.go
Includes:
- https://github.com/nats-io/nats-server/pull/5460
- https://github.com/nats-io/nats-server/pull/5457
=> Cherry-picks for 2.10.16

server/reload.go, server/server.go
Add a few comments on re-use of the Options type. (Don't do it)
Closes #5465 
Signed-off-by: Robin Ketelbuters <robin.ketelbuters@gmail.com>
=> Add comments on re-use of the Options type

server/filestore.go, server/filestore_test.go
=> [FIXED] Performance regression in LoadNextMsg with very sparse or no msgs.

server/events.go, server/events_test.go, server/jetstream_helpers_test.go, server/jetstream_super_cluster_test.go
Also minor fix for new test to cleanup cluster when done.
=> Fixes for tests that depend on fast statsz

server/accounts.go, test/accounts_cycles_test.go
Resolves https://github.com/nats-io/nats-server/issues/1789
Signed-off-by: Semen Svirkov semakasyrok1@gmail.com
=> [FIXED] improved checks of account cycling

server/raft.go
Optimizes #5504 by moving the tests for queued appendEntryResponses to the start of `lostQuorumLocked()` rather than at the end.
=> Optimize #5504

go.mod, go.sum, locksordering.txt, server/accounts.go, server/filestore.go, server/filestore_test.go, server/jetstream_cluster.go, server/jetstream_cluster_4_test.go, server/jetstream_sourcing_scaling_test.go, server/leafnode.go, server/memstore.go, server/memstore_test.go, server/monitor.go, server/norace_test.go, server/raft.go, server/server.go, server/signal.go, server/stream.go, test/accounts_cycles_test.go
- https://github.com/nats-io/nats-server/pull/5494
- https://github.com/nats-io/nats-server/pull/5497
- https://github.com/nats-io/nats-server/pull/5501
- https://github.com/nats-io/nats-server/pull/5503
- https://github.com/nats-io/nats-server/pull/5504
- https://github.com/nats-io/nats-server/pull/5505
- https://github.com/nats-io/nats-server/pull/5508
- https://github.com/nats-io/nats-server/pull/5509
- https://github.com/nats-io/nats-server/pull/5506
=> Cherry picks for v2.10.17 RC.2

server/consumer.go, server/jetstream_cluster_4_test.go, server/jetstream_test.go
=> [IMPROVED] Make sure ack processing is consistent and correct between leader and followers.

server/filestore.go, server/filestore_test.go
=> [IMPROVED] Make sure to use psim on loadLast with a wildcarded subject.

server/accounts.go, server/auth.go, server/auth_callout_test.go, server/client.go
=> Cherry-picks for 2.10.17

.github/workflows/mqtt-test.yaml, server/mqtt_ex_test_test.go
Removed leaf-node related `TestXMQTTRetained...` test cases, they were too flaky.
=> [TEST only] removed some flakier test of TestXMQTT

server/client.go
=> [FIX] Avoid data race storing mpay from a JWT claim

server/consumer.go
=> [FIX] Protect against no mset or mset.ackq

server/jetstream_cluster.go, server/raft.go
=> [FIX] Data race in runAsLeader.

server/filestore.go
We could still use find if we know the status of wildcard.
=> [FIXED] Had a perf regression with some fss fixes.

.travis.yml, go.mod, go.sum, server/consumer.go, server/filestore.go, server/filestore_test.go, server/memstore.go, server/stree/stree.go, server/stree/stree_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5610
- https://github.com/nats-io/nats-server/pull/5618
- https://github.com/nats-io/nats-server/pull/5616
- https://github.com/nats-io/nats-server/pull/5627
- https://github.com/nats-io/nats-server/pull/5629
- https://github.com/nats-io/nats-server/pull/5630
- https://github.com/nats-io/nats-server/pull/5632
- #5635
=> Cherry-picks for 2.10.18-RC.1

server/consumer.go, server/jetstream_cluster_2_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5639
=> Cherry-picks for 2.10.18-RC.2

.goreleaser.yml, scripts/runTestsOnTravis.sh, server/const.go, server/filestore.go, server/jetstream_cluster.go, server/jetstream_cluster_2_test.go, server/jetstream_test.go, server/monitor.go, server/server_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5649
- https://github.com/nats-io/nats-server/pull/5651
- https://github.com/nats-io/nats-server/pull/5650
- https://github.com/nats-io/nats-server/pull/5655
=> Cherry-picks for 2.10.18-RC.3

server/events.go
=> [FIXED] Prevent a server from panicking when shutdown immediately after starting.

server/monitor.go, server/monitor_test.go, server/opts.go
Reports some often requested information about JS config in jsz
=> Report the js limits in jsz output

server/errors.json, server/jetstream_errors_generated.go
Signed-off-by: Piotr Piotrowski <piotr@synadia.com>
=> Improve error message for JSConsumerPullRequiresAckErr

server/client.go
=> Fix panic in `getAccAndResultFromCache`

server/monitor.go
This makes it possible to collect a CPU profile via `profilez`. The CLI would need to be updated to add support for this since it requires sending a `"duration"`.
=> Add support for collecting CPU profiles via `profilez`

go.mod, go.sum
=> [IMPROVED] Dependency updates for x/sys and x/time

server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/jetstream_helpers_test.go, server/norace_test.go, server/raft_test.go
This PR tries to deflake some unit tests.
=> De-flake tests

server/jetstream_cluster.go
This was leaving dangling goroutines and creating confusing logging in unit test runs.
=> Cancel pending `checkForOrphans` on cluster monitor exit

server/jetstream_cluster.go, server/jetstream_cluster_3_test.go, server/jwt_test.go, server/stream.go
Includes:
- https://github.com/nats-io/nats-server/pull/5773
- https://github.com/nats-io/nats-server/pull/5771
=> Cherry picks for v2.10.19 RC4

server/jetstream_test.go
=> Test to verify removing and adding back in a source stream works as expected.

server/jetstream_cluster_3_test.go
Wait for stream leader after scale up should avoid some reliability isses. Also tweak helpers for better logging.
=> Tweak `TestJetStreamClusterStreamMaxAgeScaleUp`

server/server.go, server/server_test.go
=> [FIXED] Fix for new static check failure.

server/raft_test.go
=> De-flake `TestNRGUnsuccessfulVoteRequestDoesntResetElectionTimer` (again)

server/jetstream_cluster.go
But log the rest at debug for dev purposes
=> Log only durable orphaned consumers

server/accounts.go, server/opts.go
=> Stricter validation of `cluster_traffic` option

server/events.go, server/jetstream_cluster_4_test.go, server/monitor.go
=> Add `pending` to `jsz` response and `statsz`

server/events.go, server/server.go
=> Publish STATSZ messages every 10 seconds rather than 30

server/events.go, server/jetstream_cluster_4_test.go
=> Ensure `pending` sent correctly in regular `statsz` messages

server/events.go, server/jetstream_cluster.go, server/jetstream_cluster_4_test.go, server/server.go
Includes:
- #5925
- #5926
- #5927
=> Cherry-picks for 2.10.21-RC.4

server/client.go, server/client_test.go
=> Reject publishes on `$NRG.>` subjects from non-system clients

.travis.yml
Signed-off-by: Waldemar Quevedo [wally@nats.io](mailto:wally@nats.io)
=> Update Go versions

go.mod, go.sum
=> [UPDATED] Update for github.com/klauspost/compress

.travis.yml, server/signal_test.go
=> Use smaller workers in Travis CI

logger/log.go, server/const.go, server/consumer.go, server/filestore.go, server/jetstream_cluster_4_test.go, server/jetstream_test.go, server/raft.go, server/server.go
=> Release v2.10.22

server/jetstream_cluster_4_test.go
These two tests, but particularly `TestJetStreamClusterDesyncAfterPublishToLeaderWithoutQuorum`, could flake depending on timing. Now there are a couple of retries, ensuring still converging to the correct state.
=> De-flake JetStream converging state tests

server/jetstream_cluster_4_test.go
=> De-flake TestJetStreamClusterPendingRequestsInJsz

scripts/runTestsOnTravis.sh
=> Update `golangci-lint` to v1.62.0

server/jetstream_cluster_4_test.go
Example test failure:
```
=== RUN   TestJetStreamClusterDontInstallSnapshotWhenStoppingConsumer
jetstream_cluster_4_test.go:4756: require uint64 equal, but got: 4 != 3
--- FAIL: TestJetStreamClusterDontInstallSnapshotWhenStoppingConsumer (1.21s)
```
Explicitly set the expected applied value for the stream/consumer. Instead of having it be dynamically determined, which could flake.
=> De-flake don't InstallSnapshot on stop tests

server/jetstream_cluster_4_test.go
=> De-flake don't InstallSnapshot when stopping tests

server/jetstream_cluster_4_test.go
The test checks if stream state and messages equal, but also checks if the consumer pending count matches with the amount of messages in the stream. For clustered streams this consumer pending check would be done before the cluster is stabilized, so it could fail at that stage.
Move those checks down so we at least confirm the stream states are equal first before we check pending.
=> De-flake drifting test, check consumer pending after stabilized

server/jetstream_cluster.go
This adds extra WRN level logging to detect cases when there is a slowness in the metalayer snapshot duration, example line:
```
[WRN] Metalayer snapshot took 1.113s (streams: 326, consumers: 29382, marshal: 1.103s, uncompressed: 33268722, compressed: 2768064)
```
=> Add logging for large metalayer snapshots duration

server/events.go, server/jetstream_cluster.go, server/jetstream_cluster_4_test.go
- https://github.com/nats-io/nats-server/pull/6183
- https://github.com/nats-io/nats-server/pull/6185
=> Cherry-picks for 2.10.23-RC.7

server/jetstream_test.go, server/memstore.go
=> [FIXED] Memory stream compact should clear subjects state & hold write lock

server/thw/helper_test.go, server/thw/thw.go, server/thw/thw_test.go
A timed hash wheel impl to support per msg ttls in streams / KVs.
=> [ADD] Initial timer hashwheel implementation

server/jetstream_cluster.go
Includes:
- https://github.com/nats-io/nats-server/pull/6200
- https://github.com/nats-io/nats-server/pull/6202
=> Cherry-picks for 2.10.23-RC.10

server/thw/thw.go, server/thw/thw_test.go
=> THW: Add binary encoding/decoding functions

server/filestore.go, server/jetstream_api.go, server/memstore.go
fix some function name in comment
=> chore: fix some function name in comment

.travis.yml
=> Update to Go 1.23.4, 1.22.10

server/raft_helpers_test.go
We didn't wait before for `smLoop(sm stateMachine)` to exit. This change introduces a wait group so we don't have multiple go routines running.
=> De-flake RAFT adder tests

server/jetstream_cluster_4_test.go
Moves the `wg.Wait()` up, this should prevent `Unexpected number of pending messages, stream=70000, consumers=69999` errors if consumers would still be actively consuming messages. Also check on an interval, since stream message count vs consumer pending state is async.
And, correctly checking if all streams report either an error or a message at the same sequence.
=> De-flake replicas drifting test

server/events.go, server/jetstream.go, server/jetstream_test.go, server/raft_helpers_test.go, server/raft_test.go, server/websocket.go, server/websocket_test.go
- https://github.com/nats-io/nats-server/pull/6260
- https://github.com/nats-io/nats-server/pull/6249
- https://github.com/nats-io/nats-server/pull/6264
- https://github.com/nats-io/nats-server/pull/6265
- https://github.com/nats-io/nats-server/pull/6266
=> Cherry-picks for 2.10.24-RC.3

server/jetstream_cluster_1_test.go, server/raft.go, server/raft_test.go
- https://github.com/nats-io/nats-server/pull/6269
- https://github.com/nats-io/nats-server/pull/6271
=> Cherry-picks for 2.10.24

server/jetstream_api.go, server/jetstream_super_cluster_test.go
Like #6282, this adds preferred placement support to stream and consumer stepdowns too. 
=> Add support for placement tags and `preferred` to stream and consumer stepdown requests

server/jetstream_cluster_4_test.go
- Warn when stream subjects and num pending counts in consumers differs but there is no stream drift
- Log the subjects and consumers maps when there is drift
=> Updates to TestJetStreamClusterStreamOrphanMsgsAndReplicasDrifting

server/filestore.go, server/filestore_test.go
If the raw message block size was large enough to compact and it contained mostly tombstones, compaction would not be very effective (as `mb.compact()` does not remove tombstones). In certain unfortunate scenarios we would spam compaction upon subsequent calls to `fs.RemoveMsg`, since every call would try to compact again.
When this condition was hit, it would decrease publisher throughput, slow down consumer acks if they remove messages due to WorkQueue/Interest retention, etc.
This fix checks if there was a compaction before, and if so there are potential savings.
=> [FIXED] Filestore doesn't spam compact when block contains mostly tombstones

.travis.yml
=> Update to Go 1.23.5/1.22.11

README.md
Points to
https://somsubhra.github.io/github-release-stats/?username=nats-io&repository=nats-server
=> Update README.md: add GitHub downloads badge

server/stream.go
=> Fix some subject delete marker errors

server/jetstream_cluster.go, server/jetstream_cluster_4_test.go
=> Cleanup comments from #6426

server/filestore.go
This updates `dios` to range up to 50% of the core count on a system with more than 32 CPU cores, otherwise obeying the 4 to 16 limit.
=> Increase disk I/O semaphore limit

server/websocket.go
This should ensure the compressors are more aggressively cleared and also handle a couple of error scenarios better by releasing/repooling buffers.
=> WebSocket compression fixes

server/monitor.go
Fixes: https://github.com/nats-io/nats-server/issues/6475
=> Populate pending_bytes in routez

server/jetstream_cluster_4_test.go
If the consumer leader would be different than the stream leader, that would result in a race condition in this test. Where the consumer leader has not yet applied the new message yet, returning an error like the following:
```
jetstream_cluster_4_test.go:1813: require int equal, but got: 35 != 50
```
This is due to the `sub.Fetch` immediately returning instead of waiting for the expire if the EOF of the stream is reached.
=> De-flake TestJetStreamClusterAckFloorBetweenLeaderAndFollowers

server/jetstream_cluster_3_test.go
=> De-flake TestJetStreamClusterInterestStreamConsumer

server/jetstream_cluster_2_test.go
`<-ms.ch` could block if no entries get pushed to it, so at least ensure we can't block indefinitely like below:
```
goroutine 18986 [chan receive, 18 minutes]:
github.com/nats-io/nats-server/v2/server.TestJetStreamClusterLeaderAbortsCatchupOnFollowerError(0xc00390e700)
/workspace/build/buildkite/synadia/nats-server-dev/server/jetstream_cluster_2_test.go:6996 +0x86b
testing.tRunner(0xc00390e700, 0x142deb0)
/usr/local/go/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 1
/usr/local/go/src/testing/testing.go:1851 +0x413
```
=> De-flake TestJetStreamClusterLeaderAbortsCatchupOnFollowerError

server/jetstream_jwt_test.go
=> De-flake JWT JetStream tests

server/jetstream_cluster_2_test.go
=> De-flake TestJetStreamClusterConsumerResetStartingSequenceToAgreedState/File

server/jetstream_cluster_1_test.go
`m.AckSync()` does not work/do anything when using `AckNone`, and the test could flake since message removals are proposed and might take a short amount of time to be removed.
=> De-flake TestJetStreamClusterConsumerAckNoneInterestPolicyShouldNotRetainAfterDelivery

server/raft_chain_of_blocks_helpers_test.go
Partially reverts https://github.com/nats-io/nats-server/pull/6593 to return to the original locking behavior for 'chain-of-blocks' tests.
The test became flaky due to the locking changes, since it introduced a race condition where snapshots could contain new data but with an old applied index, making the test fail.
Also the lock was not held in `leaderChange`.
(This was purely a test issue)
=> De-flake TestLongNRGChainOfBlocks

server/jetstream_cluster_3_test.go, server/jetstream_jwt_test.go
Follow-up of: https://github.com/nats-io/nats-server/pull/6598
=> De-flake more JWT tests

server/jetstream_cluster_3_test.go
Since the stream and consumer are clustered and the leaders could be on different servers, the delivered state could lag based on first needing to apply the stream message and then also requiring quorum to update delivered state.
Also, the test contains `InterestPolicy` but didn't actually test interest policy. Returned that to a prior version of the test that differentiated between Limits and Interest.
=> De-flake TestJetStreamClusterInterestPolicyEphemeral

.goreleaser.yml
Forgot to do this in the earlier #6618 PR, but will be done for RC.3.
=> Update goreleaser to Go 1.24.1

server/jetstream_helpers_test.go
Make somewhat consistent with the changes in https://github.com/nats-io/nats-server/pull/6364.
=> De-flake waitOnPeerCount

server/jetstream_cluster_1_test.go
Similar to https://github.com/nats-io/nats-server/pull/6586.
=> De-flake delete consumer with interest policy

server/leafnode_test.go
`c.prunePubPermsCache()` can not be run in parallel, so if the timing is right the purge would traverse the cache and remove some entries, while other goroutines are filling up the cache more quickly. This means that the cache can grow indefinitely with the `maxPruneAtOnce = 1000` and if parallel requests come in faster than that.
Just changing the test to see the `c.perms.pcsz` property as eventually falling below the desired maximum, but not being guaranteed to always be below it.
=> De-flake TestLeafNodePubAllowedPruning

server/jetstream_cluster_4_test.go
In a clustered environment deleting streams/consumers is not immediately performed on all servers.
=> De-flake TestJetStreamClusterConsumerNRGCleanup

server/jetstream_test.go
Core publish in one account may not be immediately available in a stream on another account, this is normal since a core publish doesn't wait for a response.
=> De-flake TestJetStreamImportReload

server/raft_test.go
=> Fix data race in `TestNRGSimpleElection`

server/jetstream_cluster_2_test.go
Amount of consumers on the stream can lag due to the consumer delete being answered by the old consumer leader, but the stream leader could be on a different server and apply it a bit later.
=> De-flake TestJetStreamClusterConsumerOverrides

server/jetstream_cluster_3_test.go
=> De-flake TestJetStreamClusterMetaRecoveryLogic

server/raft_test.go
=> De-flake TestNRGUnsuccessfulVoteRequestDoesntResetElectionTimer

server/norace_test.go
=> De-flake TestNoRaceFileStoreMsgLoadNextMsgMultiPerf

test/ocsp_test.go
=> De-flake TestOCSPLeaf(NoVerify)

server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/jetstream_helpers_test.go
Also de-flakes other tests by using strict/correct approach of checking all replicas agree on the same state.
=> De-flake TestJetStreamClusterUserSnapshotAndRestore

test/accounts_cycles_test.go
=> De-flake TestServiceImportReplyMatchCycle*

server/jetstream_cluster_4_test.go
=> De-flake TestJetStreamClusterStreamAckMsgR3SignalsRemovedMsg

server/jetstream_test.go
=> De-flake TestJetStreamConsumerMultipleSubjectsAck

server/gateway_test.go, server/jetstream_cluster_1_test.go, server/jetstream_super_cluster_test.go, server/jetstream_test.go, server/mqtt_test.go, server/msgtrace_test.go, server/norace_test.go, test/accounts_cycles_test.go
=> De-flake various tests

server/reload.go, server/route.go, server/routes_test.go, server/server.go
This is to allow rolling upgrades with a change to a different pool size. It is still STRONGLY recommended to have all servers of the same cluster use the same route pool size.
=> (2.11.x) [IMPROVED] Routing: Allow servers with different pool size

server/jetstream_cluster_1_test.go
=> De-flake `TestJetStreamClusterExtendedAccountInfo`

.github/workflows/long-tests.yaml, .github/workflows/mqtt-test.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yaml, .github/workflows/stale-issues.yaml, .github/workflows/tests.yaml
=> Various GHA tweaks

server/jetstream_cluster.go, server/jetstream_cluster_4_test.go
If a stream didn't have TTL enabled and a message was published with a dedupe message ID, then the second publish would be marked as duplicate even if it didn't contain the TTL.
=> [FIXED] Replicated stream with TTL and msg ID

server/events_test.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_3_test.go, server/jetstream_cluster_4_test.go, server/jetstream_super_cluster_test.go
=> De-flake unit tests

server/jetstream_cluster.go, server/jetstream_cluster_4_test.go
If a stream had TTLs enabled and sent a message with an invalid TTL and a message ID, then sending the same message again but with a valid TTL would be marked as duplicate.
=> [FIXED] Replicated stream with invalid TTL and msg ID

server/jetstream_leafnode_test.go, server/norace_test.go, server/raft_helpers_test.go, server/raft_test.go
=> Unit test fixes

test/service_latency_test.go
=> Fix TestServiceLatencyWithNameMultiServer flake

go.mod, go.sum
=> Update `nats.go` dependency

server/consumer.go, server/jetstream_consumer_test.go
When there are multiple pending requests for a consumer with priority group set, and some of the requests are not receiving (due to priority policy), it is possible to enter a tight loop in `consumer.nextWaiting()` if another pull request is recycled during execution.
=> [FIXED] Priority group waiting requests causing tight loop in nextWaiting

server/filestore_test.go
Some of the error handling in these tests was a bit suspicious-looking.
=> Improve read-only filestore tests

server/filestore.go, server/jetstream_test.go, server/memstore.go
The timed hash wheel is not thread-safe, so we must be very careful to hold the lock while doing calls to for example `hw.ExpireTasks`. However, `fs.removeMsg` unlocks and re-locks the store lock, which would result in multiple processes running `ExpireTasks` at once. That would decrement `hw.count` multiple times, resulting it to underflow. The server would then panic while shutting down when trying to allocate based on `hw.count` in `hw.Encode`.
=> [FIXED] THW race and panic with inline msg removal

.github/workflows/tests.yaml, .golangci.yml
=> Update `golangci-lint` to v2.1.2

server/consumer.go, server/filestore.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_2_test.go, server/jetstream_cluster_3_test.go, server/jetstream_cluster_4_test.go, server/jetstream_super_cluster_test.go, server/jetstream_test.go, server/norace_test.go, server/server_test.go, test/test.go
=> Backport test fixes for 2.10.28-RC.2

server/filestore.go, server/filestore_test.go, server/jetstream_cluster_1_test.go, server/jetstream_consumer_test.go, server/jetstream_helpers_test.go, server/norace_test.go, server/raft.go, server/sublist.go, server/sublist_test.go
* https://github.com/nats-io/nats-server/pull/6815
* https://github.com/nats-io/nats-server/pull/6825
* https://github.com/nats-io/nats-server/pull/6827
=> Cherry-picks for 2.10.28-RC.3

.github/workflows/release.yaml, .github/workflows/tests.yaml
=> Update GHA workflow dependencies

server/consumer.go, server/gsl/gsl.go, server/gsl/gsl_test.go, server/jetstream_cluster_1_test.go, server/jetstream_cluster_3_test.go, server/jetstream_consumer_test.go, server/jetstream_test.go, server/sublist.go, server/sublist_test.go
=> Cherry-picks for 2.10.29-RC.1

.github/workflows/tests.yaml
This will check both commits and PR descriptions for the `Signed-off-by:` statements in CI.
=> CI: Check sign-offs in pull requests and commit messages

server/filestore.go, server/jetstream_cluster_long_test.go, server/stree/stree.go, server/stree/stree_test.go
When all of the state was lost and we need to rebuild and enforce a max messages per subject limit, then the `enforceMsgPerSubjectLimit` function could linearly scan multiple times and become very expensive if there are lots of subjects. This refactors the function to use new subject tree intersection logic to more quickly work out if there is any overlap between the subjects needing attention and the subjects in a given block, meaning we only need to scan the store once.
=> Optimise `enforceMsgPerSubjectLimit`

server/client.go
In cases where we have known validation errors on a TLS certificate, include the subject name and the SHA-256 fingerprint of the certificate in the log line so that they can be more easily identified.
Example:
`[ERR] 127.0.0.1:50610 - gid:1 - TLS gateway handshake error: tls: failed to verify certificate: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs (CN=localhost,OU=nats.io,O=Synadia,ST=California,C=US SHA-256: cb11b587f11697bec4b369f7761283f8b536337c538b5a43c07105a906f9eb12)`
=> TLS: Include subject name and SHA-256 fingerprint in handshake error log lines where possible

server/events_test.go, server/filestore.go, server/leafnode_test.go, server/memstore.go, server/norace_2_test.go, server/store.go
- #6895
- #6899
- #6900
- #6908
=> Cherry-picks for 2.11.4-RC.2

server/filestore.go, server/jetstream_test.go, server/memstore.go, server/stream.go
- https://github.com/nats-io/nats-server/pull/6912
- https://github.com/nats-io/nats-server/pull/6911
=> Cherry-picks for 2.11.4-RC.3

server/README-MQTT.md
=> [FIXED] Fixed spelling in MQTT Readme

.github/workflows/release.yaml, go.mod, go.sum, server/README-MQTT.md, server/stree/stree.go, server/stree/stree_test.go
=> Cherry-picks for 2.11.4

.github/workflows/tests.yaml
=> Update CI to test Windows Server LTSC2022/2025 builds

.goreleaser.yml, go.mod
=> Update to Go 1.24.4/1.23.10

server/stream.go
The `mset.clMu` lock should be held when reading `mset.clfs`.
=> [FIXED] Hold mset.clMu when reading mset.clfs

server/jetstream_versioning.go, server/jetstream_versioning_test.go
Also includes a test to ensure we up the API level if we introduce a feature with a higher level.
=> (2.12) Up API level to 2

server/raft.go
=> Cherry-picks for 2.11.5-RC.2

server/jetstream_cluster.go
```
[INF] JetStream cluster new consumer leader for '$G > KV_bucket > p7eMKZwR'
```
This logline is often either confusing or annoying. It happens for every R1 ephemeral that's (re)created and may result in lots of noise when using many KV watchers for example. This line is purely a side-effect of running in a clustered environment, in a standalone server this wouldn't happen, and doesn't mean much because the leader of an R1 ephemeral is always known and will not change.
Still sending the advisory though, to ensure we stay compatible.
=> [IMPROVED] Don't log R1 ephemerals in clustered environments

server/consumer.go, server/jetstream_consumer_test.go
If the client reaches the `MaxWaiting` limit, it is better for it to wait for missed idle heartbeats instead before retrying or surfacing an error rather than handling a 409 and retrying immediately. Otherwise the client can place a lot of strain on the server with those repeated requests.
=> Do not respond on exceeding `MaxWaiting` limit when heartbeat interval specified

server/filestore.go, server/jetstream_test.go
When using encryption at rest, if a server was restarted it would not initialize the fields required for encryption in the filestore. If a write was performed on a message block, before any read, that message would not be encrypted. If a read would be performed after this, it would try to decrypt plaintext data resulting in the `indexCacheBuf corrupt record state` error.
=> [FIXED] Filestore indexCacheBuf corrupt with encryption

.goreleaser.yml, go.mod
=> Update to Go 1.24.5/1.23.11

server/configs/cluster.conf, server/gateway.go, server/gateway_test.go, server/opts.go, server/opts_test.go, server/route.go, server/routes_test.go
=> (2.12) Exponential backoff opt-in

server/sublist.go
=> Export `SubjectMatchesFilter`

server/monitor.go
This provides a way to associate to the connection.
```
Signed-off-by: Byron Ruth <byron@nats.io>
```
=> Add cid to LeafInfo

server/client.go
List the remote server name when closing a leaf/route/gateway connection.
Examples:
```
lid:5 - Leafnode connection closed: Client Closed - Remote: leaf, Account: $G
rid:15 - Router connection closed: Duplicate Route - Remote: nats-1
gid:5 - Gateway connection closed: Client Closed - Remote: gw2-nats-1
```
=> (2.12) [IMPROVED] Specify Remote on connection closed

server/jetstream_cluster.go, server/jetstream_cluster_1_test.go
Since https://github.com/nats-io/nats-server/pull/7075 we can now select offline peers for a stream, as long as we have a quorum of online nodes. However, now `rg.setPreferred()` can randomly select offline nodes, so need to prefer online nodes for random selection.
=> (2.12) [IMPROVED] Randomly set rg.Preferred to online node

server/jetstream_batching_test.go, server/stream.go
Resolves https://github.com/nats-io/nats-server/issues/6979
=> (2.12) Atomic batch: cleanup after disable/step-down/delete

server/consumer.go
Fixes a small race condition where the last ack for a message could be processed in `o.processAck(..)`, the inactivity timer could then hit and lock the consumer before we're able to `o.suppressDeletion()` (which also requires the lock).
Calling `o.suppressDeletion()` first means we can't race with the inactivity timer deleting the consumer due to acking the last pending message, when the last message pull request was longer ago than the `InactivityThreshold`.
Relates to https://github.com/nats-io/nats-server/issues/7102
=> [IMPROVED] Mark consumer active before processing acks

server/monitor.go
=> Fix typos in doc comments

server/jetstream_test.go, server/stream.go
- https://github.com/nats-io/nats-server/pull/7131
=> Cherry-picks for 2.11.7

server/jetstream_cluster.go
=> [FIXED] Mark monitorWg as done if goroutine not started

server/jetstream_cluster_4_test.go
Follow up from https://github.com/nats-io/nats-server/pull/7210
=> Add regression test for R3F multileader condition

server/pse/pse_test.go
The original TestPSEmulation checked both memory and CPU usage in a single run, causing instability in CPU measurements. Splitting the test, avoids any processing in between the CPU measurements from `ps` and `ProcUsage()`, such as the invoking the garbage collector through `debug.FreeOSMemory()`.
=> Split TestPSEmulation into memory and CPU tests

server/jetstream_batching_test.go, server/jetstream_cluster.go
When a batch gets partially proposed through for a replicated stream, it needs to be rejected. This already happened consistently within `applyStreamEntries`. But, the only case where this wouldn't happen was just outside of `applyStreamEntries` if the `len(ce.Entries) == 0`. Primary reason for this could be a leader change, at which point we need to reject the batch, but this could also apply to other scenarios.
Antithesis was able to reproduce a bug where a snapshot would be made with CLFS:0, and a server that got this snapshot would properly have rejected the batch and upped CLFS, but the snapshot would undo that and make the stream on that server be desynced.
=> (2.12) Atomic batch: reject partial batch on leader change

server/jetstream_batching_test.go, server/jetstream_cluster.go
Batch recovery path wouldn't take compressed messages into account, leading up to a panic.
=> (2.12) Atomic batch: recover compressed batch messages

server/filestore.go
This restores the access time consideration after flushing and also ensures that `expireCacheLocked()` does the right thing even if only a weak reference to the cache remains.
It also ensures the cache expiry timer is running if we do hold onto the cache due to the last access time at the end of a flush.
=> (2.12) Improve filestore cache expiry

server/jetstream_api.go
There were a few places that we were trying to access `cc.meta` unlocked, and one or two places where we could panic outright if it was `nil`.
=> Fix race conditions and potential panics in JS API endpoint meta handling

server/filestore.go, server/filestore_test.go, server/stream.go
* https://github.com/nats-io/nats-server/pull/7395
* https://github.com/nats-io/nats-server/pull/7396
=> Cherry-picks for v2.12.1-RC.3

.goreleaser.yml, go.mod
=> Update to Go 1.25.2/1.24.8
