nats-io/nats-server

- server/jetstream_cluster_2_test.go
- server/raft.go
> [IMPROVED] Make sure preferred peer for stepdown is healthy.

- server/filestore.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
This fixes issue when scaling Stream with MaxAge and some older
messages stored. Until this commit, old messages were not properly
expired on new replicas, because new replicas first expiry timer
was set to MaxAge duration.
This commit adds check if received messages expiry happens before
MaxAge, meaning they're messages older than the replica.
Resolves #3848 
> Fix new replicas late MaxAge expiry

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
Added optimized store NumPending() call.
Optimized and simplified fileteredPending() which also fixed a bug.
Optimized memstore FilteredState().
Added comprehensive tests for NumPending() and FilteredState().
> [FIXED] JetStream Store fixes and speedups.

- server/jetstream_cluster.go
- server/raft.go
When the truncate failed we would continue to process append entries without changing state.
This could result in raft stores filling up disks and systems becoming unresponsive.
The server log could also fill up with warnings similar to this one.
```[WRN] RAFT [z3WIzPtj - S-R2F-76KY41ow] Wrong index, ae is &{leader:z3WIzPtj term:1 commit:100 pterm:1 pindex:100 entries: 1}, index stored was 115, n.pindex is 100```
> [FIXED] If a truncate for a raft WAL failed we could spin.

- server/subject_transform.go
- server/subject_transform_test.go
Applies https://github.com/nats-io/nats-server/pull/3887 to dev (since I noticed the merge of main to dev of that PR effectively made it disappear (because stream transform changes included extracting transforms from accounts.go)
> Port https://github.com/nats-io/nats-server/pull/3887 to dev

- server/stream.go
Stream subject mapping added index prefix to Nats-Stream-Source which was stripped when retrieving that header. That caused startingSequenceForSources to iterate over the whole stream because of
name mismatch. Stripping was removed in this commit.
> Fix memory bloat when adding source to the stream

- server/monitor.go
- server/monitor_test.go
This adds a new `raft` query parameter to be able to map a stream/consumer name with its active raft group:
```
/jsz?consumers=1&raft=1
```
```js
"stream_raft_group": "S-R3F-8Qml10Ei",
"consumer_raft_groups": [
{
"name": "1",
"raft_group": "C-R3F-5c87s2aq"
},
{
"name": "10",
"raft_group": "C-R3F-PF8WWIue"
},
{
"name": "100",
"raft_group": "C-R3F-r58xhrRe"
},
{
"name": "12",
"raft_group": "C-R3F-faSs9EY1"
},
```
> Add raft query parameter to /jsz to include raft group info

- server/accounts.go
- server/jwt_test.go
Claims update message requires only payload to be passed, but passing headers should not fail the request.
This change ensures we extract the payload from the raw message before decoding it.
Before this change, passing claims update with headers would return cryptic `expected x chunks` error.
> Fix JWT claims update if headers are passed in request

- server/accounts.go
> Fix panic if serviceExport is nil

- server/opts.go
This ensures that the existing, default behavior of the server emitting the local timezone is not changed.
> Change logtime_utc default to false

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/raft.go
- server/stream.go
Various improvements based on user test framework that put the system under heavy IO and network loads.
> [IMPROVED] Performance and Stability under heavy IO loads.

- server/leafnode.go
- server/monitor.go
- server/monitor_test.go
resolves #3921 
Adds `Name` field to `LEAFZ` info for incoming and outgoing leafnode connections. This should allow observability tools to more easily identify leaf nodes without having to require SYS accounts set up for each leaf node connection.
> Update LEAFZ to include leafnode server/connection name

- server/leafnode.go
- server/monitor.go
- server/monitor_test.go
This is a followup on #3923 that improves LEAFZ names to use `ln.leaf.remoteServer` instead of the connection name.
I've also added `is_spoke` to the leafz LeafInfo struct so that we can easily tell if a leaf connection is a hub or spoke.
> Updated LEAFZ names to use remoteServer name/id and added is_spoke

- server/jetstream_cluster.go
- server/raft.go
> [FIXED] System stability improvements on restarts with corrupt metadata.

- server/consumer.go
- server/jetstream_test.go
Server did check for timeouts in `processWaiting`, but that needs to be also checked in `nextWaiting` in case of tight timings, as `nextWaiting` can remove Pull Request based on timeouts too.
> Fix Pull Consumer not sending request timeout

- server/jetstream_cluster.go
> [FIXED] Do not hold jetstream lock cleaning up orphans, could deadlock.

- server/filestore.go
We were already converting `key` to a `string` in the loop, so the use of a `strings.Builder` is additionally wasteful and burns CPU cycles for no reason. Let's just convert `key` once instead — when it becomes a string, it already stops referring to the underlying array anyway.
> Don't use string builder in `subjString` (it is slow)

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
Also make sure when scaling up streams that are workqueue or interest policy that consumers scale as well.
Resolves #3953
> [FIXED] Scaling up workqueue stream does not remove ack'd messages.

- server/ocsp.go
- test/ocsp_test.go
This changes ocsp handling so that leafnode remote client connections behave more similarly to how regular nats clients work, rather than mimic the bidirectional verification that happens for routes/gateways.
Resolves #3959
> Fix leaf client connection failing in OCSP setups

- server/filestore.go
Otherwise we might unnecessarily write out the fss file for no reason, which is possibly happening inline.
> Only mark fss dirty if a change is made

- .github/workflows/rc_nightly.yaml
The uses option requires a path that start with . for local files
> fix uses for embedded action in nightly build

- server/jetstream_cluster_3_test.go
- server/raft.go
> Don't warn if error is node closed.

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
Make sure to cleanup stream messages on a follower consumer for an interest based stream when the consumer leader sends a state snapshot.
When we would receive a state snapshot vs individual replicated acks we would not remove the stream's messages.
> Remove msgs from interest based stream on consumer snapshot.

- server/filestore.go
We already have a pool of buffers that are going to be more than big enough most of the time, so this should save a lot of allocations if the file store is encrypted.
> Use pooled buffer for flushing encrypted message blocks

- server/filestore.go
This should fix a panic with overlapping slices ending up in the message block buffer pool.
> Don't recycle buffer more than once

- main.go
- server/events.go
- server/monitor.go
We used to snapshot to avoid runtime costs, but with containers etc. probably easiest to call at runtime.
Don't think it is as expensive as it once was either.
> Remove snapshotting of cores and maxprocs.

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
- server/norace_test.go
- server/raft.go
- server/test_test.go
Under certain circumstances, a replicated consumer configured for explicit ack could have the consumer state for the replicas grow very large with ack pending that should have been cleared.
This bug could trip from an off by one bug during out of order acks, but would only manifest if the ack pending did not reach 0 which would clear and reset the ack floor properly and mask the issue.
Also in this PR is some work on the general test framework to introduce network proxy for emulating RTT and throughput into the base cluster vs just the gateway connections.
> [FIXED] Fixed an issue with consumer states growing and causing instability.

- server/jetstream_cluster.go
- server/norace_test.go
- server/raft.go
- server/stream.go
Under asymmetric network latency based clusters, if a node in an R3 was replicating a consumer and the parent stream, which is interest policy based, but was the leader of neither, but the path from the stream leader was faster then the consumer leader a replicated ack could arrive before the message itself.
In this case we used to forward a delete message request to the stream leader which would then replicate that to all stream replicas, causing more work which could lead to increased publisher times on clients connected to the slow node.
> Improved publisher performance under some instances of asymmetric network latency clusters.

- server/raft.go
> Only process out of resources condition from raft layer if err matches explicitly.

- server/jetstream.go
- server/jetstream_cluster_3_test.go
This PR modifies `DisableJetStream` (which is called when we run out of disk space, when we are peer-removed or when we reload config with JS disabled) to stop all of the RAFT groups, ensuring that we no longer have interest for those groups. 
As a result, this fixes a memory leak that can happen if JS gets disabled on a node in an active cluster.
> Shut down RAFT groups when disabling JetStream

- .goreleaser-nightly.yml
By using the package instead of a .go file the resulting build will include the versioning information starting from Go 1.18:
Before:
```sh
go version -m ./dist/nats-server_darwin_amd64_v1/nats-server
./dist/nats-server_darwin_amd64_v1/nats-server: go1.19.5
path	command-line-arguments
dep	github.com/klauspost/compress	v1.16.3	h1:XuJt9zzcnaz6a16/OU53ZjWp/v7/42WcR5t2a0PcNQY=
dep	github.com/minio/highwayhash	v1.0.2	h1:Aak5U0nElisjDCfPSG79Tgzkn2gl66NxOMspRrKnA/g=
dep	github.com/nats-io/jwt/v2	v2.4.1	h1:Y35W1dgbbz2SQUYDPCaclXcuqleVmpbRa7646Jf2EX4=
dep	github.com/nats-io/nats-server/v2	(devel)	
dep	github.com/nats-io/nkeys	v0.4.4	h1:xvBJ8d69TznjcQl9t6//Q5xXuVhyYiSos6RPtvQNTwA=
dep	github.com/nats-io/nuid	v1.0.1	h1:5iA8DT8V7q8WK2EScv2padNa/rTESc1KdnPw4TC2paw=
dep	go.uber.org/automaxprocs	v1.5.1 …
```
> Update goreleaser to include vcsinfo in nightly

- .goreleaser.yml
Currently in Go, a release that is built via `go build` will always be labeled with its version as being `(devel)` (even if building from the [git tag commit](https://github.com/golang/go/issues/50603)):
```sh
go version -m /usr/local/bin/nats-server  | grep nats-server/v2
dep	github.com/nats-io/nats-server/v2	(devel)	
```
And in order to include the release version in the binary it has to be built using `go install`:
```sh
go install github.com/nats-io/nats-server/v2@v2.9.15 | grep nats-server/v2
path	github.com/nats-io/nats-server/v2
mod	github.com/nats-io/nats-server/v2	v2.9.15	h1:MuwEJheIwpvFgqvbs20W8Ish2azcygjf4Z0liVu2I4c=
```
~~We use `goreleaser` for the release and building for many platforms, so in order to enable adding the correct version metadata, we need to enable building …
> Add vcsinfo when building with goreleaser

- server/jetstream_cluster_3_test.go
- server/raft.go
Set existing and any new raft assets to observer mode while in a lameduck state.
> [FIXED] Do not allow JetStream leaders to be placed on a lameduck server.

- server/jetstream_cluster.go
- server/norace_test.go
- server/stream.go
Better handling of multiple consumers so as to not delete messages too early.
Better cleanup handling.
> [IMPROVED] Improvements to preAcks.

- server/consumer.go
- server/jetstream_cluster.go
- server/norace_test.go
- server/stream.go
When consumers where mutually exclusive and acks came in before a message we did not properly cleanup the messages.
> Updates to preacks when multiple consumers are mutually exclusive

- server/consumer.go
- server/jetstream_test.go
needAck has reverse logic for checking single subject-single filter
scenario.
> Fix bug in needAck

- server/jetstream_cluster_2_test.go
- server/stream.go
Adds original message timestamp to republished message as "Nats-Time-Stamp" header
Resolves #
- Add original message timestamp to republished message as header "Nats-Time-Stamp"
-
-
> Add original message timestamp to republished message headers

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/monitor.go
- server/norace_test.go
- server/raft.go
- server/server.go
- server/stream.go
Also some raft and interest based consumers improvements.
Some IO guards around removal of files.
> [FIXED] Concurrent map access for preAcks.

- server/consumer.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/monitor.go
- server/norace_test.go
- server/stream.go
Also make sure we have exited monitoring routines when doing resets for both streams and consumers.
> [IMPROVED] Protect against concurrent creation of streams and consumers.

- server/accounts_test.go
- server/client.go
- server/client_test.go
- server/websocket.go
- test/cluster_test.go
This brings #3733 forward from `dev` into `main`, to go into the next release.
> Cherry-pick #3733 (Refactor outbound queues, remove dynamic sizing, add buffer reuse)

- server/stream.go
> No inline jetstream msg processing, always queue inbound

- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
This allows us to manually specify a branch to build the nightly image from when dispatching builds manually.
> Allow overriding target branch in on-demand nightly image builds

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/monitor.go
- server/raft.go
Two changes here.
1. Revert of a change regarding handling of leadership transfer entries that caused instability in some tests and a bad upgrade experience.
2. Make sure if we detect that a stream or a consumer is already running the monitoring routines that we do not stop the underlying raft group since it will be being used in the monitor routine and would stall that asset.
> [IMPROVED] Raft layer improvements

- server/jetstream_cluster.go
These entries on restart should not be re-processed. This was causing some failures on consumer tests that involved restarts.
> Only apply consumer entries if not recovering.

- server/consumer.go
- server/norace_test.go
- server/stream.go
> [IMPROVED] Make sure to never process next message requests inline.

- server/events.go
- server/events_test.go
- server/server.go
To increase system stability in large NATS systems we do not want to process inbound system messages that are destined to be processed by the server itself to be processed inline on the inbound connection.
> [IMPROVED] Do not block routes, leafnodes or gateways on received internal system msgs.

- server/stream.go
Resolves #4000
Removes the check on the republish filter needing to have an overlap with the listened subjects, as with the new stream subject transformation changes we do not assume anymore that the subjects in a stream must match the subjects being listened to.
This allows the use of republish for mirroring and/or sourcing streams
> Allow republish for mirroring/sourcing streams

- server/errors.json
- server/jetstream_cluster_1_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
> [IMPROVE] Improvements and fixes to stream source consumer creation on leadership change or on stream config source updates

- server/filestore.go
- server/filestore_test.go
This PR adds internal support for compression of message blocks in the file store. Message blocks will be compressed when they reach their maximum configured block size and we have moved onto the next block, so as to avoid slowing down on-going writes as far as possible.
Compressed blocks are preambled with a small amount of metadata describing the compression algorithm (although at this point only S2 compression is supported) and compression takes place before encryption (so as to maximise the efficiency of the compression where a stream contains redundant or repeated information in the messages).
This PR **does not** provide any way to configure compression from the stream level yet (or indeed any other level exposed to clients or operators). It also does not go out of its way to …
> File store compression

- server/client.go
Alternative fix for issue https://github.com/nats-io/nats-server/issues/4014: where we always send pings for ROUTER, GATEWAY and LEAF spoke connections.
This is my own original work that I license to the project
[ x] Link to issue, e.g. Resolves #NNN
Documentation added (if applicable)
Tests added
[ x] Branch rebased on top of current main (git pull --rebase origin main)
[ x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
[x] Build is green in Travis CI
[ x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)
Resolves #
Changes proposed in this pull request:
- in …
> Alternative fix for issue 4014, where we always send pings on ROUTER connections

- server/ipqueue.go
- server/ipqueue_test.go
- server/raft.go
> [IMPROVED] Head of line improvements

- server/accounts.go
- server/opts.go
Resolves #3782
- Add hard_delete option in the resolver config and use it to set the deleteType in NewDirAccResolver
> ADDED hard_delete option on resolver configuration

- server/client.go
- server/stream.go
This was causing regression in certain KV performance tests.
> [IMPROVED] Optimize non-inline direct gets to not use simple go routines.

- server/jetstream_api.go
> Move stepdowns of streams and consumers to not be inline.

- server/jetstream_cluster.go
- server/monitor.go
For checking the health of jetstream, do not hold the lock as we traverse the streams and consumers.
> [IMPROVED] Finer grained locking for /healthz with large number of JetStream assets.

- server/sublist.go
- server/sublist_test.go
If we have a wider subject, meaning more tokens, but our subs end with a wildcard token make sure that matches properly.
> [FIXED] Make sure on reverse match to compensate for wider target subjects.

- server/stream.go
startingSequenceForSources had a potential panic at `ssi.External.ApiPrefix`. 
This checks if `External is not nil before matching its ApiPrefix.
cc @jnmoyne 
> Fix panic in startingSequenceForSources

- server/consumer.go
- server/jetstream_test.go
If the Consumer had a name containing `%`, it could result in the reply subject failing to format with `fmt.Sprintf`, as the `%` was not properly escaped with `%%`.
Resolves #4038 
> Fix consumer reply subject escaping

- server/filestore.go
- server/filestore_test.go
Resolves https://github.com/nats-io/nats-server/issues/4041
Keeps `firstSeqNeedsUpdate` set if set previously, to ensure the FirstSeq gets updated.
> Fix FirstSeq not being updated with filestore when purging subject

- server/filestore.go
- server/jetstream_cluster.go
- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
When failing to send a snapshot to a follower, in addition to stepping down reset our state.
For a filestore when expiring messages on recovery make sure that the first message is not a deleted message.
Fix a bad unlock of wrong type which could cause a crash during shutdown.
Add in raft specific test framework.
> [FIXES/IMPROVED] Raft and filestore logic 

- server/filestore.go
Some write operations in the filestore require re-encrypting the entire block, so having large blocks can make these operations slow and hurt performance.
> Limit filestore block size to 2MB when encryption is enabled

- server/raft.go
- server/reload.go
Fixes being able to reload debug logging for running raft groups.
> Fix raft log debug reloading

- server/filestore.go
- server/memstore.go
- server/store.go
Improve performance on storing msgs when multiple subjects exists with multiple messages and we have store limits that are being hit.
This will not fix any performance degradation per se when per subject limits are being hit constantly across a vast array of keys. That will be addressed more so in 2.10.
Resolves #4043 
> [FIXED] #4043

- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/stream.go
Make sure to process consumer entries on recovery in case state was not committed.
And sync other consumers when taking over as leader but no need to process snapshots when we are in fact the leader.
Do not let the consumer redelivered count go down on re-applying state on restarts.
> [IMPROVED] Consumer updates

- server/jetstream_cluster.go
Fixes this test [TestJetStreamClusterDeleteAndRestoreAndRestart] which would flap since it would not snapshot since hash was same but had entries that would erase stream data.
> [FIXED] The meta layer should snapshot if any outstanding entries are present.

- server/route.go
> [IMPROVED] Use new server read locks.

- server/jetstream_cluster_1_test.go
- server/jetstream_test.go
- server/stream.go
When adding or updating sources/mirrors, server was checking if the stream with a given name exists to check for subject overlaps, among other things.
However, if sourced/mirrored stream was `External`, checks should not be executed, as not only stream would never be found, but also, if `External` stream had the same name as the sourcing stream, the check would be wrongly performed against itself.
cc @jnmoyne 
> Fix stream sourcing & mirroring overlap errors

- server/monitor.go
Add server name to routez info:
```js
{
"server_id": "NAXUYR7XZFPBQPJGV5HNWIXLOCLBSA2GOQEPGP47AFY62XHWPREKCXWL",
"server_name": "nats-burn-0",
"now": "2023-04-14T19:47:52.057269Z",
"num_routes": 2,
"routes": [ 
{
"rid": 51,
"remote_id": "NACPYGKLPWMYM7YZA3NCYQ5HL2EKGVKFKNGGE6ECD5LMO26JC3T3TARR",
"remote_name": "nats-burn-1",
"did_solicit": true,
"is_configured": true,
"ip": "127.0.0.1",
"port": 57889,
"start": "2023-04-14T12:47:43.475646-07:00",
"last_activity": "2023-04-14T19:47:51.983756Z",
"rtt": "178µs",
"uptime": "8s",
"idle": "0s",
"pending_size": 0,
"in_msgs": 210,
"out_msgs": 154,
"in_bytes": 31854,
"out_bytes": 15150,
"subscriptions": 134
},
{
"rid": 53,
"remote_id": "NCTOFS2M5IVGKYRGYOWP3Q5SQNPGCPMCIIJWOEH5SOIH3XQKRBKP7ITJ",
"remote_name": "nats-burn-2",
"did_solicit": true, …
```
> Add server name / remote server name to routez

- server/raft.go
If we see another leader with same term we should step down, otherwise we could spin with catchups and WAL truncates.
> [FIXED] Do not spin on multi-leader with same term.

- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
When tracking information per subject went from >1 back to only 1 we needed to make sure we cleared firstNeedsUpdate.
Thanks to @scottf for finding it.
> [FIXED] Fix for a regression in behavior.

- server/raft.go
Reset our WAL on edge conditions instead of trying to recover.
Also if we are timing out and trying to become a candidate but are doing a catchup check if we are stalled.
> [IMPROVED] Recover on boundary conditions that could cause RAFT layer to spin.

- server/const.go
> Bump version to 2.9.16-RC.9

- server/consumer.go
This also uses the AVL tree from #4070 in place of the map that currently tracks whether or not a sequence is present in the consumer redeliveries. 
> Use AVL tree for consumer redeliver map

- server/filestore.go
- server/stream.go
This PR fills the missing link between the stream config and the actual compression state.
Related: nats-io/jsm.go#445, nats-io/natscli#762
> Apply stream compression from file store config

- server/jetstream_cluster.go
A stream could have a complicated state with interior deletes.
This is a simpler way to determine if we need to consider a snapshot that involves much less time and CPU and memory.
> A simpler stream state to detect change for snapshots.

- server/avl/seqset.go
- server/avl/seqset_test.go
- server/filestore.go
> Ability to set the minimum value for a seqset if known.

- server/client.go
- server/client_test.go
- server/websocket.go
This extends the previous work in #3733 with the following:
1. Remove buffer coalescing, as this could result in a race condition during the `writev` syscall in rare circumstances
2. Add a third buffer size, to ensure that we aren't allocating more than we need to without coalescing
3. Refactor buffer handling in the WebSocket code to reduce allocations and ensure owned buffers aren't incorrectly being pooled resulting in further race conditions
Fixes nats-io/nats.ws#194.
> Outbound queue improvements

- server/consumer.go
- server/jetstream_cluster_3_test.go
Also periodically check. If all normal will be very cheap.
> Run a check for ack floor drift.

- server/websocket.go
- server/websocket_test.go
> Swap out flate from std library for faster one from compress.

- server/raft.go
Fixes this entry showing up:
```
[36571] 2023/04/22 06:53:37.278744 [DBG] RAFT [2DfzK1X6 - C-R3F-bzb7ShZ0] Stepping down from %!s(uint64=66), detected higher term: 65 vs %!d(string=leader)
```
> fix formatting of raft debug log

- server/jetstream_test.go
- server/monitor.go
- server/norace_test.go
In single server mode healthz could mistake a snapshot staging direct…ory during a restore as an account.
If the restore took a long time, stalled, or was aborted, would cause healthz to fail.
> Do not fail healthz in single server mode on failed snapshot restore.

- server/client.go
- server/client_test.go
This PR effectively reverts part of #4084 which removed the coalescing from the outbound queues as I initially thought it was the source of a race condition.
Further investigation has proven that not only was that untrue (the race actually came from the WebSocket code, all coalescing operations happen under the client lock) but removing the coalescing also worsens performance.
> Restore outbound queue coalescing

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_3_test.go
Consumer state from Jsz() would not be consistent for a leader vs follower.
ConsumerFileStore could encode an empty state or update an empty state on startup.
We needed to make sure at the lowest level that the state was read from disk and not depend on the upper layer consumer.
> [IMPROVED] Clustered consumer improvements

- server/jetstream_cluster.go
This updates the `panic` messages on applying meta entries to include the faulty op type, so that we can better work out what's going on in these cases.
> Add op type to `panic`s

- server/accounts_test.go
- server/mqtt_test.go
- server/routes_test.go
- server/server.go
- server/server_test.go
- server/websocket_test.go
- test/cluster_test.go
This updates tests and the function comment.
Resolves #4110
> The server's Start() used to block but no longer does. 

- server/consumer.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/monitor.go
- server/raft.go
- server/stream.go
Under certain scenarios we have witnessed healthz() that will never return healthy due to a stream or consumer being missing or stopped. This will now allow the healthz() call to attempt to restart those assets.
We will also periodically call this in clustered mode from the monitorCluster routine.
> [IMPROVED] Health repair

- server/accounts.go
- server/jetstream_helpers_test.go
- server/leafnode.go
- server/norace_test.go
When a fleet of leafnodes are isolated (not routed but using same cluster) we could do better at optimizing how we update the other leafnodes since if they are all in the same cluster and we know we are isolated we can skip.
We can improve further in 2.10.
> [IMPROVED] Updating of a large fleet of leafnodes.

- server/client.go
- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
- server/reload.go
A new field in `tls{}` blocks force the server to do TLS handshake before sending the INFO protocol.
```
leafnodes {
port: 7422
tls {
cert_file: ...
...
handshake_first: true
}
remotes [
{
url: tls://host:7423
tls {
...
handshake_first: true
}
}
]
}
```
Note that if `handshake_first` is set in the "accept" side, the first `tls{}` block in the example above, a server trying to create a LeafNode connection to this server would need to have `handshake_first` set to true inside the `tls{}` block of the corresponding remote.
Configuration reload of leafnodes is generally not supported, but TLS certificates can be reloaded and the support for this new field was also added.
> [ADDED] LeafNode: TLSHandshakeFirst option

- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster_3_test.go
- server/stream.go
This can happen when we reset a stream internally and the stream had a prior snapshot.
Also make sure to always release resources back to the account regardless if the store is no longer present.
> [FIXED] A stream raft node could stay running after a stop().

- server/raft.go
> Small raft improvements.

- server/gateway.go
Fixes the following race: during reload account sublist can be changed: https://github.com/nats-io/nats-server/blob/26994655963d9bdc31150c6b101d11573c4fc667/server/reload.go#L1598-L1610
so this can become a race while checking interest in the gateway code here: https://github.com/nats-io/nats-server/blob/79de3302be4572ab1ee8da4a5f8860689c0087e8/server/gateway.go#L2683
```
=== RUN   TestJetStreamSuperClusterPeerReassign
Write at 0x00c0010854f0 by goroutine 15595:
github.com/nats-io/nats-server/v2/server.(*Server).reloadAuthorization.func2()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/reload.go:1610 +0x486
sync.(*Map).Range()
/home/travis/.gimme/versions/go1.19.8.linux.amd64/src/sync/map.go:354 +0x225 …
```
> Fix race in reload and gateway sublist check

- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
- server/stream.go
If we detect a drift for any unforeseen reason correct it.
> [IMPROVED] Protect against usage drift 

- server/consumer.go
If consumer with multiple subjects encountered a sequnece of messages in a row from the same subject, it tried to load messages from other subjects in some cases.
This checks for that scenario and optimizes it by early returning.
I added a temporary instrumentation to check for how many times fetching new messages is called, and it seems that it cuts those calls according to assumptions. Though it being internal, it's really hard to show that in test.
> Optimize consumer messages sequences for multiple subjects

- server/client.go
In #1943 it was adopted to use `UTC()` in some timestamps, but an unintended side effect from this is that it strips  the monotonic time (https://github.com/golang/go/commit/e5646b23dee5eb6f896a3eef45959aa130857988), so it can be prone to clock skews when subtracting time in other areas of the code.
> Stop using UTC for time in flushClients

- locksordering.txt
- server/accounts.go
- server/client.go
- server/consumer.go
- server/leafnode.go
- server/route.go
- server/server.go
Added a leafnode lock to allow better traversal without copying of large leafnodes in a single hub account.
> [IMPROVED] Optimizations for large single hub account leafnode fleets.

- .github/workflows/cov.yaml
- .github/workflows/go-test.yaml
Bump various GitHub Actions versions to move away from those using the deprecated node.js 12 runtime, and so remove the warnings.
For the coveralls action, I switched to just `@v2`, per their example docs and as we do for most actions, instead of major.minor.patch.
For Golang, update one 1.16 to 1.19, and quote the remaining unquoted instances, even though they had `.x` in there so had to parse as strings, because we're just switching to always-quoting for consistency.
> Bump GH Actions versions (Go; node12 deprecation)

- server/client.go
- server/routes_test.go
This is a fix for PR https://github.com/nats-io/nats-server/pull/4115. If a server has an s2_auto configuration, the compression level needs to be updated based on the RTT, however, this should not happen if a particular route is actually not using compression, either because it is a connection to an older server or the other side has explicitly configure compression to be "off".
Extended a test that would have caught this issue.
> Fixed issue with route s2_auto when compression is actually off

- server/norace_test.go
This backports the changes to the outbound queues test to the `main` branch.
> Backport outbound queues test changes (#4120) to `main`

- server/jetstream_cluster.go
- server/raft.go
> Improvements on raft leader handoff.

- server/raft.go
When doing a leader transfer clear vote state on leader and when non-chosen peers receive the update.
> [IMPROVED] Leader transfer process

- server/raft.go
When doing leadership transfer stepdown as soon as we know we have sent the EntryLeaderTransfer entry.
Delaying could allow something to be sent from the old leader which would cause the new leader to bail on being a candidate even though it would have gotten all the votes.
> [IMPROVED] Leadership transfer 

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
For some older R1 streams created by previous servers we could have no cluster for the stream assignment group which would prevent scale up with newer servers.
This will inherit cluster if detected as absent from the placement tags or client cluster designation.
> [FIXED] Can't scale up some older streams

- server/norace_test.go
This makes the `TestNoRaceClientOutboundQueueMemory` test useful and stops unnecessary logging.
> Tweak outbound queue memory test to only log if growth exceeds 10%

- server/accounts.go
- server/gateway.go
- server/monitor.go
- server/mqtt.go
- server/server.go
> Use monotonic time for measuring time internally

- server/monitor.go
- server/monitor_sort_opts.go
- server/monitor_test.go
> [FIXED] Allow sorting by rtt for connz.

- server/accounts.go
- server/dirstore.go
- server/jwt_test.go
When using the account resolver and a JWT is not found, the client could often get an i/o timeout error due to not receiving a timely response before the account resolver fetch request times out.  In this PR, instead of waiting for the fetch request to timeout, a resolver without JWTs will notify as well that it could not find a matching JWT, waiting for a response from all servers ~~but with a delay to let resolver that do have the JWT to respond first~~.
Also included in this PR is some cleanup to the logs emitted by the resolver.
> resolver: improve signaling for missing account lookups

- server/accounts.go
- server/errors.go
- server/stream.go
- server/subject_transform.go
- server/subject_transform_test.go
- test/accounts_cycles_test.go
There is currently a blanket requirement that subject transforms destinations MUST use ALL of the partial wildcards defined in the source of the transform. This is because the subject transformed defined for imports must be 'reversible' and therefore the destination transform must use all of the partial wildcard tokens defined in the source of the transform.
This reversing of a transform is only used for transforms used by imports, where in any case it doesn't make sense to use any transform other than Wildcard.
This PR:
- relaxes this requirement to only apply when the transform is used by an import, adding the ability to drop a wildcard token in transforms other than as part of an import.
- Improves transform reverse to support both legacy style wildcards $X and the new transform …
> [ADDED] Ability to drop partial wildcard tokens in some subject transforms

- server/jetstream.go
> [FIXED] Protect against out of bounds access on usage updates.

- server/monitor.go
Follow up from #4154 this one has to be in UTC when served via monitoring endpoint.
> monitor: change account detail info back to utc when served

- server/filestore.go
- server/jetstream_test.go
When the first block was truncated and missing any index info we would not properly rebuild the state.
Resolves #3734
> [FIXED] Additional fix for #3734.

- server/accounts.go
- server/jetstream_api.go
Resolves # typo err
- jetstream_api.go typo err
- accounts.go typo err
> CHANGED - typo err

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
Make sure to wait properly until we believe we are caught up to enable direct gets on followers.
Resolves #4162
> [FIXED] Avoid stale KV reads on server restart for replicated KV stores.

- server/jetstream_cluster.go
> [IMPROVED] Restart consumer behavior during healthz() checks.

- server/jetstream.go
> [FIXED] Avoid deadlock with usage lock for an account during checkAndSyncUsage()

- server/jetstream_cluster.go
When we detect conditions to reset streams, make sure we properly clean up old NRG nodes etc.
> [IMPROVED] Reset logic for streams

- .github/workflows/stale-issues.yaml
This adds a workflow to mark issues and PRs stale after the configured period of time, followed by closing the issue/PR after a subsequent period of time if there was no additional activity.
The `debug-only` option is so currently, so even when merged, it will do a dry-run and not perform any actions. Once we inspect the initial logs of the effect of an initial run (impacting existing issues), we can adjust accordingly and then follow-up with making it active.
For the debug logs to be enabled, we do need to add a repository secret named `ACTIONS_STEP_DEBUG` with a value set to `true` per [this instruction](https://github.com/marketplace/actions/close-stale-issues#debugging).
> Add workflow for stale issues

- server/accounts.go
Allows (exposes) the existing cluster filtering option of account level subject mapping, thereby allowing you to define different mapping destination per cluster (e.g. to insert the cluster name as a subject token).
Example:
```
mappings {
"foo":[
{destination:"foo-east", cluster: "east", weight:100},
{destination:"foo-west", cluster: "west", weight:100},
]
}
```
> Allows cluster filtering in account subject mapping

- server/reload.go
- server/reload_test.go
- server/route.go
- server/routes_test.go
This is a rework of incorrect changes made in PR #4001. Changes did not work for changes to export permissions. Test was modified to add export changes.
This affects only the `dev` branch.
> Fixed cluster permissions configuration reload

- server/leafnode.go
- server/leafnode_test.go
The issue really was that the test was sharing remote options. The way options are used is not ideal since we reference the user provided options (but it is relied upon now in many tests and possibly users setups). The other side of the issue was that when no local account is specified in a "remote" specification, we set it to the global account, but that was done when creating the leafnode object (when soliciting), which in the case of the test could race with the second server doing the validation.
In this PR we move the setting to global account during the validation, but also fixed the tests to not share the remote options configuration slice between the two servers.
Resolves #4191
> [FIXED] LeafNode: data race during validation and create leafnode

- server/consumer.go
- server/jetstream_consumer_test.go
While adding more complex test scenarios, some issues in multiple-filters approach surfaced.
This PR adds those tests and addresses the issues.
> Improve Consumer with multiple subjects

- server/mqtt.go
- server/mqtt_test.go
By publishing retained messages on their own subject, we can apply max messages per subject limits to them. Also include the domain name in the subject to make consistent with the other MQTT streams.
> Per-subject limits for MQTT retained messages

- server/errors.go
- server/opts.go
- server/subject_transform.go
- server/subject_transform_test.go
1: Improves error reporting for weighted mappings:
As it was, any error in a weighted mapping would return a very unhelpfull error message.
e.g. `nats-server: mappingtest.cfg:38:39: interface conversion: interface {} is []interface {}, not string`
This was because the line `err := &configErr{tk, fmt.Sprintf("Error adding mapping for %q to %q : %v", subj, v.(string), err)}` would panic on the `v.(string)` since in weighted mapping that interface{} is actually a map[string]interface{} (since there's can be more than one mapping in weighted mappings).
Now returns the actual error:
e.g. `nats-server: mappingtest.cfg:40:3: Error adding mapping for "bla" : invalid mapping destination: wildcard index out of range in {{wildcard(1)}}`
2: improves subject transform checking and catches if the …
> [IMPROVED] Subject transform validation and error reporting

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/stream.go
This records the server time when info for streams and consumers are created so that tools such as the nats cli can calculate time deltas for last ack, last delivered and so forth in the context of the server clock.
This will help aleviate problems with client devices experiencing clock jitter that can show up in user interfaces as negative seconds since last ack etc
> Record the stream and consumer info timestamps

- server/consumer.go
Saw performance issue with a user a limits based stream with large number of consumers.
> Only check ack floor if we are interest policy based.

- server/accounts.go
- server/events_test.go
- server/jetstream_cluster_3_test.go
When we were optimizing for single cluster and large numbers of leafnodes we inadvertently broke a daisy chained scenario where a server was a spoke and a hub within a single hub server.
So interest on D would not propagate properly to server A as a publisher.
```
B
/    \
A       C -- D (SUB)
|
PUB
```
> [FIXED] Daisy chained leafnodes sometimes would not propagate interest

- server/jetstream_cluster.go
- server/raft.go
- server/stream.go
> [FIXED] Data races detected in internal testing

- server/jetstream.go
When a server was killed on restart before an encrypted stream was recovered the keyfile was removed and could cause the stream to not be recoverable.
We only needed to delete the key file when converting ciphers and right before we add the stream itself.
Resolves #4195
> [FIXED] Killed server on restart could render encrypted stream unrecoverable

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
This is an extension to the excellent work by @MauriceVanVeen and his original PR #4197 to fully resolve for all use cases.
Resolves #4196
> [FIXED] Make sure to process extended purge operations correctly when being replayed.

- server/filestore.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
- server/store.go
PR https://github.com/nats-io/nats-server/pull/4212 fixed the issue I reported in https://github.com/nats-io/nats-server/issues/4196.
However, I believe there might be a bug when both `sequence` and `keep` are set during recovery.
In the `PurgeEx` the following check is done (for both `filestore.go` and `memstore.go`):
```go
if sequence > 1 && keep > 0 {
return 0, ErrPurgeArgMismatch
}
```
The `TestJetStreamClusterPurgeExReplayAfterRestart` also triggers this case, meaning that during the test this error is returned but it succeeds because the purge was already performed. Is this intended behaviour?
To elaborate a bit more, I believe the following happens:
- when running the purge normally it will properly run the `keep` (since it's not combined with `sequence` yet)
- when replaying the …
> Fix PurgeEx replay with sequence & keep succeeds

- server/accounts.go
- server/client.go
- server/ipqueue.go
- server/jetstream_cluster.go
- server/leafnode.go
- server/route.go
- server/server.go
- server/stream.go
Resolves panics in the code.
- This PR fixes some of the panics in the code
> Panic fixes

- server/consumer.go
- server/jetstream_cluster_3_test.go
- server/norace_test.go
Bail early if new consumer, meaning stream sequence floor is 0.
Decide which linear space to scan.
Do no work if no pending and we just need to adjust which we do at the end.
Also realized some tests were named wrong and were not being run, or were in wrong file.
> [FIXED] Performance issues with checkAckFloor with large first stream sequence.

- server/jetstream_chaos_test.go
It doesn't really appear as though, for what these tests are trying to prove, that an excessively large number of messages is required. Instead let's drop the count a little in the hope that they run a bit faster.
> Reduce messages in chaos tests

- server/leafnode_test.go
- server/sublist.go
- test/system_services_test.go
Fix for properly distributed queue requests over multiple leafnode connections.
When a leafnode server joins two accounts in a supercluster, we want to make sure that each connection properly takes into account the weighted number of subscribers in each account.
> [FIXED] DQ weighted subscribers across separate leafnode connections.

- server/jetstream_cluster_3_test.go
- server/leafnode.go
- server/leafnode_test.go
When a server would send an asynchronous INFO to a remote server it would incorrectly contain compression information that could cause issues with one side thinking that the connection should be compressed while the other side was not.
It also caused the authentication timer to be incorrectly set which would cause a disconnect.
Signed-off-by: Ivan Kozlovic <ijkozlovic@gmail.com>
> Fixed issues with leafnode compression negotiation

- server/filestore.go
- server/memstore.go
When messages were very small and the key space was very large the performance of last message gets in the store layer (both file and memory) would degrade.
If the subject is literal we can optimize and avoid sequence scans that are needed when multiple subject states need to be considered.
Resolves #4221
> [IMPROVED] Last msg lookup (KV Get) when subject is a literal subject

- server/jetstream.go
If we know we are in stand alone mode we do not need to run the updates for JetStream account resources updates.
Resolves #4227 (Partial)
> [IMPROVED] Only enable JetStream account updates in clustered mode.

- server/events.go
- server/events_test.go
- server/gateway.go
If we know we are in stand alone mode only send out statsz updates if we know we have external interest.
Resolves: #4234
> [IMPROVED] Optimize statsz locking and sending in standalone mode.

- server/mqtt.go
- server/mqtt_test.go
This PR separates out the small amount of necessary metadata for retained messages (stream sequence, floor) from the message itself, instead accessing the messages themselves with KV-like access patterns.
This should save quite a bit of memory where there are lots of retained messages since we only now need to hold a small amount of metadata instead of the entire messages.
> Don't hold entire MQTT retained messages in memory

- server/norace_test.go
- server/stream.go
When creating replicated mirrors where the source stream had a very large starting sequence number, the server would use excessive CPU and Memory.
This is due to the mirroring functionality trying to skip messages when it detects a gap. In a replicated stream this puts excessive stress on the raft system.
This step is not needed at all if the mirror stream has no messages, we can simply jump ahead.
> [IMPROVED] High CPU and Memory usage on replicated mirrors with very high starting sequence.

- server/client.go
This fixes #4252 by ensuring that `tls_available`, `tls_required`, `host` and `port` are populated based on the WebSocket listener rather than standard listeners.
> WebSocket-specific `INFO`

- server/jetstream_cluster.go
- server/server.go
- server/stream.go
This allows the CPU and goroutine profiles to be annotated with information that allows us to break down load based on accounts, streams and consumers. We could probably add more labels elsewhere for other purposes too. It makes it easier to spot whether there are certain assets that are responsible for heavy CPU usage, i.e. snapshotting certain stream states.
> Annotate CPU and goroutine profiles

- server/jetstream.go
- server/opts.go
This option is not available in the config, and is only accessable to embeded servers where when using custom loggers can look pretty terrible
- Add ability to disable the jetstream ascii art banner on embeded servers as when using custom logging skews the ascii art.
```
INFO[2023-06-20T21:00:54-07:00] Starting JetStream                           
INFO[2023-06-20T21:00:54-07:00] _ ___ _____ ___ _____ ___ ___   _   __  __   
INFO[2023-06-20T21:00:54-07:00] _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  | 
INFO[2023-06-20T21:00:54-07:00] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| | 
INFO[2023-06-20T21:00:54-07:00] \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_| 
INFO[2023-06-20T21:00:54-07:00]                                              
INFO[2023-06-20T21:00:54-07:00] …
```
> Adding option to disable jetstream ascii art

- server/client.go
This should stop us reporting `tls_required` when we aren't reporting `tls_available`.
> Additional check for TLS required in WebSocket `INFO`

- server/filestore.go
- server/filestore_test.go
When creating a consumer on a stream with a very large number of msg blks, calculating numPending could be slow.
This aims to optimize a bit, more work to be done on streams with a very large (> 200k) number of msg blks.
> [IMPROVED] Consumer create time when stream has large number of blks.

- .goreleaser-nightly.yml
If we're on a branch other than main or dev, then when building "nightly", build it with the name of the branch instead.  Overrideable via an env var.
It's a bit ugly because of limitations of goreleaser templating, we can't haul the expression out to be defined once, but it works.
Can build a custom Docker image with:
goreleaser release --snapshot -p 2 -f .goreleaser-nightly.yml --clean
> Adjust nightly name if on a branch

- server/gateway.go
This avoids a potential data race when reloading accounts.
> Use an account protected method to check for service imports for Gateways.

- server/jetstream_cluster_3_test.go
- server/monitor.go
Could leave them in a bad state.
Resolves #4270
> [FIXED] Do not health check streams that are actively being restored.

- server/routes_test.go
These tests are to help verify that routes aren't leaking when they go down for write deadlines or auth failures.
> Add `TestRouteNoLeakOnSlowConsumer` and `TestRouteNoLeakOnAuthTimeout`

- server/stream.go
Fixes a behavior where idempotency of re-defining the same stream more than once (with the same attributes) was broken due to the DeepEqual failing due to the StreamSource struct received from the client app not having a value for the `iname` structure field (as it's internal) but the StreamSource struct return from `mset.config()` would have it set.
> [FIXED] Stream config idempotency

- server/leafnode.go
- server/leafnode_test.go
When a queue subscriber was updated multiple times over a leafnode connection we added in more shadow subscriptions which could become zombies when the connection went away.
In a case where a leafnode server had multiple queue subscribers on the same queue group, the hub server would add in multiple shadow subs. These subs would not be properly cleaned up and could lead to stale connections being associated with them.
> [FIXED] Duplicate queue subs over leafnodes with hub stream import/export with possible dataloss

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
When restoring a filestore with no key generator but it was encrypted, fail to restore.
> [FIXED] Restore of encrypted filestore with no main key could cause dataloss

- server/client.go
- server/jetstream_test.go
This should fix #4275 by allowing advisories to be copied into other accounts via service imports.
> Evaluate service imports when publishing advisories

- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_test.go
- server/memstore.go
- server/nkey.go
- server/norace_test.go
- server/websocket.go
- test/norace_test.go
As of Go 1.20, `math/rand.Read` is deprecated. In addition to that, it also isn't recommended for use in combination with anything cryptographic.
I haven't replaced all `math/rand` imports with `crypto/rand` imports because there are still some legitimate uses for the `math/rand` package in some places.
> Use `crypto/rand.Read` instead of `math/rand.Read`

- server/jetstream_leafnode_test.go
Multiple tests were using the same port numbers and it seems that the NATS Servers were not always shutting down quickly enough or the test is reusing a port that was already assigned ephemerally, resulting in `listen tcp 127.0.0.1:50554: bind: address already in use` failures.
> Remap ports in leaf node tests to hopefully reduce flakes

- server/pse/pse_zos.go
- server/sysmem/mem_zos.go
zOS is an IBM Z (mainframe) operating system. In the days of yore, it was MVS.
Resolves - the inability to build on zOS.
- This PR adds a couple of files to allow building nats-server on zOS.
> Initial support for zOS

- server/jetstream_test.go
- server/stream.go
> Add test case for concurrent expected last subject sequence

- server/server.go
- test/tls_test.go
This should fix a bug where in-process connections expect TLS over the `net.Pipe` if TLS is configured.
> Don't require TLS for in-process connection

- .travis.yml
- server/accounts_test.go
- server/client.go
- server/server.go
When service imports were reloaded on active accounts with lots of traffic the server could panic or lose data.
> [FIXED] Server reload with highly active accounts with service imports could cause panic or dataloss

- server/events.go
If we created lots of hashes, beyond server names, like for consumer or stream NRG group names etc, these maps would grow and not release memory. Performance hit is ~300ns per call, and we can use string intern trick if need be at a future date since it is GC friendly.
Resolves #4289
> [FIXED] Leaking memory on usage of getHash()

- logger/log.go
- logger/log_test.go
- server/configs/reload/reload.conf
- server/log.go
- server/log_test.go
- server/opts.go
- server/reload.go
- server/reload_test.go
- server/signal_test.go
Includes option to log in UTC with commits from following PRs:
https://github.com/nats-io/nats-server/pull/3833
https://github.com/nats-io/nats-server/pull/3920
> Include `logtime_utc` option into v2.9 series

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/stream.go
This allows specifying `first_seq` in the stream config when creating a stream. 
> Add `first_seq` to `StreamConfig`

- server/jetstream_cluster.go
- server/norace_test.go
Previously the Total in paged responses would always equal the size of the first response this would stall paged clients after the first page.
Now correctly sets the total so paging continues, improves the test to verify these aspects of the report
> Report correct consumer count in paged list response

- server/jetstream_api.go
- server/jetstream_test.go
This cherry-picks #3776 into `main` for the next patch release.
> Cherry-pick "Fix not validating single token filtered consumer"

- server/filestore.go
This is a fix for a bad msg blk detected in the field that had sequence holes.
The stream had max msgs per subject of one and only one subject but had lots of messages. The stream did not recover correctly, and upon further inspection determined that a msg blk had holes, which should not be possible.
We now detect the holes and deal with the situation appropriately. Heavily tested on the data dump from the field.
> [FIXED] Stream recovery with corrupt msg block with sequence gaps.

- server/filestore.go
- server/filestore_test.go
When a lazy simple state has an outdated first that needs to be updated, if fseq had moved past it would panic.
This was not common but with latest fix prior in can become more common, hence why it showed up.
> [FIXED] Do not panic when re-calculating first sequence for SimpleState when fseq moves ahead of old first.

- conf/parse.go
- conf/parse_test.go
This makes configuration files that are empty, or read and processed by the parser but with no detected values now return an error.
> config: make parsing configurations without usable values invalid

- server/avl/seqset.go
- server/avl/seqset_test.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/norace_test.go
- server/store.go
This would cause decode to spin and lock up the server.
This fixes the encode bug (a delete and clear node bug in avl/seqset). Also addressed receiving a bad snapshot, etc.
> [FIXED] Seqset encode bug that could cause bad stream state snapshots

- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
This prevents configurations where mirrors are mixed with `first_seq`s of greater than zero.
> Prevent configuring `first_seq` on mirrors

- server/certstore/certstore.go
- server/client.go
- server/monitor.go
- server/ocsp.go
- test/configs/certs/ocsp_peer/mini-ca/misc/misconfig_TestServer1_bundle.pem
- test/configs/certs/ocsp_peer/mini-ca/misc/trust_config1_bundle.pem
- test/configs/certs/ocsp_peer/mini-ca/misc/trust_config2_bundle.pem
- test/configs/certs/ocsp_peer/mini-ca/misc/trust_config3_bundle.pem
- test/ocsp_peer_test.go
- test/ocsp_test.go
Resolves problems of [issue #3773](https://github.com/nats-io/nats-server/issues/3773).  
With this fix, NATS Server will locally determine it's own certificate's issuer from either the configured server certificate (bundle of leaf cert plus optional intermediate CA certs) or from the configured server CA trust store, as follows: 
1. The operator may provide the server's certificate issuer in the second position of the server's certificate configuration (typically `cert_file` but may be `cert_store` on the Windows platform).  If a candidate issuer is found here it is PKI validated as the actual issuer of the server's cert else a hard error.
2. If not found in [1], NATS Server will seek to create at least one verified chain with its configured trust store (typically `ca_file` but could by …
> Fixed local issuer determination for OCSP Staple, issue #3773

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
- server/opts.go
- server/stream.go
Three issues were found and resolved.
1. Some purge replays after recovery  could execute full purge.
2. Callback was registered without lock, which  could lead to skew.
3. Cluster reset could stop stream store and recreate it, which could lead to double accounting.
> [FIXED] Accounting drifts

- server/client.go
- server/sublist.go
Do not hold onto no interest subjects from a client in the unlocked cache.
If sending lots of different subjects all with no interest performance could be affected.
Resolves #4341
> [IMPROVED] Publish performance with lots of no interest subjects

- conf/parse.go
- conf/parse_test.go
This makes configuration files that are empty, or read and processed by the parser but with no detected values now return an error.
Fixes #4343 
Backport from dev branch (https://github.com/nats-io/nats-server/pull/4347)
> config: make parsing configurations without usable values invalid (backport)

- server/reload_test.go
- server/server.go
On reload some of the imports from the system account where going missing on reload, this adds them back after a reload:
```
$SYS.REQ.SERVER.PING.CONNZ
$SYS.REQ.ACCOUNT.PING.STATZ
$SYS.REQ.ACCOUNT.PING.CONNZ
```
> Fix some system service imports going missing after reload

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/stream.go
If the failed state of clfs drifts between leaders and followers, replicas could discard and skip messages possibly incorrectly. This will force sync if we have a non-zero clfs state when a leader takes over.
> [IMPROVED] When taking over make sure to sync and reset clfs for clustered streams.

- server/consumer.go
- server/errors.json
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
- server/jetstream_errors_generated.go
Add distinction between create and update to consumer API
As in the server there is only one API for consumer management create
and update,
if clients want to provide to the users guard against overriding
existing consumer with create operation, or accidentaly creating them with update, they need to rely on calling `Info`.
That adds latency, traffic and load on the server and is still race'y,
as state on the server can change between the info and create calls.
This PR adds `Action` to CreateConsumerRequest, which is a non-breaking
change that allows client's to present it's intent without spliting
Consumer API into create and update.
This is not a prefect solution, but such split, to not be breaking and
does not require new API version.
TODO:
> Add consumer api action

- server/events.go
- server/reload_test.go
- server/server.go
Adds back the fix from #4369 and also fixes the export that was going missing in dev branch when a custom system account was being used.
> Fixes to service system imports on reload also when using custom system account

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/norace_test.go
Track deleted with single avl.SeqSet dmap for now vs old method for memory store.
For fileStore, we were trying to be too smart to save space at the expense of encoding time, so revert back to simple version that is much 100x faster.
Size of encoding may be a bit bigger then we wanted, but we want to prefer speed over size.
> [IMPROVED] Delete blocks performance

- test/leafnode_test.go
Test would fail now with the leafnode not being able to connect due to the following:
```
[4257] [INF] 127.0.0.1:63538 - lid:6 - Leafnode connection created for account: $G 
[4257] [INF] 127.0.0.1:63547 - lid:6 - Leafnode connection created 
[4257] [DBG] 127.0.0.1:63547 - lid:6 - Starting TLS leafnode server handshake
[4257] [DBG] 127.0.0.1:63538 - lid:6 - Starting TLS leafnode client handshake
[4257] [ERR] 127.0.0.1:63538 - lid:6 - TLS leafnode handshake error: x509: certificate is not valid for any names, but wanted to match localhost
[4257] [INF] 127.0.0.1:63538 - lid:6 - Leafnode connection closed: TLS Handshake Failure - Account: $G
[4257] [ERR] 127.0.0.1:63547 - lid:6 - TLS leafnode handshake error: remote error: tls: bad certificate
[4257] [INF] 127.0.0.1:63547 - lid:6 - Leafnode …
```
> test: fix TestClusterTLSMixedIPAndDNS test in +go1.20

- server/accounts_test.go
It can take slightly longer in Travis close to the deadline so bumping it for this test:
```
=== RUN   TestAccountReloadServiceImportPanic
--- PASS: TestAccountReloadServiceImportPanic (10.60s)
=== RUN   TestAccountReloadServiceImportPanic
accounts_test.go:3621: Have not received all responses, want 187876 got 182649
--- FAIL: TestAccountReloadServiceImportPanic (14.09s)
```
locally in a container I get the following so doubled the timeout:
```
=== RUN   TestAccountReloadServiceImportPanic
--- PASS: TestAccountReloadServiceImportPanic (8.35s)
=== RUN   TestAccountReloadServiceImportPanic
--- PASS: TestAccountReloadServiceImportPanic (8.58s)
=== RUN   TestAccountReloadServiceImportPanic
--- PASS: TestAccountReloadServiceImportPanic (8.62s)
=== RUN   TestAccountReloadServiceImportPanic
--- …
```
> test: bump timeout from TestAccountReloadServiceImportPanic

- server/jetstream_cluster.go
This fixes the race condition in consumer create API by adding a missing return statement, probably introduced while solving conflicts.
> Fix race in consumer create

- server/norace_test.go
Let pull consumer in test fetch messages for slightly longer instead of at the same time as the producer, to avoid failing due to missing a few messages:
```
=== RUN   TestNoRaceJetStreamServiceImportAccountSwapIssue
norace_test.go:1194: Expected to receive 14982 msgs, only got 14981
--- FAIL: TestNoRaceJetStreamServiceImportAccountSwapIssue (3.03s)
```
> test: update TestNoRaceJetStreamServiceImportAccountSwapIssue flake

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
- .github/workflows/go-test.yaml
- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
- .travis.yml
- docker/Dockerfile.nightly
- scripts/runTestsOnTravis.sh
Picks up https://github.com/nats-io/nats-server/pull/4297 into main.  Includes: 
- Using Go 1.20 for the nightly images and Travis tests
- Drop Go 1.18
- Updates to GitHub Actions
- Upgrade to golang-ci
> Add Go 1.20 to Travis and Nightly images

- server/filestore_test.go
`t.Fatalf` being called while holding a lock would sometimes leave builds hanging until test timeout.
```
=== RUN   TestFileStoreNewWriteIndexInfo/AES-GCM-None
=== RUN   TestFileStoreNewWriteIndexInfo/AES-GCM-S2
filestore_test.go:5483: require true, but got false
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
> test: fix TestFileStoreNewWriteIndexInfo hanging

- server/mqtt_test.go
Reported error changed slightly in Go 1.21
```
=== RUN   TestMQTTTLSVerifyAndMap
=== RUN   TestMQTTTLSVerifyAndMap/no_filtering,_client_does_not_provide_cert
mqtt_test.go:1033: Unexpected error: Error reading: remote error: tls: certificate required
--- FAIL: TestMQTTTLSVerifyAndMap (0.04s)
```
> test: fix TestMQTTTLSVerifyAndMap on Go 1.21

- server/signal.go
- server/signal_test.go
When multiple instances are running on the machine a PID argument suffixed with a '*' character will signal all matching PIDs.
Example: `nats-server --signal reload=*`
> Match --signal PIDs with globular-style expression.

- server/accounts_test.go
Add extra flushes to make test more precise and try to avoid timeouts
```
=== RUN   TestAccountImportCycle
accounts_test.go:3447: require no error, but got: nats: timeout
--- FAIL: TestAccountImportCycle (1.01s)
```
> test: fix TestAccountImportCycle flake

- server/jetstream_cluster.go
- server/jetstream_test.go
- server/stream.go
- server/test_test.go
This should make it possible to switch from limits-based retention to interest-based retention on an existing stream.
> Allow switching from limits-based to interest-based retention in stream update

- .travis.yml
- server/client.go
- server/client_test.go
- server/events.go
- server/gateway_test.go
- server/leafnode_test.go
- server/monitor.go
- server/routes_test.go
- server/server.go
Adds a new `slow_consumer_stats` field to varz to get more details about the types of connections that are becoming slow consumers:
```
"slow_consumer_stats": {
"clients": 0,
"routes": 0,
"gateways": 0,
"leafs": 0
}
```
> Track slow consumers per connection type

- server/filestore_test.go
This is to try to prevent test failing due to trying to access the tempdir while it is being torn down.
(go issue: https://github.com/golang/go/issues/43547)
```
=== RUN   TestFileStoreMsgBlkFailOnKernelFaultLostDataReporting/AES-GCM-S2
testing.go:1225: TempDir RemoveAll cleanup: unlinkat ./TestFileStoreMsgBlkFailOnKernelFaultLostDataReportingAES-GCM-S23605508670/001/msgs: directory not empty
--- FAIL: TestFileStoreMsgBlkFailOnKernelFaultLostDataReporting (0.02s)
```
Also increases timeout slightly of `TestFileStoreNewWriteIndexInfo` which runs close to 1ms deadline sometimes:
```
=== FAIL: server TestFileStoreNewWriteIndexInfo/None-None (4.85s)
  | filestore_test.go:5489: Unexpected elapsed time: 1.054065ms
  | --- FAIL: TestFileStoreNewWriteIndexInfo/None-None (4.85s)
```
> test: delay slightly between filestore test permutations

- server/norace_test.go
This can sometimes go just above 50ms but have never seen it slower than 90ms:
```
=== RUN   TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes
norace_test.go:4078: Took too long to snapshot: 50.838542ms
--- FAIL: TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes (7.64s)
=== RUN   TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes
norace_test.go:4078: Took too long to snapshot: 50.920709ms
--- FAIL: TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes (7.06s)
=== RUN   TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes
norace_test.go:4078: Took too long to snapshot: 62.469125ms
--- FAIL: TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes (6.25s)
=== RUN   TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes
norace_test.go:4078: Took too long to snapshot: 69.397834ms
--- FAIL: …
```
> test: fix TestNoRaceJetStreamMemstoreWithLargeInteriorDeletes flake

- server/websocket_test.go
Similar to #4380 , this TLS error message changed in Go 1.21.
> test: update TestWSTLSVerifyClientCert for go1.21

- server/client.go
- server/events.go
- server/events_test.go
- server/monitor.go
- server/monitor_test.go
- server/server.go
Resolves #1556
Adds tw new $SYS server API endpoints:
- `$SYS.REQ.SERVER.%s.KICK` (where %s is the server_id) which 'kicks' (effectiveley 'rebalance' as the client application reconnects itself right away (potentially to another server in the cluster)). The service takes a JSON payload containing either an "id" or a "name" field. "id" disconnects the client connection id, "name" disconnects _all_ of the clients connected to the server with that name.
- `$SYS.REQ.SERVER.%s.LDM` (where %s is the server_id) and takes a JSON payload containing either an "id" or a "name" field. "id" sends an LDM Info message to the client connection id, "name" sends an LDM Info message to _all_ of the clients connected to the server with that name.
This features allow administrators to manually 're-balance' …
> [ADDED] $SYS server request to 'kick' or 'LDM' a client connection

- server/stream.go
This should fix a panic found by @scottf:
```
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x10ce982]
goroutine 51 [running]:
github.com/nats-io/nats-server/v2/server.(*stream).updateWithAdvisory(0xc0000c6380, 0xc000510156?, 0x1)
C:/nats/temp/nats-server/server/stream.go:1793 +0xa82
github.com/nats-io/nats-server/v2/server.(*stream).update(...)
C:/nats/temp/nats-server/server/stream.go:1609
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamUpdateRequest(0xc000184d80, 0x4d00000000000000?, 0xc0001d4c80, 0x64d6330f?, {0xc000510140, 0x1c}, {0xc00041c150, 0x11}, {0xc0003cc240, 0x100, ...})
C:/nats/temp/nats-server/server/jetstream_api.go:1460 +0xbf2
github.com/nats-io/nats-server/v2/server.(*jetStream).apiDispatch(0xc0 …
```
> When checking replica count when updating retention, make sure stream assignment is set 

- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
Follow up to #4276 extending to Mirror the full StreamSource functionality.
> [ADDED] Full StreamSource (filters, transforms) functionality to stream mirror

- server/monitor.go
- server/monitor_test.go
- server/server.go
Remove the gate checking that the server is configured to have a profiling port enabled before returning profiling information in respose to a `$SYS.REQ.SERVER.PING.PROFILEZ` request
> [IMPROVED] $SYS.REQ.SERVER.PING.PROFILEZ always honored

- conf/parse.go
- conf/parse_test.go
- server/config_check_test.go
- server/leafnode_test.go
- server/opts.go
Allows again empty configs and improves support for detecting some types of invalid configs:
- Adds reporting the line with the bad key position that makes the config invalid.
```
nats-server: config is invalid (foo.conf:1:2)
nats-server: error parsing include file 'included.conf', config is invalid (included.conf:2:2)
```
- Fixes a few tests with trailing braces which were being handled as keys and ignored before.
> config: allow empty configs, but prevent bad configs

- server/leafnode.go
This adds a jitter delay based on the reconnect delay for when a remote reconnects.
> Add some jitter to leafnode remotes reconnect

- server/stream.go
Fixes potential out of range access during some stream source transform configuration updates and tiny clean up
Fixes stream sourcing message header parsing for multi-subject transform in sources
> Fix stream config update of source transforms

- server/server.go
We rarely benefit from block profiles and in many cases a mutex profile will tell us what we need to know. Additionally, setting the block profile rate to `1` has the special meaning of capturing every single blocking event, which can have a fairly significant negative impact on publish performance.
> Don't set block profile rate

- server/stream.go
Adds sfs to sourceInfo such that transforms with just a subject filter (and no transformation, meaning that the transform pointer in streamInfo is nil) can still be reflected in SourceInfo, which is important since the filtering is still happening, just no transformation as well.
> [IMPROVED] StreamInfo reflecting subject transforms with just a filter and no transformation for Sources

- server/events.go
- server/events_test.go
- server/jetstream_cluster_3_test.go
- server/monitor_test.go
- server/server.go
If we send an event when entering lame duck mode, other nodes will mark the server as offline immediately, therefore R1 assets will not be placed onto that node. This is not a problem with R3 or higher because an LDM server operates as a Raft observer only and therefore cannot take the leadership role from an election, but R1 assets can in theory be placed onto any node that is not marked as offline.
A final shutdown event will still be sent when the server actually shuts down so there is no change there.
> Send shutdown event on LDM

- .travis.yml
- server/jetstream.go
- server/jetstream_test.go
We violated the locking pattern, so we now make sure we do this in a separate Go routine and put checks to only run it once.
> [FIXED] Fixed deadlock when checkAndSync was being called as part of storing message

- server/consumer.go
- server/jetstream_cluster_3_test.go
Fix for a bug that would allow old leaders of pull based durables to delete a consumer from an inactivity threshold timer inadvertently.
> [FIXED] Durable pull consumers could get cleaned up incorrectly on leader change.

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
When moving streams, we could check too soon and be in a gap where the replica peer has not registered a catchup request but had made contact via the NRG layer.
This would cause us to think the replica was caught up, incorrectly, and drop our leadership, which would cancel any catchup requests.
> [FIXED] R1 stream move would sometimes lose all msgs.

- server/route.go
- server/routes_test.go
- test/route_discovery_test.go
Sometimes LastActivity can be left uninitialized while creating the cluster.
> Update LastActivity on connect for routes

- conf/lex.go
- conf/lex_test.go
- conf/parse.go
- conf/parse_test.go
Fixes a side effect from #4394 which was breaking support for JSON configs.
> Fix JSON compatibility in conf format

- server/jetstream_cluster.go
- server/jetstream_super_cluster_test.go
We should not remove a peer from a stream when we can not find a replacement unless R>1.
Resolves #4396
> [FIXED] A peer-remove of an R1 could brick the stream.

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
When a consumer reached a max delivered condition, we did not properly synchronize the state such that on a restore or leader switch the ack pending could jump and be higher than max ack pending and block the consumer.
This propagates a delivered update and we updated the store state engine to do the right thing when the condition is reached.
> [FIXED] Consumer ack pending > max ack pending on restart or leader change

- server/raft.go
Thanks to @yuzhou-nj for the catch and fix.
Resolves #4363
> [FIXED] Make sure to reset election timer on catching up

- server/memstore.go
While shutting down a server an error during purge from a memory stream would cause a deadlock sometimes, this would sometimes show up in the `TestJetStreamClusterMemLeaderRestart` while tearing down the cluster.
This was introduced in https://github.com/nats-io/nats-server/commit/4d8d01949b04e20d6ec167e195504a2dcc3a87e2 so only relates to v2.10.
> Fix shutdown deadlock in TestJetStreamClusterMemLeaderRestart

- server/raft.go
If a leader is asked for an item and we have no items left, make sure to also step-down.
> [FIXED] NRG layer could loop if leader asked for an item and we have none.

- server/filestore.go
- server/filestore_test.go
Fix for purge with keep bug with user deletes and improved search for large number of blocks.
> [FIX] PurgeEx with keep and deleted bug 

- server/monitor.go
- server/monitor_test.go
Resolves #4422 
- Added `Access-Control-Allow-Origin` header to allow CORS requests for the monitoring server
- Added a check in the tests for the header when the `Content-Type` is `application/json`
> Added CORS support for the monitoring server

- server/filestore.go
- server/filestore_test.go
When expiring complete blocks on recover make sure to update global subject index psim.
> [FIXED] Expire on recover could not update global per subject map

- server/client.go
- test/gateway_test.go
In +Go 1.20, the `x509.HostnameError` changed to be wrapped in a [tls.CertificateVerificationError](https://pkg.go.dev/crypto/tls#CertificateVerificationError) so sometimes the name would not be reset causing tests to be extra flaky.
> Fix resetting TLS name from solicited remotes

- server/client.go
- server/mqtt.go
- server/mqtt_test.go
- server/opts.go
@derekcollison @neilalexander @kozlovic 
Adds MQTT QoS2 support
> [Added] MQTT: QoS2 support

- server/mqtt.go
(Partially?) addresses https://github.com/nats-io/nats-server/pull/4349#discussion_r1306576048
@kozlovic @neilalexander I did not remove the use of `domainTk` in the session subject since it seems to have significance to it; removing it failed `TestMQTTSessionsDifferentDomains` and I did not understand the specifics of the issue enough. Please let me know your thoughts.
> [FIXED] MQTT: Removed the use of tkDomain from retained msg subjects

- server/mqtt.go
- server/mqtt_test.go
As per specification MQTT-3.3.1-8, we are now setting the RETAIN flag when delivering to new subscriptions and clear the flag in all other conditions.
> MQTT: Cleanup code regarding retain flag and add test

- server/filestore.go
- server/jetstream_test.go
We were not recalculating first correctly since we were not considering seq < mb.first.seq.
Resolves #4445
> [FIXED] Max msgs per subject config update to lower values

- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
This should resolve a couple flakes.
> Tweak `TestJetStreamClusterMetaSnapshotsMultiChange` and `TestJetStreamClusterStreamUpdateSyncBug`

- server/filestore.go
- server/filestore_test.go
Also fixed small bug that could set bad first sequence for subject tracking info.
> [IMPROVED] Allow 2.10 tombstones to be skipped and allow us to recover on downgrade

- server/ocsp_peer.go
When reloading TLS we would always be logging the attempt to plug OCSP:
```
[42801] 2023/08/30 14:52:33.766638 [INF] Reloaded: authorization users
[42801] 2023/08/30 14:52:33.766648 [INF] Reloaded: accounts
[42801] 2023/08/30 14:52:33.766652 [INF] Reloaded: tls = enabled
[42801] 2023/08/30 14:52:33.766756 [DBG] Plugging TLS OCSP peer for [Client]
[42801] 2023/08/30 14:52:33.766763 [INF] Reloaded server configuration
```
> Remove OCSP debug log on reload

- server/stream.go
2.10 adds a couple space separated fields to the sourcing message header from 2 to 4 but the current 2.9 code is too strict of checking the number of fields is exactly 2 rather than at least 2
> [FIXED] potential message duplication from sources when downgrading back from 2.10

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
Historically we kept indexing information, either by sequence or by subject, as a per msg block operation. These were the "*.idx" and "*.fss" indexing files. When streams became very large this could have an impact on recovery time. Also, for encryption the fast path for determining if the indexing was current would require loading and decrypting the complete block.
This design moves to a more traditional WAL and snapshot approach. The snapshots for the complete stream, including summary information, global per subject information maps (PSIM) and per msg block details including summary and dmap, are processed asynchronously. The snapshot includes the msg block and has for the last record hash that was considered in the snapshot. On recovery the snapshot is read and processed and any …
> Updates to the way meta indexing is handled for filestore.

- .travis.yml
Flips the order to test with ~~Go 1.20~~ Go 1.21 instead of Go 1.19
> Run tests using Go 1.21

- server/filestore.go
This should hopefully fix a panic on unlock of unlocked mutex in the file store.
> Fix lock issue in filestore

- server/leafnode.go
`TestNoRaceLeafNodeSmapUpdate` could occasionally fail with missing `LS+` commands due not capturing all the inflight SUB commands as they were being processed outside the client lock.
> Fix leaf connection missing LS+ sometimes

- server/server.go
Fixes race that would make the `TestJetStreamJWTMove` test fail sometimes:
[0]: https://github.com/nats-io/nats-server/blob/f1bf4127c5be8005bf475cce422d9f66dd427da0/server/accounts.go#L3535
[1]: https://github.com/nats-io/nats-server/blob/f1bf4127c5be8005bf475cce422d9f66dd427da0/server/server.go#L1902
```
=== FAIL: server TestJetStreamJWTMove/non-tiered/R1 (4.79s)
Write at 0x00c0014631f8 by goroutine 22900:
github.com/nats-io/nats-server/v2/server.(*Server).updateAccountClaimsWithRefresh()
/go/server/accounts.go:3535 +0x53dc
github.com/nats-io/nats-server/v2/server.(*Server).UpdateAccountClaims()
/go/server/accounts.go:3074 +0x45
github.com/nats-io/nats-server/v2/server.(*Server).updateAccountWithClaimJWT()
/go/server/server.go:1937 +0x3e5 …
```
> Fix data race when updating account

- server/monitor.go
- server/monitor_test.go
- Added a new internal function `handleResponse` that accepts the HTTP status code and sets it after setting the headers
- Added tests for the `/healthz` endpoint for the `ok`, `error` and `unavailable` statuses
- Changed the IETF API health check URL to https://datatracker.ietf.org/doc/html/draft-inadarei-api-health-check (Previous link broken)
The function [`ResponseHandler`](https://github.com/mdawar/nats-server/blob/5b18e80d424926eca48091c6eb2e2a56fdffdc5d/server/monitor.go#L2305) that handles the monitoring server responses is exported so I had to add another internal function to prevent a breaking change to the API.
I don't know if dependent code should use this function, maybe in the next major version this function should be unexported because it's only used for the monitoring …
> Fix Content-Type header in /healthz when status is not 200 OK

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
Also small bug fix for leaking fds under certain scenarios during corruption.
> [FIXED] Check for checksum violations for all records and before any sequence processing.

- server/norace_test.go
> [FIXED] Sending too fast to have replicas be caught up enough to register directs.

- server/mqtt.go
Resolves: no ticket
- rename PUBREL durable consumer from `<idhash>_pubrel` to `$MQTT_PUBREL_<idhash>` for consistency with other durable consumer names.
> Fixed: MQTT: more consistent name for PUBREL durable

- server/filestore.go
- server/filestore_test.go
> [FIXED] Unlock panic on start when filestore needs to remove msgs for enforcement.

- server/monitor.go
- server/monitor_test.go
- server/sublist_test.go
Follow up from #4437 content-type fix for v2.9.22, some fixes to the response from `/healthz` for dev:
- In #[3326](https://github.com/nats-io/nats-server/pull/4097) it was changed to return 500 status when before we used to return 503 so this changes it back.
- Also as part of #3326 we started to return `status_code` in the healthz response (e.g `{"status":"ok","status_code":200}`) so this removes it for http responses just relying on the http header.
> Fixes to /healthz response (v2.10)

- server/filestore.go
> Fix for a filestore data race on hash during snapshots

- server/consumer.go
- server/filestore_test.go
- server/stream.go
When we fail to deliver a message for a consumer, either through didNotDeliver() or LoadMsg() failure re-adjust delivered count and waitingRequest accounting.
> [IMPROVED] Consumer failing to deliver re-adjusts delivered count and any waiting request.

- server/filestore.go
> [FIXED] We should update accounting before clearing ebit

- server/monitor.go
- server/monitor_sort_opts.go
- server/monitor_test.go
Resolves #4462 
- Changed how [`byIdle`](https://github.com/nats-io/nats-server/blob/887a4ae692292c4efd95539993b7d665fea78ec5/server/monitor_sort_opts.go#L97) struct compares the idle times (was subtracting the start time from the last activity time).
- Added tests for `byIdle`.
- Changed and simplified the test [`TestConnzSortedByIdle`](https://github.com/nats-io/nats-server/blob/8a9f441c40c43e5a5786506174d810bc559748aa/server/monitor_test.go#L1185) (No need for the clients to publish and subscribe if we are manually changing the client's `last` time, and we only need to test the sorting order). Also the test was not catching the problem because the clients `start` time was the same, now every client has a different start time.
> Fix monitoring server connz idle time sorting

- server/stream.go
Resolves #4459
Allows the user to set the deduplication window duration to 0s when the stream has sources defined. Remember that if the stream in question is also listening on subjects as well as sourcing the deduplication window is the same for sourced and listened messages.
> Enables 0s deduplication window duration when the stream has sources

- server/configs/tls/tls-ed25519.conf
- server/configs/tls/tls-none.conf
- server/configs/tls/tls-rsa-1024.conf
- server/configs/tls/tls-rsa-2048.conf
- server/configs/tls/tls-rsa-4096.conf
- server/core_benchmarks_test.go
Related: https://github.com/nats-io/nats-server/pull/4399
- Avoid binding to hardcoded port, as it may conflict if already in use
- Drop TLS from Core Request/Response benchmark, was not showing much difference, not enough data going through to become a dominant cost
- Add a different core benchmark that exercises TLS by pushing through lots of data
> Refine core and TLS benchmarks

- server/monitor.go
- server/monitor_test.go
> [FIXED] Interface conversion bug for ipQueues in monitor which would cause panics.

- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
Optimized for startup restore time.
> Filestore tweaks and improvements

- server/jetstream_test.go
- server/mqtt_test.go
- server/norace_test.go
- server/routes_test.go
- server/test_test.go
This uses `TempDir` in more tests. Some were trying to manage the directory manually, others were just not managing a directory at all. There may be more that need doing.
> Use `TempDir` in more tests

- server/mqtt.go
Removed `qos2` reference from the MQTT outgoing stream name and subjects.
Rationale: As I was reviewing the documentation and thinking how to move forward with MQTT, I am inclined to use the `$MQTT_out` stream and session-specific consumers (as opposed to subscription-specific) for all QOS-related packet delivery and PI persistence. I think I will be able to repurpose it "as is", so proposing the generic name change.
Since these (stream, consumer, subscriptions) are newly introduced in https://github.com/nats-io/nats-server/pull/4349 and have not yet been released, this is a safe change.
> [FIXED] MQTT: more generic names for outgoing stream, etc.

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
- .github/workflows/go-test.yaml
- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
- .travis.yml
- docker/Dockerfile.nightly
- scripts/runTestsOnTravis.sh
- server/client.go
- test/gateway_test.go
Includes fix for test `TestGatewayTLSMixedIPAndDNS ` that was breaking in Go 1.20.
> v2.9.x: Change CI and nightlies to use Go 1.20

- server/jetstream_cluster_3_test.go
This test flakes quite often on the final consumer info check because of one consumer reporting `PushBound` and the other not. By clearing both, this should clear up the disagreement.
> De-flake `TestJetStreamClusterConsumerMaxDeliveryNumAckPendingBug`

- .github/workflows/cov.yaml
- .github/workflows/go-test.yaml
- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
- .travis.yml
- docker/Dockerfile.nightly
- go.mod
- server/client.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/nkey_test.go
- Use Go 1.21 in nightlies
- Both rand.Seed and rand.Read are both deprecated, remove its use to fix staticcheck errors
```go
server/client.go:95:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative 
has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. 
Programs that call Seed with a known value to get a specific sequence of results should use 
New(NewSource(seed)) to obtain a local random generator. (staticcheck)
server/jetstream_test.go:20399:2: SA1019: rand.Read has been deprecated since Go 1.20 
because it shouldn't be used: For almost all use cases, crypto/rand.Read is more appropriate. (staticcheck)
```
> v2.10: Use Go 1.21 in nightlies, update rand usage

- server/filestore.go
The `streamSnapshot` function was not holding the filestore lock while resetting and using the hasher. This created a data race and also resulted in flakes in `TestFileStoreSnapshot`.
> Fix race condition in hashing stream snapshots

- server/stream.go
This reverts commit db96238ad9b18c9930e63c404d1ae288f8855374 which was causing `TestNoRaceJetStreamSuperClusterSources` to fail sometimes with duplicate messages around shutdown.
> Revert "Enables 0s deduplication window duration when the stream has sources"

- server/norace_test.go
This flakes sometimes as stalled, and it seems that a similar value for `StallWait` starts to surface errors both on `main` and `dev`. Not sure why it's happening in this test specifically, but it does not seem to be an issue beyond timing. Performance might be worth looking up as a follow-up.
> Fix TestNoRaceJetStreamInterestStreamCheckInterestRaceBug

- server/auth.go
`Resolves #4479 `
In AuthCallout server-config system, a spurious error message would be generated on server reload in the edge case that the AuthCallout user is an NKEY and both User and NKEY account members are defined in the config.
> Don't log error in legitimate nkey auth callout config case (4479).

- server/norace_test.go
This is the same fix as in https://github.com/nats-io/nats-server/pull/4500
This means it adds `StallWait` to `PublishAsync`, as that's seems to be the only
reason why this test fails.
> Fix TestNoRaceJetStreamSparseConsumers

- server/avl/norace_test.go
In CI this is typically < 700uS, but quite often > 500uS.
> Allow more time in `TestNoRaceSeqSetEncodeLarge`

- server/jetstream_cluster.go
- server/stream.go
> [FIXED] Fix for datarace on a stream's clfs.

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/monitor.go
We do not expect this condition at all but did see it in the wild, so this will detect and cleanup. Will run on same timer (2m) as general health checks run from `monitorCluster()`
> Add in utility to detect and delete any NRG orphans.

- server/norace_test.go
Fix for TestNoRaceJetStreamStreamInfoSubjectDetailsLimits.
> [FIXED] Need a flush to make sure 2nd INFO processed

- server/stream.go
> [FIXED] Data race accessing mirror tr

- server/jetstream_cluster_2_test.go
> [FIXED] Allow time for the 3rd replica to be current - TestJetStreamClusterStaleReadsOnRestart

- server/jetstream_super_cluster_test.go
The default timeout for JetStream API calls is 10s, so in the case where we determine that we are the leader, but the stream info endpoint has not registered with the server we are connected to, the stream info call could fail and we would exhaust the whole checkFor since we would stay in one call for 10s.
Fix is to override and make multiple attempts possible for the checkFor loops.
> [FIXED] Move test fix - TestJetStreamSuperClusterMovingStreamsAndConsumers/R3

- server/filestore.go
- server/filestore_test.go
When num blocks > 32 and we used new binary search in NumPending() we could return -1, nil. If sequence is inclusive this should always return valid index and mb.
The reason we could return -1 would be that we were not accounting for gaps as mb.first.seq can move ahead as first is removed. The panic could orphan held locks for filestore, consumer and possibly stream which would lock up a system, leading to memory growth and unstable behaviors.
> [FIXED] Fix for panic from a bug in selecting a filestore block in new fs code.

- server/mqtt_test.go
TestMQTTQoS2RetriesPublish to 100ms, and in TestMQTTQoS2RetriesPubRel to 50ms.
A lesser value caused another PUBLISH to be fired while the test was still processing the final QoS2 flow. Reduced the number of retries we wait for to make the test a little quicker.
> [FIXED] Increased AckWait in TestMQTTQoS2RetriesPublish, TestMQTTQoS2RetriesPubRel

- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
main is now the contents of the dev branch, the old nightly-main points to the last release for now.
> Update docker nightly builds

- go.mod
- go.sum
This updates `nats.go` to v1.29.0.
> Update nats.go to v1.29.0

- server/filestore.go
- server/filestore_test.go
This unprotected access allowed the cache to most likely be flushed and after a subsequent writeMsgRecord would have the offset > slot value which can't happen if lock is held due to us loading cache properly at beginning of the function.
Resolves #4529
> [FIXED] Fix for a call into mb.recalculateFirstForSubj() that did not hold lock.

- server/filestore.go
- server/filestore_test.go
Cherry picked from main.
Fix for a call into mb.recalculateFirstForSubj() from fs.recalculateFirstForSubj() that did not lock the mb properly.
Resolves #4529
> [FIXED]  Fix for a call into mb.recalculateFirstForSubj() that did not hold lock.

- server/jetstream_cluster_1_test.go
- server/jetstream_helpers_test.go
This adds a new `waitForAccount` test helper that ensures that an account exists across the cluster, and updates `TestJetStreamClusterAccountPurge` to use it after submitting new JWTs. This should prevent `require no error, but got: nats: JetStream not enabled for account` errors.
> De-flake `TestJetStreamClusterAccountPurge`

- server/stream.go
Repeated calls to `scheduleSetSourceConsumerRetry` could end up creating multiple timers for the same source, which would eventually schedule even more timers, which would result in runaway CPU usage. This PR instead bounds to one timer per source per stream.
> Fix leaking timers in stream sources

- server/jetstream_test.go
Can sometimes fail the first time checking for the ack floor but fine after checking again.
> flake: Fix TestJetStreamConsumerAckFloorFill

- server/consumer.go
> [IMPROVED] Consumer cleanup monitoring and FIX for datarace

- server/consumer.go
- server/filestore_test.go
> [FIXED] Possible panic in consumer, needed to recheck if consumer was closed

- server/auth_callout_test.go
- server/monitor.go
- server/websocket.go
Make sure the client handshake flag is set when TLS handshake is made as part of WebSocket connection/upgrade (notionally HTTPS) rather than as part of the NATS protocol TLS initiation chain.  AuthCallout tests the flag when building the data for the AuthCallout service request.
Added AuthCallout unit test for NATS WS client auth that requires the TLS data.
> AuthCallout request should include TLS data when client is NATS WS client

- server/jetstream_cluster.go
- server/raft.go
- server/raft_helpers_test.go
This adds some more debugging information to the Raft goroutines in pprof and improves the logging when a consumer was already running.
Example:
```
1 @ 0x1025b1838 0x1025c2ac8 0x102a47d1c 0x102a47244 0x102a858e0 0x1025e5ad4
#	0x102a47d1b	github.com/nats-io/nats-server/v2/server.(*raft).runAsFollower+0xbb		server/raft.go:1795
#	0x102a47243	github.com/nats-io/nats-server/v2/server.(*raft).run+0x2c3			server/raft.go:1715
#	0x102a858df	github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1+0x17f	server/server.go:3609
1 @ 0x1025b1838 0x1025c2ac8 0x102a47d1c 0x102a47244 0x102a858e0 0x1025e5ad4
#	0x102a47d1b	github.com/nats-io/nats-server/v2/server.(*raft).runAsFollower+0xbb		server/raft.go:1795
#	0x102a47243	github.com/nats-io/nats-server/v2/server.(*raft).run+0x2c3 …
```
> Add Raft goroutine labels, tweak logging

- server/memstore.go
Fix for a data race that was found in memory storage while working on a fix for https://github.com/nats-io/nats-server/pull/4551
```
Read at 0x00c0000a6e38 by goroutine 412:
github.com/nats-io/nats-server/v2/server.(*memStore).LoadNextMsg()
/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/memstore.go:954 +0x644
github.com/nats-io/nats-server/v2/server.(*consumer).getNextMsg()
/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/consumer.go:3413 +0xb22
github.com/nats-io/nats-server/v2/server.(*consumer).loopAndGatherMsgs()
/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/consumer.go:3824 +0x484
github.com/nats-io/nats-server/v2/server.(*consumer).setLeader.func3() …
```
> Fix for data race in memstore.LoadNextMsg

- server/consumer.go
- server/jetstream_test.go
Should fix following data race:
```
Write at 0x00c0006c3cf8 by goroutine 65593:
github.com/nats-io/nats-server/v2/server.(*stream).updateWithAdvisory()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/stream.go:1907 +0x19c6
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterUpdateStream()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3448 +0xde5
github.com/nats-io/nats-server/v2/server.(*jetStream).processUpdateStreamAssignment()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3344 +0x904
github.com/nats-io/nats-server/v2/server.(*jetStream).applyMetaEntries()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:1949 +0xcd6 …
```
> Fix for data race when changing retention policy

- server/filestore.go
- server/filestore_test.go
We fixed a few bugs in tombstone handling, and formalized support for holes in the underlying buffers. Due to customer data from the field we also now use holes during compaction.
> Various fixes and improvements to tombstone and buffer gaps.

- logger/log.go
- server/log.go
- server/opts.go
- test/log_test.go
NATS Server 2.9 has `logfile_size_limit` option which allows the operator to set an optional byte limit on the NATS Server log file which when met causes a "rotation" such that the current log file is renamed (original file name appended with a time stamp to nanosecond accuracy) and a new log file is instantiated.
This PR is a new `logfile_max_num` companion option (alias `log_max_num`) which allows the operator to designate that the server should prune the **total number of log files** -- the currently active log file plus backups -- to the maximum setting. 
A max value of `0` (the implicit default) or a negative number has meaning of unlimited log files (no maximum) as this is an opt-in feature.
A max value of `1` is effectively a truncate-only logging pattern as any backup made at …
> Add logfile_max_num feature

- server/stream.go
`addStreamWithAssignment` did not hold the JS lock at the point of calling `setStreamAssignment`, which could result in a data race accessing the Raft group peers from the stream assignment on line 774.
> Fix data race in `setStreamAssignment` by ensuring JS lock held

- server/jetstream_test.go
- server/stream.go
This is a safer (less lines of code touched) alternative to #4557 for now, which simply ignores the `subject_transform_dest` field in the API and the stream assignments. We'll still look to merge the other PR to clean up but will do so post-release when we have more time to test it.
> Ignore `subject_transform_dest` in stream sourcing

- server/reload.go
Fixes #4560. The client lock needs to be held before accessing the `c.opts`.
> Fix race condition in `clientHasMovedToDifferentAccount`

- server/leafnode.go
- server/leafnode_test.go
If a leafnode remote configuration does not have a tls{} block but connect to a hub that requires TLS, the handshake between the two servers will fail. A simple workaround is to add in the remote configuration an empty tls{} block.
This issue was introduced in v2.10.0 due to some refactoring in order to support compression.
> [FIXED] LeafNode: TLS Handshake when remote does not have a tls{} block

- server/jetstream_test.go
- server/stream.go
This fixes an issue where specifying a single subject filter, i.e. in `SubjectFilters` or `SubjectTransforms`, instead of using `SubjectFilter` would result in the old consumer create subject being incorrectly used.
> Use new consumer create subject when single subject filter specified in `SubjectFilters`

- server/stream.go
Removes the single subject transform destination field any subject transformation in StreamSources must now be done using the SubjectTransforms array instead.
> Remove `subject_transform_dest`

- server/consumer.go
- server/jetstream_test.go
If Stream has consumer limits set, creating consumer with defaults will fail in most cases.
Test didn't catch this, as by default, old JS client sets ack policy to `none`. If the policy is different, it will fail to create consumer with defaults. We agreed that default Ack Policy should be `explicit`
> Fix consumer limits

- server/filestore.go
- server/jetstream_cluster.go
> [IMPROVED] Make install snapshot errors rate limited for when catching up

- server/client.go
- server/leafnode_test.go
Mimic same behavior for normal subs.
Note that when a queue subscription is behind both a spoke leafnode connection and a service import the message will be delivered over the leafnode since service imports are binary signals that are just on. Need a more thorough investigation for a proper fix. For now its best to not have the service import on the spoke leafnode such that the raw queue sub's information if relayed across the leafnode.
Resolves #4367
> [FIXED] Make sure to not forward a message across a route for routed dq subs

- server/consumer.go
- server/jetstream_cluster_3_test.go
- server/raft.go
- server/server.go
> In lameduck mode shutdown jetstream at start, do not leave running

- server/jetstream_cluster.go
> [IMPROVED] Make sure to issue warning on reset for bad state

- server/accounts.go
- server/auth.go
- server/client.go
- server/events.go
- server/jetstream_cluster.go
- server/mqtt.go
- server/route.go
- server/server.go
- server/server_test.go
- server/websocket.go
> [IMPROVED] Move some contended locks to atomic.Bools

- server/opts.go
- server/reload.go
- server/server.go
The new `prof_block_rate` configuration option allows the block profiler to be enabled on demand after it was previously disabled in #4402. The option is also reloadable so that it can be changed after startup.
> Add `prof_block_rate` option for enabling/configuring the block profile

- server/accounts.go
> [IMPROVED] The func subjectIsSubsetMatch() is heavy so do without the account lock.

- server/stream.go
Two go routines could possibly execute the stream assignment at the same time. A WaitGroup was used to prevent that, but an issue caused the data race and possible concurrent execution.
> [FIXED] JetStream: stream assignment data race

- locksordering.txt
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
- server/server.go
There was a lock inversion but low risk since it happened during server initialization. Still fixed it and added the ordering in locksordering.txt file.
Also fixed multiple lock inversions that were caused by tests.
Signed-off-by: Ivan Kozlovic <ijkozlovic@gmail.com>
> [FIXED] Account resolver lock inversion

- server/norace_test.go
There are changes in recent versions of nats.go that seemingly increase the size of the stream info and cause this test to fail consistently with `norace_test.go:4259: require no error, but got: nats: maximum payload exceeded`. Fix the test to use larger limits and payloads so we are not sensitive to this when nats.go is upgraded.
> Fix `TestNoRaceJetStreamStreamInfoSubjectDetailsLimits` for changes in nats.go

- server/accounts.go
- server/client.go
- server/gateway.go
- server/jetstream_cluster.go
- server/leafnode.go
- server/mqtt.go
- server/route.go
- server/routes_test.go
- server/server.go
- server/server_test.go
- server/websocket.go
We added  some small performance tweak to the func checkForReverseEntries. In addition, we move the shutdown bool for the server to an atomic so we could efficiently check it when doing unsubs. If the server is going away there is really no need since the other side will do its own thing when the connection goes away. And finally we do not have to range over the account rrMap if the subscription going away is a reserved reply.
> [IMPROVED] ServiceImport Reply Optimizations

- server/sublist.go
We may be creating unnecessary lock contention on the sublist when the cache is disabled by taking the write lock anyway.
> Don't take sublist write lock in `match` if sublist cache disabled

- server/jetstream_benchmark_test.go
Resolves #
Miscellaneous fixes and improvements to server JetStream benchmarks.
Reviewers: notice the PR is broken down in 5 commit, each one is trivial to review individually, but they can be definitely squashed before merging for easier cherry-picking.
> Miscellaneous JetStream benchmark improvements

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/stream.go
> [IMPROVED] Add in warnings for filestore recover state if happy path fails.

- server/jetstream_api.go
Here we know that if we can't find the stream but have the stream assignment, this is a distinct possibility. So we wait, since not processed inline, to see if it appears.
Fixes TestJetStreamClusterParallelStreamCreation as well that could flap.
> [IMPROVED] Concurrent stream creation of the same stream could return not found

- server/filestore.go
Under certain circumstances we could delay recovery if the state file pointed to an absent msg block.
Found additional places to mark dirty and optionally kick the flusher.
> [IMPROVED] Additional markers for dirty state

- server/jetstream_cluster_3_test.go
- server/route.go
- server/routes_test.go
The issue is with a server that has a route for a given account but connects to a server that does not support it. The creation of the route for this account will fail - as expected - and the server will stop trying to create the route for this account. But it needs to retry to create this route if it were to reconnect to that same URL in case the server (or its config) is updated to support a route for this account.
There was also an issue even with 2.10.0 servers in some gossip situations. Namely, if server B is soliciting connections to A (but not vice-versa) and A would solicit connections to C (but not vice-versa). In this case, connections for pinned-accounts would not be created.
> [FIXED] Routes: Pinned Accounts connect/reconnect in some cases

- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
Fixes a race condition in some leader failover scenarios leading to messages being potentially sourced more than once.
In some failure scenarios where the current leader of a stream sourcing from other stream(s) gets shutdown while publications are happening on the stream(s) being sourced leads to `setLeader(true)` being called on the new leader for the sourcing stream before all the messages having been sourced by the previous leader are completely processed such that when the new leader does it's reverse scan from the last message in it's view of the stream in order to know what sequence number to start the consumer for the stream being sourced from, such that the last message(s) sourced by the previous leader get sourced again, leading to some messages being sourced more than once.
The …
> [FIXED] Race condition in some leader failover scenarios leading to messages being potentially sourced more than once.

- util/nats-server-hardened.service
- util/nats-server.service
- tell systemd to use SIGUSR2 for shutdown, to trigger Lame Duck Mode in nats-server
> systemd: use SIGUSR2 for shutdown, for LDM

- server/mqtt_test.go
A test-only fix.
I can not reproduce the flapping behavior, but did see a race during debugging suggesting that the CONNACK is delivered to the test before `mqttProcessConnect` finishes and releases the record.
> [FIXED] Flapping TestMQTTLockedSession

- server/opts.go
- server/opts_test.go
- server/routes_test.go
- server/server.go
- server/server_test.go
Only setup auto no-auth for $G account iff no authorization block was defined.
Resolves #4535
> [FIXED] Do not bypass authorization blocks when turning on $SYS account access

- server/filestore.go
> [IMPROVED] Add in additional warning when subject skew detected

- server/consumer.go
- server/server.go
- server/stream.go
> Add more pprof labels to consumers, sources, mirrors

- server/consumer.go
- server/events.go
- server/filestore.go
- server/gateway.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/monitor.go
- server/raft.go
- server/reload.go
- server/server.go
Several strategies are used which are listed below.
1. Checking a RaftNode to see if it is the leader now uses atomics.
2. Checking if we are the JetStream meta leader from the server now uses an atomic.
3. Accessing the JetStream context no longer requires a server lock, uses atomic.Pointer.
4. Filestore syncBlocks would hold msgBlock locks during sync, now does not.
> [IMPROVED] Reduce contention for high connections in a JetStream enabled account with high API usage.

- server/jetstream_api.go
> [IMPROVED] Optimize locking for consumer info API

- server/websocket.go
Holding onto the compressor and not recycling the internal byte slice could cause havoc with GC.
This needs to be improved but this at least should allow the GC to cleanup more effectively.
> [IMPROVED] Memory growth on compressed websocket connections.

- server/jetstream_cluster.go
- server/raft.go
> [IMPROVED] Bumped inflight updates to 16 and move one lock to rlock.

- server/client.go
- server/websocket.go
This PR primarily does two things:
1. ~~Updates the buffer pool to allow reclaiming buffers that have been grown beyond their original capacity by slicing them up into capacities we can make use of~~ (reverted for now);
2. Updates the WebSocket code to remove extra copies, instead drawing straight from the compression buffer, which is reset on each call.
With `nats bench ... --pub=1 --sub=3 --msgs=100000 --size=1024` over non-TLS WebSockets, we have gone from:
* `174,688 msgs/sec ~ 170.59 MB/sec` up to `834,240 msgs/sec ~ 814.69 MB/sec`
* 40GB of `wsCollapsePtoNB` allocations down to 10MB
* 13GB of `flate.NewWriter` allocations down to 3.63MB
> Reduce allocations in WebSockets

- server/consumer.go
- server/jetstream_cluster.go
This avoids following events happening after calling lame duck shutdown: 
```
[20] 2023/10/04 18:49:58.456838 [INF] JetStream Shutdown
...
[20] 2023/10/04 18:50:02.252947 [WRN] Consumer assignment for 'js > testStream:30 > P3xF2q4d00pYr4ACgNBf9F' not cleaned up, retrying
```
```
[21] 2023/10/01 04:42:23.552141 [INF] Initiating JetStream Shutdown...
[21] 2023/10/01 04:42:23.557252 [WRN] Consumer create failed, could not locate stream 'js > test:0 > A-0-1'
[21] 2023/10/01 04:42:23.557273 [WRN] Consumer create failed, could not locate stream 'js > test:0 > A-0-2'
[21] 2023/10/01 04:42:23.557278 [WRN] Consumer create failed, could not locate stream 'js > test:0 > A-0-3'
```
> Skip processing consumer assignments after JS has shutdown

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
Under heavy load with max msgs per subject of 1 the dmap, when considered empty and resetting the initial min, could cause lookup misses that would lead to excess messages in a stream and longer restore issues.
> [FIXED] Setting initial min on dmap caused subtle bugs with dmap. 

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This simplifies the PR template, which is a bit cumbersome, and instead replaces it with a simpler notice that includes a template sign-off and a new `CONTRIBUTING.md` document.
> Add `CONTRIBUTING.md`, simplify PR template

- server/jetstream_benchmark_test.go
Backporting of JetStream benchmarks that landed in `main` (post 2.10.x) and `dev` branches back to 2.9.
These improvements are to the benchmark code and not specific to 2.10. 
Therefore it seems appropriate to back port them, so that benchmarks more accurately compare 2.9 to 2.10 and beyond.
Notice that I cherry-picked the original commits to preserve attribution (and make review easier). However because the back porting can be considered an 'atomic' change, and these have already been reviewed I could also squash into a single commit.
Signed-off-by: Marco Primi <marco@synadia.com>
> Backport JetStream benchmarks improvements to 2.9.x

- server/mqtt.go
This really was a cut/paste/typo error, the `else` should not have been there. Came up in my testing.
The effect was that when there was a pending `PUBREL` in JetStream, and a matching client connects - we would sometimes attempt to deliver the PUBREL immediately once connected. `cpending` was already initialized, but the pubrel map was not (yet).
> Fixed a crash in MQTT outgoing PUBREL

- server/client.go
- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
- server/leafnode_test.go
- server/opts.go
- server/opts_test.go
- server/routes_test.go
- server/server.go
- server/server_test.go
Backports the following PRs from v2.10:
- #4510 
- #4556 
- #4578 
- #4605 
Signed-off-by: Your Name <wally@nats.io>
> Backports from v2.10 for v2.9.23 release

- server/filestore.go
- server/filestore_test.go
This will also reclaim more space for streams with lots of interior deletes.
> [FIXED] Compaction with compression and added out of band compaction

- .travis.yml
Also change "Compile with older Go release" to "1.19".
> [2.9.x] Bump Travis Go version to 1.20.10

- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
> Backport #4592 to 2.9

- server/consumer.go
- server/jetstream_consumer_test.go
- server/stream.go
This is a possible fix for #4653.
Changes made:
1. Added tests for creating and updating consumers on a work queue stream with overlapping subjects.
2. Check for overlapping subjects before [updating](https://github.com/nats-io/nats-server/blob/a25af02c7348d1e39cce66a5c275e1740fb0ca81/server/consumer.go#L770) the consumer config.
3. Changed [`func (*stream).partitionUnique(partitions []string) bool`](https://github.com/nats-io/nats-server/blob/a25af02c7348d1e39cce66a5c275e1740fb0ca81/server/stream.go#L5269) to accept the consumer name being checked so we can skip it while checking for overlapping subjects (Required for [`FilterSubjects`](https://github.com/nats-io/nats-server/blob/a25af02c7348d1e39cce66a5c275e1740fb0ca81/server/consumer.go#L75) updates), wasn't needed before because the …
> Fix updating a non unique consumer on workqueue stream not returning an error

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
Fixed a bug that was not correctly selecting next first because it was not properly skipping new dbit entries.
This could result in lookups failing, e.g. after a change in max msgs per subject to a lower value.
Also fixed a bug that would not properly update our psim during compact when throwing away the whole block and a subject had more than one message.
Resolves: #4643
> [FIXED] Stream / KV lookups fail after decreasing history size.

- server/filestore.go
On streams that were constantly removing items, like KVs, this could become over active when not needed. Simply mark the store as dirty for next check.
> [FIXED] Only mark fs as dirty vs full write on mb compaction.

- server/core_benchmarks_test.go
Benchmarks for NATS core fan-in and fan-out pattern workloads. 
Signed-off-by: Reuben Ninan <reuben@nats.io>
> Add fan-in/out benchmarks

- go.mod
- go.sum
- server/client.go
- server/client_test.go
- server/config_check_test.go
- server/const.go
- server/monitor.go
- server/opts.go
- server/reload.go
- server/server.go
- test/tls_test.go
A new option instructs the server to perform the TLS handshake first, that is prior to sending the INFO protocol to the client.
Only clients that implement equivalent option would be able to connect if the server runs with this option enabled.
The configuration would look something like this:
```
...
tls {
cert_file: ...
key_file: ...
handshake_first: true
}
```
The same option can be set to "auto" or a Go time duration to fallback to the old behavior. This is intended for deployments where it is known that not all clients have been upgraded to a client library providing the TLS handshake first option.
After the delay has elapsed without receiving the TLS handshake from the client, the server reverts to sending the INFO protocol so that older clients can connect. Clients that do connect …
> [ADDED] TLS: Handshake First for client connections

- server/events.go
- server/jetstream.go
- server/reload_test.go
If a configuration reload is issued as the server is being shutdown, we could get 2 different panics. One due to JetStream if an account is JetStream enabled, and one due to the send to a go channel that has been closed.
```
panic: send on closed channel [recovered]
panic: send on closed channel
goroutine 440 [running]:
testing.tRunner.func1.2({0x1038d58e0, 0x1039e1270})
/usr/local/go/src/testing/testing.go:1545 +0x274
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1548 +0x448
panic({0x1038d58e0?, 0x1039e1270?})
/usr/local/go/src/runtime/panic.go:920 +0x26c
github.com/nats-io/nats-server/v2/server.(*Server).reloadAuthorization(0xc00024fb00)
/Users/ik/dev/go/src/github.com/nats-io/nats-server/server/reload.go:1998 +0x788 …
```
> [FIXED] Configuration Reload: possible panic if done during Shutdown

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
I often encounter sisutation where one of the Raft streams are growing out of control or streams that just wont recover correctly, being able to walk backward from these streams back to their managed asset will help a lot with debugging activities
> Record details about the asset a particular raft stream belongs to

- README.md
The general NATS.io contributing doc is linked to in the new CONTRIBUTING.md doc.
> Update contributing guide link in README

- util/nats-server-hardened.service
- util/nats-server.service
Per systemd.special(7) and
<https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/> the target we want for ordering starting up the nats server is `network-online`, not `network`.
We want to be able to listen for incoming connections, and possibly connect outwards for setting up routes or connecting to external account resolvers.
Without this change, nats server start-up is subject to system-dependent race-conditions for working networking.
> systemd service files: use correct special target

- server/accounts_test.go
- server/client.go
> [FIXED] Avoid adding n shadow subs if the origin sub is a service import.

- server/raft.go
- server/raft_test.go
This PR does the following:
1. Replaces `state` with an atomic, which can be accessed lock-free instead of needing to take the group mutex
2. Ensures that `runAsFollower`, `runAsLeader`, `runAsCandidate` can only continue running as long as the `state` is correct (they will stop looping and hand back to `run` if not)
3. Removes the `isLeader` atomic, as it is now unnecessary with the `state` atomic
4. Adds a unit test to prove that we can now recover from the situation of all nodes being forced into a leaderless follower state, which now passes with the above changes
> Raft state machine tweaks

- server/client.go
- server/norace_test.go
- server/parser_test.go
- server/route.go
- server/routes_test.go
Small optimization that bypass lookup of account for a pinned account's route since the account is known for this route. The lookup would occur for every inbound message whose exact destination was not found in the cache.
Also, since configuration reload no long swaps account's sublist, we can do without the account's locking to get the sublist pointer.
> [IMPROVED] Routing: reduce account lookup for pinned accounts

- server/filestore.go
- server/filestore_test.go
Avoid additional allocations when doing a writeFullState for large state.
Track the total subject length of all subjects in the PSIM structure.
This is to optimize the writeFullState when the state is large due to a large PSIM with large subjects.
> [IMPROVED] WriteFullState Allocations

- server/signal_windows.go
We weren't monitoring `quitCh` on Windows so we could leak goroutines if it wasn't a signal that caused us to shut down.
> Ensure Windows signal handler is stopped when shutting down via other means

- server/filestore.go
- server/filestore_test.go
Before we could encounter a message in the new message block that was deleted and that would cause a full rebuild, which this approach avoids. This could happen on very active KeyValue stores.
> [IMPROVED] Updated how we recover mid-update blocks on recoverFullState.

- server/route.go
- server/routes_test.go
When a server accepts a route, that route would not be marked as solicited or configured while it should if it was present in the configuration.
Prior to pooling, if server A pointed to server B and vice-versa, one of the server will have the route as solicited and the server that accepted the route would have upgraded it as solicited. With pooling code, this was not always happening.
Maybe related to #4681 
> [IMPROVED] Routing: upgrade non solicited routes if present in config

- server/mqtt.go
- server/mqtt_test.go
It was required because it was required by JetStream, but JetStream now auto-generates a default name.
> [CHANGED] MQTT no longer requires server name to be set

- server/client.go
- server/route.go
- server/routes_test.go
Need to handle case of no pooling or pool size of 1.
> Follow up on PR #4701

- server/consumer.go
- server/jetstream_events.go
- server/jetstream_test.go
* Support getting a reason from the client doing a term
* Supply some reasons when terminating messages during limits processing
> Extend the term advisory with a reason

- server/consumer.go
- server/filestore.go
Previously we would need to move through all msg blocks and load all of the blocks into memory. We optimized this regardless to flush the cache if we loaded it like other places in the code, but for this specifically we load subject's totals which is already in memory and for each matching subject we now simply load the last message for that subject and add the sequence number to the skip list.
This drastically improves consumers that want last per subject, like KV watchers and object store lists.
Resolves: #4680
> [IMPROVED] Improved time to select skip list and starting sequence number for deliver last by subject

- server/consumer.go
- server/filestore.go
Also on SubjectsState only loadMsgs if the mb.fss is nil.
> [IMPROVED] Optimize on last by subject if mmps is one

- .github/actions/nightly-release/action.yaml
- .github/dependabot.yml
- .github/workflows/MQTT_test.yaml
- .github/workflows/cov.yaml
- .github/workflows/go-test.yaml
- .github/workflows/nightly.yaml
- .github/workflows/rc_nightly.yaml
* goreleaser/goreleaser-action 3 -> 5
* actions/checkout 3 -> 4
Also bumped default tag for nightly.
Signed-off-by: Rene Leonhardt <65483435+reneleonhardt@users.noreply.github.com>
> chore: Update GitHub actions

- server/raft.go
The runAsFollower would disable observer state working at all.
> [FIXED] Remove the state check in the runAs loops except for runAsLeader.

- server/raft.go
- server/raft_test.go
The `Observer` raft state was actually unused and is a red herring. Instead, observer state is tracked using a separate bool.
This PR also adds a unit test that confirms that applies are still happening when followers are observers.
Signed-off-by: Neil Twigg <neil@synadia.com>
> Remove unused `Observer` const, add unit test to check observer applies

- server/auth.go
- server/jwt_test.go
If a tag that doesn't exist is followed by a tag that does, a panic can occur in the subject calculation. Added a test to prove that it no longer panics and instead just returns a `generated invalid subject` error.
> Fix panic in JWT permissions template handling

- server/mqtt.go
- server/mqtt_test.go
The tests explain the condition. TL;DR: a rapid, **load-balanced** sequence of connects/disconnects from the same client to a cluster was causing failures.
This PR:
- eliminates the need to load the session message from JS when processing a persist notification from another server. The clientID that was previously obtained from the loaded message is now available in the ACK subject.
- eliminates the separate goroutine/ipQueue for processing session persist messages; now in-line
- ignores deleteMsg errors if caused by outdated cached session data
- fixes incorrect ACK subject in transfering retained messages 2.9->2.10
@derekcollison please note a **highly** variable test run times O(1ms) - O(100ms), including targeting the same server. Not sure what's going on there. (`go test -v ./server …
> [FIXED] MQTT: rapid load-balanced (re-)CONNECT to cluster causes races

- server/filestore.go
> [FIXED] Make access to mb's first and last sequence to consistently use atomics.

- server/client.go
- server/websocket_test.go
The application would disconnect due to garbage data.
This issue was introduced when refactoring flushOutbound with introduction of c.out.wnb. We no longer need to handle specifically for websocket (we were incorrectly adding c.out.nb to websocket frames...)
> [FIXED] Websocket: partial writes may lead to disconnect

- server/jetstream_cluster.go
- server/norace_test.go
- server/stream.go
We would attempt to sync with stream state and reset our CLFS tracking which would cause issues, so we do not reset CLFS or send snapshots upon being elected leader.
There is still a bug that I can see that I am chasing, but this solves many of the issues we would see in other tests.
> [IMPROVED] Resiliency when doing lots of conditional updates to a KV and restarting servers.

- server/client.go
- server/leafnode.go
- server/mqtt.go
- server/mqtt_test.go
Re-ordered the interactions with JetStream outside the locks.
2 specific use-cases covered in the tests
- Attempt to subscribe to `#` was causing deadlocks when retained messages were present.
- Attempt to subscribe to anything with relevant retained messages if a `#` (or any other subscription matching internal subjects, say `+/+/.../+`) was already set up.
> [FIXED] MQTT: deadlock between JS API and mqttDeliverMsgCbQoS0

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
Resolves https://github.com/nats-io/nats-server/issues/4771
The calculation for `MaxBytes` in combination with `DiscardNew` would be off. Using the `memStoreMsgSize`/`fileStoreMsgSize` seems to be (more) accurate.
Signed-off-by: Maurice van Veen github@mauricevanveen.com
> Fix DiscardNew exceed bytes calculation

- server/leafnode.go
- server/leafnode_test.go
This fixes the concatenated path used by remote leafnodes.
Fixes #4765
> Fix subpath used for ws leaf remote connect url

- server/filestore.go
When compacting in the syncBlocks make sure to grab fs lock in case we need to load msgs and reference psim.
> [FIXED] Datarace and panic when accessing psim from syncBlocks.

- server/leafnode.go
- server/leafnode_test.go
- server/websocket.go
This changes the`/leafnode` and `/mqtt` checks on a ws connection to detect that it is a leafnode connection over the websocket port.
This way given a remote like this:
```hcl
remotes = [
{
url: "ws://user:pass@127.0.0.1:8080/nats-leafnode",
account: "ACC"
}
]
```
Then the nginx LB configuration would match the same sub path as the configured remote leaf URL:
```hcl
upstream websocket {
server 127.0.0.1:8888;
}
location /nats-leafnode/leafnode {
proxy_pass http://websocket;
}
```
> Check for /leafnode suffix path on leaf ws connect

- server/filestore.go
Once set was set for all blks, so this localizes per blk.
> Make sure compact bool localized.

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/norace_test.go
- server/raft.go
- server/stream.go
When a message is rejected due to constraints, like CAS operations on KeyValue, we track offsets between the NRG (Raft) layer and the stream. During heavy usage and many msgs being rejected due to constraint violations and constantly restarting servers we saw some inconsistencies.
> [IMPROVED] General stability and consistency improvements for clustered streams with failure offsets during server restarts.

- server/raft.go
This PR mostly just tries to comment what is going on inside `raft.go` and does odd little bits of housekeeping/cleanup in places.
> Improve `raft.go` comments

- server/filestore.go
- server/filestore_test.go
The lock was briefly released to run `writeFullState`, but `fs.closed` wasn't set by that point, so another `Stop()` call could run and panic on closing the `qch` which was already closed.
> Fix panic in `fileStore.Stop()`

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
In cases where msg blocks have msgs but many have been deleted from the front, this speeds that up significantly.
> [IMPROVED] When we are linear scanning for first message, check if start < mb.first.seq.

- server/stream.go
This matches what fs.Delete() (and fs.Purge) were already doing.
> [IMPROVED] When removing very large streams, do fs cleanup in separate go routine.

- server/filestore.go
- server/memstore.go
No matter how a DiscardNew stream has gotten into a state where it is exceeding its configured limits, it it is never appropriate to fall back to DiscardOld behavior.  Applications rely on message durability after receiving delivery acknowledgement from a DiscardNew stream.
This patch adds a safety check to filestore's and memstore's limit reconciliation functions to prevent them from silently discarding a stream's first messages unless DiscardOld is configured.
Resolves #4775.  Silent data loss: enforceMsgLimit() and enforceBytesLimit() should never modify streams configured with DiscardPolicy.NEW
Related to #4771, where a nearby bug in message size calculation caused silent data loss.
> Only drop firstSeq under DiscardOld policy.

- server/client.go
- server/norace_test.go
- server/websocket.go
- server/websocket_test.go
In certain conditions, a WebSocket with a maximum frame size (i.e. web browsers) and specific message sizes could result in multiple overlapping slices being returned to the buffer pool. This would result in a data race that would result in data corruption on the wire.
This condition shouldn't affect WebSocket connections that don't have a maximum frame size.
> Fix data race in WebSockets (fixes #4808)

- server/consumer.go
- server/stream.go
Also protect swapSigSubs from deleted consumers.
Resolves #4809 
> [FIXED] Do not allow consumers to be updated if they have been deleted

- server/client.go
- server/filestore.go
- server/filestore_test.go
- server/gateway.go
- server/jetstream_cluster.go
- server/leafnode.go
- server/route.go
- server/store.go
Utilize non-allocating string casts to relieve pressure on GC subsystem and refactored subject handling for psim.
> [IMPROVED] Memory usage for large subject space streams

- server/consumer.go
This Just moves an assignment inside the if branch where it is used.  It's a micro optimization that's probably not worth making at all, but I came across this when reading the code and thought I could as well change it.
Signed-off-by: Sven Neumann <sven.neumann@holoplot.com>
> Only gather subject filters if we need them

- server/consumer.go
- server/jetstream_cluster.go
Beforehand the wait group was not adjusted until the goroutine had started, whereas the `inMonitor` state was adjusted before, so it may have been possible to race here. Moving these two things together should hopefully avoid this and I've also renamed a function for clarity.
This should hopefully also fix a potential panic on wait group reuse in some chaos scenarios.
> Tweak consumer monitor logic to avoid potential race

- server/consumer.go
- server/memstore.go
- server/memstore_test.go
> [FIXED] If a memstore had a last sequence that was deleted, GetSeqFromTime could panic.

- server/consumer.go
- server/filestore.go
If we had a rollback this could consume lots of memory during checkStateForInterestStream for followers since it will create pre-register acks incorrectly.
> [FIXED] Protect against bad consumer state with rollback.

- server/filestore.go
Will lessen affect on high speed ingest on large streams.
> [IMPROVED] Increase minimum interval for full index.db state writes.

- server/raft.go
- server/raft_test.go
- server/test_test.go
> Add low-level unit test for simple Raft election

- server/client_test.go
- server/filestore_test.go
- server/jetstream_consumer_test.go
- server/norace_test.go
- server/reload.go
- server/routes_test.go
Also correcting a few typos in tests that have accumulated.
> Fix reloading message for prof_block_rate

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_jwt_test.go
- server/stream.go
We had an issue with tiered accounts, where limits are flat based on type of storage. Meaning 100GB on R3 means 100GB of R3 storage, or 300GB in total. If we have limits only on an empty string tier, then consider limit as absolute, otherwise scale by tier replication.
Resolves issues with NGS account for HA / R3 limits.
> [FIXED] When calculating limits exceeded, treat replicated tier limits as flat

- server/subject_transform.go
- server/sublist.go
This method is only used from `subject_transform.go`, should it then live there as well?
Signed-off-by: Sven Neumann <sven.neumann@holoplot.com>
> Move helper subjectInfo() to the file where it's used

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_super_cluster_test.go
- server/norace_test.go
- server/stream.go
A customer had an issue with JS api requests backing up in the internal queue we use to avoid blocking non-clients. The reason for the buildup was known due to time spent in NumPending calculations for R1 consumers with wildcard filtered subjects and large subject/key space. These consumers were being created from a large fan in stream with many sources.
1. We now properly track the queue depth of this internal queue, warn if we are getting backed up and make sure to properly report under JS API usage stats - Inflight.
2. Use multiple Go routines in a pool to process this API queue vs 1.
3. When we fail to create a consumer for a mIrror or a source, back off retries.
4. When we fail do immediate cleanup, do not wait.
5. Only create internal interest for the consumer once we get a response …
> [IMPROVED] JSAPI internal routing and reporting and Source and Mirror setup

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
Update NumPending to use PSIM since block based fss is no longer present in >= 2.10.x
This was causing us to load all blocks to calculate NumPending for a new consumer with LastBySubject delivery.
Note this will be drastically improved with the new stree(ART) data structure in a future PR.
Signed-off-by: Derek Collison <derek@nats.io
> [IMPROVED] Do not load all blocks for NumPending when delivery is LastPerSubject.

- server/filestore.go
- server/filestore_test.go
- server/sublist.go
We had a bug that could cause internal memory corruption of psim subjects/keys in filestore. This could make it to disk via index.db. This checks subjects for corruption on reading in index.db.
Signed-off-by: Derek Collison <derek@nats.io
> [IMPROVED] Detect corrupt psim subjects during recovery of index.db.

- server/config_check_test.go
- server/configs/reload/tls_multi_cert_1.conf
- server/configs/reload/tls_multi_cert_2.conf
- server/configs/reload/tls_multi_cert_3.conf
- server/opts.go
- server/reload_test.go
This adds a `certs` option to the `tls` block to support loading multiple certs:
```hcl
tls {
certs = [
{
cert_file: "./configs/certs/srva-cert.pem"
key_file:  "./configs/certs/srva-key.pem"
},
{
cert_file: "./configs/certs/srvb-cert.pem"
key_file:  "./configs/certs/srvb-key.pem"
}
]
ca_file: "./configs/certs/ca.pem"
verify:  true
timeout: 2
}
```
Follow up from https://github.com/nats-io/nats-server/pull/2029
> Add 'certs' option to TLS block for multi-certs support

- server/config_check_test.go
- server/configs/reload/tls_multi_cert_1.conf
- server/configs/reload/tls_multi_cert_2.conf
- server/configs/reload/tls_multi_cert_3.conf
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/opts.go
- server/reload_test.go
- server/stream.go
- server/subject_transform.go
- server/sublist.go
- #4873
- #4880
- #4881
- #4884
- #4885
- #4890
- #4889
> Release v2.10.8 cherry picks

- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_helpers_test.go
- server/mqtt_test.go
- server/raft.go
Previously we processed this inline with startRaftNode. Normally this was fine, however if the existing WAL entries were very large, this would consume lots of memory since the upper state machine will not be running. 
Now we will track how much memory we have been building up in the apply queue, and if it exceeds our threshold we will pause the apply queue and resume from the run() go routine.
> [IMPROVED] Do not allow large memory buildup in the apply queue for NRGs during startup.

- internal/fastrand/LICENSE
- internal/fastrand/fastrand.go
- internal/fastrand/fastrand_test.go
- server/accounts.go
- server/client.go
- server/raft.go
In order to avoid top-level lock contention in the `math/rand` package, we were previously initialising our own `prand` sources in various structs. However these still needed to be protected by locks and they also just weren't that fast.
This PR removes those `prand`s and replaces those calls with calls to the Go runtime's `fastrand`, which is a couple hundred times faster and is, more importantly, lock-free:
```
goos: darwin
goarch: arm64
pkg: github.com/nats-io/nats-server/v2/server/fastrand
BenchmarkFastRand32
BenchmarkFastRand32-10          1000000000               0.2564 ns/op
BenchmarkFastRand64
BenchmarkFastRand64-10          1000000000               0.5019 ns/op
BenchmarkDefaultRand32
BenchmarkDefaultRand32-10       11997840               104.4 ns/op
BenchmarkDefaultRand64 …
```
> Use `fastrand` instead of `prand`s

- server/mqtt.go
Previously ' ' and '.' were not supported for MQTT topics until [#4243](https://github.com/nats-io/nats-server/pull/4243) brought in support for '.'. However the error message for unsupported characters appears to not have been updated. This simply updates the error message.
Had an example of a MQTT client trying to connect to `spBv1.0/Field Devices` and the error message indicated that both '.' and ' '  were unsupported which was misleading as only ' '  is unsupported.
Signed-off-by: Tom Hollingworth <tom.hollingworth@spruiktec.com>
> [FIXED] Fix unsupported MQTT topic characters error message

- server/certidp/certidp.go
- server/certidp/certidp_test.go
**Changes Proposed**
This pull request introduces a modification to the GetStatusAssertionStr
This change ensures that if no suitable value is found in the mapping (StatusAssertionIntToVal), the function will now default to returning "unknown" (from ocsp.Unknown).
**Motivation**
The motivation behind this change is to enhance the robustness of the GetStatus Assertion Str function. Previously, if the provided status assertion value did not exist in the map, the function return ocsp.Good.
**Unit Tests**
Unit tests have been added to cover various scenarios, including valid status assertion values for "good," "revoked," and "unknown," as well as an invalid status assertion value.
Please review this pull request 
Signed-off-by: Denis Korovin @korovindenis
> Fix return value in func

- server/filestore.go
- server/filestore_test.go
- server/raft.go
We will hold onto fss data to prevent large blocks being loaded into memory during scans like PurgeEx.
Also we now track both forward and backward linear access for expiring msg caches.
> [IMPROVED] Allow fss metadata to not expire when msg cache expires.

- README.md
We have an existing Artifacts Hub repository, based on the nats-io/k8s repo.
Including a badge which links to that repository should resolve the "Artifact Hub badge" item in the CLOMonitor report on nats.
While there, normalise the "CII Best Practices" badge to use markdown reference links, the same as all the other badges.
> badges: add ArtifactHub; normalize CIIBestPractices

- server/consumer.go
- server/jetstream_cluster.go
- server/monitor.go
- server/store.go
This PR optimises the marshalling of metalayer snapshots with a few techniques:
* Simplifies the custom marshalers for a number of types that appear often in the snapshotted config, as these were using reflection unnecessarily
* Simplifies the custom unmarshallers for the same types, as these were string-building more than necessary
* Attempts to reduce the number of reallocations that might happen in `metaSnapshot()` by preallocating slices
> Optimise metalayer snapshots

- server/jetstream_cluster.go
Since `doSnapshot` in both cases can be called from a maintenance timer or on the quit signal, this may cause us to snapshot before recovery has completed.
> Don't allow stream or consumer snapshots before recovery completed

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/memstore.go
- server/memstore_test.go
- server/norace_test.go
- server/store.go
- server/stream.go
Under scenarios where interior deletes were orders of magnitude larger than the msgs themselves, the system would need to transfer all interior deletes as skip msgs. This change adopts the ability to send DeleteRanges on streamSyncRequests, and for R1 mirrors to locally use the new store.SkipMsgs to optimize speed.
This CL also has a bug fix for memory store state with delete details, and several general improvements to the filestore impl.
> [IMPROVED] Optimize catchups for replicas and mirrors with large interior deletes.

- server/norace_test.go
- server/stream.go
Improves how the sequence number of the last sourced message is found for all the stream's sources (in a single pass rather that individual passes for each source).
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
> Improve finding the last sourced message for each source of a stream

- server/auth.go
- server/auth_test.go
- server/opts_test.go
> [IMPROVED] Allow no_auth_user to be an nkey.

- server/reload.go
- test/ocsp_test.go
Instead of attempting to detect whether the TLS configuration has changed
on each tls connection type, this changes to always restart the OCSP monitors
on reload in order to avoid `peer missing OCSP Staple` errors.
> Always restart OCSP monitors on reload

- .travis.yml
Test versions are now:
- 1.21.6
- 1.20.13
> Bump Go version to 1.21.6

- server/jetstream_test.go
It can take up to a couple of seconds for new source consumers to get established and all the message getting sourced in the test, the final tests had a timeout of 2 seconds that could sometimes be reached in Travis. Relaxing that timeout to something more generous fixes the flapping
> Fix flapping in TestJetStreamMirrorBasics

- server/core_benchmarks_test.go
- server/jetstream_benchmark_test.go
- Benchmark measures throughput of `N` producers publishing `M` messages to a stream
- Benchmark was previously not correctly waiting for publisher sub-routines to be created before starting `fan-in` workload.
- Publishers now generate a new random payload for each publish iteration.
- Style and formatting fixes to increase readability.
Signed-off-by: Reuben Ninan <reuben@nats.io>
> Add new JS multiproducer benchmark and fan-in benchmark improvements

- server/jetstream_api.go
- server/jetstream_test.go
Adds testing for backwards compatibility of pre 2.10 existing stream sources which used a previous message header format, the header is used to find the starting point of the source's consumer on leadership changes or stream config updates when sources are added.
> Adds testing for backwards compatibility of pre 2.10 existing stream sources

- server/jetstream_cluster.go
Feasibly a Raft node that is keeping up with its peers can become a leader regardless of whether or not the upper layer is caught up with its applies. Since the leader change notification to the upper state machine could interleave with the apply queue, then unconditionally sending a snapshot as a new append entry on consumer leader transitions could cause the rest of the group to revert to an earlier consumer state.
> Don't unconditionally send consumer snapshot when becoming leader

- server/filestore.go
- server/filestore_test.go
If LoadNextMsg was called with start sequence == FirstSeq, we would walk all blocks, which if fss was loaded we could skip fairly quickly. However on a restart or no activity past a sync interval this could cause memory blocks to be loaded in just to be skipped.
https://github.com/nats-io/nats-server/discussions/4906
> [IMPROVED] Do not load blocks when calling LoadNextMsg for the first time after restart or long inactivity

- server/stree/parts.go
- server/stree/stree.go
The `_pre` and `cparts` copies are more often than not unnecessary and result in potentially gigabytes of allocations which can slow down functions like `NumPending`.
Passing `pre` and `nparts` down recursively without copies is usually safe, even where there are appends in those, because there is no concurrency and those appends will not modify the slice length back at the callsite. Instead we'll only reallocate either when `append` does so naturally (we've ran out of capacity) or when we know specifically that we're modifying something in-place (like in `matchParts`).
This improves performance of things like `NumPending` with high subject cardinality.
> stree: Reduce allocations in `iter` and `match`

- server/stree/stree.go
When using `make(x, y, z)`, there is a heap escape due to the non-constant size/capacity. Try to stay on the stack instead, reducing GC pressure.
> stree: Reduce heap escapes in `iter`

- server/stree/stree.go
In #4974 I removed preallocated buffers for `pre` as the copies were unnecessary on each single recursion, however it turns out that having a preallocation up front removes quite a few unnecessary allocations from subject construction as the underlying memory gets reused throughout the iteration or match process, relieving further pressure on the GC.
> stree: Preallocate `pre` at top level `Match`/`Iter` calls

- server/memstore.go
This updates the memory store to use the new subject tree from #4960 for per-subject tracking.
> Use stree for per-subject tracking in memory store

- server/core_benchmarks_test.go
- server/jetstream_benchmark_test.go
Two commits (for ease of review, but they can be squashed in merge):
1. Stop using the static (thread-safe) RNG provided by `math/rand`, the CoreFanIn benchmark is very slow due to the fact that producers are piling up to use a single shared instance
2. Switch all benchmarks to a faster message payload generation (which reuses the previous payload with minor mutations).
Signed-off-by: Your Name <marco@synadia.com>
> Faster payload generation in benchmarks

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
This adds batch support for direct gets. This also works with NextFor as well.
We will not hold any state in the server, so we need to protect against slow consumers. The request also adds in a MaxBytes which can allow the client to control how much data the server will blast to it. If the client request does not contain a non-zero MaxBytes, the server will use its opts.MaxPending.
After a batch has completed, even if cut short due to MaxBytes, the server will send an end of batch (EOB) empty message with a status of 204 in the header, and a header Nats-Num-Pending which reports how many messages remain.
```go
// JSApiMsgGetRequest get a message request.
type JSApiMsgGetRequest struct {
Seq     uint64 `json:"seq,omitempty"`
LastFor string `json:"last_by_subj,omitempty"`
NextFor string …
```
> [ADDED] Batch support for direct gets from streams.

- server/filestore.go
The current code only appeared to identify holes in the message block index if they appeared at the start of the block or in between non-deleted messages, but didn't detect afterwards if there was a drift between the last indexed sequence and the last seq from the state. This now fills those gaps in the index at the end of the block too.
This fixes the accounting problem that could cause `cacheAlreadyLoaded` to incorrectly report that a block wasn't available in the cache when it actually was.
> Fix tracking holes in the message block index when they are at the end of the block

- server/jetstream_benchmark_test.go
- server/jetstream_meta_benchmark_test.go
New benchmarks:
- Jetstream subscription with filters over high cardinality subjects stream
- Create throughput for Stream, KV Store, Object store 
- Create throughput for JetStream consumers 
> New benchmarks: filtered subscription, resource creation

- server/raft.go
This makes it clear in the logs that the falling behind condition cleared up.
> NRG: Log healthy status when no longer falling behind

- server/filestore.go
- server/filestore_test.go
This PR makes two changes to `writeFullState`:
1. Use `Match(">", ...)` instead of `Iter(...)` as it is faster and results in less heap escapes
2. Don't allocate a 4K buffer on the stack if it's obvious that we won't use it
> Optimise filestore `writeFullState` for high subject cardinality

- server/filestore.go
- server/filestore_test.go
This was reported by @piotrpio when trying to do a secure erase of a message the was followed by dbit markers which occur  after compaction removes records from the raw msg block. The idx then expands via dbit markers for the idx slice.
> [FIXED] Fix for a panic calculating record length for slotInfo when followed by dbit markers in idx.

- server/events.go
If a reload happened during the LDM grace period, it was possible for the `resetCh` to have been closed between the loader fetching the channel, releasing the lock and then sending to it. By making sure that closing the channel happens after `s.sys` is invalidated, we can avoid this panic.
> Avoid panic when reloading during LDM

- server/accounts.go
- server/jetstream.go
- server/jetstream_events.go
- server/jetstream_test.go
This was intent of original design but was only sharing basic info.
> [IMPROVED] Share higher fidelity client info with JetStream

- server/raft.go
- server/raft_test.go
A node's Term may be increased during handling of a VoteRequest. When that was the case, the node was responding with a stale Term.
Example trace:
```
[DBG] RAFT [S1Nunr6R - S-R3F-5xgoWjQW] Received a voteRequest &{term:27 lastTerm:26 lastIndex:46 candidate:yrzKKRBu reply:$NRG.R.OHF7VRUO}
[DBG] RAFT [S1Nunr6R - S-R3F-5xgoWjQW] Stepping down from leader, detected higher term: 27 vs 26
[DBG] RAFT [S1Nunr6R - S-R3F-5xgoWjQW] Stepping down
[DBG] RAFT [S1Nunr6R - S-R3F-5xgoWjQW] Switching to follower
[DBG] RAFT [S1Nunr6R - S-R3F-5xgoWjQW] Sending a voteResponse &{term:26 peer:S1Nunr6R granted:true} -> "$NRG.R.OHF7VRUO"
```
This is handled correctly except VoteResponse in the last log line should be sending back Term 27, not 26.
Signed-off-by: Your Name <marco@nats.io>
> RAFT node responds to VoteRequest with outdated Term

- server/jetstream_cluster.go
Sending meta snapshots as normal entries on leader change might cause a snapshot to be generated before the apply queue has been processed fully.
> NRG: Don't send metaleader snapshot as normal entry on leader change

- server/client.go
- server/jetstream.go
Needed to explicitly set "to" to avoid extra work.
Caused performance hit on KV Get performance tests. Never released, so internal.
> [FIXED] When moving to direct addServiceImport, saw performance degradation.

- server/filestore.go
Was not released, was introduced in dios work.
> [FIXED] Use dios gate internally and do not wrap whole function.

- server/jetstream_cluster.go
We used to more broadly try to cleanup directories under a consumer. This could cause issues with reports of missing "tav.idx" etc.
This only scopes to then the account has been removed from the server.
> [IMPROVED] Revamped fallback cleanup of consumer raft directory.

- server/client.go
- server/config_check_test.go
- server/configs/reload/reload.conf
- server/opts.go
- server/reload_test.go
- server/route.go
- server/routes_test.go
Adds support to customize the `ping_interval` for routes to be different from `ping_interval` from clients:
```hcl
port = 4222
http = 8222
server_name = 'A'
cluster {
name = 'ABC'
port = 6222
routes = [
nats://localhost:6222
nats://localhost:6223
nats://localhost:6224
]
ping_interval = '5s'
ping_max = 6
}
ping_interval = '30s'
```
> Add support to customize cluster ping_interval

- server/client.go
- server/config_check_test.go
- server/configs/reload/reload.conf
- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/opts.go
- server/raft.go
- server/raft_test.go
- server/reload_test.go
- server/route.go
- server/routes_test.go
- #5025 
- #5021 
- #5024 
- #5026 
- #5027 
- #5028 
- #5029
> Cherry-pick PRs into v2.10.10 release branch

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/norace_test.go
Would lead to zombies, most common in consumers.
> [FIXED] Make sure to not restart streams or consumers when they are deleted or creation time is too soon.

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/norace_test.go
> Cherry-pick PRs into v2.10.10 release branch 

- server/auth_callout.go
- server/auth_callout_test.go
For operator mode, the server was not sending an auth violation. Added additional tests checking for this on both conf and operator mode.
> [FIX] [authcallout] ensure authcallout in operator mode sends an auth error instead of timeout

- .github/workflows/MQTT_test.yaml
- server/mqtt.go
- server/mqtt_ex_test.go
This PR adds a number of MQTT-specific benchmarks, executed with an external test client (see https://github.com/ConnectEverything/mqtt-test/pull/1). This came out of my work on MQTT message delivery issues in 2.10, and is now packaged as a `go test --bench`, and added to CI.
The test client uses the Eclipse `paho` library, and can be executed standalone, pointed at an MQTT server. It measures the timing of its operations, and outputs it as JSON of reportable metrics.
The benchmarks here run the client, and report back the metrics it outputs. Memory allocations are measured server-only. 
Github action `benchmark` is used to compare the benchmark results to the base ref of the PR, or the prior result in a branch. If it fails a 120% threshold, the failure is reported as a comment on the …
> [ADDED] MQTT: test/bench using external client

- server/filestore.go
While troubleshooting a cluster recovering a large stream, it was spotted that this read call was taking long to complete.
> Use IO gate when doing io.FullRead on block

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_events.go
> [ADDED] JetStream domain elected advisory for when we have a new meta leader.

- server/mqtt.go
- Cleaned up the retained message consumer name so that it does not cause problems
- Per @derekcollison's recommendation, use an ephemeral consumer for retained messages
> FIXED: MQTT retained message consumer creation

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/config_check_test.go
- server/configs/accounts.conf
- server/events.go
- server/gateway.go
- server/jetstream_cluster.go
- server/leafnode.go
- server/msgtrace.go
- server/msgtrace_test.go
- server/opts.go
- server/parser.go
- server/parser_test.go
- server/reload_test.go
- server/route.go
- server/server.go
- server/stream.go
- test/new_routes_test.go
When an incoming message contains the header `Nats-Trace-Dest` set to a valid subject, the server will send there messages representing events happening in each server where the message is processed.
The events will give details about ingress, subject mapping, stream export and service imports, jetstream and egress to subscriptions and/or routes, leafnodes and gateways. Except for a standalone server it is expected to receive multiple trace messages for a given inbound message.
The header `Nats-Trace-Only`, if set to `true`, will produce the same tracing events than without that header, except that the message will not be delivered to subscriptions or inserted in the JetStream stream. This is usefull to see the path that a message would take but without affecting running applications. …
> [ADDED] Distributed Message Tracing

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/norace_test.go
Do not force sequence mismatches and possible dataloss on first sequence move past a catchup request.
When a server restarts and does a stream catchup where the snapshot from the leader is for messages it no longer has, we would create a sequence mismatch reset on the follower.
Also on a catchup if the stream state has moved past the updated request range from a follower, meaning first for the new state is past the last of the request, extend and continue catchup.
> [FIXED] KeyValue not found after server restarts

- server/const.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
- server/stream.go
Updated direct get batch to always have num pending in headers. Also added in last sequence to detect any message loss to all messages and the EOB marker. Will also allow pipeline fills, to better set us up for using this as even lighter weight replacement for any consumer.
> Improved batch direct get.

- server/const.go
- server/jetstream_test.go
- server/stream.go
We were mixing between in batch messages and EOB. Make consistent and use the following always.
```go 
JSNumPending   = "Nats-Num-Pending"
```
> [IMPROVED] Make num pending consistent

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/config_check_test.go
- server/msgtrace.go
- server/msgtrace_test.go
- server/opts.go
- server/server.go
- server/stream.go
If the `Nats-Trace-Dest` header is not present, but `Traceparent` is and its last token is `01`, then message tracing is triggered. This also requires that the account be defined with a `trace_dest` subject so that traces can be sent there.
Note that `Nats-Trace-Only` is not applicable for `Traceparent`.
Addition to PR #5014
Resolves #5052
> Added OpenTelemetry support

- server/client.go
- server/jetstream.go
- server/jetstream_cluster.go
> [IMPROVED] Use GOMEMLIMIT if set to calculate dynamic memory limits for JetStream

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
> [FIXED] Make sure to properly handle filtered purges with consumers that have a wider filtered subject.

- server/accounts.go
- server/accounts_test.go
- server/msgtrace.go
- server/msgtrace_test.go
- server/opts.go
- server/server.go
Update the tests accordingly.
This change is ok since the message tracing feature is targeted for v2.11.0 which has not been released yet.
Related to #5057
> Change Account.TraceDest to private and add getter/setter

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
Calculate peer group based on streams as well as usage and realtime data on HAAssets vs async.
Resolves: #5071 
> [IMPROVED] Stream placement in cluster with N > R

- server/filestore.go
- server/stree/node.go
- server/stree/parts.go
- server/stree/stree.go
- server/stree/stree_test.go
When encountering partial frags or parts we were not properly offsetting by si. This would cause certain stree setups to fail to match properly against wildcarded subjects that had to deal with partial frags and partial parts.
Also lowered the prefix from 60 to 24.
Improved NumPending in filestore by check if fssLoaded vs whole cache.
> [FIXED] Stree match bug, filestore minor improvements.

- server/raft.go
The stepdown channel interleaves with other channels such as the apply queue, leader change notifications etc in the `runAs` goroutines in an unpredictable order, so processing a stepdown request might be delayed behind other work. Doing this inline should be safer with stronger guarantees.
> NRG: Remove stepdown channel, handle inline

- server/filestore.go
They should not happen, but it is possible and not actionable by operators, so debug is better.
> [IMPROVED] Move reallocation warnings on psim to debug.

- server/consumer.go
When a filtered consumer starts by time, there could be a large gap between the time to sequence and the real start.
This uses similar logic to starting from the beginning of a stream for a filtered consumer.
> [IMPROVED] Startup time for a start sequence by time filtered consumer.

- server/consumer.go
- server/filestore.go
> Cherry picks for v2.10.11 release

- .github/workflows/MQTT_test.yaml
https://github.com/nats-io/nats-server/pull/5082 was supposed to fix this, but it is not reviewed yet.
`mqtt-test` got updated; and the `@latest` reference is causing the new, incompatible, version to be used. This PR will fix it, until #5082 is merged.
> Fixed incorrect mqtt-test reference (mqttex tests failure)

- server/ocsp.go
- test/ocsp_peer_test.go
- test/ocsp_test.go
This makes the server send a POST request to the OCSP Server, then falling back to use GET as in previous versions.
> ocsp: make ocsp request with POST method

- server/client.go
- server/routes_test.go
Adds extra logging for routes to notice when a route that has temporarily entered the Slow Consumer state has recovered.  
Also changes the counter for route slow consumer to only count each time the server detects that a route became a slow consumer.
Example logs:
```
[20] 2024/02/17 06:18:48.891218 [INF] 10.84.13.21:33226 - rid:3579 - Slow Consumer Detected: WriteDeadline of 10s exceeded with 160926 chunks of 349984270 total bytes.
[20] 2024/02/17 06:18:58.919430 [INF] 10.84.13.21:33226 - rid:3579 - Slow Consumer State: WriteDeadline of 10s exceeded with 237701 chunks of 515825015 total bytes.
[20] 2024/02/17 06:19:08.979502 [INF] 10.84.13.21:33226 - rid:3579 - Slow Consumer State: WriteDeadline of 10s exceeded with 329433 chunks of 715565941 total bytes.
[20] 2024/02/17 06:19:18.994486 …
```
> Track recovery from slow consumer events in routes

- go.mod
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_events.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/test_test.go
This adds a new `pause_until` configuration option for pausing consumers.
It can either be set when the consumer is created (but not via a standard consumer update) or it can be changed later by using the new `$JS.API.CONSUMER.PAUSE.*.*` API endpoint by sending:
```
{"pause_until": "2024-02-08T19:00:00Z"}
```
Any time that is in the past, or a zero timestamp, is considered as "unpaused". Once the consumer reaches the `pause_until` time, messages will start flowing again automatically.
The consumer info will additionally include `paused` (type `bool`) and, if paused, a `pause_remaining` (type `time.Duration`) to report the pause status.
Also adds `$JS.EVENT.ADVISORY.CONSUMER.PAUSE.*.*` advisory messages which are sent when pausing and unpausing (i.e. reaching the pause deadline).
Idle …
> Add support for pausing consumers

- server/client.go
- server/opts.go
- server/websocket.go
- server/websocket_test.go
[FEAT] this change adds `user_cookie`, `pass_cookie`, and `token_cookie` to the WS configuration block - these mirror the behavior of `jwt_cookie`. If the options are not specified by the client but the server is has them configured, a WS connection will lookup values for the corresponding options under the HTTP cookie. This simplies websocket applications by allowing the HTTP application to set cookies that provide authentication details.
Simplifies #5047 
Signed-off-by: Alberto Ricart <aricart@synadia.com>
> [FEAT] additional WS authentication cookie configurations

- server/client.go
There's now an additional bounds check when checking for CRLF and moved one or two other bits around.
> Refactor `getHeader` to improve bounds checking

- server/jetstream_cluster_3_test.go
> Make consumer pause tests a bit more forgiving in cluster mode

- server/const.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
This allows a client to get multiple results based on multiple filters, each which can include a wildcard. You can optionally specify an UpToSeq or UpToTime.
The results will be returned in sequential order.
They will have headers matching direct get batch as well, with num pending being how many more results are coming. Currently we limit to 64 results maximum, and may revisit this in the future.
> [ADDED] Add support for multi-get directly from a stream.

- .github/workflows/tests.yaml
This should stop the status on `main` for now.
> Tweak GHA, don't run on push

- server/consumer.go
- server/jetstream_cluster_1_test.go
There was a bug that caused sending `Consumer Deleted` sending to pull consumers whenever a Peer was removed.
This is a draft solution, as I don't like how the code looks right now:
When peer is removed, the `delete flag` is set to `true`, and thats fine. After all we need to remove the stream from the peer.
However, we do not differentiate in any way if we are removing the RAFT asset as a whole, or just it from the given peer.
That's why I added additional flag, which allows more informed choices by the codepaths for stopping streams and consumers.
> Fix sending `Consumer Deleted` on peer remove

- server/consumer.go
while working on a pull request for the nats rust client, implementing the update_consumer method (which updates a consumer with a new config), i ran into a weird issue.
consumers that had the "by_start_time" delivery_policy could not be updated - they would throw the error "start time can not be updated" even though the OptStartTime would be set to the same value.
reading through the server/consumer.go code it seems like even though OptStartTime is a pointer to a time, the comparison in checkNewConsumerConfig does not take that into account and just checks for equality. therefore - if both the old config had their OptStartTime set and the new config has the same time.Time - they would be different, as they are different pointers.
this is my attempt at fixing the issue following the logic …
> [FIXED] update consumer config fails to check OptStartTime properly

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
- server/memstore.go
Firing too often can effect ingest performance.
Resolves: #5136 
> [IMPROVED] Do not fire the store's expire timer too soon or too often since.

- server/raft.go
In particular peer state entries don't produce committed entries, but bumping `applied` inline means that we can potentially move the Raft state ahead of the real applied state. Instead just send up a CE with no entries and wait for the upper layer to update `applied` instead, so that there is better consistency between the layers.
> NRG: Wait for upper layer to update applied on inline CE updates

- server/raft.go
This should ensure that duplicate vote responses from the same node can't be handled and that vote response terms can't be mixed during the handling.
> NRG: Tweak vote response handling

- server/jetstream_api.go
- server/jetstream_test.go
Fixes https://github.com/nats-io/nats-server/issues/5163, by setting the `PauseUntil` to `nil` if it was a zero-value.
This fixes the CLI `nats consumer resume` command, which is sending an empty/nil body to `$JS.API.CONSUMER.PAUSE.*.*`.
Allowing for both sending an empty/nil body as well as omitting `pause_until` (for example with just `{}`)
> Fix consumer resume on empty/zero PauseUntil

- server/consumer.go
- server/jetstream_consumer_test.go
In PR #5111 we decided to send or not the `Consumer Deleted`  message based on the fact if consumer is or is not assigned. However, in non-clustered mode, consumer will not have assignment, which would result in not sending the `Consumer Deleted` message.
> Fix consumer deleted message in non-clustered mode

- server/client.go
Take modulus before casting fastrand result to int as it can end up negative.
Related: https://github.com/nats-io/nats-server/issues/5167
> Fix select random qsub on 32-bit

- server/raft.go
Fixes:
```
goroutine 38 [sync.Mutex.Lock, 349 minutes]:
sync.runtime_SemacquireMutex(0x1400070c9c0?, 0xd0?, 0x140004630e0?)
/opt/homebrew/Cellar/go/1.21.2/libexec/src/runtime/sema.go:77 +0x28
sync.(*Mutex).lockSlow(0x14000574300)
/opt/homebrew/Cellar/go/1.21.2/libexec/src/sync/mutex.go:171 +0x174
sync.(*Mutex).Lock(...)
/opt/homebrew/Cellar/go/1.21.2/libexec/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x14000574300)
/opt/homebrew/Cellar/go/1.21.2/libexec/src/sync/rwmutex.go:147 +0x70
github.com/nats-io/nats-server/v2/server.(*raft).setWriteErr(0x14000574300, {0x101659208, 0x1400071bb00})
/src/server/raft.go:3789 +0x34
github.com/nats-io/nats-server/v2/server.(*raft).writePeerState(0x14000574300, 0x140009043b0)
/src/server/raft.go:3681 +0x20c …
```
> NRG: Fix writeErr lock usage in writePeerState

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
The motivation for this feature is to enable stream message gets as of some starting time. This is to match the same behavior with setting a start time when creating a consumer.
What this enables, combined with batches, is to read messages from a stream without the need to use a consumer. This is not intended for high-throughput use, but for querying and stream inspection.
The main driving need for this is the ability to inspect workqueue streams that cannot otherwise be done do due to the overlapping subject constraint.
> Add support for AsOfTime for get/direct msg requests

- server/jetstream_cluster.go
In a scenario where the `clfs` is high (i.e. with competing KV writes or a high number of duplicate messages) then the gap on the `clseq` fix-up condition was growing, probably to the point that it wasn't running when it should. This would cause a drift.
> Fix correcting `clseq` drift on high `clfs`

- server/accounts.go
- server/events.go
- server/monitor_test.go
In operator mode, the `acc` is the public nkey which can be difficult to correlate in monitoring dashboards. The `acc_name` as been added which includes the logical name associated with that account claims.
> Add logical name to accstatz endpoint

- server/jetstream_cluster.go
Avoid potential data race when re-capturing last seq:
```
Write at 0x00c00881bc98 by goroutine 9941:
github.com/nats-io/nats-server/v2/server.(*stream).processJetStreamMsg()
/nats-dev/src/github.com/nats-io/nats-server-gp/server/stream.go:4716 +0x2850
github.com/nats-io/nats-server/v2/server.(*jetStream).applyStreamEntries()
/nats-dev/src/github.com/nats-io/nats-server-gp/server/jetstream_cluster.go:2883 +0xb94
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream()
/nats-dev/src/github.com/nats-io/nats-server-gp/server/jetstream_cluster.go:2372 +0x2f00
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
/nats-dev/src/github.com/nats-io/nats-server-gp/server/jetstream_cluster.go:3781 +0x54 …
```
> Get last sequence with read lock in processClusteredInboundMsg

- server/gateway.go
- server/gateway_test.go
This should fix #5187. The `nil` check was insufficient because the reply could still be non-nil but empty.
This meant that we sent `RMSG $SYS $SYS.ACCOUNT.FOO.CONNECT +  myqueue 502` instead of `RMSG $SYS $SYS.ACCOUNT.FOO.CONNECT | myqueue 502`.
> Fix sending empty reply on gateway `RMSG`

- server/jetstream_test.go
When running tests using GOMEMLIMIT this one would fail.
> test: Fix TestJetStreamBasicNilConfig when GOMEMLIMIT is set

- server/filestore.go
- server/memstore.go
> [IMPROVED] Lower minimum threshold for expire timers to 250ms.

- locksordering.txt
- server/reload.go
- server/server.go
This may help with some problems during configuration reload with e.g. OCSP stapling.
> Add reload lock to ensure new connections await completion of config reload

- .github/workflows/stale-issues.yaml
This will mark an issue/PR as stale after 8 weeks
of complete inactivity (including comments). If/when new activity occurs, the stale label will be removed.
The purpose of this is to make it simplier for triagers to filter on stale issues to follow-up on.
> Enable stale issue/PR workflow

- server/filestore.go
We do not care about order so using Match() vs Iter() will be much more friendly to the GC. Especially for streams with lots of subjects, e.g. > 1M.
> [IMPROVED] Use match versus iter since more performant and less stressful on gc.

- server/consumer.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/stream.go
Using subset match for overlap checks does not work in some cases, like:
```
foo.*.bar
foo.bar.*
```
This PR swaps to using `SubjectsCollide` that takes that scenario into account.
While working on that PR, I thought it is worth checking other places we use subsetMatch for overlap, and those were changed too.
Signed-off-by: Tomasz Pietrek tomasz@nats.io
> Fix workqueue overlap

- server/monitor.go
- server/monitor_test.go
When making a JSZ request with the following options:
```
{streams: true, account: "FOO"}
```
If a server is not aware of account FOO, then the server would send back *all known accounts* details.
(Example: the additional test case provided would fail because the server sends back 3 account details, rather than zero)
The new behavior is consistent with request handling when `streams` is false: return 1 account detail if there's a match and 0 if there is no match.
> [FIXED] Adjust JSZ account filtering when asking for stream details

- server/consumer.go
Moved waiting queue for pull requests to linked-list. We had issues with very large MaxWaiting configured and causing memory and GC issues, especially if compaction kicked in.
Also when new requests for msgs are received and we are full, only check waiting queue at most once per second to avoid CPU pressure when application is continually sending new requests when the queue is full.
> [IMPROVED] Waiting queue for pull consumers

- server/jetstream_cluster.go
- server/memstore.go
- server/route.go
Signed-off-by: Your Name <your.email@example.com>
> chore: fix function names

- server/filestore.go
- server/filestore_test.go
Resolves: #5236 
Although unclear how the sequences got corrupted in the first place.
> [FIXED] Protect against corrupt msgBlock first or last sequence when doing indexing

- server/consumer.go
- server/jetstream_consumer_test.go
The code was just checking if max_deliver is >= than backoff, however infinite max_deliver is represented by -1, so it was erroring. This fixes that behavior.
> Fix checking max deliver when backoff is used

- internal/ocsp/ocsp.go
- server/gateway.go
- server/gateway_test.go
- server/ocsp.go
- test/ocsp_peer_test.go
- test/ocsp_test.go
Fixes some issues with gateways reconnections that had OCSP stapling enabled:
- Gateways that started without explicit remotes would not always have OCSP callbacks registered so had no staples ready for the remote connections, when this condition is detected they are now applied on the fly.
- Access to GetClientCertificate could be concurrent under some conditions and could also race with OCSP monitor updates.
- Reloading races with gateway reconnections also addressed.
Tests also cover conditions from #5207, this also moves the OCSP testing helpers to an internal package.
> ocsp: Fixes for gateway reconnecting and reloading

- server/accounts.go
- server/client.go
- server/events_test.go
- server/gateway.go
- server/leafnode.go
- server/mqtt.go
- server/norace_test.go
- server/route.go
- server/server.go
The main issue for router/gateway connections were that they would be registered with the global account but never removed from there, which would cause the connection to be retained. The memory leak was apparent in one user setup with large amount of subscriptions that were transfered to a slow gateway, causing accumulation of partial buffers before the connection was dropped.
For gateway connections, we also needed to clean the outbound's map since it can contain sublist referencing its own connection. Same for subscriptions in c.subs.
Another found cause for retained connection is with leafnode where we are using a subscription referencing the leafnode connection that was globally registered in a global sublist but never removed.
Also the connection's c.out.sg (a `*Cond`) needed to be …
> [FIXED] Possible memory leak due to connections not being released

- server/filestore.go
This eliminates the potential for a short or failed `rand.Read` to result in duplicate nonces used. Also fixes one or two ignored error cases.
> Improve error handling on `rand.Read`, `eraseMsg` in filestore

- server/auth.go
In this case, an empty-but-non-nil map would not be copied, which could result in the clone referring to the original map.
Also implement a deep copy of `AllowedConnectionTypes` for `NkeyUser`, like `User` already has.
> Tweak `clone` behaviour of `User` and `NkeyUser`

- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
Adds a test to check the existing behavior: when creating a WQ stream that sources from another stream and has a max messages limit and has discard policy new. The stream should never go over the limit but should still get all the messages in the stream being sourced (i.e. getting more messages as they are consumed from the WQ stream).
> Adds tests for WQ stream sourcing with limit and discard new behavior

- server/auth.go
This ensures that comparison of non-bcrypted passwords is done in constant time, whereas otherwise timing information may be apparent on a network with next to no jitter.
> Constant-time evaluation of non-bcrypt passwords

- server/opts.go
- server/websocket.go
- server/websocket_test.go
Allow to configure extra headers for the WebSocket Upgrade Response:
For Example:
```
websocket {
port: 8080
no_tls: true
headers {
Strict-Transport-Security: "max-age=15768000 ; includeSubDomains"
X-Frame-Options: "DENY"
}
}
```
Related Issue: https://github.com/nats-io/nats-server/issues/5226
Signed-off-by: Ramon Berrutti <ramonberrutti@gmail.com>
> [ADD] WebSocket custom response headers

- server/client.go
- server/client_test.go
- server/jetstream_test.go
- server/stream.go
Fix: https://github.com/nats-io/nats-server/issues/5253
Signed-off-by: Ramon Berrutti <ramonberrutti@gmail.com>
> [FIX] ignore Nats-Expected headers when process Inbound Source Msg

- server/memstore.go
- server/memstore_test.go
In memstore if upto sequence was not found, e.g. deleted already, the compact or purge command would fail.
> [FIXED] Bug that would cause extended purge or compact to fail.

- server/filestore_test.go
- server/jetstream_cluster.go
> [FIXED] Some general fixes

- server/sysmem/sysctl.go
Was getting a panic of checkptr: converted pointer straddles multiple allocations in go 1.22.1 on darwin.
> [FIXED] Fix for a race panic on macosx/darwin

- server/mqtt.go
- server/mqtt_test.go
- server/proto.go
[PDF](https://sparkplug.eclipse.org/specification/version/3.0/documents/sparkplug-specification-3.0.0.pdf)
subscribe on QoS 0
subscribe on QoS 1
133
aspects of Will Messages including use of the retain flag and QoS 1
aspects of the retain flag
of a Sparkplug Compliant MQTT Server
DBIRTH messages as they pass through the MQTT Server
NBIRTH messages available on a topic of the form:
$sparkplug/certificates/namespace/group_id/NBIRTH/edge_node_id
NBIRTH messages available on the topic:
$sparkplug/certificates/namespace/group_id/NBIRTH/edge_node_id with the MQTT retain flag set to
true
DBIRTH messages available on a topic of the form:
$sparkplug/certificates/namespace/group_id/DBIRTH/edge_node_id/device_id
DBIRTH messages available on the topic: …
> [ADDED] MQTT SparkplugB Aware support

- server/parser.go
When trace flags is closed and trace header is set, it leads to useless string memory allocation
Signed-off-by:  chenjpu <chenjpu@gmail.com>
> There is a useless memory allocation

- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/stream.go
- server/test_test.go
Specifically around interest and limited streams that are clustered. Since we operate consumers and streams independently, when a stream is removing msgs when acked and acks are coming into different servers at different times, etc. Messages can get stranded.
We introduce a better check of the interest state based on a collective low ack floor that will purge our copy of the stream to catch up. We run this periodically in monitorStream and during certain conditions.
Thanks to Wally for introducing the test that stresses this part of the system.
> [IMPROVED] Improvements to interest policy and workqueue clustered streams.

- util/nats-server-hardened.service
For the example hardened systemd file, which is derived from config files which Synadia uses in production, add more examples:
* Show setting GOMEMLIMIT env var
+ but also nudge towards using the external environment file for it
* Use an external environment config file if it exists
* Show mount-point dependency for JetStream
* Configure automatic restarts
* Show using InaccessiblePaths to lock down FS access even further
* Setup a service alias of simply 'nats'.
> systemd hardened example: add more guidance

- server/filestore.go
- server/stream.go
These error conditions didn't release held locks.
> Fix some missing mutex unlocks in filestore and streams

- server/filestore.go
Make sure to hold lock for duration of truncate, was calling slotInfo unprotected.
> [FIXED] Make sure to hold lock for duration of truncate

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
- server/stream.go
Updates and improvements to consistency of stream peers with interest retention and limits.
We moved msgId de-dupe processing to upper layer if clustered. 
Fixed interest state checks for streams and consumers.
For both filestore and memstore, if we are discard new and interest based retention we should not enforce at the store level.
This could lead to replica drift and sequences being assigned differently during server restarts, network hiccups.
Fixed bug in filestore that would not leave a tombstone during PurgeEx or Compact leading to recovery of a zero state.
> [IMPROVED] Interest based streams and consumers

- server/stream.go
The call to `o.applyState()` assumes that a write lock is held, whereas we were only taking a read lock.
> Fix race condition in `checkInterestState` by taking write lock

- server/consumer.go
- server/jetstream_cluster.go
- server/norace_test.go
When creating multiple workqueue consumers that collided, if the consumer landed on the meta-leader it would be created.
This was due to the fact that the meta-leader had the consumer assignment already and incorrectly passed wasExisting for isRecovering. On recovery we would allow from a previous bug in the 2.9 series and print a warning to the server log.
The fix is to not mark waExisting if the consumer assignment is not marked as recovering, and to pass the state of isRecovering from the js state itself.
Also added upper layer check to avoid thrashing the meta layer.
If the parent stream was an R1 the consumer would be created, on R>1 it would be created and then a non meta-leader server would fail and clean it up.
Resolves: #4957 
> [FIXED]  Creating colliding workqueue consumers could sometimes succeed.

- server/consumer.go
- server/jetstream_consumer_test.go
When we fail to deliver a message, we were not checking if this was a redelivery already and would decrement o.sseq, meaning we would pick up the same message after the next redelivery and would have a delivered count of 1.
This could lead to a message being delivered from the redelivery queue, but that could fail, then you would see same message twice, first with dc of 2, then 1.
Now app only gets one copy with delivery count of 2.
> [FIXED] Multiple deliveries of messages with delivery count going backwards.

- server/consumer.go
- server/filestore.go
- server/jetstream_consumer_test.go
Cherry-picks the following into the v2.10.14 release branch:
* #5303
* #5305
> Cherry-pick PRs for v2.10.14-RC.7

- server/stree/parts.go
- server/stree/stree_test.go
Partially addresses what is reported in https://github.com/nats-io/nats.go/issues/1608
> stree: prevent matching invalid wildcards in subject

- server/sublist.go
Otherwise the cache might end up with multiple cache entries sharing the same underlying memory.
> Don't cache `SublistResult` if from `MatchWithResult` call

- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
- server/test_test.go
We shouldn't step down if the append entry contains old terms, it may just be still in-flight from a distant node that is still behind. We also shouldn't clear the vote when leader unless we've definitely seen a newer term and not just the existing term, otherwise we could cast multiple votes.
> NRG: Don't step down for old terms in AEs

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
Since our meta state is technically optional, do not adversely effect normal operations if writing the state out would take too much time. We will force a write on a stop, e.g. server shutdown etc.
Also includes fix to recovery of partial last block to not force full recovery.
> [IMPROVED] Do not write out meta state for filestore if it would block normal operations for too long.

- server/raft.go
Otherwise we might blow away a part of the log and still have to abandon the catchup anyway, which doesn't feel ideal.
> NRG: Don't truncate WAL during catch-up until after peerstate/snapshot check

- server/filestore.go
- server/memstore.go
- server/sublist.go
- server/sublist_test.go
This may end up being more efficient than `MatchWithResult()` in some cases as we will stop processing on the first match and not spend time building up a `*SublistResult`. May want to give more thought on the caching here — right now it checks the cache, but `HasInterest()` won't populate it, only `Match()` will.
/cc @kozlovic 
> Implement `(*Sublist).HasInterest()`

- server/raft.go
- server/raft_test.go
With the current behaviour, a node that is behind but running in the candidate state could cause nodes that are current to delay switching to the candidate state themselves because they keep resetting the election timer each time they receive a vote request.
Changing this to reset the election timeout only when granting means that we will allow other possibly more up-to-date nodes to transition to the candidate state faster.
This might explain why we've seen some unexpected delays in starting a new election after a leader has gone away.
> NRG: Only reset election timeout on vote request if granting

- server/jetstream_consumer_test.go
- server/stree/dump.go
- server/stree/node.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node4.go
- server/stree/stree.go
- server/stree/stree_test.go
- server/stree/util.go
With fixed prefixes this would cause the tree to be broken and find to not work and match would work but with shortened subjects. Could not fix up with fixed prefix arrays when delete caused a non-leaf node to merge a larger prefix.
Changed to normal []byte slice for meta node prefixes.
> [FIXED]  Stree Find() would fail if delete caused a new prefix that was too large.

- server/filestore.go
Adds some extra logging to writeFullState and enforceMsgPerSubjectLimit to detect when they take took long.
> Add logging to measure writeFullState and enforceMsgPerSubjectLimit

- server/raft_helpers_test.go
- server/raft_test.go
Fixes a race that was picked up by the race detector.
> Fix race condition in `TestNRGUnsuccessfulVoteRequestDoesntResetElectionTimer`

- server/stree/node.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node4.go
The `isLeaf`, `base`, `setPrefix`, `numChildren`, `path` and `matchParts` functions all have the same implementation for each node type, so this cuts them down to a single copy.
The leaf type will continue to override these as normal with its own implementations.
> Deduplicate some `stree` functions

- server/raft.go
This PR doesn't change any logical behaviour, it just removes unnecessary `fpae` and `original` variables/steps.
> NRG: Tidy up `applyCommit`

- server/accounts.go
`Readloop processing time` on routes would appear sporadically waiting to get the server lock via `AccountResolver()` even if one is not setup.
```
[32554] 2024/04/24 21:10:23.683892 [WRN] 127.0.0.1:6222 - rid:2631 - Readloop processing time: 2.95526175s
ACCOUNT RESOLVER LOCK TOOK 1.830271834s
[32554] 2024/04/24 21:10:23.719838 [DBG] RAFT [sAhlEnh5 - S-R3F-qADugAfB] Not switching to candidate, observer only
goroutine 32490 [running]:
runtime/debug.Stack()
...
github.com/nats-io/nats-server/v2/server.(*Server).AccountResolver(0x140001a6d80)
github.com/nats-io/nats-server/server/accounts.go:3152 +0xc0
github.com/nats-io/nats-server/v2/server.(*client).processRemoteSub(0x1411e713300, {0x142afef46c4, 0x22, 0x104c59a5c?}, 0x0)
github.com/nats-io/nats-server/server/route.go:1362 +0x5ac …
```
> Change AccountResolver() to use RLock

- server/sublist.go
- server/sublist_test.go
I made an incorrect comment previously about not needing to check the cache's result to know if there is a match. I added a test for that, but also discovered that there was an issue where `HasInterest()` would incorrectly return true if checking for `foo` when there is only a subscription on `foo.*`. Added more tests.
> Fixed `(*Sublist).HasInterest()`

- server/subject_transform.go
- server/subject_transform_test.go
Adding Left and Right operations to Mappings enabling the ability to group by token beginnings and endings.  
Example: 
foo.*: foo.{{Right(1,2)}} -> foo.1234 -> foo.34
foo.*:foo.{{Left(1,2)}} -> foo.1234:  -> foo.12
Signed-off-by: Stephen Spates <sspates@starbucks.com>
> Added Left and Right Mapping Operations

- server/client.go
- server/gateway.go
- server/gateway_test.go
- server/route.go
If the first INFO never makes it back and for some reasons the remote also does not close the connection, or connection is half closed, the outbound would not have detected that the connection is stale.
The outbound connection cannot send PING before it receives the INFO from the remote because that is only when the outbound sends the CONNECT. But the remote will fail if the first protocol from an outbound is not CONNECT.
Using the same principle that we used for routes with compression enabled, where PINGs cannot be sent until a certain time in the handshake, we will use the ping timer to simply close the connection as stale if the ping timer has not been reset before the time needed to send the max number of pings.
Resolves #5349
> [FIXED] Gateway: Outbound may fail to detect stale connection

- server/server_test.go
- test/test.go
Setting this environment variable forces NATS Server instances running in the unit tests to log to stdout. Possible values are:
* `NATS_LOGGING=true go test ...` (or any other non-empty value)
* `NATS_LOGGING=debug go test ...`
* `NATS_LOGGING=trace go test ...`
> Add `NATS_LOGGING` test helper

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
- server/store.go
We had a bug that would overwrite the sync subject during parallel stream creation which would cause upper layer stream catchups to fail on server crash and subsequent restarts.
We also were reporting first sequence mismatch when we hit max retries to force a reset but this was misleading, so added in proper error for max retires limit.
Also on some extreme kill and restart cases our internal checks were being called before complete state was achieved, so delay the initial check and added in periodic checks to ensure replica consistency.
> [FIXED] Stream catchup would not sync after server crash and restart.

- server/accounts.go
- server/client.go
- server/consumer.go
- server/filestore.go
- server/gateway.go
- server/gateway_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/route.go
- server/store.go
- server/subject_transform.go
- server/subject_transform_test.go
- server/sublist.go
- server/sublist_test.go
* https://github.com/nats-io/nats-server/pull/5351
* https://github.com/nats-io/nats-server/pull/5353
* https://github.com/nats-io/nats-server/pull/5337
* https://github.com/nats-io/nats-server/pull/5356
* https://github.com/nats-io/nats-server/pull/5361
* https://github.com/nats-io/nats-server/pull/5362
> Cherry-pick PRs for 2.10.15-RC.3

- server/filestore.go
- server/norace_test.go
In cases where max per subject is utilized, once that condition is hit storing a new message involves writing the new one, flushing it, then determining the current first seq for the subject so we can remove it. Determining the first sequence for the subject could involve walking multiple blocks and loading them in as well, all while the filestore lock is being held causing delays for other access to the filestore, even for things like FastState().
> [IMPROVED] Do not hold filestore lock on msg block loads for firstSeqForSubj.

- server/jetstream_cluster_2_test.go
- server/jetstream_sourcing_scaling_test.go
- server/stream.go
- Resets the stalling detection timestamp upon re-creating the consumer
- Adjust the idle heart beat for source/mirror consumers from 1s to 5s
> Improve stream sourcing consumers stall handling

- server/stream.go
- Add comments to document main structure field names a bit better and improve the code accessibility.
- Rename setSourceConsumer to setupSourceConsumer (better and matches setupMirrorConsumer).
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
> Document struct field names in stream.go

- server/stream.go
Move cancelMirrorConsumer call inside the locked section in retryMirrorConsumer
> Move cancelMirrorConsumer call inside the locked section in retryMirrorConsumer

- server/jetstream_cluster.go
We were seeing degraded performance and possible memory bloat on small messages being compressed for replication in NRGs. This updates the threshold to 8k vs 256.
> [IMPROVED] Up the compression threshold

- server/filestore.go
- server/filestore_test.go
For certain streams that have a large subject space and max msgs per subject with moderate to high ingress rates and very large subjects, holding onto a message blocks can cause undue memory pressure and GC issues.
> [IMPROVED] Put a maximum on the idle flush time for the mb.fss.

- server/jetstream_cluster_4_test.go
- server/stream.go
Small improvement to the handling of sourcing into a WQ/Interest stream with a limit and discard new.
Avoids re-scanning the stream to find the consumer's starting sequence number for that source every time. Do not log a warning every time this happens as it becomes constant log spam for something that happens temporarily all the time.
Strengthen test TestJetStreamClusterSourceWorkingQueueWithLimit to also check the payload (to catch for example the same message being sourced more than once, or messages not getting sourced).
> [IMPROVED] Handling of sourcing into a WQ/Interest streamwith a limit and discard new

- server/filestore.go
- server/filestore_test.go
Updated subject state expiration to be handled by individual block cache expiration logic.
Also added in additional filestore config to control this if needed, still defaults to 10s.
> [IMPROVED] Updated subject state expiration 

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_sourcing_scaling_test.go
- server/stream.go
Includes:
- https://github.com/nats-io/nats-server/pull/5366
- https://github.com/nats-io/nats-server/pull/5359
- https://github.com/nats-io/nats-server/pull/5369
- https://github.com/nats-io/nats-server/pull/5371
- https://github.com/nats-io/nats-server/pull/5370
- https://github.com/nats-io/nats-server/pull/5377
- https://github.com/nats-io/nats-server/pull/5372
> Cherry-pick PRs for 2.10.15-RC.5

- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/norace_test.go
- server/stream.go
More often we are seeing filtered sources and mirrors, and on server restart they could take time to calculate num pending.
> [IMPROVED] Raise the timeout for consumer creation requests for sources and mirrors.

- server/filestore.go
- server/filestore_test.go
We were expiring the fss through forced expire and we were not properly tracking the actual access activity. When we call ensurePerSubjectInfoLoaded() it will mark activity. If we load manually to check for forced expires we mark manually.
> [IMPROVED] Added in separate last subject timestamp to track access and use of mb.fss

- server/consumer.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
When deleting a consumer, messages that lost interest would be deleted from the stream.
The same would not happen for messages that lost interest due to a consumer `FilterSubject` update.
This PR fixes that by extracting the cleanup logic that happened on delete and reuse it on update.
The tests are trimmed down versions of the unit test described here: https://github.com/nats-io/nats-server/issues/4878#issuecomment-2025831232.
These are duplicates of each other, apart from the `Replicas: 3` for the clustered setup (and of course in `jetstream_test.go` vs `jetstream_cluster_4_test.go`).  Please let me know if and how those should be deduped if you'd prefer them to be. :slightly_smiling_face: 
Resolves https://github.com/nats-io/nats-server/issues/4878 …
> Fix cleanup of messages that lost interest after consumer FilterSubject update

- server/consumer.go
- server/jetstream_cluster_3_test.go
Saw TestJetStreamClusterWorkQueueAfterScaleUp locking up, so adjusted the leader check to the atomic bool.
> [IMPROVED] Check consumer leader status without locks.

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_helpers_test.go
- server/jetstream_sourcing_scaling_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/raft.go
- server/stream.go
We were struggling with inbound performance from a large number of streams, and were not properly getting all messages when our stream had a leader change.
The general issue with performance was that we had a go routine per source pulling from individual internal message queues. If we were behind and catching up, or if all sources were receiving messages in a quick fashion, we would be very slow. This was due to us lighting up all the go routines and hence kernel threads only to contend on locks and then IO. So were were thrashing.
We now mux all sources into a single processing go routine with a shared internal message queue.
During testing there were other optimizations that were realized as well.
@jnmoyne also did some restructuring of the sourcing code to make it more understandable …
> [IMPROVED] Streams ingest performance with many stream sources.

- server/accounts.go
- server/client.go
- server/jwt_test.go
- server/monitor.go
- server/route.go
Moved account expired check to atomic.
Slightly increased cache size and floor threshold for route acc result cache. Make sure to prune first, then add new entry to avoid immediate recycling. Also moved account lock to read lock for selectMappedSubject.
> [IMPROVED] Improve mux'd routes with large subject space.

- server/events_test.go
- server/server.go
Saw a data race in Travis during a websocket test during shutdown:
```
Write at 0x00c004430618 by goroutine 112330:
github.com/nats-io/nats-server/v2/server.(*Server).Shutdown()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2527 +0x87e
github.com/nats-io/nats-server/v2/server.TestWSTLSConnection.deferwrap1()
/home/travis/gopath/src/github.com/nats-io/nats-server/server/websocket_test.go:2223 +0x33
runtime.deferreturn()
/home/travis/.gimme/versions/go1.22.2.linux.amd64/src/runtime/panic.go:602 +0x5d
testing.tRunner()
/home/travis/.gimme/versions/go1.22.2.linux.amd64/src/testing/testing.go:1689 +0x21e
testing.(*T).Run.gowrap1()
/home/travis/.gimme/versions/go1.22.2.linux.amd64/src/testing/testing.go:1742 +0x44
Previous read at …
```
> [FIXED] Data races websocket/shutdown, DisconnectClientByID and LDMClientByID

- server/client.go
- server/websocket.go
- server/websocket_test.go
PR #4255 added code in generateClientInfoJSON to set the proper info Host/Port/TLSAvailable/TLSRequired fields to send to clients.
However, this was requiring a lock but more importantly was computing the listener's host/port everytime, which is not necessary since this is immutable because we don't support the change during a config reload.
Also, the TLSRequired field was set based on the server TLSConfig's InsecureSkipVerify value, which is irrelevant for a server. The mere presence of a TLSConfig (c.srv.websocket.tls being true) is enough.
I have modified the TestWSReloadTLSConfig test to verify that the tls block cannot be removed and no_tls set to true, which means that tls value can't change. I also added check for the info's Host/Port/TLSAvailable/TLSRequired values.
Signed-off-by: …
> [IMPROVED] Websocket: generating INFO to send to clients

- go.mod
- go.sum
- server/auth.go
- server/client.go
- server/client_test.go
- server/server.go
With the JWT library update, there is now a `jwt.ConnectionTypeInProcess` connection type that can be added to the list of allowed connection types when defining an user. If the list is not empty and does not have this type, an "in process" connection will not be allowed.
Conversely, it is now possible to limit a user to be used only for in process connections (or several types based on the content of the list).
Possible solution for #5387
> [ADDED] Allowed connection type "in process"

- conf/lex.go
- conf/parse_test.go
- server/server_test.go
We had a bug that was reported that was not handling a block scope where the terminating '}' was on a new line.
Resolves: #5396 
> [FIXED] Fix to properly deal with block scopes in lexer.

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_4_test.go
Under some conditions during a rollout, messages that were already acked or double acked (ack sync), would have been redelivered to a consumer.  Also includes fixes for `TestJetStreamClusterScaleConsumer` for consumer rescaling.
> Fix acked messages being sometimes redelivered during rollouts 

- server/jetstream_cluster.go
- server/stream.go
Most of these were introduced by consideration of an atomic for leader status. This approach was abandoned.
> [FIXED] Fix for data races in stream.

- server/config_check_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
Added the leafnode remote configuration parameter `first_info_timeout`
which is the amount of time that a server creating a leafnode
connection will wait for the initial INFO from the remote server.
Resolves #5417
> [FIXED] LeafNode: connection may fail on slow link

- server/filestore.go
- server/filestore_test.go
> [FIXED] Make sure to hold onto tombstones for previous blocks on compact and to set needSync.

- server/jetstream_cluster_2_test.go
- server/raft.go
1. Pull term from tav.idx even with no voted peer on recovery.
2. If we have no pterm or pindex after recovery inherit from empty WAL and tav.idx.
3. Clear wtv if we fail to write the tav.idx file.
Also fixes flapper test with removing snapshots and block state.
> [IMPROVED] Several improvements to raft layer with limited or no state.

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/stream.go
Includes improvements for streams rescaling:
- When scaling up and down we keep same leader so no reason to tear everything down and then back up.
We do make sure when we scale down to one to tear down cluster specific subs etc.
> Fixes for rescaling streams with sources

- conf/lex.go
- conf/parse_test.go
- go.mod
- go.sum
- server/client.go
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_4_test.go
- server/raft.go
- server/server_test.go
- server/stream.go
- server/websocket.go
- server/websocket_test.go
* #5405
* #5406
* #5413
* #5419
* #5420
* #5426
* #5427
* #5428
> Cherry-picks for 2.10.15-RC.11

- conf/lex.go
- conf/parse_test.go
> [FIXED] Fix for the block lexer

- server/jetstream_cluster.go
> [FIXED] Avoid overflow of rand.Intn on 32bit platforms

- .travis.yml
This will make the next release use Go v1.22 instead when the next version is tagged.
> Use Go v1.22 in v2.10 releases

- conf/lex.go
- go.mod
- go.sum
- server/routes_test.go
- server/server.go
Includes:
- https://github.com/nats-io/nats-server/pull/5437
- https://github.com/nats-io/nats-server/pull/5436
- https://github.com/nats-io/nats-server/pull/5444
> Cherry-picks for 2.10.16-RC.1

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
When the first ack was called on an AckAll consumer attached to a stream with a very high first sequence, the server would become unresponsive for that consumer and potentially the stream due to looping down to the existing ackfloor which in this case would be zero.
> [IMPROVED] Consumer with AckAll performance of first ack with large first stream sequence.

- server/msgtrace_test.go
This test was flapping because the order of events are not guaranteed. Made a fix to ensure we have all the expected events (regardless the order they are received).
> Fixed TestMsgTraceJetStreamWithSuperCluster test

- server/consumer.go
- server/filestore.go
- server/jetstream_test.go
Make sure to not run away when acking from the middle of pending.
Also optimize loop for interest based streams to ack msgs based on actual floor of pending.
> [IMPROVED] First ack with large first sequence and not acking highest pending.

- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_helpers_test.go
- server/memstore.go
- server/norace_test.go
- server/raft.go
- server/stream.go
Various improvements to catchup logistics.
1. Make sure to register our sync sub earlier to avoid missing an early request for catchup on a scaleup.
2. Make sure we send trailing delete range blocks to avound getting stuck during catchup.
3. When parallel catchups running make sure to periodically check to see if we can send next batch since we could be blocked on others and not ourselves.
4. When catching up a stream that has a large number of interior deletes use LoadNextMsg() to more efficiently skip over large gaps.
5. When resuming apply queues in raft layer do not unpause our state until after processing to avoid possible elections under heavy load.
6. when syncing deleted blocks from snapshots only consider those applicable to our state.
Signed-off-by: Derek Collison …
> [IMPROVED] Various stream catchup improvements

- server/events.go
Avoids adding too many of these log entries while shutting down:
```
[S-2] | 2024/05/20 14:13:41.830762 [INF] JetStream cluster new consumer leader for 'js > test:13 > A:13:3'
[S-3] | 2024/05/20 14:13:41.868975 [INF] Initiating Shutdown...
[S-3] | 2024/05/20 14:13:41.868986 [INF] Initiating JetStream Shutdown...
[S-3] | 2024/05/20 14:13:41.869519 [WRN] Advisory could not be sent for account "js": system account not setup
[S-3] | 2024/05/20 14:13:41.869757 [WRN] Advisory could not be sent for account "js": system account not setup
[S-3] | 2024/05/20 14:13:41.870164 [WRN] Advisory could not be sent for account "js": system account not setup
[S-3] | 2024/05/20 14:13:41.870600 [WRN] Advisory could not be sent for account "js": system account not setup
[S-3] | 2024/05/20 14:13:41.870691 [WRN] …
```
> Skip trying to send system events just before shutdown

- server/stream.go
This will improve observability on the `mset.internalLoop()` in profiles.
> Add goroutine annotation for stream internal loop

- server/raft.go
- server/raft_test.go
If the file ends up truncated somehow then we should not try to call `Uint64`, otherwise it will result in an out-of-bounds panic.
> NRG: Avoid panic on corrupted TAV file

- server/jetstream_cluster.go
- server/memstore.go
- server/memstore_test.go
- server/stream.go
Optimize NumPending for memstore when large number of interior deletes are present.
Also as we periodically check interest state for interest policy streams and consumers, if we have zero ack consumers do not hold stream lock while checking.
> [IMPROVED] Memstore NumPending() and checkInterestState. 

- server/raft.go
- server/raft_test.go
A node that has been isolated in the candidate state for a considerable amount of time might have bumped its vote term up considerably due to a number of failed election attempts, so when the network recovers, new AEs would not trigger a stepdown. Instead, check the `pterm`, which is the term of the last entry in our log, as this will not have ratcheted up during the period of isolation.
> NRG: Stepdown candidate when AE ahead of last log term

- server/consumer.go
- server/jetstream_cluster_4_test.go
Sometimes during rollout restarts, retrying quickly a previously failed ack could succeed but still the consumer would get the message being redelivered.  To prevent this it is now checked if an inbound ack on takeover is ahead of the consumer stream sequence.
> Fix message being redelivered after successful ack on rollout restarts

- server/events.go
- server/events_test.go
- server/jetstream_super_cluster_test.go
This PR adds a filter to `sendStatsz` that limits statsz updates to the current heartbeat interval (max once per second), adding a `time.Time` field to track the time the last statsz update was sent. This limit should reduce overall `STATSZ` system event load in large clusters while still allowing initial statsz update to quickly reach newly-discovered nodes.
Fixes #5469.
Signed-off-by: Will Jordan <will.jordan@gmail.com>
> Limit statsz updates

- .travis.yml
This updates the `goreleaser` Go versions.
> Update to Go 1.22.4, 1.21.11

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
This will fix #5488 by doing two things:
1. Only enforcing the max consumer count on consumer create or create-or-update requests;
2. Not incorrectly counting a potentially existing matching consumer on create-or-update requests.
Note this only happens in clustered mode, on a single node system this does not happen.
> Fix returning `maximum consumers limit reached` on some consumer updates

- util/nats-server-hardened.service
In commit c7887427 I made various updates to one of the example systemd service
scripts, but one change causes breakage if and only if the service file is
itself named `nats.service` when installed.
We now know that some folks are doing just that, automatically; it's bad to
have a config file which only works if it has certain names (and a little
surprising that systemd doesn't detect that the alias matches its current name
and filters).
So turn that directive into a commented-out suggestion.
> systemd example: reduce risk of naive breakage

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/server.go
- server/signal.go
When we had skip msgs on the last msg block we were not writing proper tombstone markers if the block was empty.
Also no checksum should match no recorded block checksum to pull in metadata from index.db.
Also we will now wait for all async processes to complete on shutdown from signal handlers and lameduck mode.
> [FIXED] Last sequence stream reset on server restarts

- server/jetstream_cluster.go
> Fix data race between `processClusterCreateConsumer` and `resetClusteredState`

- locksordering.txt
- server/accounts.go
- server/leafnode.go
There is a possibility this might happen if `reConnectToRemoteLeafNode` from a connection drop and `connectToRemoteLeafNode` from solicitation are running in separate goroutines for the same remotes.
> Prevent interleaving of setting/unsetting observer states with `jetstream_cluster_migrate`

- server/jetstream_sourcing_scaling_test.go
- server/raft.go
- server/stream.go
Because leadership status can sometimes change very quickly and raft.updateLeadChange() can 'drop' some lead change signals, especially with the leadc channel having a capacity of one, which means that sometimes stream.setLeader(isLeader bool) gets called twice in a row with the same isLeader value.
This could lead to in some cases the sourcing to 'stall' (not all messages gets sourced) or 'duplicate messages' (more messages than expected get sourced).
Changes are increasing the leadc channel's size to 32.
The effects of the change can be demonstrated by running the TestStreamSourcingScalingSourcingManyBenchmark load test a large number of times (e.g. 100 times): without these changes the test flaps and fails between 10 and 20% of the time (most of the time 'stalling' but also sometimes …
> Improve leadership change signaling

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/memstore.go
- server/memstore_test.go
- server/monitor.go
- server/norace_test.go
- server/raft.go
- server/stream.go
Improvements to catchups and health checks.
Improvements to handling snapshots for memory based wals.
With memory based wals we can not use snapshots on restarts, but we do use them while they are running.
However if a server becomes a leader with no snapshot it will be forced to stepdown when asked to catchup a follower. So we now inherit a leaders snapshot.
Also when we tried to truncate on a mismatch, we needed to truncate the previous index, not current.
When we fail due to the previous entry being compacted away, we would reset. We now reset the wal to the prior index and use the truncate term and index.
Lastly if we receive a heartbeat with correct index but newer term just inherit.
For stream health checks for replicated streams make sure that the monitor routine is running.
When …
> [IMPROVED] Memory based streams and NRG behavior during server restarts

- server/monitor.go
Got removed while applying last cherry pick so adding it back with the expected behavior for v2.10.X.
> Fix js-server-only health check on v2.10.17

- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
> Added in memory based raft tests. Updated some raft comments.

- server/jetstream_leafnode_test.go
- server/raft.go
- server/raft_test.go
Previously if `runAsFollower` or `PauseApply` had ran while in observer state, i.e. due to `jetstream_cluster_migrate` being set when leafnode connections dropped, then the election timer would have been reset to a very high value. Then leaving observer state wouldn't have noticed the lack of a leader for some time. This fix allows a leadership election to take place very quickly after leaving observer mode.
> NRG: Reset election timer when leaving observer mode

- server/stree/leaf.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node4.go
Saves:
* 16 bytes per `leaf`
* 24 bytes per `node4`, `node16` and `node256`
> Re-order struct fields in `stree` for improved memory alignment

- server/client.go
- server/leafnode_test.go
> [FIXED] Only forward shadow subs if we are not a leafnode or a hub leafnode client

- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_jwt_test.go
- server/stream.go
We were not taking into account that consumers could be a different tier for limits or tracking usage.
> [FIXED] Proper tiered accounting for consumers with a different tier than parent stream.

- server/stream.go
> [FIXED] Fix for segfault if mset.mirror was nil when calculating last

- .travis.yml
- server/client.go
- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_jwt_test.go
- server/jetstream_leafnode_test.go
- server/leafnode_test.go
- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
- server/stream.go
- server/stree/leaf.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node4.go
* #5515
* #5516 
* #5517
* #5519
* #5514 
* #5521 
* #5522 
> Cherry-picks for 2.10.17-RC.3

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_1_test.go
- server/memstore.go
For a leader, it will skip msgs at the end to eof and remember o.sseq for the next getNextMsg call.
But this will report stream delivered different for the leader vs the followers.
Also if a consumer leader processed an ack ahead of delivered it would sync, but followers would not.
This makes the behavior consistent between leaders and followers.
> [FIXED] Make sure jsz reporting of filtered consumers delivered stream sequence is consistent.

- server/filestore.go
- server/filestore_test.go
- server/test_test.go
If the per-subject info didn't have a correct first block (which is possible as it is populated lazily), then `LoadNextMsg` could end up making a very expensive call through to `numFilteredPending` which would do a linear scan of potentially many blocks.
> Fix linear scan in `LoadNextMsg` with partial per-subject info state

- server/filestore.go
- server/jetstream_cluster_1_test.go
- server/memstore.go
Make these consistent from leaders and followers regardless of store type. Fixed a bug that would have followers stores inherit redelivered consumer delivered sequence which would break ack gap fill.
> [FIXED] Align ack gap fill from leaders to followers.

- .travis.yml
The new installer depends on a recent version of `cosign` being installed so just fetching the v1 release manually for now.
> Fix using goreleaser v1, fetch without installer script

- server/consumer.go
- server/norace_test.go
- server/raft.go
- server/stream.go
With skipMsgs calling ProposeDirect, if the prop queue was not empty this would place the skip entry ahead of the other entries. This would result in sequence mismatch and stalled processing.
Bug was we should not bypass the internal prop ipq for the nrg. This corrects it and renames to ProposeMulti.
> [FIXED] ProposeDirect would bypass internal prop ipq which could cause interleaving of state.

- server/filestore.go
- server/filestore_test.go
When we skip blocks in numFilteredPending make sure to update psim entries fblks.
> [IMPROVED] Update psi.fblk when outdated in numFilteredPending.

- server/consumer.go
- server/jetstream_cluster_1_test.go
When we delete a consumer we need to simulate acking all messages from the ackfloor to the last sequence in the stream. If the consumer is new and only consumed and acked and few messages, or none, this could be costly and cause operational pauses for the parent stream.
If the number of sequences we would need to process is obver a threshold we will let the checkInterestState() do the cleanup in a separate Go routine.
> [IMPROVED] Consumer delete time on interest policy streams with a large number of messages.

- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/stream.go
For subjects `$JS`, `$JS.API`, `$JSC` and `$SYS` subjects, If NoAck is true they are now allowed, otherwise they will not be allowed.
This allows proper setup of audit streams for production use cases.
> Formalize behavior for creating audit streams for reserved subjects.

- server/monitor.go
- server/server.go
We often find ourselves without good visibility into what's really going on in the Raft layer. This endpoint dumps quite a substantial amount of internal Raft node state.
Filters include:
* `?acc=ACCNAME` to filter by account (defaults to system account if not specified)
* `?group=GROUP` to show only specific groups
> Add `/raftz` monitoring endpoint

- server/jetstream_cluster_3_test.go
- server/stream.go
On a bad snapshot restore, e.g. R3 on single server, make sure to remove the restored stream since otherwise it would cause bad healthz reports.
> [FIXED] On failed snapshot restore make sure healthz is clean.

- server/raft.go
The `state` is not used here. 
Signed-off-by: Jay Chung <ken8203@gmail.com>
> refactor(raft): remove unused code

- server/jetstream_test.go
- server/stream.go
> Allow for audit exception for `$JS.EVENT.>` and `$SYS.ACCOUNT.>` which may already exist.

- server/raft.go
Previously (but not in released code) we were cleaning up all old ones in a go routine. However this could cause multiple go routines to race and delete the wrong snapshot leaving none available.
> When installing a new snapshot remove last inline if present.

- server/accounts.go
- server/auth.go
- server/auth_callout_test.go
- server/client.go
[FIX] added logic to enable users generated by a callout to be revoked - the callout is responsible to map the user ids for revocation purposes.
Fix #5477
> Allow callout users to be revoked

- server/events.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/raft.go
- server/stream.go
* #5552 
* #5557
* #5556
* #5558
> Cherry-picks for 2.10.17-RC.5

- server/client.go
- server/raft_test.go
Internal clients for NRG (Raft Groups) were of type SYSTEM and were not being removed from the system's account when they were closed, causing a leak of closed client connections and memory buildup.
Resolves: #5471 
> [FIXED] Make sure to always remove internal clients from the account regardless of kind.

- server/filestore.go
This is to avoid thrashing on sparse streams and streams that hit max msgs limits where we have to remove the first that nay be in a totally different block.
> [IMPROVED] Increase cache invalidation times for mb.cache.buf and mb.fss.

- server/client.go
- server/filestore.go
- server/raft_test.go
> Cherry-picks for 2.10.17-RC.6

- server/filestore.go
- server/memstore.go
Otherwise long subjects could cause us to make the same reallocations on each call to `tokenizeSubjectIntoSlice` without reusing the newly sized underlying array for the next call.
> Reduce allocations in `isMatch` in filestore/memstore

- server/mqtt.go
- server/mqtt_test.go
MQTT s.clear(): do not wait for JS responses when disconnecting the session
Related to https://github.com/nats-io/nats-server/issues/5471
Previously we were making `jsa.NewRequest` as it is needed when connecting a clean session. On disconnect, there is no reason to wait for the response (and tie up the MQTT read loop of the client).
This should specifically help situations when a client app with many MQTT connections and QOS subscriptions disconnects suddenly, causing a flood of JSAPI deleteConsumer requests.
Test: n/a, not sure how to instrument for it.
> [CHANGED] MQTT s.clear() do not wait for JS responses when disconnecting the session

- server/filestore.go
- server/filestore_test.go
This improves our updating of the outdated fblks when calling into fs.numFilteredPending()
> [IMPROVED] Updating out of date fblks in psim entries.
