nats-io/nats-server

- server/filestore.go
- server/filestore_test.go
Bug was that new wildcard matching code would not reverse start and stop, which is needed since we walk backwards. Since they were not flipped as soon as start != stop, it would not enter the loop condition, e.g. start:1, stop:2 fails start >= stop.
Only existed in 2.10.17-RC4 and beyond, not in previous releases.
> [FIXED] Fixed bug that would return no msg found for loadLast.

- server/filestore.go
- server/filestore_test.go
Should provide some deduplication of long subjects in memory when message blocks are loaded in.
> Use stree for message block `fss`

- server/stree/dump.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node48.go
- server/stree/stree_test.go
A `node256` is nearly 4KB in memory whereas a `node48` is closer to 1KB, so there is a potential for anywhere up to 75% memory savings in some subject spaces.
Implemented as per the ART paper, although with the caveat that our pointers are actually 16 bytes (as `interface{}`s) rather than 8 bytes as the paper assumes:
> Node48: As the number of entries in a node increases, searching the key array becomes expensive. Therefore, nodes with more than 16 pointers do not store the keys explicitly. Instead, a 256-element array is used, which can be indexed with key bytes directly. If a node has between 17 and 48 child pointers, this array stores indexes into a second array which contains up to 48 pointers. This indirection saves space in comparison to 256 pointers of 8 bytes, because the indexes …
> Add `node48` to stree

- server/raft.go
- server/raft_test.go
Previously, if the applies were paused (i.e. due to an on-going catchup) then calls to `SetObserver(...)` from other places, i.e. `jetstream_cluster_migrate`, would not leave observer mode after applies were resumed. This could result in assets getting stuck in observer mode.
> NRG: Fix leaving observer state when applies are paused

- server/leafnode_test.go
- server/server.go
Kick was designed for any client connection but was intended to also work on leafnodes. This allows for rebalancing etc.
Resolves: #1556 #5527 
> [FIXED] Allow kick to work on leafnodes as well.

- server/accounts.go
- server/client.go
- server/jwt_test.go
- server/server.go
With this change we do not need lookup from tmpAccounts on import processing.
Needed to fix data races from same tmpAccount entry now be re-used.
> [FIXED] Make sure tmpAccounts does not accidentally have duplicates.

- server/accounts.go
- server/client.go
- server/jwt_test.go
- server/server.go
When a client would reconnect to a server that was still setting up the imports and exports a client that reconnected too soon to a server that had just been restarted might be missing some of the imports that were defined in its JWT.
> Fix imports not being available for a client sometimes after a server restart

- server/accounts.go
- server/client.go
- server/filestore.go
- server/filestore_test.go
- server/jwt_test.go
- server/leafnode_test.go
- server/raft.go
- server/raft_test.go
- server/server.go
- server/stree/dump.go
- server/stree/node16.go
- server/stree/node256.go
- server/stree/node48.go
- server/stree/stree_test.go
- server/test_test.go
Includes:
- #5584
- #5585
- #5586
- #5587
- #5589
> Cherry picks for v2.10.17-RC.8

- server/jetstream_cluster.go
Fixes #5594. Otherwise it prints a very unhelpful error that doesn't tell you which account is at fault.
> Fix logging when exceeding JetStream account limits

- server/client.go
- server/filestore.go
- server/jetstream_cluster.go
- server/raft.go
Fix for situations where GC struggled to clean up things.
This mostly stemmed from subscriptions being held in per connection caches (routers and gateways). These held references to both clients and any internal callbacks, which usually were closures so would also hold reference to the struct target as well.
> [FIXED] Memory growth from NRG create and delete operations 

- server/client.go
- server/filestore.go
- server/jetstream_cluster.go
- server/raft.go
Includes:
* #5593
* #5597
* #5600
> Cherry-picks for 2.10.17-RC.9

- server/stree/stree.go
- server/stree/stree_test.go
On a full wildcard `Match`, we were iterating through children but then also falling through to a regular continuation instead of returning, which meant that the `Match` callback could fire twice for the same filter.
Fixes #5608.
> stree: Fix duplicate callbacks on full wildcard `Match`

- server/filestore.go
- server/stree/stree_test.go
This PR contains some bug-fixes for the filestore FSS state.
First, if the filter provided is `_EMPTY_` then we need to overwrite it to `>` for the stree functions to work, but we failed to set `wc` when doing so. This could affect the decision on whether to linear-scan or not. We will now set `wc` too in this case.
Second, if the FSS only contains a single subject then we may not correctly set `isAll` if the filter contained a wildcard, as `Find` does not work with wildcards and therefore wouldn't match the single subject. Updated to use `Match` instead, so that it correctly uses wildcards.
Third, replaces `Match(>)` with `Iter` in `enforceMsgPerSubjectLimit`, not because it is behaviourally different, but because we need to walk the entire stree anyway and `Iter` saves CPU cycles by …
> Fixes for filestore FSS state

- server/consumer.go
- server/memstore.go
When recalculating for the first, make sure not to trip accidentally with a negative npc, and make sure to floor against first sequence as needed.
Resolves: #5621 5621
> [IMPROVED] CPU spike during recalc of first msg in memstore.

- server/filestore.go
- server/filestore_test.go
This would cause LoadNextMsg() to return EOF incorrectly.
> [FIXED] checkSkipFirstBlock could return negative index if psim.fblk outdated.

- server/consumer.go
- server/jetstream_cluster_2_test.go
When checking interest state, make sure to take into account filtered consumers when acking msgs.
We were checking interest state on a leader change but we would ack msgs that may not be applicable to our consumer.
Resolves: #5612 
> [FIXED] Don't ack msgs if we are filtered and they are not applicable.

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
For R1 consumers we used to have the leader set as we called add so was handled there similar to standalone server mode. Now process in same place as R>1 for clustered usage.
> [FIXED] Make sure to send consumer create advisory regardless of node presence.

- server/const.go
Currently we use an `ldflag` to add the git commit from a server version, but this information is already present in many cases such as when building the package or using `go install`.
```
$ go build .
$  ./nats-server 
[90016] 2024/07/15 17:01:31.280879 [INF] Starting nats-server
[90016] 2024/07/15 17:01:31.281050 [INF]   Version:  2.11.0-dev
[90016] 2024/07/15 17:01:31.281054 [INF]   Git:      [dcd20c0]
```
When calling `go run` or `go build main.go` it would be still left unset:
```
go run main.go 
[90162] 2024/07/15 17:02:13.081669 [INF] Starting nats-server
[90162] 2024/07/15 17:02:13.081845 [INF]   Version:  2.11.0-dev
[90162] 2024/07/15 17:02:13.081849 [INF]   Git:      [not set]
```
> Use ReadBuildInfo if available to detect gitCommit

- .goreleaser.yml
- scripts/runTestsOnTravis.sh
- server/const.go
- server/monitor.go
- server/server_test.go
Setting a `serverVersion` variable which is set via ldflags to help security scanners like `syft` detect the version when inspecting the binary.  Goreleaser is modified to set this ldflag and a test is added to make sure that the `VERSION` constant matches the tag from the release.
Result:
```sh
$ export TRAVIS_TAG=v2.10.18
$ go test -race -v -run=TestVersionMatchesTag ./server --trimpath -ldflags="-X=github.com/nats-io/nats-server/v2/server.serverVersion=$TRAVIS_TAG" -count=1 -vet=off
=== RUN   TestVersionMatchesTag
server_test.go:144: Version (2.11.0-dev) does not match tag (2.10.18)
--- FAIL: TestVersionMatchesTag (0.00s)
$ go build --trimpath -ldflags="-X 'github.com/nats-io/nats-server/v2/server.serverVersion=$TRAVIS_TAG'" .
$ syft ./nats-server
NAME …
```
> Add serverVersion var set via ldflags

- server/filestore.go
- server/jetstream_test.go
When we matched all and had no interior deletes we would short circuit num pending calculations but were not accounting for sseq < state.FirstSeq.
> [FIXED] Consumer NumPending higher than total stream messages.

- server/server.go
Otherwise this function isn't available when embedding the NATS Server, where using `SIGUSR2` likely isn't appropriate.
> Export `LameDuckShutdown` so that it is accessible when embedding NATS

- server/events.go
- server/server.go
- server/stree/stree.go
- server/stree/stree_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5662
- https://github.com/nats-io/nats-server/pull/5663
- https://github.com/nats-io/nats-server/pull/5660
> Cherry-picks for 2.10.18-RC.4

- server/errors.go
- server/events_test.go
- server/gateway.go
- server/leafnode.go
- server/opts.go
- server/server.go
- server/server_test.go
- test/leafnode_test.go
Having cluster name with spaces in the context of a leaf node could cause problems when a subscription on the leaf node would be propagated in the cluster's hub.
Since when a gateway is specified the name of the gateway needs to match the name of the cluster, the restriction of "no spaces" is added to gateway name.
Finally, in the case of the leafnode, if no cluster name is specified the server name is used, so also applying the restriction to the server name.
Resolves #5633
> [FIXED/CHANGED] Reject server/cluster/gateway names with spaces

- server/route.go
- server/routes_test.go
- server/server.go
This is an alternate approach to the PR #5484 from @wjordan.
Using the code in that PR with the test added in this PR, I could still see duplicate routes (up to 125 in one of the matrix), and still had a data race (that could have easily be fixed). The main issue is that the increment happens in connectToRoute, which is running from a go routine, so there were still chances for duplicates.
Instead, I took the approach that those duplicates were the result of way too many gossip protocols. Suppose that you have servers A and B already connected. C connects to A. A gossips to B that it should connect to C. When that happened, B would gossip to A the server C and C would gossip to A the server B, which all that was unnecessary. It would grow quite fast with the size of the cluster (that is, …
> [IMPROVED] Routing: reduce chances of duplicate implicit routes

- .travis.yml
This was fixed in the releases branch as well here: https://github.com/nats-io/nats-server/commit/e7a27d19bde421d0729d6ebc6c0128a863bd72b4
> Fixes to goreleaser v1 script

- server/monitor.go
> Fix panic on `/raftz` when shutting down

- server/raft.go
- server/raft_test.go
Many of the follower resets that we see happen because append entries from previous terms can be in-flight during leadership transfers. This problem is worsened when high or variable latency is involved.
When a follower receives an AE from an old term today, they will reset and nuke their WAL and then run a catch-up regardless of the integrity of the log. However this situation ignores the fact that the node might have been otherwise functioning normally and network latency may be worse on some links than others. Silently dropping the AEs from previous terms and restricting the reset behaviour to the last log term and last log index reduces the number of resets considerably whilst maintaining log consistency.
Co-authored-by: Reuben Ninan <reuben@nats.io>
Signed-off-by: Neil Twigg …
> NRG (2.11): Ignore AEs from older terms

- server/raft.go
- server/raft_test.go
A candidate could incorrectly revert to an older term without resetting if an old AE arrived with a term that is at least newer than the pterm but not necessarily newer than the term.
Additionally, we also weren't handling the case that the rest of the cluster should assume the higher term number from the vote requests once an isolated candidate node rejoins the cluster.
This PR also rewrites `TestNRGCandidateStepsDownAfterAE` and replaces it with `TestNRGAssumeHighTermAfterCandidateIsolation` as the old test was checking for flawed behaviour: it was relying on the term being able to go backwards after a period of isolation, which is not correct. Instead we should prove that the rest of the cluster assumes the higher term from the isolated node.
Co-authored-by: Reuben Ninan …
> NRG (2.11): Fix term handling in candidate state and use higher term from vote request

- scripts/runTestsOnTravis.sh
During a release the `TestVersionMatchesTag` test is also run as part of this set of tests.
> Add ldflag to srv_pkg_non_js_tests tests

- server/raft.go
- server/raft_test.go
This ensures that when a Raft node steps down, any items that remain in the proposal or append entry response queues are correctly dropped. Otherwise the group might end up in an inconsistent state if that node becomes leader again.
> NRG (2.11): Ensure proposal and AE response queues drain after stepdown

- server/raft.go
- server/raft_test.go
The stepdown channel interleaves with other channels such as the apply queue, leader change notifications etc in the `runAs` goroutines in an unpredictable order, so processing a stepdown request might be delayed behind other work. Doing this inline should be safer with stronger guarantees.
---
We originally raised this in #4990 (in v2.10.11) and then reverted it in #5200 (in v2.10.12) as it was slowing down some asset moves. This was also visible in the `TestJetStreamSuperClusterDoubleStreamMove` and `TestJetStreamSuperClusterMovingStreamAndMoveBack` unit tests.
We believe that the election timer being too eagerly reset was responsible for a slowdown in establishing a new leader and therefore think that the changes in #5315 will have helped here. Both unit tests don't show any …
> NRG (2.11): Remove stepdown channel, handle inline

- server/raft.go
- server/raft_test.go
Beforehand when we were trying to run a catchup, we were reverting the `term` back to `pterm`. We can't ever move the term backwards safely and the catchup itself does not rely on this behaviour in order to work (as the catchup entries are matched only on `pterm`/`pindex`), so don't revert it.
We saw this behaviour in Antithesis where a catchup could take us back a term. 
> NRG (2.11): Don't revert `term` to `pterm` on AE mismatch

- server/monitor.go
To create tooling and to be able to detect
when ran against old NATS Servers it would
be better if this was a pointer so the absense
of it would indicate unsupported servers rather
than ones that support this feature but have
no limits set
> Make jsz limits optional

- .travis.yml
- go.mod
Follow up https://github.com/nats-io/nats-server/pull/5636
> Remove Go 1.20 from build, force building Go >= 1.21 in go.mod

- go.mod
According to [https://go.dev/issues/62278](https://github.com/golang/go/issues/62278) a concrete go version has to include
the patch number. The project declares the version as 1.21 which is invalid and
will result in an error:
GOTOOLCHAIN="go1.20+auto" go1.21.5 mod tidy
go: downloading go1.21 (linux/amd64)
go: download go1.21 for linux/amd64: toolchain not available
Changed to 1.21.0 as this is the first actual release of go 1.21.
> Fix go directive version in go.mod

- server/raft.go
- server/raft_test.go
Log consistency should only be enforced when handling append entries, not in other types of RPC. In this case, the higher term could cause us to blow away our entire log if a node with a higher term but a more out-of-date log comes along as leader without doing any other checks, and that may force us to vote for another node that's behind as a result.
> NRG (2.11): Don't reset WAL on append entry response

- server/raft_test.go
> NRG (2.11): De-flake `TestNRGSwitchStateClearsQueues`

- server/jetstream_test.go
While validating the ideas in ADR-44 the proposed improvements caught the fact that a snapshot request was being sent to a restore API call. Tests passed because there was enough overlap in the structs but strictly should have been a failure due to the invalid request
> Send the correct struct to the restore API

- go.mod
- go.sum
The 0.9.1 version of this dependency requires Go 1.22 whereas 0.9.0 requires Go 1.20.
We'll bump this back up before the 2.11 release as Go 1.23 will be out by then, so we'll only need to support Go 1.22 and Go 1.23 from that point forward.
> (2.11) Revert to `go-tpm` 0.9.0 due to supported Go versions

- server/events.go
- server/monitor.go
- server/monitor_test.go
Same as previous limits related PR but also adding it to varz, noticed varz didnt have JetStream tests so reworked a few things there to also cover that part of varz
> Export js limits in varz

- server/consumer.go
- server/stream.go
> When checking consumer state for interest policy streams, make sure match filters

- server/consumer.go
- server/jetstream_cluster_4_test.go
- server/stream.go
The `isInterestRetention` function, which gates whether or not we run `checkInterestState`, was matching for both `InterestPolicy` and `WorkQueuePolicy`.
This meant that a work queue stream could throw away messages for which there was no consumer interest as the consumer ack floors for other subjects moved up.
This PR changes `isInterestRetention` to match only `InterestPolicy` which fixes the issue. Notably this doesn't change the `ackMsg` behaviour which will continue to remove messages once they have been acked. 
> Fix `WorkQueuePolicy` retention issue

- server/monitor.go
- server/monitor_test.go
The stream state and replica info is only guaranteed to be accurate when returned by the leader of a given stream. This new option returns stream details only for the stream in which the server is the leader for that stream. For systems with many streams this can significantly reduce the amount of data returned when scraping across all servers since non-leader details will likely be ignored.
Fix #5698
> [jsz] Add StreamLeaderOnly filter option

- server/raft_test.go
> De-flake `TestNRGUnsuccessfulVoteRequestDoesntResetElectionTimer`

- server/raft_test.go
> De-flake `TestNRGSwitchStateClearsQueues`

- server/filestore.go
- server/filestore_test.go
As mentioned in https://github.com/nats-io/nats-server/issues/5705#issuecomment-2254268218, an issue was introduced starting from 2.10.17.
A call to `fs.numFilteredPending(filter, &ss)` was replaced with `nbi := fs.checkSkipFirstBlock(filter, wc)`. But the latter wouldn't handle the case where `filter == _EMPTY_` from a call to `LoadNextMsg`, whereas the former would.
Resolves #5705
> Fix 'checkSkipFirstBlock' with '_EMPTY_' filter

- server/filestore.go
- server/filestore_test.go
When LoadNextMsg misses, make sure to consult psim but conservatively.
We had a use case with millions of subjects and the last sequence checked being in the next to the last block. The consumer had a wildcard that matched lots of entries that were behind where we were. This would burn alot of cpu and when a stream had lots of consumers and they shift leadership this would introduce some instability due to all the cpu cycles.
> [IMPROVED] LoadNextMsg for wildcard consumers with millions of subjects

- server/raft.go
Otherwise we may end up in a situation where we are dropping append entries from a leader that is obviously behind, but we cannot help to bring the cluster forward to make progress.
This resolves the flakiness in `TestJetStreamLeafNodeClusterExtensionWithSystemAccount` in local testing.
> NRG (2.11): Send AE response when term is lower than ours

- server/filestore.go
- server/filestore_test.go
Make sure to account for tombstone in rbytes to avoid potential excessive compact attempts.
Partially resolves:  #5702 
> [FIXED] Excessive blk compacts with delete tombstones.

- server/auth.go
- server/auth_callout_test.go
- server/opts.go
- server/opts_test.go
This introduces a new `auth_callout` field `allowed_accounts` which enables explicitly listing which accounts in the server config should be delegated to the auth callout service.
This improves the current behavior which is an all-or-nothing switch over from config auth to auth callout.
The primary motivation for this change is to enable the system account to authenticate against the server rather than being dependent on the availability of the auth callout service.
(For reference the name `allowed_accounts` [matches what exists in nsc](https://github.com/nats-io/nsc/blob/main/cmd/editauthorization.go#L33))
> [auth-callout] Support opt-in list of accounts to be delegated in config-mode

- server/server.go
- server/server_test.go
Using `net.JoinHostPort()` properly surrounds IPv6 literals with square brackets. Using `url.URL` ensures that hostnames will be properly encoded.
> Ensure `ClientURL()` properly formats IPv6 literal addresses

- server/raft.go
- server/raft_test.go
Candidates should be stepping down based on their term rather than the term number of their last entry.
Signed-off-by: reubenninan <reuben@nats.io>
> NRG (2.11): Fix candidate stepdown logic

- server/filestore.go
- server/filestore_test.go
This will use `O_SYNC` when writing `meta.inf`, `meta.sum` and `meta.key` files for both streams and consumers when the `SyncAlways` filestore option is enabled. It will also do the same when writing the consumer state file, or rewriting it if we are converting between ciphers.
> Use `O_SYNC` for filestore meta files when `SyncAlways` is enabled

- server/accounts.go
- server/auth.go
- server/consumer.go
- server/gateway.go
This reduces allocations and potentially speeds up some hot paths, such as in consumer waiting and gateway reply mapping.
> Use `HasInterest` in place of `Match` where `SublistResult` not needed

- server/client.go
- server/consumer.go
- server/gateway.go
- server/store.go
- server/sublist.go
This should reduce the number of string allocations on some gateway hot paths quite considerably.
Note that `MatchBytes()` passes in a new option to the internal `match()` function to ensure a copy is taken when writing to the cache to ensure we don't create race conditions from memory reuse. This doesn't affect `Match()` so the behaviour there is unchanged.
> Optimise sublist matching for gateways, client replies

- server/accounts.go
- server/client.go
We'll still copy the string when asking the resolver, as we can't be sure whether a resolver will want to hold onto the string or not, but this should lead to improvements on the hot paths for routes and gateways when the cache doesn't contain the entries we want.
> Optimise `getAccAndResultFromCache` by reducing allocations

- server/route.go
- server/server.go
The PR#5602 solved the issue for typical seed setups, but it was found that the test `TestStressChainedSolicitWorks` would sometimes fail. This is a situation where we have S4->S3->S2->S1 and all servers start at the same type. This is not a typical setup, but still the regular gossip would allow the creation of the full mesh, so this PR helps in those situations.
Related to #5602
> (2.11) [IMPROVED] Routing: reduce chances of duplicate implicit routes

- server/accounts.go
- test/accounts_cycles_test.go
When checking for import cycles, only need to check 'from', not the 'to' which could lead to false positives.
However we need to pre-transform the 'from' token in case it contains transform directives, e.g. $1, {{}}.
> [FIXED] False positives on cyclic import maps with subject mappings.

- server/client.go
- server/norace_test.go
- server/routes_test.go
- server/server.go
When a slow consumer error is detected, the server will close the connection. In some race situations, it could be that the subscription interest is left intact, which would cause routed servers to continue routing messages although the interest should have been gone.
The subscription could still be seen in the monitoring subscriptions list (when displaying with details), referencing a client connection that would be in the closed connection state.
The monitoring route page of the other servers would still indicate that there is interest for this subject on the origin server.
Resolves #5539
> [FIXED] Subscription interest could remain after slow consumer error

- server/errors.go
- server/jetstream_cluster_4_test.go
- server/leafnode.go
- server/server.go
This is a relaxed version of v2.11s change (https://github.com/nats-io/nats-server/pull/5676/files) which still allows cluster names with spaces in gateways and clusters.
> Reject leafnode cluster names with spaces

- server/client.go
- server/client_test.go
This is a simpler PR than #5749 which just limits at the point of writing rather than at the point of buffering/framing. It allows us to set the deadline for each batch.
> Limit vector count in client outbound flushes

- conf/parse.go
- conf/parse_test.go
- server/opts.go
- server/opts_test.go
The publicly exposed API for parsing a string containing configuration and a string denoting a config file were unequal.
When parsing a config file, additional checks are automatically done in the (*Options).ProcessConfigFile method, however if parsing a string containing config then those additional checks have to be recreated in consumers of the public API.
This adds:
- conf.ParseWithChecks (pedantic mode equivalent to conf.Parse)
- (*Options).ProcessConfigString, which shares the same mechanism as (*Options).ProcesConfigFile.
Signed-off-by: Your Name <your.email@example.com>
> Improve config parsing API: file vs. string

- .travis.yml
- go.mod
- go.sum
- server/accounts.go
- server/auth.go
- server/client.go
- server/client_test.go
- server/consumer.go
- server/errors.go
- server/filestore.go
- server/filestore_test.go
- server/gateway.go
- server/jetstream_cluster_4_test.go
- server/leafnode.go
- server/monitor.go
- server/norace_test.go
- server/routes_test.go
- server/server.go
- server/server_test.go
- server/store.go
- server/stree/stree.go
- server/stree/stree_test.go
- server/sublist.go
- test/accounts_cycles_test.go
- https://github.com/nats-io/nats-server/pull/5690
- https://github.com/nats-io/nats-server/pull/5725
- https://github.com/nats-io/nats-server/pull/5729
- https://github.com/nats-io/nats-server/pull/5734
- https://github.com/nats-io/nats-server/pull/5735
- https://github.com/nats-io/nats-server/pull/5736
- https://github.com/nats-io/nats-server/pull/5743
- https://github.com/nats-io/nats-server/pull/5744
- https://github.com/nats-io/nats-server/pull/5751
- https://github.com/nats-io/nats-server/pull/5755
- https://github.com/nats-io/nats-server/pull/5754
- https://github.com/nats-io/nats-server/pull/5732
- https://github.com/nats-io/nats-server/pull/5750
- https://github.com/nats-io/nats-server/pull/5756
The following were reverted before this PR:
- …
> Cherry-picks for 2.10.19-RC.3

- .golangci.yml
- scripts/runTestsOnTravis.sh
- server/jetstream_sourcing_scaling_test.go
Also fixes the configuration file to remove deprecated options and/or to use new format.
Finally, run `goimports` on `jetstream_sourcing_scaling_test.go` to satisfy the linter.
> Update `golangci-lint` to v1.59.1

- server/client.go
- server/leafnode.go
Otherwise we might add the entry into the cache and then immediately prune it afterwards, depending on luck/map iteration order.
> In client and leafnode results cache, populate new entry after pruning

- server/consumer.go
- server/norace_test.go
The server would send the reply back to the client before removing message from the stream, which could cause some issues if the client expected the message to be removed after the AckSync() call returns.
For instance, a WorkQueue that would have a max message of 1 per subject and discard new message would fail a client that got a message, ack it, and re-publish this message. Depending on timing, the client may get an error `maximum messages per subject exceeded`.
Used @pcsegal description of the problem and example code to write a test that demonstrated the issue before the fix.
Resolves #5702
> [FIXED] JetStream: sending reply to Ack before processed (standalone)

- server/test_test.go
> Remove `ordered` constraint now that we can use `cmp.Ordered`

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
When checking for orphaned assets in a cluster, make sure we are properly synched with the leader before proceeding.
When R>1 the server would rebuild them after getting the proper meta state, but in cases of R1 this could lead to dataloss.
> [FIXED] Bad meta state on restart could cause deletion of assets.

- server/client.go
- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/leafnode.go
- server/norace_test.go
- server/test_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5760
- https://github.com/nats-io/nats-server/pull/5761
- https://github.com/nats-io/nats-server/pull/5763
- https://github.com/nats-io/nats-server/pull/5767
> Cherry picks for v2.10.19 RC4

- server/consumer.go
- server/jetstream_test.go
The consumer `sseq` was being clipped back to the range between the stream `FirstSeq` and `LastSeq` even when the consumer start sequence was provided, so it wasn't possible to provide a start sequence that didn't exist in the stream yet. This PR changes that to now obey the start sequence even in that case.
Note that this problem will still exist with the consumer start timestamp, as that's predicated on being able to match the timestamp to a sequence number in the stream, which it won't be able to do if the stream doesn't contain any sequences for that time.
> Fix consumer start sequence when sequence not yet in stream

- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
- server/reload.go
It will now be possible to configure the hub's `handshake_first` field in the `tls{}` block as `auto` or a duration (e.g. `"250ms"`).
When that is the case, if the server does not receive data within this time frame, it will revert to send the `INFO` protocol in plaintext because it expects the remote LeafNode to perform the TLS handshake only after receiving it.
Resolves #5772.
> (2.11) [ADDED] LeafNode: Support for TLS handshake_first duration

- server/accounts.go
- server/auth_callout_test.go
- server/avl/seqset.go
- server/consumer.go
- server/filestore.go
- server/gateway.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/memstore.go
- server/monitor.go
- server/mqtt.go
- server/norace_test.go
- server/reload.go
- server/server_test.go
Replace usage of the new sort package with the slices package (Go 1.21) where it is faster (i.e. when it has to do a conversion from `interface{}`).
Use the new (Go 1.21) cmp.Compare in the sort functions.
Also fixes a variable shadowing that somehow wasn't being detected when using `sort.Slices` on that shadowing variable.
> Upgrade sort.Slice with slices.sort

- server/auth.go
- server/jwt_test.go
The check of the allowed connection types must be maded after the user's permissions limits are possibly "swapped" with the scoped signer's.
Resolves #5786
> [FIXED] Connection type in scoped signing keys not honored

- internal/ocsp/ocsp.go
- server/server.go
- server/server_test.go
> Set `ReadTimeout` on profiling, monitoring and OCSP HTTP servers

- server/raft.go
Otherwise on a restart with a restore from snapshot, we can revert `pterm` back to an earlier position than it should be, which can create consistency issues and failed catchups.
> NRG (2.11): Don't revert `pterm` to beginning of log when installing snapshots

- server/jetstream_cluster.go
- server/stream.go
The `getExpectedLastSeqPerSubject` check in `processJetStreamMsg` would take into account that we could get a create/seq=0 for last seq per subject.
However, the `processClusteredInboundMsg` would NOT take this into account. This would result in sending the message to all replicas. If any replica would store instead of reject the message, it would desync.
The reproducible example from below issue doesn't reproduce anymore after this fix.
Resolves https://github.com/nats-io/nats-server/issues/5644
> Fix 0 expected last seq per subject for clustered stream

- server/client.go
- server/jetstream_api.go
- server/log.go
- server/server_test.go
RateLimitWarnf does actually rate limit when the error message changes every time (i.e. if it includes something like a count or a number that changes with every log line)
Added rateLimitFormatWarnf that does the rate limiting for all log messages according to the format (rather than the statement).
This also updates the default warning threshold for pending JS requests from 32 to 128.
> [IMPROVED] Log rate limited warnings

- server/jetstream_cluster.go
- server/stream.go
Upon graceful shutdown, stream snapshots aren't installed:
stream.go
```go
} else {
// Always attempt snapshot on clean exit.
n.InstallSnapshot(mset.stateSnapshotLocked())
n.Stop()
}
```
But raft.go exits immediately since it's in Closed state
```go
if n.State() == Closed {
return errNodeClosed
}
```
This turns out to be because of calling either of `close(mset.mqch)` or `close(mset.qch)`. Which then calls the following upon leaving `monitorStream`:
```go
// Make sure to stop the raft group on exit to prevent accidental memory bloat.
// This should be below the checkInMonitor call though to avoid stopping it out
// from underneath the one that is running since it will be the same raft node.
defer n.Stop()
```
This PR proposes to skip running `n.Stop()` from `monitorStream` when we know …
> Fix install stream snapshots on graceful shutdown

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/stream.go
> [IMPROVED] When we detect a bump in clfs try to snapshot (if prior was zero force).

- server/events.go
- server/events_test.go
- server/server.go
Use a dedicated internal receive queue to dispatch the StatsZ/Ping events, and have Profilez run in its own go routine (not even using internal receive queues) because execution of profilez() can take several seconds.
> [IMPROVED] Handling of StatsZ/Ping and Profilez system events

- server/filestore.go
- server/filestore_test.go
When we would miss a LoadNextMsg() from the block associated with the starting sequence, we would check if we could skip ahead. The logic for this could load old blocks, behind where we were, if the psim fblk was outdated, causing memory bloat for cache expiration time intervals.
We reworked this to load no blocks in the skip check since this is hot path for LoadNextMsg() and the linear scan, if applicable, properly will expire anything loaded that did not contain a match.
I tested that benchmarks were not affected.
`go test -v -run=XXX --bench=Benchmark_FileStoreLoadNext`
> [IMPROVED] Do not load blocks unnecessarily when checking if we can skip ahead in LoadNextMsg().

- server/consumer.go
- server/events_test.go
- server/stream.go
Some tests were showing often a race between updateWithAdvisory() and isFiltered().
There may be other data races in other files that read the mset's configuration without proper locking, but this PR addresses specifically issues between consumer (consumer.go) and stream.
> [FIXED] JetStream: data race between consumer and stream when updated

- server/jetstream_test.go
- server/stream.go
A duplicate message inserted into an Interest-based stream with no interest would return 0 as sequence instead of the sequence of the initial message.
```sh
$ nats req interest '' -H 'Nats-Msg-Id: dedupe'
20:31:43 Sending request on "interest"
20:31:43 Received with rtt 187.55µs
{"stream":"INTEREST", "seq":6}
$ nats req interest '' -H 'Nats-Msg-Id: dedupe'
20:31:43 Sending request on "interest"
20:31:43 Received with rtt 101.95µs
{"stream":"INTEREST", "seq":0,"duplicate": true}
```
> Use correct sequence on duplicate message with no interest

- server/jetstream_test.go
Test should've been prefixed with `TestJetStream`. As noted by @wallyqs: https://github.com/nats-io/nats-server/pull/5818#discussion_r1729264623
> Correct test name

- server/consumer.go
- server/errors.json
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_consumer_test.go
- server/jetstream_errors_generated.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/stream.go
This adds pedantic mode as requested in #4959 
Draft, as I need to make sure all cases are covered and tested.
I also want to check if the amount of changes in arguments passed to assigment functions could be reduced.
> Add pedantic mode

- internal/ldap/dn_test.go
- server/certidp/certidp.go
- server/certidp/ocsp_responder.go
- server/client.go
- server/gateway_test.go
- server/jetstream_cluster_3_test.go
- server/stree/node48.go
- server/stree/stree_test.go
- server/sublist_test.go
- server/websocket.go
- test/client_cluster_test.go
- test/leafnode_test.go
- test/new_routes_test.go
- test/norace_test.go
@neilalexander I do believe this uncovered two off by one conditions in node48 under stree. Could you take a look, kept that change separate.
> [FIXED] New staticcheck fixes

- server/jetstream_cluster_4_test.go
- server/stream.go
Sometimes during a stream catchup after a restart, when applying entries the clfs could have been bumped due to msg not found errors from likely deleted messages, causing a stream replica to remain out of sync.
Fixes #5205
> Do not bump clfs on seq mismatch when before stream LastSeq

- server/filestore.go
- server/filestore_test.go
We had reports of disk spikes and memory pops queued off of syncBlocks, and looks like it was coming from blocks that were no longer compressible, but would load each time and go through the process.
Resolves: #5595 
> [IMPROVED] When a block can not be compressed, mark it as such to avoid syncBlocks trying continously

- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_errors_generated.go
This issue was reported by Marco and Antithesis.
`seq=0, duplicate=true` would be returned if two duplicate messages would be processed at the same time. The first will propagate, which will take some time for a clustered stream, but then the second message gets processed and rejected with `seq=0, duplicate=true` (without `error`) which would be invalid.
One option to fix this is timing out the second publish and wait for the original message to finish processing.
That fixes this issue, and the user would just retry the request and get the valid sequence once the other message has gone through.
However, it could decrease message throughput when this is hit. An alternative could be to throw an error, but if the user would always retry if `err != nil` then they'd be "spamming" the same …
> Don't return `seq=0, duplicate=true` when processing duplicate messages asynchronously

- internal/ldap/dn_test.go
- server/certidp/certidp.go
- server/certidp/ocsp_responder.go
- server/client.go
- server/filestore.go
- server/filestore_test.go
- server/gateway_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
- server/stream.go
- server/stree/node48.go
- server/stree/stree_test.go
- server/sublist_test.go
- server/websocket.go
- test/client_cluster_test.go
- test/leafnode_test.go
- test/new_routes_test.go
- test/norace_test.go
Includes:
- https://github.com/nats-io/nats-server/pull/5825
- https://github.com/nats-io/nats-server/pull/5826
- https://github.com/nats-io/nats-server/pull/5821
- https://github.com/nats-io/nats-server/pull/5831
> Cherry picks for v2.10.19 RC6

- server/filestore.go
- server/filestore_test.go
> Adjust test to have < 64k subjects to test skip logic.

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
Prevents potential re-tagging attacks on third-party workflows.
> Pin third-party workflows in GitHub Actions

- server/certstore/certstore_windows.go
- server/pse/pse_windows.go
- server/sysmem/mem_windows.go
Otherwise DLLs can potentially be loaded in from the current working directory.
Tested on a Windows 11 ARM64 virtual machine.
> Windows: Search for DLLs in system paths only

- server/jetstream_cluster_4_test.go
- server/stream.go
A regression was introduced in https://github.com/nats-io/nats-server/pull/5821 where CAS operations on a R1 stream would succeed even if they should be rejected. Whereas on R3/clustered they would be rejected.
Resolves: https://github.com/nats-io/nats-server/issues/5840
> Fix difference in KV CAS operations for R1 vs R3

- server/jetstream_api.go
- server/jetstream_cluster_4_test.go
Follow-up of: https://github.com/nats-io/nats-server/pull/5164
When sending a consumer resume request it would be handled for single-replica per above PR, but not for the clustered case. This PR ensures clustered consumers can also be resumed.
> Fix clustered consumer resume on empty/zero PauseUntil

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
- server/certstore/certstore_windows.go
- server/jetstream_cluster_4_test.go
- server/pse/pse_windows.go
- server/stream.go
- server/sysmem/mem_windows.go
Includes:
- #5841 
- #5836
- #5837
> Cherry picks for v2.10.20

- server/jetstream_cluster.go
In `processClusterCreateStream` there was a call to `reflect.DeepEqual` with different types making it always fail. `mset.config()` is the config itself, whereas `sa.Config` is a pointer to the config. So we need to pass `mset.config()` as a pointer instead.
In `processClusterCreateConsumer` this was done as well:
```go
cfg := o.config()
if isConfigUpdate = !reflect.DeepEqual(&cfg, ca.Config); isConfigUpdate {
```
> Fix `reflect.DeepEqual` both receiving pointers

- server/jetstream_cluster.go
- server/jetstream_test.go
- server/stream.go
This change adds a new header
"Nats-Expected-Last-Subject-Sequence-Subject" when when paired with "Nats-Expected-Last-Subject-Sequence" allows publishers to customize the subject used when the server enforces
"Nats-Expected-Last-Subject-Sequence". Publishers can specify a alternative subject to be used that includes wildcards.
Resolves #5280
Signed-off-by: Caleb Champlin <caleb.champlin@gmail.com>
> [ADDED] Publish header "Nats-Expected-Last-Subject-Sequence-Subject"

- server/ipqueue.go
- server/ipqueue_test.go
- server/jetstream_api.go
You can optionally pass in an `ipQueue_SizeCalculation` function to an IP queue that fires each time an item is pushed or popped so that the total size can be tracked.
There is a slight performance impact but mostly it will depend on the complexity of the calculation function:
```
go test -v ./server -run=XXX -bench=IPQueueSizeCalculation -benchtime=10s
goos: darwin
goarch: arm64
pkg: github.com/nats-io/nats-server/v2/server
BenchmarkIPQueueSizeCalculation
BenchmarkIPQueueSizeCalculation/WithoutCalc
BenchmarkIPQueueSizeCalculation/WithoutCalc-24          396342910               30.75 ns/op      520.35 MB/s
BenchmarkIPQueueSizeCalculation/WithEmptyCalc
BenchmarkIPQueueSizeCalculation/WithEmptyCalc-24        377004524               33.91 ns/op      471.80 MB/s …
```
> (2.11) Add ability for IP queues to track total size

- server/jetstream_cluster_4_test.go
1. Add test for consuming a stream with a given sequence start offset.
- Durable consumer 
- Durable consumer with `Bind`
- Pull consumer
- Synchronous consumer
- Callback subscription
- Channel subscription
- Get stream message
- Get last stream message by subject
2. Add test where a durable consumer ACKs messages that have been deleted from a stream
> Tests: consumers with start sequence offset + ACK deleted messages

- server/jetstream_test.go
- server/opts.go
- server/stream.go
Built on top of #5575. Tries to prevent the stream `msgs` queue from becoming overwhelmed by core NATS publishes. In this case, where a reply subject is known, the sender will receive a 429 "Too Many Requests". Otherwise it's rate-logged.
Two new configuration options are added to the JetStream block: `max_buffered_size` and `max_buffered_msgs`. If not configured, defaults are used.
> Stream ingest rate limiting

- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/mqtt.go
Currently failures to unmarshal only give a vague error of "invalid JSON", this adds the original error to it as context.
Before:
````
invalid JSON
````
After:
```
invalid JSON: invalid character '\"' after object key
```
Related to but **not** dependent on https://github.com/nats-io/nats-server/pull/5858
Signed-off-by: Casper Beyer <casper@synadia.com>
> Add error details to invalid JetStream JSON errors

- .github/workflows/cov.yaml
- scripts/cov.sh
The code coverage GA was referencing 1.21.x which seem to prevent the install of gocovmerge.
Also added an early check to see if we can run gocovmerge before starting the test suite.
> Fixed nightly code coverage [ci skip]

- .github/workflows/tests.yaml
When running in GitHub actions JS cluster 4 tests would not be skipped when running JS no cluster tests.
> Skip JS cluster 4 tests when running JS no cluster tests

- server/jetstream_helpers_test.go
> Tests: Wait for shutdown on `stopAll`, parallelise LDM shutdowns

- go.mod
- go.sum
- server/accounts.go
- server/events.go
- server/jetstream.go
- server/jetstream_cluster_4_test.go
- server/jetstream_jwt_test.go
- server/opts.go
- server/raft.go
- server/route.go
- server/sendq.go
- server/server.go
This PR adds the ability to move NRG traffic out of the system account and into the asset accounts. Particularly in heavily multi-tenanted systems, this can help cases where head-of-line blocking may happen in the system account due to large amounts of replication traffic.
This needs to be enabled on a per-account basis on each participating server. Servers advertise their capability to support account NRG to each other. If a Raft group detects a peer coming up without support, they will revert back to using the system account automatically.
Requires https://github.com/nats-io/jwt/pull/223 and then `go.mod` updating.
> NRG (2.11): Add ability to move cluster traffic into asset accounts

- server/auth.go
- server/monitor_test.go
- server/server.go
changed to update the account issuer for an account to always update otherwise the information shown in accountz will not be consistent with the decoded JWT
> update account issuer always

- server/events.go
- server/events_test.go
- server/norace_test.go
(also fixed a flapper)
Resolves #5877
> (2.11) [ADDED] Monitoring: SlowConsumersStats in PING/STATSZ messages

- server/accounts.go
- server/opts.go
Avoids unnecessary `has invalid value "" for cluster traffic account` error.
> Empty `cluster_traffic` value should default to `"system"` in JWT

- server/opts.go
- server/opts_test.go
> Fix operator list config

- server/filestore.go
- server/filestore_test.go
- server/norace_test.go
We had a condition where an old index.db was not able to properly restore a stream due to max msgs per subject being set and certain blocks being compacted away and removing subject info for those sequences. In addition we fixed recovery after Truncate and PurgeEx by subject when the index.db was corrupt or not available.
This change also moves generating the index.db file to after writing the blocks during a snapshot and we do a force call to make sure it is written even when complex.
> [FIXED] Improvements to dealing with old or non-existant index.db

- server/filestore.go
- server/norace_test.go
Extension to https://github.com/nats-io/nats-server/pull/5893
If we can't update the index.db upon shutdown, for example during a hard kill, we'd enter into this condition if `MaxMsgsPer` was set.
https://github.com/nats-io/nats-server/pull/5893/files#diff-384c189826934c9a6fc3554dafc63dab2076245010e3d6fce5c71a93e15e9877R1752
However, all limits-based fields have this issue not just `MaxMsgsPer`.
Running similar tests where `nats str info` before hard kill should equal its output after hard kill:
- `MaxMsgsPer`: −7,877 diff (fixed with addition of above condition/PR)
- `MaxMsgs`: +2,123 diff
- `MaxAge`: no diff (correct messages, but still `[WRN] Filestore [stream] loadBlock error: message block data missing`)
- `MaxBytes`: +3,567 diff (had a MaxBytes set of 1016 MiB, but after restart the …
> [FIXED] Also recover on old index.db when not using MaxMsgsPer

- server/opts.go
- server/reload.go
- server/server.go
- server/server_test.go
For example, to set minimum version to TLS v1.3:
```
tls { min_version = "1.3" }
```
> Add support for setting TLS min version number in tls block

- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster_4_test.go
- server/jetstream_events.go
- server/opts.go
- server/opts_test.go
This should provide some protection against the server being completely overwhelmed by a build-up of JS API requests.
> Global JetStream API request queue limiting

- server/server.go
- test/ocsp_peer_test.go
This allows client certificates on the https monitoring port to be validated when OCSP peering is enabled.
Signed-off-by: Jarret Lavallee <jarret@synadia.com>
> OCSP: support using https port when ocsp peer enabled

- server/filestore.go
- server/filestore_test.go
When determining to rebuild state, when we match the last record in the last block indicated by index.db, we still need to check for additional blocks.
> [FIXED] Rebuild state if matched properly for index.db but we find additional blocks

- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster_4_test.go
- server/jetstream_events.go
- server/norace_test.go
- server/opts.go
- server/opts_test.go
- server/reload.go
- server/server.go
- server/server_test.go
- test/ocsp_peer_test.go
- #5901
- #5904
- #5900
- #5906
- #5908
- #5907
> Cherry-picks for 2.10.21-RC.2

- server/raft.go
- server/raft_test.go
> [FIXED] Deadlock when removing a peer that happened to be the leader.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/stream.go
> [IMPROVED] Limit stepdown to system account.

- .github/workflows/long-tests.yaml
Create a dummy workflow, only triggered by manual user action.
The existence of this workflow on the main branch enables development  and testing of the same workflow in a different branch.
Signed-off-by: Your Name <marco@nats.io>
> Add placeholder workflow for long-running server tests

- server/accounts.go
- server/client.go
- server/jetstream_cluster_4_test.go
- server/mqtt.go
- server/sublist.go
- server/sublist_test.go
There are some cases where we care about the number of subscriptions on the sublist but don't need the `SublistResult`s. We can save quite a few allocations on these paths by reusing the match-any logic from `HasInterest` to count the number of subs.
> Add `NumInterest` to optimise searching for number of sublist entries

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/norace_test.go
- server/raft_test.go
- server/stream.go
Incudes the following:
- #5910
- #5914
- #5917
> Cherry-picks for 2.10.21-RC.3

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
When scaling down a stream make sure replica count is correct if adjusted and also make sure we do not have orphan consumers.
When we scale down a replicated stream, say R5, if it has consumers that are a lower replica count, say R1, they could be placed on the peers that may go away. We need to make sure we properly assign peers and transfer state as needed.
Note the consumer state transfer expects the state to be stable, so should be paused.
> [FIXED] When scaling down a stream make sure consumers are adjusted properly.

- server/leafnode_test.go
- server/monitor.go
- server/monitor_test.go
- server/server.go
In situation where a Leaf server has no cluster specified, we internally use the server name as the cluster name. We may need it in the protocol so that the hub can suppress some messages to avoid duplicates.
We were however still reporting a cluster name in `/varz` and in the banner on startup. This PR fixes both.
Resolves #5913
Signed-off-by: Ivan Kozlovic ivan@synadia.com
> [FIXED] LeafNode: Don't report cluster name in varz/banner when none defined

- server/jetstream_cluster.go
Fixes the following panic:
```
[inf] panic: runtime error: invalid memory address or nil pointer dereference
[inf] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc0a90d]
[inf]
[inf] goroutine 1 [running]:
[inf] github.com/nats-io/nats-server/v2/server.(*jetStream).setupMetaGroup(0xc0002c2200)
[inf] server/jetstream_cluster.go:877 +0x12ed
[inf] github.com/nats-io/nats-server/v2/server.(*Server).enableJetStreamClustering(0xc00023e008)
[inf] server/jetstream_cluster.go:759 +0x1af
[inf] github.com/nats-io/nats-server/v2/server.(*Server).enableJetStream(0xc00023e008, {0x40000000, 0x280000000, {0xc00002a3f0, 0x15}, 0x1bf08eb000, 0x0, {0x0, 0x0}, 0x1, ...})
[inf] server/jetstream.go:508 +0x11fc
[inf] github.com/nats-io/nats-server/v2/server.(*Server).EnableJetStream(0xc00023e008, …
```
> Reuse pre-existing sys account reference

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
Looked into the issue reported in Antithesis of non-monotonic sequence / pub ack sequence moving back due to stream desync.
When looking at these logs:
```
[        48.508] [      service_nats-1] [inf] [1] 2024/09/27 09:29:29.624201 [WRN] Catchup for stream '$G > test-stream' stalled
[        48.508] [      service_nats-1] [inf] [1] 2024/09/27 09:29:29.624634 [DBG] RAFT [yrzKKRBu - S-R3F-gMW2rGjb] Resuming our apply channel
[        48.508] [      service_nats-1] [inf] [1] 2024/09/27 09:29:29.624796 [WRN] Error applying entries to '$G > test-stream': catchup failed, too many retries
[        48.510] [      service_nats-1] [inf] [1] 2024/09/27 09:29:29.626681 [DBG] SYSTEM - System connection closed: Internal Client
[        48.511] [      service_nats-1] [inf] [1] 2024/09/27 …
```
> Fix desync after errCatchupTooManyRetries

- server/ipqueue.go
- server/ipqueue_test.go
- server/jetstream_cluster.go
- server/stream.go
Small updates to ipQueue:
- Document that caller must not reuse the slice after call to recycle().
- Reset size to 0 on pop() or last popOne() without need to call q.caclc().
- Added missing recycle() calls in some places.
- Added benchmarks to check perf impact on future changes.
> (2.11) Internal: Small udpates to ipQueue

- server/jetstream.go
Based on [a discussion on Community NATS Slack](https://natsio.slack.com/archives/CM3T6T7JQ/p1727353138572209?thread_ts=1727312314.349369&cid=CM3T6T7JQ).
When just running `nats-server -js` or with Docker using `docker run --network host nats -js`, a temporary storage directory will be used since `-sd`/`jetstream.store_dir` is not specified.
There have been some times where people lost data, because they were not aware of the temp storage being used.
A user commented if a warning could be shown for this, therefore proposing this small fix to try and make it more obvious.
@bruth, tagging as you commented in the thread as well.
> Warn if using temp storage for JetStream

- logger/log.go
- server/filestore.go
- server/raft.go
- server/server.go
Filestore-owned items don't need to be group-accessible and log files don't need to be group-writable.
> Update default file and directory permissions

- server/raft.go
- server/raft_test.go
If a RAFT leader would call `storeToWal` and shortly after got hard killed, it should truncate the `AppendEntry` since it didn't reach quorum.
This would generally already happen correctly, except for when `n.pindex == ae.pindex` due to the `n.pterm` incorrectly being updated.
> Fix drift in WAL, truncate AppendEntry without quorum

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/jetstream_cluster_4_test.go
- server/norace_test.go
Antithesis testing has found that late or out-of-order delivery of these snapshots, likely due to latency or thread pauses, can cause stream assignments to be reverted which results in assets being deleted and recreated. There may also be a race condition where the metalayer comes up before network connectivity to all other nodes is fully established so we may end up generating snapshots that don't include assets we don't know about yet.
We will want to audit all uses of `SendSnapshot` as it somewhat breaks the consistency model, especially now that we have fixed a significant number of Raft bugs that `SendSnapshot` usage may have been papering over.
Further Antithesis runs without this code run fine and have eliminated a number of unexpected calls to `processStreamRemoval`.
We've also …
> (2.11) Don't send meta snapshot when becoming metaleader

- server/jetstream_cluster_3_test.go
- server/norace_test.go
Both tests became a bit flaky. If they would not be able to retry within the first 5s, the test would fail. So having CI be a bit slow could make this flake.
Lowering the  `startInterval` for these tests to more often try to run the consumer cleanup.
> De-flake TestNoRaceJetStreamClusterGhostConsumers

- main.go
As one was lost in the https://github.com/nats-io/nats-server/pull/3536
Signed-off-by: Alexander Kuleshov <kuleshovmail@gmail.com>
> Add missed angle bracket to the help output

- server/jetstream_cluster_2_test.go
- server/jetstream_helpers_test.go
- server/jetstream_leafnode_test.go
- server/leafnode.go
- server/opts.go
- server/opts_test.go
This adds a `delay` option to `js_cluster_migrate` as an option in nested object. The assets assets will only be migrated after the specified delay (rather than immediately, which is the default).
> [ADDED] Delay option to js_cluster_migrate

- server/jetstream_api.go
- server/jetstream_test.go
Until now, in JS API we were checking if request payload is empty.
That check was unmarshaling that payload before we did second unmarshal
for the destination type.
This commit adds separate check to avoid double unmarshaling.
This PR does not change `isEmptyRequest` implementation, as its a less strict check.
> Reduce cost of json Unmarshal operations

- server/raft.go
Fix a data race in `processAppendEntry`. Since the `ae` could be cached and returned to the pool in `applyCommit`, need to make sure we make a copy for ourselves here.
```
Write at 0x00c0157328c8 by goroutine 160360:
github.com/nats-io/nats-server/v2/server.(*appendEntry).returnToPool()
/home/travis/build/nats-io/nats-server/server/raft.go:2194 +0x17a4
github.com/nats-io/nats-server/v2/server.(*raft).applyCommit()
/home/travis/build/nats-io/nats-server/server/raft.go:2935 +0x16e8
github.com/nats-io/nats-server/v2/server.(*raft).ResumeApply()
/home/travis/build/nats-io/nats-server/server/raft.go:1001 +0x2c4
github.com/nats-io/nats-server/v2/server.(*stream).processSnapshot.func1()
/home/travis/build/nats-io/nats-server/server/jetstream_cluster.go:8307 +0x167 …
```
> NRG: Fix data race in `processAppendEntry`

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/stream.go
When checking interest state for interest or workqueue streams, we would check all msgs from the streams first sequence through ack floor and up to delivered.
We do this to make sure our ack state is correct. In cases where there were alot of messages still in the stream due to offline or slow consumers, this could be a heavy load on a server.
This improvement uses LoadNextMsg() to efficiently skip ahead and we now remember our checked floor and do not repeat checks for messages below our check floor on subsequent runs.
This change also highlighted a datarace in filestore that is fixed here as well.
> [IMPROVED] Check stream state performance

- server/filestore.go
- server/filestore_test.go
This fixes that condition and also adds in compaction logic once we know the tombstones are no longer relevant.
Resolves: #5929  (Why we have large block exceeding maximum block size)
> [FIXED] When writing tombstones we could violate max block size.

- server/raft.go
- server/raft_test.go
It is never safe for the term number to go backwards for any reason, even in a truncate scenario, as this breaks the consistency guarantees and could cause us to vote again in what should be past elections if more than one node has to truncate back at the same time.
All calls to `truncateWAL(...)` are after the AE has bumped the term number up if needed, so this is safe for making forward progress.
> NRG (2.11): Do not revert term on truncate WAL

- server/filestore.go
- server/stree/stree.go
- server/stree/stree_test.go
- server/stree/util.go
- server/sublist.go
- server/sublist_test.go
When a subject with embedded nulls was inserted into an stree followed by another one with more nulls we could recurse infinitely and panic the server.
We now changed the no pivot to 127(DEL) and enforce that you can not insert a subject with that byte. Also make sure we do not recursively call into insert with no cpi movement.
This condition was from an old server that had corrupted the PSIM data (known issue fixed), but we were not detecting it, so added test for this when checking runes under isValidSubject.
> [FIXED] Server panic on bad subject and infinite recursion.

- go.mod
- go.sum
- server/jetstream_jwt_test.go
[BUMP] jwt to v2.7.2 - which retracts case-sensitive jwt.TagList
[FIX] jwt cluster test reference ClusterTraffic as a string
Signed-off-by: Alberto Ricart <alberto@synadia.com>
> [BUMP] jwt to v2.7.2

- server/auth_callout_test.go
- server/auth_test.go
- server/client.go
- server/client_test.go
- server/gateway_test.go
- server/jwt_test.go
- server/leafnode_test.go
- server/monitor_test.go
- server/raft_test.go
- server/routes_test.go
- server/server_test.go
- server/sublist.go
- server/sublist_test.go
While writing the test, I needed to make sure that each server in
the hub has registered interest for 2 queue subscribers from the
same group. I noticed that `Sublist.NumInterest()` (that I was
invoking from `Account.Interest()` was returning 1, even after
I knew that the propagation should have happened. It turns out
that `NumInterest()` was returning the number of queue groups, not
the number of queue subs in all those queue groups.
For the leafnode queue balancing issue, the code was favoring
local/routed queue subscriptions, so in the described issue,
the message would always go from HUB1->HUB2->LEAF2->QSub instead
of HUB1->LEAF1->QSub.
Since we had another test that was a bit reversed where we had
a HUB and LEAF1<->LEAF2 connecting to HUB and a qsub on both
HUB and LEAF1 and requests …
> [FIXED] LeafNode's queue group load balancing and Sublist.NumInterest

- .travis.yml
- server/accounts.go
- server/auth_callout_test.go
- server/auth_test.go
- server/client.go
- server/client_test.go
- server/gateway_test.go
- server/jwt_test.go
- server/leafnode_test.go
- server/monitor_test.go
- server/mqtt.go
- server/server_test.go
- server/sublist.go
- server/sublist_test.go
- #5918
- #5982
- #5983 (although only the 1.22.8 upgrade, since 1.21.x is no longer receiving updates)
> Cherry-picks for 2.10.22-RC.2

- server/jetstream_cluster_2_test.go
Before setting state pause to make sure we do not update the state after we set it due to async signaling in the server.
> [FIXED] Flapper TestJetStreamClusterCheckInterestStatePerformanceInterest

- server/auth.go
- server/jwt_test.go
Relaxed template logic to allow a template in a scoped user to be in line with the subject, enabling uses like `KV_{{tag(foo)}}`. This allows more flexibility for some arcane cases even if the tag requirement is that it will still be lower-cased.
Signed-off-by: Alberto Ricart <alberto@synadia.com>
> [FEAT] enable scoped users to have templates that are not limited to a subject token

- server/raft_test.go
> Fix data race in `TestNRGTermDoesntRollBackToPtermOnCatchup`

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/store.go
Previously a related case of RAFT state being deleted was fixed, when running into `errCatchupTooManyRetries`: https://github.com/nats-io/nats-server/pull/5939
After hitting this we shutdown and retry.. but if we have not elected a leader yet we'd hit `"catchup for stream '%s > %s' aborted, no leader"`, which then would again throw away RAFT state. This PR proposes a fix for that case.
> Fix desync after errCatchupAbortedNoLeader

- server/jetstream_api.go
- server/jetstream_test.go
Side effect from https://github.com/nats-io/nats-server/pull/5956 some clients/natscli send empty objects to trigger the meta leader step down.
> [v2.11] Fix meta step down panic on empty object

- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
Process max delivery boundaries when expiring vs always putting back on the redelivered queue.
Previously we would always re-queue and do this on getNextMsg() which worked well for push consumers, but with pull based consumers would require a new pull request to be present to process any redelivered and this could report redelivered status incorrectly on max deliver of 1.
> [FIXED] Max delivered stuck consumers and mis-reported redelivered stats.

- .github/workflows/cov.yaml
> Update code coverage GitHub Action

- server/jetstream_api.go
- server/jetstream_test.go
The check for empty object exposed a lack of check for `*Placement` before accessing its fields. This commit properly fixes it.
> Fix nil pointer dereference on Placement

- server/consumer.go
- server/jetstream_consumer_test.go
We were releasing and acquiring again lock while fetching messages to reduce contention. This could cause a consumer getting stuck in certain scenarios, like when `max messages per subject` was set to `1` and message was republished while consumer was trying to `NAK` the first one.
> Fix race with store when fetching messages by a consumer

- server/jetstream_cluster_4_test.go
- server/raft.go
- server/raft_test.go
This PR makes three complementary fixes to the way how catchup and truncating is handled.
Specifically:
- when doing `n.loadEntry(index)` we need to pass where the AppendEntry is in terms of stream sequence, this is equal to `ae.pindex+1` since the `ae.pindex` is the value before it's stored in the stream.
- start catchup from `n.commit`, we could have messages past our commit that have been invalidated and need to be truncated since there was a switch between leaders
- because we catchup from `n.commit`, we check if our local AppendEntry matches terms with the incoming AppendEntry, we only need to truncate if the terms don't match
> NRG (2.11): Start catchup from `n.commit` & fix AppendEntry is stored at `seq=ae.pindex+1`

- server/jetstream_cluster.go
Spotted the following in a test run:
```
=== RUN   TestJetStreamClusterUserSnapshotAndRestoreConfigChanges
jetstream_cluster_1_test.go:3029: Unexpected error: nats: no responders available for request
[signal SIGSEGV: segmentation violation code=0x1 addr=0x25c pc=0x939f79]
goroutine 22770 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream.func1()
./server/jetstream_cluster.go:2269 +0x19
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream(0xc00070aa00, 0x0, 0xc000ac2900, 0x0)
./server/jetstream_cluster.go:2428 +0x2333
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
./server/jetstream_cluster.go:3876 +0x25 …
```
> Fix possible panic on monitorStream when shutting down

- .github/workflows/cov.yaml
> Update code coverage/coverall GitHub actions to v1.1.1 and v2.3.2

- server/consumer.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
This PR backs out #5785, which was released in v2.10.19, as it has a negative impact on sourcing and mirroring. See discussion at #6005.
Two new unit tests, `TestJetStreamSourcingClipStartSeq` and `TestJetStreamMirroringClipStartSeq`, are added to show this behaviour in action.
We will probably want to revisit this for 2.11 so that we can come up with something that works for both use-cases.
> Restore consumer `OptStartSeq` clipping behaviour

- server/jetstream_api.go
- server/jetstream_test.go
- server/server.go
This is similar to @neilalexander PR (#5948) but has a slightly different approach. We use the struct to have a `next` so that we can use a list since the list will be maintained ordered. The for-loop is in one level, as opposed to two, which means that pushing to the IPQ will be "immediately" popped, even if we have a timer initialized and waiting to fire.
The timer is reset (not recreated everytime) only if the added response ends-up being at the head of the list.
Added a test that verifies that it works properly.
> Refactor delayed API responses

- server/certstore/certstore_windows.go
This should allow access to `CERT_SYSTEM_STORE_LOCAL_MACHINE` from non-admin users.
Fixes #6018.
> Windows: Set `CERT_STORE_READONLY_FLAG` when opening cert stores

- server/consumer.go
- server/stream.go
This PR makes the following changes that should reduce allocations in consumers:
* `JSApiConsumerGetNextRequest` structs are now pooled, as they were unavoidably escaping to the heap;
* `waitingRequest` structs are now returned to the pool correctly if hitting `MaxWaiting`;
* Reuse the `hdr` buffer from pooled `jsPubMsg` when returning consumer errors to the client.
> Reduce allocations in consumers

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
When we're being asked to provide data within a range during catchup, we should not extend that range and provide more data. Especially since that range was defined by a snapshot, which also specifies which RAFT entries should be sent after processing that snapshot. This would just result in duplicated work and possible desync for the follower, so these lines can safely be removed.
**Timeline of these lines:**
Previously when receiving a catchup request the `FirstSeq` could be moved up to match what the state says:
[[IMPROVED] Catchup improvements #3348](https://github.com/nats-io/nats-server/pull/3348/files#diff-5cb252c37caef12e7027803018861c82724b120ddb62cfedc2f36addf57f6970R7132-R7138) (August, 2022)
Afterward this was removed in favor of only extending the `LastSeq`:
[[FIXED] KeyValue …
> [FIXED] Catchup must not extend past requested sequence range

- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
Reverts the changes made in https://github.com/nats-io/nats-server/pull/5987, but the tests are kept.
Instead opting for a simpler approach:
- removing the `isNew` condition when `pterm` or `pindex` don't match, to ensure consistency even during catchup
- move the `ae.pindex == n.pindex` condition up so `pterm` can be corrected (otherwise it would not be executed)
> NRG (2.11): Truncate entries without quorum from different `pterm`

- server/client.go
- server/leafnode_test.go
When receiving a message from a route, if the queue interest is only routes and leaf connections, the server will always favor the leaf kind. However, if there were more than one leaf connections for the same queue group, the server will always pick the same (the last one). It would change if new leaf were to connect or disconnect/reconnect, but with a stable set, it would always be the same.
This PR makes this selection somewhat random.
Resolves #6040
> [FIXED] Cluster: loab balancing of queue groups from attached leaf nodes

- .github/workflows/long-tests.yaml
- server/jetstream_cluster_long_test.go
This pull request introduces a new group of tests for server: long-running test.
Anything that takes more than a few seconds can be relocated here to speedup the regular CI flow.
- Add a new test group
- Add an example test (KV Put for 3 minutes with server restarts)
- Set up [GH workflow](https://github.com/nats-io/nats-server/actions/workflows/long-tests.yaml) (scheduled daily) 
> New test group and pipeline for long-running tests

- server/certstore/certstore_windows.go
- server/certstore_windows_test.go
Fixes a bug in #6042 where the `thumbprint` would never match, as we were passing in a hex-decoded form instead of the actual string value.
> Fix matching by `thumbprint` in the Windows certificate store

- server/stree/stree.go
- server/stree/stree_test.go
> stree: Don't panic when checking `hasFWC`

- server/jetstream_cluster.go
With the introduction of these PRs, https://github.com/nats-io/nats-server/pull/5939 and https://github.com/nats-io/nats-server/pull/5986, we don't blow away our state anymore as we can keep retrying.
However, if a follower had installed a snapshot from the leader and would then start processing it, only for the leader to go offline for an extended period, we could spin. Since we'd immediately detect there's no leader, stop the RAFT group, recreate it, stop since no leader, etc. etc.
Prevent spinning by introducing some wait time in-between if it's the first time trying, and check before returning if a leader became available since as then we could still continue.
> [FIXED] Don't spin during snapshot processing with no leader

- server/jetstream_cluster.go
This PR fixes two bugs in `encodeStreamMsgAllowCompress`:
* The boundary lengths could have overflowed when casting potentially large values down to uint16 or uint32 and we wouldn't have noticed;
* We would then copy in the subject/reply/header/msg with the original length regardless, not the overflowed length, meaning the decoding side would have the wrong boundaries.
Now we will correctly calculate the bounds, avoiding overflows, and only append as many bytes as we clipped down to.
> Refactor encoding replicated stream messages to properly enforce framing

- server/filestore.go
- server/raft.go
> NRG (2.11): Always write term/vote and peer state synchronously

- server/raft.go
- server/raft_test.go
After installing a snapshot for `n.applied=5`, and then truncating back to its `pterm` and the same `pindex` as `applied` it would remove the snapshot as well, even though it should be kept.
> [FIXED] Don't remove snapshot if truncate to applied

- server/raft.go
- server/raft_test.go
A follower could become candidate/leader before processing a snapshot. Based on timing the snapshot could enter into the apply queue, and before `n.PauseApply()` is called the follower could freely become leader and then fail processing the snapshot.
When a snapshot is not successfully applied yet, block the follower from becoming candidate until the snapshot is processed.
> NRG: Don't switch to candidate when waiting for pending applies

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
Antithesis found a case where if a server was hard killed and would replay RAFT append entries during startup, if it would then be SIGTERM-ed while the RAFT recovery is running, the `acc.lookupStream` that happens in `js.processClusterCreateStream` resulted in a `JetStream not enabled for account` error. Which would then delete the RAFT state.
There are also other errors that could pop up, so either way; if we're shutting down, don't delete the RAFT state.
> NRG: Don't delete RAFT state if stream/consumer creation failed during shutdown

- server/jetstream_api.go
When logging about streams or consumers, the order is always `accountName > streamName > consumerName`. For example:
```go
s.Noticef("JetStream cluster new consumer leader for '%s > %s > %s'", ca.Client.serviceAccount(), streamName, consumerName)
```
This was not fully consistent everywhere, so updated the cases where it was flipped. (`streamName > accountName`)
> Make 'accountName > streamName' logs consistent

- server/filestore.go
- server/jetstream_cluster.go
> NRG: Use configured sync intervals for group stores

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
This updates the metalayer recovery so that consumer assignments are grouped by the stream recovery key, such that a stream removal can also clean up any pending consumer updates.
Previously, if the metalayer recovered the following:
1. Stream update assignment
2. Consumer update assignment
3. Stream remove assignment
4. Stream update assignment
... then 2 would survive the recovery process because 4 cancelled out 3 and 3 didn't cancel out 2.
Co-authored-by: Maurice van Veen <github@mauricevanveen.com>
> Group metalayer consumer assignments by stream during recovery

- server/jetstream_cluster.go
We can't know whether `s.quitCh` or `qch` will fire first, since the `select` order is indeterminate. Try to snapshot either way.
> Improve metalayer snapshot on shutdown

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
For the following scenario:
1. create file-based R3 stream
2. delete stream
3. create memory-based R3 stream
4. add a consumer
The call to `js.processStreamAssignment(sa)` even while we're recovering would mean that on meta recovery we'd first create the file-based stream, then create the memory-based stream and fail to do so since we can't change storage types. Which then leaves us stranded with 2 nodes having a memory-based stream, and that one node with a file-based stream.
This change proposes to have the stream additions be consistent with the other collecting of state into `ru *recoveryUpdates` before applying, and waiting until recovery is finished to do so.
Co-authored-by: Neil Twigg <neil@nats.io>
> [FIXED] Handle recreating file-based stream to be memory on meta recovery

- server/jetstream_api.go
- server/stream.go
The same data race was fixed before in https://github.com/nats-io/nats-server/pull/5880, but was re-introduced in https://github.com/nats-io/nats-server/pull/5858/files#diff-9c075c47b0690a821ad35caa26308b69adeb132042f062eef75513db2a26638aL2515
This PR re-introduces the calls to `.clone()`.
> [FIXED] Fix data race when moving a stream

- server/raft.go
- server/raft_test.go
Antithesis triggered a case where:
- a follower (S0) is behind and triggers catchup from the leader (S2)
- another follower (S1) triggers leader election
- the follower (S0) allows follower (S1) to become leader
- the leader (S2) sends a new message, which new leader (S1) rejects because it's on a higher term
- the follower (S0) now receives above message that new leader (S1) rejected, providing previous leader (S2) with quorum
- the new leader (S1) rejected that message, so previous leader (S2) has now desynced since it applied the message
This is solved by canceling catchup once a leader election happens for a higher term. The new leader will then resume our catchup once it's elected.
> NRG (2.11): Vote request cancels catchup, new leader could have rejected subsequent catchup messages

- server/jetstream_cluster.go
> [FIXED] Panic on nil sysAcc

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
- server/raft.go
- server/raft_test.go
This should fix some logical races where multiple sets of goroutines can fight over the same store directory, i.e. when shutting down and recreating a group rapidly.
> NRG: Wait for goroutines to shutdown when recreating group

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_consumer_test.go
- server/jetstream_events.go
Changes introduced:
**Do not set default pinned TTL if it's not a pinned client consumer**
In one case, we were not checking if given consumer config is a pinned
one when setting pinned TTL. That caused the TTL to be always set, which
in turn incremented API Level even if Priority Groups were not used.
**Rename advisories**
Advisories were following ADR, but ADR names were fixed.
This follows up the ADR names fix.
**Improve unpinning**
It was possible that the same client was picked after `unpin` call.
This commit makes sure that different waiting request will be picked.
> Improve unpinning

- server/consumer.go
- server/jetstream_consumer_test.go
This PR introduces few changes & improvements to Pinned Consumers
**Fix pinned TTL timer when its assigned from existing waiting request**
Until now, we were resetting Pinned TTL only if pin was set on incoming
Pull Request, but not when we were pinning an existing waiting request.
It also simplifies some logic.
**Switch to slice of PriorityGroupState**
Previously, we were storing just the pinned IDs, but to be more
future-proof, this commit will switch approach to store a struct.
It also adds `PinnedTS` which can be useful for debugging pinned consumers.
cc @ripienaar @jnmoyne 
> Change Consumer Priority Group State info and fix pinned TTL

- server/consumer.go
- server/jetstream_consumer_test.go
fixes #6076 
When starting by time option was used , a different codepath was taken when calculating starting sequence for the consumer. That codepath had off by one bug.
> Fix consumer starting sequence with start time and multiple filters

- server/jetstream_cluster.go
During shutdown calls to `js.processConsumerAssignment` can short-circuit with:
```go
if s == nil || noMeta || shuttingDown {
return
}
```
Ensure that we don't up `n.Applied` and snapshot after while we're shutting down, as we can't be sure we've actually applied those entries.
> [FIXED] Freeze `n.Applied` for cluster when shutting down

- server/jetstream_cluster_4_test.go
This may not fix this test entirely, but right now all of the different R=3 permutations are doing different things, so the results that it gives us are not comparatively useful at all. Instead this PR harmonises all the R=3 tests.
> Update params in `TestJetStreamClusterStreamOrphanMsgsAndReplicasDrifting`

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
If the `cc.meta.Propose` fails, for example due to restarts, the `sa.consumers[ca.Name] = ca` would have staged a consumer that will never be successfully added. That consumer would then become part of the next snapshot (for example during shutdown), which meant that that server had a ghost consumer it was unable to clean up.
This does not fully solve the ghost consumers issue, but this should contribute to the final solution.
> [FIXED] Ghost consumers after failed meta proposal

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
Consumers with many filtered subjects and large streams could suffer from slow creation times due to NumPending() being called for all filtered subjects.
This improvement is similar to the LoadNextMsgMulti for consumers with large number of filtered subjects.
Also fixed a bug in normal NumPending for memstore.
> Introduce a NumPendingMulti that uses a sublist for efficient selection.

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_cluster_4_test.go
- server/norace_test.go
During meta recovery `ru.updateConsumers` and `ru.removeConsumers` would not be properly cleared since the move from `map[string]*consumerAssignment` to `map[string]map[string]*consumerAssignment`. Which meant that consumers that needed to be removed were both in `ru.removeConsumers` and left in `ru.updateConsumers`. Resulting in a ghost consumer.
Also don't clear recovering state while we still have items to process as part of recovery.
De-flakes `TestJetStreamClusterLostConsumers`, and makes `TestJetStreamClusterConsumerLeak` more reliable by re-introducing the `ca.pending` flag. Since the consumer leader responds for consumer creation, but meta leader responds for consumer deletion, so need to have the consumer assignment available so meta leader can respond successfully. …
> [FIXED] Ghost consumers during meta recovery

- server/jetstream_cluster_3_test.go
RAFT group's subs are closed asynchronously, so there could be some left when checking right after calling `server.DisableJetStream()`. Eventually all subs should be gone.
> De-flake TestJetStreamClusterInterestLeakOnDisableJetStream, RAFT groups close asynchronously

- server/norace_test.go
The test failed on CI, but also sometimes locally. Had this fail locally just now with:
```
norace_test.go:11087: require 74.138µs to be less than 46.426µs
```
Improved the require to also report the time spent, as well as be <5ms.
> De-flake TestNoRaceJetStreamClusterCheckInterestStatePerformanceWQ

- server/jetstream_super_cluster_test.go
A stream move could be completed when looking at the stream info, but the meta leader could still deny move updates for a short time while state is cleaned up (i.e. the old peers are not removed yet). This doesn't happen often locally, but would happen more when running in CI.
> De-flake TestJetStreamSuperClusterMovingStreamAndMoveBack

- server/raft_test.go
> De-flake `TestNRGCandidateDontStepdownDueToLeaderOfPreviousTerm`

- server/raft.go
- server/raft_test.go
If we are leader and store two entries, the first having quorum and being committed/applied and the second not having quorum. A new leader should be able to truncate the second entry.
That was not possible before as the `n.loadEntry(ae.pindex)` and `n.truncateWAL(eae.pterm, eae.pindex)` combination would remove two entries, not just one.
We now check if the entry stored at `ae.pindex` has a matching term with `ae.pterm`, if so we can truncate entries past that point and then simply continue storing that append entry. Instead of needing to truncate, stop, get a heartbeat, start catchup, get the same append entry again, store it, get the next entry, stop catchup, etc. In this case we can now just, truncate and store.
> NRG (2.11): When term matches, simply truncate and store append entry

- server/stree/dump.go
- server/stree/node10.go
- server/stree/node16.go
- server/stree/stree_test.go
Although we probably don't want too many different node sizes here, the `node10` case is particularly interesting because it perfectly fits the full 0-9 numeric range without wasting bytes. In fact it saves 96 bytes (208 bytes instead of 304) compared to using `node16` for the same purpose.
This means memory savings for tracking subjects which are either mostly numerical throughout, or have tokens that are primarily numerical.
For a subject space that is mostly numerical, this can be several GBs less at the half-billion subjects mark and the saving can grow above that.
> Add `node10` to stree

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/norace_test.go
- server/stream.go
Detect if we receive an ack past our last stream sequence.
We also no longer register pre-acks when we detect this from a consumer snapshot since we properly handle this now and this could lead to excessive memory usage.
> [IMPROVED] Pre-acks handling, detecting ack for out of bounds sequence.

- server/store.go
- server/store_test.go
When a `DeleteRange` was used to mark deletes, when looping over it with `dr.Range(..)` it would delete one message too much.
Compared with a `DeleteSlice` the `DeleteRange` also didn't return the correct `last` for `dr.State()`. Also being +1 what it should be.
> [FIXED] DeleteRange deletes one message too much

- server/filestore.go
- server/memstore.go
- server/sublist.go
- server/sublist_test.go
This optimises #6089 by ensuring that we don't over-walk either the sublist or the subject tree, instead only matching the subject tree on subjects for which the sublist expresses interest.
On my machine, in the `JetStreamConsumeWithFilters` benchmark with `-benchtime 1000x`, this reduces the CPU time taken by `NumPendingMulti` by 19.41 seconds, reducing it to only 0.06 seconds.
> Use interest-based intersection for `NumPendingMulti`

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_consumer_test.go
- server/jetstream_errors_generated.go
- server/jetstream_events.go
After round of feedback, few changes were requested:
**Fix unpin advisory name**
Copy-paste mistake was made in unpin advisory name.
**Fix PinnedTS**
It was meant to return time when pinned happened, not the daedline.
**Add check for group name**
As the ADR for Priority Groups was [also updated](https://github.com/nats-io/nats-architecture-and-design/pull/311) after feedbach, this PR implements that.
cc @ripienaar @jnmoyne 
> Improve pinning/unpinning in Priority Groups

- server/jetstream_jwt_test.go
test(flapper): fix TestJetStreamJWTMove - by removing a check on stream update for the configuration, likely the server was able to accomplish the move, right after, the test will assert that C2 is the stream was placed in the correct cluster
Signed-off-by: Alberto Ricart <alberto@synadia.com>
> fix TestJetStreamJWTMove flapper

- server/filestore_test.go
Using `crand` was unpredictable because it might produce bytes that are a valid subject and therefore we wouldn't notice the problem in `recoverFullState`. Dropping in a UTF-8 rune error trips the detection always and is therefore more reliable.
> De-flake `TestFileStoreCorruptPSIMOnDisk`

- server/jetstream_cluster.go
If we are reassigning a stream assignment to a different placement, i.e. due to insufficient resources or another placement error, then don't process any further stream assignment results for that stream until the new assignment is processed. Otherwise we might generate multiple new assignments unnecessarily which could delete/recreate/update the stream multiple times, potentially on different peer sets.
This should also de-flake `TestJetStreamSuperClusterConcurrentOverflow`.
> Don't process multiple stream assignment responses for the same assignment

- server/consumer.go
`mset.noInterest(..)` mentions it requires a write lock to be held:
```go
// Check if there is no interest in this sequence number across our consumers.
// The consumer passed is optional if we are processing the ack for that consumer.
// Write lock should be held.
func (mset *stream) noInterest(seq uint64, obs *consumer) bool {
return !mset.checkForInterest(seq, obs)
}
```
This wasn't done in `cleanupNoInterestMessages`.
> [FIXED] `mset.noInterest` requires write lock

- server/jetstream_cluster_1_test.go
> De-flake `TestJetStreamClusterConsumerAckSyncReporting`

- server/client.go
- server/leafnode_test.go
In complex setup, a message produced from a cluster that had queue interest from leafnodes (either hub or spoke) would sometimes not deliver a message if the interest was a leafnode that had the interest on behalf of a gateway.
In the setup described in the issue this PR fixes, "Cluster B" may have picked "Cluster C", but that cluster does not have local queue interest, only the leafnode interest from "Cluster B", and would pick a LEAF connection to this cluster, but then suppress the message since it came from "B" so "C" cannot send it back there.
But picking a queue sub for "B" in "C" would then prevent the message to be delivered to the gateway "D".
Resolves #6125
> [FIXED] LeafNode: queue distribution with daisy-chain and gateway

- server/jetstream_cluster_4_test.go
> Fix data race in `TestJetStreamClusterMetaSnapshotMustNotIncludePendingConsumers`

- server/websocket.go
The `cp.Write()` call may have been partial and we would not have noticed.
> WebSocket: Ensure full writes to compressor

- server/sendq.go
This reduces allocations in the NRG `sendRPC` and `sendReply` functions by promoting buffer reuse.
> NRG: Reduce sendq allocations

- .travis.yml
This updates the patch versions. It also updates the version that we use for goreleaser — all releases are currently built using Go 1.22, but there isn't really a good reason why we shouldn't build them with Go 1.23 instead, since there will be new compiler optimisations we can take advantage of.
> Update to Go 1.23.3/1.22.9, use Go 1.23 for goreleaser

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_3_test.go
- server/memstore.go
Made `o.Update(state)` consistent for file and mem stores. For example: mem would not report for certain error conditions and file would not report an error for an error condition.
Also fixed integer underflow in `o.checkAckFloor`.
> [FIXED] Make `o.Update(state)` consistent for file and mem & fixed int underflow

- server/jetstream_cluster_4_test.go
Should solve this data race, where `rn.updateLeader(noLeader)` was called without holding the lock.
```
Write at 0x00c0011d6da8 by goroutine 238071:
github.com/nats-io/nats-server/v2/server.(*raft).updateLeader()
/home/travis/build/nats-io/nats-server/server/raft.go:3212 +0x1fa
github.com/nats-io/nats-server/v2/server.TestJetStreamClusterDesyncAfterErrorDuringCatchup.func2()
/home/travis/build/nats-io/nats-server/server/jetstream_cluster_4_test.go:3970 +0x1f2
github.com/nats-io/nats-server/v2/server.TestJetStreamClusterDesyncAfterErrorDuringCatchup.func3()
/home/travis/build/nats-io/nats-server/server/jetstream_cluster_4_test.go:4046 +0xc56
testing.tRunner()
/home/travis/sdk/go1.23.3/src/testing/testing.go:1690 +0x226
testing.(*T).Run.gowrap1() …
```
> Fix data race when updating leader

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
We could have an empty apply queue length, but have stored uncommitted entries. If we then call `SendSnapshot` when becoming consumer leader we would be reverting back to previous state.
This was also an issue for meta leader changes, which was fixed in https://github.com/nats-io/nats-server/pull/5700. This PR fixes it for consumer leader changes.
> [FIXED] Don't SendSnapshot on becoming consumer leader

- server/consumer.go
- server/jetstream_consumer_test.go
Match the check of the backoff and maxDeliver configs with the official documentation -> https://docs.nats.io/nats-concepts/jetstream/consumers#:~:text=The%20sequence%20length,MaxDelivery
Documentation, tell that `Backoff ` config **must** be **less than or equal** to `MaxDelivery`. But we were checking the opposite 
Signed-off-by: Luisao <luisgustavomacedo13@gmail.com>
> [FIXED] check of the backoff and max delivery configs

- server/consumer.go
- server/jetstream_cluster.go
`store.UpdateDelivered` would always be called, without checking quorum. Which meant that we could get a consumer to be ahead on delivered after switching leader. This change makes `o.updateDelivered` consistent with `o.updateAcks`, which does the same; if clustered propose through RAFT, if not just update delivered directly.
> [FIXED] only `UpdateDelivered` with quorum when clustered

- server/jetstream_cluster_3_test.go
- server/norace_test.go
`TestJetStreamClusterParallelStreamCreation` called `c.waitOnServerCurrent(nl)` whereas it should've called `c.waitOnStreamCurrent(nl, globalAccountName, "TEST")`. So it waits for the stream to be current, and not just the meta layer.
Also slightly extended logging where we'd only print `"Expected no errors, got 1"`. Now also logging the first received error to give more context what went wrong.
> De-flake TestJetStreamClusterParallelStreamCreation & improve logging when `len(errCh) > 0 `

- server/norace_test.go
- server/test_test.go
Previous behaviour of checking interface is `nil` didn't do the right thing as a `nil` parameter could still be wrapped in an interface descriptor that itself would be non-`nil`, so use reflection instead.
> Tests: Fix `require_NotNil`

- server/raft.go
- server/raft_test.go
This adds support for reply subjects on forwarded proposals, so we can know whether or not a leader has acted upon those proposals yet.
The `ForwardProposal` function does NOT yet use this functionality as we cannot yet know in a mixed-version or upgrade scenario yet if the remote side will be able to respond.
> NRG: Support for replying to forwarded proposals

- server/client.go
- server/const.go
- server/gateway.go
- server/leafnode.go
- server/leafnode_test.go
- server/parser.go
- server/reload.go
- server/route.go
- server/routes_test.go
- server/server.go
- test/new_routes_test.go
- test/test.go
There were multiple issues, but basically the fact that we would not store the routed subscriptions with the origin of the LEAF they came from made the server unable to differentiate those compared to "local" routed subscriptions, which in some cases (like a server restart and the resend of subscriptions) could lead to servers sending incorrectly subscription interest to leaf connections.
We are now storing the subscriptions with a sub type indicator and the origin (for leaf subscriptions) as part of the key. This allows to differentiate "regular" routed subs versus the ones on behalf of a leafnode.
An INFO boolean is added `LNOCU` to indicate support for origin in the `LS-` protocol, which is required to properly handle the removal. Therefore, if a route does not have `LNOCU`, the server …
> [FIXED] LeafNode: propagation of (no)interest issues

- server/jetstream_test.go
This test was ignoring errors from some calls that could possibly fail. As a result the occasional failures could not be traced back exactly to an issue.
Refresh this tests:
- Check for all errors
- Increase the number of messages
- Verify uniqueness of messages delivered
- Comments
> De-flake TestJetStreamAckExplicitMsgRemoval

- server/jetstream_super_cluster_test.go
Request to cancel the move sometimes lands as the stream is being moved
and at that point there is not leader hence no response is sent back.
With this change we're retrying the request and falling back to the case
later in the test where we skip as stream move is not in progress.
Signed-off-by: Ziya Suzen <ziya@synadia.com>
> De-flake `TestJetStreamSuperClusterTagInducedMoveCancel`

- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
`os.Remove(filepath.Join(n.sd, snapshotsDir, "*"))` doesn't remove all files in the snapshots directory. This PR ensures the snapshots dir is cleaned up for in-memory WALs.
> NRG: empty snapshots dir if memory WAL

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
Fixes this data race:
```
Read at 0x00c0034a4720 by goroutine 19950:
runtime.mapiterinit()
/home/travis/sdk/go1.23.3/src/runtime/map.go:877 +0x0
github.com/nats-io/nats-server/v2/server.TestJetStreamClusterMaxConsumersMultipleConcurrentRequests()
/home/travis/build/nats-io/nats-server/server/jetstream_cluster_2_test.go:2080 +0xcc6
testing.tRunner()
/home/travis/sdk/go1.23.3/src/testing/testing.go:1690 +0x226
testing.(*T).Run.gowrap1()
/home/travis/sdk/go1.23.3/src/testing/testing.go:1743 +0x44
Previous write at 0x00c0034a4720 by goroutine 20101:
runtime.mapassign_faststr()
/home/travis/sdk/go1.23.3/src/runtime/map_faststr.go:223 +0x0
github.com/nats-io/nats-server/v2/server.(*jetStream).processConsumerAssignment() …
```
> [FIXED] Hold JS lock when accessing stream assignment

- server/leafnode.go
- server/leafnode_test.go
Leaf node credential parsing was using a regular expression that didn't handle CRLFs correctly
Fix #6167
Signed-off-by: Your Name <alberto@synadia.com>
> fix(leafnode): credentials parsing for leafnode connections doesn't handle CRLFs correctly

- server/client.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/norace_test.go
- server/server.go
Processing a missing consumer was a heavier operation on the meta-layer and could lead to API queue buildup.
This processes that condition at point of entry to the system vs at the meta-layer.
If the consumer assignment does exist we process as normal for now.
Also moved jetstream clustered state and system account to atomics to avoid lock contention.
Add in lookup for both stream and consumer assignments at the same time.
> [IMPROVED] Bypass meta-layer's API queue for non-existent consumers.

- server/jetstream_cluster_4_test.go
Adds explicit test showing behavior of consumer state when ack is received after a stream has been recreated.
> Add test covering handling of delayed acks from recreated streams

- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
Based on https://github.com/nats-io/nats-architecture-and-design/pull/309
Compact the keys and remove the 'created' keys.
> Compact JetStream asset versioning

- server/events.go
- server/jetstream_cluster.go
This should reduce the size of metalayer snapshots quite significantly by only including the `Account`, `Service` and `Cluster` fields from the `ClientInfo`, as those are the only ones that are relevant from a snapshot.
> Don't include unnecessary `ClientInfo` fields in metalayer snapshots

- conf/parse.go
- conf/parse_test.go
- main.go
- server/monitor.go
- server/opts.go
- server/opts_test.go
- server/reload.go
- server/reload_test.go
- server/routes_test.go
- server/server.go
- server/signal_test.go
Makes the server generate a digest representing the expanded version of the parsed configuration:
```
$ nats-server -c foo.conf -t
nats-server: configuration file configs/foo.conf is valid (sha256:e14d9fd914ee4a83c481c6bf97b44d7bc23d8f475f7f30af0c4e96ab4e5ad00c)
```
It can be inspected via `/varz`:
```
"config_load_time": "2023-07-19T14:28:28.77128Z",
"config_digest": "sha256:6a383afa5fa6e00262105fbf061cabf48db892d1aa677f491dbabe7894393413",
"system_account": "$SYS"
```
And it is also logged at runtime making it possible to check whether the reload had side effects:
```
[1935] 2023/07/19 02:57:29.245020 [INF] Using configuration file: configs/foo.conf (sha256:6a383afa5fa6e00262105fbf061cabf48db892d1aa677f491dbabe7894393413)
...
[1935] 2023/07/19 02:58:06.993874 [DBG] Trapped "hangup" …
```
> v2.11: Add digest to represent configuration state

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/norace_test.go
- server/stream.go
For an Interest or WorkQueue stream messages will be removed once all consumers that need to receive a message have acked it.
For a clustered stream each consumer would ack and remove a message by themselves. This can be problematic since that introduces different ordering between servers. For example when using DiscardOld with MaxMsgs, which could result in stream desync. Proposing the message removal ensures ordering between servers.
> [FIXED] (2.11) Propose message delete for clustered interest stream

- server/jetstream_cluster.go
- server/jetstream_test.go
- server/stream.go
The current duplicate tracking has a couple of problems, namely that the `ddmap` capacity is potentially never reclaimed if it grows suddenly, and secondly that we have to constantly monitor `ddarr`'s capacity and copy it to stop the array from growing infinitely too.
This PR makes the following changes:
- `ddmap` is now using the stree, which means there is efficient in-place deduplication of message IDs and no infinitely growing backing capacity;
- `ddarr` and `ddindex` are now gone, replaced with linked-list references and `ddnext` and `ddlast` tracking, so we also don't need to watch the capacity and reallocate this either;
- `ddtmr` is now only scheduled when there is actually something to do.
Also added a unit test to prove the behaviour as well as the linked-list stitching. …
> Refactor duplicate `Nats-Msg-Id` tracking

- server/jetstream_cluster.go
We would not expect to respond to a consumer assignment after, e.g. a restart, and we don't store these for stream assignments already, therefore the `subject` and `reply` fields do not need to be encoded for consumer assignments either.
Similarly, the `stream` name doesn't need to be repeated for each consumer assignment either, as we can just pull that out of the parent stream assignment when decoding, so don't encode that either.
This should further reduce the size of meta snapshots and, with it, reduce their encoding/decoding time.
> Reduce size of meta snapshots further

- server/jetstream_cluster.go
This should prevent the following from happening during shutdown:
```
[1] 2024/11/30 23:09:21.559476 [DBG] JETSTREAM - JetStream connection closed: Client Closed
[1] 2024/11/30 23:09:21.561754 [DBG] JETSTREAM - JetStream connection closed: Client Closed
fatal error: sync: Unlock of unlocked RWMutex
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcde26b]
goroutine 623 [running]:
sync.fatal({0x12c1d0a?, 0xc040000000?})
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:1007 +0x18
sync.(*RWMutex).Unlock(0xc0000db7e4)
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/sync/rwmutex.go:208 +0x7e
panic({0x11e5780?, 0x1b73560?})
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/panic.go:770 +0x132 …
```
> Check for sys being ready before calling sysRequest

- server/jetstream_cluster.go
This was changed in #6189 but we need it to be in the snapshot after all in order to be able to safely roll back to earlier versions.
> Re-add `"stream"` to consumer assignments

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
JetStream catchup could have a follower delete too much because it could send too large delete ranges.
This was due to `LoadNextMsg` being used and not checking if the requested `last` sequence was exceeded. This could happen if `LoadNextMsg` was used AND `last < state.LastSeq` AND there's at least one deleted message at sequence `last+1`.
Given you have a stream with a message at sequence 1 and 100, with a gap in the middle, there were two issues when requesting only to receive what message is stored at sequence 5 (for example):
- A delete range would be sent with sequence 5 and number of deletes of 95, this should be 1 delete.
- If the message at sequence 100 was deleted it would also return the same as above, this should also be only 1 delete. …
> [FIXED] JetStream catchup may return/delete too much

- server/jetstream_cluster_1_test.go
> Fix `TestJetStreamClusterConsumerAckOutOfBounds` not run in CI

- server/stream.go
If a stream that is sourcing is R1, setup the consumers inline on setLeader which is at server start on recovery of the stream.
> [IMPROVED] Process sourced streams consumer sequences inline iff R1.

- server/filestore.go
`flushStreamStateLoop` would always run on the same interval for each and every stream. Introduce jitter to spread out after restarts.
> Add jitter for flushing stream state

- server/errors.json
- server/jetstream_errors_generated.go
As the error is returned from a call to create/update a consumer "Valid name" was potentially confusing as the user may think the problem is with the consumer's name, not the priority group.
> Improve JSConsumerInvalidGroupNameErr's description

- server/filestore.go
This should provide less contention on systems where we have plenty of headroom for more I/O-blocked threads.
> Increase disk I/O semaphore on systems with more CPU cores

- server/filestore.go
- server/memstore.go
- server/store_test.go
Subject state would not always remain consistent given a specific pattern of message removals.
There were three bugs:
- `recalculateFirstForSubj` in memstore would do `startSeq+1`, but filestore would always just start at `mb.first.seq`. These are now consistent.
- `recalculateFirstForSubj` was not called when `ss.Msgs == 1`, which could mean we had a stale `ss.FirstSeq` if it needed to be recalculated.
- If after recalculation it turns out `ss.FirstSeq` equals the message we're trying to remove, we need to `recalculateFirstForSubj` again, since `ss.Last` is also lazy and could be incorrect.
Apart from that, filestore and memstore are now both equivalent when it comes to first updating per-subject state and then removing the message, as well as `removeSeqPerSubject` and how it updates the …
> [FIXED] Subject state consistency

- go.mod
- go.sum
- server/filestore.go
Includes:
- https://github.com/nats-io/nats-server/pull/6229
- https://github.com/nats-io/nats-server/pull/6230
- https://github.com/nats-io/nats-server/pull/6233
> Cherry-picks for 2.10.23-RC.12

- server/raft_helpers_test.go
- server/raft_test.go
Fixes `TestNRGHeartbeatOnLeaderChange` by checking if new entries are actually being applied. This was not possible before because it would always check a total of 0. If all proposals would fail, this test would still pass.
More importantly `a.sum` was not reset, which meant that state before the call to `restart()` would be preserved, and replayed entries during catchup/recovery would be re-applied.
Also added a call to `a.n.WaitForStop()` in `a.stop()`. Otherwise things could still be around and not properly stopped when we restart with `a.restart()`.
> De-flake RAFT state adder tests

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/store.go
- server/store_test.go
Improve performance by only setting `ss.Last` during recalculation, so only when it's needed.
Also fixes a bug where `ss.Last` was not kept up-to-date if `ss.Msgs > 1`, by introducing a `ss.lastNeedsUpdate` just like `ss.firstNeedsUpdate`.
> [FIXED] Improve per-subject state performance & keep `ss.Last` up-to-date

- server/client.go
Fixes performance issues noted in #6058. Attempts to prune reply map every `replyPermLimit` messages or if it has been more than `replyPruneTime` since the last prune.
Resolves #6058 
Signed-off-by: Jack Morris <jack@jackmorris.me>
> [FIXED] Fix request/reply performance when using allow_responses perms

- server/filestore.go
- server/memstore.go
- server/store_test.go
If a stream, either in-memory or file-based, would be updated from having no `MaxMsgsPer` to having it set the messages would not be removed.
> [FIXED] MaxMsgsPerSubject limit not applied when updating from no value

- server/raft.go
- server/raft_test.go
If we're actively catching up, but `n.commit == n.applied`, we would mark it as current/healthy. This would result in healthz reporting healthy too soon based on timing.
Also removed the cancellation of catchup in `isCurrent`. We shouldn't be able to influence catchup based on if and how often we call healthz. Also because we might need to do 2 catchups back-to-back if our first catchup takes longer and after that catchup is finished we get a heartbeat that re-triggers catchup. If we would cancel catchup due to the health check we would erroneously be marked healthy, whereas we require another catchup still.
> NRG: Don't mark current/healthy while catching up

- server/monitor.go
- server/monitor_test.go
Return non-200 status codes if there are errors, also log (just the count, otherwise the log statement could explode in size).
> [FIXED] Healthz with details returns 200 OK even with errors

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_4_test.go
- server/raft.go
When a server restarts and is behind enough it will require to be caught up from a snapshot. If after receiving a snapshot from the leader the leader itself shuts down, the remaining server (in a R3 scenario) will become leader.
If this new leader is behind on applies it should not fulfill the catchup request. Messages that would be returned as part of the catchup might be deleted as part of the unapplied append entries. And sending these messages over to the follower would mean the follower wouldn't be able to remove them as part of the append entries if they were meant to be deleted.
Either way, the new leader is temporarily unable to fulfill the catchup request and must wait for its applies to reach the minimum required for the catchup response to be valid.
Signed-off-by: Maurice van …
> NRG (2.11): Don't run catchup when behind on applies

- README.md
Currently build badge on readme is broken (at least for me)
For some reason when image is on 'org' domain it works.
vs.
see also build tag on travis' own readme https://github.com/travis-ci/travis-web/blob/master/README.md
Signed-off-by: Ziya Suzen <ziya@synadia.com>
> Fix readme build badge

- server/websocket.go
- server/websocket_test.go
The server was incorrectly sending back a close message frame with status 1005 when not receiving a status in the close message frame from the client. This was wrong. This status was to be used internally to keep track that no status was received and therefore the server should not send a status back.
Also, the server was sending status 1006 in some error conditions, while the spec also states that this status must not be used to set the status, instead it was to internally keep track that there was an error condition.
Resolves #6259
> [FIXED] Websocket: handling of close message frame without status

- server/events.go
These are used by the cli and other tools to decode the responses from the z endpoints
> Adds a number of helper structs for z responses

- server/jetstream.go
- server/jetstream_test.go
The calculation should check if the current total plus what we want to store exceeds the max.
> [FIXED] JetStream would exceed limits calculation

- server/raft_test.go
`TestNRGSimple` was not actually testing anything, as `proposeDelta` asynchronously proposes the changes so the `waitOnTotal` would immediately pass even if none of the proposals went through (or even if `proposeDelta` was commented out).
> De-flake TestNRGSimple

- server/filestore.go
- server/jetstream_api.go
- server/store.go
Currently it's possible for errors to occur during the creation of a stream backup, but they are not properly reported to the user. Making it look like the backup was successful.
During stream backup, errors are reported through calling `writeErr`, which in turn writes an `errors.txt` file containing the error message:
https://github.com/nats-io/nats-server/blob/a07bde9fa7d499c7039f74cac9d11f4c046b9250/server/filestore.go#L8285-L8286
When performing a backup, for example through the CLI, even when this error is hit it reports as successful:
```
$ nats str backup stream stream-backup/
Starting backup of Stream "stream" with 10 MiB
386 KiB/s [=>--------------------------------------------]   4%
Received 386 KiB compressed data in 18 chunks for stream "stream" in 38ms, 13 MiB uncompressed …
```
> Improve stream backup error reporting

- server/raft.go
- server/raft_test.go
If truncation fails we would spin on retrying. Now only continue if `pindex/pterm` are aligned, otherwise responds non-success to the leader.
> NRG: Only continue if aligned with pindex/pterm

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
If the stream is ingesting loads of new messages, for example in a benchmark, either the `compactNumMin` or `compactSizeMin` would be reached fairly quickly. The `minSnapDelta` (10s) is used to not snapshot too often, since that would degrade performance.
However, if `clfs=0` then we'd be forcing snapshots every time the compact minimums are reached.
> NRG: When `clfs=0`, don't snapshot very often

- server/jetstream_cluster.go
Since the race condition of installing snapshots during shutdown was fixed in https://github.com/nats-io/nats-server/pull/6153, we have not re-introduced this snapshotting but done in the right place. (Meta already has this)
> Re-introduce stream/consumer snapshot on shutdown

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_helpers_test.go
- server/jetstream_super_cluster_test.go
- server/stream.go
This makes it possible to nominate a JetStream metaleader transfer to servers matching specific placement tags in addition to cluster names, or optionally, to a specific named server.
* If `preferred_server` is specified then placement will select that server only.
* Otherwise, either `cluster` or `tags` can be supplied for placement. If both the `cluster` and `tags` are supplied then the placement will select a server that matches both.
* If multiple `tags` are specified, the placement will select servers only if they match all supplied tags.
Also factors out some of the logic for making the preferred leader decision so that it could be reused for stream & consumer stepdowns.
> Add support for placement tags and `preferred` to metaleader stepdown request

- server/filestore.go
The `hbit` had two purposes depending on whether it was applied to the `mb.cache.idx` or the `rl` but it could be confusing. This PR adds a new `cbit` for clarity, although it has the same computed value. 
> Filestore: Disambiguate `hbit` usage with new `cbit` flag

- server/leafnode.go
- server/leafnode_test.go
If the hub has a user with subscribe permissions on a literal subject that the leaf is trying to create a queue subscription on, the interest may not be propagated.
The issue was caused by the fact that we were checking the permissions on the key (that includes subject and queue name) instead of the subject itself.
Resolves #6281
> [FIXED] LeafNode: queue interest on leaf not propagated with permissions on hub

- .github/actions/nightly-release/action.yaml
- .goreleaser-nightly.yml
- .goreleaser.yml
- .travis.yml
Switch to goreleaser v2, similar to:
https://github.com/nats-io/natscli/pull/1191
```
[alex@omenlaptop:nats-server] [13:15:58] goreleaser_v2_config []   NGS-Default-CLI
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
[alex@omenlaptop:nats-server] [13:16:02] goreleaser_v2_config []   NGS-Default-CLI
• checking                                 path=.goreleaser-nightly.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
```
```
> Goreleaser v2 config

- server/consumer.go
- server/jetstream_test.go
The drifting tests would occasionally fail due to the consumer pending count drifting. This was due to a race condition described on `checkNumPending`:
```
// Does some sanity checks to see if we should re-calculate.
// Since there is a race when decrementing when there is contention at the beginning of the stream.
// The race is a getNextMsg skips a deleted msg, and then the decStreamPending call fires.
// This does some quick sanity checks to see if we should re-calculate num pending.
// Lock should be held.
func (o *consumer) checkNumPending() uint64 {
```
This PR doesn't fix this race condition, but improves the tracking which improves test reliability. If the race condition happens we can still check if the deleted message is between `o.asflr` and the `o.sseq` that's skipped ahead. …
> Improve consumer pending count tracking during stream contention

- .goreleaser-nightly.yml
- .goreleaser.yml
Use commit time in mod_timestamp, as documented in:
https://goreleaser.com/customization/builds/#reproducible-builds
https://goreleaser.com/blog/reproducible-builds/
https://goreleaser.com/customization/templates/?h=templates#common-fields
Build two times:
```
goreleaser release --snapshot --clean -f .goreleaser.yml
mv dist/ ~/tmp/dist_before
goreleaser release --snapshot --clean -f .goreleaser.yml 
vimdiff dist/SHA256SUMS ~/tmp/dist_before/SHA256SUMS
```
Observe all the shasums are different:
Do the build two times, 
```
goreleaser release --snapshot --clean -f .goreleaser.yml
mv dist/ ~/tmp/dist_after
goreleaser release --snapshot --clean -f .goreleaser.yml 
vimdiff dist/SHA256SUMS ~/tmp/dist_after/SHA256SUMS
```
Observe that only rpm and deb packages are different
There was a feature …
> Make goreleaser archives reproducible

- server/consumer.go
Makes the change suggested in https://github.com/nats-io/nats-server/pull/6297#discussion_r1896181250
> Re-order condition in decStreamPending

- server/errors.json
- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster.go
- server/jetstream_errors_generated.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/norace_test.go
- server/raft.go
- server/store.go
- server/store_test.go
- server/stream.go
- server/thw/thw.go
This is an incomplete but somewhat-working implementations of per-message TTLs.
Notes:
- Adds `AllowMsgTTL` to stream config;
- Parses the `Nats-TTL` message header as a parsable duration, or if not, second precision;
- Bumps the `index.db` magic version so that we can add a new field for tracking how many TTL'd messages are in each message block (means that `index.db` needs to be rebuilt if downgrading);
- Adds a new `thw.db` to store the timed hash wheel state, and tries to rebuild it from a linear scan if it is missing or out-of-date.
Future work:
- Memory store support;
- Expires "never" including not aging out with MaxAge;
- Ability to update a TTL for a message;
- Decide what we want to do for enabling/disabling TTL support;
- Decide how mirroring/sourcing streams will handle TTL …
> Initial support for per-message TTLs

- server/filestore.go
`nextTTL` was not defaulted to `math.MaxInt64` so it would not cancel the age check in this condition: `if fs.state.Msgs == 0 && nextTTL == math.MaxInt64`.
> De-flake TestJetStreamClusterMirrorAndSourceExpiration

- .goreleaser.yml
- .travis.yml
This will generate a new set of SPDX-formatted SBOM files on a release using the the GoReleaser + Syft toolchain.
Travis currenly invocates GoReleaser so the Syft dependency needs to be installed ahead of the `deploy` action.
> Enable SBOM config for GoReleaser

- .travis.yml
This is a followup to #6306 which pins the Syft version.
> Pin Syft version on Travis

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/raft.go
There was a race with keeping peers up-to-date. When updating replicas of a stream up and down rapidly enough the peer state could desync since the update is handled by the meta layer, but the peer removal is handled by the stream. If the meta layer agreed on scaling the stream up to 5 replicas, but a peer removal came in after from an earlier downscale, then a server would end up with an incomplete peer list.
Since peer changes are done by the meta layer we can/should trust that does the right thing, and we don't need to fiddle by proposing peer removals ourselves.
Also, since the meta layer handles stream creates/updates and calls into `UpdateKnownPeers` already, we shouldn't then propose the peers (again) through the stream layer. …
> [FIXED] Peer removal race

- server/raft.go
- server/raft_test.go
There could be a call to `n.PauseApply()`, for example during recovery if a max size is reached or when doing a stream catchup. This pauses the commits but was not reflected by the health check. Should only report current/healthy if we're paused but still up-to-date, with pending commits we should wait for `n.ResumeApply()` to be called and applies to be current.
> NRG: Don't mark current/healthy while paused with pending commits

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/norace_test.go
- server/stream.go
If a message in a stream was removed/erased/purged the pre-acks would not be cleared for that sequence. This meant that pre-acks could remain and potentially result in a memory leak.
There was also a call to `mset.clearAllPreAcks(last)` where the write lock was not held. Updated `mset.setLastSeq` to require a write lock to already be held, so we don't need to keep locking/unlocking multiple times.
Also de-flakes `TestNoRaceJetStreamClusterUnbalancedInterestMultipleConsumers` due to:
- remaining pre-acks that should have been cleared
- messages being removed asynchronously due to going through proposals (added `checkFor`)
> [FIXED] Clear all pre-acks for seq upon removing message

- server/accounts.go
- server/events.go
- server/jwt_test.go
- server/monitor.go
- server/monitor_test.go
- server/mqtt_test.go
- server/server_test.go
This supersedes #5173 since it introduced a redundant field `LogicalName` on `Account` with the existing field `nameTag`.
The endpoints that are currently covered include:
- /accountz
- /accstatz
- /connz
- /subsz
- /jsz
The following endpoints also contain account metadata, but have not been implemented yet.
- /routez
- /gatewayz
- /leafz
> Add account name tag to monitoring endpoints

- server/jetstream_helpers_test.go
Benchmarks like `BenchmarkJetStreamPublish` would fail when changed to use memory-based storage with the following message:
```
BenchmarkJetStreamPublish/N=3,R=3,MsgSz=1024b,Subjs=1/Async[W:4000]
jetstream_benchmark_test.go:738: Publish timed out
```
This was due to the underlying error being hit:
```
Apply stream entries for '$G > S' got error processing message: insufficient resources (10023)
```
Making the maximums consistent so all file-based benchmarks/tests can also run for memory-based without timing out due to insufficient resources.
> Prepare benchmarks for memory streams

- server/events.go
- server/jetstream_cluster.go
This avoids JWTs etc from the client info from being encoded into stream and consumer assignments proposals when they are not needed.
This will reduce the network bandwidth required to send such proposals in some deployments, as well as reducing the memory footprint of proposals queued in memory and the disk footprint required for the metalayer WAL.
> Strip unnecessary `ClientInfo` fields from stream & consumer assignment proposals

- server/jetstream_helpers_test.go
- server/jetstream_jwt_test.go
Similar fix to https://github.com/nats-io/nats-server/pull/4533, but extending to some other clustered tests, as well as one super cluster test. Should prevent these tests from failing with `JetStream not enabled for account`. 
> De-flake by waiting for account fetch in (super) cluster

- server/jetstream_cluster_long_test.go
- server/raft_chain_of_blocks_helpers_test.go
- server/raft_test.go
Add 'Chain of Blocks' tests for Raft/NRG
Chain of Blocks is a simple state machine on top of Raft/NRG.
Values delivered through Raft are hashed allowing for easy verification of replicas divergence.
- Add one happy-path test
- Add one test for recovery/catchup
- Add a 'Long' randomized test
Signed-off-by: marco@nats.io
> Add more RAFT tests

- server/jetstream_test.go
Could take some time for `o.processStreamSignal` to be called and up `o.npc`. Without would sometimes fail with `jetstream_test.go:24773: require int64 equal, but got: 0 != 1`.
> De-flake TestJetStreamConsumerDecrementPendingCountOnSkippedMsg

- server/jetstream_cluster_2_test.go
`TestJetStreamClusterRedeliverBackoffs` would sometimes fail, even though it would be very close to the intended backoff:
```
jetstream_cluster_2_test.go:4216: Timing is off for 1, expected ~100ms, but got 99.846642ms
jetstream_cluster_2_test.go:4216: Timing is off for 0, expected ~25ms, but got 50.767748ms
jetstream_cluster_2_test.go:4216: Timing is off for 4, expected ~250ms, but got 249.95211ms
```
Allowing for a bit of leeway on both ends.
> De-flake TestJetStreamClusterRedeliverBackoffs

- server/jetstream_cluster_2_test.go
Calling `require_NoError` in a `checkFor` immediately fails the test and doesn't allow for retries. Also up the max timeout when doing stepdowns, as that might sometimes take longer as well.
> De-flake StreamResetOnExpirationDuringPeerDownAndRestartWithLeaderChange

- server/jetstream_test.go
Ack state could take some time to propagate, since the sent acks are not synchronous.
> De-flake TestJetStreamNextMsgNoInterest

- server/signal.go
- server/signal_test.go
Upon receiving `SIGTERM` we would exit with exit code 1, even though we successfully/gracefully shutdown.
This was also flagged by Antithesis as a correctness issue:
> Containers that exit normally (exit code 0) will not trip this property. Nor will containers exiting with codes 137 and 143, which correspond to SIGKILL and SIGTERM on the container process. This is because attempts to shut down containers with standard tools may generate these codes.
>
> To avoid false positives, please ensure that the main process running within each of your containers exits with code 0 when terminating without error.
We should return a successful/0 exit code when we were able to gracefully shutdown, just like when receiving `SIGINT`.
Have added 2.11 in the title, as we might want to put this into a minor …
> [FIXED] (2.11) Successful exit code for SIGTERM

- server/events.go
- server/jetstream_api.go
Otherwise these advisories can end up very large and take more CPU time to encode.
> Remove JWT & alternates from `$JS.EVENT.ADVISORY.API` and stream snapshot/restore advisories

- server/consumer.go
Idle heartbeats for push consumers were added in https://github.com/nats-io/nats-server/pull/1965
But for pull consumers, it is a field in `JS.API.CONSUMER.MSG.NEXT`
https://github.com/nats-io/nats-server/pull/2865/files#diff-9c075c47b0690a821ad35caa26308b69adeb132042f062eef75513db2a26638aR580
https://beta-docs.nats.io/ref/protocols/jetstream#pull-next-messages
Clarify that by moving the field close to other push-based consumer fields
See also
https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-9.md
> Clarify that Heartbeat field in ConsumerConfig only applies to push consumer

- server/filestore.go
- server/jetstream_test.go
- server/stream.go
A message with `Nats-TTL: never` will never expire, even if the `MaxAge` policy is set.
> Add support for "never expires" TTL

- server/consumer.go
- server/jetstream_test.go
Reverts the change made in https://github.com/nats-io/nats-server/pull/6297. The change did (somewhat) improve the reliability of the drifting tests if the `o.npc--` was done as a result of contention, but resulted in a regression if `o.npc--` was done twice when a message was acked that did not move the ack floor up for WorkQueue/Interest retention.
This PR fixes what would otherwise have been a regression.
We really should try to fix the race condition itself though (outside of this PR). Without fixing it the pending count can be incorrect with no way to be resolved unless all messages are consumed, or we'd need to manually recalculate.
> [FIXED] Don't decrement pending count twice after ack

- go.mod
- go.sum
- internal/antithesis/noop.go
- internal/antithesis/test_assert.go
- server/jetstream_helpers_test.go
- server/server_test.go
- server/test_test.go
1. Introduce dependency on antithesis-sdk-go (default NOOP variant)
2. Introduce assertions utilities suitable for use in tests
3. Instrument frequently used test utilities with the new assertions
N.B. unless the `enable_antithesis_sdk` tag is specified at build time, both the SDK and the assertions wrappers are NOOP, and should have no effect.
This will also facilitate other Antithesis one off experiments since developers no longer have to manually add the SDK to their branch.
Signed-off-by: Your Name <marco@nats.io>
> Facilitate flake tests reproduction with Antithesis

- server/consumer.go
Since `deleteNotActive` already runs in its own goroutine via `time.AfterFunc`, we just create more work for the scheduler by having extra goroutines running on top of that.
> Do not start additional goroutines from consumer `deleteNotActive`

- server/errors.json
- server/jetstream_errors_generated.go
Tiny improvement to the description of JSConsumerPullRequiresAckErr to specify which ack policy is required for WQ streams.
> Improve description for JSConsumerPullRequiresAckErr

- server/jetstream_cluster.go
Need to capture `rg.node` while the JetStream lock is held, otherwise stopping an asset could race and it could be set back to `nil`.
> Fix panic in `isGroupLeaderless`

- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_helpers_test.go
- server/jetstream_jwt_test.go
- server/jetstream_test.go
Deponds on https://github.com/nats-io/nats-server/pull/6345
Includes the following de-flakes:
- https://github.com/nats-io/nats-server/pull/6329
- https://github.com/nats-io/nats-server/pull/6330
- https://github.com/nats-io/nats-server/pull/6331
- https://github.com/nats-io/nats-server/pull/6332
- https://github.com/nats-io/nats-server/pull/6334
And this data race fix:
- https://github.com/nats-io/nats-server/pull/6150
> Cherry-pick de-flakes for 2.10.25-RC.1

- server/consumer.go
This ensures that we stop these goroutines more quickly when either the server or the JetStream system shuts down.
This also avoids a race in `TestJetStreamClusterGhostEphemeralsAfterRestart`, as the unit test was reverting a modified constant before these goroutines would have finished in some cases.
> Ensure `deleteNotActive` stops on JetStream or server shutdown

- server/consumer.go
Pinned timestamp was set when the timer was triggered, instead when the new ID was set.
Additionally, this PR make the timestamp format consistent with other timestampts by setting it to UTC.
> Fix setting first Pinned TS and use UTC

- server/filestore.go
This avoids an unnecessary `TTL state is outdated` message in the log when there is nothing to do.
> Don't run TTL state recovery if no messages

- server/jetstream_api.go
- server/jetstream_cluster_3_test.go
> Fix race condition between server shutdown and consumer info

- server/jetstream_api.go
- server/jetstream_cluster_4_test.go
This updates the JS API workers to use `popOne`, so that if the queue stacks up at all, the recovery is fairer across workers, rather than single workers stealing the entire queue.
This was extracted from #6342.
> Use `popOne` in JS API routed request workers

- go.mod
- go.sum
- server/consumer.go
- server/events.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_events.go
- server/jetstream_helpers_test.go
- server/jetstream_jwt_test.go
- server/jetstream_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/memstore.go
- server/norace_test.go
- server/raft.go
- server/raft_test.go
- server/store.go
- server/store_test.go
- server/stream.go
- https://github.com/nats-io/nats-server/pull/6323
- https://github.com/nats-io/nats-server/pull/6324
- https://github.com/nats-io/nats-server/pull/6291
- https://github.com/nats-io/nats-server/pull/6226
- https://github.com/nats-io/nats-server/pull/6235
- https://github.com/nats-io/nats-server/pull/6277
- https://github.com/nats-io/nats-server/pull/6279
- https://github.com/nats-io/nats-server/pull/6283
- https://github.com/nats-io/nats-server/pull/6289
- https://github.com/nats-io/nats-server/pull/6316
- https://github.com/nats-io/nats-server/pull/6317
- https://github.com/nats-io/nats-server/pull/6325
- https://github.com/nats-io/nats-server/pull/6326
- https://github.com/nats-io/nats-server/pull/6335
- https://github.com/nats-io/nats-server/pull/6338
- …
> Cherry-picks for 2.10.25-RC.1

- server/consumer.go
- server/jetstream_consumer_test.go
This was not seen in tests, as `ConsumerConfig.PriorityPolicy` is `omitempty` and `PolicyNone` is 0, but could still fail in other structs.
> Add missing marshaling case for PriorityPolicy

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/norace_test.go
Since we use `MarshalJSON()` on some types, we must be careful that a JSON marshalling error cannot be dropped.
> Error handling in `metaSnapshot`

- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
As per the ADR:
> When either these settings are set the Stream should require API level `1`.
> Per-message TTLs set metadata API level to `1`

- server/jetstream_helpers_test.go
Cluster tests would sometimes fail with the following error message:
```
jetstream_helpers_test.go:774: Expected a fully formed cluster, only 0 of 3 peers seen
```
This was due to a logic error in the tests, where it was assumed that once a meta leader is chosen it will remain the same. That's not always true as the meta leader can still shift around. So, keep fetching the latest leader and check the peers on that.
Previously it would fail by selecting a meta leader, the meta leader would change, and the follower would then be used to request peers on. But because of the following lines in `JetStreamClusterPeers()`:
```go
cc := js.cluster
if !cc.isLeader() || cc.meta == nil {
return nil
}
```
You'd get no peers at all, leading into that error message. …
> Test: expected a fully formed cluster error

- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
Factored out the rejection behaviour from #6298 so that it can be reviewed/merged separately from the sourcing/mirroring.
> Reject TTL messages when not enabled on stream

- server/leafnode.go
- server/leafnode_test.go
- server/route.go
If a cluster has leafnode connections and each have the same queue group, the loss of a leafnode connection could cause the server in the "hub" cluster to drop interest across a gateway for this queue group.
The issue is fixed by properly accounting for all queue sub and unsub in the server gateway interest map.
> [FIXED] LeafNodes: Queue interest may be lost in super cluster

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/test_test.go
This ensures that messages received from an upper-layer catchup also have their TTLs added to the timed hash wheel correctly on the follower.
(Also updates `require_NotNil` to be variadic because it looks nicer in the test.)
> Correctly handle TTLs from upper-layer stream catchups

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_helpers_test.go
- server/jetstream_test.go
- server/jetstream_versioning.go
- server/memstore.go
- server/store.go
- server/stream.go
This PR adds the `LimitsTTL` functionality for system tombstones when a subject is removed via `MaxAge`. The tombstone will have the header `Nats-Applied-Limit` and the specified `LimitsTTL` value as the TTL.
Further limits and/or administrative actions to follow separately.
This also requires API version 1, cannot be set if TTLs are disabled and cannot be combined with a mirror configuration.
> Add support for subject delete markers by `MaxAge`

- server/filestore.go
Static analyzer found unclosed filehandle tmpFD in case of errors. It is not strictly necessary as GC will eventually close tmpFD, but explicit call of Close is always better than magic finalizer.
Based on the [SO discussion](https://stackoverflow.com/questions/58351084/does-go-automatically-close-resources-if-not-explicitly-closed)
Signed-off-by: Dmitry Dorofeev <dima@yasp.com>
> fixed unclosed tmp file handle in filestore.go

- server/consumer.go
- server/jetstream_consumer_test.go
During server restarts (for example) a response to an `AckSync` could be lost which leads into a timeout. If the client would then retry the `AckSync` it should eventually come back successful.
This was true for `AckExplicit`, but for `AckAll` the retried `AckSync` would always timeout. In this case the server would not respond to the client at all, making it impossible for the client to know if the ack for that message went through.
> [FIXED] Don't timeout for retried AckAll

- server/consumer.go
- server/jetstream_consumer_test.go
Contains two fixes:
1. If a message is Acked, `o.awl` is incremented and the message is pushed into `o.ackMsgs`. However, if the consumer leader steps down (with `o.setLeader(false)`), `o.ackMsgs.drain()` is called, but `o.awl` is not reset. This results in a stuck consumer that can't redeliver messages due to `o.checkPending` short-circuiting on `o.awl` being set.
2. If a message is scheduled for redelivery but a race condition is hit where the message has been removed in the meantime. We would not catch this, keep the message around for redelivery, and as a result slowdown a lot. Instead the message should be removed since it can not be delivered anymore.
Resolves https://github.com/nats-io/nats-server/issues/6374
> [FIXED] Consumer stuck/slowdown during leader changes or redeliveries

- .travis.yml
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/ipqueue.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_consumer_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/raft.go
- server/route.go
- server/store.go
- server/stream.go
- https://github.com/nats-io/nats-server/pull/6373
- https://github.com/nats-io/nats-server/pull/6377
- https://github.com/nats-io/nats-server/pull/6379
- https://github.com/nats-io/nats-server/pull/6390
- https://github.com/nats-io/nats-server/pull/6392
- https://github.com/nats-io/nats-server/pull/6387
- https://github.com/nats-io/nats-server/pull/6292
> Cherry-picks for 2.10.25-RC.3

- .goreleaser.yml
There is no point in building .tar.gz. for windows and .zip for linux. 
When .tar.gz. was added in https://github.com/nats-io/nats-server/pull/1589
goreleaser did not have a feature to override the archive.
Now it does(found it in https://github.com/golangci/golangci-lint/blob/master/.golangci.yml)
```
dist/nats-server-v2.11.0-dev-darwin-amd64.tar.gz
dist/nats-server-v2.11.0-dev-darwin-arm64.tar.gz
dist/nats-server-v2.11.0-dev-freebsd-amd64.tar.gz
dist/nats-server-v2.11.0-dev-linux-386.tar.gz
dist/nats-server-v2.11.0-dev-linux-amd64.tar.gz
dist/nats-server-v2.11.0-dev-linux-arm64.tar.gz
dist/nats-server-v2.11.0-dev-linux-arm6.tar.gz
dist/nats-server-v2.11.0-dev-linux-arm7.tar.gz
dist/nats-server-v2.11.0-dev-linux-mips64le.tar.gz
dist/nats-server-v2.11.0-dev-linux-ppc64le.tar.gz …
```
> [v2.11] Update goreleaser to build .tar.gz for linux, .zip for windows

- server/consumer.go
- server/jetstream_cluster_1_test.go
When using a replicated stream a consumer with a starting sequence could be created on a follower that's ever so slightly behind on applies. If the starting sequence is higher than the stream's last sequence we would clamp it down.
We should not be clamping it down, and must respect what the user/client gave us. That ensures any messages the user/client gets are always `message.seq>=starting_seq` as well.
However, if the consumer is used for mirroring/sourcing then we should still clamp down.
> [FIXED] (2.11) Respect consumer's starting seq, even if in the future

- server/consumer.go
- server/jetstream_consumer_test.go
Follow-up of https://github.com/nats-io/nats-server/pull/6387
Deleting from `o.pending` and `o.rdc` in `o.getNextMsg` was a correctness issue. Due to us calling `go o.processTerm` we could go into `o.getNextMsg` before `o.processTerm` has adjusted the accounting for the message that's deleted. So we must not change `o.pending/o.rdc` ourselves, and we can just skip, waiting for `o.processTerm` to run.
Resolves https://github.com/nats-io/nats-server/issues/6374
> [FIXED] Don't adjust o.pending during redelivery, gets fixed elsewhere

- .github/actions/nightly-release/action.yaml
- .goreleaser.yml
- .travis.yml
Similar to https://github.com/nats-io/nats-server/pull/6299
Make packages set mtime to `commitdate`.
Upgrade goreleaser to the latest 2.6.1, which includes the feature used in this PR: https://github.com/goreleaser/goreleaser/pull/5392
```
go install github.com/goreleaser/goreleaser/v2@v2.6.1
goreleaser release --snapshot --clean -f .goreleaser.yml
mv dist/ ~/tmp/dist_before
goreleaser release --snapshot --clean -f .goreleaser.yml 
vimdiff dist/SHA256SUMS ~/tmp/dist_before/SHA256SUMS
```
> [v2.11] Make RPMs and DEBs reproducible

- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
This adds support for TTLs and subject delete markers into the memory store. Much of this is just replicating and aligning the logic from the filestore. None of the recovery/rebuilding/re-indexing code is needed as the memory store does not recover from disk.
Some of the relevant JetStream unit tests have been updated to test both `MemoryStorage` and `FileStorage`. The relevant filestore tests have also been replicated into the memstore tests. 
> Add support for TTLs and subject delete markers to memory store

- server/consumer.go
- server/jetstream_consumer_test.go
> Cherry-picks for 2.10.25

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
After experimenting with this, it feels strange to have `MaxAge` etc typed as `time.Duration` but then have `SubjectDeleteMarkerTTL` typed as a maybe-string-integer maybe-string-duration. This PR instead standardises on `time.Duration`.
This does not change the behaviour of the `Nats-TTL` header.
> Change `SubjectDeleteMarkerTTL` stream config field to duration

- server/consumer.go
We intended to deprecate this but did not do so in the end and it is critical in current API clients
> Remove the comment that durable_name is deprecated

- server/consumer.go
- server/jetstream_test.go
Before this change, an attempt to change consumer type (by either setting or removing deliver subject), resulted in `max waiting can not be updated` error as `MaxWaiting` has a default value for pull consumers. This ensures that changing consumer type is checked before max waiting to return a more useful error message.
> Improve error message when attempting to change consumer type

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/stream.go
Issue description:
- Publish a message with a `Nats-Msg-Id`.
- Leader election through restarts/networking/etc.
- Due to leader election the proposal queue is drained and the message is not stored/proposed.
- Any retries of the original message will fail until the de-dupe window clears the original message, even though it was not stored in the stream.
This issue is due to staging a zero sequence in the de-dupe map. An easy solution seems to clear all zero sequence entries from the de-dupe map upon stepping down, but that has correctness issues if any of those messages did get proposed.
This PR removes the staging of a zero sequence and ensures all replicas can deterministically do de-duping themselves. And duplicate messages are only blocked at the cluster-level if we know what the …
> [FIXED] Deterministic clustered dedupe

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/monitor.go
This should make the output of `healthz` less opaque when there are stream or consumer healthcheck errors. Also more closely aligns the checks between streams and consumers.
> Descriptive stream & consumer health errors

- server/jetstream_cluster_4_test.go
Previously the test could fail if it so happened that a heartbeat was sent either before or during the `storeToWAL` loop, due to directly interacting with the RAFT code.
To de-flake, instead publish some messages and manually truncate one replica in a way which the RAFT layer can/should always recognize and fix.
> De-flake TestJetStreamClusterPreserveWALDuringCatchupWithMatchingTerm

- server/jetstream.go
Using NATS in our unit tests with the Go data race detector turned on, we [sometimes see failures in `nats-server` like the following](https://github.com/mindersec/minder/actions/runs/13006404998/job/36274161639):
```
Read at 0x00c0004ba0e8 by goroutine 41:
github.com/nats-io/nats-server/v2/server.(*Account).filteredStreams()
/home/runner/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.10.25/server/jetstream.go:1504 +0x3e4
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamNamesRequest()
/home/runner/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.10.25/server/jetstream_api.go:1662 +0x516
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamNamesRequest-fm()
<autogenerated>:1 +0xcb
github.com/nats-io/nats-server/v2/server.(*jetStream).apiDispatch() …
```
> Fix data race on mset.cfg

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/stream.go
This PR adds subject delete markers when doing purge/compact/remove operations for the filestore.
Memstore will be a separate PR but expect it to look a lot like this one.
Remaining questions before I mark for review:
> Subject delete markers on purges and removes for filestore

- server/filestore.go
- server/filestore_test.go
- server/jetstream_test.go
- server/jetstream_versioning.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
Remove the boolean and the default value and preserve only the single TTL configuration option. We also no longer need the pedantic checks anymore either.
> Single configuration option for subject delete markers

- CONTRIBUTING.md
- README.md
- TODO.md
- server/README.md
•	Corrected typos and grammatical errors in documentation.
•	Improved text clarity and accuracy across README, CONTRIBUTING, and other files.
•	Updated wording for better readability and a more professional tone.
> Minor Documentation and Typographical Fixes for NATS Server

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/monitor.go
- server/raft.go
This removes lock contention around JS API requests figuring out if the meta group is leaderless or not by instead tracking that state atomically. 
Also fixes a race condition in inactivity thresholds/consumer pause that this seemed to uncover.
> NRG: Lockless `Leaderless` and `HadPreviousLeader`

- server/events.go
- server/events_test.go
- server/monitor.go
- server/monitor_test.go
This PR adds `$SYS.REQ.SERVER.*.RAFTZ` and `$SYS.REQ.SERVER.*.IPQUEUESZ` so that they can be queried via the system account as well as the monitoring port.
> Expose `raftz` and `ipqueuesz` via system account

- server/stream.go
Message was not returned to the pool if there was an error.
> [FIXED] Return msg to pool if 429 Too Many Requests

- server/jetstream_cluster.go
- server/jetstream_cluster_2_test.go
- server/raft_test.go
- server/stream.go
A replicated stream can compress the data in proposals/catchup if all servers support it. However, if a stream already exists and the servers restart then compression would not be enabled, even though all servers support it.
This was due to the `compressOK` flag only being set upon becoming leader, which meant that if a quorum of servers comes online and the leader is elected before the final server comes online, compression will not be enabled until there is another leader election.
We could re-calculate `compressOK` when a server comes online, but that could be expensive depending on the amount of servers and streams involved. Since compression has been added in v2.9.0 this means that all supported versions already support compression and there's no need to check. (Only 2.8.4 or earlier …
> [FIXED] Allow compress after restart

- server/sublist.go
In the case that `IntersectStree` yields subject literals instead of wildcards, then using `Find` on the stree is much cheaper than using `Match`. This should help codepaths like `NumPendingMulti`. 
> Optimise `IntersectStree` for matching subject literals

- server/jetstream_benchmark_test.go
The relevant code for multi-filtered consumers differs considerably between the two stores, so we need to be watching both.
> Add filestore permutations to `BenchmarkJetStreamConsumeWithFilters`

- server/filestore.go
This PR optimises `LoadNextMsgMulti` by doing two things:
* Avoid large linear scans in `firstMatchingMulti` by using subject tree intersection when it looks like the FSS size is smaller than the scan range, this should be less expensive (although the threshold for choosing strategy may need further attention);
* Check the `dmap` before calling `mb.cacheLookup()` in either the FSS search or the linear scan, such that we can avoid calling `time.Now()` a lot when we are tight-looped scanning over a large number of interior deletes.
This PR provides a 2x improvement on the 1000-filter `LoadNextMsgMulti` unit test and provides a 10x improvement when tested against a store that has extremely sparse messages and 8 consumer filters.
> Optimisations for `LoadNextMsgMulti`

- .travis.yml
> Update to Go 1.23.6/1.22.12

- server/client.go
- server/client_test.go
- server/jetstream_api.go
In the various places that we are handling client info from headers, like when queuing and pulling from the JS API queue or due to the service export, we could safely refer to the underlying header slice, instead of making a copy as `getHeader()` does today.
This PR adds a new `sliceHeader()` that merely slices the input header instead, reducing copies considerably in any system where there is heavy usage of JS API requests.
> Add `sliceHeader` for zero-copy parsing of message headers, use for client info

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
If a peer remove entry would be included with other entries in the same append entry. Any entry after the peer remove would be skipped. If there was a stream message after the peer remove, that meant the next stream message would result in a 'last seq mismatch', resetting the clustered state which could lead into stream desync.
The same issue also existed for consumer entries after a peer remove within the same append entry.
> [FIXED] Desync after stream/consumer peer remove

- server/filestore.go
- server/memstore.go
- server/stree/stree.go
- server/stree/stree_test.go
- server/stree/util.go
Not all of the `Iter()` call-sites required ordering, and ordering would slow down the process quite a bit, so replace with two new `IterFast()` and `IterOrdered()` functions instead.
This should speed up populating the per-subject infos, multi-filter num pending and enforcing the per-subject limits.
> stree: Split `Iter` into `IterFast` and `IterOrdered`

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/stream.go
Reserved resources for a stream with `MaxBytes` set would be double-accounted after a `mset.resetClusteredState`.
Resolves https://github.com/nats-io/nats-server/issues/6455
> [FIXED] Reserved resources accounting after cluster reset

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
If a replica was catching up based on a stream snapshot and it would be incomplete due to the RAFT node/server quitting then there could be desync if there was at least one entry after it that got `n.Applied` and stored in a snapshot upon shutdown.
> [FIXED] Desync after quit during catchup

- server/consumer.go
Lock ordering was violated resulting in a deadlock. Must not hold consumer lock while trying to grab JS lock.
> [FIXED] Consumer/JS deadlock

- server/filestore.go
- server/memstore.go
- server/norace_test.go
- server/store.go
- server/stream.go
Added LoadPrevMsg to optimize when we walk backwards looking for source sequences and we have lots of interior deletes.
> [IMPROVED] Optimized calculating source sequences for sourced stream with lots of deletes.

- .github/actions/nightly-release/action.yaml
- .github/workflows/nightly.yaml
- .goreleaser-nightly.yml
- .travis.yml
- docker/Dockerfile.nightly
- server/client.go
- server/client_test.go
- server/consumer.go
- server/events.go
- server/events_test.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_benchmark_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
- server/memstore.go
- server/monitor.go
- server/monitor_test.go
- server/norace_test.go
- server/raft.go
- server/store.go
- server/stream.go
- server/stree/stree.go
- server/stree/stree_test.go
- server/stree/util.go
- server/sublist.go
- server/websocket.go
- #6406
- #6412
- #6408
- #6416
- #6425
- #6424
- #6438
- #6439
- #6446
- #6447
- #6448
- #6449
- #6450
- #6451
- #6452
- #6453
- #6456
- #6458
- #6457
- #6459
- #6460
- #6461
> Cherry-picks for 2.10.26-RC.1

- go.mod
- go.sum
- server/client_test.go
- server/jetstream_test.go
- server/jwt_test.go
- server/monitor_test.go
- test/client_cluster_test.go
- test/fanout_test.go
- test/tls_test.go
Updated nats.go to v1.39.0.
- https://github.com/nats-io/nats.go/pull/1674
- https://github.com/nats-io/nats.go/pull/1709
Fixed the connection not being closed on exceeding subs, so using `nats.ErrorHandler` instead of `nats.DisconnectErrHandler`.
- https://github.com/nats-io/nats.go/pull/1728
Changed `nats: Permissions Violation for ...` to `nats: permissions violation: Permissions Violation for ...`, so `strings.HasPrefix` checks (and others) have been updated.
> [IMPROVED] Update nats.go dependency

- server/consumer.go
- server/jetstream_cluster_1_test.go
When a client requests for messages, in `o.deliverMsg` the following is done:
```go
// Update delivered first.
o.updateDelivered(dseq, seq, dc, ts)
// Send message.
o.outq.send(pmsg)
```
For `o.updateDelivered` we need to establish quorum to have all servers know the message was delivered, and this can fail. So we would have sent the client messages that a new leader will not know have ever been delivered.
Once a new leader gets elected and receives an ACK for a message it doesn't know was delivered it would move `o.sseq` ahead. This is incorrect, since the message is not in `o.pending` it results in ack floors not being updated. And if any messages before the one that was acked were not acknowledged/NAK-ed, that would mean these messages would never be redelivered resulting in the stuck …
> [FIXED] Stuck consumer after leader change

- server/client.go
By calculating the write deadline at the beginning of the flush operation, we could be hitting it early if there is a lot of data queued up. Instead this PR applies it to each `writev` batch of at most 1024 vectors, which means that the deadline applies to no more than 64MB in one go.
This makes it simpler to tune the write deadline as it can be thought of as "the maximum time taken to allow writing at most 64MB" instead.
> Apply client write deadline to batches rather than total flushes

- server/jetstream_cluster_4_test.go
This should hopefully de-flake this test by ensuring we send enough requests that we can't possibly interleave with a listening worker.
> De-flake `TestJetStreamClusterAPILimitAdvisory`

- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/norace_test.go
- server/raft.go
- server/store.go
- server/stream.go
As per [the ADR](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-43.md#purge-api-call-marker), this adds the `no_markers` flag to the JS API stream purge request, such that a stream can be purged without leaving behind any subject delete markers, if they are enabled.
This helps to avoid the "poison pill" problem if there are subjects for example that are causing problems with a consuming application.
Individual message deletes are less of a concern here because a single message delete will leave behind at most one marker, which can be deleted too (and would not be replaced in that case), but a purge can potentially leave behind lots of markers for lots of subjects, which could be difficult to sort through by hand otherwise.
Signed-off-by: Neil Twigg …
> Purge requests with no subject delete markers

- server/client.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/monitor.go
- server/raft.go
When replicating messages over NRGs that still use the system account, make sure to add in to account stats the sent msgs and bytes to replicate.
> Account for replicated msgs in user account.

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_test.go
Using `MaxStreams` and `MaxConsumers` you can limit the amount of streams, and the amount of consumers on a specific stream.
There were some edge conditions where stream/consumer creates would fail with a "limit reached" error which have been fixed in this PR:
- non-clustered create of a stream that already exists when at limit
- clustered create of a stream that already exists when at limit
- clustered create of a consumer that already exists when at limit
In above cases the accounting would think an additional stream/consumer would be added which would exceed the limit, even though this was not the case and the request should have been successful.
> [FIXED] Stream/consumer limit reached edge conditions

- server/jetstream_api.go
- server/jetstream_cluster_3_test.go
Stream info would bail and timeout even if `rg.Preferred` would equal the current server, but if `rg.node` would still be `nil`.
Resolves https://github.com/nats-io/nats-server/issues/6421
> [FIXED] Preferred stream leader responds without initialized RAFT node

- server/jetstream_cluster_1_test.go
> [ci skip] Fix for typo

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/raft.go
- server/stream.go
Previously https://github.com/nats-io/nats-server/pull/6194 implemented a way to wait for entries that are stored in the new leader's log but not yet applied, before allowing 'expected per subject' operations to go through. This protected against KV/stream desync.
That protection is now extended to the whole of (clustered) JetStream, and not specific to this one operation anymore. Meaning that if the new leader recognizes it has entries in its log that have not yet been applied, it waits for those to be applied before responding to any read/write operations. In essence it's the 'Leader Completeness Property' as described by the Raft paper. This also brings us closer to 'read-your-writes' when only requesting reads from the leader. …
> NRG (2.11): Completeness/consistency after leader changes

- server/events.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/route.go
- server/server.go
- server/stream.go
Reverts https://github.com/nats-io/nats-server/pull/6415 and https://github.com/nats-io/nats-server/pull/6426. If duplication would be deferred to be done by a replica, and that replica was down for at least 'dupe window+5s', and it would clean up the dedupe map. A message that was meant to be duplicate could be passed as a genuine message, resulting in stream desync.
Instead, the dedupe map should be cleared of any staged zero-sequences. However, that was not possible before as a new leader would not always be fully up-to-date when it starts responding to new write requests, which could result in duplicate messages as well.
However, relying on the 'Leader Completeness Property' implemented here: https://github.com/nats-io/nats-server/pull/6485, we can confidently clear the dedupe map now …
> [FIXED] (2.11) Clear inflight dedupe IDs on leader change

- server/auth.go
- server/auth_callout_test.go
- server/leafnode.go
If a username and password is provided in a leaf remote URL, as such:
```
leafnodes {
remotes [
{url: "nats://leaf:pwd@hub_host:7422"
]
```
or a authorization token, as such:
```
leafnodes {
remotes [
{url: "nats://myToken@hub_host:7422"
]
```
and if the server uses authorization callout, it will be possible to authenticate such leafnode, in either server configuration or operator mode.
Resolves #6481
> [FIXED] Auth-Callout: Allow username-password/token in Leaf remote URL.

- server/accounts.go
- server/jetstream_jwt_test.go
Messages that are exported/imported can be published on an account that has an export, and ingested into a stream in an account that imports it.
This would not work as expected if the stream existed prior to a server restart, and exports/imports would be updated after.
- If exports/imports are added which should allow the stream to ingest, these messages would not be received by the stream.
- If exports/imports are removed which should stop message flow to the stream, the stream would keep receiving messages.
Once the server was restarted again, the exports/imports would be respected.
The issue was that the internal JetStream client that's used for the stream was added to the account before its `a.clients` map was initialized. So once the exports/imports were updated, these clients/subs …
> [FIXED] Stream ingest after JWT exports/imports update

- server/client.go
- server/msgtrace.go
- server/norace_test.go
- server/opts.go
- server/reload.go
Normally, when a producer detects that one of the consumer of a message is falling behind, it will stall. Which means that if a message has 2 consumers and the first is "slow", then it will affect the timely delivery to the second consumer.
With the new option `no_fast_producer_stall=true`, the server will simply drop a message destined to a consumer that would have caused the producer to stall. The message is still delivered to consumers that are not falling behind.
The option can be config-reload'ed and if a message is dropped due to fast-producer/slow-consumer, and the message was traced (with deliver option), then the message trace egress event will have an error indicating the reason why the message was not delivered.
Resolves #6413
> [ADDED] Option that disables fast producer stalling (drops msg instead)

- server/consumer.go
- server/gsl/gsl.go
- server/gsl/gsl_test.go
- server/stream.go
This PR adds a new `GenericSublist`, which is based on the existing sublist, but with the following changes:
- No queue semantics — they are not necessary for straight-forward matching of generic objects;
- No cache — at the scale at which this produces a difference, none of the cache entries survive long enough, resulting in endless churn;
- No `SublistResult` allocations — the match function instead takes a callback, like `SubjectTree` does, making it effectively zero-allocation to use.
It also moves the stream `mset.csl` for filtered consumers over to the new generic sublist, such that consumer signalling for new messages and/or storage updates only touches interested consumers rather than all of them. This reduces CPU dramatically when there are a very large number of consumers on a …
> Consumer signalling using generic sublist

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
There was a race condition (reproduced by Antithesis) where a server restarts and needs to catchup with a stream leader, but no stream leader could be elected for that stream temporarily. The RAFT node would then be stopped and restarted after some time, allowing for a stream leader to be elected, after which we can request catchup again.
However, since `resetClusteredState` is called, which resets `sa.Group.node = nil` and recreates it after. `checkForNRGOrphans` does not track the stream assignment while collecting RAFT nodes, and then sees the RAFT node is still registered on the server (because `n.Stop()` runs in parallel and didn't get to cleaning this up yet), and then deletes the RAFT node.
If the intend was to restart the RAFT node and all RAFT state is nuked due to this check …
> [FIXED] (2.11) Race when checking for orphaned NRG

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
Maximum streams reached errors would be returned when creating (the same) streams in parallel:
- if max streams = 1, the second create request would fail as the previous create request being inflight made it exceed the limit, even if it was about the same stream
- if max streams > 1, if the streams already existed would count the streams twice, once for the streams existing already, and another time due to being inflight
> [FIXED] Max streams reached with parallel stream creation

- .travis.yml
- go.mod
- scripts/runTestsOnTravis.sh
- server/filestore.go
Updates `go.mod` to require Go 1.23, update Travis CI to use Go 1.24.
Also update golangci-lint and fix a couple new things that it highlighted.
> Update to Go 1.24.0/1.23.6

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
If a server would be down during the recreation of a consumer, and the remaining servers performed a meta snapshot, if the server came back online it would not recreate the consumer based on the snapshot and leave it stranded with an old RAFT group.
> [FIXED] Recreate consumer on meta snapshot

- server/opts.go
- server/opts_test.go
Fixes: https://github.com/nats-io/nats-server/issues/6496
Signed-off-by: Yevhen Surovskyi <surovskyi.y@ajax.systems>
> Handle max_closed_clients property

- server/raft.go
- server/raft_test.go
If an outdated server wants to become leader, other servers can recognize they have a more up-to-date and start campaigning early to speed up the leader election process.
However, if two servers would both become candidate at the same time due to this, and one of the candidate's log is slightly more ahead it would again start campaigning early. This can essentially short-circuit the voting process, starting a new leader election/term while that wouldn't be necessary to do. That ahead candidate could just reject the vote for the other candidate, and wait for successful votes for itself to come in.
> NRG: Campaign early unless already candidate

- server/raft.go
- server/raft_test.go
If the leader changed, a heartbeat would not be able to signal there's quorum on messages. This is because the leader only tracked quorum for entries it sent out itself AND were stored in its own log. Heartbeats are sent by the leader but are not stored in its log, which means they can't be used to track quorum.
To solve this we don't need to track the leader in `n.acks`, which would not get populated after a leader change. Instead we only track the replicas that signal success and we always count ourselves anyway. This ensures that heartbeats, although not stored, can still signal quorum properly.
Also, acks from previous terms would not be reset during stepdown. Which meant that successful acks from previous terms could be combined with acks from newer terms, making the leader believe …
> NRG (2.11): Heartbeat can establish quorum & reset acks during stepdown

- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
The `n.pae` is an in-memory cache of pending but not yet applied entries. When applying commits we can pull from this cache so we don't need to pull them from disk for example. However, the cache has a bounded size. So if the cache would be fully filled and we'd store a different entry at an index that was cached, we'd apply the wrong (cached) entry.
If we get an entry that we can't cache because it's full, we can simply drop the entry from the cache if it exists. If an entry at this index doesn't exist it's a noop, but if it did exist then it clears up room in the cache for the next entries to be stored.
> NRG: Invalidate pending append entries cache

- server/filestore.go
- server/memstore.go
- server/store_test.go
In `Compact` and `Truncate` the interior delete map would not always be cleaned up properly. This could result in memory leaks. Also, if the filestore would restore based on `index.db` it would invalidate it due to having too many deletes and not being able to reconstruct the state.
> [FIXED] Cleanup dmap on Compact/Truncate

- server/consumer.go
- server/jetstream_cluster_4_test.go
- server/norace_test.go
- server/stream.go
Partial backport of #6140 for v2.10.26+
`mset.ackMsg` could fail if the clustered stream is behind on applies on this server, but the consumer's ack floor is ahead. In this case `checkStateForInterestStream` would skip its check floor ahead, never retrying to ack/remove this message again. Which would leave messages around, not being removed even though they could be.
This PR is a partial backport, still doing `mset.ackMsg` for each individual server instead of via message delete proposals for clustered streams, but allowing to retry if a removal should be done.
> [FIXED] Backport retry mset.ackMsg if removal fails

- server/filestore.go
- server/filestore_test.go
If the filestore recovers based on just the `.blk` files and not based on `index.db`, and it would start with an erased message it would be left in the `mb.dmap` even though it would be below the `mb.first.seq`.
> [FIXED] SkipMsg left in mb.dmap after recovery

- server/client.go
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/gateway.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_4_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/memstore.go
- server/monitor.go
- server/norace_test.go
- server/opts.go
- server/opts_test.go
- server/raft.go
- server/raft_helpers_test.go
- server/raft_test.go
- server/store_test.go
- server/stream.go
- https://github.com/nats-io/nats-server/pull/6507
- https://github.com/nats-io/nats-server/pull/6497
- https://github.com/nats-io/nats-server/pull/6476
- https://github.com/nats-io/nats-server/pull/6511
- https://github.com/nats-io/nats-server/pull/6513
- https://github.com/nats-io/nats-server/pull/6517
- https://github.com/nats-io/nats-server/pull/6515
- https://github.com/nats-io/nats-server/pull/6519
- https://github.com/nats-io/nats-server/pull/6521
> Cherry-picks for 2.10.26-RC.4

- server/jetstream_cluster_1_test.go
Fixes the following test panic:
```
=== FAIL: server TestJetStreamClusterRecreateConsumerFromMetaSnapshot (4.18s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xc4a8b3]
goroutine 68737 [running]:
testing.tRunner.func1.2({0x134cb80, 0x20093e0})
/usr/local/go/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1737 +0x35e
panic({0x134cb80?, 0x20093e0?})
/usr/local/go/src/runtime/panic.go:787 +0x132
github.com/nats-io/nats-server/v2/server.TestJetStreamClusterRecreateConsumerFromMetaSnapshot.func3()
/workspace/build/buildkite/synadia/nats-server-dev/server/jetstream_cluster_1_tes …
```
> Test: fix panic for non-existent RAFT node/group

- server/monitor.go
- server/monitor_test.go
- test/ocsp_peer_test.go
When checking the `gatewayz` monitoring endpoint, if the user requests accounts `?accs=1` or a specific account `?acc_name=B` then we can now include the subscription list for each account with `&subs=1` or the subscription details list with `&subs=detail`.
The subscription information will be contained in each account in the `accounts` list of the `outbound_gateways` block.
Resolves #6473
> (2.11) [ADDED] Monitoring: Include subscriptions in `Gatewayz`

- server/filestore.go
- server/memstore.go
- server/store_test.go
Consumers could occasionally skip messages given specific message removal patterns. This was most prevalent for WorkQueue and Interest-based streams.
The issue lies in both `ss.First` and `ss.Last` being lazy and needing to be recalculated once they are needed. `ss.Last` was not recalculated before, but it is since https://github.com/nats-io/nats-server/pull/6235 ensuring the subject state remains correct.
However, if `ss.Last` was overwritten after a new message was ingested into the stream, the `ss.lastNeedsUpdate` flag was not updated. Which resulted in `ss.Last` being recalculated to a lower value, skipping over the message with the sequence that was previously `ss.Last`.
> [FIXED] Consumer skips some messages

- server/accounts.go
- server/events.go
- server/monitor.go
There was a deadlock introduced in https://github.com/nats-io/nats-server/pull/6310. In `s.accountInfo(accName)` we get the read lock on the account, but when going into `a.getNameTag()` we get the read lock again. If at any point the write lock would be taken from somewhere else, we'd be deadlocked. Since we're already holding the lock we don't need to get it again.
> [FIXED] Deadlock on getting account name tag

- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/leafnode.go
- server/raft.go
- server/stream.go
Follow-up of https://github.com/nats-io/nats-server/pull/6485
After above PR the RAFT state would become `Leader` as normal, but a call to `updateLeadChange` would be delayed until the server is up-to-date with all stored but unapplied entries from its log. The intention of this is to not respond to read/write requests for meta/stream/consumer until the leader is in a complete state, which ensures consistent handling of requests after leader changes.
However, calls like `isLeader`, `isStreamLeader`, and `isConsumerLeader` would request `n.Leader()` which returns whether the RAFT node is leader. And it would not use the signal sent to `updateLeadChange`.
To achieve this level of consistency with minimal code changes:
- `n.Leader()` only returns true once the RAFT node is both a leader, and …
> NRG (2.11): Mark n.Leader() when complete with applied floor

- server/jetstream_cluster_long_test.go
> Add `TestLongClusterWorkQueueMessagesNotSkipped` to long-running tests

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
- .github/workflows/long-tests.yaml
- .github/workflows/mqtt-test.yaml
Setup-go has some non-straitforward tricks:
https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
> The go directive in go.mod can specify a patch version or omit it altogether (e.g., go 1.22.0 or go 1.22).
If a patch version is specified, that specific patch version will be used.
If no patch version is specified, it will search for the latest available patch version in the cache, [versions-manifest.json](https://github.com/actions/go-versions/blob/main/versions-manifest.json), and the [official Go language website](https://golang.org/dl/?mode=json&include=all), in that order.
This is an invention of setup-go action authors. Go team [says](https://github.com/golang/go/issues/68971#issuecomment-2300236006) that release version (e.g. 1.22.0) should be …
> Use stable go version in gh actions

- .goreleaser.yml
- .travis.yml
We have reproducible binaries, [rpms/debs](https://github.com/nats-io/nats-server/pull/6359) and [archives](https://github.com/nats-io/nats-server/pull/6299).
And `goreleaser.yml` holds [all the knobs](https://goreleaser.com/customization/builds/go/) that can be tuned to build the binary. 
The only thing that affects the build and is not defined in the goreleaser config is the go toolchain version. 
Currently, we set the version of the go toolchain that is used for releases in Travis:
<https://github.com/nats-io/nats-server/blob/5e6017135b4b1d333b435ff55b720275a39bb7af/.travis.yml#L11-L12>
<https://github.com/nats-io/nats-server/blob/5e6017135b4b1d333b435ff55b720275a39bb7af/.travis.yml#L67>
I spent some time [trying to understand the behavior of go and toolchain …
> Explicitly set go toolchain in goreleaser config

- server/jetstream_cluster_long_test.go
We need to check for `ErrSubscriptionClosed` as the defer to close the client and shutdown the server will happen while the consumer goroutines are still running, so we need to detect that gracefully rather than accidentally failing the test.
[ci skip] as this test isn't run under Travis.
> Fix `TestLongClusterWorkQueueMessagesNotSkipped`

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
If a stream or consumer was created prior to 2.11 there would be no versioning metadata. After the server upgrade sending an identical create request would fail with `stream already exists`. If a stream or consumer already exists without metadata, creates are now idempotent. Which also means that the new versioning metadata will only be set if creating a new stream/consumer, or when updating it.
Also, the signatures of `setStaticStreamMetadata` and `setStaticConsumerMetadata` were updated, since the second parameter is unused. Cleaned that up, along with duplicate test cases in `jetstream_versioning_test.go`.
> [FIXED] (2.11) Idempotent stream/consumer create after server upgrade

- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/jetstream_cluster_2_test.go
- server/jwt_test.go
- server/msgtrace_test.go
- server/parser.go
Since service imports are internal callbacks with no signaling for delivered status, when sending through a service import with no interest in the exporting account, the requestor would simply timeout. 
> [FIXED] A request through a service import with no interest should return no reponders.

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
Replicated consumers could skip redeliveries of non-acked messages when:
- A message was delivered to the client, but there was no quorum on updating delivered state across replicas. Then a replicated ack came in, which would up the starting sequence, skipping redelivery of messages below. The following code caused that issue:
```go
// Match leader logic on checking if ack is ahead of delivered.
// This could happen on a cooperative takeover with high speed deliveries.
if sseq > o.state.Delivered.Stream {
o.state.Delivered.Stream = sseq + 1
}
```
- A message was delivered to the client, but there was no quorum on updating delivered state across replicas. Then the consumer leader steps down, and becomes leader again. It would not  reset `o.sseq` back down to agreed state, skipping …
> [FIXED] (2.11) Replicated consumer skipped redeliveries

- .github/workflows/cov.yaml
- go.mod
- go.sum
- server/accounts.go
- server/accounts_test.go
- server/client.go
- server/config_check_test.go
- server/filestore.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/jwt_test.go
- server/leafnode.go
- server/leafnode_test.go
- server/memstore.go
- server/monitor.go
- server/monitor_test.go
- server/opts.go
- server/parser.go
- server/store_test.go
- test/ocsp_peer_test.go
- https://github.com/nats-io/nats-server/pull/6524
- https://github.com/nats-io/nats-server/pull/6525
- https://github.com/nats-io/nats-server/pull/6526
- https://github.com/nats-io/nats-server/pull/5424
- https://github.com/nats-io/nats-server/pull/6565
- https://github.com/nats-io/nats-server/pull/6532
> Cherry-picks for 2.10.26-RC.5

- server/client.go
- server/client_test.go
- server/msgtrace_test.go
- server/norace_test.go
> [IMPROVED] Adjusted stalled producers to not be as penalizing.

- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
Resolves https://github.com/nats-io/nats-server/issues/6538
If a consumer reached max deliveries for a message, it should preserve the redelivered state and allow inspecting its content. However, if a new consumer would be created and consume this message as well, it would still be removed under Interest retention.
This PR fixes that by using the redelivered state to keep marking there's interest.
Only downside is that the redelivered state gets cleaned up after a restart (this PR does not change/fix that). So if the consumer that had a max delivery message keeps acknowledging messages and its acknowledgement floor moves up, it would clean up the redelivered state below this ack floor.
Honestly I feel like keeping messages around if max delivery is reached makes the code very complex. It …
> [FIXED] Preserve max delivered messages with Interest retention

- server/filestore.go
The following changes are all to reduce GC pressure:
- The `hdr` array looked like it should be stack-allocated but was actually always escaping to the heap because of the highwayhash writer, so instead of allocating a ton of those, just preallocate space on the underlying cache buffer instead (since that has already escaped to the heap);
- Reuse the memory of the last checksum instead of allocating unnecessarily there too, and use `stringToBytes` for the subject, avoiding a further copy.
> [IMPROVED] Reduce allocations in `writeMsgRecord`

- server/client.go
> [FIXED] Fix for data race for c.out under stalledWait

- server/jetstream_test.go
This would show the error on tests that used to fail like this:
```
=== RUN   TestJetStreamConsumerMaxDeliveryAndServerRestart
jetstream_test.go:3750: No response for "order-3", possible timeout?
--- FAIL: TestJetStreamConsumerMaxDeliveryAndServerRestart (0.86s)
```
> test: Show error in sendStreamMsg test helper

- server/raft_chain_of_blocks_helpers_test.go
```
FAIL: TestLongNRGChainOfBlocks (400.71s)
panic: failed to snapshot: raft: snapshot can not be installed while catchups running [recovered]
panic: failed to snapshot: raft: snapshot can not be installed while catchups running
```
Installing snapshots can fail, for example if catchups are running. Don't need to panic if it fails.
> Don't panic if install snapshot failed in TestNRGChainOfBlocks

- server/norace_test.go
The test could fail with the following error messages:
```
norace_test.go:5181: Not hit limit yet
norace_test.go:5163: Got a Fetch error: nats: Server Shutdown
norace_test.go:5163: Got a Fetch error: nats: Server Shutdown
norace_test.go:5163: Got a Fetch error: nats: Server Shutdown
norace_test.go:5163: Got a Fetch error: nats: Server Shutdown
```
This was triggered by:
```go
if si.State.Msgs < limit {
return fmt.Errorf("Not hit limit yet")
}
```
If we'd wait for 1 millisecond too often, you'd get this error.
> De-flake TestNoRaceJetStreamClusterInterestPullConsumerStreamLimitBug

- server/jetstream_test.go
The test could fail with the following error:
```
jetstream_test.go:3749: No response for "order-3" (error: nats: timeout)
```
This was due to the server restarting, but the connection not yet recognizing the server was stopped when `sendStreamMsg(t, nc, mname, "order-3")` is called resulting in a timeout. Instead we can just force reconnect since we know we need to reconnect, and this test is about the MaxDelivery setting after restarts.
> De-flake TestJetStreamConsumerMaxDeliveryAndServerRestart

- .github/workflows/release.yaml
- .goreleaser.yml
- .travis.yml
- server/norace_test.go
This switches the release process to use GitHub Actions instead of Travis CI.
Tested on a forked repository:
- Successful run: https://github.com/neilalexander/nats-server/actions/runs/13546082159/job/37857914525
- Created release: https://github.com/neilalexander/nats-server/releases/tag/v2.11.0-RC.4
> Use GitHub Actions for releases

- server/norace_test.go
The test can fail for any consumer info call that takes longer than 5ms. On CI, and for replicated streams/consumers this seems to be too short. Failing with for example:
```
norace_test.go:6441: ConsumerInfo took too long: 6.324631ms
norace_test.go:6457: ConsumerInfo took too long: 10.305282ms
```
Changed to 50ms to be aligned with other performance related tests like `TestJetStreamClusterConsumerDeleteInterestPolicyPerf`.
> De-flake TestNoRaceJetStreamClusterConsumerInfoSpeed

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
Using a consumer with `AckAll` on an Interest-based stream would not properly remove messages below the sequence as part of the `AckAll`.
It would not work on the leader because in `processReplicatedAck` the skipped ahead `o.asflr` (`=sseq`) is used, so the `sagap = sseq - o.asflr` would actually be `sagap == 0`. But using `state.AckFloor.Stream` also doesn't work and results in `sagap == 0`, because `o.store.UpdateAcks(dseq, sseq)` is called first.
Should use the state prior to updating for both cases.
> [FIXED] AckAll on replicated Interest stream

- server/jetstream_test.go
The wrong connection object was used, resulting in occasional no responder errors. Also ensuring the correct subject is used.
> De-flake TestJetStreamSnapshotsAPI

- server/jetstream_test.go
Test would flake with timeouts on getting advisories when not using `nc.Flush()`, as the subscription might still be inflight when the stream is created.
> De-flake TestJetStreamAccountImportJSAdvisoriesAsStream

- server/raft_chain_of_blocks_helpers_test.go
- server/raft_helpers_test.go
- server/raft_test.go
Various Raft tests could potentially deadlock if they'd make a call to `rg.lockAll()` which locks all Raft nodes while another part is also holding the state machine's lock and requires a Raft lock.
`TestNRGTermDoesntRollBackToPtermOnCatchup` could fail with the following error message due to interest propagation not being immediate.
```
raft_test.go:882: require read from channel within 5s but didn't get anything
```
> De-flake TestNRGTermDoesntRollBackToPtermOnCatchup

- server/jetstream_cluster.go
- server/jetstream_helpers_test.go
- server/norace_test.go
The test could flake if the stream leader makes a snapshot which requires the shutdown follower to catchup based on that snapshot. The follower would then get these errors during startup:
```
[WRN] Catchup for stream '$JS > TEST' errored, account resources exceeded: insufficient resources (10023)
[WRN] Error applying entries to '$JS > TEST': insufficient resources (10023)
```
This was because tier-based limits would be checked during catchup, but we should not do so. The same reasoning mentioned in `processJetStreamMsg` applies here as well:
```go
// If clustered this was already checked and we do not want to check here and possibly introduce skew.
if !isClustered {
if exceeded, err := jsa.wouldExceedLimits(stype, tierName, mset.cfg.Replicas, subject, hdr, msg); exceeded {
``` …
> De-flake TestNoRaceJetStreamAccountLimitsAndRestart

- server/gateway.go
- server/leafnode_test.go
If a server has a connection from a route or a leaf and the remote has more than one member of the same queue group, when the connection is recreated (due to network issue or server restart), then count coming from the connection would be greater than 1 but the server would store the interest count for outbound gateways as 1.
When one of the remote queue subscriber unsubscribes, the count would go down to 0 and the server would incorrectly send a protocol to the gateway indicating that there is no longer interest for this queue group, which would stop the flow.
A new queue subscriber on that group would resume the flow.
> [FIXED] Gateway: Possible loss of queue sub interest on restart

- server/subject_transform.go
- server/subject_transform_test.go
It is likely that this is to do with a faulty service import, and we'll almost certainly be able to do better validation there too, but in the meantime we can and should avoid a panic with more rigorous bounds checking.
> Fix panic when subject transform has missing tokens

- server/jetstream_helpers_test.go
Tests like `TestJetStreamSuperClusterMetaStepDown` could fail if the meta leader was not yet available. It would panic on the `.getJetStream()` call. Wait for a leader and ensure the test doesn't panic/indicates no meta leader being available.
> Test panic with nil super cluster meta leader

- server/server.go
`s.sys = nil` is called in `shutdownEventing()` while holding the lock. But `configureAccounts` reads after unlocking.
```
=== RUN   TestConfigReloadNoPanicOnShutdown
Write at 0x00c0000ca330 by goroutine 132061:
github.com/nats-io/nats-server/v2/server.(*Server).shutdownEventing()
/home/travis/build/nats-io/nats-server/server/events.go:1831 +0x1f0
Previous read at 0x00c0000ca330 by goroutine 131431:
github.com/nats-io/nats-server/v2/server.(*Server).configureAccounts()
/home/travis/build/nats-io/nats-server/server/server.go:1387 +0x1245
```
> Data race in configureAccounts

- server/jetstream_test.go
Same de-flake as in https://github.com/nats-io/nats-server/pull/6592, but for this test.
> De-flake TestJetStreamAccountImportJSAdvisoriesAsService

- server/norace_test.go
Allow for some more time for a stalled request to return, and make error message more informative.
> De-flake TestNoRaceProducerStallLimits

- server/reload.go
- server/signal_test.go
Enabling this would require taking the digest of TLS certs among other extra state at the moment.  We could potentially re-enable in the future so that authorization with no changes is skipped since that would be safe to do.
> v2.11: Disable skipping reload on no config changes

- server/jetstream_cluster_1_test.go
Test would fail with:
```
jetstream_cluster_1_test.go:1203: Consumer info did not match: &{Stream:foo ... Delivered:{Consumer:10 Stream:10 Last:<nil>} ...} vs &{Stream:foo ... Delivered:{Consumer:11 Stream:11 Last:<nil>} ...}
```
Delivered state is proposed asynchronously compared with a call to `sub.NextMsg`, so it can't be guaranteed to be up-to-date immediately after receiving a message. Need to wait for the state to be what we expect.
> De-flake TestJetStreamClusterStreamPublishWithActiveConsumers

- server/jetstream_cluster_1_test.go
Test could fail with:
```
jetstream_cluster_1_test.go:6169: require int equal, but got: 9 != 10
```
If the stream leader and consumer leader are not on the same server.
> De-flake TestJetStreamClusterConsumerAckSyncReporting

- server/jetstream_super_cluster_test.go
Follow-up of several tests failing with `jetstream_super_cluster_test.go:4365: require no error, but got: nats: JetStream not enabled for account`
> De-flake TestJetStreamSuperClusterMixedModeSwitchToInterestOnlyOperatorConfig

- server/events_test.go
- server/jetstream_cluster_3_test.go
- server/monitor.go
- server/norace_test.go
This option checks the healthz state similar to js-server-only used to do on v2.10.X.
> Add js-meta-only healthz option

- server/jetstream_cluster_1_test.go
Interest propagation is not immediate, allow some time for the subscription to be known by all servers.
> De-flake TestJetStreamClusterPeerExclusionTag

- server/jetstream_cluster_1_test.go
Stream is replicated, so `js.PurgeStream` could be performed too late on a follower where the consumer is created on, resulting in:
```
jetstream_cluster_1_test.go:7627: require uint64 equal, but got: 4 != 9
```
Since the purge hasn't happened yet on that follower, so the first seq isn't ahead yet.
> De-flake TestJetStreamClusterRespectConsumerStartSeq

- server/leafnode_test.go
It's expected some messages can be lost still even if `sub.Drain()` is used. It's better than not draining, but still doesn't guarantee the level of consistency this test checks for.
Alternatively, clients could be made smarter to not only check client-known pending messages once, like in https://github.com/nats-io/nats.go/pull/1817. But even then it would not be guaranteed 100%, only up to the arbitrary additional time.
> De-flake TestLeafNodeWithWeightedDQRequestsToSuperClusterWithStreamImportAccounts

- server/mqtt.go
- server/mqtt_test.go
Tests would race if the published message didn't make it in the stream yet.
> De-flake TestMQTTSubRetainedRace

- .goreleaser.yml
Follow up to https://github.com/nats-io/nats-server/pull/6299
The modification time of LICENSE and README.md in the archive is the one when the job https://github.com/nats-io/nats-server/actions/runs/13816873025/job/38652255585 checked out the code:
```
wget https://github.com/nats-io/nats-server/releases/download/v2.11.0-RC.3/nats-server-v2.11.0-RC.3-linux-amd64.tar.gz
tar -xvf nats-server-v2.11.0-RC.3-linux-amd64.tar.gz
ll nats-server-v2.11.0-RC.3-linux-amd64
total 16080
drwxr-xr-x  2 alex alex      100 Mar 12 12:58 .
drwxrwxrwt 48 root root     1280 Mar 12 12:57 ..
-rw-r--r--  1 alex alex    11357 Mar 12 09:54 LICENSE
-rwxr-xr-x  1 alex alex 16442017 Mar 12 09:43 nats-server
-rw-r--r--  1 alex alex     4404 Mar 12 09:54 README.md
```
And that works as designed: …
> Set CommitDate in goreleaser archives

- server/jetstream_test.go
Would race due to cleaning up streams/account directories in a goroutine.
```
=== RUN   TestJetStreamAutoTuneFSConfig
jetstream_test.go:347: Unexpected error adding stream: could not create storage directory - mkdir /tmp/TestJetStreamAutoTuneFSConfig1851261231/002/jetstream/$G/streams/foo_bar_baz: no such file or directory (10077)
--- FAIL: TestJetStreamAutoTuneFSConfig (0.01s)
```
> De-flake TestJetStreamAutoTuneFSConfig

- server/jetstream_cluster_3_test.go
Since replicated interest/workqueue streams now do message removals through proposals sent by the consumer leader, there could be a scenario where one consumer leader is on one server, and another leader on another. Both leaders process acks first, and both decide to not remove the message, then the followers process acks (and they aren't allowed to propose message removals). Due to this ordering the messages would not be removed early, and `checkInterestState` needs to run to clear them up.
> De-flake TestJetStreamClusterInterestStreamConsumer

- server/client.go
- server/leafnode_test.go
The test `TestLeafNodePubAllowedPruning` would sometimes report (after all go routines calling c.pubAllowed() being done) that the cache size was greater than the max allowed (128).
@MauriceVanVeen did fix the test with a correct explanation of why this test flapped, but I think we can improve a tiny bit the code so that the cache is much likely to be pruned enough.
In this PR, I make `prunePubPermsCache()` attempts up to 5 times to prune enough the cache, locking/releasing at each attempt to improve the odds that another routine takes a shot at it.
In my experiments, I am seeing only up to 2 attempts to be below the max size (and less than 10ms execution time). That being said, with artificial sleep before the release of the lock, it could take way more attempts. So for very slow …
> [IMPROVED] Publish permissions cache pruning

- server/jetstream_cluster_3_test.go
This was because it was calling `streamAssignment` without proper JS locking.
> Fixed test `TestJetStreamClusterMetaRecoveryLogic` causing data race

- server/filestore.go
- server/filestore_test.go
File store should only recover `%d.blk` files. If a file would be compressed there's temporarily a `%d.blk.tmp` file. Those temporary files would be recognized during recovery by `fmt.Sscanf`, which resulted in loading the same block file multiple times.
Also de-flakes `TestFileStoreFullStateBasics` as it includes some tests that use compression.
> [FIXED] Only recover .blk files in file store

- server/filestore.go
- server/memstore.go
- server/store_test.go
The following PR builds on top of PR https://github.com/nats-io/nats-server/pull/6686 by @svenfoo:
> This brings back an optimization that was removed with commit 79b41b122511df.
>
> Without this optimization the first sequence number is lost from the per-subject state whenever a message is added and the per subject limit is enforced. This is happening a lot on a stream with MaxMsgPerSubject set to 1. And it can lead to a dramatic slowdown when catching up on a stream with sequence numbers spread out wide.
Resolves https://github.com/nats-io/nats-server/issues/6687
Signed-off-by: Sven Neumann <sven.neumann@holoplot.com>
> Optimize removeSeqPerSubject() for MaxMsgPerSubject == 1

- server/filestore.go
- server/filestore_test.go
- server/jetstream_cluster_2_test.go
- server/jetstream_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
This PR proposes subject delete markers through the stream, avoiding a last sequence mismatch between the stream layer and the store, and ensuring that in clustered mode, all replicas are inserting the markers in a consistent order.
Co-authored-by: Maurice van Veen <github@mauricevanveen.com>
> Proposed subject delete markers

- server/filestore.go
- server/jetstream_cluster_2_test.go
- server/memstore.go
We would only reset the timer based on the newly submitted TTL value if the timer was already running, but that could have been set to `MaxAge` based on no messages being left in the stream if it was configured, delaying the next clean-up. Instead just kick the timer anyway with each new TTL message.
> Fix timing inconsistency between `Nats-TTL` and `MaxAge` timers

- server/raft.go
- server/raft_test.go
- If a snapshot was created, and the WAL would move forward to a different term/pterm, and a new leader would send a heartbeat/message referencing the same `applied`/`pindex` as in the snapshot, then it would reset the WAL. Instead of cleanly truncating back to applied/snapshot.
- If a snapshot is made multiple times for the same `applied` number, the correct value for the entry's `term` gets lost, due to the first snapshot compacting it. Only ever allow one snapshot to be made for a given `applied` number, to ensure correctness.
> NRG: Snapshot create/truncate logic

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/raft.go
When creating a replicated stream/consumer a preferred leader is selected, which will start campaigning earlier than the normal election timer. This is to speed up leader election so we can respond quickly to the create request.
However, campaigning uses a random delay between 100-800ms which can delay any replicated create request by at least that delay, averaging around ~470ms to create. Versus ~20ms for non-replicated assets.
Since it's the initial creation/campaign, we could speed it up further to not have an as long delay. With this PR the average create time would be ~60ms instead, significantly speeding up replicated asset creation.
This change also significantly speeds up server test times that rely on a setup containing replicated stream/consumer creation.
Resolves …
> [IMPROVED] Replicated asset creation performance

- server/client.go
- server/client_test.go
- server/opts.go
- server/reload.go
When true, trace logs will no longer emit the payload of the message, only the headers if these are present.
An additional change, is not emitting the MSG_PAYLOAD log line if the payload is empty.
> (2.11.x) [log] Add TraceHeaders option

- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/stream.go
`o.checkRedelivered` would throw away delivered counters for messages if the server that became consumer leader was a lagging-behind stream follower. Should preserve this data to ensure the counters stay correct and the client gets the right data once the stream becomes up-to-date again.
> [FIXED] Preserve redelivered state with lagging stream

- server/raft.go
Before this change there were two log statements: `WRN Resetting WAL state` and `DBG Resetting WAL`. Whenever a WAL needs to be reset, when looking at the WRN log, it means something went wrong and we can't properly replicate (which could result in desync). The DBG log however looks just as scary but actually is harmless. You'd see that log message when truncating the WAL back to applied/snapshot, which is normal and can happen.
Updating the wording in the DBG log to clearly differentiate between a (bad) reset and clearing/truncating the WAL which is normal in this case.
> NRG: Clarify debug log when clearing WAL

- server/filestore_test.go
- server/memstore_test.go
A performance regression with subject state performance was fixed in https://github.com/nats-io/nats-server/pull/6688.
This performance regression existed in v2.10.25 and v2.10.26. Prior to v2.10.25 (v2.10.24 and lower) there was no performance regression, but there were some cases where the subject state would not be kept up-to-date correctly (although this did not apply to `MaxMsgsPer=1`).
The added benchmark confirms the performance optimization put into place is kept, as it's exponentially expensive to recalculate the next subject sequence otherwise.
Measuring the time taken to execute this benchmark (locally) before and after fixing the regression:
- Memory, before: 2m32s, after: 300ms
- File, before: 31s, after: 1s
> Benchmark performance of MaxMsgsPer=1 subject state optimization

- server/accounts.go
- server/accounts_test.go
- server/events.go
- server/jetstream.go
- server/monitor.go
- server/monitor_test.go
- server/opts.go
- server/server.go
Previously, if 2 accounts exported the same subject, another account would not be able to import the 2 accounts with the same subject. This would produce an error saying that there was a duplicate.
We are changing the internal structure to store the service imports which is now allowing such services import definition.
See test `TestAccountMultipleServiceImportsWithSameSubjectFromDifferentAccounts` for an example.
> [IMPROVED] Services: Now possible to import same subject from diff accounts

- server/memstore.go
- server/store_test.go
The change from `ms.Purge()` to `ms.purge(0, false)` in https://github.com/nats-io/nats-server/commit/0208ab26237a9b347e8561b187ebc622958a2bb3, introduced a regression in 2.11.0 where it would set the `FirstSeq=0` and the `LastSeq` be max of `uint64`, making the in-memory stream unusable after.
This change makes the memstore a bit more aligned with the filestore, where `fs.purge(0, false)` equals a full purge as well.
Resolves https://github.com/nats-io/nats-server/issues/6709
> [FIXED] PurgeEx with zero seq equals Purge

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
Relates to https://github.com/nats-io/nats-server/pull/6535
When upgrading from 2.10.x to 2.11.x, a standalone server would not allow what would otherwise be idempotent stream/consumer creates.
> [FIXED] Idempotent stream/consumer create after standalone server upgrade

- .github/workflows/release.yaml
> Use `permissions` key in GHA release workflow

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
If a server is peer-removed, a new peer will be selected if the server hosted a stream. That new peer would be given the new peer set by the meta layer, but would then reset back to the old peer set as part of the stream's log.
This is a short-term fix, proposing the new peer set through the stream's log to ensure all replicas agree on it.
Later we'll need to rework some parts to ensure the meta layer only 'suggests' new changes, but the proposing actually goes through the stream/consumer's log instead of meta's log.
Co-authored-by: Neil Twigg <neil@nats.io>
> [FIXED] Stream peers drift after server peer-remove

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
Related to https://github.com/nats-io/nats-server/pull/6720, but for consumer peer sets.
Makes `processClusterCreateConsumer` more aligned with `processClusterCreateStream` by also doing the call to `createRaftGroup`, which proposes the peer change automatically.
> [FIXED] Consumer peers drift after server peer-remove

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
In some leafnodes setups with shared system account, the leafnode is supposed to set itself as observer and step down so that only servers in the hub cluster can be elected leaders. A test was flapping but it turns out that there was a race condition that could cause a server that has chosen to be in observer mode and step down to still end-up being elected.
Added a dedicated test that was able to reproduce the issue more easily than the leafnode test.
> [FIXED] JetStream clustering: observer incorrectly elected leader

- server/opts.go
- server/opts_test.go
Improve the config parsing to make `authorization` -> `timeout` parsing consistent with the `tls_timeout` option
> [IMPROVED] Config Parsing consistency with authentication timeout option

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_4_test.go
Antithesis triggered duplicate Raft nodes with the following scenario:
- follower needs to catchup based on snapshot, but is leaderless, so results in: `catchup aborted, no leader`
- call to `mset.resetClusteredState(..)` attempts to restart Raft node
- `mset.stop(..)` call resets `sa.Group.node = nil`
- goes into `js.createRaftGroup(..)` and waits for Raft node to stop
- in the meantime this folllower gets a snapshot from the meta layer, which updates/checks the stream assignment
- update notices `sa.Group.node == nil`
- does another call to `js.createRaftGroup(..)`, and also waits for Raft node to stop
- now Raft node stops and both `js.createRaftGroup(..)` calls duplicate the Raft node
- health check now notices `Detected stream cluster node skew`, deletes node and resets
This fix …
> [FIXED] Duplicate Raft nodes during restart

- .github/workflows/tests.yaml
- scripts/runTestsOnTravis.sh
This will keep the race detector runs on development branches, but it will no longer run on `main`, release branches or `pull_request` runs.
> CI: Only run race detector on development branches

- server/filestore.go
- server/jetstream_cluster_2_test.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
- server/memstore.go
- server/stream.go
Subject delete markers, if enabled, will now also be placed for TTL'd messages and not only messages expired by MaxAge.
However, there would be an issue if `SubjectDeleteMarkerTTL: 2h` and message `TTL: 5s` for example. If a subject delete marker for that subject already existed, then there wouldn't be a new subject delete marker if this message expired earlier than the previous subject delete marker. (Since subject delete markers don't place another marker once they expire)
To alleviate this, the TTL will always be made to be at minimum the `SubjectDeleteMarkerTTL`. This is not a hard error on publish, but will dynamically update the TTL based on the `SubjectDeleteMarkerTTL`. Since subject delete markers can be seen as a way to inform consumers about the removal of a subject, and the TTL …
> Place subject delete markers for TTL'd messages

- go.mod
- go.sum
> Update nats.go dependency to v1.41.0

- server/filestore.go
- server/filestore_test.go
We had a bug where we were only looking at the first msg since we did not offset buf by index.
> [FIXED] Fix for a bug in recovering ttls without the hashwheel info.

- server/jetstream_test.go
- server/stream.go
Using import/export, if one tries to limit the consumer create API with specific stream name and subject filter, the sync of a mirror would fail if using a single subject transform.
This PR checks that if there is no filter subject, but a single entry in FilterSubjects, then we switch to simple FilterSubject as to allow the use of the extended consumer create API that allows for fine grained permissions.
Resolves #6751
> [FIXED] JetStream: cross-account mirror with subject transform issue

- server/pse/pse_freebsd_cgo.go
- server/pse/pse_freebsd_sysctl.go
For the pse support for FreeBSD:
* switch the CGO implementation to require the cgo build tag, rather than per-architecture exemptions
* rather than have N files, 1 for each arch, to set the constants for that one arch, switch the existing non-CGO file:
+ Be named without an arch constraint (use `_sysctl` instead)
+ Use arch build tags
+ Use an init-time runtime.GOARCH dispatch to set the variables needed.
> FreeBSD: PSE non-CGO for arm64 too

- server/filestore.go
- server/jetstream_test.go
When creating a stream a custom first sequence can be used to skip ahead the initial stream sequence. However, if a file-based stream was setup to use a custom first sequence, if the server restarted it could come up without any messages. Essentially fully purging the stream of its contents.
This would only happen IFF:
- the stream is file-based
- the stream uses a custom first sequence
- the server restarts
- the first message's sequence == custom first sequence
This bug exists in all versions starting from 2.10.0, until this fix is released. It can be mitigated prior to a restart by ensuring streams that apply above conditions have had the first message at that sequence removed.
> [FIXED] Filestore initial first seq purge after restart

- .goreleaser.yml
Make contents of the archive to be owned by root, so archives have same shasum, no matter which user runs the build.
https://www.gnu.org/software/tar/manual/html_node/Reproducibility.html
Built 2.11.0 tag locally with:
`# go clean -cache && goreleaser  release --skip=announce,publish,validate --clean -f .goreleaser.yml`
File permissions in the archive are different, reported by https://diffoscope.org/: 
```
--- nats_server_gh_assets/2.11.0/nats-server-v2.11.0-linux-amd64.tar.gz
+++ nats-server/dist/nats-server-v2.11.0-linux-amd64.tar.gz
├── nats-server-v2.11.0-linux-amd64.tar
│ ├── file list
│ │ @@ -1,3 +1,3 @@
│ │ --rw-r--r--   0 runner    (1001) docker     (118)    11357 2025-03-19 15:28:05.000000 nats-server-v2.11.0-linux-amd64/LICENSE
│ │ --rw-r--r--   0 runner    (1001) docker …
```
> make .tar.gz file metadata reproducible

- server/filestore.go
- server/filestore_test.go
`PurgeEx` would not write all tombstones, and `Compact` would not write tombstones at all. After a restart all would be good if `index.db` is available and valid. But if it's missing or invalid, some messages would not be removed due to the missing tombstones, resulting in inconsistencies in the stream state.
Also made `rebuildStateLocked` consistent with `recoverMsgs`. Must also not set the first sequence to be lower if the message block was empty, and the first sequence was set based on the known last sequence without timestamp.
> [FIXED] Missing tombstones in file store for `PurgeEx` and `Compact`

- server/memstore.go
- server/memstore_test.go
Interior deletes would not be cleaned up/leaked if the memory stream got fully purged. Compact and reset would already properly cleanup the deletes.
> [FIXED] Memstore leaks interior deletes on purge

- server/client.go
- server/jetstream_cluster_1_test.go
Streams, consumers and subjects are allowed to have `@` characters, but JS ACKs would be invalid if a client requests messages from a consumer leader and is not directly connected to the server hosting that leader.
When publishing a message with subject `foo.with.@.at`, a client would receive the following from the server:
```
subject: at
reply: $JS.ACK.StreamNoAt.ConsumerNoAt.1.1.1.1744203858108658190.0@foo.with
```
Instead the following should be sent/received:
```
subject: foo.with@at
reply: $JS.ACK.StreamNoAt.ConsumerNoAt.1.1.1.1744203986298728967.0
```
Clients would either recognize the invalid JS ACK and return errors, or for clients that would allow to `msg.Ack()`, the server would not be listening on that subject and the message would not be acked. …
> [FIXED] Invalid JS ACK for subject with '@' character

- server/jetstream_cluster_4_test.go
Expiring subject delete markers after a second was sometimes too quick, added an additional second for some tests.
> De-flake propose SDM tests

- go.mod
- go.sum
- server/jetstream_cluster_3_test.go
- server/jetstream_helpers_test.go
Using the new JetStream API from the client increases the reliability of this test as it removes the race conditions in the client between the consumer info and the consumer create calls (now fixed by the presence of the consumer actions).
> De-flake `TestJetStreamClusterParallelConsumerCreation`

- server/filestore.go
- server/filestore_test.go
- server/thw/thw.go
If a server successfully shut down, upon recovery it would still (incorrectly) print the TTL state was outdated.
The sequence that's written into the TTL file should contain up to which sequence the TTLs were valid. So we don't have an off-by-one where the TTL state file contains `LastSeq` and we reload the last TTL because `ttlseq <= LastSeq`.
Also cleaned up `fs.ttlseq` as it was not really used.
> [FIXED] No TTL outdated state after successful shutdown

- server/filestore.go
- server/filestore_test.go
Fixes an edge case where the stream state could reset during recovery in WorkQueue (WQ) streams.
In WQ streams, messages are removed immediately upon ACK. Once a message block becomes empty, NATS deletes the corresponding block file. After deleting the last message block (lmb), NATS also creates a new block file that carries the latest sequence and timestamp from lmb.
If NATS crashes between deleting the lmb and creating the new block file, on NATS reboot the recovery logic cannot restore the stream state due to the absence of any block files. This leads to a reset to sequence 0, potentially causing inconsistencies such as the consumer sequence being higher than the stream sequence.
This change updates the logic to first create the new block file before deleting the lmb. This ensures that …
> [FIXED] Lost sequences after hard kill in fs.removeMsgBlock of lmb

- server/consumer.go
For R1 AckAll consumers with Interest/WorkQueue retention would set the `floor` to `sgap`, which is the amount of messages that need to be deleted. However, that's incorrect, for example with:
```go
o.asflr = 2500
sseq = 2550
sgap = 50
```
We would scan from 2550 to 50, instead of from 2550 to 2501. If the `FirstSeq` of the stream was already at 2501, then we'd be doing over 2k additional iterations of `mset.ackMsg`.
```go
for seq := sseq; seq >= floor; seq-- {
mset.ackMsg(o, seq)
}
```
> [FIXED] AckAll R1 consumer use correct floor

- server/jetstream_cluster_4_test.go
- server/stream.go
When a stream follower requires a catchup from a leader but is unable to do so, `mset.resetClusteredState` is called. However, it would also result in the replicated consumer state to be deleted. Which isn't needed, as the node can just be restarted.
> [FIXED] Consumer reset on stream snapshot failure

- server/filestore.go
- server/jetstream_test.go
We have an effective and seemingly undocumented limit of 32MB for messages published into JetStream as `indexCacheBuf` in the filestore rejects any records that exceed this length. We did not catch this on publish however, and then `indexCacheBuf` would later error when consuming etc.
Related: #6797
> Avoid filestore corruption by rejecting large publishes into JetStream

- server/monitor.go
- server/monitor_test.go
The core issue was that the account names were not being sorted unless offset was non-zero. However, the first page will always be an offset of zero and thus there is no determinism of the order.
Now the accounts are sorted and the logic is simplified to handle both single account and multiple account queries.
> [monitoring] Fix jsz offset bug

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/norace_1_test.go
Related to https://github.com/nats-io/nats-server/pull/6469, about the following code:
```go
// Update delivered first.
o.updateDelivered(dseq, seq, dc, ts)
// Send message.
o.outq.send(pmsg)
```
`o.updateDelivered` requires proposing delivered state through Raft, and even if proposing fails, we immediately sent the message to the client. This is great for performance, but really bad for properly replicating this piece of data. Before the before-mentioned PR there would be a bunch of nasty side-effects of stuck consumer, perceived data loss through missed redeliveries, etc. Because clients could get messages that a new leader wouldn't know about if proposals failed.
The core issue is that we should only send the message AFTER we had quorum on updating delivered state. Otherwise the …
> [FIXED] Only deliver replicated message after quorum

- server/const.go
Includes the following (already cherry-picked) PRs:
- https://github.com/nats-io/nats-server/pull/6587
- https://github.com/nats-io/nats-server/pull/6607
- https://github.com/nats-io/nats-server/pull/6612
- https://github.com/nats-io/nats-server/pull/6609
- https://github.com/nats-io/nats-server/pull/6620
- https://github.com/nats-io/nats-server/pull/6668
- https://github.com/nats-io/nats-server/pull/6674
- https://github.com/nats-io/nats-server/pull/6647
- https://github.com/nats-io/nats-server/pull/6684
- https://github.com/nats-io/nats-server/pull/6691
- https://github.com/nats-io/nats-server/pull/6697
- https://github.com/nats-io/nats-server/pull/6705
- https://github.com/nats-io/nats-server/pull/6706
- https://github.com/nats-io/nats-server/pull/6704
- …
> Release v2.10.28-RC.1

- server/consumer.go
- server/jetstream_cluster_1_test.go
If for some reason a message was not delivered to a push consumer (for example the client/route connection closed as it was about to be delivered), it would be marked inactive, even if there's local interest for the `DeliverSubject`. This would result in a stuck push consumer that doesn't receive new messages.
> [FIXED] Inactive push consumer after failed delivery

- server/filestore.go
- server/memstore.go
- server/raft_test.go
De-flakes `TestJetStreamUpdateStream`, `TestJetStreamLargeExpiresAndServerRestart`, and `TestNRGSnapshotAndTruncateToApplied`.
Actually use 250ms as minimal expiry, and don't rely on v2.11.x behavior for test.
> De-flakes for v2.10.28

- util/nats-server-hardened.service
- util/nats-server.service
Based on description the following directives:
* [ExecStop](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#ExecStop=)
* [TimeoutStopSec](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#TimeoutStopSec=)
* [KillSignal](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html#KillSignal=)
This is what happens when one executes `systemctl stop nats-server` (or shuts down/reboots the host):
1. The timer for `TimeoutStopSec` is started.
2. `ExecStop` is executed
3. Immediately after `ExecStop` returns, `SIGTERM` is sent to the process.
4. After `TimeoutStopSec` seconds passed, if the service is still running, it is killed with `SIGKILL`
When we handle `SIGTERM`, [we do nothing if LDM is already in …
> Update example systemd unit files to use Lame Duck Mode

- server/jetstream_cluster_4_test.go
- server/stream.go
In https://github.com/nats-io/nats-server/pull/6741 if `SubjectDeleteMarkerTTL` is used it will require that any per-message TTL is either the same or higher than the configured `SubjectDeleteMarkerTTL`. This limitation was added to ensure a subject delete marker is not missed when there's already a subject delete marker for a given subject, and a new message with a lower TTL expires earlier.
This limitation doesn't need to apply when `MaxMsgsPer=1` is set, because then the subject delete marker will be removed automatically for the new published message. This allows you to have a high `SubjectDeleteMarkerTTL`, but use lower per-message TTLs, if the use case matches with `MaxMsgsPer=1`.
Resolves https://github.com/nats-io/nats-server/issues/6814 …
> [IMPROVED] SubjectDeleteMarkerTTL not used as minimum TTL when MaxMsgsPer=1 is set

- server/client.go
- server/client_test.go
- server/log_test.go
- server/monitor_test.go
- server/parser.go
Updated trace functionality to redact auth_tokens in addition to passwords in logs to prevent sensitive information leakage. Refactored logic to use a generalized `redact` function and added extensive tests to ensure proper redaction in various scenarios.
Fix #6666
Signed-off-by: Alberto Ricart <alberto@synadia.com>
> Redact auth tokens in trace logs for enhanced security

- server/accounts.go
- server/jetstream_jwt_test.go
After an account expires, it is expected that an existing or new connection for this account is closed/rejected. However, if the account's expiration time is updated, a new connection should be able to publish into a stream.
This was not the case because on account expiration, all its clients were closed, including internal ones, which would remove the subject interest for the stream.
Resolves #6806
> [FIXED] JetStream: message not accepted after expired account is updated

- server/jetstream_cluster.go
The equivalent in `monitorStream` already has this exact check but it never made its way into `monitorConsumer` seemingly. Buildkite runs picked up a panic here.
> Fix panic in `monitorConsumer` if meta nil

- server/signal.go
It would be useful to figure out what led to a change in the server state post-factum.   
`nats-server --signal term`
and observer in the console:
```
[390785] 2025/04/16 16:19:23.666627 [INF] Server is ready
[390785] 2025/04/16 16:19:54.341025 [INF] Trapped "terminated" signal
[390785] 2025/04/16 16:19:54.341190 [INF] Initiating Shutdown...
[390785] 2025/04/16 16:19:54.341316 [INF] Server Exiting..       
```
There is https://pkg.go.dev/golang.org/x/sys/unix#SignalName, that we could use to print names like SIGTERM here, but I guess we do not add the dependency just for that.
> Print "Trapped %q signal" as Notice level message

- server/jetstream_cluster_1_test.go
- server/raft.go
A server can be shutdown and then peer-removed from the cluster to have streams/consumers moved to a different server (if replicated), since it indicates a server will not be coming back.
However, imagine the following failover scenario/setup:
- server X fails due to cloud/server issue
- spin up new server Y
- shutdown server X, and peer-remove it, stream/consumer replica moves to server Y
- once the server X issue is resolved, restart server X
- shutdown server Y, and peer-remove it, stream/consumer replica moves back to server X
Although it sounds straightforward enough, you'd currently need to restart ALL servers in the (super) cluster to allow server X to come back like that. This would be a hidden requirement if the server X would only come back after some months, and servers would …
> [FIXED] Server peer re-add after peer-remove

- server/filestore.go
- server/filestore_test.go
- server/norace_2_test.go
- server/sdm.go
Make sure that we do async flush for multiple tombstones.
Also added in short circuit for PurgeEx when we know we have no more matches for explicit subjects.
> [FIXED] Async tombstones on PurgeEx

- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
Direct gets on subject delete markers would fail to decode due to one too many CRLFs.
> [FIXED] Direct get subject delete marker

- server/jetstream_consumer_test.go
- server/sublist.go
- server/sublist_test.go
The subject tree intersection could miss non-wildcard matches if they were followed up by further extended wildcards in other sublist filters. This is now fixed.
Fixes #6824.
Co-authored-by: Maurice van Veen <github@mauricevanveen.com>
> Fix subject tree intersection to match literals when followed by additional wildcards

- server/filestore.go
- server/jetstream_test.go
`fs.removeMsg` unlocks and relocks the filestore lock. We could be gracefully shutting down, write TTL state with the TTL-ed message expired, but have not yet removed the message because we shutdown too early. That would result in message not being removed by TTL after a restart.
For now we'll need to keep the message in the THW and check if the message is removed prior to removing it.
Later on we should make it so that `fs.removeMsg` doesn't unlock the filestore to do a callback. That would allow us to `fs.removeMsg` inline within THW's ExpireTasks and help fix the consumer pending race condition. But that will need more thinking/changes.
> [FIXED] TTL-ed message not removed after graceful restart

- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
Consumer state reporting would be incorrect for filtered consumers. For example:
- 2 messages in the stream, one matches your filter subject
- you fetch 2 messages, but only get one because that matches your filter
- you now ack that message at sequence 1
- after acking, your delivered and ack floor state should mention sequence 1
However, currently this is incorrect and reports sequence 2 for both.
We must always use our stored state, even if not replicated. The leader uses a running total, and although that can be relied upon for delivering new messages, it does not always report correct data when used for info requests.
> [FIXED] Consistent filtered consumer state reporting

- server/monitor.go
- server/monitor_test.go
When filtering on a given connection ID, if the user also filters on the state being "all" and the connection is opened, it would not be returned. It would be if the connection was closed.
Resolves #6839
> [FIXED] Monitoring: Issue with Connz filters "cid" and "state=all"

- server/mqtt.go
- server/mqtt_test.go
- server/opts.go
There was a hard-coded timeout of 4s for making JS API calls (`mqttJSAPITimeout`).
Added an MQTT config option to configure this timeout.
Partially fixes https://github.com/nats-io/nats-server/issues/6191 
I think the proper fix would require sending an error to the mqtt client that we could not create a subscription. But this helps to at least bump the limit.
Signed-off-by: Ondrej Belusky <zlymeda@gmail.com>
> [ADDED] MQTT: allow custom timeout for JS API calls

- server/monitor.go
- server/monitor_test.go
- server/raft.go
- server/raft_test.go
- https://github.com/nats-io/nats-server/pull/6851
- https://github.com/nats-io/nats-server/pull/6849
> Cherry-picks for 2.10.29-RC.2

- util/nats-server-hardened.service
- util/nats-server.service
I switched the hardened example config file to use `Restart=always` in c78874276 just over a year ago.  That was a mistake.
If the nats-server is asked to shut down, and shuts down cleanly, then the service manager should not restart it.  The server should be restarted if it exits on failure.
https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Restart=
> systemd: switch to Restart=on-failure

- server/filestore.go
- server/jetstream_test.go
Filestore would incorrectly set `mb.first.seq` after a `PurgeEx` using a sequence within an interior delete gap. It would set the first sequence to whatever is provided as the purge sequence, instead of properly moving the first sequence up and taking deletes into account.
> [FIXED] Filestore PurgeEx by sequence with interior delete gap

- server/consumer.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_3_test.go
- server/jetstream_test.go
A consumer with `MaxDeliver: 1` reports non-acked messages as `Redelivered Messages`, although no redeliveries have happened. The state is still preserved, otherwise unacked messages in an Interest stream can be lost if used for DLQ (https://github.com/nats-io/nats-server/issues/6538). But we don't report redeliveries anymore for this case.
Resolves https://github.com/nats-io/nats-server/issues/6874
> [FIXED] Don't report redeliveries for consumer with MaxDeliver 1

- server/gateway.go
- server/gateway_test.go
When a config reload is issued and a server has implicit remote gateways (that is, gateways that were gossiped and not explicitly configured), the TLS changes were applied only to explicit remotes.
With this change, the changes to the main `tls{}` block will be applied to implicit remotes.
Credit to @song0071000 for the proposed changes in the code.
Resolves #6875
> [FIXED] Gateway: TLS configuration reload now applies to implicit remotes

- server/filestore.go
- server/filestore_test.go
I encountered an issue where a Workqueue stream’s first and last sequence numbers were unexpectedly reset to 0 following an abrupt termination of the NATS server. Interestingly, the consumer remained fully caught up with messages and retained its expected state even after the crash, but the stream itself appeared to have been reset.
I was able to retrieve a backup of the data after the crash and debug it locally. During analysis, I found that new msgs had not been flushed to disk, resulting in a zero-sized blk file I believe. As a result, during recovery, the stream state remained at zero and the index.db could not be used to reconstruct the state
Resolves : https://github.com/nats-io/nats-server/issues/6881
Signed-off-by: souravagrawal <souravagrawal1111@gmail.com>
> [FIXED] workqueue reset to 0 when blk file is zero-sized due to unflushed data on crash

- server/ats/ats.go
- server/ats/ats_test.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/norace_2_test.go
> [IMPROVED] Move the access time service to its own package and ensure go routine cleanup.

- server/store.go
We ran into the "message too large" error today, but the server reports it as "message to large". This fixes the spelling mistake.
Signed-off-by: Christian Johansen <christian@cjohansen.no>
> Fix spelling mistake

- server/filestore.go
- server/memstore.go
`MultiLastSeqs` already held the read lock before calling `AllLastSeqs` which would try to take the read lock again, but this could result in a deadlock if another goroutine is meanwhile trying to take the lock for writing.
> Fix potential deadlock in `MultiLastSeqs`

- server/filestore.go
This improves `firstMatching` by simplifying the wildcard vs non-wildcard logic and removing a substantial number of allocations by no longer collecting `subs`. This results in quite a notable performance improvement and reduced GC pressure when checking interest state etc.
> Optimise `firstMatching` by reducing allocations

- server/jetstream_test.go
- server/memstore.go
- server/stream.go
Fixes #6077 by ensuring that we can't select a sequence number from the timestamp that falls below the stream first sequence.
Fixes #6032 by ensuring that the memory store doesn't return the first sequence incorrectly when there are no matching messages.
> Direct get fixes

- server/stree/stree.go
- server/stree/stree_test.go
Fix a bug that could cause a panic if subject to delete was shorter then index and prefix.
Also fixed some spelling.
> [FIXED] Potential panic if subject to delete shorter then interior node index and prefix.

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/store_test.go
> Correctly handle updates to `AllowMsgTTL` on streams

- server/client.go
- server/leafnode_test.go
If a request originates from cluster A and is routed to cluster B then to a leafnode where a service is running, sending back the reply could fail if the leafnode has restrictive publish permissions.
Resolves #6894
> [FIXED] LeafNode: Unable to reply if origin originates from super-cluster

- locksordering.txt
- server/stream.go
Otherwise this can potentially result in a deadlock if interleaving with certain other operations, i.e. stream purges, new consumer assignments.
> Don't hold `clsMu` while purging stream consumers

- server/stream.go
Reporting the stream ingest warning on high load to publishers was causing lock contention issues trying to get the stream name:
```
goroutine 3570823 [sync.RWMutex.RLock, 6 minutes]:
sync.runtime_SemacquireRWMutexR(0x4906aa?, 0x20?, 0xc54f06ec80?)
runtime/sema.go:100 +0x25
sync.(*RWMutex).RLock(...)
sync/rwmutex.go:74
github.com/nats-io/nats-server/v2/server.(*stream).name(0xc0006b4408)
github.com/nats-io/nats-server/v2/server/stream.go:5531 +0x4c
github.com/nats-io/nats-server/v2/server.(*stream).queueInbound(0xc0006b4408, 0xc0001a0000, {0xc1ece520b0, 0x10}, {0xc489410e40, 0x26}, {0x0, 0x0, 0x0}, {0xc237180c00, ...}, ...)
github.com/nats-io/nats-server/v2/server/stream.go:4401 +0x1e6
github.com/nats-io/nats-server/v2/server.(*stream).processInboundJetStreamMsg(0xc0006b4408, …
```
> Fix lock contention issue when reporting stream ingest warnings

- server/raft.go
Usually `Resetting WAL state` is a prime indicator something went horribly wrong with replication, and resetting is our last effort at fixing things. Antithesis reports on this being logged so we can look into it and fix the condition.
However, this also triggers if the WAL is empty, a leader gets elected and stores a message that doesn't get quorum. Once a new leader is elected and this entry without quorum gets removed, we'd also log `Resetting WAL state` even though this is a normal condition. If we have made no commits, it's safe to reset/clear the WAL. This PR changes the log line to clarify this.
Relates to https://github.com/nats-io/nats-server/pull/6705
> [IMPROVED] NRG: Clarify log when resetting WAL

- server/client.go
- server/leafnode.go
- server/server.go
- server/server_test.go
- test/client_auth_test.go
- test/leafnode_test.go
- test/routes_test.go
- test/test.go
In response to a leafnode or client CONNECT protocol, the server responds
with an INFO that contains the name of the account it is bound to and if
this account is the system account.
For client connections, since most of our supported clients send the
CONNECT and a PING and expect a PONG *first*, the server will send
the "Connect Info" protocol only after receiving the first PING and
sending back the first PONG.
> [ADDED] Protocol: INFO in response to CONNECT contains account info.

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_cluster_2_test.go
- server/stream.go
When shutting down the stream would not be snapshotted. Either the monitor would close first and `doSnapshot` would not be called, or there would be a race with the Raft node being stopped and `InstallSnapshot` becoming a no-op.
Relates to https://github.com/nats-io/nats-server/pull/6279
> [FIXED] Attempt stream snapshot on shutdown

- server/stree/stree.go
- server/stree/stree_test.go
> [IMPROVED] Added in additional tests and one minor bug fix

- server/norace_2_test.go
This test could flake because we currently don't provide read-after-write guarantees when using `DirectGet`. Disabling `DirectGet` means only the leader can answer, which ensures the immediate level of consistency this test expects.
The leader answering still doesn't 100% guarantee read-after-write, that needs to be fixed as part of https://github.com/nats-io/nats-server/issues/6557. Once we support that, this test can be adapted to use `DirectGet` again, but with the additional read-after-write guarantee.
> De-flake TestNoRaceJetStreamKVReplaceWithServerRestart

- server/norace_1_test.go
- server/raft.go
- server/raft_test.go
Desync was observed in the Raft layer in the following scenario:
1. Server 1 is leader at `term=1` and proposes an entry but no server receives this entry.
2. Server 2, after some time, gets a heartbeat from Server 1 and starts catching up.
3. Server 2 receives the entry from Server 1 in its subscription buffer, but does not yet process this entry from `term=1`.
4. Server 3 tries to become leader for `term=2`, and Server 2 ups its term to `term=2` and votes for Server 3.
5. Server 2 now processes the catchup entry from the leader at `term=1` and (wrongfully) accepts it.
In this case, the catchup entry at step 5 from a leader at `term=1` should be rejected, because it knows the highest term is `term=2` at that point. We must only accept changes to the log if the leader tells us to. Because …
> NRG: Only allow highest known term for catchup

- server/raft.go
> NRG: Improve docs & fix ae response leak

- server/jetstream_helpers_test.go
- server/jetstream_leafnode_test.go
- server/leafnode.go
- server/stream.go
When a consumer for a source or a mirror is failing to be created, we backoff creation attempts.
If the failures were due to a downed leafnode, meaning the mirror or source is across a leafnode connection, the resync could take more time then desired after the leafnode reconnects.
This improves resync time by hooking into the leafnode's reconnect logic (either via connect or async info).
Once we detect the reconnect, we search for streams that are leaders and are mirrors or sources, and  do not have an active sync consumer.
If we detect this we will reset the consumer backoff and retry with just a small jitter backoff.
> [IMPROVED] Speed up a mirror or source consumer's resync across leafnode connections.

- server/stream.go
There was a data race between writing stream metadata in `copyStreamMetadata` and the reading using `reflect.DeepEqual`.
```
Write at 0x00c0002a0c30 by goroutine 227:
runtime.mapdelete_faststr()
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.linux-amd64/src/runtime/map_faststr.go:321 +0x0
github.com/nats-io/nats-server/v2/server.deleteDynamicMetadata()
server/jetstream_versioning.go:177 +0xa8
github.com/nats-io/nats-server/v2/server.copyStreamMetadata()
server/jetstream_versioning.go:70 +0x66
github.com/nats-io/nats-server/v2/server.(*Account).addStreamWithAssignment()
server/stream.go:537 +0x46e9
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream()
server/jetstream_cluster.go:3842 +0x1b24 …
```
> [FIXED] Data race on copy stream metadata

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
There was a race condition where the stream/consumer health check would delete the group's node if the stream/consumer's node was not yet initialized.
The following would be observed in the logs:
```
Detected stream cluster node skew
Resource not found: open /nats/store/jetstream/$SYS/_js_/S-R3F-tuN0AWqr/tav.idx: no such file or directory
Error writing term and vote file for "S-R3F-tuN0AWqr": open /nats/store/jetstream/$SYS/_js_/S-R3F-tuN0AWqr/tav.idx: no such file or directory
```
> [FIXED] Cluster node skew race

- .github/workflows/tests.yaml
- server/raft.go
This PR fixes an integer overflow that would happen only on 32-bit architectures. It also improves the `elen` counting in the Raft code to do the right thing on both 32-bit and 64-bit architectures.
Also adds 32-bit build checks into CI so this kind of thing doesn't sneak in again.
> NRG: Fix integer overflow on 32-bit platforms

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
Adds a new `SubjectForSeq` function to the filestore that copies less and performs fewer allocations compared to `LoadMsg`. This is then used inside `needAck` when we don't know what the subject is for the sequence, i.e. when called from `checkStateForInterestStream`.
There are more improvements that need to be made here but for now this will reduce the amount of garbage created by this process, and by extension, reduce GC pressure and CPU usage on large interest-based streams.
> Optimise `needAck` with new `SubjectForSeq` store function

- server/jetstream_test.go
- server/stream.go
When switching from limits to interest, we were propagating this update to consumers, but we weren't doing so when switching from interest to limits. This would leave consumers running with `o.retention` set to `InterestPolicy`, continuing to run `checkStateForInterestStream` etc even after the stream itself had moved back to the `LimitsPolicy`.
> Propagate stream interest policy changes to consumers in all cases

- server/jetstream_cluster.go
- server/monitor.go
- server/raft.go
Converting the timestamps to `UnixNano` meant that all of these operations were using wall-clock rather than monotonic time, which meant that these operations were not safe against wall-clock drifts or NTP adjustments. This could result in unexpected loss of quorum.
> NRG: Monotonic heartbeat and quorum tracking

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
The health check could still reset/restart stream and consumer Raft nodes. However, if a new Raft node instance is assigned to the stream/consumer assignment, but this is not yet reflected in the stream/consumer, then the new Raft node's state would be fully deleted. This is possible because the assignment's Raft node is updated under the JS lock, but the stream/consumer nodes aren't, resulting in many potential race conditions for the health check to do the wrong thing.
The health check must only do reporting and not try to fix anything, it simply can't guarantee both the assignment and stream/consumer nodes are not stale.
When the logs show `Detected stream/consumer cluster node skew` once, there's nothing to worry about. It was simply a temporary condition that resolved itself. If it's …
> [FIXED] Health check only does reporting

- server/consumer.go
- server/jetstream_test.go
When the consumer was trying to find the next message from a skiplist, we were not correctly moving `o.sseq` up to the next skiplist sequence, which would result in missed messages and some acks being ignored. This is particularly evident with interior deletes, such as those created by the `MaxMsgsPerSubject` limit which the unit test uses.
> Fix `DeliverLastPerSubject` consumer policy with interior deletes

- server/pse/pse_linux.go
- server/pse/pse_test.go
4KB pages were assumed rather than asking the OS.
> Report memory usage correctly on Linux with huge pages

- server/client.go
- server/jetstream_benchmark_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_test.go
- server/stream.go
This extends Maurice's work in #6973 by adding source tracking in the `Nats-Counter-Sources` header. This allows us to correctly rewrite `Nats-Incr` when a source counter that's non-zero is added, as well as correctly identifying and reconciling gaps due to the source being removed or unavailable, or when there are lost messages etc, providing eventual consistency with sourced counters.
The additional unit test proves the functionality even with source streams that have `MaxMsgsPerSubject` of 1, as well as a combination of stream-local and sourced increments, with full header checking.
> (2.12) Source-aware counter CRDT

- server/stream.go
When sourcing from a stream on a leaf node, it may be useful to know when it was last seen and how long ago that was. Before now that wasn't really possible because it would reset roughly every 10 seconds, even if the source consumer wasn't even established.
This makes the last seen value for sources a bit more valuable. Even though this value is not preserved after restarts, and will show last seen never in that case.
> [IMPROVED] Preserve source last seen

- server/events_test.go
- server/monitor.go
- server/monitor_test.go
Previously `SUBSZ` reported the number of returned `SubDetails` in `Subsz.Total`, which means that when using pagination if the total number of subs exceeds `Limit` it will cap at that). That does not align with how `Total` is used when using pagination in other endpoints (e.g. in `CONNZ` `Total` contains the full number of connections).
> Fix subsz total subs count

- server/filestore.go
- server/filestore_test.go
We should only return that the cache can be expired if the start sequence is the end of the block, otherwise we will repeatedly load and expire the cache of the same block in `LoadNextMsgMulti`. This results in a noticeable slowdown.
Fixes #7014.
> Fix performance issue in `firstMatchingMulti`

- server/jetstream_cluster.go
- server/jetstream_cluster_3_test.go
When restoring a replicated stream from a backup, healthz would report `JetStream stream '$G > test-stream' is not current: monitor goroutine not running`. This was due to not initializing we were already running that monitor goroutine.
> [FIXED] Healthz "monitor goroutine not running" after stream restore

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
A removed stream could be wrongfully revived. For example when quickly scaling up and down, the follower will not have caught up, eventually call `mset.resetClusteredState` and then the stream would be wrongfully recreated.
Note, there's still a race condition here. We're not holding any locks, and the revival is done (eventually) in a goroutine. There's not too much we can do to guard against the unfortunate scenario where all things align just right (at least for now). But we can easily guard against `mset.resetClusteredState` not resetting if we know the stream is already closed at that point.
> [FIXED] Removed stream is revived

- .github/workflows/tests.yaml
Capture `github.event.pull_request.body` in `"$PR_DESC"` as the PR description.
> CI: Check PR sign-offs with env variable

- server/client_test.go
- server/events.go
- server/events_test.go
Fixes #6543 SRV-13 by generating `$SYS.ACCOUNT.$G.CONNECT` and `$SYS.ACCOUNT.$G.DISCONNECT` events in the system account.
> (2.12) Generate connect and disconnect events for global account clients

- server/jetstream_benchmark_test.go
This ensures that the benchmark covers both `LoadNextMsg` and `LoadNextMsgMulti`.
> Update `BenchmarkJetStreamConsumeFilteredContiguous` to test both single-filter & multi-filter

- server/jetstream_cluster_2_test.go
- server/raft.go
- server/raft_test.go
When an outdated follower requires JetStream-layer stream catchup, but the leader goes down, and the follower then restarts. Upon recovery it will retry the catchup, which will fail because there's no leader. If the outdated follower can get quorum and become leader: the catchup would be aborted, and the follower would continue with missing data.
This is solved by not upping `n.applied` on recovery, because a server can only become leader if all commits are applied (so `n.commit==n.applied`). This requires the Raft recovery and snapshot processing on startup to finish before allowing the server to start a leader election.
> NRG: Partial catchup protection

- server/raft.go
The `n.wal.Compact()` call before `n.installSnapshot()` is potentially dangerous in a crash scenario as we could blow away the log without having written the snapshot to disk yet. Once the snapshot is written, `n.installSnapshot()` will compact the log itself to the same index (as `lastIndex == n.pindex`).
> NRG: Don't compact on catchup until snapshot written

- server/client.go
- server/errors.json
- server/jetstream_benchmark_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
- server/stream.go
Implement a counter CRDT based on [ADR 49](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-49.md).
R1 is pretty straightforward, enable `AllowMsgCounter`, and publish using `Nats-Incr` headers. R3 is also straightforward from the user's perspective, it works exactly the same, but in terms of replication we need to keep a running count if a single counter is rapidly updated by multiple processes such that there are multiple but not yet applied proposals and can continue counting without needing to block or error.
Additionally, Mirrors can do verbatim copies. Sources can do verbatim copies if `AllowMsgCounter` is disabled. Sources can aggregate counters if `AllowMsgCounter` is enabled.
Resolves https://github.com/nats-io/nats-server/issues/6560
Signed-off-by: …
> (2.12) Counter CRDT

- locksordering.txt
- server/errors.json
- server/filestore.go
- server/jetstream_batching.go
- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
- server/memstore.go
- server/norace_1_test.go
- server/raft.go
- server/stream.go
This PR implements an initial version for atomic/batch publishing, as described in [this ADR](https://github.com/nats-io/nats-architecture-and-design/pull/346).
In general:
- A client can now be implemented (given the current limitations listed below) to use the new batch API. For an example, see `TestJetStreamAtomicPublish`.
- The stream config field for `AllowAtomicPublish` is added, support for batch headers `Nats-Batch-Id, Nats-Batch-Sequence, Nats-Batch-Commit`, feature versioning, and support for batching as per the ADR.
- Dedupe state (`mset.ddmap, mset.ddarr, mset.ddindex`) is now guarded by a separate lock (`mset.ddMu`). This is required because we need to keep holding `mset.clMu` while accessing the dedupe state, and we can't use `mset.mu` as that would be a lock order …
> (2.12) Initial atomic batch publish

- server/consumer.go
- server/jetstream_cluster_3_test.go
- server/jetstream_consumer_test.go
For a pull consumer that has an `AckWait: 30s` and an `InactiveThreshold: 5s`, if it fetches a few messages and only acks all of them after 20 seconds, it will be removed due to inactivity.
Pending acks should count toward activity, even if we've not heard from the consumer in a while, we can safely assume they're processing the message if still within `AckWait` and must not mark it inactive early.
Resolves https://github.com/nats-io/nats.go/issues/1900
> [FIXED] Pull consumer AckWait signals still active

- server/client.go
- server/client_test.go
`Nats-Expected-Last-Subject-Sequence-Subject` and `Nats-Expected-Last-Subject-Sequence` share a common prefix. We could not get the proper value for the latter header depending on the ordering in the headers.
> [FIXED] Get header value with shared prefix

- server/filestore.go
- server/filestore_test.go
We would panic on `if mb.ttls == 0` after `goto retry` if `fs.selectMsgBlock(seq)` returned a `nil` message block.
This shouldn't happen normally, since `fs.selectMsgBlock(seq)` selects either the message block that contains the `seq`, or the block after the one that should have contained it. Returning no block at all would likely mean the storage has been corrupted in some way.
> [FIXED] Panic when selectMsgBlock returns nil

- server/jetstream.go
- server/opts.go
- server/server.go
- server/test_test.go
Flipped to `opts.NoJetStreamStrict` so any empty `Options{}` will have JetStream be strict by default.
Resolves https://github.com/nats-io/nats-server/issues/6539
> (2.12) JetStream Strict by default

- server/jetstream_api.go
- server/jetstream_test.go
- server/stream.go
As per ADR-52, nats-io/nats-architecture-and-design#352.
> (2.12) Add `no_hdr` support to message get and direct get

- server/parser_fuzz_test.go
- server/server.go
- server/server_fuzz_test.go
- server/subject_fuzz_test.go
Add fuzz tests:
1) Protocol parsing (adapting the previous test)
2) TLS handshake validation
3) Subject collision detection. 
Signed-off-by: Sergey Sobolev <seregasobolev96@gmail.com>
> Add fuzz tests

- server/errors.json
- server/jetstream_batching_test.go
- server/jetstream_cluster.go
- server/jetstream_errors_generated.go
For now reject the usage of `Nats-Expected-Last-Sequence` and `Nats-Last-Msg-Id` since they are currently not compatible with batching. Will revisit and enable if this can be fixed.
Relates to https://github.com/nats-io/nats-server/issues/6975
> (2.12) Atomic batch: reject unsupported headers

- server/raft.go
- server/raft_test.go
We would not truncate back to a snapshot properly if `n.applied` was not caught up or moved further ahead.
For example:
- outdated server catches up and gets a snapshot at index 10 (`n.commit = 10`, but `n.applied = 0` still)
- server misses message at index 11
- server receives message at index 12 and catches up between indices 10-12
- server now receives message at index 11 with a delay (the `ae.pindex` will be 10, so it requires a consistency check on an append entry that doesn't exist because a snapshot is there)
- we now need to truncate the log back to the snapshot (we would reset the WAL fully, which is bad)
We now check if we can truncate back to the snapshot successfully, otherwise we still reset the WAL as before.
Also improved some logs to make debug lines more helpful when …
> NRG: Truncate back to snapshot properly

- server/auth_callout_test.go
Prior to https://github.com/nats-io/nats-server/pull/6808, `ac.ClientInformation.User` and `ac.ConnectOptions.Token` would both hold the raw token value. This means in an auth callout service, you could use `ac.ClientInformation.User` when doing token-auth, and it would break after upgrading to 2.11.2+. However, the token is not public information so it's now `[REDACTED]` in `ac.ClientInformation.User`.
When upgrading past server version 2.11.2, make sure to use `ac.ConnectOptions.Token` and not `ac.ClientInformation.User` when getting the token.
This PR just adds a test to explicitly cover this as correct behavior, and calling out the above functionality for anyone upgrading and noticing this change.
> Add auth callout [REDACTED] token test

- server/filestore.go
- server/filestore_test.go
- server/jetstream_benchmark_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
- server/memstore.go
- server/store.go
- server/stream.go
The filestore's `AsyncFlush` setting can now be enabled for a JetStream stream using the `AllowAsyncFlush` field. Some initial benchmarks showed a 10-15% performance increase when using a R3 stream (3-node cluster with each node in a different availability zone).
Only enabling the filestore's `AsyncFlush` setting without additional code would be unsafe. That's why this PR introduces some new mechanisms to make it safe. This makes the performance improvement essentially "free", with no negative consequences for data safety/consistency.
- Before `n.InstallSnapshot(..)` we now do a `mset.flushAllPending()` to ensure all state represented in the snapshot, actually all made it to disk.
- The previous `fs.lmb` would only be sometimes be flushed, for example in `fs.checkLastBlock` but not when …
> (2.12) Filestore async flush

- server/filestore.go
- server/jetstream_test.go
If a message block was compressed and the encryption cipher was changed, a cipher conversion would happen on startup. Although the cipher conversion would be successful, the sanity check would not take compression into account and would fail. Now we optionally decompress to allow for the sanity check to pass before converting to the new cipher.
> [FIXED] Cipher conversion fails on compressed msg block

- server/errors.json
- server/jetstream_batching.go
- server/jetstream_batching_test.go
- server/jetstream_cluster.go
- server/jetstream_errors_generated.go
- server/opts.go
- server/stream.go
Limits for batches can now be configured with the following settings (listed values are the defaults):
```
jetstream {
limits {
batch {
max_inflight_per_stream: 50
max_inflight_total: 1000
max_msgs: 1000
timeout: 10s
}
}
}
```
Additional to the above listed limits, there's also a hard-coded limit of 64 characters for the `Nats-Batch-Id`. This protects the system and ensures very long IDs will not need to be stored in the batching map.
Resolves https://github.com/nats-io/nats-server/issues/6977
> (2.12) Atomic batch: limits & cleanup after timeout

- server/filestore.go
- server/raft.go
- server/raft_test.go
Every call to `n.Applied` would result in calling `n.wal.FastState`, we can prevent this from happening by adding some additional tracking in the `raft` struct itself to not need to call out. The `raft` struct is now also aligned.
Any tombstones that need to be written as part of the `Compact` are now flushed async, similar to `PurgeEx`.
> [IMPROVED] NRG: remove StreamState usage in n.Applied and n.Size & async flush compacted tombstones 

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/memstore.go
- server/memstore_test.go
- server/monitor.go
- server/norace_1_test.go
- server/opts.go
- server/raft.go
- server/raft_test.go
- server/store.go
- server/store_test.go
- server/stream.go
- Backported commit 12552e06366d0998ccc286b78e83bf6beeb8203f from #7018
- #7100 
- #7107
- #7109
- #7110
- #7111
> Cherry-picks for 2.11.7-RC.2

- server/filestore.go
- server/filestore_test.go
The filestore could contain 3 blocks, had a successful write to the last message block, and wrote a valid `index.db` containing those 3 blocks. If a block was deleted (but was not the last) and the server had an ungraceful shutdown, the removed block was not recognized. This would result in the `index.db` being regarded as valid and loading messages in that block to return `loadBlock error: message block data missing` errors.
This PR fixes that by recognizing certain files don't exist on disk anymore, adds those to the lost data, and rebuilds the index.
> [FIXED] Detect removed blocks with stale index.db

- server/jetstream_batching.go
- server/jetstream_batching_test.go
- server/jetstream_cluster.go
- server/jetstream_test.go
- server/stream.go
Counters already respected the server's `MaxPayload`, but did not yet respect the `MaxMsgSize` as configured on the stream. Also resolved cases where `len(hdr)+len(msg)` could potentially overflow.
> (2.12) Support MaxMsgSize for Counter CRDTs

- server/auth_callout.go
- server/consumer.go
- server/errors.json
- server/events.go
- server/jetstream_api.go
- server/jetstream_cluster_1_test.go
- server/jetstream_errors_generated.go
- server/jetstream_super_cluster_test.go
- server/jetstream_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
- server/stream.go
- server/util.go
See [ADR: JetStream Read-after-Write](https://github.com/nats-io/nats-architecture-and-design/pull/358) for context, problem statement, and design.
Resolves https://github.com/nats-io/nats-server/issues/6557
> (2.12) Read-after-write & monotonic reads

- server/consumer.go
- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/store.go
- server/stream.go
There were a bunch of stream and consumer settings that could be set to invalid values. A few examples include a `MaxBytes` of a large negative number, or stream `Storage` types that don't exist. There are no known cases where these are set wrongly by clients or the CLI, but it's generally better to have the server protect against invalid inputs.
> (2.12) [FIXED] Validate stream/consumer configs

- server/jetstream_api.go
Consumer creates/updates and stream updates would spin up multiple (redundant) goroutines, potentially allowing the system to become overloaded.
`if c.kind != ROUTER && c.kind != GATEWAY` we're already running a goroutine because it will be done by the JS API pool, that uses a `JETSTREAM` client, so it would then open yet another goroutine. Due to this other goroutine we also lose visibility on requests that take a long time, because the `Internal subscription on %q took too long: %v` only gets logged if taking a long time AND we've not spun up a different goroutine to do the actual work that could take time, making this logging ineffective. These additional goroutines could also result in being able to quickly overwhelm the API. Client connections would block and handle these inline …
> (2.12) [IMPROVED] Always handle JS API requests from pool

- .github/workflows/cov.yaml
- .github/workflows/release.yaml
> Update CI dependencies

- .goreleaser.yml
- go.mod
- go.sum
> Update to Go 1.24.6/1.23.12, nats.go v1.44.0

- server/disk_avail_solaris.go
- server/pse/pse_solaris.go
- server/sysmem/mem_solaris.go
This allow NATS Server to build under the illumos.
Signed-off-by: Jiwon Na jwntree@hotmail.com
> Add support for illumos

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
A Limits-based R3 stream can have ephemeral consumers that are R1. Ephemeral consumers don't specify a replica count, instead they specify `Replicas: 0`, to be inferred automatically based on the stream retention and the amount of stream replicas.
Before this PR, `createGroupForConsumer` would check there's at least one online server hosting the stream, but it would still select a peer set (R3 in this example) equal to the stream. After creating the group, it would be "fixed" by doing `rg.Peers = []string{rg.Preferred}` if it's an ephemeral consumer.
In 2.12, due to this fix: https://github.com/nats-io/nats-server/pull/7083, `rg.setPreferred()` will always only select online servers. But on 2.11 and prior, it could randomly select any node, even ones that are offline. Even though this …
> [FIXED] Ephemeral consumers always selects an online server

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster_1_test.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
Remove read-after-write/monotonic reads for 2.12.
> Although the design (read-after-write/monotonic reads/linearizable) gives a lot of control and flexibility, we'll need to decide whether this adds a bunch of complexity which would be (too) hard to understand by an end-user, in which case we might need to revisit this.
https://github.com/nats-io/nats-server/pull/7146#issuecomment-3160570465
The current design is very flexible, but adds a ton of complexity that needs to be handled on a per-request basis. We've discussed whether this should instead be on a per-stream basis. Where on a replicated stream/KV/ObjectStore the reads are serializable by default, but one can opt-in to linearizable for that whole stream. That would mean client code doesn't need to change at all to get this …
> (2.12) Remove Read-after-Write for now

- server/consumer.go
- server/errors.json
- server/jetstream_api.go
- server/jetstream_errors_generated.go
- server/jetstream_versioning.go
- server/jetstream_versioning_test.go
- server/stream.go
As described in the [ADR-44 update](https://github.com/nats-io/nats-architecture-and-design/pull/362), adding support for a `Nats-Required-Api-Level` on all `$JS.API.>` requests. A request will be rejected if the responding server does not support features of that API level.
Resolves https://github.com/nats-io/nats-server/issues/6540
> (2.12) Add required API level in JS requests

- server/client.go
- server/client_test.go
Using [Request-Reply](https://docs.nats.io/nats-concepts/core-nats/reqreply) is very useful.
When using Request with multiple replays, it is difficult to know when the requester loses interest in the replays.
Today, Nats returns an error 503 to the replay subject without any extra information.
Signed-off-by: Ramon Berrutti <ramonberrutti@gmail.com>
> (2.12) [ADD] no responders return the original subject

- server/jetstream_cluster_4_test.go
- server/stream.go
This PR fixes a bug where the `Nats-TTL` header would not be corrected if the TTL got changed based on the `SubjectDeleteMarkerTTL` and `MaxMsgsPer`.
> [FIXED] Correct Nats-TTL header if SDM TTL overrides it

- server/jetstream_cluster.go
- server/jetstream_test.go
- server/stream.go
This allows promoting mirrors by removing the mirror configuration in a stream update.
> (2.12) Allow promoting mirrors

- server/accounts_test.go
https://github.com/nats-io/nats-server/pull/7181 mentioned https://github.com/nats-io/nats-server/pull/5757 introduced a regression as observed by `TestAccountMaxConnectionsDisconnectsNewestFirst`.
However, that bug has been in there since 2.9.0 or earlier, so it can't be attributed to that PR. Both tests are failing all the way to that version. `TestAccountUpdateRemoteServerDisconnectsNewestFirst` was actually fixed since https://github.com/nats-io/nats-server/pull/5757.
> Remove regression note on TestAccountMaxConnectionsDisconnectsNewestFirst

- server/consumer.go
- server/jetstream_test.go
- server/stream.go
Follow-up of https://github.com/nats-io/nats-server/pull/7134 and https://github.com/nats-io/nats-server/pull/7164.
> (2.12) [FIXED] Tune pedantic stream/consumer config validation

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
- server/monitor.go
- server/raft.go
- server/stream.go
This reports how long the leader believes it has been leader in stream & consumer info responses, as well as raftz.
> (2.12) Add `"leader_since"` to stream and consumer info response

- server/jetstream_cluster.go
- server/monitor_test.go
- server/raft.go
- server/stream.go
Similar to https://github.com/nats-io/nats-server/pull/7186, but implementing it for `/jsz`. Due to it being added in `ClusterInfo`, this means a `nats stream info` will also include these details.
> Report cluster traffic account in `jsz`

- server/errors.json
- server/jetstream_batching.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
The `Nats-Expected-Last-Subject-Sequence-Subject` header was added in https://github.com/nats-io/nats-server/pull/5281, but we would not return an error if it was specified without the `Nats-Expected-Last-Subject-Sequence` header.
> (2.12) [IMPROVED] Error on missing Nats-Expected-Last-Subject-Sequence

- server/jwt.go
- server/jwt_test.go
Updated logic to allow scoped users with `IssuerAccount` and empty permissions to bypass immediate validation, with runtime rejection if invalid.
Fix #7137
Signed-off-by: Your Name alberto@synadia.io
> Enhance JWT validation for scoped users

- server/events_test.go
- server/jetstream_cluster_4_test.go
Also fix reported error from `TestJetStreamClusterConsumerReplicasAfterScale`
> Fix TestServerEventsConnectDisconnectForGlobalAcc flaking 

- server/raft.go
The Raft group leader would cache all pending entries in `n.pae`, allowing it to grow infinitely when applies are slower than the proposals themselves. This PR extracts that logic so the leader and follower caching paths are the same, as well as applying the same limits.
> [FIXED] Cache and limit pending entries

- server/client.go
- server/client_test.go
- server/opts.go
Enables showing the headers and/or payload of the message that was routed across multiple hops then delivered (`->>`).
```
cid:5 - <<- [HPUB _INBOX.d3lXYRzwIiKASPZQIMYov4.639bgwnJ 24 33]
cid:5 - <<- MSG_PAYLOAD: ["NATS/1.0\r\nA: 1\r\nB: 2"]
cid:6 - ->> [HMSG _INBOX.d3lXYRzwIiKASPZQIMYov4.639bgwnJ 1 24 33]
cid:6 - ->> MSG_PAYLOAD: ["NATS/1.0\r\nA: 1\r\nB: 2"]
```
> (2.12) Add trace logging for msg delivery

- server/leafnode.go
- server/leafnode_test.go
- server/opts.go
This allows configuring the `isolate_leafnode_interest` item in the `leafnode` configuration block for the leafnode listener. When enabled, interest from leafnodes is not propagated to other isolated leafnodes, suppressing a potential storm of east-west interest when there are many leafnodes connected to an account.
> (2.12) Add `isolate_leafnode_interest` for suppressing east-west leafnode interest propagation

- server/jetstream_cluster.go
On shutdown, server may find the cluster meta node to be nil. If so, return early from the method.
> Fix nil pointer dereference in sendDomainLeaderElectAdvisory

- server/jetstream_cluster_1_test.go
- server/stream.go
Message scheduling can't be disabled once enabled, similar to TTL.
> (2.12) [FIXED] Can't disable message schedules

- server/jetstream_cluster.go
- server/jetstream_cluster_4_test.go
Revert https://github.com/nats-io/nats-server/pull/7071, since it would result in losing consumer state when scaling down a replicated stream and the consumer state would need to be moved, but the current stream leader doesn't host that consumer.
`TestJetStreamClusterConsumerReplicasAfterScale` started flaking due to this bug. `TestJetStreamClusterConsumerReplicasAfterScaleMoveConsumer` has been added in this PR which specifically tests for this situation (the former test would only hit that randomly, hence it flaking).
We'll need to revisit this later when implementing the stream-managed consumers, which isn't going to be for 2.12.
>  (2.12) Revert to meta leader proposing consumer remaps

- server/jetstream_cluster_1_test.go
Test fails as follows:
```
cfg.Replicas = 1
_, err = js.UpdateStream(cfg)
require_NoError(t, err)
checkFor(..., func() error {
if s.JetStreamIsStreamAssigned(globalAccountName, "TEST") {
// some error
}
}
...
require_True(t, mset.closed.Load()) // mset.closed still false
```
This can happen because `js.UpdateStream()` will internally `removeStream()`, which will cause nodes to:
- step down from the Raft group
- remove themeselves from the stream assignment
- mark the stream as stopped
Therefore `JetStreamIsStreamassigned()` may return false *before* the stream is marked as closed.
> Fix TestJetStreamClusterDontReviveRemovedStream

- server/client.go
- server/leafnode.go
- server/leafnode_test.go
The issue can be observed for instance with JetStream and source streams, that would not be populating properly depending on where a server connects to in a given topology. See the new test `TestLeafNodeDaisyChainWithAccountImportExport` for a demonstration of the issue without the fix in place.
> [FIXED] LeafNode: Subject propagation with daisy chain and import/export

- .github/actions/nightly-release/action.yaml
- .github/workflows/cov.yaml
- .github/workflows/long-tests.yaml
- .github/workflows/mqtt-test.yaml
- .github/workflows/release.yaml
- .github/workflows/stale-issues.yaml
- .github/workflows/tests.yaml
- .goreleaser.yml
- go.mod
- go.sum
> Update to Go 1.25.1/1.24.7, dependencies, GHA workflow dependencies

- server/errors.json
- server/jetstream_api.go
- server/jetstream_batching_test.go
- server/jetstream_errors_generated.go
- server/jetstream_events.go
- server/stream.go
Add batch abandoned advisories, for example when the batch timed out or when it was incomplete due to gaps. Also including some general improvements, with a specific error when trying to publish a too large batch, as well as not allowing batching on mirrors.
> (2.12) Atomic batch: advisories & general improvements

- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/stream.go
If a stream was created with `Placement: nil`, but a stream update was performed with `Placement: {}` (empty) then it would trigger a move request. An empty placement object should not be used to trigger a move request, since no (different) placement is specified.
> [FIXED] Empty placement triggers move request

- server/filestore_test.go
- server/test_test.go
These tests verify that writes to readonly files or directories fail when using the filestore. They pass in other environments, but not in Buildkite: `os.Chmod()` sets the mode to readonly, yet the process can still write without error.
> Skip Test*FSModeReadOnly tests in Buildkite

- server/raft_helpers_test.go
- server/raft_test.go
The test proposes a message and expects it to be committed via rg.waitOnTotal(). This was nondeterministic:
- If the leader first received an AppendEntriesResponse from a follower, the proposed message could be committed.
- If the leader first received the AppendEntriesResponse with a higher term (injected by the test), the leader stepped down and the proposed message could not be committed.
The test would sometimes fail depending on the ordering of these events. This fix ensures that the test always follows the second path, where the leader steps down before the proposal can be committed.
> Fix TestNRGNoResetOnAppendEntryResponse

- server/jetstream_test.go
- server/stream.go
Previously this would not work because we would error if a body was provided. Now we only error if field values are provided that don't make sense for the endpoint.
Co-authored-by: Piotr Piotrowski <piotr@synadia.com>
> (2.12) Fix `no_hdr` requests on direct get by last subject endpoint

- server/certidp/ocsp_responder.go
- server/certidp/ocsp_responder_test.go
Like described in issue #7183 , this PR adds the encoding to the base64 encoded certificates.
Resolves #7183 
Signed-off-by: Alexander Zerbe <alex@aqube.de>
> Fix url encoding for ocsp requests

- server/filestore.go
This PR fixes the following filestore bugs:
- `flushPendingMsgsLocked` could, in some cases, hold onto a buffer after returning it to the pool, which could result in corruption
- `flushPendingMsgsLocked` was not making best use of reused buffers as the head of the buffer was left as "dead space" rather than reclaiming it
- `loadMsgsWithLock` would incorrectly report failing to load the cache as though there is corruption
> Filestore fixes

- server/jetstream_test.go
- server/stream.go
When processing a direct get batch (even without NextFor) deleted messages are skipped over. This fixes/extends this so the skipping also happens if the requested sequence number happens to be deleted.
Signed-off-by: Jean-Noël Moyne <jnmoyne@gmail.com>
> Fixes handling a batched direct get request where the starting sequence number requested is deleted

- server/errors.json
- server/jetstream_batching_test.go
- server/jetstream_errors_generated.go
- server/jetstream_events.go
- server/stream.go
Follow-up of https://github.com/nats-io/nats-server/pull/7274, improves the advisory when a batch is too large, and improves the error message to return the defined max batch size.
> (2.12) Atomic batch: improve large batch error and advisory

- server/jetstream_batching_test.go
- server/stream.go
Add support for empty acks, this allows sending the first (or all) messages as requests instead of fire-and-forget publishes. These empty acks can be used for flow control, making sure the remainder of the batch is not wasted if it would just be rejected when the commit comes in, etc.
In general, clients can use this construct when they need more control.
> (2.12) Atomic batch: support empty acks

- .goreleaser.yml
Follow-up to https://github.com/nats-io/nats-server/pull/6359 and https://github.com/nats-io/nats-server/pull/6701
Since 2.11.2 version of goreleaser, it is allowed to set buildhost for RPMs
https://github.com/orgs/goreleaser/discussions/5662
I believe with this all the rpms, debs and tars will be reproducible(the binaries have been reproducible for long time) 
```
```
```
Build Host  : synadia.com
```
Signed-off-by: Alex Bozhenko <alexbozhenko@gmail.com>
> Set build host in goreleaser to have reproducible rpms

- server/filestore.go
- server/filestore_test.go
This PR fixes some of the elastic pointer handling when setting up the write cache.
It also removes the positional/partial write cache and the associated offset altogether. Previously it was possible to create a partial cache for writes with an offset, but this creates a logical race condition between the flusher and whether or not another read happens in the interim. If this happens then the presence of the offset will cause any pending writes to be lost as the cache is considered to be not loaded and therefore is blown away. This creates a consistency issue when async flushes are enabled and can result in corrupted blocks.
It also tweaks the TTL code to satisfy some tests.
> (2.12) Filestore fixes

- server/jetstream_batching_test.go
- server/jetstream_cluster.go
- server/stream.go
Deleting the batch apply state when unsubscribing from the stream resulted in a race condition when shutting down when that batch is actively being applied.
Also implements a fix for a partially applied batch committing properly upon recovery.
> (2.12) Atomic batch: partial batch recovery

- server/jetstream_test.go
- server/stream.go
Empty string gets turned into the default persist mode. Updating the persist mode is currently not allowed.
> (2.12) Default persist mode for empty string

- server/mqtt.go
- server/websocket.go
In PR #1562, the use of `net.Listen` was replaced with a custom `natsListen` that uses a `net.ListenConfig` where `KeepAlive` has been disabled.
The development of MQTT was happening prior to that PR and when MQTT was merged, it had not been changed to use `natsListen`.
The websocket code was done a bit earlier than PR #1562, and it states that it was not changed for websocket, but I am not sure why. Since websocket is still NATS protocol, NATS has its own PING/PONG that should keep the connection alive. So I am changing the websocket code too.
> [CHANGED] Websocket and MQTT: Inhibit TCP Keep Alive

- server/jetstream_batching.go
- server/jetstream_batching_test.go
- server/stream.go
The batch timeout advisory was not sent if the batch timed out and was cleaned up.
> (2.12) [FIXED] Atomic batch: batch timeout advisory

- server/gsl/gsl.go
- server/gsl/gsl_test.go
- server/jetstream_consumer_test.go
- server/sublist.go
- server/sublist_test.go
Similar to https://github.com/nats-io/nats-server/pull/6827, but when combining filter subjects of `stream.A` and `stream.*.A`.
Resolves https://github.com/nats-io/nats-server/issues/7336
> [FIXED] Fix subject tree intersection to match literals when combined with partial wildcards

- server/jetstream_api.go
JS read lock was not held upon calling `jsa.js.checkAllLimits`.
Resolves https://github.com/nats-io/nats-server/issues/7288
> [FIXED] Data race on JetStream reserved limits

- server/jetstream_benchmark_test.go
Folow-up of https://github.com/nats-io/nats-server/pull/7350
> Benchmark JS meta snapshots

- server/jetstream_cluster.go
- server/raft.go
- server/raft_test.go
`mset.resetClusteredState` can be the source of many issues due to race conditions. When something has already gone very wrong with replication then it's a good last effort way to try and get us out of this situation. However, we should never be resetting the whole state as a result of a stream snapshot timing out due to no leader or exceeding retries.
This PR changes this such that we "just" replay the snapshot and allow us to re-send entries into the apply queue afterward. When running under Antithesis this has shown to resolve many health-related issues such as "node skew" where the Raft node for the stream/consumer assignment is different than what is actually being used for the stream/consumer. 
Closely related to https://github.com/nats-io/nats-server/pull/7249, this was very likely …
> NRG: Replay snapshot upon timeout instead of reset

- .github/workflows/release.yaml
- .goreleaser.yml
- go.mod
- go.sum
- server/consumer.go
- server/events.go
- server/filestore.go
- server/filestore_test.go
- server/gsl/gsl.go
- server/gsl/gsl_test.go
- server/jetstream_api.go
- server/jetstream_benchmark_test.go
- server/jetstream_cluster.go
- server/jetstream_cluster_1_test.go
- server/jetstream_consumer_test.go
- server/jetstream_test.go
- server/leafnode.go
- server/log.go
- server/memstore.go
- server/norace_1_test.go
- server/raft.go
- server/raft_test.go
- server/sdm.go
- server/stream.go
- server/sublist.go
- server/sublist_test.go
- server/thw/thw.go
- https://github.com/nats-io/nats-server/pull/7290
- https://github.com/nats-io/nats-server/pull/7295
- https://github.com/nats-io/nats-server/pull/7291
- https://github.com/nats-io/nats-server/pull/7287
- https://github.com/nats-io/nats-server/pull/7299
- https://github.com/nats-io/nats-server/pull/7300
- https://github.com/nats-io/nats-server/pull/7297
- https://github.com/nats-io/nats-server/pull/7303
- https://github.com/nats-io/nats-server/pull/7304
- https://github.com/nats-io/nats-server/pull/7305
- https://github.com/nats-io/nats-server/pull/7309
- https://github.com/nats-io/nats-server/pull/7307
- https://github.com/nats-io/nats-server/pull/7320
- https://github.com/nats-io/nats-server/pull/7337
- https://github.com/nats-io/nats-server/pull/7344
- …
> Cherry-picks for v2.11.10-RC.1

- go.mod
- go.sum
> Update dependency `nats.go` to v1.46.1

- server/filestore.go
- server/filestore_test.go
This should improve the error reporting and reduce more expensive lookup operations when we know that the block is empty.
> Fast-path check for empty block on filestore cache lookup

- server/opts_test.go
- server/server.go
Resolves #7092
This PR introduces a new `NewServerFromConfig()` function that automatically processes configuration files for embedded NATS servers.
When using NATS embedded in Go applications, developers (such as me) often pass the `ConfigFile` field in the `Options` struct, but `NewServer(opts *Options)` doesn't automatically process this configuration file. This leads to confusion and requires additional manual steps to load the configuration.
In pr #7333, a solution was proposed to directly modify `NewServer()`:
```go
func NewServer(opts *Options) (*Server, error) {
if opts.ConfigFile != _EMPTY_ && opts.configDigest == "" {
if err := opts.ProcessConfigFile(opts.ConfigFile); err != nil {
return nil, err
}
}
// ...original code
}
```
However, directly modifying `NewServer()` might raise …
> feat: add NewServerFromConfig function for embedded server config processing

- server/filestore.go
- server/filestore_test.go
This provides better crash-resilience during interrupted filesystem operations, i.e. where writing `meta.inf`/`meta.sum`/`index.db` is interrupted with `O_TRUNC` leaving behind an empty file.
> Always use temporary staging for filestore meta file writes

- server/jetstream_cluster.go
- server/stream.go
Some TODOs were left around while implementing atomic batch that can now be removed.
One important change is that we should never try to revert state based on a failed proposal. It's brittle anyhow as it can only error directly if the server is not Raft leader anymore, but the proposal can still fail anyhow. So, just making it consistent and not rolling back only partially under some conditions, always commit to doing the accounting properly.
> (2.12) Atomic batch: remove TODO comments

- server/config_check_test.go
- server/leafnode.go
- server/leafnode_proxy_test.go
- server/opts.go
- Add proxy configuration to `RemoteLeafOpts` in `server/opts.go`
- Implement HTTP CONNECT tunnel establishment in `server/leafnode.go` 
- Support both authenticated and non-authenticated proxy connections
Enables WebSocket leaf node connections in corporate environments where direct connections are blocked by firewalls, but HTTP proxy access is available.
```conf
leafnodes {
remotes [{
urls: ["ws://remote-server.example.com:443/ws"]
proxy {
url: "http://corporate-proxy.company.com:8080"
username: "proxy_user"
password: "proxy_pass"
timeout: "30s"
}
}]
}
Signed-off-by: Dan Bailey danbailey1000@msn.com
> Add HTTP proxy support for WebSocket leaf node connections

- server/filestore.go
- server/filestore_test.go
If there was a gap in messages in the filestore, and the very last message was an erased message it would not register these as deletes properly. This would then result in a all kinds of issues: constant cache invalidation, slow reads/catchup, and generally the filestore not knowing these messages were deleted.
> [FIXED] Filestore detect delete gap with last SkipMsg

- server/filestore.go
- server/filestore_test.go
Follow-up of https://github.com/nats-io/nats-server/pull/7399, when a block contains multiple `SkipMsgs` and is empty at the start (or fully), then these should not be added as deleted messages to the dmap.
> [FIXED] Filestore don't add deletes for empty block with SkipMsgs

- server/raft.go
- server/raft_test.go
The peer activity timestamp tracking was somewhat inconsistent.
The leader should always be able to reach and report on all peer activities, because it sends heartbeats it will know best when all peers were last seen. Followers only talk to the leader, so they can only track the leader's activity.
However, during leader changes or cluster resizes old active timestamps would remain and would not be updated. This is not an issue per se, but since it's exposed as "last seen" and "active" in various APIs this would look very misleading. A last seen timestamp could show "17 hours ago" and that would feel very problematic "a node hasn't been active for 17 hours!?". But actually that server happened to be a leader 17 hours ago and there's a new leader since, so that timestamp has just not been …
> [IMPROVED] NRG: Peer activity tracking
