nats-io/nats-server

server/server.go

Hello,
Due to [this](http://golang.org/pkg/sync/atomic/#pkg-note-BUG) gnatsd crash on windows with 386 bit architecture as soon as first client connects. Reordering structure fields the way counters are 64bit aligned fixes the issue.
Related to #15 and #14

Sever structure align fix for atomic operations.

---

gnatsd.go

This fixes issue #77, which was caused by the stderr redirect check, due to os.stderr.stat() failing on Windows. 
This is probably the quickest possible fix, happy to expand on it if it's deemed necessary. Figured that handling the possible error from file.stat is not that important anyway as before it was just discarded.

handle stderr stat() throwing an error on Windows

---

server/parser.go
server/route.go
server/split_test.go

When message is split we need to copy message arguments to avoid
rewriting them with new message. Subject, reply and size were correctly
copied by sid wasn't. That led to dropping some messages in clustered
mode if they were split, and the second part was long enough to overwrite
sid in the original buffer.

Fix sid for split messages

---

server/monitor.go
server/monitor_sort_opts.go
server/monitor_test.go

Implements option to sort connz in the server side so that queries to the monitor server like `?limit=1&sort=msgs_from`, return the client from which the server has processed the most messages, rather than what happened to be the first one from the unordered set. /cc @derekcollison

Add query parameter to sort connz by the monitor server 

---

README.md

Add to the example that it is possible to get the subscriptions from a connection when using query like `http://localhost:8222/connz?subs=1`
cc/ @derekcollison

Add subscriptions_list example to readme

---

README.md

Just added the remaining client implementations listed on NATS.io website to README.

Added remaining clients implementations to README.md

---

sublist/sublist.go
sublist/sublist_test.go

Could be the reason why messages would sometimes get delivered to the
wrong subscription, as matching would not differentiatie between
'foo.bar' and 'foo.bars'.

Fix off-by-one in matchLiteral

---

README.md
server/monitor.go
server/monitor_test.go

Add JSONP support for monitoring routes

---

server/client.go
server/parser.go
server/parser_test.go
server/split_test.go

Make sure we do the right thing when no args are presented for an MSG, e.g. MSG <spc>.
Also do not parse at all of this is a client, only valid for routes.
/cc @kozlovic @wallyqs

Fix parser bug around MSG protocol.

---

server/pse_freebsd.go

This file is required to build against FreeBSD.
Tested on FreeBSD 10.1, Go versions 1.4.2 and 1.5.

Compile cleanly on FreeBSD, using the Windows approach to `procUsage`

---

test/maxpayload_test.go

Adds logic to test which mimics previous behavior of client. This fixes the last build error which was reported by travis: https://travis-ci.org/nats-io/gnatsd/builds/79524831
@levb @derekcollison @kozlovic

Update max payload test to reflect behavior change in go client.

---

server/monitor.go
server/monitor_test.go

Clients can optionally set a name label on `CONNECT`.  This just exposes the name set by the client so that it can be polled from the `/connz` endpoint.
```
curl http://127.0.0.1:8222/connz
{
"now": "2015-11-01T17:57:12.340117801-08:00",
"num_connections": 1,
"offset": 0,
"limit": 1024,
"connections": [
{
"cid": 2,
"ip": "127.0.0.1",
"port": 53528,
"pending_bytes": 0,
"in_msgs": 0,
"out_msgs": 0,
"in_bytes": 0,
"out_bytes": 0,
"subscriptions": 0,
"name": "sample"
}
]
}
```

Expose name label from client in connz

---

server/pse_solaris.go

Please review, it's only basic (same as freebsd) so to be able to compile on illumos and run on illumos.

Added basic support for illumos/Solaris

---

server/client.go
server/route.go

Fix for #138.
If processRoute executes before createRoute finishes registering the route, and before a subscriber has connected (or reconnected), and the subscriber connects (or reconnects) before the route is registered, then this subscription will stay local and not be forwarded to the route.
@derekcollison @olegshaldybin : Oleg, I think that this is the root cause for the un-explained timeouts on Bagel that only a restart of the component would solve.

Fix possible non-propagation of subscription interest to routed server.

---

server/client.go
server/client_test.go
test/proto_test.go

* There was a race during unsubscribe()
* 'go test -race' reports a race in TestSetLogger test. This one could be ignored since we normally invoke SetLogger only on server startup. That being said, Travis failed when I tried to submit a PR for the fix of the unsubscribe race. So proposing to fix the logger too.

Fix races, add a test and adjust others.

---

README.md
server/opts.go

We make sure to require client certs and verify them when connecting routes.

TLS strict route verifications

---

server/parser.go
test/proto_test.go

Found a corner case when a client can send corrupted PUB payloads and cause the server to panic.  Added a patch to detect this case disconnecting the client with protocol error to avoid server crashing.
/cc @derekcollison @kozlovic
```
panic: runtime error: makeslice: cap out of range
goroutine 51 [running]:
github.com/nats-io/gnatsd/server.(*client).parse(0xc208ffe000, 0xc208a28000, 0x8000, 0x8000, 0x0, 0x0)
/home/vagrant/go/src/github.com/nats-io/gnatsd/server/parser.go:634 +0x2c6
github.com/nats-io/gnatsd/server.(*client).readLoop(0xc208ffe000)
/home/vagrant/go/src/github.com/nats-io/gnatsd/server/client.go:156 +0x1b9
created by github.com/nats-io/gnatsd/server.(*client).initClient
/home/vagrant/go/src/github.com/nats-io/gnatsd/server/client.go:133 +0x5fc
goroutine 1 [IO wait]: …
```

Avoid `cap out of range` error when handling split buffer

---

gnatsd.go
server/opts.go

This allows to set cluster addr and port as a url in the command line, would be useful to be able to set via flag in some scenarios.

Add --cluster_listen flag to set cluster addr and port

---

.travis.yml
TODO.md
auth/plain.go
auth/token.go
server/client.go
server/monitor.go
test/auth_test.go
test/gosrv_test.go
test/routes_test.go
travis/coveralls-script.sh
util/mkpasswd.go

This adds support for bcrypt hashes instead of passwords or tokens in configurations. Also added a utility to generate strong passwords/tokens and the associated bcrypt hash which can be used in the config files.
/cc @philpennock @eftychis

Bcrypt Support

---

server/parser.go
server/parser_test.go

This fixes behavior for showing protocol parsing errors in the logs.  Included a test to clarify the behavior of the function too. Fixes https://github.com/nats-io/gnatsd/issues/154
/cc @kozlovic

Fix and add tests for proto snippet func for showing protocol parsing errors

---

test/client_cluster_test.go

* There was a bug in the send loop (use of 1 instead of i)
* On Windows specifically, the test did not exit without explicit closing of the connections (I don't think we should have to do that). This behavior combined with the send loop bug would cause this test to consume all memory on the machine.
cc @ColinSullivan1

Fix test that was failing on Windows.

---

server/configs/tls.conf
server/configs/tls_bad_cipher.conf
server/configs/tls_ciphers.conf
server/configs/tls_empty_cipher.conf
server/opts_test.go
test/configs/srv_a_tls.conf
test/configs/srv_b_tls.conf
test/configs/tls.conf
test/configs/tlsverify.conf
test/test.go
test/tls_test.go

We would get failures on Travis, I would think because of small TLS timeout. Increase (or set) the TLS timeout to 2 seconds in most configuration files. Update tests that relied on the original value.

Increase TLS timeout in config files

---

server/server.go
server/server_test.go
test/test.go

* Add server.GetListenEndpoint() to return options' host and port when server is ready to accept client connections. The server can be asked to pick a random port. This function returns a string of the form "host:port" with the port selected by the net.Listen() call.
* Replace the use of server.Addr() with above function to connect to the starting server (using net.Dial) to check for success. The original issue was that, when no hostname is specified in the configuration, the server uses 0.0.0.0 for the listen address. However, server.Addr() would return "[::]", even on a machine with IPv6 disabled, which would cause the net.Dial call to fail with "network unreachable".

Adapt tests for Travis GCE.

---

server/usage.go

- Added `Usage: gnatsd [options]` at the top
- `--auth` wasn't included in the usage menu, so added it.
- A couple of the options didn't indicate whether an argument was `<required>` or `[optional]`, so I fixed that.
- Capitalization was not uniform throughout, so fixed that. Other than acronyms and proper nouns, only the first letter is capitalized in descriptions.

Add 'auth' option, make all usage hints uniform with conventions

---

server/monitor_test.go
server/server_test.go
test/routes_test.go
test/test.go

- The raw connection used to check that the server is started now consumes the INFO and sends PING and consumes PONG before returning.
- The route test needs to make sure that the client connection has client id 2. Using PING/PONG before creating route connection to make sure of that.

Fix code that checks that server is started + route test

---

server/parser.go
server/parser_test.go

Noticed that currently parser is tolerant to not having spaces after `unsub`, for example:
```
telnet demo.nats.io 4222
INFO ...
unsub_hello_world 90
+OK
```
This change adds a new state to the parser in case we want to handle this and sends `-ERR 'Unknown Protocol Operation'` to clients sending `unsub` commands which are not following the protocol then disconnect due to parser error.

Add UNSUB_SPC parser state

---

gnatsd.go

Super small fix I've found today upgrading, golint popped me a couple of details to fix.
```
$ golint .
gnatsd.go:25:6: var showTlsHelp should be showTLSHelp
gnatsd.go:213:2: var clusterUrl should be clusterURL
```

Fixed "golint ." issues

---

server/monitor.go
server/monitor_test.go

- Updating TestConnzWithOffsetAndLimit() to test for c.NumConns. This would have caught the issue that was fixed in my previous change.
- Use of variable sortValue set to pair.Val to help readability. No functional change.

Update test that would catch incorrect NumConns

---

server/client.go
server/route.go
test/routes_test.go

Attempt to address issue #175.
Instead of trying to detect if route URL will point to route listen address, detects that the route remoteID is server's ID. If so, closes the connection and stop trying.

Fix infinite server attempt to connect route to itself

---

server/route.go
test/route_discovery_test.go

This helps in case where the original host in the route URL can resolve to different IPs or has different meaning depending on which host it is running. Returning the real IP should solve some issues.

Return route's remote IP through INFO protocol

---

server/monitor.go
test/configs/tls.conf
test/monitor_test.go

Currently they become the zero values if TLS is being used:
```js
{
"now": "2016-02-14T19:12:39.523426391-08:00",
"num_connections": 1,
"offset": 0,
"limit": 1024,
"connections": [
{
"cid": 1,
"ip": "",
"port": 0,
...
"tls_version": "1.2",
"tls_cipher_suite": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
}
]
}
```

Set IP and Port for monitoring connections using TLS in /connz

---

server/configs/srv_a_bcrypt.conf
server/configs/srv_b_bcrypt.conf

The ports were conflicting with the 'test' package when running the test suite in parallel (go test -race -v ./...)

Fix ports for cluster bcrypt auth config files in server package

---

server/client.go
server/configs/seed.conf
server/configs/seed_tls.conf
server/route.go
server/routes_test.go
server/server.go
test/client_cluster_test.go
test/cluster_test.go
test/cluster_tls_test.go
test/route_discovery_test.go
test/routes_test.go

Both seed and chained cases are now handled properly when servers
connect quickly and concurrently to one another.
When accepting a route, the server will forward the new route INFO
protocol to its known routes. In turn those routes will connect
to the new server (if not already connected).
A retry for implicit route was introduced to mitigate the issue
with two servers connecting to each other and electing the opposite
connection as the winner, resulting in both connections being dropped.
The server with smaller ID will try once to reconnect.
Some tests were fixed to handle possible extra INFO protocol.
New tests added.
Fix issue: https://github.com/nats-io/gnatsd/issues/206

Fix cluster formation when servers connect quickly

---

server/monitor_test.go
server/pse_test.go
server/route.go
server/server.go
test/client_cluster_test.go
test/cluster_test.go
test/maxpayload_test.go
test/routes_test.go
test/tls_test.go

Mainly tests, but also a fix in route.go to reject a route when the server is being shutdown.

Fixed code and tests to run on Windows

---

server/client.go
server/parser_test.go
test/ping_test.go

- The number of outstanding PINGs is now reset whenever the server
receives a PONG from the client.
- Updated parser test to check c.pout.
- Added a test to check for unprompted PONGs.
Resolves issue: https://github.com/nats-io/gnatsd/issues/168

Fixed handling of unprompted PONG protocols

---

TODO.md
server/client.go
server/split_test.go
server/sublist.go
server/sublist_test.go
test/client_cluster_test.go

Reworked sublist to sort out normal subscribers from queue subscribers into
a result set that can be cached and easily iterated over.

Queue subscriber performance

---

server/client.go

This removes an potentially unneeded allocation when processing messages. Previous to this change, the processMsg function always converted the subject from a []byte to a string, thus allocating, and used it to lookup or set a cache entry.
By moving the conversion for the cache lookup into the map access, we can use an optimization introduced in Go 1.3 that avoids allocating the string for the map lookup.
In case where we insert into the cache we still need to allocate, because we need a string for the Match function and also because setting the map key still needs to allocate, if the key isn't already in the map (if I remember correctly).
These are the results from the publish benchmarks from github.com/nats-io/nats/test:
```
benchmark                          old ns/op     new ns/op …
```

Remove an unnecessary string allocation

---

server/sublist.go

The Insert function on \*Sublist converts the subject of the given subscription to a string.
Before this change, the conversion was done in 2 steps:
1. Appending the subject to a nil byte-slice, causing a new byte slice to be allocated.
2. Converting the new byte-slice to a string.
This is done so that the code doesn't (potentially) hold on to the original byte-slice, which might be a part of a larger slice (thus preventing it from being deallocated).
But step 1 is unnecessary, as step 2 always allocates a new string with the exact length and capacity needed.
This change removes step 1 an relies on step 2 only.
Benchmark results:
```
name                                    old time/op    new time/op    delta
______________________SublistInsert-4      971ns ± 0%     766ns ± 4%   ~ …
```

Remove allocation when inserting into sublist

---

TODO.md
gnatsd.go
server/client.go
server/client_test.go
server/const.go
server/opts.go
server/opts_test.go
server/route.go
server/server.go

This allows outbound buffers to clients to dynamically resize. Helps memory footprint with lots of connections and pairs with the read buffer work.
/cc @kozlovic

Dynamic writes

---

server/pse_windows.go
server/pse_windows_test.go

Use the built-in typeperf.exe utility on windows to query performance counters and obtain equivalent data as that from the pcpu, rss and vsz flags in ps.  There are alternatives, but those require installing additional third party tools or mapping native windows APIs into GO.

Windows procUsage implementation and test

---

server/client.go
server/route.go
server/server.go
test/cluster_test.go
test/cluster_tls_test.go

We need to make sure that when Shutdown() returns, routes go routines
that try to connect or reconnect have returned. Otherwise, this may
affect tests running one after the other (a server from one test
may connect to a server in the next test).
/cc @derekcollison

Ensure Shutdown() waits for outstanding go routines

---

server/client.go
server/server.go
test/routes_test.go

When processing a connect request, there was a risk of race condition
when the server was being shutdown. Capture fields that are checked
under lock and lock when setting the route's remote ID.
Resolves #255

Fix data race

---

server/monitor.go
server/monitor_test.go
test/monitor_test.go

Adds a new field, `total_live` to the `/connz` generated json, representing the number of live connections at the moment.

Add a live connection count to connz monitoring.

---

server/monitor_test.go

Check that Total is representative of the real number of connections as opposed to what Connz returns when using limits and offsets.

Add test for Connz Total connections

---

server/monitor_test.go

Introduce sleep when checking activity updates. I had fixed it
originally for Windows and then made it for all platform recently
but only for the publish case. I missed the subscribe test.

Fix flapping test

---

server/pse/pse_windows_test.go

While locally tested before committing, this test was inadvertently being skipped in the suite.
* Use the proper build flag
* Call ProcUsage (versus procUsage), as test has been moved.

Update the Windows PSE Test

---

server/pse/pse_windows.go
server/pse/pse_windows_test.go

Performance improvements for process usage statistics on windows
* Call into the performance counter API directly, rather than using the typeperf tool
* Incorporate caching to reduce load on the server

Update PSE for Windows

---

server/parser.go
server/split_test.go

In split buffer conditions, a buffer is used to accumulate bytes.
After processing, this buffer needs to be reset.
/cc @derekcollison 
Resolves #270

Fix INFO_ARG parsing

---

server/route.go

Hi there, 
We got the following trace today testing nats 8.
```
goroutine 59 [running]:
runtime.throw(0x947620, 0x21)
/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8200f3710 sp=0xc8200f36f8
runtime.mapaccess2_faststr(0x792fc0, 0xc8203149f0, 0xc82050c57b, 0x3, 0x3, 0x3)
/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8200f3770 sp=0xc8200f3710
github.com/nats-io/gnatsd/server.(*Server).routeSidQueueSubscriber(0xc82009d200, 0xc82050c573, 0xb, 0x3a8d, 0xc820245180, 0x39)
/go/src/github.com/nats-io/gnatsd/server/route.go:426 +0x2a6 fp=0xc8200f3838 sp=0xc8200f3770
github.com/nats-io/gnatsd/server.(*client).processMsg(0xc8200aed00, 0xc82050c584, 0x25a, 0x3a7c)
/go/src/github.com/nats-io/gnatsd/server/client.go:848 +0x5b2 fp=0xc8200f3ad0 sp=0xc8200f3838 …
```

Concurrent map access in server/route.go

---

conf/lex.go
conf/lex_test.go
conf/parse.go
conf/parse_test.go

PR to land first pass at configuration language supporting variable references. These will be block scoped from the parse state and can also come from the environment variables as well.

Configuration Variables

---

server/client.go
server/client_test.go
server/route.go

Ensure that all socket writes are protected with deadlines.
For connection Close(), also use deadlines since in case of TLS,
the Close() will send an alert (do a write) if the handshake was
completed. If the peer is not reading, this would cause the Close()
to hang.

Fix possible blocking on sock write or connection close (when using TLS)

---

server/monitor.go
server/monitor_test.go
server/server.go

Allows to get the server's stacks from the monitoring interface.

Add /stacksz to monitoring

---

server/client.go

This commit has 3 changes:
- Remove duplicate logic for creating cache results map.
- Move code out of an if that will always be true and remove the if.
- Use == 0 instead of <= 0 for comparing the return value of len(X) as the value can never be < 0.

Simplify processMsg

---

server/pse/pse_rumprun.go

This is a stub to allow nats to run as a rumprun unikernel.

rumprun unikernel support

---

TODO.md
server/client.go
server/client_test.go
server/errors.go
server/route.go
server/server.go
server/server_test.go
test/routes_test.go
test/test.go

Clients that will be at the ClientProtoInfo protocol level (or above)
will now receive an asynchronous INFO protocol when the server
they connect to adds a *new* route. This means that when the cluster
adds a new server, all clients in the cluster should now be notified
of this new addition.

[ADDED] Server sends INFO with cluster URLs to clients with support

---

server/parser.go
server/parser_test.go
server/split_test.go
test/bench_test.go

Similar improvement that we got in the client's parser.
The PR includes benchmarks for routes. Here would be the results with/without the changes.
```
Original:
Benchmark_RoutePubSub_NoPayload-8	 3000000	       590 ns/op
Benchmark_RoutePubSub_1K-8       	  500000	      3119 ns/op
Benchmark_RoutePubSub_100K-8     	   10000	    128411 ns/op
Change in parser:
Benchmark_RoutePubSub_NoPayload-8	 3000000	       584 ns/op
Benchmark_RoutePubSub_1K-8       	 1000000	      1181 ns/op (2.64x faster)
Benchmark_RoutePubSub_100K-8     	   20000	     76809 ns/op (1.67x faster)
```
/cc @derekcollison

[IMPROVED] Route performance for larger messages

---

main.go
server/opts.go
server/opts_test.go

If the server was started with a cluster section in a configuration
file and one would want to override the routes (using `-routes`) the
server would complain that you need to use `-cluster`. Adding
an override of cluster would not work, server would still complain.
Trying to override simply the cluster listen info (without override
of routes) would also not work.

[FIXED] Route/Cluster override

---

server/server.go
server/server_test.go

The server was returning all resolved IP addresses, including link
local addresses, which did not make sense for remote clients.
Note that if server listens to localhost, it still returns that so that clusters running on single host (most likely test) will work. To avoid servers to advertise `localhost` as an URL you should start the server with a global IP address instead.
Resolves #321

[FIXED] When server listens to any interface, return only global IPs

---

server/route.go
server/routes_test.go
server/server.go
server/server_test.go

Trying to use IPv6 address for the cluster host would fail.
Also, there were some unclosed channels in case of accept loop
setup failures.
Resolves #323

[FIXED] Cluster's listener with IPv6

---

main.go
server/opts.go
server/opts_test.go
server/route.go
server/server.go
test/routes_test.go

By default, a server is now sending to its clients the client URLs
of all servers in the cluster. This allows clients to be able
to reconnect to any server in the cluster even if those clients
were not configured with the list of servers in the cluster.
However, there may be cases where it would make sense to disable
this feature. This now can be done with this option/command line
parameter.
Resolves #322

[ADDED] Option to not advertise to clients cluster's IPs

---

server/server.go
server/server_test.go

We saw a case where a Windows VM would return 0.0.0.0 in the INFO
protocol. After debugging, it appeared that the VM had an issue
and a reboot solved it, but while in bad mode, the resolution of
the IP address would not return an error, but nothing was added
to the array and we ended-up adding at the last resort the 0.0.0.0
IP. This is a problem for Windows clients since they can't use
that IP to connect. In that situation, the server will now log an error
message and not return a client connect URL, which is fine.

Check that 0.0.0.0 or [::] is not returned as a client connect URL

---

server/opts.go
server/opts_test.go

Enables using the same listen from server as was specified via `--addr`, for the monitoring server:
```sh
$ gnatsd -a 127.0.0.1 -p 4222 -m 8222 --cluster nats://127.0.1.1:6222 --routes nats://127.0.0.1:6222,nats://127.0.1.2:6222
[22861] 2016/08/17 22:54:58.080511 [INF] Starting nats-server version 0.9.2
[22861] 2016/08/17 22:54:58.080594 [INF] Starting http monitor on 127.0.0.1:8222
[22861] 2016/08/17 22:54:58.080703 [INF] Listening for client connections on 127.0.0.1:4222
[22861] 2016/08/17 22:54:58.080739 [INF] Server is ready
[22861] 2016/08/17 22:54:58.080918 [INF] Listening for route connections on 127.0.1.1:6222
^C[22861] 2016/08/17 22:55:01.973635 [INF] Server Exiting..
$ gnatsd -p 4222 -m 8222 --cluster nats://127.0.1.1:6222 --routes nats://127.0.0.1:6222,nats://127.0.1.2:6222 …
```

Enables using the same listen from server for monitoring endpoint via `-a`

---

server/opts.go
server/server.go
test/configs/tlsverify_noca.conf
test/tls_test.go

When `verify` was set to true in the configuration, the 
server was requiring a client certificate, but unfortunately
not verifying it.
Resolves #336

[FIXED] Client certificate verification when `verify` is true.

---

server/monitor.go
server/monitor_test.go

Fixes #304 
Changes the non-ASCII curly quotes in the HTML to use the regular ASCII double quotes. Also adds a test to check for the existence of non-ASCII characters in that same HTML.

Fix non-ASCII quotes in HTML

---

server/log.go
server/log_test.go

In NATS Streaming, we have a test - started early on - that was testing
logging and called SetLogger(l, true, true), then reset by calling
SetLogger(l, false, false) to reset the values. That obviously had not
the expected effect.
During profiling, I noticed that there were tons of allocated
objects due to NATS server debug/trace statements caused by that.

[FIXED] SetLogger to be able to set debug/trace to 0

---

logger/syslog.go
logger/syslog_test.go

When running multiple NATS servers on a machine and directing output to syslog, we need a way to differentiate the servers beyond process ID.  One way to do this is to use the link or executable name used to launch the process.  Users can then identify individual servers in the syslog output if they link to, or copy the NATS server.  Current behavior will be maintained when using the default NATS server executable.
Given files `gnatsd`, a copy of `gnatsd` (`gnatsd.1`) and a link `gnatsd-link`:
```
-rwxr-xr-x  1 colinsullivan  staff  9084636 Oct 18 11:35 gnatsd
lrwxr-xr-x  1 colinsullivan  staff       10 Oct 18 11:38 gnatsd-link -> ./gnatsd
-rwxr-xr-x  1 colinsullivan  staff  9084636 Oct 18 11:36 gnatsd.1
```
The NATS server will generate syslog statements based on the link or executable …

Generate syslog tags based on the name of the executable or link.

---

.travis.yml
server/route.go
server/server.go
util/tls.go

Running `go vet ./...` with `go 1.7.3` would report the following:
```
server/route.go:342: assignment copies lock value to tlsConfig: crypto/tls.Config contains sync.Once contains sync.Mutex
server/server.go:479: assignment copies lock value to config: crypto/tls.Config contains sync.Once contains sync.Mutex
```
Add a “clone” function while waiting for this to be addressed
by the language itself (https://go-review.googlesource.com/#/c/28075/)

[FIXED] assignment copies lock value for crypto/tls.Config

---

util/tls.go
util/tls_pre17.go

Use build directives to solve the problem of new fields in tls.Config
in go 1.7
Related to #231

Use 2 files for CloneTLSConfig instead of reflection

---

server/server.go
server/signal.go
server/signal_windows.go

Windows has limited support for signals, and does not define `syscall.SIGUSR1`.  Log rotation will be handled differently in windows.
* Add signal.go for all non-windows builds
* Add signal_windows.go for windows builds.
Today, windows looks to be the only platform that does not have `syscall.SIGUSR1` defined.
Resolves #381

Differentiate signal handling for windows

---

server/const.go
server/opts.go
server/opts_test.go

Previous implementations of the server checked the pending data size being currently buffered for a client to detect slow consumers, though this does not apply to latest version of the server, so removing
it as a config option for now to avoid confusion since not implemented.

Remove "max_pending_size" option

---

server/client.go
server/errors.go
server/server.go
server/server_test.go

The max_connections config parameter was accepted but the server
would not check this limit when processing client connections.
Resolves #386

[FIXED] Honor max_connections setting

---

server/client.go

Since we now return an error before setting up the client's readLoop,
testing for this error in readLoop in not needed.

Remove non needed test for ErrTooManyConnections in client's readLoop

---

main.go
server/server.go
server/server_test.go

Currently we allow `version` and `help` as subcommands and ignoring others, though this conflicts with command line options as it ignores the rest of the options and uses default parameters. Instead now we change to bail on unrecognized command to prevent misconfigurations which may arise from this.
Examples which now show usage of the binary instead:
```
gnatsd -p 4223 foo 
gnatsd foo -p 4223
gnatsd bar
```
Subcommands allowed are only `version` and `help`:
```
gnatsd version -p 4223 -DV
nats-server version 0.9.5
gnatsd help
```
Using only option flags works as they were previously
```
gnatsd -p 4223 -DV
[10452] 2016/12/01 14:48:27.641548 [INF] Starting nats-server version 0.9.5
[10452] 2016/12/01 14:48:27.641630 [DBG] Go build version go1.7
[10452] 2016/12/01 14:48:27.641635 [INF] …
```

Prevent unrecognized sub commands in cmd line

---

.travis.yml
staticcheck.ignore

PR #398 used strict equality for `1.7` which would fail. Use lexicographical order instead (will potentially work even if we were to upgrade to `1.8` later and forget about changing this line).
Also exclude the `vendor` directory from a bunch of `go` commands.
Resolves #399

Fixed Travis check for 1.7 and some cleanup

---

server/route.go
server/routes_test.go
server/server.go
server/server_test.go
test/routes_test.go
test/test.go

The RunServer() function (and the various variants)
call Server.Start() in a go-routine, but do not return until
it has verified that the server is ready to accept connections.
To do so, it use GetListenEndpoint() to get a suitable connect
address (replacing "0.0.0.0" or "::" with localhost - important
on Windows). It then creates a raw TCP connection to ensure the
server is started, repeating the process in case of failure up
to 10 seconds.
This PR replaces this with a function that checks that client
listener, and route listener if configured, are set. This removes
the need to get a connect address and create test tcp connections.
The reason for this change is that NATS Streaming when starting
the NATS Server (unless configured to connect to a remote one)
calls RunServerWithAuth(), …

Replace GetListenEndpoint() with ReadyForConnections()

---

server/auth.go
server/client.go
server/client_test.go

It makes it possible to implement a Auth that uses client TLS certificates
to identify them.

Add TLS infos to ClientAuth interface

---

logger/syslog_windows.go
logger/syslog_windows_test.go
main.go
vendor/manifest

Currently, the windows sys logger is a stub for standard logging.  This PR implements windows event logging as the “syslog" for the NATS server on windows.
Using the `-s` or `-r` parameters on windows will enable logging to the windows event log.
- The event source is `NATS-Server`, and data is written to the `Application` log.
- Writing to the event log requires an elevated privilege.  If the user does not have required privileges, the server panics.
- Log messages are written to the Application event log in the following format: `pid[<pid>]:[<type>]: Message`
- `Notice`, `Trace`, and `Debug` messages are written as info messages and `Errorf` or `Fatalf` log messages are logged as event log errors.
- Remote logging is supported.
- Includes tests and vendoring
Here is what a NATS server …

Implement windows event logging

---

.travis.yml

Doing code coverage/cross compile for a single Go release. As of now,
if we were to introduce Go 1.8 in the matrix, we would do code
coverage (which may be ok) and create release (which would not be
ok) for 2 Go releases since were were using >= comparison.
This change ensures that we do for only 1.7.x for now.

Change coverage/cross compile trigger for travis.yml

---

test/test.go

* Windows and very stressed test machines may require more time to connect; this was causing flappers.

Increase the internal test client dial timeout

---

server/client.go
server/configs/test.conf
server/opts.go
server/opts_test.go
server/server_test.go

We use a hardcoded value of 2 seconds for Write deadline when
writing data to client's socket.
This PR makes that value configurable.
Question is should we push the setting down to the client's object
to avoid indirection such as client.srv.opts.WriteDeadline?

[ADDED] Make Write deadline configurable

---

.travis.yml
main.go
server/opts_test.go
test/pid_test.go
test/tls_test.go

Staticcheck has probably been updated and is finding new errors.
They have been fixed.
Also, moved the run of staticcheck before running the test suite,
so if it fails, it fails sooner ;-).

Fixed errors found by staticcheck

---

.travis.yml
server/server_test.go
server/sublist.go

- Get gosimple package
- Updated staticcheck's URL
- Moved build and above checks in `before_script` section to fail fast
- Fixed reports from gosimple

Added gosimple

---

server/client.go
server/client_test.go
server/errors.go
server/routes_test.go

This happens sometimes, and the latest occurence was today:
https://github.com/nats-io/java-nats/issues/96
When it happens, there is no error but subscribers would not receive
anything, etc...
This PR uses the fact that clients set the field Lang in the CONNECT
protocol that ROUTEs do not. I have checked that all Apcera supported
clients do set Lang in the CONNECT protocol.
If we plan to add Lang for routes, we need to find another field or
use a new one, in which case that would work only for new clients
(that would need to be updated).
With this change, when the server accepts a connection on the route
port and detects that this protocol field is present, it now closes
the client connection.
The nice thing is that newer clients, when incorrectly connecting
to the route port, get from …

[ADDED] Reject clients connecting to route's listen port

---

main.go

Removed `os.Exit()` from function assigned to `flag.Usage`.

Fix staticcheck report

---

.travis.yml
test/tls_test.go

Go 1.8 has been released, move from go 1.8beta2 to the current 1.8 release.
* Go 1.8 uncovered a staticcheck violation; the fix is included here.

Update Travis to use Go 1.8

---

server/monitor.go
server/sublist.go
test/monitor_test.go

* Includes a unit test that checks all endpoints for data races.

Use atomic.Load to access fields used in /varz and /subsz requests.

---

.travis.yml
scripts/cov.sh
server/client.go
test/ping_test.go

Resolves #458
- Removed unnecessary cast check to (*net.TCPConn). When the timer
fires, the connection is already established. Replaced with check
that connection has not been closed.
- Add PING test that checks that pings are sent to TLS connections.
- Changed Go version to 1.7.5 in travis.
- Removed test package from code coverage.

[FIXED] Server not sending PINGs to TLS connections (clients or routes)

---

server/monitor.go
server/opts.go
server/sublist.go

Found the couple nits while running `gometalinter` on the repo
- [N/A] Documentation added (if applicable)
- [N/A] Tests added
- Remove unused `usage` type
- Fix unnecessary conversions

Fixes to a couple of `gometalinter` checks

---

README.md
server/opts.go
server/opts_test.go
test/client_auth_test.go

Resolves #464
So far, it was only possible to use token from the command line.
- Add support for `token` in the `authorization` configuration section.

[ADDED] Support for token in configuration file

---

scripts/cross_compile.sh

Resolves # 470
We are using the tool from https://github.com/mitchellh/gox
for cross compilation. When we issue a new release, we create a
tag and trigger Travis build which will then invoke the script and
upload the files to GH.
We were affected by https://github.com/mitchellh/gox/issues/55
Invoking the script on a Linux amd64 would produce this:
file pkg/gnatsd-linux-amd64/gnatsd
pkg/gnatsd-linux-amd64/gnatsd: ELF 64-bit LSB executable, x86-64,
version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
With the fix, you'll get this:
file pkg/gnatsd-linux-amd64/gnatsd
pkg/gnatsd-linux-amd64/gnatsd: ELF 64-bit LSB executable, x86-64,
version 1 (SYSV), statically linked, stripped

[FIXED] Release on linux amd64 is the only one dynamically linked

---

scripts/cov.sh

Since `auth` package was removed, this would cause the script coverage to fail with error:
```
can't load package: package github.com/nats-io/gnatsd/auth: cannot find package "github.com/nats-io/gnatsd/auth" in any of:
/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/github.com/nats-io/gnatsd/auth (from $GOROOT)
/home/travis/gopath/src/github.com/nats-io/gnatsd/auth (from $GOPATH)
```

Fix code coverage script (remove auth package that no longer exists)

---

conf/lex.go
conf/lex_test.go

This involves evaluating and interpolating \-escaped sequences
in double-quoted and undelimited strings.
Added tests on various edge-conditions, as well as ruling out bare
strings like '\true' as a bool.
- [x ] Resolves #477 
- [x ] Documentation added (if applicable): n/a
- [x ] Tests added- for all edge cases of combinations of escaped and unescaped substrings, 
Also tests for 
- x[ ] Branch rebased on top of current master (`git pull --rebase origin master`)
- [x ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)) (url => 404)
- [ x] You have certified that the contribution is your original work and that you license the work to the project under the [MIT …

Issue 477: Improve handling of escaped substrings

---

server/monitor_test.go
server/pse/pse_darwin.go
server/server.go

Resolves #480
- Add `Server.HTTPHandler()` function that returns the http handler used by the server after it is started and if it has been configured for monitoring.
- Add test to make sure that HTTP handler is correctly returned
- Fix unrelated staticcheck report

[ADDED] Ability to get the server's HTTP Handler

---

server/configs/test.conf
server/opts.go
server/opts_test.go

Resolves #487
Changing from being the number of seconds to a time.Duration.
For backward compatibility, the configuration with the number
of seconds is still accepted but an error message is printed
asking the user to convert to duration.
/cc @nats-io/core @petemiron

Changed write_deadline configuration type

---

server/route.go
test/routes_test.go

Base on [`func (s *Server) routeSidQueueSubscriber(rsid []byte) (*subscription, bool)`](https://github.com/nats-io/gnatsd/blob/master/server/route.go#L458) `rsid` comes from [`func routeSid(sub *subscription) string`](https://github.com/nats-io/gnatsd/blob/master/server/route.go#L486), I think we can replace `regexp.FindSubmatch` with a simple function.
The Benchmark result:
```
go test -bench=. -benchmem
BenchmarkRegexp-4   	 1000000	      1124 ns/op	     144 B/op	       2 allocs/op
BenchmarkParse-4    	50000000	        26.2 ns/op	       0 B/op	       0 allocs/op
```
The Benchmark code:
```
const (
RSID  = "RSID"
QRSID = "QRSID"
QRSID_LEN = len(QRSID)
RSID_CID_INDEX   = 1
RSID_SID_INDEX   = 2
EXPECTED_MATCHES = 3
)
var qrsidRe = regexp.MustCompile(`QRSID:(\d+):([^\s]+)`)
var _rsid = …
```

[IMPROVED] Route sid parse performance

---

server/client_test.go
server/server.go
test/tls_test.go

When TLS and authorization is enabled, the authorization timeout can
fire during the TLS handshake, causing the server to write the
authorization timeout error string into the client socket, injecting
what becomes bad data into the TLS handshake. This creates misleading
errors on the client such as tls: oversized record received with length
21024.
Resolves #432
This moves the authorization timeout scheduling to after the TLS
handshake to avoid the race. This should be safe since TLS has its own
handshake timeout. Added a unit test that fails with the old behavior
and passes with the new. LMK if you can think of a better way to test
this.

[FIXED] Authorization Timeout and TLS

---

server/monitor.go
server/monitor_test.go

Resolves #491
Ensure that if the offset is negative, it is set to 0. If the limit
is negative, it is set to the default value.

[FIXED] Check for negative Offset and/or Limit when processing Connz

---

.travis.yml
server/server.go
test/monitor_test.go

In case one creates a server instance with New() and then starts
the http server manually (s.StartHTTPMonitoring()), calling
s.Shutdown() would not stop the http server because Shutdown()
would return without doing anything if `running` was not true.
This boolean was set to true only in `s.Start()`.
Also added StartMonitoring() to perform the options check and
selectively start http or https server to replace individual calls.
This is useful for NATS Streaming server that will now be able
to call s.StartMonitoring() without having to duplicate code
about options checks and http server code.
This is related to PR #481

[FIXED] Ensure Shutdown() always stops http server

---

server/client.go
server/log.go
server/log_test.go
server/monitor.go
server/opts.go
server/parser_test.go
server/route.go
server/server.go
server/signal.go
server/signal_test.go
server/split_test.go

gnatsd currently uses a global logger. This can cause some problems
(especially around the config-reload work), but global variables are
also just an anti-pattern in general. The current behavior is
particularly surprising because the global logger is configured through
calls to the Server.
This addresses issue #500 by removing the global logger and making it a
field on Server.
@nats-io/core

Remove global logger

---

server/client_test.go

Added the sleep back in to TestAuthorizationTimeout which got removed in #493.
This was causing the test to fail intermittently, though it would
usually pass on Travis CI or with the -race flag since these slowed it
down enough.
@nats-io/core

[FIXED] Intermittent failing test

---

server/configs/reload/reload.conf
server/configs/reload/reload_unsupported.conf
server/configs/reload/test.conf
server/reload.go
server/reload_test.go

Add config reload support for `debug` option.
@nats-io/core

Implement config reload support for debug

---

.travis.yml
scripts/cross_compile.sh

Run the cross-compile script as part of CI to prevent mistakes like [this](https://github.com/nats-io/gnatsd/pull/504) from happening again.
@nats-io/core

Cross compile CI

---

server/auth.go
server/auth_test.go
server/opts.go
server/opts_test.go

Ensure Options.Clone() only initializes Users and Routes when the
Options it's cloning has them initialized.
@kozlovic

Fix Options Clone

---

conf/parse.go
server/client_test.go
server/configs/malformed_cluster_address.conf
server/configs/malformed_listen_address.conf
server/configs/reload/basic.conf
server/configs/reload/tls_test.conf
server/configs/reload/tls_verify_test.conf
server/log.go
server/monitor_test.go
server/opts_test.go
server/reload.go
server/reload_test.go
server/route.go
server/routes_test.go
server/server.go
server/server_test.go

- Moves clustering and profiler to Random Ports
- Enables setting Random Ports in config files
- Adds capture of the last error string for future enhancements to unit tests
- Converts Default Option maps to methods generating a new map for each test

Random port extended

---

server/auth.go
server/client.go
server/configs/reload/reload.conf
server/configs/reload/srv_a_1.conf
server/configs/reload/srv_a_2.conf
server/configs/reload/srv_a_3.conf
server/configs/reload/srv_b_1.conf
server/configs/reload/srv_b_2.conf
server/configs/reload/srv_c_1.conf
server/configs/reload/test.conf
server/opts.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go
util/tls.go
util/tls_pre17.go
util/tls_pre18.go

Adds support for cluster/routes config reload. Routes authorization behavior is similar to users: if username/password change, routes that are no longer authorized are closed.
@nats-io/core

Cluster reload

---

server/client_test.go
server/monitor_test.go
server/reload_test.go

Fixing various tests that were failing locally when running in
parallel mode (without -p=1).
In reload_test.go, lots of nats.Conn.Close() were missing which
would require too much memory when running with `-race` mode.

Fix some tests

---

scripts/cross_compile.sh

The cross compile script compiled an ARM executable, but the ARM
default version varies based on the host, etc..
Made a change to the cross compile script to explicitly compile
ARMv5 and ARMv7.

[ADDED] Build for ARMv7

---

server/reload_test.go

Use checkClusterFormed() to minimize risk of test failures due
to the subscription not being registered through the cluster.

Fixed some config reload cluster tests

---

server/reload_test.go

It's hard to implement a bulletproof solution for cleaning up the
symlinks created by config reload tests on failure since, for example,
there is nothing we can do when log.Fatal is called. Instead, prevent
the existence of a symlink from failing the tests if there is one
hanging around. Generally, these symlinks will not be left unless
os.Exit was called (as is the case with log.Fatal).
Fixes #534 
@nats-io/core

Handle symlinks better

---

server/configs/reload/srv_a_3.conf
server/configs/reload/srv_c_1.conf

Trying to solve issue with Windows Docker run:
```
=== RUN   TestConfigReloadClusterRoutes
--- FAIL: TestConfigReloadClusterRoutes (13.11s)
sublist_test.go:28: Expected 1 routes for server "VUlU12p66c8CaA5h9QTaXA", got 0
2 - C:/gopath/src/github.com/nats-io/gnatsd/server/reload_test.go:1313
3 - c:/go/src/testing/testing.go:657
4 - c:/go/src/runtime/asm_amd64.s:2197
```
Already bumped the timeout to 10 seconds, but it did not help.
Noticed that some of the config files involved used `127.0.0.1` while
those 2 used `localhost`. Changed them to use `127.0.0.1`.

Use loopback for some config reload tests

---

Dockerfile.win64
logger/syslog_windows.go
logger/syslog_windows_test.go
server/const.go
server/service_windows.go

The use of the `svc` API prevented the NATS Server to run as
a container on both nanoserver and windowsservercore Docker images.
An attempt was made to replace svc.Debug with normal server.Start()
if detected to be interactive, however, that did not work. The
fact of detecting if interactive or not already requires connecting
to the service controller apparently.
This change looks up for an environment variable (NATS_DOCKERIZED)
and if set to "1", will not make use of the `svc` package.
This environment variable will be set in the Docker image (in
nats-docker/windows/nanoserver/Dockerfile and windowsservercore/Dockerfile).
Resolves #543

[FIXED] Windows Docker Images

---

server/client.go
server/reload.go
server/route.go
server/routes_test.go
server/server.go

When A connects to B and B connects to A (either based on static
configuration - explicit routes, or because of auto-discovery -
implicit routes), it is possible that each server initially
registers the route from the opposite TCP connection. It will
then result in each server dropping the connection.
We were previously setting a retry flag in the first accepted route
based on the name of servers, which means that regardless of
duplicate detection, the server with the "smaller" server name would
try to reconnect when the route connection was closed. For instance,
suppose that server B connects to server A, when B disconnects, A
would try to reconnect once to B. This became problematic in the
case of configuration reload, because removing the route from B to
A would still result in a route …

[FIXED] Handling of duplicate routes

---

server/configs/reload/reload.conf
server/reload_test.go

- Move the kill of a server in a cluster test to ensure that
list of routes to remove is not empty.
- Change write_deadline reload value to 3s to make it different
from default value
- Add test for option that does not support hot-swapping

Improved Config Reload test coverage

---

server/client.go
test/cluster_test.go

Fixed error of hang subscriptions in the cluster when used auto unsubscribe

---

test/client_cluster_test.go
test/tls_test.go

- Corresponding fixes for https://github.com/nats-io/go-nats/pull/308

Use DefaultOptions as function that produces new Options on every call

---

README.md

Resolves #553 
Document string escape behavior in the configuration file.

Document string escape behavior [ci skip]

---

server/client_test.go
server/sublist.go
server/sublist_test.go

The issue was that a subject such as `foo.bar,*,>` would be
inserted to the cache as is, but when trying to remove from the
cache, calling matchLiteral() with the above subject in the cache
against the same subject would return false. This is because
matchLiteral would treat those characters as wildcards token.
Note that the sublist itself splits subjects on the `.` separator
and seem not bothered by such subject (would have `foo` and `bar,*,>`
tokens). Also, note that IsValidSubject() and IsValidLiteralSubject()
properly checked that the characters `*` and `>` are treated
as wildcards only if they are tokens on their own.
Resolves #558
/cc @derekcollison if you could have a look to see if this makes sense, thanks!

[FIXED] Use of `*` and `>` in subjects as literals

---

test/ping_test.go

Resolves:
TLS TImeout causing errors in arm build testing.

increased tls timeout to get test passing on arm.

---

README.md

- [x ] Build is green in Travis CI
- [x ] You have certified that the contribution is your original work and that you license the work to the project under the [MIT license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)
- Added a clarification into README.md about a token usage

DOC: added a clarification about a token usage

---

server/client.go

We were pruning the wrong cache.
@nats-io/core

Fix permissions cache pruning

---

main.go
server/opts.go
server/opts_test.go
server/server.go

There were some cases where override would not work. Any command
line parameter that would be set to the type default value (false
for boolean, "" for string, etc) would not be taken into account.
I moved all the flags parsing and options configuration into
a new function, which may help reduce code duplication in
NATS Streaming.
The other advantage of moving this in a function is that it
can now be unit tested.
I am also removing call to `RemoveSelfReference()` which attempted
to remove a route to self, which has been already solved at runtime
with detecting and ignoring a route to self.
This function would be invoked only when routes were defined in
the configuration file, not in the command line parameter.
Removing this call also solves an user issue (#577)
Resolves #574
Resolves #577

[FIXED] Override from command line not always working

---

server/opts.go
server/opts_test.go

This is just for tests since from main.go, the FlagSet is set
with ExitOnError so Parse() would call os.Exit(2).
Regardless, I wanted to add error checking and a test for that.
Related to #578

Added error check for fs.Parse() call

---

main.go
server/opts.go
server/opts_test.go

This will allow NATS Streaming to provide its own version of what
should be printed when various flags are set.
Related to #578

Pass functions to ConfigureOptions to print version, help, tls help

---

server/sublist.go
server/sublist_test.go

This is similar to #561 where `*` and `>` characters appear in tokens
as literals, not wilcards.
Both Insert() and Remove() were checking that the first character
was `*` or `>` and consider it a wildcard node. This is wrong. Any
token that is more than 1 character long must be treated as a literal.
Only for token of size one should we check if the character is `*`
or `>`.
Added a test case for Insert and Remove with subject like `foo.*-`
or `foo.>-`.

[FIXED] Sublist Insert and Remove with wildcard characters in literals

---

server/server.go

This is an error users should know about. Thus, the log level should be
error.
Fixes #583
@nats-io/core @ripienaar

[CHANGED] Client Accept error log level

---

README.md

Add the write_deadline configuration option to the example configuration file.

Add write_deadline configuration option [ci skip]

---

server/auth.go
server/opts.go
server/server_test.go

Add back a SetCustomClientAuth as a replacement for SetClientAuthMethod that was removed for 1.0.x.)
Resolves #476 (waiting for #434)

Add back custom Auth api

---

util/gnatsd.service

- Bug report #569 "Starting with systemd for daemon management"
- Adds util/gnatsd.service which is a systemd unit file

Add systemd unit file

---

server/util.go

Using a `goto` based loop makes it become a leaf function which can be inlined, making us get a slight performance increase as this is in the fast path:
```
go test ./... -gcflags="-m -m" -run TestParseSize -v 
...
server/util.go:24:6: cannot inline parseSize: unhandled op range
go test ./... -gcflags="-m -m" -run TestParseSize -v
server/util.go:24:6: can inline parseSize as: func([]byte) int {...
```
Local benchmarks:
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkParseSize-4                8.81          5.74          -34.85%
Benchmark_____Pub0b_Payload-4       92.9          85.6          -7.86%
Benchmark_____Pub8b_Payload-4       96.1          86.4          -10.09%
Benchmark____Pub32b_Payload-4       106           99.7          -5.94% …
```

Remove for loop in parseSize to enable inlining

---

server/client.go
server/parser_test.go

The parser has already dropped CRLF by when `processPub` [is called](https://github.com/nats-io/gnatsd/blob/master/server/parser.go#L167-L183), so we can skip doing these checks there.  This change also refactors the pub arg tests to use `t.Run` closure along with more checks for when parsing reply inboxes.

Remove check for '\r\n' when processing pub args

---

.travis.yml
Dockerfile
Dockerfile.all

Updated travis to use 1.8.5 and 1.9.2 and build/push release
for 1.9.2 release.
Updated Docker files too.

Update Go version to 1.9.2

---

server/server.go
server/server_test.go
test/monitor_test.go
test/route_discovery_test.go

The http servers for those two were recently modified to set
a ReadTimeout and WriteTimeout. The WriteTimeout specifically
caused issues for Profiling since it is common to ask sampling
of several seconds. Pprof code would reject the request if it
detected that http server's WriteTimeout was more than sampling
in request.
For monitoring, any situation that would cause the monitoring code
to take more than 2 seconds to gather information (could be due
to locking, amount of objects to return, time required for sorting,
etc..) would also cause cURL to return empty response or WebBrowser
to fail to display the page.
Resolves #600

[FIXED] Profiling and Monitoring timeout issues

---

server/client.go
server/monitor.go
server/monitor_test.go
server/server.go

If server requires TLS and clients are connecting, and a Connz
request is made while clients are still in TLS Handshake, the
call to tls.Conn.ConnectionState() would block for the duration
of the handshake. This would cause the overall http request to
take too long.
We will now not try to gather TLSVersion and TLSCipher from a
client that is still in TLS handshake.
Resolves #600

[FIXED] Connz would "block" for TLS clients still in TLS handshake

---

server/route.go
server/server.go
test/routes_test.go

When the option Cluster.NoAdvertise is false, a server will send
an INFO protocol message to its client when a server has joined
the cluster.
Previously, the protocol would be sent only if the
joining server's "client URLs" (the addresses where clients connect
to) were new. It will now be sent regardless if the server joins
(for the first time) or rejoins the cluster.
Clients are still by default invoking the DiscoveredServersCB callback
only if they themselves detect that new URLs were added. A separate
PR may be filled to client libraries repo to be able to invoke
the callback anytime an async INFO protocol is received.
Based on @madgrenadier PR #597.

[CHANGED] Server notifies clients when server rejoins cluster

---

server/route.go

Also move route created log message to when the route has actually been
created successfully.
Resolves #610
@nats-io/core
cc @ripienaar

[IMPROVED] Use correct log level for route errors

---

README.md
main.go
server/log_test.go
server/opts.go
server/reload.go
server/reload_test.go
server/route.go
server/routes_test.go
server/server.go
server/server_test.go
server/util.go
server/util_test.go
test/proto_test.go

Resolves #447 
- Adds `client_advertise` and `cluster_advertise` config item
- Updates Host and Port in server INFO message
- Updates Host, Port and IP in route INFO message
- If `client_advertise` is set, INFO message's ClientConnectURLs will contain that address
To Do:

[ADDED] Client and Cluster Advertise. Issue #447

---

Dockerfile
Dockerfile.all
server/const.go
server/server.go

Added g/n/gnatsd.GITHASH variable to server. This enables via linker flags to add a value during the build process that is exposed on the server log (if debug) and on /varz.
```-ldflags "-s -w -X github.com/nats-io/gnatsd/server.GITHASH=`git rev-parse --short HEAD`"```
Note that the docker files were injecting a value via the same mechanism that was never exposed ```github.com/nats-io/gnatsd/version.GITCOMMIT```

[ADDED] Print release's GitCommit in the banner

---

.travis.yml

Drop 1.7 and add 1.10. However leave 1.9 for releases for now in case we have a release soon since 1.10.1 is just around the corner fixing some security issues in 1.10

Update Go versions in travis.yml

---

server/client.go
server/reload.go
server/reload_test.go
server/route.go
server/routes_test.go
server/server.go
server/server_test.go
test/monitor_test.go
test/routes_test.go

Until now, a server would only notify clients of servers that join
the cluster. More than that, a server would send ot its clients only
information if new servers were added.
This PR changes this by sending to clients that support async INFO
the list of URLs for all servers in the cluster any time that there
is a change (joining or leaving the cluster).
As of now, clients will not be affected by the change (and will not
take benefit of this: removing servers from their server pool). This
will be addressed in each supported client once this is merged.

[ADDED] Notification to clients when servers leave the cluster

---

server/route.go
server/routes_test.go
server/server.go

When a server accepts a route, it will keep track of that server
`connectURLs` array. However, if the server was creating a route
to that other server at the same time, it will promote the route
as a solicited one. The content of that array was not transfered,
which means that on a disconnect, it was possible that the cluster
topology change was not properly sent to clients.

[FIXED] Cluster toplogy change possibly not sent to clients

---

server/client.go
server/route.go
server/routes_test.go
server/server.go

This is the result of flapping tests in go-nats that were caused
by a defect (see PR https://github.com/nats-io/go-nats/pull/348).
However, during debugging, I realize that there were also things
that were not quite right in the server side. This change should
make it the notification of cluster topology changes to clients
more robust.

Additional fix to #631

---

test/gosrv_test.go
test/test.go

This is used by RunDefaultServer() and some external projects tests
may rely on the fact that this runs on the default port.
Our tests that want to use ephemeral ports to avoid port conflicts
should be updated to not use these default options and/or RunDefaultServer().

Restore DefaultTestOptions port to 4222

---

server/sublist.go
server/sublist_test.go

This would manifest for instance when server tries to send messages
to queue subscribers and a subscription is unsubsribed at the same
time.
Resolves #640

[FIXED] RACE in Sublist

---

logger/log.go
server/configs/reload/file_rotate.conf
server/configs/reload/file_rotate1.conf
server/log.go
server/reload_test.go

As described in issue #630, when rotating log files with a reload, windows would keep files open causing issues.  This fix closes open log files when creating a new logger.  I also renamed the logger import for readability.
Before the fix, windows systems would fail reporting:  _“The process cannot access the file because it is being used by another process.”_

[FIXED] Close old log files when reloading (log rotation)

---

server/monitor.go
server/monitor_sort_opts.go
server/monitor_test.go

Fixes #612 by adding a new Varz method to the Server. This can be used
by processes embedding gnatsd to access the Varz struct without relying
on the HTTP API. This starts with just Varz but the same pattern could
be expanded to other monitoring APIs in the future.
@nats-io/core
cc @ripienaar

[ADDED] Monitor endpoints as server methods (Varz(), etc..)

---

server/client.go
server/route.go
server/routes_test.go
test/routes_test.go

This PR is based out of #633. It imroves parsing QRSID so that the
TestRouteQueueSemantics test now passes (when dealing with malformed
QRSID).
A test similar to what is reported in #632 was also added. This
test however, uncovers a race condition that will be fixed in a
separate PR.
Resolves #632

[IMPROVED] Better attempt at delivering messages to queue subscriptions

---

conf/lex.go
conf/lex_test.go

The configuration format from the server is almost already a superset of JSON with exception of the following two cases:
1) trailing commas from values at the top level are not allowed(although they are supported inside of maps)
2) initial and final brackets at the top level section not supported
This change relaxes the two cases above to just skip those tokens so that the config syntax can also support valid JSON objects for configuring the server which might be helpful when generating it programmatically.
- Skip initial and final brackets from config syntax
- Ignore trailing commas at the top level

Proposal: Improve compatibility with JSON in configuration

---

server/client.go
server/monitor_test.go

This test originally used only 1 connection. It was then modified
to use another connection to check the publishing effect into
the last activity. However, when polling for connz we were using
[0], but that may not necessarily match the connection we were
checking.
I don't think that there was a need for a new connection in this
test, so use a single connection.

Fix last activity monitoring test

---

server/route.go

Fix for the message displayed when `--cluster nats://localhost:-1` is specified. The current behavior is to print `localhost:0` rather than the actual port selected.

[FIXED] Random cluster port displayed as 0 instead of actual value

---

server/pse/pse_openbsd.go

Resolves #290
Copy the pse_darwin.go file to pse_openbsd.go to allow compilation to succeed on OpenBSD. 
CPU numbers appear to be correct after building and running, and tests continue to pass.  
Not sure this is the correct approach, but the native go `ProcUsage` function works correctly on OpenBSD.
-
-
-

Add pse file for OpenBSD

---

server/route.go
server/routes_test.go
server/server.go

When a route connection is created, the server will keep track
of the client structure in a special map until the route protocol
completes. This is meant so that if the server is shutdown before
the route is registered in routes map, the server can kick out
the connection's readLoop.
The route connection was correctly removed on success, but was
not for route connections that were not registered and dropped.
This was not causing any issue, but for correctness, doing the
removal now when server removes a route connection.

Remove route connection from temp map

---

server/client.go
server/monitor.go
server/monitor_test.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go

This PR changes the way we handle client INFO protocols. It will now send the cid such that clients can report into operators (or themselves) their cid for monitoring/debugging. We also now allow filtering of the /connz endpoint by cid.
Lastly I have removed some of the items that were sent to the client in the INFO if they are default, empty or false.

Support CID in client INFO, allow filtering /connz by CID

---

server/auth.go
server/client.go
server/opts.go
server/route.go
test/configs/srv_a_perms.conf
test/routes_test.go

Adds permissions for the cluster. There are Import and Export permissions.
The `client.perms` struct is left unchanged. We simply map Import
and Export semantics to existing Publish and Subscribe ones.

[ADDED] Route permissions

---

server/server.go

The one for route was already changed. Changing the one for
client handshake and TLS timeout.
Resolves #513

[UPDATED] Elevate TLS error logs from DBG to ERR

---

server/client.go
server/client_test.go
server/const.go
server/route.go
server/server.go

[ADDED] Ability to suppress echos from your own connection

---

main.go
server/reload.go
server/reload_test.go
server/route.go
test/test.go

When changing something in the cluster, such as Timeout and doing
a config reload, the route could be closed with an `Authorization
Error` report. Moreover, the route would not try to reconnect,
even if specified as an explicit route.
There were 2 issues:
- When checking if a solicited route is still valid, we need to
check the Routes' URL against the URL that we try to connect
to but not compare the pointers, but either do a reflect
deep equal, or compare their String representation (this is
what I do in the PR).
- We should check route authorization only if this is an accepted
route, not an explicit one. The reason is that we a server
explicitly connect to another server, it does not get the remote
server's username and password. So the check would always fail.
Note: It is possible that …

[FIXED] Possible cluster `Authorization Error` during config reload

---

server/reload.go
server/route.go
server/util.go
server/util_test.go

I don't think it is a good thing to compare the pointers and we
should use the DeepEqual instead.
When comparing a solicited route's URL to the URL that was created
during the parsing of the configuration, the pointers maybe the
same and so u1 == u2 would work. However, there are cases where
the URL is built on the fly based on the received route INFO protocol
so I think it is safer to use a function that does a reflect.DeepEqual
instead.

Ensure URLs are compared using reflect.DeepEqual

---

logger/syslog.go
logger/syslog_windows.go
server/const.go
server/service_windows.go
server/signal.go

for the process name and service name. This allows the reuse of this
code in NATS Streaming Server by invoking the new setters to
change the service and process names.

Update service and syslog code to use variable instead of constant

---

server/sublist.go
server/sublist_test.go

Sublists have a caching layer that is shared. Most of the extreme performance in NATS comes from the client L1 cache of the sublist which has no contention. This works well as long as the sublist has a fairly low rate of change. When highly concurrent reads to the sublist's cache were present performance suffered. 
Also #710 showed a case where the shared cache made things worse.
This PR alleviates some of those issues by being smarter when having a literal subject to add or remove from the shared cache.
It also uses Go 1.9 sync.Map which performs better under highly concurrent conditions with many cores.

Sublist Shared Cache Improvements

---

server/sublist_test.go

Use `checkFor` to ensure that cache size is ok. Repeated test
1000 times and no failure now.

Fix sublist cache flapping test

---

server/opts.go
server/route.go
test/routes_test.go

This is an issue in master only, not in any public release.
The issue is that permissions should be assigned as-is for the
route perms because Publish/Subscribe could be nil, so trying
to dereference Publish.Allow/Deny or Subscribe.Allow/Deny could
crash. The code checking for permissions correctly check if
Publish/Subscribe is nil or not.
This was introduced with PR #725

Fixed crash related to route permissions after allow/deny feature

---

server/server.go
test/ports_test.go

Needed to use filepath, not path for Join/Base in order for that
to work. Tests were actually failing on Windows and now they pass.

[FIXED] Ports file on Windows

---

README.md
server/configs/reload/reload.conf
server/reload_test.go
server/server.go

- Config reload tests have been modified to not rely on symlink.
- Close logger on shutdown (for Windows tests cleanup)

Update some tests

---

server/auth.go
server/monitor.go
server/monitor_test.go
test/configs/srv_a_perms.conf
test/configs/srv_b.conf
test/routes_test.go

The source server will now report any filtering it will be doing on connected routes.

Report route filtering on source server

---

server/reload_test.go

During a config reload, it is possible for the server to send
an -ERR with auth violation and then close the connection.
Client library most of the time will process the -ERR but in
some cases, the socket read gets an error before that can happen.
Some tests were expectign the async error handler to fire, and would
fail the test otherwise. Changed those tests to still check that
if the async error is fire, we get the expected error, but not fail
the test if we don't. We still must get the disconnected callback
in those cases though.

Fixed flappers

---

logger/log.go
logger/syslog.go
logger/syslog_windows.go
server/log.go
server/log_test.go
server/routes_test.go
test/test_test.go

Adds support to be able to log warnings when using `Warnf`.
- Add `Warnf` as part of the `Logger` interface

Add Warnf to Logger interface

---

.travis.yml
server/auth.go
server/client.go
server/log_test.go
server/nkey.go
server/nkey_test.go
server/opts.go
server/opts_test.go
server/server.go

This PR provides basic Nkey support. Server sends nonces and future clients will sign the nonce challenge and return that with their public Nkey.
Added in some warnings for plaintext passwords in config files.
Also added in redaction for passwords in log files when tracing of CONNECT messages.

Basic Nkey support

---

README.md
server/auth.go
server/client.go
server/opts.go
server/opts_test.go
server/routes_test.go
test/configs/srv_a_perms.conf

It will be possible to set subjects permissions regardless of the
presence of an authorization block.

[CHANGED] Cluster permissions moved out of cluster's authorization

---

README.md

To be merged only when https://github.com/nats-io/nats-site/pull/376
is merged and site is live.

Change README nats.io URL documentation back [ci skip]

---

README.md
conf/parse.go
main.go
server/config_check_test.go
server/configs/include_bad_conf_check_a.conf
server/configs/include_bad_conf_check_b.conf
server/configs/include_conf_check_a.conf
server/configs/include_conf_check_b.conf
server/configs/include_conf_check_c.conf
server/opts.go

Introduce `-t` flag thats tests whether the configuration file syntax is correct or not and then exits after reporting errors, including line and source file where the error was found:
```sh
$ cat -n bad.conf
1	listen: 127.0.0.1:4222
2	
3	monitor = "127.0.0.1:8222"
4	
$ gnatsd -c bad.conf -t
unknown field "monitor" in bad.conf:3
```
Or in case of no errors:
```sh
$ gnatsd -c server/configs/authorization.conf -t
configuration file server/configs/authorization.conf test is successful
```
When using `-t` flag, it always has to be used along with `-c`:
```sh
$ gnatsd -t
gnatsd: must specify [-c, --config] option to check configuration file syntax
```
In current PR it only checks for unknown fields or unused variables but in separate PRs it could be added support to report line where an …

[ADDED] Check configuration option `-t`

---

server/auth.go
server/nkey.go
server/nkey_test.go
vendor/github.com/nats-io/nkeys/keypair.go
vendor/github.com/nats-io/nkeys/main.go
vendor/github.com/nats-io/nkeys/nk/main.go
vendor/github.com/nats-io/nkeys/strkey.go
vendor/manifest

Updated for new nkey changes. Also use standard base64 encoding vs URL. Reduce size of raw nonce to 11 which yields 16byte base64.

Update for nkey changes

---

server/client.go
server/log_test.go

Found that current [regex](https://github.com/nats-io/gnatsd/blob/846544ecfe405aaeceb349b23d32a1f73804830c/server/client.go#L708-L709) to filter passwords occasionally can replace the wrong field in some cases. Updating the regex to prevent the following case (using cluster authorization in this case):
Before:
```
[TRC] 127.0.0.1:60178 - rid:3 - ->> [CONNECT {...,"user":"foo","pass":"s3cr3t","name":[REDACTED],...}]
```
After:
```
[TRC] 127.0.0.1:60137 - rid:3 - ->> [CONNECT {...,"user":"foo","pass":"[REDACTED]","name":"jY8IWHNwTq65A5F7PNDQKU",...}]
```
- Update regex for removing password from logs

Fix regex matching group for removing password

---

server/client.go
server/reload.go
server/reload_test.go
server/route.go
server/routes_test.go
server/server.go

[ADDED] Support for route permissions config reload

---

conf/lex.go
server/accounts_test.go
server/auth.go
server/client.go
server/client_test.go
server/configs/accounts.conf
server/errors.go
server/monitor.go
server/nkey_test.go
server/opts.go
server/parser.go
server/reload.go
server/route.go
server/server.go
server/split_test.go
server/sublist.go
server/sublist_test.go

This PR introduces accounts and account isolation. Users are assigned to one account per connection and that defines their subject space.
We also introduce streams and services. These are ways to share messages across accounts with the proper permissions. Streams are pub/sub and Services are usually req/reply semantics. 
We allow explicit permissions to services to also generate implicit permissions in realtime for one time use responses.
We also have support for configuration parsing.

[ADDED] Account Support

---

server/accounts_test.go
server/auth.go
server/errors.go
server/opts.go
server/server.go

Added a reserved account for the default global account for backwards compatibility.

Support for global/reserved accounts

---

server/accounts_test.go
server/client.go

Fix for #772. Track shadowed subscriptions and delete when local interest is removed. This will be reworked during the cluster rewrite.

Cleanup of shadowed subscriptions, fixes #772

---

server/client.go
server/log_test.go

Alternate approach to fix https://github.com/nats-io/gnatsd/issues/762 and https://github.com/nats-io/gnatsd/pull/766 continuing to use regex based approach to filter password entries from the log instead of using JSON.
Resolves #762 

Fixes to remove traced password

---

server/config_check_test.go
server/configs/multiple_errors.conf
server/errors.go
server/opts.go
server/opts_test.go

Enables support to gather all errors that may be found in the configuration file along with the source of the error for each one of them.  This also adds supports for warning error types that will still allow the server to start, but warning messages will be displayed at the beginning instead.  
Multiple errors, warnings shown first: 
```sh
$ gnatsd -c server/nats.conf
server/nats.conf:10:1: invalid use of field "write_deadline": write_deadline should be converted to a duration
server/nats.conf:8:1: unknown field "monitoring"
server/nats.conf:20:30: Detected service "bar" but already saw a stream
server/nats.conf:24:5: Not a valid public nkey for an account: "OC5GRL36RQV7MJ2GT6WQSCKDKJKYTK4T2LGLWJ2SEJKRDHFOQQWGGFQL"
server/nats.conf:29:9: Not a valid public nkey for a user …
```

Show all config errors and warnings on start

---

server/client.go
server/config_check_test.go
server/configs/test.conf
server/const.go
server/monitor.go
server/opts.go
server/opts_test.go
server/route.go
server/server.go
server/server_test.go
server/service_windows.go
server/signal.go
server/signal_test.go
server/signal_windows.go

When receiving SIGUSR2 signal (or -sl ldm) the server stops
accepting new clients, closes routes connections and spread the
closing of client connections based on a config lame duck duration
(default is 30sec). This will help preventing a storm of client
reconnect when a server needs to be shutdown.

Added support for lame duck mode

---

server/config_check_test.go
server/opts.go

Allow conf vars within account block

---

.travis.yml
server/auth.go
server/client.go
server/configs/reload/authorization_1.conf
server/configs/reload/authorization_2.conf
server/reload.go
server/reload_test.go
server/route.go
server/sublist.go
test/bench_test.go
test/configs/authorization.conf
test/configs/auths.conf
test/user_authorization_test.go

Allow deny clauses for subscriptions to still allow wildcard subscriptions but do not deliver the messages themselves.
- [ X] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
Resolves #792 

Fix for #792

---

server/client.go
server/client_test.go
server/parser.go
server/parser_test.go
server/route.go

This was introduced with https://github.com/nats-io/gnatsd/commit/ec3115ad210cbf8ad0fa1dc722db8975181bec67

Fixed data race with client trace flag

---

server/route.go
server/server.go
server/server_test.go

This will allow to signal multiple servers at once to go in
that mode and not have their client reconnect to one of the
servers in the group.

Introduce some delay before closing clients in LameDuck mode.

---

server/accounts.go
server/client.go
server/errors.go
server/jwt_test.go
server/monitor.go
server/reload.go
server/server.go

Implemented single server account claim limits for subscriptions and active connections and message payload size.

Single Server Limits

---

server/client.go
server/gateway.go
server/gateway_test.go
server/opts.go
server/route.go

- If/when splitting buffer to pass to queueOutbound(), it has to
be include full protocol.
- Fix counting of total queue subs
- Fix tests
- Send RS- if no plain sub interest even if there is queue sub
interest.
- Removed a one-liner function

Fixed issue with gateways

---

server/configs/test.conf
server/const.go
server/gateway_test.go
server/opts.go
server/opts_test.go
server/server.go

- Increase grace period to 10sec
- Make default 2min
- Reject config with value less than 30sec
- Don't wait more than 1sec between clients if there are much
less than alloted time
- Stop after last one (was still sleeping after last client was
closed)

Update to LameDuck mode

---

server/auth.go
server/client.go
server/errors.go
server/events.go
server/events_test.go
server/gateway.go
server/monitor.go
server/parser.go
server/parser_test.go
server/route.go
server/server.go
server/split_test.go
server/sublist.go
server/sublist_test.go
server/util.go

Added ability for servers to send and receive messages as their own entity.
Added account scoped events for connection created and connection closed.

Allow servers to send and receive messages directly

---

server/sublist_test.go

This saves a lot of memory and init time when running non benchmark
tests in race mode.

Initialized the sublist for benchmark tests only when needed

---

server/accounts.go
server/client.go
server/events.go
server/events_test.go
server/opts.go
server/opts_test.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go
test/new_routes_test.go

Specifically this is to support distributed tracking of number of account connections across clusters.
Gateways may not work yet based on attempts to only generate payloads when we know there is outside interest.

Allow servers to send system events.

---

server/client.go
server/gateway.go
server/gateway_test.go
server/parser.go
server/route.go
server/server.go
test/gateway_test.go

When a gateway starts to send too many no-interest subjects
for a given account, it may decide to switch to a mode where it
will send all its subs so that the remote no longer optimistically
send, but check explicit interest.
Right now the decision is simply based on the number of RS-
per account, but we could make it more complex.

Switch to send-all-subs when number of RS- gets too big

---

server/gateway.go
server/opts.go
server/reload.go
server/reload_test.go
server/server_test.go

Moved setting to the default value in setBaselineOptions()
so that config reload does not fail.

Fixing setting of default gateway TLS Timeout

---

README.md
main.go
server/opts.go

Resolves #
- Make the `-sl` / `--signal` flag accept the path to a PID file as an argument. This is useful in scenarios where `pgrep` isn't available (such as in the official Docker images) but there is a PID file.

[ADDED] Support a path as argument to --signal

---

server/auth.go
server/client.go
server/client_test.go

This adds a RemoteAddress() method to the ClientAuthentication
interface which would facilitate CustomClientAuthentication
mechanisms considering the remote IP address of the client in
their decisions to allow clients or not
Resolves #832 

[ADDED] RemoteAddress() to the CustomClientAuthentication interface

---

server/client.go
server/gateway.go
server/gateway_test.go
server/route.go
server/server_test.go
test/gateway_test.go
test/new_routes_test.go

This is not complete solution and is a bit hacky but is a start
to be able to have service import work at least in some basic
cases.
Also fixed a bug where replySub would not be removed from
connection's list of subs after delivery.

Allow service import to work with Gateways

---

server/client.go
server/route.go
test/new_routes_test.go

When service imports cross routes they are mapped back and forth from accounts as needed. If the requestor's reply subject also has a queue group, the response message, which traveled as a normal pub, would be dropped when the service import processing produced queue subscribers.
This fixes that edge case.

ServiceImports and queue groups

---

server/const.go
server/events.go
server/events_test.go

Add support to send a broadcast ping to have all servers respond with a statusz. Will do random backoff to prevent thundering herd for requestor.

Support server ping for statusz

---

server/const.go
server/gateway.go
server/gateway_test.go
server/server.go

Otherwise, this may be sent to servers in the cluster and to other
gateways which may result in attempt to connect to self which
in case of TLS would produce error.

Resolve IP if gateway listen is 0.0.0.0 or ::

---

server/client.go
server/events.go
server/events_test.go
server/server.go

Converted to authorization error events on different subject.
Add cluster name if gateways are configured and pass in INFO to clients.

Should not send disconnect events on account $G.

---

server/client.go
server/const.go
test/tls_test.go

Under some scenarios a client may hit the slow consumer write deadline during the connecting stage, meaning that it is possible to consider unhealthy clients that could not finish the TLS handshake as slow consumers.
For example, if the `write_deadline` is way shorter than the TLS timeout deadline it is possible for a client to become a slow consumer even though it has not finished connecting properly:
```sh
[92961] 2018/12/18 22:04:03.308501 [DBG] 127.0.0.1:51506 - cid:1 - Client connection created
[92961] 2018/12/18 22:04:03.308837 [INF] 127.0.0.1:51506 - cid:1 - Slow Consumer Detected: WriteDeadline of 1µs Exceeded
[92961] 2018/12/18 22:04:03.308854 [DBG] 127.0.0.1:51506 - cid:1 - Starting TLS client connection handshake
[92961] 2018/12/18 22:04:03.308931 [ERR] 127.0.0.1:51506 - cid:1 …
```

Only consider as slow consumers clients that did CONNECT

---

docker/Dockerfile.alpine
docker/nats-server.conf

Adds extra Dockerfile image that can be used to build the server from master.
```
docker build -f docker/Dockerfile.alpine -t <image:tag> .
```
- Add Dockerfile.alpine to build latest nats server image

Add alpine based Dockerfile

---

server/gateway.go
server/route.go
test/tls_test.go

Moving some of the connection initialization post TLS handshake
to avoid temporary memory growth when getting repeated failed
connections to any of the client, route and gateway ports.

[FIXED] Memory usage for failed TLS connections

---

server/opts.go
server/reload_test.go

[FIXED] Logtime reset to true on config reload

---

server/accounts.go
server/client.go
server/const.go
test/bench_test.go

This tries to balance the new decoupled producer consumer architecture for fanout with the ability to utilized coupled feedback in fan in scenarios where slow consumers where becoming the norm.

Changes to prevent fan-in scenarios from slow consumer state

---

server/opts.go
server/opts_test.go
server/reload.go
server/reload_test.go
server/routes_test.go

PR #874 caused an issue in case logtime was actually not configured
and not specified in the command line. A reload would then remove
logtime.
Revisited the fix for that and included other boolean flags, such
as debug, trace, etc..
Related to #874

Fixed reload of boolean flags

---

util/gnatsd.service

- Add ntp service dependant to natsd's systemd file after directive. This is for the reason that natsd relies on time correction.

add ntp dep to systemd service file

---

server/util_test.go

- enhance ut with more possible cases for `TestParseSize` and `TestParseSInt64`
-
-

enhance ut for server

---

server/events_test.go
server/server.go

Fixed possible race when looking/registering an account

---

server/client.go
server/server_test.go

There is a possibility that a partial write results in data
not being sent in a timely fashion to a subscription.

[FIXED] Possible delays in delivering messages

---

server/accounts.go
server/client.go
server/client_test.go
server/const.go
server/events.go
server/gateway.go
server/monitor.go
server/opts.go
server/opts_test.go
server/parser.go
server/parser_test.go
server/reload.go
server/route.go
server/server.go
server/split_test.go

1. Change outbound client structure to be smaller and more cache friendly.
2. Snapshot MaxControlLine into client structure (mcl) to avoid server opts lookup.

Some Optimizations

---

conf/lex.go
conf/lex_test.go
conf/parse.go
conf/parse_test.go

Fixes parser to support string values that are not within quotes.
```hcl
authorization {
user = 3hello
pass = 4world
}
```
Before it used to fail with an error as follows:
```
nats-server: Parse error on line 2: 'Expected a map value terminator "," or a map terminator "}", but got 'h' instead.'
```
Fixes #885 

Support for unquoted config strings that start with number

---

conf/parse.go
conf/parse_test.go

Currently if there are issues parsing an env var, the config parser fails silently.

Show parse errors from looked up env vars

---

conf/lex.go
conf/parse_test.go

Improves the compatibility with JSON by allowing to use `"include"` directive within quotes.
Fixes #801 

Allow using quotes around include

---

server/reload.go
server/reload_test.go

Make sure to update connected clients when max_control_line changes.

Support reload of max_control_line by updating connected clients

---

server/client.go

Need to be explicit about the connection type to apply the budget to.

Fixed use of flush budget for connections other than ROUTER

---

.travis.yml

This allows being able to run test builds when forking the repo.

Add go import path for Travis

---

server/parser.go

Resolves #
Added compile type safety for internal parser state. Uncovered single buggy behavior on line 209 (( drop should probably not be set to OP_START but 0, which OP_START has a value of in this case )) 
Furthermore, this change helps the debugger too, since the state isn't a naked int debug resolves the constant appropriately in debugging view (( for goland at least )). Makes it easier to follow through parser code. 
-
-
-

Added type safety to Parser state

---

README.md

Update README with info about TLS based auth introduced in https://github.com/nats-io/gnatsd/pull/865 and https://github.com/nats-io/gnatsd/pull/896

Verify and map readme update

---

.travis.yml
scripts/cov.sh
server/client.go
server/const.go
server/route.go
test/norace_test.go

[FIXED] Possible slow consumers when routes exchange sub list
If each server has a long list of subscriptions, when the route
is established, sending this list could result in each server
treating the peer as a slow consumer, resulting in a reconnect, etc..
Reworked fan in logic.
We do not hold locks during IO, either read or write.
On scenarios where we can get behind mostly due to fan-in from fast producers
we detect and create a stall channel. Once we catch up we close the stall channel
to release all blocked producers. Producers have an upper bound on how long
they will be stalled.

Routes sending large subs and fan-in slow consumer fixes.

---

.github/ISSUE_TEMPLATE.md
README.md

For security, we should change http into https links.
Co-Authored-By: Nguyen Van Trung [trungnv@vn.fujitsu.com](mailto:trungnv@vn.fujitsu.com)
Signed-off-by: Nguyen Quang Huy [huynq@vn.fujitsu.com](mailto:huynq@vn.fujitsu.com)

Change http to https for security links

---

server/gateway.go
server/gateway_test.go
server/server.go
test/gateway_test.go
test/routes_test.go
test/tls_test.go

We now send A- if an account does not exists, or if there is no
interest on a given subject and no existing subscription.
An A+ is sent if an A- was previously sent and a subscription
for this account is registered.

Gateways: Rework Account Sub/Unsub

---

server/gateway.go
test/bench_test.go

Check sublist only when required.
Send the subs list in place instead of go routine (gateways have
different outbound/inbound connections so they don't suffer same
issue than routes)
Bump the default array size when collecting gateway connections

Gateways: some optimizations

---

server/client.go
server/const.go
server/leafnode.go
server/opts.go
server/route.go
server/server.go
test/leafnode_test.go

A server that creates a LeafNode connection to a remote cluster
will now be notified of all possible LeafNode URLs in that cluster.
The list is updated when nodes in the cluster come and go.
Also support for advertise address, similar to cluster, gateway, etc..

LeafNode: support for advertise

---

server/client.go
server/route.go
test/routes_test.go

When a route is established, it is possible that each server sends
its list of subscriptions to each other at the same time. Doing
it in place from the readLoop could then cause problems because
each side could reach a point where the outbound socket buffer
is full and no one is dequeuing data (since readLoop is doing
the send of the subs list).
We changed sending this list from a go routine. However, for small
number of subscriptions, it is not required and was causing some
of the tests to fail because of timing issues.
We will now send in place if the estimated size of all protocols
is below a give threshold (1MB).

Conditional send of routed subs from a go routine

---

server/leafnode.go
server/leafnode_test.go
server/opts.go
server/opts_test.go
server/server.go

This is similar to what we do with Gateways.

LeafNode: do hostname resolution and get random one from result

---

util/mkpasswd.go

Fix the mkpasswd utility on Windows.
Resolves #934 
Unlike other platforms, on windows the fd of `0` is an invalid handle. This was causing `terminal.ReadPassword` to fail resulting in the behavior that was described in #934.  Instead pass  `syscall.Stdin`.
Tested on windows and darwin.

Fix the mkpasswd utility on Windows

---

server/reload.go
server/route.go
test/cluster_tls_test.go

For cluster, we allow to skip hostname verification from certificate.
We now print a warning when this option is enabled, both on startup
or if the property is enabled on config reload.

Add a warning if cluster's insecure setting is enabled

---

server/gateway.go

- The `ServerName` member of the `tls.Config` struct will not be overridden when connecting to a gateway if the provided `tls.Config` struct already has a value set.
(same basic deal as https://github.com/nats-io/nats-streaming-server/pull/767)
I am integrating NATS into Chef's Automate product. Automate internally has a Microservices architecture with connections between services secured by mutual TLS cert verification. Automate is usually deployed by our customers on their own infrastructure so we have elected not to rely on using hostnames in our certificates' CN fields; instead we use the internal service names (i.e., something like event-service instead of host.example.com).
This already works for NATS go clients using the option to set a custom `tls.Config` but when using the …

Allow explicit server name in tls.Config

---

server/gateway_test.go

Checks that if not provided server fails to connect to remote
gateway. Once set to expected hostname ("localhost"), connection
works.
Related to PR: #922 

Added test gateway tlsConfig.ServerName

---

server/const.go
server/route.go
test/new_routes_test.go

Reduce memory during route setup to allow more moderate memory usage for larger clusters.
Addresses some of #954 

Reduce startup memory for cluster

---

server/client.go
server/leafnode.go
test/leafnode_test.go

This adds a test for a service import across a leafnode and a cluster. Also includes fixes to handle properly and deal with no echo directly.

Test for leafnodes, service imports and clusters

---

server/leafnode.go

The leafnode start of go routines for readloop and writeloop were
missing from PR #961

Fixed invocations of startGoRoutine (continued)

---

server/sublist.go
server/sublist_test.go

Allow a sublist's shared cache to be disabled. Also share an empty result set.
Partially Resolves #941 

Allow sublist cache to be disabled

---

server/accounts.go
server/client.go
server/gateway.go
server/gateway_test.go
server/leafnode.go
server/norace_test.go
server/route.go
test/bench_test.go
test/gateway_test.go

This addresses the following race:
- client connection creates a subscription on a reply subject
- client connection sends a request
- server sends the subscription to inbound gateway
- server sends the message to outbound gateway (those may be
to different servers)
- receiving server sends to sub interested in request subject
- app sends reply
- its server then check for interest on the reply's subject
In interestOnly mode, there is a possibility that this server
has not received the interest on the reply subject yet and would
then drop the reply.
This PR detects above scenario and will prefix the reply subject
to identify the origin cluster if it is detected that the last
subscription from the sending connection was created less than
a second ago.
Once the destination has this prefix, …

Gateways: Fix race for request reply

---

server/accounts.go
server/accounts_test.go
server/auth.go
server/client.go
server/events.go
server/gateway_test.go
server/reload.go
server/route.go
server/server.go
server/split_test.go
test/bench_test.go

This switches account lookup to use sync.Map. This should help in concurrent access from routes and gateways when interest graph churn forces cache misses.

Make account lookup faster with sync.Map

---

server/accounts.go
server/auth.go
server/client.go
server/events.go
server/jwt_test.go
server/leafnode.go
server/server.go
test/leafnode_test.go

Added ability to monitor maximum number of connections for leafnodes and enforce similar to the client connections.

Leafnode account based connections limits

---

conf/lex.go
conf/parse_test.go

Reverts nats-io/gnatsd#891 since it would mean not being able to use `"include":` as part of map. Only way that another file can be included would be via this syntax:
```
include "path/to/file"
```
and all the following would result in `unknown field "include"` error:
```java
include: "path/to/file"
"include": "path/to/file"
'include': "path/to/file"
"include" "path/to/file"
'include' "path/to/file"
```

Revert "Allow using quotes around include"

---

server/gateway.go
test/leafnode_test.go

Say there are 2 clusters, A and B. A client connects to A and
publishes messages on an account that B has no interest in.
Then a leaf node server connects to B (using same account than
the no-interest is for). Cluster B will ask cluster
A to switch to interest mode only for leaf node account. This
would cause a panic.

Fixed panic with leafnode and gateway when no interest registered

---

server/client.go
server/const.go
server/gateway.go
server/leafnode.go
test/leafnode_test.go

When having a connection like a client or a gateway that was sending to both routes and leafnodes the prefix for the MSG protocol could get stuck with 'L', causing router protocol violations.
This PR also reuses hostnames for soliciting leafnode connections when TLS is utilized.

Make sure we use correct MSG prefix

---

server/leafnode_test.go
server/opts.go

If server solicits leaf node TLS connection and needs to verify
the server certificate, it did not have the root CAs set in its
config.

Fixed LeafNode failed to create TLS connection when CA needed

---

server/reload.go
server/reload_test.go

We don't support reload of leafnode config yet, but we need to make
sure it does not fail the reload process if nothing has been changed.
(it would fail because TLSConfig internally do change in some cases)

Fixed failed configuration reload due to present of leafnode with TLS

---

server/auth.go
server/client.go
server/events.go
server/leafnode.go
server/monitor.go
server/opts.go
server/server.go
test/leafnode_test.go

Various fixes for panics in auth event handling and leafnodes.
Added gateway interest for smap handling for leafnodes.

Leafnode updates

---

server/leafnode.go
test/leafnode_test.go

Remotes were not sending existing subject interest. Detected when a local app was trying to reconnect on a remote leafnode restart.

Make sure remotes send existing sub interest

---

server/monitor.go
server/monitor_test.go
server/opts.go
server/reload.go
server/reload_test.go
server/server.go

----------------------------------------------------------------
Backward-incompatibility note:
Varz used to embed *Info and *Options which are other server objects.
However, Info is a struct that servers used to send protocols to other
servers or clients and its content must contain json tags since we
need to marshal those to be sent over. The problem is that it made
those fields now accessible to users calling Varz() and also visible
to the http /varz output. Some fields in Info were introduced in the
2.0 branch that clashed with json tag in Options, which made cluster{}
for instance disappear in the /varz output - because a Cluster string
in Info has the same json tag, and Cluster in Info is empty in some
cases.
For users that embed NATS and were using Server.Varz() directly,
without …

[FIXED] Changes to Varz content and fixed race conditions

---

server/accounts.go
server/leafnode.go
server/server.go

Previously we would walk all clients bound to an account to
collect the leaf nodes for updating of the subscription maps.
Resolves #988 

Optimize updates for leaf node smaps.

---

docker/Dockerfile.alpine

This adds a symlink of the `nats-server` binary to `/gnatsd`  in order to mimic how the `FROM scratch` image works.

Add symlink to gnatsd on alpine image

---

server/gateway.go
server/leafnode.go
server/route.go
server/routes_test.go
server/server_test.go
server/util.go

This applies to routes, gateways and leaf node connections.
The failed attempts will be printed at the first, after the first
minute and then every hour.
The connect/error statements now include the attempt number.
Note that in debug mode, all attempts are traced, so you may get
double trace (one for debug, one for info/error).
Resolves #969

[UPDATED] Reduce report of failed connection attempts

---

server/configs/test.conf
server/const.go
server/gateway.go
server/leafnode.go
server/opts.go
server/opts_test.go
server/route.go
server/server_test.go
server/util.go

This is a continuation of #1000. Added a configuration to specify
the number of attempts at which the repeated error is reported.
The algo is now to print only the 1st attempt and when current
attempt % <this config param> == 0.
Resolves #969

Make the error report attempts configurable

---

server/gateway.go

Shuffle the array created when iterating through the gateways URLs
map since map iteration may not be well randomized with small maps.

Better randomize solicited Gateway URLs

---

server/const.go
server/gateway.go
server/parser.go
test/gateway_test.go

If the first protocol for an inbound gateway connection is not
CONNECT, reject with auth violation.
Fixes #1006

Check inbound GW connection connected state in parser

---

server/gateway.go
server/monitor.go
server/monitor_test.go
server/reload.go
server/server.go

In varz's cluster{} section, there was no URLs field. This PR adds
it and displays the routes defined in the cluster{} config section.
The value gets updated should there be a config reload following
addition/removal of an url from "routes".
If config had 1 route to "nats://127.0.0.1:1234", here is what
it would look like now:
```
"cluster": {
"addr": "0.0.0.0",
"cluster_port": 6222,
"auth_timeout": 1,
"urls": [
"127.0.0.1:1234"
]
},
```
Adding route to "127.0.0.1:4567" and doing config reload:
```
"cluster": {
"addr": "0.0.0.0",
"cluster_port": 6222,
"auth_timeout": 1,
"urls": [
"127.0.0.1:1234",
"127.0.0.1:4567"
]
},
```
Note that due to how we handle discovered servers in the cluster,
new urls dynamically discovered will not show in above output.
This could be done, but would need some …

[ADDED] URLs to cluster{} in /varz and update of gateway ones

---

server/events_test.go
server/gateway_test.go
server/monitor_test.go
test/leafnode_test.go

- TestSystemAccountConnectionUpdatesStopAfterNoLocal: I believe that
the check on number of notifications was wrong. Since we did not
consume the ones for the connect, the expected count after the
disconnect is 8 instead of 4.
- Possible fix GW tests complaining about number of outbound/inbound
I think that it may be possible that connection does not succeed
right away (remote to fully started, etc) and due to dial timeout
and reconnect attempt delay, I suspect that when given a max time
of 1sec to complete, it may not be enough.
Quick change for now is to override to 2secs for now in the
wait helpers. If that proves conclusive, we could remove the
timeout given to these helpers.
- TestGatewaySendAllSubsBadProtocol: used a t.Fatalf() in checkFor
instead of return fmt.Errorf().
- …

Fix flappers

---

server/gateway.go
server/gateway_test.go
test/gateway_test.go

Suppose two servers, SA in cluster A and SB in cluster B. If SA
sends a message to SB on an account for which there is no interest
at all (account not known or no subscription), SB will send an A-
and keep track that it sent an A- for this account.
When a queue subscription is created on SB, SB will send and RS+
to A because A needs to have perfect knowledge of all queue subs
in all clusters.
If then a regular subscription is also created on SB, SB will
think that it needs to send an A+ because it had sent an A- for
this account. However, SA had an entry for this account for the
queue sub. The A+ would clear the entry in the map and would cause
SA to not send messages to SB even if they would have been a
match for the queue sub on SB.
We fix this in two ways:
- Clear the possible A- in SB …

Fixed loss of queue subscription interest across Gateways in some cases

---

server/gateway.go
server/gateway_test.go
server/monitor.go
server/monitor_test.go
server/norace_test.go
server/server.go

Such endpoint will list the gateway/cluster name, address and port
then list of outbound/inbound connections.
For each remote gateway there will be at most one outbound connection.
There can be 0 or more inbound connections for the same remote
gateway.
For each of these outbound/inbound connection, the connection info
similar to Connz is reported. Optionally, one can include the
interest mode/stats for each account.
Here are possible options:
* No specific options
http://host:port/gatewayz
* Limit to specific remote gateway, say name "B":
http://host:port/gatewayz/gw_name=B
* Include accounts
http://host:port/gatewayz/accs=1
* Specific account, say "acc_1". Note that accs=1 is not required then
http://host:port/gatewayz/acc_name=acc_1
* Above options can be mixed: specific remote gateway …

[ADDED] Gatewayz endpoint

---

server/configs/test.conf
server/const.go
server/gateway.go
server/gateway_test.go
server/leafnode.go
server/monitor_test.go
server/opts.go
server/opts_test.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go
server/server_test.go
server/util.go

Changed the introduced new option and added a new one. The idea
is to be able to differentiate between never connected and reconnected
event. The never connected situation will be logged at first attempt
and every hour (by default, configurable).
However, once connected and if trying to reconnect, will report every
attempts by default, but this is configurable too.
These two options are supported for config reload.
Related to #1000
Related to #1001
Resolves #969

Update to connect/reconnect error reports logic

---

server/gateway.go
server/gateway_test.go

Both sides will log when an account is switched to interest-only
mode. There are 2 traces (start/complete) per account.
They are logged at [INF] level.

Added logging of account interest mode switch for gateways

---

server/client.go
server/const.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go
test/configs/new_cluster.conf
test/operator_test.go

When tls is on routes it can cause reloadAuthorization to be called.
We were assuming configured accounts, but did not copy the remote map.
This copies the remote map when transferring for configured accounts
and also handles operator mode. In operator mode we leave the accounts
in place, and if we have a memory resolver we will remove accounts that
are not longer defined or have bad claims.

Fix for reloadAuthorization bugs

---

server/opts.go
server/opts_test.go

This will be required for NATS Streaming server since streaming
allows user to have NATS and Streaming specific options in same
file.

Added a function to allow ignoring top-level unknown config option

---

server/gateway.go
server/gateway_test.go

When a leafnode connection is created, the server forces all
gateway inbound connections to switch to InterestMode. Do this only
once, regardless of how many times the LN (re)connects.

Switch gateway to InterestMode only once

---

server/auth.go
server/client.go
server/const.go
test/leafnode_test.go

This allows account connect and disconnect events for leafnodes. Still need accounting for long standing connections, but this brings leafnodes up to clients for the moment.

Add in leafnode bound account events for accounting

---

server/auth.go
server/client.go
server/const.go
test/leafnode_test.go

Leafnodes should behave like direct connected clients and prefer local cluster distributed queue subscribers before crossing a gateway. 

Fix for leafnode messages and DQ selection over GWs

---

server/client.go
server/leafnode.go
server/route.go
test/leafnode_test.go
test/norace_test.go

When messages came from a leafnode there were not being distributed evenly to the destination cluster.

Messages not distributed evenly when sourced from leafnode.

---

server/config_check_test.go
server/const.go
server/leafnode_test.go
server/opts.go
server/opts_test.go

Resolves #1039
- Allows overriding the TLS timeout for leaf remotes when no using certs (otherwise fail with file not found error)
- Bumps the default timeout for leafnode remotes to 2s

Allow updating TLS timeout for leafnode remotes

---

server/client.go
server/leafnode.go
test/maxpayload_test.go

One could craft a PUB protocol to cause server to panic. This can
happen if the size in the PUB protocol overruns an int32.
(note that if authorization is enabled, the user would need to
authenticate first, limiting the impact).
Thank you to Aviv Sasson and Ariel Zelivansky from Twistlock
for the security report!

[FIXED] Check of maxpayload could be bypassed if size overruns int32

---

server/accounts.go
server/client.go
server/gateway.go
server/opts.go
server/opts_test.go
server/server.go
server/sublist.go
server/sublist_test.go

Added a "disable_sublist_cache" which will globally turn off caching. Accounts issue was resolved by not allocating sublist by default.
In gateway and in permissions I used caching where we expected change rate to be low (e.g. permission only on config load/reload).

Allow sublist cache do be disabled globally for all accounts.

---

server/client.go
test/maxpayload_test.go

When a bound account's MaxPayload is not the same as the server make sure we send it to clients that can do async INFO.

MaxPayload async INFO updates

---

server/leafnode.go
server/leafnode_test.go
server/monitor.go
server/monitor_test.go
server/opts.go
server/opts_test.go
server/server_test.go
test/leafnode_test.go

Convert leafnode solicited remotes to an array

---

server/server.go

- Add check for monitor server `Serve` returned error.
-
-

check for monitor server start error

---

server/gateway.go
server/route.go
server/server.go
server/server_test.go
test/cluster_tls_test.go

This has an effect only on connections created by the server,
so routes and gateways (explicit and implicit).
Make sure that an explicit warning is printed if the insecure
property is set, but otherwise allow it.
Resolves #1062

[FIXED] Allow TLS InsecureSkipVerify again

---

server/leafnode.go
server/route.go
test/leafnode_test.go

When a cluster of servers are having routes to each other, there
is a chance that the list of leafnode URLs maintained on each
server is not complete. This would result in LN servers connecting
to this cluster to not get the full list of possible URLs the
server could reconnect to.
Also fixed a DATA RACE that appeared when running the updated
TestLeafNodeInfoURLs test. Fixed the race and added specific
test that easily demonstrated the race: TestLeafNodeNoRaceGeneratingNonce

[FIXED] LeafNode urls may be missing in INFO sent to LN connections

---

server/client.go
server/opts.go
server/opts_test.go
server/reload.go

Resolves #None
- allow limit to traced message
-
-

allow limit to traced message

---

server/accounts.go
server/client.go
server/route.go
server/server.go
test/new_routes_test.go

Fix for #1065 
When the same dq subscriber was represented across multiple client connections the state of updates to the queue weight could have been delivered out of order to a route server, resulting in orphaned subscriptions. This fix deals with contention and will only send the latest update such that it can avoid sending needless updates and will not send a previous update to a remote route.

Fix for #1065 (leaked subscribers from dq subs across routes)

---

server/auth.go
server/client.go
server/configs/authorization.conf
server/const.go
server/opts.go
server/opts_test.go
server/route.go
test/configs/authorization.conf
test/configs/auths.conf
test/user_authorization_test.go

This allows a dynamic publish permission to be granted only to subjects that were delivered as reply subjects. We also allow more detailed permission on maximum number of messages that can use the permission and maximum amount of time the permission can be active.

Allow dynamic publish permissions based on reply subjects of received msgs.

---

server/client.go
server/norace_test.go

When a route receives a message, it uses a thread local cache to
find the account and subscriptions match for a given subject.
When not found, an entry is added to this cache. The problem is
that this cache will reference subscriptions that in turn
reference connections.
When the subscriptions/connections are closed, this thread local
cannot be purged from those closed subscriptions (since it is
thread local - no locking is used).
The real issue is that connection's buffer was not set to nil on
close, which then could cause more than expected memory to be
still referenced. Setting the buffer to nil will help reduce the
memory being used.
When an entry is added to the cache, the cache may reach a size
that will cause the server to prune some entries. From time to
time, the cache will be …

[FIXED] Reduce memory usage on routes

---

server/accounts.go
server/accounts_test.go
server/client.go
server/client_test.go
server/configs/accounts.conf
server/const.go
server/events.go
server/leafnode.go
server/opts.go
server/reload.go
server/route.go
server/server.go

Enable stream responses. Take into account tracking of response maps that are created and do proper cleanup.
Also fixes #1089 which was discovered while working on this.

Add ability for cross account import services to return streams

---

go.mod
go.sum
server/accounts.go
server/jwt_test.go
vendor/github.com/nats-io/jwt/creds_utils.go
vendor/github.com/nats-io/jwt/exports.go
vendor/modules.txt

Test checks that response types are initialized
Updated to latest JWT library with response types
- [X ] Branch rebased on top of current master (`git pull --rebase origin master`)
- [X ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X ] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)
Resolves #
- Add support for response types in services, based on latest JWT library
- Updated to latest JWT library
- Updated vendor

Added support for service response types

---

server/client.go
server/const.go
server/gateway.go
server/gateway_test.go
server/monitor.go
server/opts_test.go
server/route.go

This was introduced in PR#930. The first commit had the route's
check if the flushOutbound() returned false, and if so would
locally unlock/lock the connection's lock. Unfortunately, this
was replaced in the second commit (https://github.com/nats-io/nats-server/commit/a6aeed3a6b359de2be5b1d6edd8b33d48b61610b)
to the flushOutbound() function itself.
This causes the function closeConnection() to possibly unlock
the connection while calling flushOutbound(), which if the
connection is closed due to both a tls timeout for instance
and explicitly, it would result in the connection being scheduled
for a reconnect (if explicit gateway connection, possibly route).
Added defensive code in Gateway to register a unique outbound gateway.

[FIXED] Connection could be closed twice

---

.travis.yml

I had put that in place when testing the release process.
Removing now.

Removing skipping email notification [ci skip]

---

.travis.yml
server/accounts_test.go
server/client.go
server/gateway_test.go
server/norace_test.go

I noticed that TestNoRaceRoutedQueueAutoUnsubscribe started to
fail a lot on Travis. Running locally I could see a 45 to 50%
failures. After investigation I realized that the issue was that
we have wrongly re-used `subscription.nm` and set to -1 on unsubscribe
however, I believe that it was possible that when subscription was
closed, the server may have already picked that consumer for a delivery
which then causes nm==-1 to be bumped to 0, which was wrong.
Commenting out the subscription.close() that sets nm to -1, I could
not get the test to fail on macOS but would still get 7% failure on
Linux VM. Adding the check to see if sub is closed in deliverMsg()
completely erase the failures, even on Linux VM.
We could still use `nm` set to -1 but check on deliverMsg(), the
same way I use the …

Fixed subscription close

---

server/monitor.go
server/monitor_test.go
server/route.go
server/routes_test.go
test/new_routes_test.go
test/norace_test.go
test/route_discovery_test.go
test/routes_test.go

Added the RTT field to each route reported in routez.
Ensure that when a route is accepted, we send a PING to compute
the first RTT and don't have to wait for the ping timer to fire.

[ADDED] RTT in routez's route info

---

server/client.go
server/route.go
test/bench_test.go

With Go 1.12 (strangely was not able to reproduce with Go 1.11)
the test TestRouteNoCrashOnAddingSubToRoute() would frequently
locks up and consume all avail CPUs on the machine. Running
this test with GOMAXPROCS=2 you would see server.test CPU usage
pegged at 200% (assuming you have at least 2 CPUs).
The reason was that the writeLoop was spinning because another
routine was already in flushOutbound() and stack trace would
show that it was stuck in system calls. It seems that even though
the writeLoop does release the lock but grab it right away was
not allowing the syscall to complete.
So decided to put back the unlock/gosched/lock back in flushOutbound()
when flag is already set, but then protect the closeConnection()
with its own flag (similar to clearConnection) to not re-introduce …

Fixed flushOutbound

---

server/accounts.go
server/accounts_test.go
server/client.go
server/client_test.go
server/errors.go
server/events.go
server/events_test.go
server/server.go
server/sublist.go
test/leafnode_test.go
test/service_latency_test.go

This PR allows an exported service to request latency tracking for the service itself. This tracking can be down-sampled and supports anything from 1-100%. When configuring latency, you give the export a subject to publish metrics to, e.g. `latency.metrics.service1`.  Each service can have its own sampling rate and its own publish subject for metrics.
The system will track the backend service latency no matter how many queue subscribers / normal subscribers, and also properly tracks the NATS latency. So for instance if a requestor is far away the system will report that the backend took say 2ms but NATS latency was 12ms for a total of 14ms for the sampled latency.
This will work regardless of NATS setup, from a single server to a small cluster to a global system like NGS.
Signed-off-by: …

Track latency for exported services

---

server/configs/new_style_authorization.conf
server/opts_test.go

Currently, the $SYSTEM subject is used in this repo, but it seems like this
subject name is out of date.
This change updates the code to use $SYS to match the [documentation](https://nats-io.github.io/docs/sys_accounts/sys_accounts.html).

Update SYS account name

---

server/accounts.go
server/events.go
server/jwt_test.go
server/server.go

If account A imports from B and B from A, when the account A
is built, it causes B to be fetch, but since B imports from A,
A was fetch/built again in an infinite loop.
Resolves #1117

[FIXED] Circular account service import dependency

---

server/accounts.go
server/client.go
server/events.go
server/gateway.go
test/service_latency_test.go

Will now breakout the internal NATS latency to show requestor client RTT, responder client RTT and any internal latency caused by hopping between servers, etc.
Resolves #
-
-
-

Latency tracking updates.

---

server/accounts.go
server/accounts_test.go
server/route.go
test/norace_test.go

In updateRouteSubscriptionMap(), when a queue sub is added/removed,
the code locks the account and then the route to send the update.
However, when a route is accepted and the subs are sent, the
opposite (locking wise) occurs. The route is locked, then the account.
This lock inversion is possible because a route is registered (added
to the server's map) and then the subs are sent.
Use a special lock to protect the send, but don't hold the acc.mu
lock while getting the route's lock.
The tests that were created for the original missed queue updates
issue, namely TestClusterLeaksSubscriptions() and
TestQueueSubWeightOrderMultipleConnections() pass with this change.

Fixed a lock inversion issue with account

---

server/opts.go

Modified the cluster listenstr parsing to allow cluster urls that have a -1 for a port. This re-enables ability to create clusters on a random port for testing.

FIX #1128 - allow cluster urls with -1 to work again

---

server/accounts.go
server/auth.go
server/client.go
server/errors.go
server/events.go
server/events_test.go
server/leafnode.go
server/parser.go
server/server.go
server/sublist.go
test/leafnode_test.go
test/system_services_test.go

This is the first pass at introducing exported services to the system account for generally debugging of blackbox systems.
The first service reports number of subscribers for a given subject. The payload of the request is the subject, and optional queue group, and can contain wildcards.

System level services for debugging.

---

server/accounts.go

This is for API server lookup of account JWTs on server bounce to amortize the TLS costs.

Use multiple connections to amortize TLS

---

server/accounts.go
server/events.go
server/events_test.go
server/jwt_test.go
server/reload.go
server/server.go
server/split_test.go

Ensure that lookupAccount does not hold server lock during
updateAccount and fetchAccount.
Updating the account cannot have the server lock because it is
possible that during updateAccountClaims(), clients are being
removed, which would try to get the server lock (deep down in
closeConnection/s.removeClient).
Added a test that would have show the deadlock prior to changes
in this PR.

[FIXED] Locking issue around account lookup/updates

---

server/accounts.go
server/client.go
server/config_check_test.go
server/const.go
server/opts.go
server/opts_test.go

Currently, the config file doesn't recognize the `latency` config block in account exports. This change exposes those settings in the config file.
TODO:

Expose service latency info in config file

---

server/accounts.go
server/server.go
test/service_latency_test.go

- Add ability to programatically untrack latency.
- Make sure to turn on for existing service imports on an export claim update.
- General cleanup for service exports.

Latency tracking updates

---

server/accounts.go
server/client.go
test/service_latency_test.go

Fixes issue with latency tracking samples occasionally being negative by adjusting them to be zero instead.

Adjust to zero negative latency values

---

server/client.go
server/client_test.go

Adds support for permissions for queue subscriptions.  For example:
```hcl
users = [
{
user: "foo", permissions: {
sub: {
allow: ["foo", "foo v1", "foo v1.>", "foo *.dev"]
deny: ["> *.prod"]
}
}
]
```
Signed-off-by: Jaime Piña <jaime@synadia.com>

Add QueueSubscribe permissions

---

server/auth.go
server/config_check_test.go
server/leafnode.go
server/leafnode_test.go
server/opts.go
server/server.go

Added a way to specify which account an accepted leafnode connection
should be bound to when using simple auth (user/password).
Singleton:
```
leafnodes {
port: ...
authorization {
user: leaf
password: secret
account: TheAccount
}
}
```
With above configuration, if a soliciting server creates a LN connection
with url: `nats://leaf:secret@host:port`, then the accepting server
will bind the leafnode connection to the account "TheAccount". This account
need to exist otherwise the connection will be rejected.
Multi:
```
leafnodes {
port: ...
authorization {
users = [
{user: leaf1, password: secret, account: account1}
{user: leaf2, password: secret, account: account2}
]
}
}
```
With the above, if a server connects using `leaf1:secret@host:port`, then
the accepting server will bind the …

[ADDED] Basic auth for leafnodes

---

server/opts.go
server/opts_test.go

Currently, the leafnode configuration doesn't expand the `~` character to the user's home directory. This change allows users to use `~` in the configuration file when declaring the path to their credentials.
```
leafnodes {
remotes [
{
url: nats-leaf://127.0.0.1:2222
account: foobar
credentials: ~/my.creds
}
]
}
```
Signed-off-by: Jaime Piña <jaime@synadia.com>

Add tilde support for leafnode credentials

---

server/memstore.go
server/memstore_test.go
server/sysmem/mem_windows.go

- If all messages are expired, stop/set timer to nil so new messages can be expired
- If not all messages are expired, reset timer to fire soon.
Also add missing `package` for sysmem/windows

Fix message expiration

---

server/monitor.go
server/ring.go
server/server.go
test/configs/multi_accounts.conf
test/monitor_test.go

1. Accounts, if not the global account, will show up in connection info if auth=1.
2. When using auth=1 info, you can now filter by user (?auth=1&user=ivan) or account (?auth=1&acc=eng)
This will need changes to docs for arguments - https://nats-io.github.io/docs/nats_server/monitoring.html#connection-information 
/cc @gcolliso

Account support for Connz and user or account filtering

---

server/pse/pse_windows.go

Resolves #
TrimRight is char based, and TrimSuffix is word based, that's what we want here,
please see diffs here: https://play.golang.org/p/HwWzZ86WbqS

fix string trim func usage in pse

---

server/configs/test.conf
server/events.go
server/monitor.go
server/monitor_test.go
server/opts.go
server/opts_test.go
server/server.go
server/server_test.go
server/sublist_test.go

This adds a new config option server_name that
when set will be exposed in varz, events and more
as a descriptive name for the server.
If unset though the server_name will default to the pk

Allows a descriptive server_name to be set

---

server/gateway.go
server/gateway_test.go

If cluster A configures a gateway to cluster B, the server on A
tries to connect to any configured URL. If there is no server on B
at any of the configured addresses, but a server on B with a 
different address connects to server on cluster A, that server
should be able to create its outbound connection in response.
That was not the case because the configured URLs were snapshot
before the loop of trying to connect. When accepting an inbound
connection and updating the array, this new URL was not being used.
The issue is only if the server on A had no outbound connection
at that time.

[FIXED] Explicit gateway not using discovered URLs

---

server/opts.go
server/reload_test.go
server/route.go

I may need to introduce a new route protocol version for an upcoming
PR and realized that this needed some cleaning.

Changes on how tests can override route protocol

---

server/events.go
server/events_test.go
server/route.go

Add the remote server name for a route in the statsz event

[ADDED] Server name in the RouteStat for statsz

---

server/accounts.go
server/leafnode.go
server/leafnode_test.go
server/monitor_test.go
server/opts.go
test/leafnode_test.go

This is achieved by subscribing to a unique subject. If the LS+
protocol is coming back for the same subject on the same account,
then this indicates a loop.

[FIXED] Detect loop between LeafNode servers

---

server/client.go
server/client_test.go
server/monitor.go

As soon as server has processed a client CONNECT, it was possible
that if Connz() or other was requested, the server will send a
PING to compute the RTT. This would cause clients that expect
the first PONG as part of synchronous CONNECT logic to fail.
Make sure that we delay the first RTT ping to after sending the
first PONG, or if client does not send PING as part of the CONNECT,
after 2 seconds have elapsed since the tcp connection was accepted.
Resolves #1174

[FIXED] Server should not send RTT PING before sending initial PONG

---

server/accounts.go
server/accounts_test.go
server/client.go
server/events.go
server/monitor_test.go
server/opts_test.go
server/server.go
test/service_latency_test.go
test/test_test.go

If a client RTT for a requestor is longer than a service RTT, the requestor latency was often zero.
We now wait for the RTT (if zero) before sending out the metric.

Wait on requestor RTT when tracking latency.

---

server/accounts.go
server/client.go
server/client_test.go
server/events.go
server/gateway.go
server/gateway_test.go
server/leafnode.go
server/norace_test.go
server/route.go
server/server.go
server/split_test.go
test/bench_test.go
test/gateway_test.go
test/leafnode_test.go
test/service_latency_test.go

- New prefix that includes origin server for the request
- Mapping done if request is service import or requestor has
recent subscription
- Subscription considered recent if less than 250ms
- Destination server strip GW prefix before giving to client
and restore when getting a reply on that subject
- Mapping removed aftert 250ms
- Server rejects client publish on "$GNR." (the new prefix)
- Cluster and server hash are now 8 chars long and from base 62
alphabets
- Mapped replies need to be sent to leafnode servers due to race
(cluster B sends RS+ on GW inbound then RMSG on outbound, the
RS+ may be processed later and cluster A may have given message
to LN before RS+ on reply subject. So LN needs to accept the
mapped reply but will strip to give to client and reassemble
before sending it …

Work on Gateways reply mapping

---

server/accounts.go
server/server.go

We may have the case that the account is held in tmpAccounts but does not have a sublist. When this happens if we process as RS+ and do LookupAccount and get it from the tmpAccount and before it was registered the route code could try to do an insert on the sublist.

Fix possible panic on nil sublist.

---

server/accounts.go
server/accounts_test.go
server/client.go
server/events.go
server/gateway.go
server/gateway_test.go
server/route.go
server/server.go
test/new_routes_test.go
test/service_latency_test.go

We had too much special processing, so reduced to a single wildcard which will propagate across routes and gateways and is consistent with gateway handling of globally routed subjects and timeouts.
Signed-off-by: Derek Collison derek@nats.io

Introduced wildcard handling of _R_ mapped replies. 

---

server/events.go
server/server.go
test/operator_test.go

Noticed we would lookup accounts, but would also fetch them when tracking remote connections, etc.

Do not fetch accounts on system events.

---

server/leafnode.go
test/leafnode_test.go

This is needed for mapped gateway replies. We had used an extra
token when implementing the new prefix, but it was then removed,
but the leafnode subscription on _GR_.*.*.*.> was not updated.
We now subscribe on _GR_.>
There was a test that was passing because we were using inboxes
that caused the pattern to match. Replaced with single token
reply so that it would have caught this bug.

Make the Leafnode internal sub on _GR_.>

---

server/parser.go
server/split_test.go

With this test, and with previous cloneArg() code, the parsing
will cause subject to become "fff" because c.pa.subject points
to somewhere in the underlying buffer that is now overwritten
with the body payload. With proper cloneArg(), the c.pa.subject
(and other) point to the copy of argBuf.

Added split test buffer that shows the subject overwritte

---

logger/syslog_windows_test.go
server/client.go
server/config_check_test.go
server/events_test.go
server/gateway_test.go
server/monitor.go
server/monitor_test.go
server/opts_test.go
server/server_test.go
test/leafnode_test.go
test/routes_test.go

Running test suite on a Windows VM, I notice several failures.
Updated the compute of the RTT to be at least 1ns. I think that
this is just an issue with the VM I am running, but that change
will have no impact for normal situations (since setting the rtt
to the very minimum duration (1ns) instead of 0) and will prevent
some tests from failing.
Because of those same timer granularity issues, I had to add some
delays between some actions in order for time.Sub()/Since() to
actually report something more than 0.

Tune some code/test for Windows

---

logger/log.go
logger/log_test.go
server/log.go
server/opts.go

Allow auto-rotation of log files when the size is greater than
configured limit.
The backup files have the same name than the original log file
name with the following suffix:
<log name>.yyyy.mm.dd.hh.mm.ss.micros
where:
- yyyy   is the year
- mm     is the month
- dd     is the day
- hh     is the hour
- mm     is the minute
- ss     is the second
- micros is the number of microseconds (to help avoid duplicates)
Resolves #1197

[ADDED] LogSizeLimit option

---

server/gateway.go
server/gateway_test.go

Prevent sending an A- for a given account if the server has this
account registered and an internal service reply subscription.

[FIXED] Prevent A- for account that has service reply subscription

---

server/opts.go

According to the help it should be possible to use --jetstream command line option.

add long version to toggle on jetstream

---

server/client.go
server/client_test.go
server/gateway.go
server/gateway_test.go
server/leafnode_test.go
server/route.go
server/routes_test.go

This could happen if the remote server is running but not dequeueing
from the socket. TLS connection Close() may send/read and so we
need to protect with a deadline.
For non client/leaf connection, do not call flushOutbound().
Set the write deadline regardless of handshakeComplete flag, and
set it to a low value.

[FIXED] Closing of Gateway or Route TLS connection may hang

---

server/client.go
server/const.go
server/events.go
server/events_test.go

- Call flushOutbound() for SYSTEM connections
- Flush in place in internalSendLoop when sending the shutdown event
- Fix some tests:
- missing defer client connection Close()
- ensure subs are registered and messages received before shutdown
of leafnode server to check disconnected event's stats.

Fixes for system events

---

server/accounts_test.go
server/client.go
server/client_test.go
server/events_test.go
server/jwt_test.go
server/log_test.go
server/monitor_test.go
server/nkey_test.go
server/norace_test.go
server/reload_test.go
server/server_test.go
server/split_test.go
test/client_cluster_test.go
test/gosrv_test.go
test/leafnode_test.go
test/new_routes_test.go
test/norace_test.go
test/operator_test.go
test/service_latency_test.go
test/system_services_test.go
test/tls_test.go

Updated all tests that use "async" clients.
- start the writeLoop (this is in preparation for changes in the
server that will not do send-in-place for some protocols, such
as PING, etc..)
- Added missing defers in several tests
- fixed an issue in client.go where test was wrong possibly causing
a panic.
- Had to skip a test for now since it would fail without server code
change.
The next step will be ensure that all protocols are sent through
the writeLoop and that the data is properly flushed on close (important
for -ERR for instance).

Refactor async client tests

---

docker/Dockerfile.alpine

Wondering if we should move to root as well to work better with some of the new tools?

Update to 3.10 and go 1.12

---

server/accounts.go
server/accounts_test.go
server/client.go
server/errors.go

Previously though this would work with different prefixes but that did not even work. This allows any number of imports on the same subject as needed.

Should allow multiple stream imports on same subject.

---

server/accounts.go
server/jetstream.go
server/observable.go
server/store.go

A quick spike on the idea I mentioned of sampling ack times in observables

support sampling time to ack messages in explicit ack mode

---

server/accounts.go
server/jwt_test.go
server/reload.go
server/server.go

On config reload, the URL account resolver was recreated and a
Fetch() with empty account was done. Move the empty fetch test
in NewServer() instead.
Added a test that shows that fetch is no longer invoked on reload
but server reports failure on startup.
Resolves #1229

[FIXED] Do not check URL account resolver reachability on reload

---

logger/syslog_test.go
server/accounts_test.go
server/client.go
server/client_test.go
server/events_test.go
server/gateway.go
server/gateway_test.go
server/jwt_test.go
server/leafnode.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go
test/leafnode_test.go
test/new_routes_test.go
test/tls_test.go

- All writes will now be done by the writeLoop, unless when the
writeLoop has not been started yet (likely in connection init).
- Slow consumers for non CLIENT connections will be reported but
not failed. The idea is that routes, gateway, etc.. connections
should stay connected as much as possible. However if a flush
operation times out and no data at all has been written, the
connection will be closed (regardless of type).
- Slow consumers due to max pending is only for CLIENT connections.
This allows sending of SUBs through routes, etc.. to not have
to be chunked.
- The backpressure to CLIENT connections is increased (up to 1sec)
based on the sub's connection pending bytes level.
- Connection is flushed on close from the writeLoop as to not block
the "fast path".
Some tests have been …

[UPDATED] TCP Write and SlowConsumer handling

---

server/client.go
server/gateway.go
server/gateway_test.go
test/client_cluster_test.go

When an account is switched to interest-only mode due to no interest,
it was not possible to switch that account more than once. But the
function switchAccountToInterestMode() that triggers a switch could
possibly doing it more than once. This should not cause problems
but increased the number of traces in a big super cluster.
Also fixed some flappers and a data race.

[FIXED] More than expected switch to Interest-Only mode for account

---

server/client.go
server/client_test.go
test/routes_test.go

This related to PR #1233.
The computation of the time to stall a fast producer was bogus. Fixed
that and added a unit test for the function computing this stalled
duration.
Also, in PR #1233, I had removed Gosched() when a call to flushOutbound()
realizes that the flag is already set. It was forgetting that readLoop
in some cases will call flushOutbound() in place. So there is still
value in unlock/gosched/lock again in that function.

Fixed client stalled duration computation and added back Gosched()

---

server/client.go

Also make the wait bound to 3secs after which writeLoop will attempt
to flush. Will log if it timed out on the wait and entering with
fsp > 0. Limit the report to once every 10 minutes

Replace sync.Cond with go channel for writeLoop notification

---

server/jetstream.go
test/jetstream_test.go

I anticipate it would be desirable to allow a microservice running
in an account to create only the stream it needs when it starts up
if there is no stream but no others, so a ACL would be written to
allow that.
Thus adding the T pattern to stream create too.

add stream name to create subject

---

server/consumer.go
server/jetstream.go

This is a proposal to add schema, timestamps and unique ids to
events.  For now just JS ones but I propose to do these for all
events the server sends that might be end user consumed.
These exist to help the user identify a message even if it was
sent to a 3rd party system, the schema will be translatable to
a well known url like https://nats.io/schames/jetstream/event/v1/obs_ack.json
or to another wll known identifier like a NATS subject name
We'd publish JSON schema documents at these well known locations
describing each key and so forth

proposed schemas for events

---

docker/Dockerfile.alpine

We require go 1.12 now at least, so this just bumps things up a bit.

update to go 1.12 and latest alpine

---

server/consumer.go
server/jetstream_api.go

Use the same key name for time in all events
Use the same format in all events
RFC3339 is the standard for this stuff and
for sure it should all be in UTC rather than
local time

consistent timestamps in events

---

server/client.go
server/client_test.go

When the server logs information related to a connection, it uses
the connection IP and remote port as a prefix. When it was an IPv6
address, the square brackets would be missing.

[FIXED] Display of connections address when using IPv6

---

server/gateway.go
server/leafnode.go
test/gateway_test.go
test/leafnode_test.go

For issue #1256, we cleared the possibly saved tlsName on Hanshake failure.
However, this meant that for normal use cases, if a reconnect failed for
any reason we would not be able to reconnect if it is an IP until we get
back to the URL that contained the hostname.
We now clear only if the handshake error is of x509.HostnameError type,
which include errors such as:
```
"x509: Common Name is not a valid hostname: <x>"
"x509: cannot validate certificate for <x> because it doesn't contain any IP SANs"
"x509: certificate is not valid for any names, but wanted to match <x>"
"x509: certificate is valid for <x>, not <y>"
```
Applied the same logic to solicited gateway connections, and fixed the fact
that the tlsConfig should be cloned (since we set the ServerName).
I have also made a change for …

[FIXED] Reset of tlsName only for x509.HostnameError

---

server/sublist.go

Without this nats-req '$JS.TEMPLATE..DELETE' '' causes a panic

handles 0 length tokens correctly

---

server/client.go
server/errors.go
server/leafnode.go
server/leafnode_test.go

Currently when a NATS Server connects to a leafnode to the client port, the connection is established successfully and remains connected until the first message is sent.
For example given this config:
```hcl
leafnodes {
remotes = [
{
url = "nats://connect.ngs.global:4222"
credentials = "~/.nkeys/creds/synadia/NGS/NGS.creds"
}
]
}
```
The server will remain connected, with ping/pong working ok:
```
2020/01/28 12:52:16.468011 [INF] Starting nats-server version 2.1.3-RC05
2020/01/28 12:52:16.468129 [DBG] Go build version go1.13.3
2020/01/28 12:52:16.468134 [INF] Git commit [not set]
2020/01/28 12:52:16.468479 [INF] Listening for client connections on 0.0.0.0:4222
2020/01/28 12:52:16.468496 [INF] Server id is NC2IUWWQCR7OYW6ONQAFQINLKCDWJ6BXGAL52L5JLDZHWJGVIMFXMA72
2020/01/28 12:52:16.468503 …
```

Add check to prevent leafnode connecting to client port

---

server/jwt_test.go
server/opts.go
server/reload.go
server/reload_test.go
server/server.go

A new config section allows to specify specific TLS parameters for
the account resolver:
```
resolver_tls {
cert_file: ...
key_file: ...
ca_file: ...
}
```
Resolves #1271

[ADDED] Ability to specify TLS configuration for account resolver

---

server/configs/test.conf
server/opts.go
server/opts_test.go
server/reload_test.go

took code of write_deadline and moved it into separate function.
added tests. 
changed tests.conf to not produce the warning as to not throw off other tests.

parse ping_interval as duration, else assume seconds and warn

---

server/parser.go

Use constant for error

---

server/events_test.go

Fixed improper field pass to Fatalf()

---

server/events.go
server/monitor.go
server/server.go

I know we're not really sure how to show all the per account stuff, but I figured some basic varz/event info would be helpful

show basic jetstream info in varz and server info

---

server/client.go
server/server.go

This can be used when a NATS client application wants to know its public IP, or at least the server's version of the client IP.

Place server's version of client IP in INFO

---

main.go
server/client.go
server/events.go
server/log.go
server/opts.go
server/server.go

Use sys_trace option in config file or --sys_trace on the command line
I made this non reloadable as this affects clients and reload does not alter existing clients.
(Will address this in a separate PR)

Adding option to enable tracing the system account. (default: false)

---

server/client.go
server/client_test.go
server/log_test.go
server/server.go
test/test.go

Increment the ping counter so they remain subject to the overall timeout.
This does not affect pings sent to directly obtain RTT.
These seem to be generally called when the connect message has been received already.
To keep this change small I refrained from altering that logic.
server
[49483] 2020/02/27 14:05:10.184185 [DBG] 127.0.0.1:50612 - cid:1 - Client connection created
[49483] 2020/02/27 14:05:12.496584 [DBG] 127.0.0.1:50612 - cid:1 - Client Ping Timer
[49483] 2020/02/27 14:05:12.496654 [DBG] 127.0.0.1:50612 - cid:1 - Faking PING until connect message, timeout in 2 intervals false
[49483] 2020/02/27 14:07:12.498158 [DBG] 127.0.0.1:50612 - cid:1 - Client Ping Timer
[49483] 2020/02/27 14:07:12.498200 [DBG] 127.0.0.1:50612 - cid:1 - Faking PING until connect message, timeout in 1 …

Do not send ping to presumed telnet clients until they connected/send ping

---

server/opts.go

Fixes #1290, where -DV option was skipped when config file had a warning

[FIXED] configuration warnings do not cause cmd line options to be skipped

---

server/client.go
server/client_test.go

Added a test that demonstrates the issue and a proposed fix.
Also fixed the incorrect increment of c.out.pb when going over
MaxPending.

[FIXED] Incorrect buffer reuse in case of partial connection write

---

test/leafnode_test.go

Ran into a low ulimit when running tests manually.

Modifying unit test error message to hint at ulimit -n possibly being too low

---

server/leafnode.go

Sample output
[62401] 2020/03/06 15:15:55.433837 [INF] Starting nats-server version 2.1.4
[62401] 2020/03/06 15:15:55.434100 [INF] Git commit [not set]
[62401] 2020/03/06 15:15:55.434932 [INF] Listening for client connections on 127.0.0.1:5222
[62401] 2020/03/06 15:15:55.435001 [INF] Server id is ND7OUS...HSLES
[62401] 2020/03/06 15:15:55.435024 [INF] Server is ready
[62401] 2020/03/06 15:15:55.435320 [ERR] Error trying to connect as leafnode to remote server "127.0.0.1:6223" (attempt 1): dial tcp 127.0.0.1:6223: connect: connection refused
[62401] 2020/03/06 15:15:55.436832 [INF] Connected leafnode to "127.0.0.1:4223"
[62401] 2020/03/06 15:15:59.449039 [INF] Connected leafnode to "127.0.0.1:6223"

[CHANGED] Include port in "Connected leafnode" log statement

---

server/monitor.go

Sample output of  /varz
{
...
"cores": 16,
"gomaxprocs": 16,
...
},
"config_load_time": "2020-03-06T13:55:53.816454-05:00"
}

[ADDED] Value of GOMAXPROCS in /varz monitoring output

---

server/client.go
server/events.go
server/gateway.go
server/leafnode.go
server/log.go
server/parser.go
server/parser_test.go
server/reload.go
server/reload_test.go
server/route.go
server/server.go

Fixed #1296, by altering client state on reload
Detect a trace level change on reload and update all clients.
To avoid data races, read client.trace while holding the lock,
pass the value into functions that trace while not holding the lock.
Delete unused client.debug.
Taking to @kozlovic, we had no strong opinions for/against holding the server lock while updating clients.

[FIXED] trace/debug/sys_log reload will affect existing clients

---

server/server_test.go

When no tag was set, os.Getenv("TRAVIS_TAG") would return empty string.
Travis now set TRAVIS_TAG to `''`. So check for both.

Fixed TestVersionMatchesTag test

---

server/parser.go

The trace in question was not there prior to tracing change.
Fixes #1310, by removing it.
The original had a tracing argument in processPub, processLeafMsgArgs and processRoutedMsgArgs passed in false. When moving tracing to the caller I ended up adding tracing. 
Somehow Wally was able to produce the issue on this box with telnet. I never could. 

Remove double trace on split buffer

---

server/accounts.go
server/client.go
server/monitor.go
server/reload.go

Fixes #1314 by:
There was a data race with a write during reloadAuthorization.
Locking was added to all places where it was missing.
In situations were it appeared feasible, access was moved into existing
lock/unlock.
Where it was added, the lock order was already established.

Make sure server lock is held while accessing server.gacc

---

server/accounts.go
server/events_test.go
server/leafnode.go
server/leafnode_test.go
test/leafnode_test.go

This is in addition to checking if the own subscription comes back.
The duplicated lds subscription must come from a different client.
Added unit tests. 
Fixes #1305
Test output in a test where I configued a loop as follows:
A
B->A
C->B
D->C <--- this remote is wrong.
D->A <--- OR this remote is wrong
Server D will detect the error.
This holds true even if it is not the server closing the loop. 
If all server but Server B are running, starting server B will result in Server D detecting the loop and  close one of its connections. Which connection C/A is closed depends on timing, which one of the two connections is last to send the loop detection subscription for A to D.
nats-server -c cfg/daisyC.cfg
[11014] 2020/03/09 15:23:57.998901 [INF] Starting nats-server version 2.1.4
[11014] …

[FIXED] loop detection by checking for duplicate lds subscriptions

---

server/monitor.go
server/monitor_test.go
server/ring.go
server/server.go

added sub=detail option to routez/connz. 
When specified will include subscriptions_list_detail instead.
I would have liked to change the type of subscriptions_list from []string to []interface{} and not have subscriptions_list_detail, but that is part of the interface used by embedded server.
Applies to routez and connz and closed connections.
with detail                 
```                                                                                                                                                                                                                                                                                         >curl "http://localhost:8080/connz?subs=detail"
{
"server_id": "NDVNBYWHR7OZFDDVLNAHFK5PLRTBLENHSNMRV5WBSFAF6W3E67PCLC6A",
"now": …
```

[ADDED] Option to include subscription details in monitoring responses

---

server/consumer.go

Handy to be able to look at the JSON out of context from where it was created and know what stream it relates to.
Not urgent at all.

add the stream name in consumer info

---

server/client.go
server/leafnode.go
server/leafnode_test.go
server/opts.go

This allows a node that creates a remote LeafNode connection to
act as it was the hub (of the hub and spoke topology). This is
related to subscription interest propagation. Normally, a spoke
(the one creating the remote LN connection) will forward only
its local subscriptions and when receiving subscription interest
would not try to forward to local cluster and/or gateways.
If a remote has the Hub boolean set to true, even though the
node is the one creating the remote LN connection, it will behave
as if it was accepting that connection.

[ADDED] Leafnode remote's Hub option

---

server/accounts.go
server/events.go
server/gateway.go
server/server.go
test/leafnode_test.go
test/service_latency_test.go

This is needed to put those accounts into interest only mode for inbound gateway connections. Also added code to make sure we were doing proper account tracking and would track the global account as well, which used to be excluded.
Fixes #977

This commit allows new servers in a supercluster to be informed of accounts with leafnodes.

---

server/accounts.go
server/events_test.go
server/leafnode.go
server/leafnode_test.go
server/monitor_test.go
test/leafnode_test.go

We need to send the unique LDS subject to all leafnodes to properly detect setups like triangles.
This will have the server who completes the loop be the one that detects the error solely based on
its own loop detection subject.
Otehr changes are just to fix tests that were not waiting for the new LDS sub.

Detection for loops with leafnodes.

---

server/client.go
server/events_test.go
server/leafnode.go
server/leafnode_test.go
server/opts.go

This will allow a leafnode remote connection to prevent unwanted
messages to be received, or prevent local messages to be sent
to the remote server.
Configuration will be something like:
```
leafnodes {
remotes: [
{
url: "nats://localhost:6222"
deny_imports: ["foo.*", "bar"]
deny_exports: ["baz.*", "bat"]
}
]
}
```

[ADDED] Deny import/export options for LeafNode remote configuration

---

server/accounts.go
server/leafnode.go
test/leafnode_test.go

When a responder was on a leaf node and the requestor was connected to the same server as the leafnode we did not propagate the service reply wildcard properly. This fixes that.

Fix for bug when requestor and leafnode on same server.

---

server/client.go
test/leafnode_test.go

Fix for stream imports and leafnodes, fixes #1332

---

server/client.go
server/leafnode.go
server/leafnode_test.go

If the loop is detected by a server accepting the leafnode connection,
an error is sent back and connection is closed.
This change ensures that the server checks an -ERR for "Loop detected"
and then set the connect delay, so that it does not try to reconnect
right away.

LeafNode: delay connect even when loop detected by accepting side

---

server/leafnode.go
test/leafnode_test.go

[FIXED] Service across accounts and leaf nodes

---

server/events.go
server/leafnode.go
server/leafnode_test.go

Changing the role of a leafnode to a hub even when soliciting caused some interest propagation to fail. This commit allows the role to be sent to the receiving server so it can update its role as well.

Fix gateway and leafnode hubs in interest propagation

---

server/leafnode.go
test/leafnode_test.go

When an account had a pre-existing siReply wildcard and a leafnode restarted this subscription was not being properly sent to the new leafnode connection.
Resolves #1344 
/cc nats-io/core

Fix for #1344

---

server/client.go
server/client_test.go

This gives the close reason directly in the log without having to
get that information from the monitoring endpoint. Here is an
example of a route closed due to the remote side not replying to
PINGs:
```
[INF] 127.0.0.1:53839 - rid:2 - Router connection closed: Stale Connection
```
Without this change, the log statement would have been:
```
[INF] 127.0.0.1:53839 - rid:2 - Router connection closed
```

[IMPROVED] Added close reason in the connection close log statement

---

server/consumer.go
server/events.go
server/events_test.go
server/jetstream_api.go
server/server.go

This bring these to same level as the JS events, these are the ones
I care for right now but will do this to the rest here in time as well
and document them in JSON schema

add schema, id and time to client connect events

---

server/accounts.go
server/accounts_test.go
server/client.go
server/const.go
server/events.go
server/gateway.go
server/gateway_test.go
server/jwt_test.go
server/leafnode.go
server/monitor.go
server/opts.go
server/reload.go
server/route.go
server/server.go
server/sublist.go
test/leafnode_test.go
test/new_routes_test.go
test/service_latency_test.go
test/services_test.go

This contains a rewrite to the services layer for exporting and importing. The code this merges to already had a first significant rewrite that moved from special interest processing to plain subscriptions.
This code changes the prior version's dealing with reverse mapping which was based mostly on thresholds and manual pruning, with some sporadic timer usage. This version uses the jetstream branch's code that understands interest and failed deliveries. So this code is much more tuned to reacting to interest changes. It also removes thresholds and goes only by interest changes or expirations based around a new service export property, response thresholds. This allows a service provider to provide semantics on how long a response should take at a maximum.
This commit also introduces formal …

Services rewrite #2

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/defect.md
.github/ISSUE_TEMPLATE/feature_request.md

This allows users to select a specific type of issue that they want to report, rather than using the same template to choose either a defect or feature request. A similar change was just merged into the Rust client. When you click "Open Issue", users are presented with [this menu](https://github.com/nats-io/nats.rs/issues/new/choose) before taking them to a specialized issue template. This reduces friction for reporters as they can spend less work reading and cutting irrelevant parts of the template.
This also automatically assigns the bug and enhancement labels to relevant issues opened through this form, and it also provides an "escape hatch" for users to skip the template with a blank issue if they feel the choices are inappropriate for the information that they wish to convey. …

Use split GitHub issue templates

---

server/consumer.go
server/jetstream.go
server/jetstream_api.go
test/jetstream_test.go

Removed usage of +OK and -ERR. All responses are valid json objects now and optionally can include an ApiError which will have Code and Description.

Redesign message-based API

---

doc/adr/0001-jetstream-json-api-design.md
server/jetstream_api.go
test/jetstream_test.go

Also standardise some names of response structures and create
reusable types that can be included into others to construct
our standard API requests and responses.
Fixes some json tags.
Updates the design document of the JSON responses to reflect
the implementation that was done

adds API type hints to responses

---

server/auth.go
server/opts.go
server/opts_test.go
server/server.go

Added a no_auth_user as discussed.
To simplify error checking, I decided to do a post parsing error pass.
Reason being, we have multiple sections where users can be configured (multiple accounts as well authorization block). 

Add a no_auth_user

---

server/monitor.go
server/monitor_test.go
server/sublist.go

Fixes  #1371 and #1357 by adding up stats and collecting subscriptions
from all accounts.
I will add selecting individual accounts in a separate PR as this has to happen for more than one endpoint.

[FIXED] subsz monitoring endpoint did not account for accounts.

---

server/reload.go
server/reload_test.go
server/server.go

Fixes #1378 by calling validateOptions on reload
Add missing comment to validateOptions

[FIXED] on reload, check error conditions checked in validateOptions

---

server/events.go
server/events_test.go
server/monitor.go

I am exposing these as there should not be two different code paths and that enhancements to one are available in the other as well.
I'm also establishing this as the pattern so that we can inspect server state via http as well as nats.
Available via $SYS.REQ.SERVER.%s.%s and $SYS.REQ.SERVER.PING.%s
Last token is the endpoint name.
Since this is in system events I went for less code and thus use of closures over avoiding them
This can change if you  want to.
Input can be empty or a json of the corresponding options.
return always includes server. error and data are mutually exclusive. 
I can rename data to smth. more specific (connz/subsz/...) as well.
connz and subz have a limit option. Limit and offset are honored by this.
We can consider adding code to return a chunked response.
But I …

[ADDED] Making monitoring endpoints available via system services.

---

server/client_test.go
server/server.go

If the connection is marked as closed while sending the INFO, the
connection would not be removed from the internal map, which would
cause it to be shown in the monitoring list of opened connections.
Resolves #1384

[FIXED] Early closed connection may linger in the server

---

server/client.go
server/client_test.go
server/const.go
server/errors.go
server/monitor.go
server/opts.go
server/parser.go
server/parser_test.go
server/server.go

This is first pass header support in the server. This introduces a new client protocol HPUB and bidirectional agreement between server and client on abilities using the header feature flag both in INFO and CONNECT.
Next pass will add in HMSG and complete propagation through the server with ability to strip headers for older clients.

Header support

---

server/accounts.go
server/events.go
server/events_test.go
server/reload.go
server/reload_test.go
server/server.go

Fixes #1372 by updating s.sys.account pointer.
This issue also showed that accounts are unnecessarily reloaded.
This happened because account imports were not copied and thus,
deepEqual detected a difference were none was.
This was addressed by making the copy less shallow.
Furthermore did deepEqual detects a difference when it compared 
slices that were appended to while processing a map.
This was fixed by sorting before comparison.
Noticed that Account.clients stored an unnecessary pointer.
Removed duplicated code in systemAccount.
I did not outright eliminate sys.account pointer as we do not necessarily always have a name that is specified.

[FIXED] Unnecessary account reloads

---

server/reload.go
server/server.go

This does not avoid the race condition, but makes it less likely to trigger in unit tests.

Move reset of internal client to after the account sublist was moved.

---

main.go
server/configs/test.conf
server/const.go
server/monitor.go
server/monitor_test.go
server/opts.go
server/opts_test.go
server/server.go

Resolves #
- Add flag `http_base_path` to be able to access nats monitoring endpoint behind a proxy (e.g. nginx) 

[ADDED] base path for monitoring endpoints

---

server/client.go
server/client_test.go
server/gateway_test.go
server/monitor.go
server/opts.go
server/reload.go
server/route.go
server/server.go
server/util.go
server/websocket.go
server/websocket_test.go
test/ports_test.go

Websocket support can be enabled with a new websocket
configuration block:
```
websocket {
tls {
cert_file: "/path/to/cert.pem"
key_file: "/path/to/key.pem"
}
}
```

[ADDED] Websocket support

---

server/auth.go
server/jwt_test.go

This relaxes the nonce signing checks when a bearer token is provided. PR is a preview and depends on JWT changes.

[ADDED] Support for JWT BearerToken

---

.github/workflows/go-test.yaml
README.md

Adds basic GH Workflow that runs tests on push and pr, coverage
is disabled.
The intention is to soft switch to GH Actions by just letting them
run next to travs for a while to get a feel for things

initial gh actions

---

server/consumer.go
server/events.go
server/jetstream_api.go
server/jetstream_events.go
server/stream.go

We now publish advisories when streams and consumers are added,
deleted and modified
Also rework how TypedEvents are created to be easier to use

create advisories for stream and consumer add/delete/modify

---

server/jetstream_events.go
server/stream.go

On reflection I think this is a bad idea,
it's enough to know there was a change we
do not need to expose this to potential 3rd
parties
Also since advisories are versioned but
configuration is not, this is awkward.

removes the configuration from advisories

---

server/gateway.go
server/gateway_test.go
test/leafnode_test.go

Say server in cluster A accepts a connection from a server in
cluster B.
The gateway is implicit, in that A does not have a configured
remote gateway to B.
Then the server in B is shutdown, which A detects and initiate
a single reconnect attempt (since it is implicit and if the
reconnect retries is not set).
While this happens, a new server in B is restarted and connects
to A. If that happens before the initial reconnect attempt
failed, A will register that new inbound and do not attempt to
solicit because it has already a remote entry for gateway B.
At this point when the reconnect to old server B fails, then
the remote GW entry is removed, and A will not create an outbound
connection to the new B server.
We fix that by checking if there is a registered inbound when
we get to the point …

[FIXED] Race condition during implicit Gateway reconnection

---

server/auth.go
server/jetstream.go
server/opts.go
server/server.go
test/jetstream_test.go

Also warn when accounts configured but JetStream is not enabled.

Don't allow JetStream on system account. 

---

server/client.go
server/client_test.go
server/route.go
server/server.go
server/server_test.go

Also send an INFO to routes so that the remotes can remove the
LDM's server client URLs and notify their own clients of this
change.

[FIXED] LameDuckMode sends INFO to clients

---

server/auth.go

- Support all bcrypt versions, see https://en.wikipedia.org/wiki/Bcrypt#Versioning_history

Support all bcrypt versions

---

server/accounts.go
server/client.go
server/filestore.go
server/filestore_test.go
server/jetstream.go
server/jetstream_api.go
server/memstore.go
server/store.go
server/stream.go
test/jetstream_test.go

We now support snapshots and restores for JetStream streams.
Snapshots are gzipped tar files of the file store directory for a stream.
This tries to protect the server and stream data and not bloat the server.

JetStream Snapshots

---

server/consumer.go
server/jetstream_api.go
server/jetstream_events.go
test/jetstream_test.go

Allow a message to be terminated for delivery. Will send advisory.
https://github.com/nats-io/jetstream/issues/189

Add in a terminate delivery

---

server/client.go
server/server_test.go
test/leafnode_test.go

Server was incorrectly processing a queue subscription removal
as both a plain sub and queue sub, which may have resulted in
drop of interest even when some queue subs remained.
Resolves #1421

[FIXED] Possible removal of interest on queue subs with leaf nodes

---

go.mod
server/accounts.go
server/events_test.go

When a remote update is delayed and local connections are being made we could discover we have exceeded our maximum after the fact. Close new connections here if an update from a remote server shows we are over.

Close connections when a remote update exceeds maximum

---

go.mod
server/consumer.go

Since consumers use the stream's internal sendq and that can fill up we need to make sure we do not hold the consumer lock across a send. We avoided this for normal message sends, this adds advisories.

Avoid deadlock by releasing consumer lock.

---

server/auth.go

- Check bcrypt '$' prefix before performing regex on password

First check bcrypt '$' prefix before performing rexeg on password

---

server/filestore.go
server/filestore_test.go
server/jetstream_api.go
test/jetstream_test.go

First design was very conservative. This one increase performance for API based snapshots by > 10x. We use a fixed window that is below all spike buffers in nats-servers. We track outstanding bytes and do accounting via the ack reply subject.

Snapshot performance tweaks

---

server/filestore_test.go
server/leafnode_test.go
server/monitor_test.go
server/server_test.go

- A race test may have consumed a lot of fds going in TIME_WAIT
that could cause some issues for other tests
- Missing defer filestore.Stop() that would leave flushLoop()
routines
- A defer for the from server in a LeafNode test
- Rework [Re]ConnectErrorReports that was failing often for me
locally (probably due to exhaustion of fds - too many TIME_WAIT).

Fixed some tests

---

server/log.go
server/log_test.go

When the logfile_size_limit option is specified, the logfile will
be automatically rotated. However, if user still sends the re-open
signal (SIGUSR1), the log file will then no longer apply the
size limit.

[FIXED] Log file size limit not honored after re-open signal

---

server/parser_test.go
server/util.go
test/maxpayload_test.go

Fixes https://www.twistlock.com/labs-blog/finding-dos-vulnerability-nats-go-fuzz-cve-2019-13126/

Avoid parsing large sizes for messages

---

server/consumer.go
test/jetstream_test.go

All this information is included in the reply subject. This is penalizing for small messages.
Thought is later as we add in client support we could lift these into headers inside the client.

Remove JS headers for now, find better way to deliver in client

---

server/reload_test.go

Buffering the channel and calling t.Helper()

Fix flapper by making the channel buffered

---

server/server.go
server/server_test.go
server/websocket.go
server/websocket_test.go

This is related to #1408.
Make sure that we close the websocket "accept loop" if configured
before proceeding with the lame duck mode.

LameDuckMode takes into account websocket accept loop

---

server/client.go

In master, this this what happens when a connection is closed
and server runs with `-D`
```
[95023] 2020/06/03 14:55:28.395532 [DBG] 127.0.0.1:54077 - cid:2 - Client connection created
[95023] 2020/06/03 14:55:29.164118 [DBG] 127.0.0.1:54077 - cid:2 - Client connection closed: Client Closed
[95023] 2020/06/03 14:55:29.164191 [DBG] 127.0.0.1:54077 - cid:2 - Client connection closed
```
Notice the trace of connection closed with the reason, and then
the bare connection closed statement.
This double trace was introduced by mistake during the JS branch
work (https://github.com/nats-io/nats-server/commit/dd116fcfd4ecada200bd4dc8c7b72d213d549ece#diff-853eb184ac73cf9597d7833f6b89e9c9R3547)

Removed double connection close trace

---

server/accounts.go
server/jetstream_api.go
test/jetstream_test.go

This also introduces the ability to have flow control inbound for restoring a stream.
If the system detects a reply subject it will respond with a nil payload.
For the last EOF message if a reply is present it will respond with a stream info response or error.

Snapshot restore now works across leafnodes.

---

.github/workflows/nightly.yaml
.goreleaser-night.yml
docker/Dockerfile.nightly

Adds a nightly build as `synadia/nats-server:nightly` and `synadia/nats-server:nightly-yyyymmdd`

add nightly docker build workflows

---

server/client.go
server/leafnode.go
test/norace_test.go

There is a race between the time the processing of a subscription
and the init/send of subscriptions when accepting a leaf node
connection that may cause internally a subscription's subject
to be counted many times, which would then prevent the send of
an LS- when the subscription's interest goes away.
Imagine this sequence of events, each side represents a "thread"
of execution:
```
client readLoop                         leaf node readLoop
----------------------------------------------------------
recv SUB foo 1
sub added to account's sublist
recv CONNECT
auth, added to acc.
updateSmap
smap["foo"]++ -> 1
no LS+ because !allSubsSent
init smap
finds sub in acc sl
smap["foo"]++ -> 2
sends LS+ foo
allSubsSent == true
recv UNSUB 1
updateSmap
smap["foo"]-- -> 1
no LS- because count != 0 …
```

[FIXED] Unsubscribe may not be propagated through a leaf node

---

server/auth.go
server/leafnode_test.go
server/server.go
server/websocket.go
server/websocket_test.go

We added authentication override block for websocket configuration
in PR #1463 and #1465 which somehow introduced a drop in perf as
reported by the bench tests.
This PR refactors a bit to restore the performance numbers.
This change also fixes the override behavior for websocket auth:
- If websocket's NoAuthUser is configured, the websocket's auth
block MUST define Users, and the user be present.
- If there is any override (username/pwd,token,etc..) then the
whole block config will be used when authenticating a websocket
client, which means that if websocket NoAuthUser is empty we
are not falling back to the regular client's NoAuthUser config.
- TLSMap always override the regular client's config. That is,
whatever TLSMap value specified in the websocket's tls{} block
will be used.
The …

[FIXED] LeafNode TLSMap and websocket auth override

---

server/gateway_test.go
server/server.go
server/server_test.go

[ADDED] Print the config file being used in startup banner

---

server/leafnode.go
server/leafnode_test.go
test/leafnode_test.go

This was found due to a recent test that was flapping. The test
was not checking the correct server for leafnode connection, but
that uncovered the following bug:
When a leafnode connection is solicited, the read/write loops are
started. Then, the connection lock is released and several
functions invoked to register the connection with an account and
add to the connection leafs map.
The problem is that the readloop (for instance) could get a read
error and close the connection *before* the above said code
executes, which would lead to a connection incorrectly registered.
This could be fixed either by delaying the start of read/write loops
after the registration is done, or like in this PR, check the
connection close status after registration, and if closed, manually
undoing the …

[FIXED] LeafNode solicit failure race could leave conn registered

---

server/client.go
server/client_test.go
server/errors.go

Allow support for a empty response message when no responders are present.
This will also set a response status of 503 with the new header support.

Allow support for no responders nil response message.

---

server/auth.go
server/client.go
server/leafnode.go
server/leafnode_test.go
test/cluster_test.go
test/leafnode_test.go

When a leafnode would connect with credentials that had permissions the spoke did not have a way of knowing what those were. This could lead to being disconnected when sending subscriptions or messages to the hub which were not allowed.

Properly handle leafnode spoke permissions.

---

server/events.go
server/events_test.go
server/monitor.go
server/monitor_test.go
server/server.go

Issue reset after cluster name changed. 
Add filtering by name and cluster to system events.
empty cluster name
```
nats -s localhost:4141 --creds=$NATS_ADMIN_CREDS  req "\$SYS.REQ.SERVER.PING.VARZ" "{\"cluster\":\"\",\"subscriptions\":true}"
15:30:43 Sending request on [$SYS.REQ.SERVER.PING.VARZ]
15:30:43 Received on [_INBOX.SMi3XB4JfXyrhLMLK60lt2]: '{
"data": {
"server_id": "NBZEZ5V6J7N6MXVZPH7VOHFGW46NUMSJYXEDKZSBA5Y3USF4Z5J7SX74",
"server_name": "NBZEZ5V6J7N6MXVZPH7VOHFGW46NUMSJYXEDKZSBA5Y3USF4Z5J7SX74",
"version": "2.2.0-beta.15",
"proto": 1,
"go": "go1.14.1",
"host": "localhost",
"port": 4141,
"auth_required": true,
"max_connections": 65536,
"ping_interval": 120000000000,
"ping_max": 2,
"http_host": "localhost",
"http_port": 0,
"http_base_path": "",
"https_port": 0,
"auth_timeout": …
```

Add filtering by name and cluster to PING events

---

server/client.go
server/opts.go
server/websocket.go
server/websocket_test.go

When authenticating via browser, the best security practice is to use HttpOnly cookies, to avoid scripts stealing client identity via XSS.
HttpOnly cookies can't be accessed by JavaScript, making those perfect for server-certified authentication.
PR implements optional JWT auth using cookies by specifying this option in a config file:
`ws: { jwt_cookie: "cookie_name" }`
This will make NATS treat a cookie named "cookie_name" as JWT for authentication. If this cookie exists in the HTTP request and is valid, the server will act as if authentication is not required. If this token is missing or invalid, it's possible to authenticate using other configured methods.
Notice that since signing is not possible when authorizing this way, BearerToken should be set in the JWT (e.g. User should be …

[ADDED] Cookie JWT auth for WebSocket

---

server/accounts.go
server/client.go
server/const.go
server/leafnode.go
server/leafnode_test.go
server/monitor.go
server/parser.go
server/route.go
server/server.go
test/leafnode_test.go
test/new_routes_test.go
test/test.go

Leafnodes that formed clusters were partially supported. This adds proper support for origin cluster, subscription suppression and data message no echo for the origin cluster.
Meaning we can now have a leafnode cluster that can transparently send through a hub (i.e. NGS) and to each other.

Properly support leadnode clusters.

---

server/client.go

Fix for duplicate delivery into a hub, was checking wrong client for hub status.

Track destination leafnode status

---

server/client_test.go
server/server_test.go

Fixed some flappers

---

server/gateway.go
server/gateway_test.go
server/leafnode.go
server/route.go
server/routes_test.go
server/server.go
server/server_test.go
server/websocket.go

This was discovered with the test TestLeafNodeWithGatewaysServerRestart
that was sometimes failing. Investigation showed that when cluster B
was shutdown, one of the server on A that had a connection from B
that just broke tried to reconnect (as part of reconnect retries of
implicit gateways) to a server in B that was in the process of shuting down.
The connection had been accepted but createGateway not called because
the server's running boolean had been set to false as part of the shutdown.
However, the connection was not closed so the server on A had a valid
connection to a dead server from cluster B. When the B cluster (now single
server) was restarted and a LeafNode connection connected to it, then
the gateway from B to A was created, that server on A did not create outbound …

Fixed accept loops that could leave connections opened

---

server/client.go
test/new_routes_test.go

That is, if the server receives "SUB foo 1" more than once from
the same client, we would register in the client map this subscription
only once, and add to the account's sublist only once, however we
would have updated shadow subscriptions and route/gateway maps for
each SUB protocol, which would result in inability to send unsubscribe
to routes when the client goes away or unsubscribes.

[FIXED] Handling or real duplicate subscription

---

server/client.go
server/client_test.go

If an IPv6 address contains some "%" characters, this was causing
the connection name in log statement to mess up the Sprintf formatting.
The solution is to escape those "%" characters.
Resolves #1505

[FIXED] Connection name in log statement for some IPv6 addresses

---

server/consumer.go
server/stream.go
test/jetstream_test.go

This provides two mechanisms for exactly once.
1. Deduplication for messages that are published multiple times. We use headers to denote a Msg-Id per message. These are kept for a certain window of time.
2. When you ack a message that has been consumed you can receive an ack to your ack. If that ack is received you will not receive the message again.

Provide exactly once semantics

---

server/client.go
server/gateway.go
server/leafnode.go
server/route.go

The call sendProtoNow() should not normally be used (only when
setting up a connection when the writeloop is not yet started and
server needs to send something before being able to start the
writeLoop.
Instead, code should use enqueueProto(). For this particular
case though, use queueOutbound() directly and add to the
producer's pcd map.
Also fixed other places where we were using queueOutbound() +
flushSignal() which is what enqueueProto is doing.

Fixed no_responders use of sendProtoNow()

---

server/gateway.go
server/leafnode.go
server/route.go
server/server.go
server/server_test.go
server/util.go
server/websocket.go
test/gateway_test.go
test/leafnode_test.go

If some servers in the cluster have the same connect URLs (due
to the use of client advertise), then it would be possible to
have a server sends the connect_urls INFO update to clients with
missing URLs.
Resolves #1515

[FIXED] Handling of gossiped URLs

---

server/jetstream.go
test/jetstream_test.go

Previously unlimited accounts - ones who inherit server values - would
be unable to publish any messags at all

ensure unlimited account limits are calculated correctly

---

main.go
server/opts.go

This is handy for client libraries that start the server as
external executable and pass command line arguments. Without
specifying the cluster name, routes can take time to establish
and cause some tests to fail.

Added -cluster_name command line option

---

server/opts.go

Internally option for NoHeaderSupport was available, but no way to set it.

added 'no_header_support' config option mapping to NoHeaderSupport

---

server/jwt_test.go
server/server.go
test/operator_test.go

The check that an account has to be signed by a configured operator is
done after fetch as well. As a consequence an account claim will never
become an Account in memory.
The original check during client or leaf authentication is left in
place.
Adding unit tests.
Modifying existing tests to not rely on an account but it's name instead.
change in server.go is check for isTrustedIssuer. other change is removing one level of indentation.
changes in tests where the operator is explicitly added where done to provide the setup with the operator as isTrustedIssuer returns false when no key is specified.

Ensuring that an untrusted account is not held in memory

---

server/accounts.go
server/jwt_test.go
server/route.go
server/server.go

[Fixed] Skip fetch when a non config based account resolver is used
Resolves #1532
Instead of the fetched account we create a dummy account that is
expired. Any client connecting will trigger a fetch of the actual
account jwt.
This also avoids one fetch, thus the unit test was changed to reflect this.
Unlike other resolver the memory resolver does not depend on external
systems. It is purely based on server configuration. Therefore, fetch
can be done and not finding an account means there is a configuration issue.
Also  reduce usage of tmpAccounts to only location where it is needed imports
On import handle it with priority as in non recursive situations, it
won't be present.

[Fixed] Skip fetch when a non config based account resolver is used

---

server/consumer.go
server/jetstream.go
test/jetstream_test.go

allow max consumers to be set

---

server/opts.go
server/server_test.go
server/websocket.go

The new option Websocket.NoTLS would have to be set to true
to disable the server check that enforces TLS configuration.
Resolves #1529

Websocket: add option to disable TLS

---

server/leafnode.go
server/norace_test.go
server/route.go
server/routes_test.go
server/server.go

We cannot call c.closeConnection() under the server lock because
closeConnection() can invoke server lock in some cases.
Created a test that should run without `-race` to reproduce the deadlock
(which it does) but sometimes would fail because cluster would not be
formed. This unconvered an issue with conflict resolution which
test TestRouteClusterNameConflictBetweenStaticAndDynamic() can reproduce
easily. The issue was that we were not updating a dynamic name with
the remote if the remote was non dynamic.
Resolves #1543

[FIXED] Possible deadlock with solicited leafnodes when cluster conflict

---

server/client.go

When using a queue subscription with an internal client, this caused messages to be sent back.
Going with a check for remote sub seems to match the comment best.

Deliver to all non remote queue subscriber instead of kind == CLIENT

---

server/accounts.go
server/client.go
server/events.go
server/leafnode.go
server/route.go
server/server.go

This change allows the removal of the connection and update of
the server state to be done "in place" but still delay the flushing
of and close of tcp connection to the writeLoop. With ref counting
we ensure that the reconnect happens after the flushing but not
before the state has been updated.
Had to fix some places where we may have called closeConnection()
from under the server lock since it now would deadlock for sure.

Rework closeConnection()

---

server/accounts.go
server/accounts_test.go
server/client.go
server/errors.go
server/events.go
server/events_test.go
server/jetstream.go
server/norace_test.go
server/parser.go
server/reload_test.go
server/stream.go
test/jetstream_test.go
test/leafnode_test.go

Made changes to processSub() to accept a subscription which allows
the icb callback to be set prior to add the subscription to the
account's sublist, which prevent races.
Fixed some other racy conditions, notably in addServiceImportSub()

Fix sysSubscribe races

---

server/reload.go
server/reload_test.go

[FIXED] Deadlock on config reload with routes and account service import

---

server/gateway.go
server/gateway_test.go
server/leafnode.go
server/route.go
server/routes_test.go
server/server.go
server/util.go

Go 1.13 changed the semantics of the tuning parameters for TCP keepalives, including the default value.  This affects all TCP listeners.  The NATS protocol has its own L7 keepalive system (PING/PONG) and the Go defaults are not a good fit for some valid deployment scenarios, while Go doesn't directly expose a working API for tuning these.
Rather than add a configuration knob and pull in another dependency (with portability issues) just disable TCP keepalives for all listeners used for speaking the NATS protocol.
Change the tests so we test the same logic.  Do not change HTTP monitoring or the websocket API.
This addresses the same problem as Issue #1561 but does not resolve all of it, as we're not making this configurable.

Inhibit Go's default TCP keepalive settings for NATS

---

server/events.go
server/events_test.go

The dedicated struct contains filter options not used in monitoring
This change primarily exposes filtering as a combined struct with whatever options are taken

Create dedicated options struct for system events that invoke monitoring

---

server/auth.go
server/client.go
server/jwt.go
server/jwt_test.go

because times stored are hh:mm:ss it is possible to end up with start > end where end is actually the next day.
jwt.go line 189
Also, ranges are based on the servers location, not the clients.

[ADDED] Checks for CIDR blocks and connect time ranges specified in jwt

---

doc/adr/0003-distributed-tracing.md
server/accounts.go
server/accounts_test.go
server/client.go
server/opts.go
server/parser.go
test/service_latency_test.go

When latency is set to a percentage, headers are included as well.
Header sharing can be turned off by setting (import) sharing to false.
As of now config only has one new value, "headers" (see changes in test/service_latency_test.go)
Since some of the tracing systems make use of multiple header anyway I figured I inspect them all, instead of configuring a particular one. 
As a result I did not include the name of the tracing system (yet?).
Another difference is how headers are included. (array of values)
I also include them every time, even when sampling is set to 100%. (can change)
output sample:
```
{
"type": "io.nats.server.metric.v1.service_latency",
"id": "LnDl4oXc5MjOQsRSIO6GXc",
"timestamp": "2020-08-11T18:38:47.853862Z",
"status": …
```

Emit latency traces when sampling is set to headers

---

server/monitor.go

Minor fix for monitoring menu.
If we use nginx proxy for 8222 monitoring hosts. http://host:81/nats/node1/ urls in menu http://host:81/ like http://host:81/varz not http://host:81/nats/node1/varz

fix absolute url in monitoring menu

---

server/client.go
server/client_test.go
server/jwt_test.go

Addresses part of #1552  
While implementing this I noticed casts to int32, from int64 or int.
I intend to resolve this by altering jwtv2 to use int32 instead of int64.
Or would you increase the server side variables?

Adding user jwt payload and subscriber limits

---

server/client.go
server/jwt_test.go

RI ran into an issue where he submitted a user jwt even though the server was not set up in operator mode.
Subsequently values from the jwt got used.

Discard client provided jwt when not in operator mode

---

server/jwt.go

The value of d (line 185) was off as it was computed in local timezone then added to desired timezone.
This started to fail when Europe already had the next day.

Convert current time into time for locale before usage

---

server/accounts.go
server/jwt_test.go
server/server.go

This failure can be caused if the imported account can't be fetched or
is not up to date yet.
This change introduces a new account flag.
If this flag is set, perform the update and do NOT return ErrAccountResolverSameClaims.
Added two unit tests for both situations.
Shorten one unit test that was able to use the default operator.

[FIXED] Error when importing an account results in an error, retry later

---

.travis.yml
README.md
server/const.go

This is based on branch_2_1_x and includes the following fixes:
- Allow response permissions to work across accounts (#1487)
- Race condition during implicit Gateway reconnection (#1412)
- Possible stall on shutdown with leafnode setup (#1414)
- Possible removal of interest on queue subs with leaf nodes (#1424)
- Unsubscribe may not be propagated through a leaf node (#1455)
- LeafNode solicit failure race could leave conn registered (#1475)
- Handling or real duplicate subscription (#1507)
- Log file size limit not honored after re-open signal (#1438)
- Connection name in log statement for some IPv6 addresses (#1506)
- Better support for distinguishedNameMatch in TLS Auth (#1577)
- Error when importing an account results in an error (#1578)

Release 2.1.8

---

doc/adr/0004-nats-headers.md

clarifications on the ADR. Go is non-standard, and it's formatting
rules, create formatting dependencies that are not part of the spec.
Also added simplified guidance of allowed characters to help those
having to implement it.
[ci skip]

Header ADR clarifications

---

.goreleaser.yml

The zip/unzip commands aren't installed by default on most Linux
distros. However, tar is almost always installed. Additionally, users
may get confused when they try to uncompress an archive with
gzip/gunzip, only for it to fail because gunzip is for .gz files, not
.zip.
This change makes it a little easier to grab a copy of a nats-server
release binary.
I tested the change in a junk repo on my account:
https://github.com/variadico/tmp/blob/master/.goreleaser.yml#L37
The existing zip archives are preserved, this just adds .tar.gz, like so: 
https://github.com/variadico/tmp/releases/tag/0.1.0
The archive structure remains the same.
```
$ tree .
.
├── tar
│   ├── tmp-0.1.0-linux-amd64
│   │   ├── LICENSE
│   │   ├── README.md
│   │   └── tmp
│   └── tmp-0.1.0-linux-amd64.tar.gz
└── zip
├── …
```

Offer .tar.gz releases additionally

---

server/client.go
server/gateway.go
server/leafnode.go
server/opts.go
server/route.go
server/routes_test.go
server/server.go
server/server_test.go

We previously simply called DialTimeout() on a route's url when
soliciting. If it resolved to the IP of the host, it would create
a route to self, which server detects, but then would not try again
with other IPs that would have allowed to form a cluster with
other servers running on the other IPs.
This PR keeps track of local IPs + cluster port and exclude them
from the list of IPs returned by LookupHost API. This even prevent
solicitation of routes to self. Only non-local IPs will be tried.
Resolves #1586

[ADDED] Support for route hostname resolution

---

server/accounts.go
server/jetstream.go
server/jwt_test.go
server/server.go

I'm setting the account to incomplete so it is set for when we start to report things like that.
Have to set srv in update as on connect update is called before register. JS depends on that pointer existing.

Updating jetstream account settings from jwt

---

server/dirstore.go
server/dirstore_test.go

When using Unix() time, since it is number of seconds, it is better
to round up the time before adding a ttl. Trying to shorten some
of the tests showed that in some cases a file was removed too early.
This was because the computed expiration with ttl fell in the same
second, so the file was removed prematurely.
So anywhere where we used to do: time.Now().Addd(ttl).Unix(), I
changed to time.Now().Round(time.Second).Add(ttl).Unix().
I was able to reduce the time of TestTTL from 21 seconds down to
less than 5. TestExpiration was also shorten.

Fix dirstore code and speed up some tests

---

server/accounts.go
server/events.go
server/events_test.go

Lookup is a request.
STATSZ was duplicated so it falls into this scheme: 
$SYS.REQ.SERVER.<ID>.<OPERATION> and $SYS.REQ.SERVER.<ID>.PING.<OPERATION>.
The original SYS.REQ.SERVER.<ID>.PING is kept for backwards compatibility. (reason for change in events_test.go)
As for update I didn't go all in on avoiding parsing the jwt twice as it' not a frequent operation and avoids code changes.
There are more changes to come in that area but these where the straight forward ones.

Tie account in system event subject to data and clean up subject names

---

server/events.go
server/events_test.go

This fits better with similar events
New subject is $SYS.ACCOUNT.%s.SERVER.CONNS
Old subject remains for backwards compatibility
For backwards compatibility 2 subjects are used.
The utility to check if interest exists comes in handy here.
Going forward I'd add those to other system events as well, just thought this is a good first show case.

Adding new subscription for account conns

---

server/accounts.go
server/events.go
server/events_test.go
server/jwt_test.go

Old $SYS.ACCOUNT.%s.CLAIMS.UPDATE is kept for backwards compatibility.
The old name is in the same name space as events.
To be able to abuse this, an attacker needs to be in possession of the operator key as well.
In order to not introduce more version dependencies I decided to support old and new name for nats based account resolver as well.

Add $SYS.REQ.ACCOUNT.%s.CLAIMS.UPDATE

---

server/leafnode.go
server/leafnode_test.go
test/leafnode_test.go

If the soliciting side detects the disconnect and attempts to
reconnect but the accepting side did not yet close the connection,
a "loop detected" error would be reported and the soliciting server
would not try to reconnect for 30 seconds.
Made a change so that the accepting server checks for existing
leafnode connection for the same server and same account, and if
it is found, close the "old" connection so it is replaced by
the "new" one.
Resolves #1606

[FIXED] Prevent LeafNode loop detection on early reconnect

---

server/client.go
server/client_test.go
server/jetstream_api.go

- Server-side logs include the host IP and port that clients connected on as well as the client id created by the server but clients can specify additional info that would be useful for identifying them and this adds that info to the logs (when it is available)

[CHANGED] add client provided info into server side client logs when available

---

server/accounts.go
server/events.go
server/events_test.go
server/jwt_test.go
server/monitor.go
server/monitor_test.go
server/route.go
server/server.go

Returned imports/exports are formatted like jwt exports imports, even if they originating account is from config.
Fixes #1604
I named the account specific subject INFO as it makes more sense than ACCOUNTZ.
ForCONNZ/SUBSZ we remain to have the plural even when scoped to the account, not so much for account itself.
Also setting update time on every update and account creation. (avoids empty values)
For consistency, setting incomplete when expired (dummy) account is created.
This is primarily to make the returned json make sense and look somewhat similar no matter the origin (jwt/cfg)
```
http://localhost:7222/accountz
{
"server_id": "NDSVJWYHPIXEYV3PS66X4V2PUWWYVQVPQUJ35FZJRI5PN6QMWBHJ2MZH",
"now": "2020-09-23T16:18:53.199956-04:00", …
```

[Adding] Accountz monitoring endpoint and INFO monitoring req subject

---

server/client_test.go
server/events.go
server/jwt_test.go

The connection count sent and the connection count used to determine if
the timer should be disabled could differ.
Also fixed issues in unit test triggering this behavior.
It did not check if remote connections where set to 0 prior to doing
more tests.
Fixes #1613 
When running with -race, tests kept failing until I increased the check time to 4 seconds.

[Fixed] race condition where account conns timer was disabled too soon

---

server/events.go
server/events_test.go
server/monitor.go
server/monitor_test.go

On the monitoring endpoint /leafz specify ?acc=<account id>

[Added] filtering by account to leafz and exposing this as per acc subject

---

server/consumer.go
test/jetstream_test.go

It seems that when updating the delivery subject, we use as the
first sequence the ack floor, but if no message was ever ack'ed
then it causes the first message to be redelivered twice.
Resolves #1619

AddConsumer causes redelivery of first message

---

server/consumer.go
test/jetstream_test.go

This causes nil messages mid content stream and is confusing,
the test for this is amended to test the content received for
validity - where previously the test assumed any content is
good content but in fact it only received half the content.
Removing this behaviour until we can design this properly

Do not ack to AckNxt

---

server/consumer.go
test/jetstream_test.go

The panic was caused by the closing of an already closed Go channel.
The Delete() relied on the consumer's mset being nil to consider
the consumer already closed. However, the consumer's mset is set
to nil after invoking sendDeleteAdvisoryLocked() which internally
invokes sendAdvisory() which releases/reacquires the consumer lock.
This left an open door for a race to occur and Delete() to be
invoked twice on the same consumer.
Moving setting the consumer's mset to nil too early would prevent
the sendAdvisory() to actually do its job. We could pass the mset
to sendAvisory(), but a simpler approach is to simply use a "closed"
boolean on the Consumer object that is set to true at the beginning
of the Delete() function.
Resolves #1621

Fixed possible panic on consumer.Delete() during server Shutdown()

---

server/events.go

Noticed TestSystemAccountConnectionUpdatesStopAfterNoLocal failing du to the timer still being around.
I moved clearing of the timer, but still got failures where the last message does not contain conn count 0.
This hinted at one event from one client interfering with an event from another.
To avoid this holding the account lock during send seems the most appropriate solution.
sendInternalMsg essentially records the send queue and unlocks the server. 
This change just merges that with the code in sendAccConnsUpdate.

Fix event ordering issue caused by re-locking

---

server/accounts.go
server/dirstore.go
server/jwt_test.go

Full nats based resolver sync within a cluster.
This functionality addresses syncing between cluster.
Fixing deadlock when more than one server responds to lookup.
Fixing 2 crashes when shutdown and pack happen at the same time.
As a side effect of also doing fetch in the full account resolver, functionality was moved from the caching account resolver.

Adding fetch on missing jwt of full nats based resolver

---

server/client_test.go
server/norace_test.go

This test has been found to cause TestAccountNATSResolverFetch to
fail on macOS. We did not find the exact reason yet, but it seem
that with `-race`, the queue auto-unsub test (that creates 2,000
queue subs and sends 1,000 messages) cause mem to grow to 256MB
(which we know -race is memory hungry) and that may be causing
interactions with the account resolver test.
For now, moving it to norace_test.go, which consumes much less
memory (25MB) and anyway is a better place since it would stress
better the "races" of having a queue sub being unsubscribed while
messages were inflight to this queue sub.

Moving TestQueueAutoUnsubscribe to norace_test.go

---

server/consumer.go
server/filestore.go
server/stream.go
test/jetstream_test.go

As of now, this PR has only a new test that shows the issue.
It seems that Consumer.needAck() for AckExplicit should consider
that an Ack is needed if sseq > o.asflr and there is no pending
ack at all. However making this change would break the test
TestJetStreamInterestRetentionStream.
Also, running the new test with `-count 100` and by adding an
artificial delay in stream.ackMsg() (just before calling
mset.store.RemoveMsg(seq)) causes sometimes delete requests
for the same sequence to be processed twice, which causes
the new test to fail (even with an attempted fix as discussed
above). I think that the attempt to remove the same sequence twice
is messing up the state.
Resolves to #1627 

AckExplicit removes message for "offline" durable

---

server/events.go
server/events_test.go
server/monitor_test.go

Only one subscription is necessary. What is important for the user is that we publish on both, not that we also subscribe on both.

Avoid unnecessary CONNS subscription

---

server/accounts.go

Skip revocation check if the client has no jwt and is therefore internal

---

docker/Dockerfile.nightly

Currently, the NATS operator doesn't work with the nightly NATS Server images because binary is in a different location. This symlinks the binary to a few different known paths.
This is a backwards compatible change and shouldn't break existing users.

Update nightly image server binary path

---

docker/Dockerfile.nightly

Approach we'll take instead is to change to use for the path in the container to be `/bin/nats-server`
Reverts nats-io/nats-server#1637

Revert "Update nightly image server binary path"

---

server/accounts.go
server/dirstore.go
server/dirstore_test.go
server/events.go
server/jwt_test.go
server/opts.go

Update already existed scoped by account, this exposes update without account.
List returns a list of all stored accounts.
Delete deletes accounts.
Fix a crash on startup with non existing directory.
This does NOT cause existing accounts to be evicted from memory and will be added in a separate PR.

Adding list/delete/update operations for jwt stored by nats-resolver

---

server/client.go
server/const.go
test/leafnode_test.go

When creating shadow subscriptions for import streams, we were
not invoking code for gateway subscription accounting, which means
that when the account (for leafnodes) was switched to interest
only, those shadow subscriptions were not sent.

[FIXED] Stream's subscription propagation issue with gateways

---

go.mod
go.sum
server/accounts.go
vendor/github.com/nats-io/jwt/v2/exports.go
vendor/modules.txt

moved code from checkUserRevoked into separate function to be used by both revocation checks.

[Fixed] revocation check for activations used current time instead of jet issue time

---

server/accounts.go
server/accounts_test.go
server/client.go
server/errors.go
server/monitor.go
server/opts.go
server/parser.go
server/reload_test.go
server/server.go
server/sublist.go

This PR contains code to allow accounts to form subject mappings from one subject to another for both client inbound and service import invocations. This also allows weighted sets for the destinations.
```go
mappings = {
foo: bar
foo.*: [ { dest: bar.v1.$1, weight: 40% }, { destination: baz.v2.$1, weight: 20 } ]
bar.*.*: RAB.$2.$1
}
```
Full wildcard transformations are possible, such that a user has full control over how subjects are matched and transformed.
This transform code was also utilized to enable full wildcard support for service and stream exports/imports.
For instance this is now possible.
```go
imports = [
{ service: {account: "foo", subject:"request.*"}, to:"my.request.*"}
{ stream:  {account: "foo", subject:"events.>"}, to:"foo.events.>"}
{ stream:  {account: "foo", …
```

Traffic shaping and full wildcard support for streams and services exports/imports

---

server/leafnode.go
test/leafnode_test.go

[FIXED] Possible panic when server accepts TLS leafnode connection

---

server/accounts_test.go
server/events_test.go
server/server.go

Fix error and remove print from test.
My new found jwt knowledge made me realize that the issuer could change.
What needs to remain constant is the subject.
At the time of test we know we trust the jwt.
Internally acc.Name is set from accClaims.Subject 
The condition is to prevent one valid jwt becoming another by modifying the subject.

Fixed account update issue where signing key (and thus issuer) changes

---

server/accounts.go
server/dirstore.go
server/dirstore_test.go
server/jwt_test.go
server/opts.go

To enable in full mode configure allow_delete: true
When enabled the file will be renamed to allow for manual restore.
In cache mode it will be enabled by default.
When enabled files will be deleted.
For now deletes need to be done using the operator identity key.
Going forward we can allow signing keys to remove accounts issued by them while the operator identity key can be used to delete any jwt.

Adding support and an option for removal of jwt

---

server/client_test.go
server/leafnode.go

This is an addition to PR #1652. I have simply added a check but
at this point in time there is no risk that connection is closed
this early.
I also renamed the small helper function and fixed a test that
had an improper `s.mu.Unlock()` in an error condition.

Prevent panic when accepting TLS leafnode connections

---

server/dirstore_test.go

TestLru had rounding issue.
Ran the test 200 times on my box w/o issue.

Fix timing issue in unit test

---

server/accounts.go
server/client.go
server/config_check_test.go
server/opts.go
test/service_latency_test.go

When old requests were utilized and the requestor was on a different server then the responder, the auto-unsubscribe log on the requestors server when the reply was delivered would trigger a behavior that would report bad latency results since we did not have our second measurement m2 from the remote server yet.
This fixes that by tracking if we have delivered a response to the request, and if so will wait for the m2 measurement to arrive and not report bad results immediately.

[FIXED] Do not report bad latency results on auto-unsubscribe triggers

---

server/jetstream_api.go

When purging an empty stream success is true but the
purged is then omitted since its, correctly, 0. It's
better to include it even when zero so it's not weirdly
inconsistent between succesful purges.
Also helps with validation of payloads

always include purged number

---

server/filestore.go
server/filestore_test.go
server/memstore.go
server/store.go
server/stream.go

Previously interest based retention streams would save and the delete a message from the store if there were no consumers interested. This could lead to issues with messages showing up in the stream when none should be there.
This could also be the effect seen here: https://github.com/nats-io/jetstream/issues/314
We introduce SkipMsg() for the store interface to allow bumping the sequence number but never saving a message, which will guarantee there can never be a state observation of non-zero.
During this investigation I also realized that the filestore did not properly select a new starting sequence upon removal if the removal's block and the true next first sequence were not in the same message block, so fixed that too.

Add store.SkipMsg() and update no interest retention streams

---

server/const.go

(no code changes beyond server const)

Bump version to 2.2.0-beta.27

---

server/consumer.go
server/filestore.go
server/memstore.go
server/store.go
server/stream.go
test/jetstream_test.go

This will track the stream pending state for each consumer.
This code does account for filtered consumers.

Track number of stream pending for each consumer.

---

server/consumer.go
test/jetstream_test.go

rename consumer pending fields for clarity

---

conf/lex.go
conf/parse.go
conf/parse_test.go

This adds an alias to the NATS config to be able to use base2 units like `Gi`, `Mi`.  This will help it make it easier to declare when allocating volumes in Kubernetes which uses the units in this format as well, otherwise will have to use total bytes:
```yaml
nats:
image: synadia/nats-server:nightly
jetstream:
enabled: true
memStorage:
enabled: true
size: 1 Gi
fileStorage:
enabled: true
storageDirectory: /data/
size: 1 Gi
storageClassName: default
```
- Add alias of base 2 units to SI units

Add support for base2 units in NATS config

---

server/accounts.go
server/consumer.go
server/filestore.go
server/filestore_test.go
server/jetstream.go
server/memstore.go
server/store.go
server/stream.go
test/jetstream_test.go

The original design had a shared filestore write buffer and individual message blocks had a read cache.
This presented some performance and stability issues when lots of reads and deletes were happening to a
message block that was also being written to actively.
This change eliminates the shared write buffer and uses the message block's cache as a write through as
well as read cache and handles partials correctly.
This PR also introduces a dynamic autotuned block size for file based streams aiming at 25% overhead in most cases.
We also now dynamically discover the available disk space by storage directory.

Stability and performance updates for filestore.

---

server/filestore.go
server/filestore_test.go

We had a left over artifact from the shared write buffer architecture where the filestore was still controlling the flush loop for the special last message block. This changes it such that each message block is running their own flush loop.

Update to write architecture and bug fixes and stability improvements.

---

server/client.go
server/const.go
server/gateway.go
server/gateway_test.go
server/server.go

Connections normally suppress sending PINGs if there was some
activity. We now force GATEWAY connections to send PINGs at the
configured interval or 15 seconds, whichever is the smallest.

[CHANGED] Gateway connections now always send PINGs

---

server/filestore.go
server/filestore_test.go
test/jetstream_test.go

Fix for partial cache overwrite bug.
When we moved to a write through cache architecture we also moved the cache write to offset based instead of APPEND.
We were inadvertently clearing our offset from our cache when we would clear which meant if the next operation was another write we would have the wrong offset and overwrite previous messages.

Partial filestore cache bug

---

server/consumer.go
server/filestore.go
test/jetstream_test.go

We want to redeliver all pending immediately and in stream order if a consumer changes its delivery subject.

Redeliver pending 

---

server/filestore.go
server/filestore_test.go

We can have partial caches and we can also remove the idx cache. This was causing a bug where we would get the wrong slotInfo from the cache.idx. This code fixes the bug and detects idx partials.

Updates to index cache handling for message blocks.

---

server/consumer.go
server/filestore.go
server/filestore_test.go
server/jetstream.go
server/memstore.go
server/store.go
server/stream.go
test/jetstream_test.go

In preparation for clustering we need to have the consumer filestore update state with deltas vs original design.
Not sure I will stick with this long term since we could do delta updates for clustering at the consumer level above the store implementation but this includes some fixes and stability improvements and moves us closer to clustering.

Updates to consumer store to support delta updates.

---

server/consumer.go
server/filestore.go
server/filestore_test.go
server/memstore.go
server/store.go
server/stream.go
test/jetstream_test.go

We would release locks and call into upper layers when removing a message.
The upper layers may call back into the lower layers to get more information, such as the subject.
This fix has the storage updates optionally supply the subject for filtered consumers and fixes the bug of double deletes.

Fix bug when removing the same message from a stream.

---

server/errors.go
server/jetstream.go
server/jetstream_api.go
server/stream.go
test/jetstream_test.go

Allow an API endpoint and public API to lookup a stream by subject. The subject needs to be an exact match or a subset. If the subject is considered a filtered subject for the stream that will also be returned.

Allow stream lookup by subject.

---

server/consumer.go

We will be replacing this soon (channels) but wanted a separate PR for decoupling consumer from stream first.

Decouple consumer from using stream's sendq.

---

server/consumer.go
test/jetstream_test.go

When I moved the MaxAckPending logic to getNextMsg() it no longer enforced on streaming current inbound messages directly to consumers.

Make sure to honor MaxAckPending when streaming directly to consumers

---

conf/fuzz.go
server/fuzz.go

This PR addresses https://github.com/nats-io/nats-server/issues/1442 by adding two fuzzers.
The parser in `/server` has been fuzzed before and as a result of this, bugs and vulnerabilities have been found. 
With this PR I suggest running these fuzzers continuously by way of oss-fuzz. This will allow Google to run the fuzzers and notify maintainers in case any bugs or vulnerabilities are found. The service is offered free of charge with an implied expectation that bugs are fixed, so that the resources spent on fuzzing NATS are put to good use. I have previously reported bugs in NATS and they were fixed incredibly fast, so I presume this is not a problem.
I can confirm that these fuzzers work on oss-fuzz's infrastructure, and I have the setup ready to integrate NATS into oss-fuzz. All I …

Added 2 fuzzers

---

server/monitor.go
server/opts.go
server/opts_test.go

this is supposed to make it clearer what is being rejected

Rename reject_unknown to reject_unknown_cluster

---

server/accounts.go
server/server.go

This only cuts down on obviously bad requests that would have otherwise resulted in failures/timeouts on the receiving end

Only fetch account jwt if the name is a proper public account key

---

server/const.go

- Bump the beta version of the server to .33

Bump beta version (.33)

---

server/client.go
server/events_test.go
server/leafnode_test.go

Suppose a cluster of 2 servers, let's call them leaf1 and leaf2.
These servers are routed and have a leaf connection to another
server, let's call it srv1.
They share the same cluster name.
If a queue subscriber runs on srv1 and a queue subscriber on the
same subject/group name runs on leaf1, if a requestor runs on
leaf2, the request should reach only one of the 2 queue subs.
The defect was that sometimes both queue subs would receive the
message.
The added test checks that only one reply is ever received and
that the local "leaf" cluster is preferred.
Resolves #1722

[FIXED] LeafNode: duplicate queue messages in complex routing setup

---

server/server.go

only do so if $SYS is the system account
shortcut if all I want is forward it. Avoid unnecessary configuration.

[Adding] ability to reference $SYS in leaf node config

---

server/accounts.go
server/accounts_test.go
server/client.go
server/events.go
server/jetstream_api.go
server/stream.go
test/jetstream_test.go

This allows basic access to publish into a stream and receive the pub ack across accounts, as well as pull and push based receipt of consumer messages and the ability to ack those messages.

Enable JetStream streams and consumer access to be exported

---

server/auth.go
server/auth_test.go
server/config_check_test.go
server/opts.go
test/tls_test.go

Only works for gateways and routes. When true the subject alt DNS name
must match one url in the corresponding configuration
As discussed. At the very least have a look at the unit test cases in TestDNSAltNameMatching. Looking at certs to write my other tests I started to wonder if we should extend this to IPs too?
```
X509v3 extensions:
X509v3 Subject Alternative Name:
DNS:localhost, IP Address:127.0.0.1
```
Also look for 127.0.0.1 and it's IPv6 variant. Opinions?
If yes, I'd be open to suggestions on which urls to provide in test/tls_test.go line 823, 891, 892
What I intend to include in the doc
verify_and_implicit_allow| Only settable in a non client context where verify=true is the default (gateways/cluster). The incoming connections certificate's `X509v3 Subject Alternative Name` DNS …

[ADDED] verify_cert_and_check_known_urls to tie subject alt name to url in cfg

---

server/disk_avail.go

The types of fields in syscall.Statfs_t varies between platforms.
fs.Bavail is uint64 on Linux and int64 on FreeBSD.  This is the opposite way
around to fs.Bsize.
For now, just coerce the Bavail to be uint64.
If the VFS layer might return -1 for one or the other of these then these casts
will be problematic and we'll need more safeguards.

Unbreak FreeBSD compilation (syscall.Statfs_t)

---

server/accounts.go
server/client.go
server/errors.go
test/service_latency_test.go

Simple configs that represent a service export/import cycle between accounts could crash the server.

[FIXED] Detect service import cycles.

---

server/stream.go
test/jetstream_test.go

This PR does two things. 
1. Changes the ack from a publish to a formal api response.
2. We add in the ability to set headers to check for expected stream name, last sequence and last msg ID.
Second item reference: #1648 

Stream publish changes

---

server/client.go
server/leafnode.go
server/leafnode_test.go
server/monitor.go

There was a test to prevent an errorneous loop detection when a
remote would reconnect (due to a stale connection) while the accepting
side did not detect the bad connection yet.
However, this test was racy because the test was done prior to add
the connections to the map.
In the case of a misconfiguration where the remote creates 2 different
remote connections that end-up binding to the same account in the
accepting side, then it was possible that this would not be detected.
And when it was, the remote side would be unaware since the disconnect/
reconnect attempts would not show up if not running in debug mode.
This change makes sure that the detection is no longer racy and returns
an error to the remote so at least the log/console of the remote will
show the "duplicate connection" error …

[FIXED] LeafNode reject duplicate remote

---

server/leafnode.go
server/leafnode_test.go
server/server.go

[Added] account name checks for leaf nodes in operator mode

---

.goreleaser.yml
server/pse/freebsd.txt
server/pse/pse_freebsd.go
server/pse/pse_freebsd_amd64.go

(These commits should be preserved in merge, not squashed.)
The first commit fixes FreeBSD %cpu calculation, which was wrong by a factor of
2048, and provides an alternative implementation on amd64 which avoids the need
for cgo.  The framework setup is extensible to other architectures.
The second commit adds goreleaser targeting FreeBSD/amd64 as part of our usual
release artifact generation.
f088660d
goreleaser target freebsd/amd64
80d11fa1
FreeBSD fixes: %cpu scale; no-cgo for amd64
It would be convenient if we did not need to use cgo to compile for FreeBSD
for common architectures, allowing builds to be generated in Linux CI
flows.
The sysctl interface uses offsets which can vary by build architecture, so
doing this in the general case without cgo is not realistic.  But we can …

Cross-compile for FreeBSD/amd64 without cgo

---

server/consumer.go
server/jetstream.go
server/jetstream_api.go
server/stream.go
server/sublist.go
test/jetstream_test.go

Made several changes based on feedback.
1. Made PubAckResponse only optionally include an ApiError and not force an API type.
2. Allow FilterSubject to be set on a consumer config and cleared if it matches the only stream subject.
3. Remove LookupStream by subject, and add in filters for stream names API.

JetStream changes.

---

server/client.go
server/events_test.go

In some cases, the reply of a request message is prefixed when
going over a gateway so that if it comes back to a different
server than when the request originates, it can be routed back.
For system accounts, this routed reply subject was not tracked
so the server would reply to the inbox and may reach a server
that had not yet processed (through the route) the interest
on that inbox. If the reply came with the GW routed info, that
server would know to route it to the original server.

[FIXED] System account was not properly tracking GW routed replies

---

server/consumer.go
test/jetstream_test.go

Remove limitation on AckAll for consumers with filtered subjects.

---

server/leafnode_test.go
server/parser.go
server/route.go

When cluster origin code was added, a server may send LS+ with
an origin cluster name in the protocol. Parsing code from a ROUTER
connection was adjusted to understand this LS+ protocol.
However, the server was also sending an LS- with origin but the
parsing code was not able to understand that. When the unsub was
for a queue subscription, this would cause the parser to error out
and close the route connection.
This PR sends an LS- without the origin in this case (so that tracing
makes sense in term of LS+/LS- sent to a route). The receiving side
then traces appropriate LS- but processes as a normal RS-.
Resolves #1751

Send LS- without origin to route

---

server/const.go
server/jetstream.go
server/jetstream_api.go
server/reload.go
test/jetstream_test.go

When a system account was configured and not the default when we did a reload we would lose the JetStream service exports.
Resolves #1736 

Fix for #1736

---

test/service_latency_test.go

as pointed out int the review to https://github.com/nats-io/nats-server/pull/1731 importFormsCycle does not work and:
cycles are found where there are none
the 3 account test in TestServiceCycle does not fail because a cycle between A - B - C is detected. 
rewriting the imported subject is not taken into account
If we do not allow cycles for services, we shouldn't allow cycles for streams either.
Frankly we shouldn't look at subjects or import types, we should require that no information flow in a cyclic way, thereby requiring accounts to be hierarchical.  
I would certainly consider this a best practice practice as it avoids common errors (see lock hierarchies).
Anything tightly coupled should end up in the same account.
This should be detected as cycle. 
```
accounts {
A {
exports [ { …
```

Servicecyclewithmapping

---

server/accounts.go
server/errors.go
test/accounts_cycles_test.go
test/service_latency_test.go

Although Go stacks are not limited per se (just by memory), we wanted to put a limit to the depth to check. I chose 1024, which in my opinion if we hit this from a chaining perspective something is probably wrong.

Limit search depth for account cycles for imports

---

server/consumer.go
server/stream.go
test/jetstream_test.go

Had a deadlock with new preconditions. We need to hold lock across Store() call but that call could call into storeUpdate() such that we may need to acquire the lock. We can enter this callback from the storage layer itself and the lock would not be held so added an atomic.
Resolves https://github.com/nats-io/jetstream/issues/396

[FIXES] https://github.com/nats-io/jetstream/issues/396

---

server/dirstore.go
server/dirstore_test.go

fixed timing issue in unit test.
added another unit test for lru.
fixed pop / push issue. this caused the lru list to be reordered, which tripped of test assumptions.

fix test timing issue and flapper caused by unnecessary pop/push

---

server/accounts.go
server/auth.go
server/client.go
server/client_test.go
server/config_check_test.go
server/consumer.go
server/events.go
server/filestore.go
server/jetstream.go
server/jetstream_api.go
server/monitor.go
server/mqtt.go
server/mqtt_test.go
server/opts.go
server/parser.go
server/reload.go
server/route.go
server/server.go
server/server_test.go
server/stream.go
server/sublist.go
server/sublist_test.go
server/websocket.go
server/websocket_test.go

This PR introduces native support for MQTT clients. It requires use
of accounts with JetStream enabled. Since as of now clustering is
not available, MQTT will be limited to single instance.
Only QoS 0 and 1 are supported at the moment. MQTT clients can
exchange messages with NATS clients and vice-versa.
Since JetStream is required, accounts with JetStream enabled must
exist in order for an MQTT client to connect to the NATS Server.
The administrator can limit the users that can use MQTT with the
allowed_connection_types option in the user section. For instance:
```
accounts {
mqtt {
users [
{user: all, password: pwd, allowed_connection_types: ["STANDARD", "WEBSOCKET", "MQTT"]}
{user: mqtt_only, password: pwd, allowed_connection_types: "MQTT"}
]
jetstream: enabled
}
}
```
The "mqtt_only" …

[ADDED] MQTT Support

---

server/accounts.go
server/auth.go
server/jwt_test.go

fixed check of user issuer against the account id (Name) - was set to Issuer instead (issuer is always an operator)
added tests
FIX #1740

fixed bad issuer check performed against account issuer instead account subject (Name)

---

server/gateway.go
server/gateway_test.go
server/leafnode.go
server/leafnode_test.go
server/reload.go
server/server.go
test/gateway_test.go

Presence of TLS config in any remote gateway or leafnode would
cause the config reload to fail (because TLS config internal
content may change which fails the DeepEqual check).
This PR excludes the TLS configs in such case to check for
changes in gateways and leafnodes.
Although GW and LN config reload is technically supported, this
PR updates the internal remotes' TLS configuration so that
changes/updates to TLS certificates would take effect after
a configuration reload.

[FIXED] Config reload for gateways/leaf remote TLS configurations

---

server/dirstore.go
server/dirstore_test.go

each test takes about 2 seconds. one second to observe expiration does not happen, and one to observe expiration.

Break test up into shorter ones

---

server/gateway.go
server/gateway_test.go

PR #1412 had a fix for races during implicit GW reconnection.
However, the fix was a bit too simplistic in that it was checking
only if there was any inbound gateway to decide to try to reconnect
an implicit disconnected GW. We need to check the name, not only
presence of inbound GW connections.
Related to #1412

Fixed GW implicit reconnection

---

logger/syslog.go
logger/syslog_windows.go

Use `Warning()` instead of `Notice()` and fix documentation for both syslog and Windows event log.
Signed-off-by: Paolo Teti <paolo.teti@gmail.com>

[FIXED]: syslog Warnf call Notice() instead of Warning()

---

server/stream.go

Resolves https://github.com/nats-io/nats.java/issues/384
So a header can be serialized `<key><colon><value>`  or `<key><colon><space><value>` 
When I wrote nats-java headers, I did not use the extra space b/c why send an extra byte. The go client uses a space.
https://tools.ietf.org/html/rfc2616#section-4.2 Leading Whitespace (LWS) is optional
```
message-header = field-name ":" [ field-value ]
field-name     = token
field-value    = *( field-content | LWS )
field-content  = <the OCTETs making up the field-value
and consisting of either *TEXT or combinations
of token, separators, and quoted-string>
```
For example: 
If you send with a space `Nats-Expected-Stream: stream-name` the server compares the actual stream name to `stream-name`
If you send without a space, i.e …

stream handle headers with no space after colon

---

conf/lex.go

after eof isVariable had a buffer overflow
stringStateFn was not set when lexString was returned

[fixed] two minor configuration lexer issues found by oss-fuzz

---

conf/lex.go
conf/parse_test.go

Peek followed by next resulted in an infinite loop when eof was not
checked.
I looked for all instances of this pattern and return an error when eof is not already checked or skip was used.

[fixed] timeout in configuration lexer found by oss-fuzz

---

server/accounts.go
server/jwt_test.go

[Added] support for jwt export response threshold

---

.github/workflows/nightly.yaml
docker/Dockerfile.nightly

2.2 will be built with 1.15 so preparing nightlies to match

use go 1.15 for nightly builds

---

conf/lex.go
conf/parse_test.go

and double quote.
similar to last, even more straight forward

[fiixed] infinite loop in config parser for include with quote

---

server/monitor.go
server/monitor_test.go

Only the user (from username/password connection method) was reported
in this monitoring endpoint. Will now report proper nkey, public key,
etc..
Resolves #1799

[FIXED] Monitoring endpoint `connz?auth=true` show incorrect user

---

server/client.go
test/bench_test.go

This is how it was up to v2.1.2 included (changed in v2.1.4 onward).
I added a benchmark that has 3 subscribers running and increase
the number of publishers: 1, 2, 5 and 10. This is the comparison
between the pre-PR and post-PR:
```
benchcmp old.txt new.txt
benchmark                           old ns/op     new ns/op     delta
Benchmark___BumpPubCount_1x3-16     396           385           -2.78%
Benchmark___BumpPubCount_2x3-16     495           406           -17.98%
Benchmark___BumpPubCount_5x3-16     542           395           -27.12%
Benchmark__BumpPubCount_10x3-16     549           515           -6.19%
benchmark                           old MB/s     new MB/s     speedup
Benchmark___BumpPubCount_1x3-16     717.27       737.54       1.03x
Benchmark___BumpPubCount_2x3-16     574.31 …
```

Propose going back to condition variable to notify writeLoop

---

server/sublist.go
server/sublist_test.go

The insert notification was done based on the creation of a node
during an insert, which was wrong since the node may have already
existed and still the subscription could be all new. For instance,
suppose that there is a subscription on "foo.bar".
We register an notification interest for "foo", which does not
notify, which is normal. Then we create a subscription on "foo".
During the insert, "foo" node already exists so notification would
not be sent, but it should.
Fixed also removed by having removeFromNode() returning a boolean
to indicate if the subscription was the last in that node.
However, it seems that we again check for interest in
chkForRemoveNotification(), so not sure if that is required.

Fixed sublist notification

---

server/client.go
test/accounts_cycles_test.go
test/tls_test.go

Also added some no-op error handler for some tests to silence the
error report in the log.

Fixed service import cycle detection that broke with JS clustering

---

server/accounts.go
server/auth.go
server/client.go
server/jwt_test.go

I added a lookup of the scoped signing key to applyAccountLimits. 
passing in the values into the function would have made the change a lot bigger.
Currently the update strategy of scoped keys is to disconnect the clients

[added] enforcement and usage of scoped signing keys

---

server/accounts.go
server/jwt_test.go

Also adjusting unit test to not check for renamed values

Fixing latency sharing which was overwritten

---

server/jetstream_cluster.go
test/jetstream_cluster_test.go

Resolves #
- Update error message to indicate where the cluster name is set to. The current server startup error was misleading (it was probably copied from the `server_name`)

Update error message with correct config value

---

server/events.go
server/gateway.go
server/route.go
server/server.go

Those changes are required to maintain backward compatibility.
Since the replies are "_G_.<gateway name hash>.<server ID hash>"
and the hash were 6 characters long, changing to 8 the hash function
would break things.

Fixed gateway reply mapping following changes in JetStream clustering

---

server/accounts.go
server/server.go

There was a bug where the client chosen under the $SYS account could have a different account.

Routes send subscriptions by utilizing random clients from an account.

---

server/accounts.go
server/route.go
server/server.go
test/norace_test.go

Since we were creating subs on the fly, sub.im would always be nil.
We were passing a client because it was needed in sendRouteSubOrUnSubProtos().
This PR simply fills the buffer with each account's subscriptions.
There is also no need to have subs sent from different go routine
based on some threshold. Routes are no longer subject to max pending.
Some code has been made into a function so that they can be shared
by sendSubsToRoute() and sendRouteSubOrUnSubProtos(). The function
is simply adding to given buffer the RS+/- protocol.

Simplify sendSubsToRoute()

---

server/jetstream_api.go
test/jetstream_test.go

Will now return an error that the stream is unknown.
Resolves #1827

Fixed SIGSEGV when sending update for unknown stream

---

server/dirstore_test.go
server/events.go
server/events_test.go
server/monitor.go
server/monitor_test.go
server/opts.go
server/reload.go

fixes #1588
original issue asks for map, but I'd rather stick to the same label format we have in other places.
For now I also refrained from sending them between server.

[added] support for tags and filter ping monitoring requests by tags

---

server/mqtt.go
server/mqtt_test.go

- Allow parsing password field on MQTT Connect request as a JWT to use bearer token client authentication/authorization
- Test MQTT authentication with tokens with different "allowed connection types" to ensure correct user authorization

[ADDED] Allow bearer token as mqtt authentication method

---

server/opts.go

When JS with clustering is enabled, a `server_name` is required error is reported (since that is the name of the config option), though there is no `server_name` flag since to set the name in the command line either `-n` or `--name` have to be used instead. Have ran into this a few times so thought might be good to add an option when creating a cluster via the CLI.
```sh
nats-server -js -p 4222 --cluster nats://127.0.0.1:6222 --cluster_name ABC --routes nats://127.0.0.1:6222,nats://127.0.0.1:6223,nats://127.0.0.1:6224 -D
nats-server: jetstream cluster requires `server_name` to be set
```
With the new flag:
```sh
nats-server -js -p 4222 --server_name=A --cluster nats://127.0.0.1:6222 --cluster_name ABC --routes nats://127.0.0.1:6222,nats://127.0.0.1:6223,nats://127.0.0.1:6224 -D
``` …

Add --server_name flag to set server name

---

server/leafnode.go
server/leafnode_test.go

[FIXED] LeafNode: save hostname that may be used during TLS handshake

---

server/raft.go
server/server.go

Had some flappers determining state to be current because applied and commit were going backwards.

Raft fixes

---

server/client.go
server/const.go
server/log_test.go
server/parser.go
server/parser_test.go

Only check limit for CLIENT connection types, however, the check
is done for CLIENT in all conditions, not only in the case of a
split buffer as it was the case so far.

[CHANGED] Enforce max_control_line for client connections only

---

server/consumer.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_events.go
server/raft.go
test/jetstream_cluster_test.go

Add in leader elected and lost quorum advisories.

---

server/monitor.go
server/monitor_test.go

[added] cluster/gateway/leafnode  tls required/verify/timeout to varz

---

server/sublist.go
server/sublist_test.go

A subject such as `foo..bar` is invalid, but if it is published
from a connection that has disabled pedantic, then the message
is matched against subscriptions and will be delivered.
This change causes Sublist.Match() to return no result.

[FIXED] Return no match result if subject contains empty token

---

server/client.go
server/gateway.go
server/leafnode.go
server/leafnode_test.go
server/mqtt.go
server/opts.go
server/route.go
server/server.go
server/websocket.go
server/websocket_test.go

Users will now be able to create a Leafnode connection to the websocket
port of the remote server.
The URL in the remote configuration has to start with "ws" (or "wss").
By default, since this is communication between two servers, the websocket
frames will not be masked. However, there is an option to force the masking.
Here is what a remote leafnode configuration would look like:
```
leaf {
remotes [
{url: "ws://host1:6222", ws_compression: true, ws_no_masking: true}
{url: "ws://host2:6222", ws_compression: true}
{url: "ws://host3:6222"}
]
}
```

[ADDED] Websocket for Leaf Node connections

---

server/accounts.go
server/jetstream.go
server/jetstream_cluster.go
server/jwt_test.go
server/server.go

When trying to make sure we properly created all subs for service imports we would check the internal client to see if we should process. With JS enabled on the server we would place system imports that would break that check and orphan other service imports.
Resolves #1864 

[FIXED] Fix for #1864

---

server/leafnode.go
server/leafnode_test.go
server/websocket.go

The issue was introduced by PR #1858.
Key points:
- Sec-WebSocket-Extensions must contain approved headers, so moving
the "no-masking" private extension to its own header "Nats-No-Masking".
- The format of the permessage-deflate negotiation response became
invalid, I have fixed that.
- For leaf nodes, if `permessage-deflate` extension is not at all
present in the response, then simply disable compression, however
if it is present but there is no server/client no context take over,
then we have to fail the connection.
- A leafnode test was not setting the "NoMasking" option so the
test TestLeafNodeWSNoMaskingRejected was not capturing possible
error if negotiation failed.

Fixed compression http header request/response

---

go.sum
server/accounts.go
server/accounts_test.go
server/jwt_test.go
server/opts.go
server/opts_test.go

This was added to support ngs.
This change does 4 things.
Refactor to only have one function to validate imports.
Have This function support the jwt field account_token_position.
For completeness make this value configurable as well. 
unit tests

[Adding] support for account_token_position

---

server/accounts.go
server/consumer.go
server/jetstream.go
server/jetstream_api.go
server/jetstream_cluster.go
server/raft.go
server/reload.go
server/server.go
server/stream.go
test/jetstream_cluster_test.go
test/norace_test.go

Added in JS disable per server on reload. This will cause all peer allocations from this server to be re-assigned.
Added ability to disable JS for a server but have the server properly route JS traffic.
Fixed ability to reload debug setting and have raft nodes react.
Added API to allow removing a peer from a stream (and hence the consumers as well)
Add stepdown api for streams and consumers which will cause leader election to happen. 
Various bug fixes, stability improvements.

Removing peers from streams and consumers and stepdown functionality

---

server/filestore.go
server/filestore_test.go
server/jetstream_api.go

We needed to clear the erase bit to properly set fseq in the cache structure on re-indexing.

[FIXED] Bug with erased messages and re-indexing the message block cache.

---

server/client.go
server/events.go
server/jetstream_cluster.go
server/raft.go
server/route.go
server/server.go
server/stream.go
test/jetstream_cluster_test.go
test/service_latency_test.go

This allows metacontrollers to span superclusters. Also includes placement directives for streams. By default they select the request origin cluster.

First pass at supercluster enablement.

---

server/consumer.go
server/jetstream_cluster.go

- Should check if there is interest at top of deleteNotActive timer
callback.
- Use RLock/RUnlock for no interest check
- Remove some checks in cluster mode regarding internal stream/consumers

Fixed some issues with JS consumers

---

server/jetstream_cluster.go
server/raft.go
test/jetstream_cluster_test.go

Purge operations would be replayed on restart regardless if they had already been processed.

Purge operation replay on restart

---

server/events.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go

For larger superclusters we send out our server information after a short delay on startup.
For determining leaderless status for API calls make sure the raft node has been running for long enough.

Fixes for supercluster startup and JetStream clustering.

---

server/accounts_test.go
server/client.go

Currently when someone imports a subject with a wildcard, uses an empty string for `LocalSubject`, and if the importer account subscribes to `>`, then non-exported messages from the exported account leak to the importer account.
This happens because a shadow subscription is created on `>` (subscriber subject), instead of the import subject. From what I could see, I think these are the relevant code sections in master, in chronological order.
1. https://github.com/nats-io/nats-server/blob/master/server/accounts.go#L2272-L2283
(value of `usePub` relevant)
2. https://github.com/nats-io/nats-server/blob/master/server/client.go#L2466-L2469
(value of `ime.dyn` relevant [boolean value of `ime{}`])
3. https://github.com/nats-io/nats-server/blob/master/server/client.go#L2507-L2520
(subscription …

Prevent non-exported messages from leaking into importer account

---

server/accounts.go
server/accounts_test.go
server/client.go

Also optimized a test that was taking too long to run.

Remap subject only for service imports

---

server/events.go
server/monitor.go

Adds an error type and a check to avoid sending them
to clients

skip responses from non leaders in jsz

---

server/monitor.go

track per server stats rather than cluster stats

---

server/auth.go
server/client.go
server/consumer.go
server/filestore.go
server/filestore_test.go
server/jetstream.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/jetstream_test.go
server/memstore.go
server/raft.go
server/server.go
server/stream.go

Previously we did a snapshot and compaction strategy that would require pauses to the proposals from clients which was not ideal. This changes that to a raft node maintained external snapshots that do not require pauses. We also moved to memory based WALs for streams and consumers.
Various other bug fixes, data race fixes and stability improvements.

Snapshot and Compaction Improvements

---

server/consumer.go
server/filestore.go
server/jetstream_cluster.go
server/raft.go

Original thought to move to memory based WALs was ill-advised and caused issues with stability around restarts.
Returned to file based but with async flush for the WAL itself.
Also the raft inline catchup has been improved.

General stability improvements.

---

server/client.go

doc of LastIndex says it will return -1 when none found.

[fixed] out of range issue in processMsgResults during subject rewrite

---

server/client.go
server/leafnode_test.go

A publish on "a" becomes an LMSG on ">" which
is the stream import's subject. The subscriber on "a" on the other
side did not receive the message.
This change adds @kozlovic unit test and adds a missing check.
The check is now identical to other regions of code doing smth similar.
```
func (c *client) processMsgResults(acc *Account, r *SublistResult, msg, deliver, subject, reply []byte, flags int) (bool, [][]byte) {
...
// Loop over all normal subscriptions that match.
for _, sub := range r.psubs {
...
// Assume delivery subject is normal subject to this point.
dsubj = subj
// Check for stream import mapped subs (shadow subs). These apply to local subs only.
if sub.im != nil {
if sub.im.tr != nil {
to, _ := …
```

[fixed] LeafNode sending message using stream's import subject.

---

server/client.go
server/consumer.go
server/events.go
server/filestore.go
server/gateway.go
server/jetstream_api.go
server/jetstream_cluster.go
server/mqtt.go
server/mqtt_test.go
server/opts.go
server/reload.go
server/server.go
server/stream.go

Made changes needed to support JetStream clustering.
I am no longer making any call to direct stream/consumer internal APIs.
I have no longer the need for "internal/no_interest/no_subject" private stream/consumer configuration properties, so I have removed them and remove the JSON marshaller that was added to persist those (since they were not exported).

MQTT clustering

---

server/gateway.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/raft.go

Allow metacontroller leaders to be moved to specific clusters in a supercluster setup.

Allow placement directives for meta controllers

---

server/jetstream.go

test case (as per email from Ben) passes now without crash
```
00:44:26  ~/repos/nats-server  crash-no-sys-acc-js *20  go run ./main.go -c /Users/matthiashanel/Downloads/nats-server.conf -n asdf
[32566] 2021/02/23 00:44:27.741177 [INF] Starting nats-server
[32566] 2021/02/23 00:44:27.741278 [INF]   Version:  2.2.0-beta.88
[32566] 2021/02/23 00:44:27.741281 [INF]   Git:      [not set]
[32566] 2021/02/23 00:44:27.741283 [DBG]   Go build: go1.14.1
[32566] 2021/02/23 00:44:27.741285 [INF]   Name:     asdf
[32566] 2021/02/23 00:44:27.741292 [INF]   ID:       NBHX3YTUYZQ6MZKTBXI63DX6IYGKFBLNVSGZ5SN4JUBUUQMC54NRSWRX
[32566] 2021/02/23 00:44:27.741297 [INF] Using configuration file: /Users/matthiashanel/Downloads/nats-server.conf
[32566] …
```

[fixes] crash in checkJetStreamExports when there is no system account

---

.travis.yml
server/client.go
server/const.go
server/consumer.go
server/events.go
server/gateway.go
server/jetstream.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/jetstream_test.go
server/norace_test.go
server/raft.go
server/stream.go
server/sublist.go

Also various fixes, stability improvements, etc.

Stream Mirrors, Sources and Updates Support

---

server/const.go
server/consumer.go
server/events.go
server/filestore.go
server/jetstream.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/raft.go
server/server.go

Tracked down the expected not what we wanted state with snapshots etc. Was a term mismatch so properly truncate now. Still may be some lingering strange states but this seemed to help.
Found some general subscription management issues with leaking subscriptions.
Made shutdown more bearable, and also the reporting on stalled quorums got slowed down for when we have lots of streams and consumers.

General stability improvements. 

---

server/client.go
server/jetstream_cluster_test.go
server/stream.go

Reply subject rewrite behaviors when crossing accounts via service imports would break JetStream pull consumers.
For now make special case. Need longer term solution for opt-in or opt-opt of reply subject rewrite.
Also do not store request info headers into JetStream streams.

Cross account JetStream pull consumers.

---

server/consumer.go
server/jetstream_test.go

This avoids a situation where a consumer asks for
ORDERS.new today on a stream of ORDERS.new but later
someone makes the same stream ORDERS.* and the new
consumer would then get messages for other purposes
as well

always store the filter subject

---

server/jetstream_api.go
server/jetstream_test.go
server/stream.go

Now will keep trying to establish contact.
Fixed bug where double source headers for sourced messages were causing issues.

Allow sources and mirrors to not be pre-defined.

---

.github/workflows/nightly.yaml
docker/Dockerfile.nightly

upgrade nightlies to go 1.16

---

server/accounts.go
server/auth.go
server/client.go
server/dirstore.go
server/jetstream_cluster.go
server/monitor.go
server/mqtt.go
server/route.go
server/server.go

```
From top 
accounts.go: 
se is never nil
complained about differing receiver names (I only fixed a few of these. To keep the change smaller )
unnecessary conversion
unused constant
acc will be nil
p is always nil
complaining about errors starting with lower case (There are more. I only changed one of these)
receiver name again
jwt overloaded the package. (there are more than this one, but only fixed a few to keep this change smaller)
auth.go
regex was bad , is not part of the regex. {n} is only needed when n > 1
client.go
return is always false
srv is never nil (scroll up quite far)
err is never nil  (scroll up quite far)
dirstore.go
differing receiver name
jetstream_cluster.go
|| threw off the linter thought both conditions where possible …
```

Fixed linter issues

---

server/accounts.go
server/consumer.go
server/events_test.go
server/jetstream.go
server/jetstream_api.go
server/jetstream_cluster_test.go
server/monitor.go
server/monitor_test.go
server/stream.go

In clustered JetStream we need to move API calls out of routes/gateways/leafnodes path.
This moves from explicit imports and subscriptions to one wildcard subscription and a single wildcard export.

JetStream API Changes

---

server/consumer.go
server/events.go
server/jetstream.go
server/jetstream_api.go
server/jetstream_cluster_test.go
server/jetstream_test.go
server/norace_test.go

Make sure to not process next message (batch) requests inline if non client connection.
Added an index to the redeliver queue for large rdq scenarios.
Cleanup service exports and imports for JetStream.

Consumer Updates.

---

server/events.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/raft.go
server/route.go
server/server.go

Took the approach of storing struct instead of pointer. Of course,
when changing the offline bool from false to true, it means that
we need to call Store again (with same key).
This is based on the assumption that those Load/Store are not too
frequent. Otherwise, we may need to use locking (and keep *nodeInfo)

Fixed data race with nodeInfo

---

server/accounts.go

Yesterday this unit test used to pass for me locally. So this is smth new.
`jsAllApi` is not included in `allJsExports`.
On update we would then loose the `jsAllApi` subscription.
Because of this enableAllJetStreamServiceImports would fail (export not found) when adding the import for `jsAllApi` of the system account.
Additionally, the export `jsAllApi` overlaps with the other exports (in pairs below). (Overlapping exports are smth. we prohibit in jwt)  
The solution could also be adding `jsAllApi` to `allJsExports`. 
I was not sure what's best, so I picked calling `checkJetStreamExports `
Opinions?
```
// For easier handling of exports and imports.
var allJsExports = []string{
JSApiAccountInfo,
JSApiTemplateCreate,
JSApiTemplates, …
```

[Fixed] missing export jsAllApi on system account update

---

server/client.go
server/gateway.go
server/jetstream.go
server/jetstream_cluster_test.go
server/norace_test.go

- Fixed the close of a TLS connection which starting Go 1.16
set the deadline to 5 seconds.
- Fixed an issue with setHeader that was causing these error messages
```
=== RUN   TestServiceImportReplyMatchCycleMultiHops
nats: message could not decode headers on connection [4] for subscription on "foo"
--- PASS: TestServiceImportReplyMatchCycleMultiHops (0.04s)
```
- Fixed names of tests in norace_test.go since they must start with
TestNoRace in order to make sure that we execute them in Travis:
```
go test -v -run=TestNoRace --failfast -p=1 ./...
```

Switch Gateway JS accounts to interest-only mode + some other fixes

---

server/client.go
server/const.go
server/consumer.go
server/events.go
server/jetstream_api.go
server/jetstream_cluster.go
server/jetstream_cluster_test.go
server/raft.go
server/sendq.go
server/server.go
server/stream.go

Move raft comms off of internal sendq. Move our stream msg processing out of Go routines servicing routes and gateways.

Raft changes and inbound stream msgs out of fastpath for non-clients.

---

server/consumer.go
server/jetstream_test.go
server/raft.go

Allow an option to push based consumers to have idle heartbeats delivered.
This allows an endpoint to know the consumer is still alive.

Push consumer idle heartbeats

---

server/consumer.go
server/filestore.go
server/jetstream_api.go
server/jetstream_test.go
server/signal.go
server/stream.go

Enable slow start flow control for push based consumers using flow control messages.

Enable opt-in flow control for push based consumers.

---

server/jetstream_cluster.go

Changed the stream min size default value back to 32MB and removed
the one for consumer since we don't use it anymore but set the
count size same than for stream (8192).

monitorConsumer perform snapshot similar to monitorStream

---

server/const.go
server/signal.go
server/signal_test.go

In some platforms like K8S / Docker, the TERM signal is sent after calling `docker stop` / `kubectl delete pod`, letting the process terminate for some time before stopping the container.  
In order to terminate gracefully in NATS, it is needed to first send an USR2 signal to the server so that it enters lame duck mode before exiting. For example in k8s the `preStop` command can be used to send the signal:
```yaml
#
lifecycle:
preStop:
exec:
command: ["/bin/sh", "-c", "/nats-server -sl=ldm=/var/run/nats/nats.pid"]
```
But soon after sending the signal, K8S will send a `TERM` signal and abort the LDM graceful stop. In this PR, we add a check to the TERM signal handler so that LDM is able to wrap up and exit on its own before being forced to terminate (like `terminationGracePeriodSeconds` …

Skip TERM signal during lame duck mode

---

server/jetstream.go

getJetStreamCluster returns nil when `server.shutdown == true`.
I manually call shutdown to keep the change small and future proof (more conditions where nil is returned)
Error in travis:
```
=== RUN   TestJetStreamClusterExtendedStreamInfo
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb178ba]
goroutine 120333 [running]:
github.com/nats-io/nats-server/server.(*Server).DisableJetStream(0xc00e05aa80, 0x0, 0x0)
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:291 +0xfa
created by github.com/nats-io/nats-server/server.(*Server).handleOutOfSpace
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream.go:262 +0xd1
FAIL …
```

fixing crash when disabling already shut down server

---

server/jetstream_cluster_test.go

With the latest change I still see the large run times (10sec> runtime <30sec)
Even though I increase the timeout quite drastically, most tests stay below 3 seconds (#49) and 5 seconds (#24) )
In this run of 100 tests 85 tests stay below 10seconds, and the remaining 15 would have failed without the change.
When running this on travis I found a crash ([PR is out](https://github.com/nats-io/nats-server/pull/1978)) and 4 failures of the unit test `TestNoRaceJetStreamClusterSuperClusterSources`.  Getting to green builds rather quickly now.
```
grep "[^(]....s[)]" testout
--- PASS: TestNoRaceJetStreamClusterLargeStreamInlineCatchup (12.44s)
--- PASS: TestNoRaceJetStreamClusterLargeStreamInlineCatchup (14.76s)
--- PASS: …
```

Increasing unit test timeout for waitOnStreamCurrent from 10 to 30 sec

---

server/consumer.go
server/jetstream_test.go

Noticed that when making a batch request, it was possible to ask for a batch larger than ack pending so resulting in redeliveries as part of the batch.

Prevent pull batch larger than max ack pending
