- TODO.md
- server/client.go
- server/const.go
- server/parser.go
- sublist/sublist.go
- test/bench_test.go
This dramatically improves large message performance.
> Large Message Performance

- server/monitor.go
- server/monitor_sort_opts.go
- server/monitor_test.go
Left it pending to enable this one option from last PR. /cc @derekcollison
> Add option to sort by pending size

- server/client.go
- test/proto_test.go
This is issue #136. With routes, it is possible that a subscriber connects (or reconnects) and is about to broadcast the SUB protocol to the routed server, and at the same time, the server sends the list of the local subscriptions. This would result in a SUB processed twice, adding the same sub in the sublist twice. If the server sending the subscription list is restarted, this will leave "detached" subscriptions in the sublist which would trigger the "Bad or Missing ROUTER info" for every message published on that subject.
@derekcollison @olegshaldybin Oleg, this is probably the issue you saw last Friday on Bagel.
> Fix handling of duplicate SUB protocol.

- .travis.yml
- README.md
- gnatsd.go
- server/ciphersuites_1.4.go
- server/ciphersuites_1.5.go
- server/configs/tls.conf
- server/const.go
- server/opts.go
- server/opts_test.go
- server/route.go
- server/server.go
- server/usage.go
- test/configs/tls.conf
- test/tls_test.go
Many updates for timeouts, handshake synchronization, etc.
> TLS updates

- server/pse_freebsd.go
Dear Sir:
I make a patch to grab rss/vss/cpu on freebsd,
please help to review, thanks.
> add freebsd support.

- server/configs/srv_a.conf
- server/configs/srv_b.conf
- server/opts_test.go
This is to workaround the issue we have on Travis new GCE.
> Set 'net' in some config files

- TODO.md
- server/client.go
- server/monitor.go
- server/monitor_sort_opts.go
- server/monitor_test.go
This supports tracking last activity on connections, such as connect, sub and pub. It does not track ping/pong for this statistic.
> Support for connection last activity tracking.

- TODO.md
- server/client.go
- test/proto_test.go
- test/routes_test.go
Better performance for queue subscriber distribution.
> Randomize distribution to subscribers

- server/monitor.go
- server/monitor_sort_opts.go
- test/gosrv_test.go
- test/test.go
- Possible race/invalid value in LastActivity
- Routez
- Believe fixes #189
> Fix races in monitoring

- TODO.md
- gnatsd.go
- server/client.go
- server/client_test.go
- server/configs/srv_a_bcrypt.conf
- server/configs/srv_b_bcrypt.conf
- server/errors.go
- server/routes_test.go
- server/server.go
- test/test.go
> Support for bcrypt in cluster auth

- server/client.go
- server/sublist.go
This allows for low contention hot cache on a per client basis. Other optimizations around atomic stats accounting has also been optimized.
> L1 client cache for sublist and accounting optimizations

- .travis.yml
- logger/log_test.go
- scripts/cov.sh
- server/monitor_test.go
- server/opts.go
- server/parser_test.go
- server/routes_test.go
- server/server_test.go
- test/test.go
- test/test_test.go
-Test coverage was no longer triggered due to the check for BUILD_GOOS
environment variable that was removed. Removed the check.
-Re-run test package with server code coverage.
-Remove unused functions in test.go.
-Add test for a function in test.go.
-Add missing parse +OK test.
> Add more code coverage

- server/pse/pse_windows.go
Code referenced Debugf which is not available in this package.
/cc @derekcollison
> Fix Windows build

- README.md
discovered some of this while debugging and deploying. Thought it could do some good.
> update readme about cluster config

- server/client.go
This PR addresses the issue by testing the result of the
`Timer.Stop()` method, which if `false` indicates that the callback
may be in progress. When that happens, the `processConnect` method
will wait for the callback to finish and simply return. The auth
timeout error will therefore be received by the client during the
synchronous connect process, which will allow it to try again.
Resolves #289
> Fix possible authentication timeout after accepting CONNECT proto

- TODO.md
- auth/multiuser.go
- server/auth.go
- server/client.go
- server/configs/authorization.conf
- server/const.go
- server/errors.go
- server/opts.go
- server/opts_test.go
- server/pse/pse_windows.go
- server/server.go
- server/sublist.go
- test/auth_test.go
- test/bench_test.go
- test/client_auth_test.go
- test/configs/authorization.conf
- test/user_authorization_test.go
This allows authorization of subjects for publish and subscribe filters with enforcement.
/cc @kozlovic @ColinSullivan1
> Authorization

- README.md
@mcqueary @ColinSullivan1 @kozlovic @aricart @derekcollison @wallyqs
> Updates to README; permissioning feature added

- server/client.go
- server/errors.go
- server/parser.go
- server/sublist.go
- test/proto_test.go
- test/test.go
Make sure we error on a breach of maximum control line. Not precise because if performance hit, but will prevent memory and DOS attacks.
/cc @wallyqs @kozlovic
> Control overflow

- README.md
@aricart @derekcollison Addresses Alberto's feedback on clustering section.
> Updates to Clustering section

- server/pse/pse_test.go
- server/pse/pse_windows_test.go
Added garbage collection before each capture method and bump the
delta threshold to 1MB.
Resolves #310
> [FIXED] PS test to reduce failures in some situations

- server/monitor.go
- server/monitor_test.go
> [FIXED] Server panic when poll for Varz and others concurrently

- server/client.go
- server/route.go
> [FIXED] Data RACE on Unsubscribe when client connection is closed

- server/configs/test.conf
- server/opts.go
- server/opts_test.go
This adds tests to an original code review here: https://github.com/nats-io/gnatsd/pull/187
> [#370] Ability to configure ping_interval and ping_max (with tests)

- conf/includes/passwords.conf
- conf/includes/users.conf
- conf/lex.go
- conf/lex_test.go
- conf/parse.go
- conf/parse_test.go
- conf/simple.conf
- server/const.go
- server/opts.go
- test/configs/authorization.conf
- test/configs/auths.conf
- test/user_authorization_test.go
Add in support for configuration file includes.
> Include Support

- server/log.go
- server/server.go
Uses USR1 to re-open file based logs.
> Support to reopen file based logs for file rotation

- main.go
- server/monitor_test.go
- server/opts.go
- server/opts_test.go
- server/route.go
- server/routes_test.go
- server/server.go
- server/server_test.go
- test/route_discovery_test.go
- test/routes_test.go
- test/test.go
Cleaned up handling of cluster options.
> Cluster opts

- Dockerfile
Reference: https://groups.google.com/forum/m/#!topic/golang-announce/2lP5z9i9ySY
> Update golang version to 1.7.4 in Dockerfile, Security Update.

- logger/syslog_windows_test.go
- server/monitor_test.go
* Fixes unit tests running in windows containers with the default configuration.
> Unit Test updates for a windows container environment.

- server/routes_test.go
With the following client fix: https://github.com/nats-io/go-nats/pull/260
the client should always be able to connect after the initial
failure.
> Update client connect to route port test

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
@ColinSullivan1 @petemiron @aricart @wallyqs @kozlovic Please review/give feedback
> [WIP] [ADDED] Add issue and PR templates [CI SKIP]

- server/route.go
> Fix gosimple report

- README.md
Small PR, found there was a missing space before title in readme so that markdown renders it properly
- Markdown fixes
> Readme fixups 

- server/log_test.go
- server/routes_test.go
- server/signal_test.go
Resolves #460
- Two files were showing poor code coverage affecting the overall total.
- Fix to a route test that would fail on Windows.
> Increase code coverage

- .travis.yml
- server/log.go
- server/monitor.go
- server/monitor_test.go
- server/opts.go
- server/route.go
- server/server.go
- server/sublist.go
- server/sublist_test.go
- staticcheck.ignore
> Fixes for staticcheck tests, added misspell check and fixes.

- scripts/cross_compile.sh
> Replaced ARMv5 with ARMv6 in cross_compile

- server/monitor.go
- server/monitor_test.go
> [FIXED] Possible data race in routez when route disconnects

- README.md
- server/const.go
Essentially patch for Windows Docker Images.
> Release 1.0.2

- README.md
Add a community and contribution section that references [NATS.io](https://nats.io), describe the NATS office hours, and link to the office hours agenda.
/cc @bjflanne @nats-io/core
> Add a community section and office hours [ci skip]

- .travis.yml
- server/client.go
- server/route.go
- server/server.go
- server/sublist_test.go
- test/test.go
This tool combines staticcheck, gosimple and unused.
Fixed reports from unused.
> Added megacheck

- README.md
Resolves #  
Update office hours schedule.  We decided to change the date and need to update the readme.
> Update office hours schedule [ci skip]

- README.md
Update the link to the office hours document.
> Update office hours link

- server/monitor.go
- server/monitor_test.go
Resolves #490  
- Adds additional information (the server id) to the JSON that enables tools to associate a particular server process without having to look at the `now` information.
> [ADDED] Server id to connz and routez

- .travis.yml
- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
-Update Dockerfile Go version to 1.9.4
-Add ARM32v6 build of Docker image
> Prepare for release v1.0.6

- CODE-OF-CONDUCT.md
> Add CNCF Code of Conduct

- README.md
> Update to Office Hours

- README.md
Update to gnatsd/README.md fixing authorization section addressing issue #662 "_INBOX.>" permission
> Update to gnatsd/README.md fixing authorization section 

- README.md
Update to gnatsd/README.md clarifying single-user and token-based authentication (issue #316)
> Clarifying single-user and token-based authentication on README.md issue #316

- .travis.yml
- server/configs/reload/srv_a_4.conf
- server/reload_test.go
- server/route.go
- server/server_test.go
> Solicited Routes Reload Fix

- server/client.go
- server/monitor.go
- server/monitor_test.go
- server/parser_test.go
- test/monitor_test.go
> Support for RTT - #643

- server/client.go
- server/parser.go
> Fix for #278

- server/monitor_test.go
- server/server.go
> Make sure closed connection accounting is correct for bad clients

- .travis.yml
- server/client_test.go
- server/norace_test.go
- server/reload_test.go
- server/routes_test.go
- test/cluster_test.go
Fixes for some of the flapping tests we have had.
/cc @kozlovic
> Fix for flaky tests

- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
> Prepare for release 1.2.0

- server/sublist.go
There could be a race introduced between the sublist and the caching layer with the new sync.Map. This holds the read lock to match and to store in the cache.
> Avoid a race between sublist and cache on store

- .travis.yml
- Dockerfile
- Dockerfile.all
- README.md
> Prepare for new release

- server/const.go
- server/sublist.go
> Bump version and fix megacheck report

- README.md
Document route permissions.
Signed-off-by: Colin Sullivan <colin@synadia.com>
> Document route permissions

- server/monitor_test.go
> Fixed flapping tests

- .travis.yml
> Limit cross compile for time were we push a tag

- README.md
> updating README nats.io URL ref to match new doc dir path [ci skip]

- server/nkey.go
- server/routes_test.go
- test/client_cluster_test.go
> Fixed flappers

- server/opts.go
- server/opts_test.go
Issue only in master, no public release is affected.
Resolves #764
> Fixed accounts users loading

- server/config_check_test.go
- server/opts.go
Follow up from #769 .  This enables reporting source of error in config file by default to most configuration errors.
> Include source of configuration error (continued)

- .travis.yml
Resolves #
- use the last Go version for travis CI
> Use the last Go version for travis CI

- server/accounts_test.go
- server/auth.go
- server/client.go
- server/reload.go
- server/reload_test.go
> Added support for Accounts reload

- conf/lex.go
- conf/lex_test.go
> Fix conf parser hang on dangling quote

- server/reload.go
- server/server.go
> Fix data race on config reload with routes and accounts

- server/client.go
- test/bench_test.go
- test/new_routes_test.go
Optimization for subs and qsubs when we send messages over routes. Improved pub/sub a bunch and qsubs a little. Still looking for the qsubs slowdown.
> Optimize subs over routes

- server/accounts.go
- server/client.go
- server/jwt_test.go
Was not handling service import updates or expirations properly.
Also cleaned up some tests for jwts.
> Service Import Updates/Expiration

- server/auth.go
- server/client.go
- server/errors.go
- server/gateway.go
- server/gateway_test.go
- server/monitor.go
- server/opts.go
- server/opts_test.go
- server/parser.go
- server/reload.go
- server/route.go
- server/server.go
- server/server_test.go
- server/split_test.go
- test/gateway_test.go
- test/test.go
> Gateways [WIP]

- server/gateway_test.go
Need to make sure message is received before unsub'ing because
otherwise it would be possible that the unsub happens before
message is delivered, which would have resulted in an RS- while
we were expecting the message to not cause one.
> Fixed gateway flapper

- server/gateway.go
- server/gateway_test.go
We can't use a simple sync.Map here because the noInterest map
for inbound gateway connections are used concurrently. Indeed,
whenever an account would have been registered or a new sub created
this could trigger an update of that map in order to clear the
fact that we had sent an A-/RS- and now are sending an A+/RS+.
So changed to simple map but protected by gw connection's lock.
There was also issue with trying to cache result, which was causing
a map to be possibly updated concurrently which would produce a
panic. Removed that "optimization" for now. Without this change, 
server would panic if there are messages published to cluster A 
while on server B a queue sub is then created on matching subject.
> Fixed race issue with lookup/update of the sent no-interest map

- server/accounts_test.go
- server/auth.go
- server/gateway.go
- server/jwt_test.go
- server/nkey.go
- server/nkey_test.go
- server/reload_test.go
- vendor/github.com/nats-io/jwt/account_claims.go
- vendor/github.com/nats-io/jwt/claims.go
- vendor/github.com/nats-io/jwt/header.go
- vendor/manifest
> Change to RawURLEncoding

- server/events.go
- server/events_test.go
Removed the code getting matching subscriptions and trying
to exclude non internal interest since as soon as there is
routing and/or gateway, it is likely that server would end-up
generating the payload and sending. May need to revisit.
> Allow system messages to cross gateways.

- server/reload.go
- server/reload_test.go
Although Gateways reload is not supported at the moment, I had
to add the trap in the switch statement because it would find
a difference. The reason is the TLSConfig object that is likely
to not pass the reflect.DeepEqual test. So for now, I exclude this
from the deep equal test and fail the reload only if the user
has explicitly changed the configuration.
> Fix config reload that failed because of Gateways

- server/client.go
- server/events.go
- server/events_test.go
- server/server.go
> Enforce account limits on system account too

- server/const.go
- server/events.go
- server/events_test.go
- server/routes_test.go
Added Version and Clustername to StatsZ
Fixed account connection accounting sending after local connections is 0.
> Added server version and cluster name to statsz. Fixed account connection reporting.

- server/accounts.go
- server/client.go
- server/const.go
- server/events.go
- server/events_test.go
- server/nkey.go
- test/operator_test.go
> Internal clients aren't weighed against limits

- server/gateway_test.go
> Added Gateway test for service import with queue group

- server/route.go
This bug is only in master, not in any public release.
> Fixed possible deadlock when updating route permissions

- server/const.go
- server/gateway.go
- server/server.go
> Add more tracing for Gateway connect/ip

- server/client.go
- server/const.go
- server/gateway.go
- server/route.go
This impacted even non gateway traffic
> Fix performance degradation introduced by GW code

- test/new_routes_test.go
- test/test.go
> quick enablement of logging and tracing

- server/accounts.go
- server/client.go
- server/gateway.go
- server/gateway_test.go
- server/route.go
- server/server.go
> Fix Gateways with Service Imports

- server/gateway_test.go
> Add Gateway test for service import and interest only

- server/accounts.go
- server/accounts_test.go
- server/gateway_test.go
- server/reload_test.go
- test/new_routes_test.go
- test/tls_test.go
> Support for service export with wildcards

- server/accounts.go
- server/events.go
- server/events_test.go
- server/jwt_test.go
- server/opts.go
- server/server.go
Fix for exports moving from private back to public did not allow imports to work again.
Added start time to track uptime in Statsz from servers.
More debug printing on export and import processing.
Changed subs reporting for Statsz to sum over all accounts.
> Various small fixes and updates

- .travis.yml
- conf/parse.go
- conf/parse_test.go
- server/accounts.go
- server/client.go
- server/config_check_test.go
- server/errors.go
- server/events.go
- server/jwt_test.go
- server/monitor.go
- server/opts.go
- server/reload.go
- server/route.go
- server/server.go
- server/util.go
Fixed issues reported by staticcheck
> Replace megacheck with staticcheck

- server/client.go
- server/route.go
> Fixed data race

- .gitignore
- util/mkpasswd.go
- replace magic number with constant for mkpasswd
- enhance help usage info for mkpasswd
> remove magic number and enhance help info for mkpasswd

- conf/lex.go
- conf/lex_test.go
> Fix dangling bracket and parens EOF bugs in config parser

- server/parser.go
- server/parser_test.go
- server/split_test.go
> Don't allow overruns for message payloads, fixes #884

- server/client.go
This is a simpler version of a fix from master into the 1.4.0 branch.
> [FIXED] Possible delay in flushing data

- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
> Prepare for release 1.4.1

- server/client.go
- server/events.go
> Some cleanup on outbound and flush

- server/const.go
- server/events.go
- server/events_test.go
> Remove delay for global statsz ping, bumped 2.0 RC version

- server/client.go
- server/const.go
- server/route.go
Would like to merge those 2 fixes in the 1.4.x branch.
[FIXED] Route may disconnect when sending subscription interest
[FIXED] Removing fan-in fix
> Fix route sending of subs list and removing fan-in fix

- README.md
- ROADMAP.md
Correct some words spelling for reading more easily.
File changed:
- README.md
- ROADMAP.md
> Fix some typos

- .travis.yml
> Add Go 1.12 to Travis

- server/gateway.go
- server/reload.go
- server/reload_test.go
- server/route.go
- server/server.go
> [FIXED] Allow use of custom auth with config reload

- MAINTAINERS.md
Add Oleg Shaldibin as maintainer [ci-skip]
> Add Oleg Shaldibin as maintainer [ci-skip]

- README.md
> [FIXED] small typo in README [ci skip]

- README.md
> Gateways: adding documentation in README [ci skip]

- server/client.go
- server/routes_test.go
> Fixed panic when server needs to send message to more than 8 routes

- server/gateway.go
- server/gateway_test.go
- test/new_routes_test.go
Similar to #956 but for gateways code.
> Reduce startup memory for gateways

- server/gateway.go
- server/route.go
- server/server.go
> Fixed invocations of startGoRoutine

- README.md
- server/const.go
> Pre-Release 2.0.0-RC8

- docker/Dockerfile.alpine
Fixes duplicated symlink in the Dockerfile for alpine image
> Fixes to alpine Dockerfile

- server/gateway_test.go
> Fixed gateway test race report

- server/accounts.go
- server/auth.go
- server/norace_test.go
> Fix for reload race on global account

- server/client.go
- server/gateway_test.go
- server/jwt_test.go
TestJWTAccountImportActivationExpires
TestGatewayServiceImportWithQueue
TestGatewayServiceExportWithWildcards
> Fixes for flappers

- README.md
> Pre-Release 2.0.0-RC14

- server/events_test.go
- server/gateway.go
- server/jwt_test.go
- server/monitor_test.go
- server/server_test.go
- test/gateway_test.go
> Fixed some flappers

- server/events.go
- server/events_test.go
The timer was not set with the proper variable, which caused the
check to always think that a new timer should be created, which
would lead to more and more timers being created which translated
to updates being sent more and more frequently.
> Fixed setting timer for account connection updates

- server/client.go
- server/client_test.go
Issue a warning in readLoop if execution of code after connection
Read() until end of for loop reaches a certain threshold.
> Print warning if code in readloop execute for more than threshold

- server/client.go
> Add chunk and total bytes to slow consumer log

- server/accounts.go
- server/auth.go
- server/client_test.go
- server/jwt_test.go
- server/server.go
> Fix for unix time flapper

- server/leafnode.go
- server/server_test.go
> Cleaned up logging for leafnodes

- server/gateway.go
The go routine that is started during interest mode switch was
using the accName (which was a byte slice) instead of account,
which was a string copy of that byte slice. It meant that when
printing the notice, the underlying buffer may have be overwriten
by the readloop.
Changing accName to a string - since we were doing a copy anyway,
better change it at the function param level.
> Fixed race due to use of byte slice instead of string

- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
> Tag v2.0.0-RC19

- README.md
- server/const.go
> Prepare for release 2.0.0

- logger/log_test.go
This PR does following changes
- add log date field format check
- rename `gnatsd` to `nats-server`
- typo fix
> add log date field check

- server/jwt.go
- server/opts.go
> Make ReadOperatorJWT public for embedded use case. Fixes #1050

- server/client.go
- server/const.go
- server/server.go
- test/ping_test.go
- test/test.go
> Stager first ping from server and suppress pings if a ping was received.

- server/sublist.go
- server/sublist_test.go
> Protect stats when no cache is present

- server/leafnode.go
- test/leafnode_test.go
When we have gateways involved we sometime rewrite new subscriptions such that we can properly route in the absence of perfect interest being propagated. Leafnodes are strictly interest only, so if a subscription was initiated in a remote cluster with a subsequent request with a reply it would be rewritten. If delivered to a leafnode the response would not move across the leafnode connection properly since there was no explicit interest in the rewritten response subject.
> Make sure we route  responses across leafnodes

- server/sublist.go
- server/sublist_test.go
> Make sure Sublist.All collect all subscriptions

- test/leafnode_test.go
If two leafnodes solicited the same server in a remote cluster, but were staggered such that the subscription happened before the second leafnode connected, a publish to the second leafnode server would not be delivered.
Resolves #1066 
> Test for staggered leafnodes and sub/pub. Verifies fix for #1066

- server/client.go
- server/leafnode.go
- test/leafnode_test.go
When a solicited leafnode comes from multiple servers that themselves are a cluster, cycles were formed.
This change allows solicited leafnodes to behave similar to gateways in that each server of a cluster
is expected to have a solicted leafnode per destination account and cluster.
We no longer forward subscription interest or messages to a cluster from a server that has a solicited leafnode.
> Prevent multiple solicited leafnodes from forming cycles.

- server/client.go
- server/leafnode.go
- server/opts.go
- test/leafnode_test.go
> Report authorization error and use TLS hostname for IPs on leafnodes.

- server/gateway.go
- server/leafnode.go
- server/server_test.go
Also fix for #1071 in that we need to check remote gateways TLS
config even if main gateway section is not configured with TLS.
Related to #1071
> Add warning for TLS insecure setting on LeafNodes

- server/client.go
This is helpful for clients who send data and close the connection.
Also helpful to process errors like auth for solicited leafnodes.
> If we read data and have an error, still process and parse data.

- server/client.go
- server/client_test.go
> add ut for tracemsg

- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
> Release 2.0.2

- server/auth.go
- test/leafnode_test.go
Updated to match client authentication
Added test
> leafnode user jwt with signer fails to authenticate on solicit

- server/client.go
- test/norace_test.go
> Check response perms more often, make sure we limit memory growth

- server/accounts.go
- server/auth.go
- server/client.go
- server/errors.go
- server/jwt_test.go
- server/monitor.go
- test/ping_test.go
> Added support for user and activation token revocation

- server/monitor.go
> Add leafnode connections to varz

- .travis.yml
> tmp disable of coveralls testing due to site down

- server/errors.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
Resolves #
-
-
-
> cleanup: fix word errors in errors.go

- server/jwt_test.go
> Fix for flapping test

- server/gateway_test.go
- server/routes_test.go
- test/leafnode_test.go
> Fix flappers

- server/events.go
- server/monitor.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
Resolves #
- cleanup codebase
-
-
> Cleanup: fix some typos in code comment

- server/accounts_test.go
- server/client.go
> Prune remote reply tracking

- server/client.go
- server/client_test.go
* Changed some of client.outbound fields to int64.
* Moved fields around to minimize size of struct (checked with unsafe.Sizeof())
* Checked benchmark results before/after
* Added test
Resolves #1118
> [FIXED] MaxPending > MaxInt32 causes client to be disconnected

- go.mod
- go.sum
- server/accounts.go
- test/service_latency_test.go
- vendor/github.com/nats-io/jwt/exports.go
- vendor/github.com/nats-io/jwt/header.go
- vendor/modules.txt
> Add in JWT support for tracking latency

- server/accounts.go
- server/auth.go
- server/client_test.go
- server/jwt_test.go
- server/opts.go
- server/opts_test.go
- Ensure that defaults are set when values are 0
- Fixed some tests
- Added some helpers in jwt tests to reduce copy/paste
> Fixed ResponsePermissions

- go.mod
- go.sum
- vendor/github.com/nats-io/jwt/creds_utils.go
- vendor/github.com/nats-io/jwt/exports.go
- vendor/github.com/nats-io/jwt/header.go
- vendor/github.com/nats-io/jwt/imports.go
- vendor/github.com/nats-io/jwt/operator_claims.go
- vendor/modules.txt
> Updated JWT dependency

- Dockerfile
- Dockerfile.all
- README.md
- server/const.go
> Release v2.1.0

- server/accounts.go
- server/accounts_test.go
- server/config_check_test.go
- server/opts.go
Report error from configuration parsing, and also return error
in AddServiceImport() (and its variants).
> [FIXED] Reject duplicate service import "to" subject

- README.md
> update Slack url link

- server/accounts.go
- server/accounts_test.go
- server/errors.go
> Fix for panic on #1159, do not allow wildcards in stream import prefix

- server/accounts.go
> Fixed nil dereference reported by staticcheck

- server/auth.go
- server/config_check_test.go
- server/leafnode_test.go
This was introduced in master #1147, not in any public release.
> Issue with multiple users in Leafnode authorization

- server/monitor.go
> [UPDATED] Link to monitoring page in new doc [ci skip]

- test/service_latency_test.go
> Fix latency test flapper.

- server/accounts.go
- server/leafnode.go
Code for leafnode loop detection had a data race.
> Fix race introduced in #1170

- server/client.go
- test/gateway_test.go
> Relax check on reserved GW prefix for system clients

- server/accounts.go
- server/events.go
- server/reload.go
- server/server.go
- test/leafnode_test.go
- test/norace_test.go
- test/service_latency_test.go
Also prior this would have leaked subscriptions as well.
> Fixed a bug where we leaked service imports. 

- server/events.go
- server/events_test.go
> Need return when acc not found

- server/leafnode.go
- test/leafnode_test.go
> Allow interest propagation with daisy-chained leafnodes

- server/const.go
- server/parser.go
- test/leafnode_test.go
> [FIXED] Handling of split buffer for LEAF messages

- server/closed_conns_test.go
- server/opts.go
- test/bench_test.go
> Fixed issues reported by staticcheck

- jetstream/README.md
> markdup fixes

- jetstream/jsm/jsm.go
> support TLS on the jsm command

- server/sysmem/mem_windows.go
Resolves #1213
- rename variable k32 to kernel32
- cast uint64 memory size to int64 as other platforms do
> Fixed Memory() for Windows

- server/client.go
- test/bench_test.go
- test/client_cluster_test.go
> Fixes #1144, qsub performance improvements

- jetstream/jsm/jsm.go
- server/filestore.go
- server/memstore.go
- server/msgset.go
- server/observable.go
- server/store.go
similar to c78139c75417ac7c10b61b8a19876cd6355954a9
> report observable config and observables count on message sets

- server/jetstream.go
- server/msgset.go
I think some of this stuff is useful to see on startup - it's how I noticed the obs leak.  Debatable if warning or error level, but this is already helpful
> elevate some logging to improve visibility into corruption

- server/client.go
- server/const.go
- server/gateway_test.go
- server/sublist.go
- server/sublist_test.go
If a subject has empty tokens, returns false.
> [FIXED] Sublist isSubsetMatch to handle empty tokens

- server/observable.go
> npe guard around mset access when sampling acks

- server/client.go
Remove debug trace in writeLoop
> Remove debug trace in writeLoop

- .travis.yml
- README.md
- docker/Dockerfile.alpine
- server/const.go
> Release 2.1.4

- server/opts.go
Allows:
```
server_name: "jetstream"
jetstream {
store_dir: "/tmp/jet"
}
```
> allow jetstream to be enabled in the config file

- server/opts.go
- server/server.go
> add some more jetstream options

- server/configs/panic.conf
- server/opts.go
- server/opts_test.go
This will also result in an error with line number close to the issue.
Basically move parsing into own function.
In there, recover and turn panic into an error.
> [IMPROVED] Replace panic with error during configuration parsing/reload

- main.go
- server/server.go
> [FIXED] Server that is sent the lame duck mode signal does not exit

- server/sublist_test.go
- test/bench_test.go
> Fixed benchmark tests to be able to run with Go 1.13+

- server/opts.go
nsc push automatically adds /accounts. Thats why its added here too.
Operator jwt reload is not supported and is not taken into account.
On startup the AccountResolver url is checked and exits if it can't be reached.
> Using AccountResolver url from operator jwt.

- README.md
- docker/Dockerfile.alpine
- server/const.go
- test/cluster_tls_test.go
- test/new_routes_test.go
> Release v2.1.6

- server/store.go
> ensure deliver policy can be unmarshalled

- server/leafnode_test.go
Make sure that the subscription on "service" is registered on server A.
> Fixed flapper test

- test/leafnode_test.go
Make use of some existing helpers and add checkFor in some places
since accounting updates may not be instantaneous.
> Fix some leafnode test flappers

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
- test/jetstream_test.go
> expose the arrival timestamp in the message metadata

- server/gateway.go
- server/gateway_test.go
- server/route.go
If a node in the cluster goes away, an async INFO is sent to
inbound gateway connections so they get a chance to update their
list of remote gateway URLs. Same happens when a node is added
to the cluster.
> [FIXED] Update remote gateway URLs when node goes away in cluster

- server/jetstream_api.go
> send audit advisories for all api errors

- server/accounts.go
- server/consumer.go
- server/events.go
- server/events_test.go
- server/jetstream_api.go
- test/leafnode_test.go
> add schema fields to service latencies

- doc/README.md
- doc/adr/0001-jetstream-json-api-design.md
> initial Architecture Decision Record repository

- server/jetstream_api.go
> minor fix for json keys on consumer lists

- server/jetstream_api.go
> fix the type hint for msg_get

- server/jetstream_api.go
> ensures that the streams value is never null

- doc/adr/0002-nats-typed-messages.md
> typed messages adr

- server/client.go
- server/client_test.go
- server/const.go
- server/leafnode.go
- server/parser.go
- server/parser_test.go
- server/route.go
- test/new_routes_test.go
- test/service_latency_test.go
- test/test.go
This also fixes a critical bug in the client headers implementation.
> Server support for headers between routes

- server/const.go
- server/filestore.go
- server/memstore.go
- server/store.go
- server/stream.go
- test/jetstream_test.go
- test/service_latency_test.go
Also various bug fixes, flappers, etc.
> Add timestamps to stream state, don't allow stream to overlap with API

- server/gateway.go
- server/gateway_test.go
- server/leafnode.go
- test/leafnode_test.go
> Header support for Gateways and Leafnodes

- server/filestore.go
- server/filestore_test.go
The filestore was updating accounting of msgs and bytes even though the message may have been deleted out from underneath us. Happens with expirations or limits that remove messages.
> Fix for test failure when racing against double deletes.

- server/opts_test.go
> Disable logs in test

- server/leafnode.go
- server/leafnode_test.go
If a leafnode connection is accepted but the server is shutdown
before the connection is fully registered, the shutdown would
stall because read and write loop go routine would not be
stopped.
> [FIXED] Possible stall on shutdown with leafnode setup

- server/consumer.go
We were not forcing a write of consumer state during shutdown.
> Write consumer state during stop if not deleting

- server/consumer.go
- server/filestore.go
- server/jetstream.go
- test/jetstream_test.go
> Properly recover ephemeral consumers after restart

- server/opts.go
> improve consistency between top level and account js options

- server/filestore.go
> Add in snapshot modTime, use PAX format

- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/memstore.go
- server/store.go
- server/stream.go
- test/jetstream_test.go
> Allow snapshots to optionally check all message checksums

- server/consumer.go
- test/jetstream_test.go
Resolves #1436
This also is a redesign for the redelivery system to be much more robust.
> Allow redelivery for AckAll

- server/jetstream_api.go
- server/jetstream_events.go
- server/stream.go
- test/jetstream_test.go
> add advisories and logging for snapshots

- server/accounts.go
- server/client.go
- server/jetstream_api.go
- test/jetstream_test.go
> Do proper ubsubscribe when shutting off restore endpoint

- server/monitor.go
- server/monitor_test.go
Also allow ability to filter based on account.
> Add account details to subsz.

- server/reload.go
- server/reload_test.go
> Add default system account back to accounts after reload

- server/accounts.go
- server/const.go
- server/events_test.go
- server/reload.go
> Don't leak service import subs on claim updates

- go.mod
- go.sum
- server/client.go
- server/gateway.go
- server/leafnode.go
- server/opts.go
- server/route.go
- server/server.go
- test/configs/tls_mixed.conf
- test/tls_test.go
- vendor/github.com/nats-io/nats.go/context.go
- vendor/github.com/nats-io/nats.go/nats.go
- vendor/modules.txt
> Allow mixed TLS and non-TLS on same port.

- server/auth.go
- server/opts.go
- server/server.go
- server/websocket.go
- server/websocket_test.go
Websocket can now override
- Username/password
- Token
- Users
- NKeys
- no_auth_user
- auth_timeout
For TLS, support for verify and verify_and_map. We used to set
tls config's ClientAuth to NoClientCert. It will now depend
if the config requires client certificate verification, which
is needed if TLSMap is enabled.
> Added dedicated auth block for websocket

- server/auth.go
- server/websocket.go
Building server's nkeys and users map out of slices form options
has been made a function so it can be used for the server and
websocket (and in future for mqtt)
> Refactor some code to make it reuseable

- MAINTAINERS.md
> Fix typo in maintainers.md

- server/ping_test.go
The test was not checking that PINGs were sent, however, without
disabling the first short ping and with a very low interval, there
was chance on Travis that the first short ping was sent before
the client had connected, which would break the NATS client protocol
that expects to receive a PONG to initial PING (after CONNECT).
The client library could arguably be updated to accept PING during
the CONNECT phase.
> Fixed TestPing test

- server/route.go
> Avoid data race on cluster name

- server/filestore.go
- server/filestore_test.go
- server/memstore.go
> Run expiration only once at a time and double check cache, fixes #1482

- test/leafnode_test.go
> Fixed flapper

- server/client.go
- server/filestore_test.go
- server/gateway.go
- test/services_test.go
> Allow response permissions to work across accounts

- server/reload.go
- server/reload_test.go
> Support clustername change on reload, fixes #1492

- go.mod
- go.sum
- server/client.go
- server/const.go
- server/reload_test.go
- test/norace_test.go
- test/service_latency_test.go
- test/test_test.go
- vendor/golang.org/x/time/AUTHORS
- vendor/golang.org/x/time/CONTRIBUTORS
- vendor/golang.org/x/time/LICENSE
- vendor/golang.org/x/time/PATENTS
- vendor/golang.org/x/time/rate/rate.go
- vendor/modules.txt
> Update write deadline, client processing and slow proxy

- server/client_test.go
In some tests, async clients are used with a running server (which
was not original intent). This resulted in the client writeLoop
to be started twice.
> Fixed async client tests

- server/consumer.go
- test/jetstream_test.go
> Pending timers could go negative, this is a fix for #1502

- server/reload.go
- server/reload_test.go
> Fix config reload when no changes for leafnode remotes

- server/stream.go
- test/jetstream_test.go
> More checks on duplicate window config, signal in PubAck if duplicate

- doc/adr/0005-lame-duck-notification.md
> adr describing new `ldm` field in the `INFO` protocol.

- server/consumer.go
- server/stream.go
- test/jetstream_test.go
Resolves https://github.com/nats-io/jetstream/issues/260
> Fix for stream delete with many consumers

- server/client.go
- server/events_test.go
The issue was caused by the kind of connections being checked.
Resolves #1527
> [FIXED] Queue subscriptions not able to receive system events.

- server/consumer.go
- test/jetstream_test.go
Allow consumers to specify an optional rate limit for push based consumers.
> Add in push based consumer rate limits

- server/jwt_test.go
The error is disabled by default.
To make it start failing, change errCnt from 0 to 1.
This tests #1532
> Adding unit test demonstrating silent subscription loss

- server/route.go
Changed: removeReplySub, removeRemoteSubs and processRemoteUnsub
This is a follow up to #1538 . Now that we don't fetch on sub, we shouldn't on unsub either.
> Remove unnecessary account fetch from remote remove functions

- server/filestore.go
- server/memstore.go
- test/jetstream_test.go
Resolves https://github.com/nats-io/jetstream/issues/297
> Fix for https://github.com/nats-io/jetstream/issues/297

- server/client_test.go
- server/const.go
- server/server.go
> [FIXED] Possible panic for TLS connections that are aborted early

- go.mod
- go.sum
- server/jwt.go
- server/jwt_test.go
- vendor/github.com/nats-io/jwt/.gitignore
- vendor/github.com/nats-io/jwt/.travis.yml
- vendor/github.com/nats-io/jwt/LICENSE
- vendor/github.com/nats-io/jwt/Makefile
- vendor/github.com/nats-io/jwt/README.md
- vendor/github.com/nats-io/jwt/ReleaseNotes.md
- vendor/github.com/nats-io/jwt/account_claims.go
- vendor/github.com/nats-io/jwt/activation_claims.go
- vendor/github.com/nats-io/jwt/claims.go
- vendor/github.com/nats-io/jwt/cluster_claims.go
- vendor/github.com/nats-io/jwt/creds_utils.go
- vendor/github.com/nats-io/jwt/exports.go
- vendor/github.com/nats-io/jwt/genericlaims.go
- vendor/github.com/nats-io/jwt/go.mod
- vendor/github.com/nats-io/jwt/go.sum
- vendor/github.com/nats-io/jwt/header.go
- vendor/github.com/nats-io/jwt/imports.go
- vendor/github.com/nats-io/jwt/operator_claims.go
- vendor/github.com/nats-io/jwt/revocation_list.go
- vendor/github.com/nats-io/jwt/server_claims.go
- vendor/github.com/nats-io/jwt/types.go
- vendor/github.com/nats-io/jwt/user_claims.go
- vendor/github.com/nats-io/jwt/v2/decoder_user.go
- vendor/github.com/nats-io/jwt/v2/go.mod
- vendor/github.com/nats-io/jwt/validation.go
- vendor/modules.txt
updates jwt library. This fixes an issue where limits where initialized wrong. (issue was caused by v1 to v2 conversion)
> Update JWT and incorporate change of cidr ranges from string to array

- server/jwt.go
- server/jwt_test.go
Basically interpret the time range with the given locale.
Once we moved from a time range to a time (with date) convert the time to the location of the server.
changes to the unit test consist of wrapping one test in a for loop.
`for _, l := range []string{"", "Europe/Berlin", "America/New_York"} `
> Support locale for times in user jwt

- server/monitor.go
- This PR fixes a Mixed Content warning in web browsers when viewing the monitoring webpage.
> [CHANGED] nats.io resources from HTTP to HTTPS

- server/events.go
- server/events_test.go
This is the low hanging fruit.
Take existing monitoring endpoints that allow to filter by account.
Expose these endpoints on an account specific subject. 
Extract account id from subject and set the account filter. (this will overwrite whatever other value may have been specified) 
I also moved CONNS into that setup loop.
> Expose SUBSZ and CONNZ monitoring endpoints for accounts

- go.mod
- go.sum
- server/accounts.go
- server/server.go
- vendor/github.com/nats-io/jwt/v2/exports.go
- vendor/github.com/nats-io/jwt/v2/imports.go
- vendor/github.com/nats-io/jwt/v2/user_claims.go
- vendor/modules.txt
> Updated jwt library and check (account & token) issuer prior to jwt Validate

- server/const.go
> Bump version

- go.mod
- go.sum
- server/accounts.go
- server/auth.go
- server/jwt_test.go
- vendor/github.com/nats-io/jwt/v2/account_claims.go
- vendor/github.com/nats-io/jwt/v2/revocation_list.go
- vendor/github.com/nats-io/jwt/v2/validation.go
- vendor/modules.txt
Also empty revoked keys once account jwt has no revocations.
> [Fixed] revocation check used current time instead of jwt issue time

- server/accounts_test.go
- server/gateway_test.go
- server/monitor_test.go
- server/route.go
- server/routes_test.go
- server/server.go
- test/new_routes_test.go
- test/routes_test.go
> Accepting route warns if remote server has same name

- server/opts.go
Re introduced that one during changes to PR...
> Fixed crash on non existing directory

- server/jetstream_api.go
- server/monitor.go
- test/jetstream_test.go
> fix npe for offsets larger than items

- server/websocket.go
- server/websocket_test.go
> Fix typo in websocket err message

- server/events.go
> add type hints num accounts message

- server/monitor.go
This endpoint is for debugging, so we shouldn't rely on things not being nil.
Also include validation results and missing mapping
> Fix nil deref when account is in bad/incomplete state

- server/client.go
- test/service_latency_test.go
Addresses stack overflow issue wally was seeing with configs
that mix and match streams and services between each other.
> Do not forward service import messages to a stream export.

- server/monitor.go
> Adding more debugging information to accountz

- docker/Dockerfile.nightly
> include nsc nightly binaries

- server/stream.go
- test/jetstream_test.go
Resolves https://github.com/nats-io/jetstream/issues/340
> Purge clears dedupe window as well

- main.go
> Fixed no_advertise comment in `nats-server -help`

- README.md
- server/filestore.go
- server/filestore_test.go
Also changed the link to travis-ci.com instead of .org
> JetStream: clear erased bit when reading sequence number

- server/consumer.go
- server/stream.go
- test/jetstream_test.go
> Would not properly handle wildcard streams with interest retention and filtered consumers

- server/consumer.go
- test/jetstream_test.go
> ensure bare AckNxt requesting >1 is supported

- test/jetstream_test.go
> Fix for flapper and additional consumer perf test

- test/jetstream_test.go
> Flush after purge too

- server/disk_avail.go
- server/disk_avail_windows.go
- server/jetstream.go
> Separate out disk available for Windows

- server/consumer.go
- test/jetstream_test.go
> support next structure in acknxt

- .goreleaser.yml
- README.md
- server/const.go
This is based on branch_2_1_x and includes the following fixes:
- Possible panic if server receives a maliciously crafted JWT.
- User and claims activation revocation checks.
- Panic on shutdown while accepting TLS client connections.
- Added defensive code for handling of Leafnode connections.
> Release v2.1.9

- doc/adr/0004-nats-headers.md
> Clarify HPUB and HMSG examples

- server/consumer.go
- server/stream.go
- test/jetstream_test.go
> Remove conditional and broadcast for signalling consumers

- server/consumer.go
- test/jetstream_test.go
> Fix flapper, be pedantic about signaling on delivery subject update

- server/consumer.go
- server/sublist.go
- server/sublist_test.go
- test/jetstream_test.go
> Make interest notifications explicit match only

- server/filestore.go
When under load a call to `LoadMsg()` could return the wrong error since we did not snapshot the last sequence properly and would read it after.
Fixed race condition on clearing cache.
> Fixed bug and a race condition

- server/consumer.go
- test/jetstream_test.go
> Add support for MaxAckPending

- server/jetstream_api.go
- test/jetstream_test.go
> support json requests for stream lookup

- server/fuzz.go
The updates in the fuzzers fix the broken oss-fuzz build locally. Once merged I will run the oss-fuzz integration tests again.
> Updated fuzzer

- server/consumer.go
Went from ~2400ns with 8 allocations to 60ns and 0 allocations.
> Optimize ackReply parsing

- server/filestore.go
- server/filestore_test.go
- test/jetstream_test.go
When all messages where deleted we could forget the sequence number that we should be starting back off with on restart/receovery.
This also fixes a few minor other bugs.
> Fix for not properly recovering first sequence number on recovery.

- server/accounts.go
- server/client.go
- server/consumer.go
- test/jetstream_test.go
> Allow complete $JS.API to be imported from another account.

- server/leafnode_test.go
- server/parser.go
If a LeafNode message is sent across a route, and the message
does not fit in the buffer, the parser would incorrectly process
the "pub args" as if it was a ROUTED message, not a LEAF message.
This caused clonePubArg() to return an error that would cause
the parser to end with a protocol violation.
Keep track that we are processing an LMSG so that we can pass
that information to clonePubArg() and do proper parsing in split
scenario.
Resolves #1743
> [FIXED] Split LMSG across routes

- server/leafnode.go
A newly introduced test (TestLeafNodeTwoRemotesBindToSameAccount)
had a server creating two remotes to the same server/account.
This test quite often show the data race:
```
go test -race -v -run=TestLeafNodeTwoRemotesBindToSameAccount ./server -count 100 --failfast
=== RUN   TestLeafNodeTwoRemotesBindToSameAccount
Write at 0x00c000168790 by goroutine 34:
github.com/nats-io/nats-server/v2/server.(*client).processLeafNodeConnect()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/leafnode.go:1177 +0x314
github.com/nats-io/nats-server/v2/server.(*client).processConnect()
/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/client.go:1719 +0x9e4
github.com/nats-io/nats-server/v2/server.(*client).parse() …
```
> Fixed data race on leafnode check for remote cluster

- server/consumer.go
- server/filestore.go
- server/filestore_test.go
This was also the flapper test we had for **TestJetStreamConsumerMaxDeliveryAndServerRestart**.
We were not properly restoring our state for consumers and we also had a bug where we would not properly encode and write redelivered state.
> Fixed bug restoring consumer state

- server/stream.go
- test/jetstream_test.go
> ensure the stream originating a pub error is reported

- server/filestore.go
- server/filestore_test.go
- server/jetstream_api.go
- server/memstore.go
- server/memstore_test.go
- server/store.go
- server/stream.go
> Added Compact to store interface for WAL functionality

- docker/Dockerfile.nightly
> use the natscli repo instead of jetstream

- server/mqtt.go
- server/mqtt_test.go
- Keep track of published topic to avoid conversion in some case
- Rework tracing of some MQTT protocols
- Rework topic-to-subject conversion
- Update some tests
> MQTT updates

- docker/Dockerfile.nightly
> use new nats code location

- test/jetstream_test.go
> Fix flapper

- server/accounts.go
- server/client.go
- server/parser.go
- test/accounts_cycles_test.go
> Catch condition where a serviceImport response matched the original import.

- server/filestore.go
- server/filestore_test.go
Resolves #https://github.com/nats-io/jetstream/issues/406
> Fix for https://github.com/nats-io/jetstream/issues/406

- go.mod
- go.sum
- server/accounts.go
- server/jwt_test.go
- server/monitor.go
- vendor/github.com/nats-io/jwt/v2/account_claims.go
- vendor/github.com/nats-io/jwt/v2/activation_claims.go
- vendor/github.com/nats-io/jwt/v2/exports.go
- vendor/github.com/nats-io/jwt/v2/genericlaims.go
- vendor/github.com/nats-io/jwt/v2/go.mod
- vendor/github.com/nats-io/jwt/v2/header.go
- vendor/github.com/nats-io/jwt/v2/imports.go
- vendor/github.com/nats-io/jwt/v2/revocation_list.go
- vendor/github.com/nats-io/jwt/v2/types.go
- vendor/modules.txt
> [Added] ability to use jwt latency sampling properties headers/share

- server/leafnode.go
- test/leafnode_test.go
The server that solicits a LeafNode connection does not send an
INFO, so the accepting side had no way to know if the remote
supports headers or not. The solicit side will now send the headers
support capability in the CONNECT protocol so that the receiving
side can mark the inbound connection with headers support based
on that and its own support for headers.
Resolves #1781
> Fixed headers support for inbound leafnode connection

- dependencies.md
> Create dependencies.md [ci skip]

- go.mod
- go.sum
- server/jwt_test.go
- server/opts_test.go
- vendor/github.com/nats-io/jwt/v2/types.go
- vendor/modules.txt
> Added tests for cfg/jwt based queue restrictions and updated jwt lib

- server/jetstream.go
- server/jetstream_cluster.go
> Fixes for data races

- server/client.go
- server/leafnode.go
- server/leafnode_test.go
- test/leafnode_test.go
> Fixed some leafnode issues introduced from JS cluster work

- go.mod
- go.sum
- server/accounts.go
- server/const.go
- server/consumer.go
- server/events.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/raft.go
- server/stream.go
- test/jetstream_cluster_test.go
- test/jetstream_test.go
- vendor/github.com/nats-io/nats.go/context.go
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/jsm.go
- vendor/modules.txt
Added in support for stream update as well as stream and consumer detailed lists which use a scatter and gather approach.
> Clustering updates

- server/client.go
- server/const.go
- server/consumer.go
- server/events.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_events.go
- server/raft.go
- server/route.go
- server/server.go
- server/store.go
- server/stream.go
- test/jetstream_cluster_test.go
- test/jetstream_test.go
This adds in optional reporting to stream and consumer info when running in clsutered mode.
> Report on RAFT group information.

- server/accounts.go
- server/auth.go
- server/client.go
- server/events.go
- server/jwt_test.go
- server/monitor.go
- server/server.go
Also added a trace on jwt authentication
```
[53472] [TRC] 127.0.0.1:51931 - cid:3 - "v1.11.0:go" - Authenticated JWT: Client "UAW2WHOE5AKJHEWVHJJMDWSVIN4BHU2HGNFKS4ZL2JOZ5RN774CP3ZVF" (claim-name: "a name", claim-tags: ["tags" "other"]) signed with "ACMAPDNT4LQZU6GYD22JVXLUZJT6AK4ONHKIB4TSJEAUHAEOONFLY22R" by Account "ACMAPDNT4LQZU6GYD22JVXLUZJT6AK4ONHKIB4TSJEAUHAEOONFLY22R" (claim-name: "", claim-tags: []) signed with "OCAT33MTVU2VUOIMGNGUNXJ66AH2RLSDAF3MUBCYAY5QMIL65NQM6XQG"
[53472] [TRC] 127.0.0.1:51932 - cid:4 - "v1.11.0:go" - Authenticated JWT: Client "UAW2WHOE5AKJHEWVHJJMDWSVIN4BHU2HGNFKS4ZL2JOZ5RN774CP3ZVF" (claim-name: "a name", claim-tags: ["tags" "other"]) signed with "ACMAPDNT4LQZU6GYD22JVXLUZJT6AK4ONHKIB4TSJEAUHAEOONFLY22R" by …
```
> [added] jwt/issuerkey/nametag/tags to monitoring and event endpoints

- server/const.go
> Bump version's beta

- server/const.go
- server/consumer.go
- server/events.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/stream.go
- test/jetstream_cluster_test.go
- test/jetstream_test.go
> Added support for clustered account info and limit enforcement

- server/jetstream_cluster.go
- server/stream.go
> Change over last to active and a duration

- go.mod
- go.sum
- test/jetstream_cluster_test.go
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/jsm.go
- vendor/github.com/nats-io/nats.go/nats.go
- vendor/modules.txt
> Use client version for stream and consumer extended info

- server/jetstream_api.go
- server/jetstream_cluster.go
- test/jetstream_cluster_test.go
> Fixes for cluster info when R=1 and consumer names lists in clustered mode.

- .github/workflows/go-test.yaml
- server/const.go
- server/jetstream_api.go
- server/raft.go
- server/server.go
- test/jetstream_cluster_test.go
- test/jetstream_test.go
Some raft changes for split vote scenarios which leads to some flappers. LDM support for raft leaders and some other fixes.
> LDM Support, Raft updates, fixes

- server/raft.go
- test/jetstream_cluster_test.go
- test/jetstream_test.go
- test/leafnode_test.go
> Fix for blocking on a channel for the raft impl, various test fixes for flappers.

- server/leafnode_test.go
- server/mqtt_test.go
> Fixing some flappers (leafnode and mqtt)

- server/raft.go
> Fix for split vote bug

- go.mod
- go.sum
- server/events.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/raft.go
- test/jetstream_cluster_test.go
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/jsm.go
- vendor/modules.txt
Also various fixes for bugs and data races.
> Added in raft quorum tracking and stepdown and API responses.

- server/jetstream_cluster.go
- test/jetstream_cluster_test.go
Small bug prevented memory store backed streams and consumers. 
> [FIXED] Fixed bug to allow memory store for clustering

- server/errors.go
- server/jetstream_cluster.go
- test/jetstream_cluster_test.go
> Fix for broken stream restore functionality

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_events.go
- server/stream.go
- test/jetstream_cluster_test.go
> Updates to leader elect and lost quorum advisories and log entries.

- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/stream.go
- test/jetstream_cluster_test.go
> Extended AccountInfo to track API calls and errors.

- server/jwt.go
- server/monitor.go
- server/monitor_test.go
- server/opts.go
> [added] field to varz output containing the operator jwt

- server/events.go
- server/jetstream_cluster.go
- server/raft.go
- server/stream.go
- test/jetstream_cluster_test.go
> Suppress additional advisories on server restart and leadership changes.

- server/jetstream_cluster.go
Noticed in the logs a few of these entries when running tests:
```
Did not receive all stream info results
```
In case there are no consumers for a stream, sends response with the empty list without waiting.
> js: consumer list request fix

- server/stream.go
- test/jetstream_cluster_test.go
Fixed a bug that on restore of single streams in clustered mode would subscribe to the stream subjects twice.
> [FIXED] Bug on single replica restore would deliver duplicate messages.

- server/jetstream_cluster.go
- server/raft.go
- test/jetstream_cluster_test.go
- test/norace_test.go
> Fixed bug on raft inline catchup when apply channel was full.

- .travis.yml
- server/consumer.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/stream.go
- test/jetstream_cluster_test.go
> Make sure to suppress duplicate create/delete audit events

- server/accounts.go
- server/jwt_test.go
This corresponds to changes we did in jwt code as well
> [removed] activation token download

- server/jetstream.go
- server/monitor.go
> Modified jetstream varz information

- server/jetstream_cluster.go
This would cause high cpu usage and memory usage.
Also made consumer Created() UTC.
> Noticed stream snapshots were being processed on recovery

- server/jetstream_api.go
- test/jetstream_cluster_test.go
> Make direct message retrieval from stream cluster aware.

- server/jetstream_cluster.go
- test/jetstream_cluster_test.go
> Make peer reassignment supercluster aware.

- server/consumer.go
- server/events.go
- server/events_test.go
- server/monitor.go
- server/monitor_test.go
- server/server.go
@ripienaar format and functionality what you had in mind? Currently I page on account level
sample:
```json 
{
"server_id": "NBPTR6WDBM3YG5W36KJ6ER2YZC3MVHSAMXIYEXKUSBX5R2X67NJ5EPCU",
"now": "2021-02-03T18:35:39.107669-05:00",
"config": {
"max_memory": 10485760,
"max_storage": 10485760,
"store_dir": "/var/folders/9h/6g_c9l6n6bb8gp331d_9y0_w0000gn/T/srv_7500046161537"
},
"memory": 0,
"storage": 66,
"api": {
"total": 5,
"errors": 0
},
"total_streams": 2,
"total_consumers": 2,
"total_messages": 1,
"total_message_bytes": 33,
"meta_cluster": {
"name": "cluster_name",
"leader": "server_5500",
"replicas": [
{
"name": "server_5500",
"current": true,
"active": 2563000
}
]
},
"total_streams_non_replicated": 1,
"total_streams_in_quorum": 1, …
```
> [added] jsz nats and http monitoring endpoint for jetstream

- server/client.go
- server/consumer.go
- server/events.go
- server/events_test.go
- server/filestore.go
- server/filestore_test.go
- server/gateway.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_events.go
- server/jwt_test.go
- server/monitor_test.go
- server/raft.go
- server/route.go
- server/server.go
- server/store.go
- server/stream.go
- test/jetstream_cluster_test.go
- test/norace_test.go
More stability improvements to the raft core.
Made filestore better at handling write errors and propagating them.
Removed majority of MarshalIndent.
> JetStream updates and improvments

- server/monitor.go
Speaking with @ripienaar it seemed like a good option to ask the jsz endpoint to only respond if its the leader, since for the metacluster information only the leaders information is useful.
@matthiashanel could you review and possibly add some tests (apologies for that).
> Added leader only response for jsz.

- server/events_test.go
- server/monitor.go
- server/monitor_test.go
> [added] system_account to varz/accounts and is_system_account to accountz

- server/accounts_test.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/opts.go
- server/reload.go
- server/server.go
Also easier way to put authorization on system account and still use $G.
> Allow meta leader stepdown.

- server/monitor.go
> fix jsz when server is not started in cluster mode and fix landing page

- .gitignore
- server/accounts.go
- server/client.go
- server/events.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/parser.go
- server/raft.go
- server/stream.go
> Changes needed to properly support multi-layer service imports

- server/jetstream_test.go
- server/raft.go
> Set pindex to wrong setting on snapshot restore with no WAL

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/raft.go
> Restoration of streams would possibly block route and client connections.

- .github/workflows/nightly.yaml
> enable manual triggers of nightly builds

- .github/workflows/nightly.yaml
> revert to previous checkout version

- server/gateway.go
- server/gateway_test.go
If a gateway is configured with an authorization block containing
username and password and accepts an unknown Gateway connection,
when initiating the outbound connection, it should use the
gateway authorization's user/pass information.
Resolves #1912
Resolves #
-
-
-
> [FIXED] Gateway's implicit connection not using global user/pass

- server/jetstream_cluster.go
- server/jetstream_events.go
- server/raft.go
- server/server.go
- test/norace_test.go
General stability improvements on catch up, restore and snapshot.
> Better restore logic

- server/const.go
- server/jetstream_cluster.go
- server/raft.go
> Some stability improvements to raft lib and catchup stream processing.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/raft.go
> various bug fixes, wal/snapshot stability

- .goreleaser-nightly.yml
- docker/Dockerfile.nightly
> add version strings to the nightly builds of nats cli

- server/client.go
When pulling consumer messages if the consumer and the client were o the same server we needed to process local deliver subject.
> Properly handle local deliver subjects

- server/jetstream_api.go
- server/jetstream_cluster.go
> ensure sources and mirror info is in stream list

- server/client.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_events.go
- server/raft.go
- server/store.go
- server/stream.go
Also tweaked some write/sync params.
> [FIXED] Bug where followers would not snapshot/compact WAL.

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_events.go
- server/raft.go
> extend the out of space advisory

- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
Moved this into a separate branch as per @wallyqs suggestion.
> changing NEXT expires field from time to duration in nanoseconds

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
Bug fix for lockup in raft on blocking channels.
Bug fix for off by one bug on out of band catchup.
> Stability Updates

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
> Consumers were double processing as leaders.

- server/jetstream_api.go
- server/jetstream_cluster_test.go
> update api types, remove meta peer by id

- server/client.go
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/stream.go
> Enable cross account behaviors for mirrors and sources.

- go.sum
- server/jetstream_api.go
- server/jetstream_cluster_test.go
> restore meta peer remove by name rather than id

- server/const.go
- server/consumer.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
- server/reload.go
- server/stream.go
Better handling on out of disk.
Suppress some stream and consumer bad results since they delete the asset.
Allow rehup to re-enable JetStream.
Changes to handle short writes. Bug fixes to truncation.
Fixed leaking consumer info sub
> Various bug fixes and improvements to out of disk handling.

- server/consumer.go
- server/jetstream_cluster_test.go
Found that the following panic can happen with `m.Respond([]byte("+NXT"))`.
```
panic: runtime error: slice bounds out of range [:57] with capacity 3
goroutine 6441 [running]:
github.com/nats-io/nats-server/v2/server.(*client).msgParts(...)
/Users/wallyqs/repos/nats-dev/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20210305172713-34f66748770a/server/client.go:2136
github.com/nats-io/nats-server/v2/server.(*consumer).processNextMsgReq(0xc001a4c900, 0x0, 0xc000abe600, 0xc001410870, 0x2e, 0xc000a47c38, 0x11, 0xc0002f69fd, 0x0, 0x3)
/Users/wallyqs/repos/nats-dev/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20210305172713-34f66748770a/server/consumer.go:1596 +0x835
```
> Fix check from next request msg

- server/const.go
- server/consumer.go
- server/filestore.go
- server/jetstream.go
- server/jetstream_cluster.go
- server/memstore.go
- server/raft.go
- server/store.go
- server/stream.go
> Memory cache for commits and WAL size constraints.

- server/const.go
- server/jetstream_cluster.go
- server/raft.go
- server/stream.go
We had issues with multiple publishers or sources causing ordering issues.
> Need to make sure order of clseq as stamped is preserved.

- server/consumer.go
- server/filestore_test.go
- server/store.go
- server/stream.go
> Updates to JS consumer references in comments/errors

- server/events_test.go
travis ran into this:
```
=== RUN   TestSystemAccountWithGateways
events_test.go:1625: Expected subject $SYS.ACCOUNT.$G.SERVER.CONNS but got $SYS.ACCOUNT.AASFGYFS64ODVDAUGE6DRHTGWQK4REMJF2FC2RSZCBSI6IULEPPWF6N6.SERVER.CONNS
--- FAIL: TestSystemAccountWithGateways (0.06s)
```
Without the flush, we'd receive the connect message of the connect in line 1588.
This messed up the test logic. 
I cleaned that up as well and added more tests. (check if the Connect message is from the correct cluster)
> Fix unit test that received an extra connect message

- server/const.go
- server/consumer.go
- server/gateway.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/stream.go
> Make source and mirror consumers direct.

- server/raft.go
Under some failure conditions a stream replica set could end up with `cluster size < 2` and failing to restart with a `raft: cluster too small` error unless removing a peers.idx file out of band.  We relax this check to allow starting the cluster if we are aware of other known peers which would help recover the state as well.
Also, sometimes the clustersize could end up in 0 or -1 values when restarting JS in nodes were it had become disabled:
```
[70376] 2021/03/11 12:06:03.265984 [DBG] RAFT [NUmM6cRx - S-R3F-hT2jragG] Expanding our clustersize: -1 -> 0
```
prevent that from happening as well by capping the number to be positive (consider at least one node in the cluster always).
> raft: Fixes to cluster size check for streams

- server/accounts_test.go
- server/const.go
- server/consumer.go
- server/events.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/monitor.go
- server/raft.go
- server/reload.go
- server/server.go
- server/stream.go
- test/norace_test.go
Tweaked raft leader election under transfer or campaign.
Changed raft startup to not require certain cluster size.
Tweaked default block size for streams.
> JSC Updates

- server/monitor.go
> Avoid lock inversions.

- server/jetstream.go
> update banner url

- server/client.go
- server/consumer.go
> improve log line when account registration fails

- server/jetstream_cluster_test.go
- server/stream.go
> Mirror consumers were not able to restart after initial failure.

- server/consumer.go
- server/jetstream_test.go
If a filtered consumer was backed by a busy stream then idle heartbeats for the idle consumer would be suppressed.
> Fix for filtered consumers and idle heartbeats.

- server/auth.go
> ensure connect events are always sent

- server/const.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/stream.go
> Can not use sub comparisons for old messages from direct consumers.

- server/const.go
- server/consumer.go
- server/jetstream_cluster_test.go
- server/stream.go
Add last delivered sequence to consumer idle heartbeats.
> Reworked sources and mirrors on missed data.

- server/const.go
- server/consumer.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
Also allow chaining of sources and mirrors with filtered consumers.
> Fix for bad behavior with flow control and multiple sources streams.

- server/const.go
- server/consumer.go
- server/jetstream_cluster_test.go
- server/raft.go
This code changes the way we handle raft based proposals for consumers.
> Durable consumers with R>1 had performance challenges.

- server/accounts.go
- server/dirstore.go
- server/dirstore_test.go
- server/jwt_test.go
2 commits:
1: adding ability to remove account jwt.
2: when doing so disconnect clients and disable account. 
In lieu of account removal inside the server (preferred), I had to add this stop gap measure as this would have been the next ask.
> Jwt remove

- server/jwt_test.go
Test was failing with the following due to upstream changes in the Go client after latest client update:
```
=== RUN   TestJWTUserRevocation
jwt_test.go:4425: Expected connection to have failed
--- FAIL: TestJWTUserRevocation (2.15s)
```
> Fix to authentication revoked test

- go.mod
- go.sum
- server/jwt_test.go
- vendor/github.com/nats-io/nats.go/go.mod
- vendor/github.com/nats-io/nats.go/go.sum
- vendor/github.com/nats-io/nats.go/js.go
- vendor/github.com/nats-io/nats.go/nats.go
- vendor/modules.txt
One test had a race.
For the other one, the updated go client changed the callback used.
> Updated go client for unit tests and fixing test

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
> During repeated server restarts or failures consumer state could drift between replicas.

- server/client.go
> [Fixed] remote subscription leak for leafnodes caused by auto unsubcribe

- server/mqtt.go
- server/mqtt_test.go
In error conditions or when replacing an existing sub qos1 to qos0,
we were unsubscribing the NATS subscription, but that would not
have been propagated across the cluster.
Also fixed a flapper
> [FIXED] MQTT: make sure unsubscribe is propagated

- README.md
- go.sum
- server/const.go
> Release v2.2.1

- server/errors.go
> Adding back public error ErrAccountResolverSameClaims

- server/monitor.go
> ensure varz subscriptions consider all accounts

- server/stream.go
> If a mirror was removed or changed this would panic.

- server/filestore.go
> Quiet race detector

- server/jetstream_cluster_test.go
Added back the mixed mode test with accounts to have a test for cluster size stepdown.
> Add mixedmode test back in

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
> Only adjust cluster size when we have heard from all peers.

- server/leafnode_test.go
> Fixed leafnode flapper

- server/filestore.go
> Make sure we do not set last to -1

- server/consumer.go
- server/jetstream_cluster_test.go
> Pull based consumers when deleted were not removing messages from an interest retention stream.

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
- server/stream.go
Allow deleted details if requested.
Clients owners may be impacted and will need to update clients. 
/cc @wallyqs @variadico @aricart @scottf 
> Change to report total deleted by default for stream info.

- server/stream.go
> Make sure to stop unneeded retries for mirror consumers.

- server/jetstream_cluster_test.go
Added more test to make sure we properly scale up and down peer set sizes when extending JetStream across hub and leafnode clusters.
> Add in more extensive test on extending hubs with leafnode clusters

- server/stream.go
> Cleanup request subscription if no answer

- server/jetstream_cluster_test.go
- server/stream.go
> Check that we have mirror still to not panic and deadlock/hang

- server/jetstream_cluster_test.go
> Use lower ports to not collide with -1s

- server/const.go
- server/consumer.go
- server/jetstream_cluster_test.go
- server/stream.go
> Make sure that ephemerals are cleaned up across gateways.

- server/jetstream_api.go
- server/jetstream_cluster_test.go
> Make sure to return no consumer error if we are still waiting on a leader.

- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
> Check for overlapping subjects on stream update.

- server/jetstream_api.go
this gives a stream/consumer leader time to respond first
I went with 500 ms as I still saw the issue with 250. (the leader is under full load)
Since the group is not available in all cases, I do not use that channel.  (don't think responding would be a big problem)
When we address responding by non leader via a queue, I think this code will change
> Delaying stream/consumer error response when there is no contact to meta

- server/jetstream_cluster.go
This can lead to a data race and is not needed after being applied.
> Do not persist or snapshot consumer state after a restore.

- server/monitor.go
- server/monitor_test.go
> [added] leaf deny exports/imports to varz monitoring

- server/raft.go
This also adjust the minimum election timeout to 2 seconds vs just 1 for very large networks.
> Under heavy load a leader change could warn about not processing entry responses.

- server/errors.go
- server/filestore.go
- server/filestore_test.go
- server/jetstream.go
- server/jetstream_cluster_test.go
> [FIXED] Stream byte limit setting failed on dynamic account, filestore not honoring blksize.

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_test.go
- server/opts.go
- server/sublist.go
> Check for bad domain names

- server/consumer.go
- server/jetstream_cluster_test.go
- server/stream.go
> [FIXED] Mirror/Source streams from work queues and a deadlock on interest streams.

- server/consumer.go
- server/jetstream.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_events.go
- server/stream.go
> add domain in JS advisories

- server/consumer.go
> When dealing with filtered subjects do not assume the current state

- server/consumer.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
We needed to account for consumers having filtered subjects configured but not really being filtered.
> Fix for failing test

- server/errors.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/stream.go
When using multiple source streams from either different accounts or domains, the stream name could be the same and would cause bad behavior.
Resolves: #2202 
> [FIXED] Issue #2202

- server/jetstream.go
- server/jetstream_test.go
- server/server.go
> [FIXED] A store directory on disk without 'jetstream' could appear to lose assets on restart.

- README.md
- server/const.go
> Release v2.2.4

- server/client.go
- server/jetstream_cluster_test.go
> Under double import scenarios we could possibly map to the wrong subject.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/raft.go
Also fixed another flapping test.
> Changed remove peer logic to wait for RemovePeer entry to be replicated.

- server/stream.go
> Fix a data race.

- server/jetstream_cluster_test.go
> Mapped cross account test

- server/mqtt.go
- server/mqtt_test.go
Say with a cluster of 3, all MQTT assets are created with a replicas
of 3. However, when a server is shutdown, then any new MQTT client
will fail to connect because we try to create a session stream
with R(3), which leads to insufficient resources.
The longer term solution should be for the server to allow the
creation of an asset with a R() value that is bigger than the
current number of running servers as long as there is quorum.
For now, we will reduce the R() value for the sessions if we get
an "insufficient resources" error.
Note that the other assets still will use the compute R() based
on cluster size. So the first time that a client on a given
account is started, we will still need to have R() == cluster size
(at least for R(3)).
Partially resolves #2226
Signed-off-by: Ivan …
> [FIXED] MQTT: session fails if the number servers below cluster size

- README.md
- server/const.go
> Release v2.2.5

- server/jetstream.go
- server/jetstream_cluster_test.go
> Fix for varz JetStream usage showing total account usage vs server usage.

- README.md
- server/const.go
> Release v2.2.6

- server/raft.go
This would cause CPU spikes and catch-up cycles that could spin.
> [FIX] Avoid spinning when we are in a cacth-up phase but first message matches index but not term.

- server/jetstream_api.go
- server/jetstream_test.go
> Fix for #2290

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_errors_test.go
> further tagged error confusion cleanups

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
- server/stream.go
This will allow purge by subject and the ability to specify the sequence or number of messages to keep.
> Allow for more advanced purge operations.

- server/filestore.go
- server/jetstream_cluster_test.go
- server/memstore.go
- server/sublist.go
Fix for purge and keep when keep == total msgs.
Fix for purge with keep but no filtered subject.
> Fixes to PurgeEx

- server/websocket.go
- server/websocket_test.go
For compression, continuation frames had the compress bit set, which is
wrong since only the first frame should.
For decompression, continuation frames were decompressed individually
instead of assembling the full payload and then decompressing.
Resolves #2287
> [FIXED] Websocket (de)compression issues with continuation frames

- server/filestore.go
- server/jetstream_cluster_test.go
- server/memstore.go
> Fix for extended purge by sequence.

- server/norace_test.go
> test to show slow purges

- server/reload_test.go
- server/server.go
This was introduced by PR#1900 by detecting that a single system
account was configured. A "fake" user name was created and added
to the list of users and set as a no_auth_user.
However, on config reload, a new fake user was created, which
would cause existing connected clients to be disconnected.
Resolves #2282
> [FIXED] Clients disconnected on reload when only $SYS account configured

- doc/adr/0006-protocol-naming-conventions.md
Proposal for protocol naming convention
> 0006-protocol-naming-conventions

- README.md
- server/const.go
> Release v2.3.0

- server/filestore.go
- server/jetstream_api.go
- server/jetstream_test.go
- server/memstore.go
- server/store.go
This is to aid in K/V overlay for simple Get ops vs creating a full blown consumer.
> Added in Stream get last message by subject.

- server/consumer.go
- server/errors.json
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/jetstream_errors_generated.go
- server/jetstream_test.go
> FIXED max consumers was not enforced when set on stream.

- server/errors.json
- server/jetstream_errors_generated.go
- server/store.go
- server/stream.go
Some of these are quite generic errors that can happen a lot
in normal circumstances so no need to be too noisy about them
Fixes one missed old style Api Error
> do not log at Error level for some store failures

- server/filestore.go
- server/jetstream_test.go
- server/stream.go
> Added ability to match based on last expected sequence per subject.

- server/accounts.go
- server/jetstream_cluster_test.go
> Protect account prand, use faster Uint64 variant

- doc/adr/0010-js-purge.md
> adr documenting purge and options

- doc/adr/0009-js-idle-heartbeat.md
> adr documenting the idle_heartbeat feature for consumers

- server/events.go
- server/events_test.go
- server/jwt.go
On export/import a header was inserted which broke parsing of the
message.
Fixed unit test broken by .beta in version
> [fixed] header handling in system services

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_test.go
- server/norace_test.go
- server/stream.go
> [FIXED] Use of sync.Pool for filestore could cause msg corruption.

- README.md
- server/const.go
> Release v2.3.2

- server/jetstream_api.go
> Fix for #2352

- server/reload.go
Resolves #2272
- Provide a public interface to Reload() the server from an Options struct instead of a changed config file. This is useful when embedding.
Testing to be completed (and commits squashed) once appropriately defined by other contributors
This is a minor addition
> [ADDED] ReloadOptions() for embedded cases

- server/consumer.go
- server/errors.json
- server/jetstream_errors_generated.go
> remove duplicate error

- server/consumer.go
> fix error replacements in consumer validation

- server/consumer.go
- server/jetstream_test.go
> Off by one bug (surprise) that would skip first new message on deliver last per subject.

- server/consumer.go
- server/jetstream_test.go
Now we just let it fire as normal and it will be canceled or not as needed.
Resolves #2392 
> Fix for #2392. We were not resetting the pending timer properly during a stream purge.

- go.mod
- go.sum
- vendor/github.com/nats-io/jwt/v2/header.go
- vendor/modules.txt
> Update go.mod JWT reference to latest release

- README.md
- server/const.go
> Release v2.3.3

- server/consumer.go
- server/filestore.go
- server/jetstream_cluster_test.go
> Various bug fixes and improvements to clustered filestore consumer stores.

- server/consumer.go
- server/jetstream_cluster_test.go
- server/jetstream_test.go
- server/memstore.go
> Fix for initial pending and DeliverLastPerSubject

- README.md
- server/const.go
> Release v2.3.4

- server/consumer.go
- server/stream.go
> [FIXED] #2416

- server/consumer.go
- server/jetstream_test.go
> Fix for #2423

- server/consumer.go
- server/jetstream_test.go
> Make sure PushActive is nil for pull consumers

- server/events_test.go
- server/filestore_test.go
- server/monitor.go
- server/norace_test.go
> Account connz should be client and leaf connections only by default.

- server/jetstream_cluster.go
> Add in warn for error on catchup of a stream

- server/filestore.go
- server/jetstream_test.go
> When we expired all messages on a restart we did not properly setup lmb.

- server/filestore.go
- server/jetstream.go
> Add in additional checks for failures during filestore encryption.

- server/jetstream_test.go
- server/stream.go
> Use append in case pubAck is larger than stack []byte

- go.mod
- go.sum
- server/events.go
- server/jetstream.go
- server/norace_test.go
- vendor/github.com/klauspost/compress/s2/README.md
- vendor/github.com/klauspost/compress/s2/decode.go
- vendor/github.com/klauspost/compress/s2/decode_other.go
- vendor/github.com/klauspost/compress/s2/encode.go
- vendor/github.com/klauspost/compress/s2/encode_all.go
- vendor/github.com/klauspost/compress/s2/encode_amd64.go
- vendor/github.com/klauspost/compress/s2/encode_best.go
- vendor/github.com/klauspost/compress/s2/encode_better.go
- vendor/github.com/klauspost/compress/s2/encode_go.go
- vendor/github.com/klauspost/compress/s2/encodeblock_amd64.go
- vendor/github.com/klauspost/compress/s2/encodeblock_amd64.s
- vendor/github.com/klauspost/compress/s2/s2.go
- vendor/modules.txt
> Add in optional compression schemes for Accept-Encoding on server API.

- server/filestore.go
- server/jetstream_test.go
- server/memstore.go
> Consumer num pending fixes for multiple matches and merging.

- server/events.go
> [fixed] error print on re adding existing system import

- server/jetstream_cluster_test.go
- server/leafnode.go
> Make sure to suppress dupes on JS deny all for system account

- server/sublist.go
> [FIXED] memory leak for queue subscription

- server/mqtt_test.go
Creating a stream will become idempotent, so assuming that we
should try to transfer the old session streams only on success
will no longer work.
Added a test that checks that "stream" list is queried only once
which means transfer was attempted only once after the second
cluster restart and new connection.
> MQTT add test to check for idempotent session stream creation.

- server/jetstream.go
- server/monitor_test.go
@wallyqs this probably needs to make it into prometheus
> Exposing reserved memory in jsz/varz

- README.md
> Release v2.6.1

- server/filestore.go
> Make sure wp is > len(cache.buf)

- server/consumer.go
- server/jetstream_cluster.go
- server/norace_test.go
- server/stream.go
> Direct consumers used for mirroring should not be affected by max consumers limits

- server/norace_test.go
> Fix corrupt wal test that was flapping

- server/jetstream.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
Improves handling of our of resources from an account level, including stream out of band catchup.
> Improve handling when exceeding account resources.

- server/accounts.go
- server/events.go
- server/events_test.go
- server/jetstream_cluster_test.go
Question, what's the expected influence of JS on conn count?
> [FIXED] Internal connections were counted toward account's max connections (client or leaf)

- server/const.go
- server/events.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/monitor.go
- server/raft.go
> Adjust cluster size on cold start in mixed mode

- server/jetstream_cluster_test.go
Added this unit test to test something and it worked.
Committing it as we don't have a test where source/mirror are not neighbors.
> added unit test to test stream source/mirror cross different domains

- server/events.go
this is what already happens in `zreq`
Basically the message contains header, and they need to be striped before unmarshal.
> [fixed] missing support for header in some request handler

- server/jetstream_cluster_test.go
- server/stream.go
Messages published with the rollup header will place the new message onto the stream and purge all others based on subject, or the complete stream.
> Rollup functionality.

- server/jetstream_cluster_test.go
- server/stream.go
> Fix for rollups and filtered purge

- server/filestore.go
- server/jetstream_test.go
Upon server restart a server would set the check expiration to the configured amount vs delta of next to expire.
Resolves #2662 
> [FIXED] Messages not expiring properly after server restart #2662.

- server/jetstream_api.go
- server/jetstream_cluster.go
- server/jetstream_cluster_test.go
- server/norace_test.go
- server/stream.go
> [FIXED] Duplicate stream create returned wrong response type #2658

- server/jwt_test.go
> Altered jwt tests to not use localhost and prefixed tests with TestJWT

- server/client.go
- server/errors.go
- server/opts.go
- server/opts_test.go
- server/reload.go
> Add in max_sub_tokens support

- server/jetstream.go
> Fix for race on js.cluster status

- README.md
- server/const.go
> Release v2.6.4

- server/jetstream.go
> Undo race fix which could cause deadlock

- server/jetstream_test.go
- server/memstore.go
> [FIXED] Bug in memstore when setting max msgs per subject to 1.

- README.md
- server/const.go
> Release v2.6.5

- server/const.go
- server/consumer.go
- server/filestore.go
- server/jetstream_cluster.go
- server/memstore.go
- server/stream.go
> [FIXED #2706] - Only utilize full state with deleted details when necessary.

- server/consumer.go
- server/errors.json
- server/jetstream_errors_generated.go
- server/jetstream_test.go
- server/stream.go
> Stream valid subjects

- server/jetstream_test.go
- server/stream.go
> prevent stream update to add subjects to mirrors

- server/jetstream_cluster.go
Also align stream and consumer timeouts.
> Aligning timeout to be shorter than 5 second cli default

- README.md
- server/const.go
> Release v2.6.6

- server/raft.go
If a node fell behind, when catching up with the rest of the
cluster, it is possible that a lot of append entries accumulate
and the server would print warnings such as:
```
[WRN] RAFT [jZ6RvVRH - S-R3F-CQw2ImK6] <some number> append entries pending
```
It would then continously print the following warning:
```
AppendEntry failed to be placed on internal channel
```
When that happens, this node would always be shown with be running the
same number of operations behind (using `nats s info`) if there are
no new messages added to the stream, or an increasing number of
operations if there is still activity.
> [FIXED] JetStream: stream blocked recovering snapshot

- server/jetstream_test.go
This was me trying to double check that interest across stream imports worked correctly.
> Added test to show cross account interest for push consumers works.

- main.go
- server/accounts.go
- server/accounts_test.go
- server/opts.go
- server/server.go
> Added in ability to have account limits configured in server config.

- server/server.go
s.fetchAccount should not be used for the system account as it creates a new struct.
Changed to update in place in one location.
The other one I changed to lookup.  (In this location the system account will be fixed up a few lines further down.
> Fixed system account issue where the wrong struct got updated

- server/jetstream.go
- server/jetstream_cluster.go
Have seen this one a few times trigger race detector.
> Avoid race condition

- go.mod
- go.sum
- server/accounts.go
- server/jwt_test.go
- vendor/github.com/nats-io/jwt/v2/account_claims.go
- vendor/github.com/nats-io/jwt/v2/creds_utils.go
- vendor/github.com/nats-io/jwt/v2/decoder_account.go
- vendor/modules.txt
updates jwt library to pick up last commit on main.
also test if value is set.
> [Adding] support for JS MaxBytesRequired

- server/server.go
Make the http monitoring endpoint available before starting JetStream to be able to monitor whether it is available during startup and recovery of streams.
> Start monitoring before JetStream during startup.

- README.md
- server/const.go
> Release v2.7.0

- README.md
- server/const.go
> Release v2.7.1

- .goreleaser-nightly.yml
- docker/Dockerfile.nightly
> Fix nightly to have proper git commit and move to Go 1.17

- README.md
- server/const.go
> Release v2.7.2

- server/consumer.go
- server/jetstream_test.go
> Fixed flow control stall under specific conditions of message size.
